### DISCUSSION TITLE
How to hook a sidecar to a VM?

### DISCUSSION THREAD

**Discussion by Javier-VL** [harvester/harvester#7175] [Q&A]
Following this discussion 
https://github.com/harvester/harvester/issues/4324

I want to be able to  modify SMBIOS system information

**Comment by m-ildefons** [comment]
Hi @Javier-VL ,

sorry for late reply. I messed around with the sidecar-shim feature just last week for the first time.

Let me preface this by saying that the sidecar feature is at the moment not supported. Meaning follow these directions at your own risk.

Step one is to enable the sidecar feature gate by editing the `Kubevirt.kubevirt.io/v1` object in the `harvester-system` namespace.
Add `Sidecar` to the list of feature gates:
```
[...]
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - Sidecar
[...]
```

Step two would be to write your sidecar hook and put it into a config map, or build a custom sidecar container image. I'm not going to cover this, since it's already covered in the KubeVirt documentation. Particularly for SMBIOS information, there is an [example](https://github.com/kubevirt/kubevirt/tree/main/cmd/sidecars/smbios)

Then you can add sidecar-shim containers, by editing the YAML that defines the VM.
Assuming you create a new VM, you can edit the YAML manifest by clicking the `Edit as YAML` button at the bottom of the page:

![](https://docs.harvesterhci.io/assets/images/create-vm-volumes-e8e820f4a3e9af9ff1ab1bb36e475a21.png)

It is important that you add the annotations to the *VMI template*, not to the VM object directly!

```
[...]
spec:
  template:
    metadata:
      annotations:
        hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha2"], "image": "registry.opensuse.org/kubevirt/sidecar-shim:1.4.0.3.224", "configMap": {"name": "my-hook-cm","key": "my-hook.sh", "hookPath": "/usr/bin/onDefineDomain"}}]'
[...]
```

More information can be found here:
https://kubevirt.io/user-guide/user_workloads/hook-sidecar/#sidecar-shim-container-image
Particularly, how the config maps need to be set up and what the hooks inside the sidecar-shim container will need to do.

Hope this helps.
