### DISCUSSION TITLE
Harvester host SSH key

### DISCUSSION THREAD

**Discussion by DamyanKolev** [harvester/harvester#8248] [Q&A] [answered]
Hello,
I'm new to working with Harvester and I have a question: after Harvester is already installed and I have SSH access using a password, is it possible to add an SSH key for authentication and disable password-based login?

Thank you in advance!

**Comment by ihcsim** [comment, marked as answer]
You can do that by using the `CloudInit` CRD following the steps at https://docs.harvesterhci.io/v1.5/advanced/cloudinitcrd/. This is YAML I used in my own testing:

```yaml
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-config
spec:
  matchSelector: 
    harvesterhci.io/managed: "true" # apply to all harvester nodes
  filename: 99-ssh-config
  contents: |
    stages:
      network:
      - name: "add ssh key"
        authorized_keys:
          rancher:
          - <your_pub_key>
      - name: "disable password login"
        commands:
        - sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
        - systemctl restart sshd
  paused: false
```

The nodes will need to be rebooted following the changes.
