### ISSUE TITLE
Zero downtime upgrade

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1022]
The epic issue to track all upgrade-related issues.

## pre-1.0.0 dependencies
- [ ] https://github.com/longhorn/longhorn/issues/3234 (Enhancement included in `v1.2.3-rc1`)
- [x] https://github.com/harvester/harvester/issues/1521
- [x] https://github.com/rancher/rancher/issues/35464 (To eliminate double draining operation)
- [x] https://github.com/rancher-sandbox/cOS-toolkit/issues/928

**Comment by yasker** [comment]
Unfortunately, we don't have enough time to finish the upgrade support in v0.3.0. Move to v1.0.0.

**Comment by bk201** [comment]
For design doc and discussions, please head to https://hackmd.io/@bk201/H1rTAGaLt

**Comment by bk201** [comment]
See this issue when upgrading a controller node today: https://github.com/harvester/harvester/issues/1521

**Comment by bk201** [comment]
**Update**
Note I found it's not possible to test a master ISO due the the `rancher/harvester-upgrade` image for a dev build is not published.
Currently, we need a hack like https://github.com/bk201/harvester-installer/commit/040fb91f7aff0b77ecf3083f4c928acf9ff680f4 to include the image in a testing ISO.


**Test plan to upgrade from 1.0.0-rc2 to latest mater**

- Download master ISO and put it in an HTTP server or use the master ISO URL directly
- Get sha512 sum of the ISO.
- Create a version resource. This pretends there is a new upgrade. Adjust the `isoChecksum` and `isoURL` below. Keep the other fields.
```
cat > versions.yaml <<EOF
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: 1.0.2
  namespace: harvester-system
spec:
  isoChecksum: 2765d89e5e8024347c81d36cc84b7168bf358a3a2f4da0c63164ad834a94bcbbaa13af4900aad4caa0a27550e4b4db5bf2c4726daa88664378e0c581a79ad2cb
  isoURL: http://10.10.0.1/harvester/harvester.iso
  minUpgradableVersion: 0.3.0
  releaseDate: "20211231"
  tags:
  - dev
  - test
EOF
```

```
kubectl create -f versions.yaml
```

- Refresh the GUI, there should be a new upgrade notification on the dashboard page (first page). Do an upgrade.
- How to verify
  - First, identify the master version. Mount the master ISO and see the `harvester-release.yaml` file. This is the version that will be upgraded. e. g.,
  ```
        harvester: b9613f9-dirty
        harvesterChart: 0.0.0-dev
        os: Harvester ce1368d-dirty
        kubernetes: v1.21.7+rke2r1
        rancher: v2.6.3-rc4
        monitoringChart: 100.0.0+up16.6.0
  ```
  - Verify the Harvester version. The version can be found at the bottom-left side of GUI. It should be identical to the version in `harvester: ` field.
  - Verify the OS versions: `cat /etc/os-release` . `PRETTY_NAME` should be identical to the value of `os: ` field. A easier way to verify all nodes at once: `kubectl get nodes -o json | jq '.items | map([.metadata.name, .status.nodeInfo.osImage])'`
  - Verify the RKE2 version: `kubectl get nodes`. The `VERSION` should be identical to the value of `kubernetes: ` field.
