### ISSUE TITLE
[Doc] Add netwrok config of the Harvester configuration doc

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1023]
**Is your feature request related to a problem? Please describe.**
Add network config of the Harvester configuration doc

**Describe the solution you'd like**
Note: All fields are required for static, only interface and method is requried for DHCP
```
install:
  networks:
    - interface: eth0
      method: static #static/dhcp
      ip: 172.16.10.1
      subnetMask: 255.255.0.0
      gateway: 172.16.0.1
      dnsNameservers:
        - 114.114.114.114
        - 8.8.8.8
```
needed for both v0.2.0 and dev version
