### ISSUE TITLE
add custom default label when creating the VM from the harvester ui

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#103]
**Description:**
add custom default label when creating the VM from the harvester UI

```
kind: VM
metadata:
  labels:
    harvester.cattle.io/creator: harvester # need to hide in the UI label
spec:
  metadata:
    labels:
      harvester.cattle.io/creator: harvester
      harvester.cattle.io/vmname: name
  domain:
```
