### ISSUE TITLE
[Question] Why can only some Harvester nodes transit to a LoadBalancer svc located on a VLAN segmented K3s cluster deployed on top of Harvester? And the Harvester node that can, changes on rebooting the Harvester node that cannot.

### ISSUE THREAD

**Issue by larssb** [harvester/harvester#1044]
> Starting of. Bare with me, this question comes with quite the context. No way around it.

# The question

If I deploy Pod workloads via e.g. `Kind: Pod` or `Kind: Deployment` directly on-top of Harvester. Instead of deploying a Kubernetes flavor cluster on top of Harvester and then on that cluster deploy Pod workloads - do I then have to configure the `k8s.v1.cni.cncf.io/networks:` annotation on the deployed Pod's, with a `default-route` specification, setting the `default-route` to the GW IP matching the CNI network interface on the Harvester hosts? Found via SSH'ing into a Harvester host and executing `ip a`.

So in my Harvester cluster:

```txt
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 62:74:4f:17:4a:0a brd ff:ff:ff:ff:ff:ff
    inet 10.52.1.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::6074:4fff:fe17:4a0a/64 scope link 
       valid_lft forever preferred_lft forever
7: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 16:f9:28:16:12:62 brd ff:ff:ff:ff:ff:ff
    inet 10.52.1.1/24 brd 10.52.1.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::14f9:28ff:fe16:1262/64 scope link 
       valid_lft forever preferred_lft forever
```

> NIC '7'

and then `ip route` for further confirmation:

```txt
harvester-host-b [~]# ip route
default via 192.168.10.1 dev eth1 
10.52.0.0/24 via 10.52.0.0 dev flannel.1 onlink 
10.52.1.0/24 dev cni0 proto kernel scope link src 10.52.1.1 
10.52.2.0/24 via 10.52.2.0 dev flannel.1 onlink 
127.0.0.0/8 dev lo scope host 
192.168.10.0/23 dev eth1 proto kernel scope link src 192.168.10.23 
192.168.10.0/23 dev harvester-br0 proto kernel scope link src 192.168.10.22 
192.168.10.1 dev harvester-br0 scope link
```

Because if I don't specify the `default-route` - in this case `10.52.2.1` the HAProxy `Deployment` would not be able to reach the HAProxy instance deployed to the K3s cluster. E.g. `traceroute` would not be able to find the path to the ip set on the LoadBalancer svc covering the HAProxy instance on K3s. And `nc -v -z IP_OF_LOAD_BALANCER_SVC_ON_K3s` would simply timeout.

The weirdest thing though is that if I deploy `Kind: Pod` - a simple Pod such as [this one](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment) that Pod gets the correct GW IP and can `traceroute` and `nc` to the HAproxy instance on the K3s cluster. What is up with that?

# More context

So yes I might not be using Harvester in a way that is the "straight down the road" use case. For a @yasker comment - see [this Slack comment/discussion](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1626804521332700)

I'm doing this basically because my FW/Router do not support NAT'ing on SNI. I therefore have to have a management Kubernetes cluster to host a load balancer workload, so that I can NAT to that workload in the FW and (I'm using the [HAProxy Kubernetes ingress-controller](https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress) that load balancer is then forwarding the request based on an Ingress obj. to the K3s cluster deployed on-top of Harvester (as KubeVirt VM's).

# Technical info

The `Ingress`, `LoadBalancer` svc and `Endpoint` on the Harvester cluster, that the HAProxy ingress controller uses to load balance incoming requests to the K3s deployed HAProxy instance.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/ssl-passthrough: "true"
    kubernetes.io/ingress.class: "haproxy"
  name: git-hospites-cloud-to-int-cluster
  namespace: hospites
spec:
  rules:
  - host: git.hospites.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: git-hospites-cloud-to-int-cluster
            port:
              number: 443
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: git-hospites-cloud-to-int-cluster
  namespace: hospites
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: git-hospites-cloud-to-int-cluster
  namespace: hospites
subsets: 
  - addresses:
      - ip: 192.168.60.26
    ports:
      -  name: https
         port: 443
         protocol: TCP
```

All fine and dandy as the Harvester cluster deployed HAProxy instance picked up the service. However, HAProxy's check fails because it cannot find a route to the `LoadBalancer` svc on the K3s cluster.

---

Looking forward to hearing from someone knowing the network details of Harvester better than I do.

Thank you very much 😀
