### ISSUE TITLE
[FEATURE] Migrate harvester api actions to standardized k8s mechanism

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1078]
**Is your feature request related to a problem? Please describe.**
We will need to migrate the existing harvester API actions to the standardized k8s api mechanism, so users who deal with the vanilla k8s API can also use those customize API actions.  

**Describe the solution you'd like**
e.g using the k8s API subresources, but will need further investigation.

**Comment by gitlawr** [comment]
Actions being used:
VM:
- start
- stop
- restart
- ejectCDRom
- pause
- unpause
- migrate
- abortmigration
- backup
- restore
- createTemplate

Node:
- enableMaintenanceMode
- disableMaintenanceMode
- cordon
- uncordon

**Comment by Yu-Jack** [comment]
@bk201  Just spent some time checking this. To be more clear, we should use `apiservice` to replace. Let me use kubevirt as example to explain this.

Let's say, if we try to start or stop the VM, we could see there are requests printed in virt-api.
```
{"component":"virt-api","contentLength":0,"level":"info","method":"PUT","pos":"filter.go:47","proto":"HTTP/1.1","remoteAddress":"192.168.122.75","statusCode":202,"timestamp":"2024-04-26T06:32:28.770904Z","url":"/apis/subresources.kubevirt.io/v1/namespaces/default/virtualmachines/test/start","username":"-"}
{"component":"virt-api","contentLength":0,"level":"info","method":"PUT","pos":"filter.go:47","proto":"HTTP/1.1","remoteAddress":"192.168.122.75","statusCode":202,"timestamp":"2024-04-26T06:40:44.729912Z","url":"/apis/subresources.kubevirt.io/v1/namespaces/default/virtualmachines/test/stop","username":"-"}
```

The URL is `/apis/subresources.kubevirt.io/v1/namespaces/default/virtualmachines/test/start` or `/apis/subresources.kubevirt.io/v1/namespaces/default/virtualmachines/test/stop`, then KubeVirt will [handle these requests by different routes](https://github.com/kubevirt/kubevirt/blob/ca94b81c667ab4cee70e7c009a5a67e2386d2c1d/pkg/virt-api/api.go#L249-L271).

This uses Aggregated API to do that. In order to use that, we need to define a new resource called `apiservice`, here is an example KubeVirt defined. 

```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/component: kubevirt
    app.kubernetes.io/managed-by: virt-operator
    kubevirt.io: virt-api-aggregator
  name: v1.subresources.kubevirt.io
spec: 
  group: subresources.kubevirt.io
  groupPriorityMinimum: 1000
  service:
    name: virt-api
    namespace: harvester-system
    port: 443
  version: v1
  versionPriority: 15
```

So, you could see the group matches the URL mentioned above which follows the kubernetes rules.

Some references

- [difference between CRD and Aggregated API](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility)
- [sample-apiserver](https://github.com/kubernetes/sample-apiserver/blob/master/README.md)
