### ISSUE TITLE
unable to uninstall harvester chart

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#115]
unable to uninstall harvester due to incorrect resource config
```
$helm list -a

NAME            	NAMESPACE       	REVISION	UPDATED                                	STATUS      	CHART          	APP VERSION
harvester-system	harvester-system	2       	2020-09-03 14:36:05.944463616 +0000 UTC	uninstalling	harvester-0.1.0	0.1.x
```
run `$helm delete harvester-system`  -n harvester-system returns error
```
Error: warning: Hook pre-delete harvester/templates/job.yaml failed: Job.batch "harvester-pre-delete" is invalid: [spec.template.spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit, spec.template.spec.containers[0].resources.requests: Invalid value: "256Mi": must be less than or equal to memory limit]
```

and check its generate YAML via `$helm get all harvester-system  -n harvester-system  | less`

```
# Source: harvester/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  # NB(thxCode): name should not be customized as below:
  # name: harvester-system-pre-delete
  # because we can easily confirm this resource from the corresponding namespace.
  name: harvester-pre-delete
  labels:
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: harvester-0.1.0
    app.kubernetes.io/version: "0.1.x"
    helm.sh/release: harvester-system
    app.kubernetes.io/part-of: harvester
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: harvester-pre-delete
      labels:
        helm.sh/release: harvester-system
        app.kubernetes.io/part-of: harvester
        app.kubernetes.io/name: pre-delete
        app.kubernetes.io/component: job
    spec:
      # NB(thxCode): reuse the "harvester" ServiceAccount under the same namespace.
      serviceAccountName: harvester
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: pre-delete
          image: bitnami/kubectl:1.18.6
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
          args:
            - "-c"
            - "echo '[INFO] deleting kubevirt ...'; kubectl delete kubevirt --wait --all; echo '[INFO] deleting cdi ...'; kubectl delete cdi --wait --all; exit"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 256Mi
```
