### ISSUE TITLE
[BUG] VM only shows the IPV6 address

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1176]
**Describe the bug**
When the VM has been assigned with both IPV4 and IPV6 addresses, by default the VMI will only store the IPV6 address, it should store both.
```
 conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-08T10:51:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  guestOSInfo: {}
  interfaces:
  - ipAddress: fd31:f874:bf29:0:14df:8ff:fefe:a2bf
    ipAddresses:
    - fd31:f874:bf29:0:14df:8ff:fefe:a2bf
    mac: 16:df:08:fe:a2:bf
    name: default

==== VM info ====
ubuntu@vmtest1:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 16:df:08:fe:a2:bf brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.161/16 brd 172.16.255.255 scope global dynamic enp1s0
       valid_lft 83428sec preferred_lft 83428sec
    inet6 fd31:f874:bf29::c0b/128 scope global dynamic noprefixroute
       valid_lft 40230sec preferred_lft 40230sec
    inet6 fd31:f874:bf29:0:14df:8ff:fefe:a2bf/64 scope global mngtmpaddr noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::14df:8ff:fefe:a2bf/64 scope link
       valid_lft forever preferred_lft forever
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```

**To Reproduce**
1. create a VM e.g with ubuntu focal image 
2. set the first network to use VLAN network
3. create the VM and wait for it to be ready.

**Expected behavior**
- the VMI should include both the IPV4 and IPV6 address

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by johnliu55tw** [comment]
@guangbochen I cannot reproduce this issue on my setup (Harvester deployed as a KVM VM). Does the VM has guest agent installed?

Without the guest agent, the VMI has no `ipAddresses` info:
```
  guestOSInfo: {}
  interfaces:
  - mac: ea:9c:c7:ea:64:47
    name: default
```

With the guest agent, both IPv4 and IPv6 are there:
```
  guestOSInfo:
    id: ubuntu
    kernelRelease: 5.4.0-84-generic
    kernelVersion: '#94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021'
    name: Ubuntu
    prettyName: Ubuntu 20.04.3 LTS
    version: "20.04"
    versionId: "20.04"
  interfaces:
  - interfaceName: enp1s0
    ipAddress: 192.168.122.52
    ipAddresses:
    - 192.168.122.52
    - fe80::605c:67ff:fee2:aeb6
    mac: 62:5c:67:e2:ae:b6
    name: default
```
