### ISSUE TITLE
UI support for unmount cd-rom

### ISSUE THREAD

**Issue by aiwantaozi** [harvester/harvester#123]
support for unmount cd-rom disk

```
 spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: isodisk1
          - bootOrder: 1
            disk:
              bus: virtio
            name: isodisk2
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
```

for CD-ROM type show a checkbox before it, and an eject button, after the user selects some CD-ROM and click the eject button, pop out a confirm dialogue.

eject CD-ROM
![1599622199783](https://user-images.githubusercontent.com/5936271/92551121-d1a94d00-f28f-11ea-8d2e-e9ab17efd647.jpg)

confirm dialogue:
```
Eject CD-ROM
Are you sure you want to eject CD-ROM name1, name2 ...., this action will restart the virtual machine
```
