### ISSUE TITLE
[BUG] Calico veth interfaces are mistakenly deleted 

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1259]
**Describe the bug**

When using the network interface with index 3 as the VLAN interface, the calico veth interfaces will be deleted atypically. 

**To Reproduce**
1. Set up a Harvester cluster with two NICs. Generally, the index of the second NIC is 3.
2. Enable VLAN with default NIC whose index is 3.

**Expected behavior**

 Calico veth interfaces should not be deleted.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head 0922
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtual

**Additional context**

**Comment by yaocw2020** [comment]
Workaround for the existing cluster:
- Disable the VLAN network
- Execute the command `kubectl edit nn` to edit all the nodenetwork CR and delete the finalizers.
```
apiVersion: network.harvesterhci.io/v1beta1
kind: NodeNetwork
metadata:
  creationTimestamp: "2021-09-22T09:11:36Z"
  finalizers:
  - wrangler.cattle.io/harvester-vip-controller
  - wrangler.cattle.io/harvester-nodenetwork-controller
  generation: 3
```
- Reboot the machines.
- Update harvester-network-controller daemonset to the master-head version.
- Re-enable the VLAN network.
