### ISSUE TITLE
telnet vm IP failed when using masquerade pod network

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#129]
telnet vm IP failed when using masquerade pod network

**Comment by guangbochen** [comment]
firstly `ipv4.ip_forward` should be enabled of the CNI config of the VM k8s cluster https://github.com/rancher/harvester/issues/94, additionally, we should allow the user to config the ports when creating the VM in the UI.

> In masquerade mode, KubeVirt allocates internal IP addresses to virtual machines and hides them behind NAT. All the traffic exiting virtual machines is "NAT’ed" using pod IP addresses. A virtual machine should be configured to use DHCP to acquire IPv4 addresses.
To allow traffic into virtual machines, the template ports section of the interface should be configured as follows.

```
kind: VM
spec:
  domain:
    devices:
      interfaces:
        - name: red
          masquerade: {} # connect using masquerade mode
          ports:
            - name: HTTP
               port: 80 # allow incoming traffic on port 80 to get into the virtual machine
               protocol: TCP
            - port: 3306 # e.g, MySQL DB
  networks:
  - name: red
    pod: {}
```
