### ISSUE TITLE
[Question] Is there a way to keep ip address of vms?

### ISSUE THREAD

**Issue by joy717** [harvester/harvester#1317]
Hi..
The vm's IP will be changed after restarting. 
Is there a way to keep the IP address in the vm's lifecycle?
Even the vm is stopped, the IP should be kept until it's destroyed.

**Comment by gitlawr** [comment]
You can use the vlan networks: https://docs.harvesterhci.io/v0.2/harvester-network/#vlan

**Comment by joy717** [comment]
Thanks gitlawr
Is there an example or doc?
I don't know how to keep the vm's IP within the whole lifecycle. 
/sad

**Comment by yaocw2020** [comment]
You can set a static IP by cloud-init config. For example, 
```
network:
  version: 1
  config:
    - type: physical
      name: enp1s0
      subnets:
         - type: static
           address: 192.168.178.2/24
           gateway: 192.168.178.1
```
