### ISSUE TITLE
[BUG] bond_options parameter not working

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1323]
Harvester 0.3.0-rc1

According to the documentation the following configuration should be used to configure the bond mode to `balance-rr` :

```
install:
  mode: create
  networks:
    harvester-mgmt:       # The management bond name. This is mandatory.
      interfaces:
      - name: ens5
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-rr
```

This has no effect.  In order to successfully set the bond interface mode the configuration has to modified by changing `bond_options` to `bond_option`:

```
      method: dhcp
      bond_option:
        mode: balance-rr
```
