### ISSUE TITLE
[BUG] Installation fails if bonding interface is configured without IP and gateway

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1325]
Harvester v0.3.0-rc1

**Steps to reproduce**

Install Harvester with a network configuration that defines a bonding interface for VLAN networking without assigning an IP address. Note, that since the bonding interface is merely used for VLAN trunking, assigning an IP address to that interface is neither required nor would it provide any value.

Example:

```
harvester-mgmt:
      interfaces:
        - name: ens3f2
      method: dhcp
vlan-bond0:
      interfaces:
        - name: ens3f3
        - name: ens3f4
      method: static
      bond_options:
        mode: 802.3ad
```

**Result**

> Error: must specify IP in static method
