### ISSUE TITLE
cloud-init config and design enhancement

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#136]
**Description*:*
Need to review the current design of cloud-init config and provide the advanced configuration that allows arbitrary input, 

For some existing configuration like ssh-key and hostname that can be configured by the UI can be overwritten by the cloud-init config but don't need to show it again.

**Comment by guangbochen** [comment]
will change the current design as below: cc @WuJun2016 @gitlawr @yasker 
1. bring back cloud-config with user data input(if the user specify the hostname in the user-data it will overwrite the one defined in the UI)
2. add [network data config](https://kubevirt.io/user-guide/#/creation/cloud-init?id=cloud-init-network-config-as-clear-text), and `#cloud-config` is always required of the user-data config.
3. add YAML format validation to both user-data and cloud-data configs.
4. add the YAML style design of the user-data and cloud-data input. (nice to have)
![image](https://user-images.githubusercontent.com/4569037/93068471-175e7f00-f6af-11ea-9281-825e43cae243.png)


**small text description:**
1. You can specify user data to configure an instance or run a configuration script during launch. If you launch more than one instance at a time, the user data is available to all the instances in that reservation. [Learn more](https://cloudinit.readthedocs.io/en/latest/topics/examples.html)
2. The network-data configuration allows you to customize the instance’s networking interfaces by assigning subnet configuration, virtual device creation (bonds, bridges, vlans) routes and DNS configuration. [Learn more](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html)

**Comment by guangbochen** [comment]
validation steps:
1. create a new VM e.g. using ubuntu cloud image
2. set the hostname to `foo.bar`
3. config both the user data and network data as below:
```
#cloud-config
password: root
chpasswd: { expire: False }
ssh_pwauth: True

=====

network:
  version: 1
  config:
  - type: physical
    name: eth1
    subnets:
      - type: dhcp
```

4. ssh to the VM with above defined passwd and check the second network interface is up as expected.

**Comment by DoNotSayYes** [comment]
**Validation steps:**
1. create a new VM e.g. using ubuntu cloud image
2. set the hostname to `foo`
3. config both the user data and network data as below:
```
#cloud-config
password: root
chpasswd: { expire: False }
ssh_pwauth: True

=====

network:
  version: 1
  config:
  - type: physical
    name: eth1
    subnets:
      - type: dhcp
```

**Result:**
UI is not passing the network config in API request. @WuJun2016 
![image](https://user-images.githubusercontent.com/57614736/94546236-300a8f80-0280-11eb-955c-c8a500235c0f.png)
