### ISSUE TITLE
[BUG] Rancher monitoring stack is crashing on Harvester guest cluster 

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1369]
Rancher 2.6-rc11
Harvester 0.3.0-rc1

**To Reproduce**
1. Import Harvester in Rancher
2. Provision RKE2 cluster using Harvester node driver and with Harvester cloud provider enabled
3. Deploy Rancher monitoring chart from application catalog
3a. Make sure to enable "Persistent Storage for Prometheus" option and selecting Harvester storage class

**Expected behavior**
Prometheus is deployed without error

**Actual behavior**
Prometheus pods are stuck in CrashLoopBackOff with error `open /prometheus/queries.active: permission denied`

**Additional Info**

It seems that the expected permissions on the volume (UID: 1000) are not set correctly.
Temporary workaround is to modify the `securityContext` of the Prometheus pod and changing `runAsUser` from `1000`to `0`.

The root cause for this issue was fixed in the Longhorn CSI but probably not in the Harvester CSI: https://github.com/longhorn/longhorn/issues/2964#issuecomment-910969543

**Comment by yasker** [comment]
@guangbochen Can you check if we need to update the node driver for this?

**Comment by yasker** [comment]
FYI: Here is the fix from Longhorn side. It has fixed both CSI driver and storage class. https://github.com/longhorn/longhorn-manager/pull/1026

**Comment by gitlawr** [comment]
The workaround is to create and use another storageclass with fstype parameters, or append the default-fstype arg to the csi-provisioner container as shown in @janeczku's PRs.
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harvester2
provisioner: driver.harvesterhci.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: "ext4"
```

We need to update the harvester-csi-driver chart, then update rke2-chart, rke2, and kontainer-driver-metadata.
