### ISSUE TITLE
[BUG] VM unable to be cloned which was created from existing volume

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1374]
### Describe the bug
This issue probably is a cascading failure from #1372

** VM's test case No.60

### To Reproduce
1. Follow steps of #1372
2. perform clone on the VM
3. error message shown

### Expected behavior
VM created from existing volume should able to be cloned.

## Environment:
 - Harvester ISO version: **master-a4528869-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360** 3nodes

### Additional context
N/A

**Comment by yasker** [comment]
@lanfon72 What's the error message you mentioned in the steps?

**Comment by lanfon72** [comment]
doing reproduce then found another bug.......
Let me finish remaining test cases then I will update the error message (also the bug caught when reproducing)

**Comment by WuJun2016** [comment]
@guangbochen  I think this situation should not be cloned. When we use an existing volume to create a vm, in the clone of this vm, it will be reported that the volume has been used。

**Comment by guangbochen** [comment]
@lanfon72 It makes sense not to clone the VM with existing volumes as per volume can only be mounted to one VM, a real VM clone will be introduced via https://github.com/harvester/harvester/issues/571 and that will support the above case.

**Comment by lanfon72** [comment]
update the error message which tested on **v0.3.0**:
![image](https://user-images.githubusercontent.com/5169694/137265510-4b52acb1-5a62-4b39-9820-e27837e24629.png)

**Comment by lanfon72** [comment]
Currently clone behaviors:
VM **a** created from `img`_A_,
- modifying **a** as **a+**, clone **a+** => succeed, **b** created from **a**
- modifying **b** as **b+**, clone **b+** => succeed, **c** is created from **b** (which equals **a**)
- delete **b+** but keep volume **b+v**, create VM **c** from **b+v**, clone **c** => failed, `volume is already used`

VM **x** created from `iso` _X_,
- clone **x** => failed, `At least an image volume or an existing root-disk volume is required`
- modifying **x** as **x+**, clone **x+** => failed as above
- delete **x+**, but keep volume **x+v**, create VM **y** from **x+v**, clone **y** => failed, `volume is already used`

As a user perspective, on dashboard, it is hard to distinguish a VM is created from **img**/**iso**/**existing volume**, especially the VM created from **img**, a volume will be created for it, and _clone_ is working as normally, but nothing actually cloned.

I think we should define more explicitly, then I can update test cases to cover them.

**Comment by FrankYang0529** [comment]
I can reproduce this issue and get VM YAML as following:
1. Create a new VM `vm-original`. We have content in `harvesterhci.io/volumeClaimTemplates`.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"vm-original-disk-0-p1lkd","annotations":{"harvesterhci.io/imageId":"default/image-h2g8s"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-h2g8s"}}]'
  name: vm-original
...
spec:
  ...
  template:
    ...
    spec:
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: vm-original-disk-0-p1lkd
```
2. Delete `vm-original` but keep the root disk. Create a new VM `vm-with-root-disk`. This time, we don't have content in `harvesterhci.io/volumeClaimTemplates`.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/volumeClaimTemplates: '[]'
  name: vm-with-root-disk
...
spec:
  ...
  template:
    ...
    spec:
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: vm-original-disk-0-p1lkd
```
3. Try to create a new VM `vm-clone` by cloning VM `vm-with-root-disk`. Webhook stops the request because `vm-clone` tries to use a PVC which has already been used by `vm-with-root-disk`.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/volumeClaimTemplates: '[]'
  name: vm-clone
...
spec:
  ...
  template:
    ...
    spec:
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: vm-original-disk-0-p1lkd
```

I would suggest we leave this issue after #569. Also, we will change `clone` behavior. UI can just send a `clone` request to the backend and it will handle it. However, users can only modify VM's name when they create a VM by cloning a VM. They cannot modify other things like the current `clone` behavior. In the backend, we will create a `VMBackup` CRD with a `post-hooks` annotation like the following. After backing up VM is done, it will automatically create a `VMRestore` to create a new VM.

```
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineBackup
metadata:
  annotations:
    harvesterhci.io/post-hooks: '{"actions": [{"action": "restore-vm", params: {"name": "vm-clone"}}]}'
  name: snapshot
  namespace: default
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-with-root-disk
  volumeSnapshotClassName: "longhorn-snapshot"
```

If users want to create a new VM with data and modify other fields, they can use `VMTemplate` to handle it. This will be implemented in #571.

cc @guangbochen @bk201. WDYT? Thank you.
