### ISSUE TITLE
[FEATURE] Support configuring a VLAN at the management interface in installer config

### ISSUE THREAD

**Issue by bashofmann** [harvester/harvester#1390]
**Is your feature request related to a problem? Please describe.**
Currently you can't configure a VLAN directly at the harvester management interface, see https://docs.harvesterhci.io/v0.3/install/harvester-configuration/#installnetworks.

**Describe the solution you'd like**
Add more network configuration options to the installation options, so that you can add an additional tagged vlan to a bonded management interface.

A resulting network config could be

![network-interfaces](https://user-images.githubusercontent.com/243056/136570782-05686026-5ae1-420b-9000-09e1bdf3369b.png)

With such a routing config

![routes](https://user-images.githubusercontent.com/243056/136570903-0ea88895-6ec3-48a4-8f3e-0667204a0093.png)

The harvester vip should be attachable to the vlan

![vip_interface](https://user-images.githubusercontent.com/243056/136571163-cfb7d26c-5cf2-445a-8c8d-025877fee86d.png)

**Comment by FrankYang0529** [comment]
## Test plan

### Case 1 - No VLAN

* Set `vlan_id` as `0` or don't set it.
```
install:
# ...
  networks:
    harvester-mgmt:
      interfaces:
      - name: ens5
      method: static
      ip: 192.168.0.30
      subnet_mask: 255.255.255.0
      gateway: 192.168.0.1
      vlan_id: 0
```
```
install:
# ...
  networks:
    harvester-mgmt:
      interfaces:
      - name: ens5
      method: static
      ip: 192.168.0.30
      subnet_mask: 255.255.255.0
      gateway: 192.168.0.1
```
* Install Harvester.
* Check `harvester-mgmt` has IP `192.168.0.30` and there is no `vlan0@harvester-mgmt`.

### Case 2 - VLAN

* Set `vlan_id` as `1`.
```
install:
# ...
  networks:
    harvester-mgmt:
      interfaces:
      - name: ens5
      method: static
      ip: 192.168.0.30
      subnet_mask: 255.255.255.0
      gateway: 192.168.0.1
      vlan_id: 1
```
* Install Harvester.
* Check `vlan1@harvester-mgmt` is existent and `vlan1@harvester-mgmt` has IP `192.168.0.30`.

**Comment by FrankYang0529** [comment]
We need further PR to update network-controller-harvester. If users set VLAN on harvester-mgmt and enable vlan feature in harvester, `harvester-br0` should inherit the VLAN tag of `harvester-mgmt`.

**Comment by tjjh89017** [comment]
This feature request might need some enhancement and another implementation for mgmt vlan.
and consider network controller at the same time

**Comment by tjjh89017** [comment]
@bashofmann 
Could you help us to check with the external switch if it could have Native VLAN support?
If it could have native vlan, we could setup native vlan for your harvester-mgmt to access the network.
and setup harvester-mgmt without VLAN ID on it.

If it couldn't setup native vlan, need your help to provide more info about this. 
thanks a lot.

**Comment by tjjh89017** [comment]
Note: need to add some KB to describe the limitation.
For now, we are getting to support this feature but harvester nodes will need more that two NICs to support VM VLAN networks.
We couldn't use harvester-mgmt with tagged vlan on VM VLAN networks.
need to separate VM VLAN networks with different NIC

**Comment by tjjh89017** [comment]
@bashofmann Please take a look at the docs of [best practice](https://docs.harvesterhci.io/v1.0/networking/best-practice/overview/)
and check if users could modify the network to these settings.
thanks a lot

**Comment by bashofmann** [comment]
@tjjh89017 I'll check back with the prospect. This may take a bit of time though.

**Comment by abonillabeeche** [comment]
> Note: need to add some KB to describe the limitation. For now, we are getting to support this feature but harvester nodes will need more that two NICs to support VM VLAN networks. We couldn't use harvester-mgmt with tagged vlan on VM VLAN networks. need to separate VM VLAN networks with different NIC

Does this mean it would be possible to utilize harvester-mgmt on a VLAN if it runs on a third NIC?

**Comment by tjjh89017** [comment]
> Does this mean it would be possible to utilize harvester-mgmt on a VLAN if it runs on a third NIC?

Nope, after some research, for now we still need to configure the switch to fit the requirement.
otherwise, still need some vlan enhancement.

**Comment by tjjh89017** [comment]
wait for new VLAN design

**Comment by tjjh89017** [comment]
## test plan

### No vlan

1. config
```yaml
... omit ...
install:
  ... omit ...
  management_interface: # It will create `br-mgmt.101` as mgmt interface
    interfaces:
    - name: eth0
    - name: eth1
    method: dhcp
  ... omit ...
```

2. check mgmt-br has IP address

### vlan

1. config 
``` yaml
... omit ...
install:
  ... omit ...
  management_interface: # It will create `br-mgmt.101` as mgmt interface
    interfaces:
    - name: eth0
    - name: eth1
    method: dhcp
    vlan_id: 101
  ... omit ...
```

2. check mgmt-br.101 has IP address
