### ISSUE TITLE
[BUG] Reboot the deleted node and it will be added to the cluster again

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1497]
Related to https://github.com/rancher/rancher/issues/35258

**Comment by weihanglo** [comment]
Confirmed that this is also reproducible via Harvester dashboard.

**Comment by guangbochen** [comment]
We should consider cleaning up the Harvester node on node delete, but I just want to make sure the users are well notified as this action will wipe all the system components like rke2 and kubelet and can't be undone.
https://docs.rke2.io/install/linux_uninstall/

**Comment by weihanglo** [comment]
We encounrted a situation that we cannot rely on pod/job to execute [standard RKE2 uninstallation](https://docs.rke2.io/install/linux_uninstall/) procedure: When one deletes the node via K8s API, any further pod/job is not expected to schedule on the node.

As a result, we tried to leverage [rancher-system-agent](https://github.com/rancher/system-agent), a systemd unit, to deal with uninstallation outside K8s. However, the `Plan` structure and logic are more like implementation details which we may not want to depend on. Moreover, if the node is already shutdown, Neither can we delete node nor do do any operation on it via neither system-agent.

---

We here propose another way to resolve the issue.

1. When deleting a node via Dashboard UI, label the node as schedule-to-delete, such as `harvesterhci.io/schedule-to-delete: "true"`
2. A node controller watches that label and then does followings:
    1. Creates a job to perform the standard RKE2 uninstallation.
    2. After the uninstallation, delete the node resource as normal.
4. If the node is shutdown or not scheduable, the job won't be able to schedule. Therefore, the node will be in a `deleting` status and only after the node is booted, the job would be scheduled and executed.

There is a obvious caveat in this approach. One cannot delete prevent re-joining if they deletes the node via standard `DELETE` API, they then should label the node instead.

If aforementioned method seems not appropriate, we may just document the `node deletion` process and info users that if they want to delete a node, they should disable RKE2 systemd unit manually. This is also acceptable to me since deletion is actually a destructive operation that needs to take care of and system admin **should** read the manual.

**Comment by weihanglo** [comment]
We've tested some workarounds to resolve this issue but all went stuck.

The first attempt is leverage the finalizer feature in K8s. We added a finalizer on node and it'll spawn a job to uninstall RKE2 on the node to delete. Unfortunately there is also other logic that disconnect the node from the cluster network, so the node became `unreachable` and the pod scheduler cannot schedule any pod onto it.

The other way is abusing admission webhook. We've tried to spawn job during admission webhook of nodes, but there was still a chance that the node became tainted and disconnected from the cluster network, which resulted in unschedulable of any other new pod.

Based on previous two attempts, we cannot find an easy way to delete a node with RKE2 uninstallation (or remove the token on the node to prevent re-joining). There might exists a solution to spawn a job outside K8s but need more investiations and helps.

**Comment by lanfon72** [comment]
Unable to remove the node which will stuck on deleting.
monitoring from API:
```py
"finalizers": [ # field of metadata, fetch from https://<VIP>/v1/harvester/nodes/<deleting_node>
"harvesterhci.io/delete-node-controller",
"wrangler.cattle.io/delete-node-controller"
],
```
snapshot of dashboard:
![image](https://user-images.githubusercontent.com/5169694/144027480-32445aa8-1ac2-48e3-9cb9-52653c67adaf.png)

and the deleted node will not re-join to cluster after reboot.


Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-7a54d362-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with 3 nodes
2. login and delete one of the host
3. State of node should change to removing
4. Node should be removed in the list
5. Reboot the deleted node
6. SSH to the node, Check the file `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` should be removed
7. The node should not appear in dashboard again

**Comment by weihanglo** [comment]
@gitlawr 

That looks like what I encountered in the first place. Node becomes `NotReady` before we remove our own finalizer. Any insight?

**Comment by guangbochen** [comment]
if the `harvesterhci.io/delete-node` finalizer exists and the job's related pod is succeeded, can we just ignore and remove the node from the API directly?

**Comment by weihanglo** [comment]
> if the `harvesterhci.io/delete-node` finalizer exists and the job's related pod is succeeded, can we just ignore and remove the node from the API directly?

No. Unfortunately the node became `NotReady` before the job scheduled

**Comment by gitlawr** [comment]
Nodes become not ready when kubelet is lost, can you check the reason?

**Comment by lanfon72** [comment]
@weihanglo now it's yours again :bowing_man: 

[supportbundle_6285e994-c3c3-490b-8628-0a2334de5a49_2021-12-06T08-54-32Z.zip](https://github.com/harvester/harvester/files/7659418/supportbundle_6285e994-c3c3-490b-8628-0a2334de5a49_2021-12-06T08-54-32Z.zip)

Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-3b5fe2e0-head**
* **ui-source** Option: **Auto**

ipxe-example/settings.yaml
```yaml
---
##########################################################################
# NOTE: this is a YAML file so please pay close attention to the leading #
# spaces as they are significant.                                        #
##########################################################################

#
# harvester_iso_url
# harvester_kernel_url
# harvester_initrd_url
#
# Harvester media to install. The URL scheme can be either 'http', 'https', or
# 'file'. If the URL scheme is 'file', the given media will be copied from the
# local file system instead of downloading from a remote location.
harvester_iso_url: file:///home/lanfon/dev_src/harvester_iso/harvester-amd64.iso
harvester_kernel_url: file:///home/lanfon/dev_src/harvester_iso/harvester-vmlinuz-amd64
harvester_ramdisk_url: file:///home/lanfon/dev_src/harvester_iso/harvester-initrd-amd64
harvester_rootfs_url: file:///home/lanfon/dev_src/harvester_iso/harvester-rootfs-amd64.squashfs

#
# harvester_cluster_nodes
#
# NOTE: keep in mind that you need at least 3 nodes to make a cluster
#
harvester_cluster_nodes: 3

#
# network_config
#
# Harvester network configurations. Make sure the cluster IPs are on the same
# subnet as the DHCP server. Pre-assign the IPs and MACs for the Harvester
# nodes.
#
# NOTE: Random MAC addresses are generated with the following command:
# printf '02:00:00:%02X:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
# Thanks to https://stackoverflow.com/questions/8484877/mac-address-generator-in-python
# If any of the generated MAC addresses is in conflict with an existing one in
# your environment, please use the above command to regenerate and replace
# the conflicting one.
#
harvester_network_config:
  # Run as an airgapped environment that only has internet connectivity through an HTTP proxy.
  # The HTTP proxy runs on DHCP server using port 3128
  offline: false

  dhcp_server:
    ip: 192.170.0.254
    subnet: 192.170.0.0
    netmask: 255.255.255.0
    range: 192.170.0.50 192.170.0.130
  # Reserve these IPs for the Harvester cluster. Make sure these are outside
  # the range of DHCP so they don't get served out by the DHCP server
  vip:
    ip: 192.170.0.131
    mode: DHCP
    mac: 02:00:00:03:3D:61
  cluster:
    - ip: 192.170.0.30
      mac: 02:00:00:0D:62:E2
      cpu: 8
      memory: 16384
      disk_size: 150G
      vagrant_interface: ens5
      mgmt_interface: ens6
    - ip: 192.170.0.31
      mac: 02:00:00:35:86:92
      cpu: 4
      memory: 8192
      disk_size: 150G
      vagrant_interface: ens5
      mgmt_interface: ens6
    - ip: 192.170.0.32
      mac: 02:00:00:2F:F2:2A
      cpu: 6
      memory: 16384
      disk_size: 150G
      vagrant_interface: ens5
      mgmt_interface: ens6
    - ip: 192.170.0.33
      mac: 02:00:00:A7:E6:FF
      cpu: 4
      memory: 8192
      disk_size: 150G
      vagrant_interface: ens5
      mgmt_interface: ens6

#
# harvester_config
#
# Harvester system configurations.
#
harvester_config:
  # static token for cluster authentication
  token: token

  # Public keys to add to authorized_keys of each node.
  ssh_authorized_keys:
    # Vagrant default unsecured SSH public key
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  # password to for the `rancher` user to login to the Harvester nodes
  password: p@ssword

  # NTP servers
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org

#
# harvester_node_config
#
# Harvester node-specific configurations.
#
harvester_node_config:
  # number of CPUs assigned to each node
  cpu: 4

  # memory size for each node, in MBytes
  memory: 8192

  # disk size for each node
  disk_size: 100G

```
