### ISSUE TITLE
[BUG] NFS backups don't finish

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1536]
**Describe the bug**

When you start an NFS backup it doesn't complete
**To Reproduce**
1. Create new VM
2. Create a backup with an NFS backup target
**Expected behavior**

Backup should complete
**Support bundle**

[supportbundle_caa0bfe9-902d-45d6-bb88-9b74fe60e0eb_2021-11-10T21-27-20Z.zip](https://github.com/harvester/harvester/files/7517000/supportbundle_caa0bfe9-902d-45d6-bb88-9b74fe60e0eb_2021-11-10T21-27-20Z.zip)

**Environment:**
 - Harvester ISO version: master-119c2c48-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
The backups show as complete in Longhorn, but they don't show as finished in the list in backups. This was done to a local NFS share created on the embedded rancher using the YAML here. 
https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml
backup target was set as `nfs://longhorn-test-nfs-svc.default:/opt/backupstore`
![Greenshot 2021-11-10 13 16 59](https://user-images.githubusercontent.com/83787952/141220968-a3f990c6-8a1c-4f7a-8642-301c8819ba43.png)
![Greenshot 2021-11-10 13 17 06](https://user-images.githubusercontent.com/83787952/141220970-382af19b-f98b-404b-bd1b-0eb77c890241.png)

**Comment by FrankYang0529** [comment]
I can reproduce the issue. The root cause is that the value in secret for `cloudInitNoCloud.secretRef` and `cloudInitNoCloud.networkDataSecretRef` must be encoded by base64. So empty string will cause an error.

```
Invalid value: \"\": status.secretBackups.data.networkdata in body must be of type byte: \"\"
```

```
apiVersion: v1
data:
  networkdata: "" <-- this will cause error
  userdata: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3dvcmQKY2hwYXNzd2Q6CiAgZXhwaXJlOiBmYWxzZQpzc2hwd2F1dGg6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKcGFja2FnZXM6CiAgLSBxZW11LWd1ZXN0LWFnZW50CnJ1bmNtZDoKICAtIC0gc3lzdGVtY3RsCiAgICAtIGVuYWJsZQogICAgLSAnLS1ub3cnCiAgICAtIHFlbXUtZ2Euc2VydmljZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogIC0gPi0KICAgIHNzaC1yc2EKICAgIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUUM5Nzc4OFNvb3BPamZ2YmZQbkF2MzVHcWJrVFhENFRoWWdVZFZhT2FBV2ErTzVoSFNnZ05RTDkvK2xCQ0RsWGI3SzEvSGlmOFJiUkdURnpxU3d6RDJWNVhpcWJXcFFEZlJsVFg4T0s4SjdqTWxUYU96TVc3SUFyMjJGSFRveVlHQTAxUGtWdXkxV2UvSzV6RmIrdWVsZEt2NEZSZ0NkcVlqaGdhaklVZEYxRWRlOTF6WEFtb3BuSExRenk3SmZIZi94MEJrVnp0S1N1Y2d0aW1PdUJzODNFR1dENnBGbnh2UmNQMXBITGl4TXI0d3FQU1lSUFVzeW5nL0tKejVUOFd2NGdTL0NtS09Kc3EydjNxNGpWVTREMWhuR3l5SXovS0JqejI3ckluRUlRbVpmMXpOTkdBemlHdWc0cXdwbS9INVMwbEtlQWRyTmlOWitwY1p2MGZORUVLa292TmkyWm9DRDJzeGJ0TTZOM3d6ODhVdkRpck95a2JpdmY2U0ZnWlVVQ29JS0xpMnh5Ym84bFBUUm05emx1QUZrVjJrQzgvUDl3bkR4SzY1U0hwL1R5bFYxeXlvakowY2o5QUpyTU93czQ0czlYTUJVWUpNSjAyMEZqbXB0R3NBT1pPT3k1Q0x4OXZlMk5iNnJGcktiOFE4NkJjdU12TUsrbHcvSnFPMD0KICAgIG5vYWguZ2lsZGVyc2xlZXZlQHN1c2UuY29tCg==
kind: Secret
metadata:
  name: secret-volume
  namespace: default
type: Opaque
```

If we change the secret like the following and it can pass.
```
apiVersion: v1
data:
  networkdata: Cg==
  userdata: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3dvcmQKY2hwYXNzd2Q6CiAgZXhwaXJlOiBmYWxzZQpzc2hwd2F1dGg6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKcGFja2FnZXM6CiAgLSBxZW11LWd1ZXN0LWFnZW50CnJ1bmNtZDoKICAtIC0gc3lzdGVtY3RsCiAgICAtIGVuYWJsZQogICAgLSAnLS1ub3cnCiAgICAtIHFlbXUtZ2Euc2VydmljZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogIC0gPi0KICAgIHNzaC1yc2EKICAgIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUUM5Nzc4OFNvb3BPamZ2YmZQbkF2MzVHcWJrVFhENFRoWWdVZFZhT2FBV2ErTzVoSFNnZ05RTDkvK2xCQ0RsWGI3SzEvSGlmOFJiUkdURnpxU3d6RDJWNVhpcWJXcFFEZlJsVFg4T0s4SjdqTWxUYU96TVc3SUFyMjJGSFRveVlHQTAxUGtWdXkxV2UvSzV6RmIrdWVsZEt2NEZSZ0NkcVlqaGdhaklVZEYxRWRlOTF6WEFtb3BuSExRenk3SmZIZi94MEJrVnp0S1N1Y2d0aW1PdUJzODNFR1dENnBGbnh2UmNQMXBITGl4TXI0d3FQU1lSUFVzeW5nL0tKejVUOFd2NGdTL0NtS09Kc3EydjNxNGpWVTREMWhuR3l5SXovS0JqejI3ckluRUlRbVpmMXpOTkdBemlHdWc0cXdwbS9INVMwbEtlQWRyTmlOWitwY1p2MGZORUVLa292TmkyWm9DRDJzeGJ0TTZOM3d6ODhVdkRpck95a2JpdmY2U0ZnWlVVQ29JS0xpMnh5Ym84bFBUUm05emx1QUZrVjJrQzgvUDl3bkR4SzY1U0hwL1R5bFYxeXlvakowY2o5QUpyTU93czQ0czlYTUJVWUpNSjAyMEZqbXB0R3NBT1pPT3k1Q0x4OXZlMk5iNnJGcktiOFE4NkJjdU12TUsrbHcvSnFPMD0KICAgIG5vYWguZ2lsZGVyc2xlZXZlQHN1c2UuY29tCg==
kind: Secret
metadata:
  name: secret-volume
  namespace: default
type: Opaque
```

**Comment by FrankYang0529** [comment]
## Test cases

### Secret reference cloud-init with empty string

* Create a secret like the following:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-volume
type: Opaque
data:
  userdata: "I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3dvcmQKY2hwYXNzd2Q6CiAgZXhwaXJlOiBmYWxzZQpzc2hwd2F1dGg6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKcGFja2FnZXM6CiAgLSBxZW11LWd1ZXN0LWFnZW50CnJ1bmNtZDoKICAtIC0gc3lzdGVtY3RsCiAgICAtIGVuYWJsZQogICAgLSAnLS1ub3cnCiAgICAtIHFlbXUtZ2Euc2VydmljZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogIC0gPi0KICAgIHNzaC1yc2EKICAgIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUUM5Nzc4OFNvb3BPamZ2YmZQbkF2MzVHcWJrVFhENFRoWWdVZFZhT2FBV2ErTzVoSFNnZ05RTDkvK2xCQ0RsWGI3SzEvSGlmOFJiUkdURnpxU3d6RDJWNVhpcWJXcFFEZlJsVFg4T0s4SjdqTWxUYU96TVc3SUFyMjJGSFRveVlHQTAxUGtWdXkxV2UvSzV6RmIrdWVsZEt2NEZSZ0NkcVlqaGdhaklVZEYxRWRlOTF6WEFtb3BuSExRenk3SmZIZi94MEJrVnp0S1N1Y2d0aW1PdUJzODNFR1dENnBGbnh2UmNQMXBITGl4TXI0d3FQU1lSUFVzeW5nL0tKejVUOFd2NGdTL0NtS09Kc3EydjNxNGpWVTREMWhuR3l5SXovS0JqejI3ckluRUlRbVpmMXpOTkdBemlHdWc0cXdwbS9INVMwbEtlQWRyTmlOWitwY1p2MGZORUVLa292TmkyWm9DRDJzeGJ0TTZOM3d6ODhVdkRpck95a2JpdmY2U0ZnWlVVQ29JS0xpMnh5Ym84bFBUUm05emx1QUZrVjJrQzgvUDl3bkR4SzY1U0hwL1R5bFYxeXlvakowY2o5QUpyTU93czQ0czlYTUJVWUpNSjAyMEZqbXB0R3NBT1pPT3k1Q0x4OXZlMk5iNnJGcktiOFE4NkJjdU12TUsrbHcvSnFPMD0KICAgIG5vYWguZ2lsZGVyc2xlZXZlQHN1c2UuY29tCg=="
  networkdata: ""
```

* Create a VM with the above secret:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  # ...
spec:
    # ...
    spec:
      # ...
      volumes:
      # ...
      - cloudInitNoCloud:
          networkDataSecretRef:
            name: secret-volume
          secretRef:
            name: secret-volume
        name: cloudinitdisk
```

* Setup NTP/S3 backup target
* Backup VM and check vmbackup can go into Ready state
* Try to restore vmbackup to new vm and check the vm can go into Running state.

### VM Restore with retained policy

* Try to restore to existent VM with the previous volume retained policy.
* Check whether the previous volume doesn't be deleted.

### VM Restore with deleted policy

* Try to restore to existent VM with the previous volume deleted policy.
* Check whether the previous volume is deleted.
