### ISSUE TITLE
[BUG] Unable to login after initial password setup

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1549]
**Describe the bug**
Admin user unable to log back in after the initial password setup. Admin user was prompted to create a password at initial login. After creating a password and signed into the UI the first time, subsequent logins all result in errors.

We suspect this is due to recent upstream Rancher change in enforcing a default password policy (i.e. minimal of 12 characters) which is not fully reflected in the Harvester UI.

**To Reproduce**
1. PXE install Harvester in a Vagrant (https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) or baremetal environment.
2. Access the Harvester UI at "https://<VIP>/" and set the initial admin password to "Password12345". Admin user is able to successfully login at this point.
3. Logout from the UI.
4. Try to re-login and see the failure.

**Expected behavior**
Admin user should be able to login.

**Support bundle**

**Environment:**
 - Harvester ISO version: master ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): This is reproducible in both vagrant (https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) and baremetal environment.

**Additional context**
Add any other context about the problem here
![Harvester_login_error](https://user-images.githubusercontent.com/1808417/142046538-7a4317a4-d179-4812-bcc2-c7d36cea88b5.png)
.
![Harvester_set_password](https://user-images.githubusercontent.com/1808417/142046549-95f07438-bfaf-4dfd-b617-808e3f225845.png)

**Comment by gitlawr** [comment]
Workaround:
```
echo "apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userattributes.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: UserAttribute
    listKind: UserAttributeList
    plural: userattributes
    singular: userattribute
  scope: Cluster
  versions:
  - name: v3
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true" | kubectl apply -f -
kubectl delete userattributes.management.cattle.io --all
```

**Comment by gitlawr** [comment]
The userattributes CRD created by Harvester is incompatible with the current Rancher version.
```
# rancher created
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userattributes.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: UserAttribute
    listKind: UserAttributeList
    plural: userattributes
    singular: userattribute
  scope: Cluster
  versions:
  - name: v3
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
# Harvester created
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userattributes.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: UserAttribute
    listKind: UserAttributeList
    plural: userattributes
    singular: userattribute
  scope: Cluster
  versions:
  - name: v3
    schema:
      openAPIV3Schema:
        properties:
          groupPrincipals:
            additionalProperties:
              properties:
                items:
                  items:
                    properties:
                      displayName:
                        nullable: true
                        type: string
                      extraInfo:
                        additionalProperties:
                          nullable: true
                          type: string
                        nullable: true
                        type: object
                      loginName:
                        nullable: true
                        type: string
                      me:
                        type: boolean
                      memberOf:
                        type: boolean
                      principalType:
                        nullable: true
                        type: string
                      profilePicture:
                        nullable: true
                        type: string
                      profileURL:
                        nullable: true
                        type: string
                      provider:
                        nullable: true
                        type: string
                    type: object
                  nullable: true
                  type: array
              type: object
            nullable: true
            type: object
          lastRefresh:
            nullable: true
            type: string
          needsRefresh:
            type: boolean
          userName:
            nullable: true
            type: string
        type: object
    served: true
    storage: true
```

Rancher fails to save the GroupPrincipals field in userattributes and gets panics:
```
E1117 01:58:11.254589      33 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 168046 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x39e5e00, 0x482b750)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:48 +0x86
panic(0x39e5e00, 0x482b750)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).UserAttributeCreateOrUpdate(0xc0021c6480, 0xc0077ccca0, 0xa, 0x41aa741, 0x5, 0x6a15bd8, 0x0, 0x0, 0xc00cfbcc00, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:598 +0x285
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).NewLoginToken.func1(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:659 +0x8e
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc007bb0c90, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x5f5e100, 0x4000000000000000, 0x3fc999999999999a, 0x5, 0x0, 0xc007bb0c90, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:399 +0x55
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).NewLoginToken(0xc0021c6480, 0xc0077ccca0, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc0078d7980, 0x12, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:658 +0x1b7
github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).createLoginToken(0xc001dc2c60, 0xc006a66900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:229 +0xe85
github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).login(0xc001dc2c60, 0xc001a03437, 0x5, 0xc00a58a880, 0xc006a66900, 0xc00373a000, 0xc00cfbcab0)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:69 +0x189
github.com/rancher/norman/api.handleAction(0xc00a58a880, 0xc006a66900, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:263 +0x62
github.com/rancher/norman/api.(*Server).handle(0xc000820630, 0x49163a8, 0xc001d14f00, 0xc00292b300, 0x4924ba0, 0xc00cfbc210, 0xc000c5cea0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:251 +0xde
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000820630, 0x49163a8, 0xc001d14f00, 0xc00292b300)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:180 +0x7d
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000edd740, 0x49163a8, 0xc001d14f00, 0xc00292b100)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x49163a8, 0xc001d14f00, 0xc00292b100)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:110 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000ccab00, 0x49163a8, 0xc001d14f00, 0xc00292b100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001231080, 0x49163a8, 0xc001d14f00, 0xc00292af00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc006a7c180, 0x49163a8, 0xc001d14f00, 0xc00292ad00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x49163a8, 0xc001d14f00, 0xc00292ad00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000ccab20, 0x49163a8, 0xc001d14f00, 0xc00292ad00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001230fc0, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
2021/11/17 01:58:11 [ERROR] Panic serving api request:
goroutine 168046 [running]:
runtime/debug.Stack(0xc007bb0338, 0x39e5e00, 0x482b750)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x49163a8, 0xc001d14f00)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:175 +0x85
panic(0x39e5e00, 0x482b750)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:55 +0x109
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:76 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000ccab80, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
panic(0x39e5e00, 0x482b750)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).UserAttributeCreateOrUpdate(0xc0021c6480, 0xc0077ccca0, 0xa, 0x41aa741, 0x5, 0x6a15bd8, 0x0, 0x0, 0xc00cfbcc00, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:598 +0x285
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).NewLoginToken.func1(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:659 +0x8e
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc007bb0c90, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:211 +0x69
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x5f5e100, 0x4000000000000000, 0x3fc999999999999a, 0x5, 0x0, 0xc007bb0c90, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:399 +0x55
github.com/rancher/rancher/pkg/auth/tokens.(*Manager).NewLoginToken(0xc0021c6480, 0xc0077ccca0, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc0078d7980, 0x12, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/manager.go:658 +0x1b7
github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).createLoginToken(0xc001dc2c60, 0xc006a66900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:229 +0xe85
github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).login(0xc001dc2c60, 0xc001a03437, 0x5, 0xc00a58a880, 0xc006a66900, 0xc00373a000, 0xc00cfbcab0)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:69 +0x189
github.com/rancher/norman/api.handleAction(0xc00a58a880, 0xc006a66900, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:263 +0x62
github.com/rancher/norman/api.(*Server).handle(0xc000820630, 0x49163a8, 0xc001d14f00, 0xc00292b300, 0x4924ba0, 0xc00cfbc210, 0xc000c5cea0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:251 +0xde
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000820630, 0x49163a8, 0xc001d14f00, 0xc00292b300)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/api/server.go:180 +0x7d
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000edd740, 0x49163a8, 0xc001d14f00, 0xc00292b100)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:43 +0xf2
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x49163a8, 0xc001d14f00, 0xc00292b100)
net/http.HandlerFunc.ServeHTTP(0xc002034a68, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x48b6b00, 0xc002034a68, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20211025232108-df28932a5627/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc002034a80, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:110 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000ccab00, 0x49163a8, 0xc001d14f00, 0xc00292b100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001231080, 0x49163a8, 0xc001d14f00, 0xc00292af00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc006a7c180, 0x49163a8, 0xc001d14f00, 0xc00292ad00)
net/http.HandlerFunc.ServeHTTP(0xc002034a98, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x49163a8, 0xc001d14f00, 0xc00292ad00)
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x48b6b00, 0xc002034a98, 0x0, 0xc000944d20, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:57 +0x53c
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000ccab20, 0x49163a8, 0xc001d14f00, 0xc00292ad00)
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210922195510-7224dc21013d/pkg/auth/filter.go:167 +0x1c7
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001230fc0, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
net/http.HandlerFunc.ServeHTTP(0xc0027ad1d0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:76 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000ccab80, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:43 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc002034a68, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x48b6b00, 0xc002034a68, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20211104200948-cd5d71f2fe95/server/server.go:193 +0x95
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20211025232108-df28932a5627/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc002034a80, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc002034a98, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x48b6b00, 0xc002034a98, 0x0, 0xc000944d20, 0x49163a8, 0xc001d14f00, 0xc00292ab00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:57 +0x53c
net/http.HandlerFunc.ServeHTTP(0xc003b843c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210922195510-7224dc21013d/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc0027ad1d0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20211104200948-cd5d71f2fe95/server/server.go:193 +0x95
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.HandlerFunc.ServeHTTP(0xc003b843c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20211104200948-cd5d71f2fe95/redirect.go:20 +0xa4
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x49163a8, 0xc001d14f00, 0xc009d91d00)
net/http.HandlerFunc.ServeHTTP(0xc0019803d8, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc00546a1c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.initALPNRequest.ServeHTTP(0x4924ba0, 0xc00910c360, 0xc004324380, 0xc00546a1c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:3439 +0x8d
net/http.(*http2serverConn).runHandler(0xc00a3cc000, 0xc001d14f00, 0xc009d91d00, 0xc009b24f30)
	/usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20211104200948-cd5d71f2fe95/redirect.go:20 +0xa4

net/http.HandlerFunc.ServeHTTP(0xc0019803d8, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc00546a1c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.initALPNRequest.ServeHTTP(0x4924ba0, 0xc00910c360, 0xc004324380, 0xc00546a1c0, 0x49163a8, 0xc001d14f00, 0xc009d91d00)
	/usr/local/go/src/net/http/server.go:3439 +0x8d
net/http.(*http2serverConn).runHandler(0xc00a3cc000, 0xc001d14f00, 0xc009d91d00, 0xc009b24f30)
	/usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
```
