### ISSUE TITLE
[BUG] Installation failed: "Could find partition device path for partition 6"

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1583]
**Describe the bug**
Installer reports fatal error during installation:
<img width="1050" alt="screen_shot_2021-11-23_at_10 31 23_am" src="https://user-images.githubusercontent.com/5047724/143192870-0244d415-0d8f-41df-8063-5fc289a360e8.png">

**To Reproduce**
Install Harvester with all default options. **This issue is easier to reproduce on bare-metals**.

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Fremont `1.46`

**Additional context**
This is the error message from the installer saying that it failed to partition the storage device. The main reason is the tool for performing disk partitioning "`yip`" sometimes can't synchronize the latest disk partitioning layout, and the inconsistency is detected and thus stops the whole process.

To verify this issue, you could solely run `yip` to see if it could properly and consistently partitioning the device:
1. Boot the Harvester ISO and proceed with the installation **until you finished configuring networking**. Having network access to the machine would make things easier.
2. SSH into the machine with credential `rancher/rancher`. You could also switch to another virtual terminal using `Ctrl-Alt-F2`, but it would make things a bit harder, as we later need to copy data into the machine.
3. Switch to root user `sudo -s`
4. Copy the following data into a file named `part-layout.yaml`. It's a partitioning layout for `yip` to execute:
    ```
    stages:
      partitioning:
      - layout:
          add_partitions:
          - fsLabel: COS_OEM
            size: 50
            pLabel: oem
            filesystem: ext4
          - fsLabel: COS_STATE
            size: 15360
            pLabel: state
            filesystem: ext4
          - fsLabel: COS_RECOVERY
            size: 8192
            pLabel: recovery
            filesystem: ext4
          - fsLabel: COS_PERSISTENT
            size: 102400
            pLabel: persistent
            filesystem: ext4
          - fsLabel: HARV_LH_DEFAULT
            pLabel: longhorn
            filesystem: ext4
          device:
            path: /dev/sda  # Change this line if you have different disk
        name: Part layout
    ```

5. Run this command to **wipe the disk `/dev/sda`** first, then partition the disk with `yip` using the layout from last step:
    ```
    # wipefs -af /dev/sda && yip -s partitioning part-layout.yaml
    ```
6. If partitioning succeeds, you should see messages like this:
    ```
    INFO[0007] Finished yip file execution                   stage=partitioning stages=1 success=true
    ```
    If failed, you would see messages similar to the screenshot.
7. You could repeatedly run the command from step 5, or write a bash script to try to reproduce the issue.
