### ISSUE TITLE
[BUG] exported image can't be deleted after vm removed

### ISSUE THREAD

**Issue by aiwantaozi** [harvester/harvester#1602]
**Describe the bug**

**To Reproduce**
1. create a VM with 2 volumes
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"test-vm-disk-0-9xocg","annotations":{"harvesterhci.io/imageId":"default/image-smjv2"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-smjv2"}},{"metadata":{"name":"test-vm-disk-1-pjaew"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn"}}]'
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    network.harvesterhci.io/ips: '[]'
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: linux
  name: test-vm
  namespace: default
spec:
  running: true
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: test-vm
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-0
          - bootOrder: 2
            disk:
              bus: virtio
            name: disk-1
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 52:54:00:0d:4c:79
            masquerade: {}
            model: virtio
            name: default
        machine:
          type: q35
        memory:
          guest: 924Mi
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 62m
            memory: 512Mi
      evictionStrategy: LiveMigrate
      hostname: test-vm
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: test-vm-disk-0-9xocg
      - name: disk-1
        persistentVolumeClaim:
          claimName: test-vm-disk-1-pjaew
      - cloudInitNoCloud:
          networkDataSecretRef:
            name: test-vm-sfmfk
          secretRef:
            name: test-vm-sfmfk
        name: cloudinitdisk
```
2. go to the volume page, and export those volumes as image

![image](https://user-images.githubusercontent.com/5936271/144188266-fed66ba1-ceb2-4f25-8c57-0f0a6da489df.png)

3. found those exported images bind to the same PVC as VM volumes
![image](https://user-images.githubusercontent.com/5936271/144188350-a5abd16f-78cd-45d4-b0a7-27fb1a737ded.png)

![image](https://user-images.githubusercontent.com/5936271/144188430-a55e1f4e-2a7c-4af5-a1ee-8534d37140d6.png)

4. delete the VM and it's volumes

![image](https://user-images.githubusercontent.com/5936271/144188587-9c5e4fa0-d86c-44dc-8775-34add638d930.png)

5. then go to the image page, delete the exported image, it is stuck in removing, logs show can't found PVC xxx

![image](https://user-images.githubusercontent.com/5936271/144189581-7dea5d1a-425f-4b3c-bd7a-0e4e9c4a459a.png)

**Expected behavior**

delete VM should not cause the exported image can't work

**Support bundle**

**Environment:**
 - Harvester ISO version: master-f6bc010b-head

 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
