### ISSUE TITLE
[FEATURE] Ability to use HwAddr to lookup NetworkInterface Name in harvester-installer.

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#1641]
**Is your feature request related to a problem? Please describe.**

Currently harvester-installer needs a create.yaml or join.yaml which contains the name of the interface to be used for harvester-mgmt network definition. This generally works fine in private cloud environments where the hardware details are available before hand or if we are using the ISO installation method.

When using PXE installation method, coupled with use in public metal cloud providers this becomes more challenging since the network interface name generated by the OS can vary based on the type of underlying hardware.

**Describe the solution you'd like**

The NetworkInterface kind allows users to specify Name and HwAddr (MAC address). Empty Names are not allowed, even if HwAddr is specified. Users should be able to provide just an empty Name with a valid HwAddr and the harvester-installer should be able to lookup the HwAddr from available interfaces and populate the device name at runtime. This will make it easier to configure PXE installation as the user doesnt need to factor in predefined interface names before hand.

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
Addressed by: https://github.com/harvester/harvester-installer/pull/183

**Comment by guangbochen** [comment]
**To Test:**
- Ability to use HwAddr to lookup NetworkInterface Name in harvester-installer, mode details please refer to https://github.com/harvester/harvester-installer/pull/183#issue-1072692585

An example of the PXE config with the network part is shown below, the interface name is not required if hwAddr is provided.
```
  networks:
    harvester-mgmt:
      interfaces:
      - hwAddr: '0c:c4:7a:6b:84:20'
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
```

**Comment by lanfon72** [comment]
verified this feature works as expected, document need to be updated correspondingly.

The config content for this issue:
```yaml
server_url: https://192.170.0.131:8443
token: token
os:
  hostname: harvester-node-1
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
  password: p@ssword
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
install:
  mode: join
  networks:
    harvester-mgmt:
      interfaces:
      - hwAddr: '02:00:00:35:86:92'
      # - name: ens6   # The management interface name
      method: dhcp
    bond0:
      interfaces:
      - name: ens5
      method: dhcp
  device: /dev/vda       # The target disk to install
  iso_url: http://192.169.121.220/harvester/harvester-amd64.iso
#  tty: ttyS1,115200n8   # For machines without a VGA console
  tty: ttyS0
```

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-5d739671-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with PXE installation, set `hwAddr` instead of `name` in `install.networks`
2. Harvester should installed successfully
