### ISSUE TITLE
[BUG] data partition is not mounted to the LH path properly

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1667]
**Describe the bug**
Install the Harvester manually using the ISO installer, the LH allocated disk size is only `100 Gi` while its partition and label are added successfully at `/dev/sda6`.
```
sda       8:0    0   1.1T  0 disk
├─sda1    8:1    0    47M  0 part
├─sda2    8:2    0    50M  0 part /oem
├─sda3    8:3    0    15G  0 part /run/initramfs/cos-state
├─sda4    8:4    0     8G  0 part
├─sda5    8:5    0   100G  0 part /usr/local
└─sda6    8:6    0 992.5G  0 part
$ blkid /dev/sda6
/dev/sda6: LABEL="HARV_LH_DEFAULT" UUID="8d3f864e-d443-41f6-bb6e-1b944d787e6b" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="longhorn" PARTUUID="e84451a4-4b13-438d-b26c-97cc0d230b36"
```
but the LH partition was not mounted to the `/var/lib/longhorn` path successfully and the `fstab`  is missing the expected config of `/dev/disk/by-label/HARV_LH_DEFAULT /var/lib/longhorn auto defaults 0 0`.

**To Reproduce**
1. Install the Harvester with `UEFI` mode installation.
2. There is only one root disk with 1.1TB and was formatted using the RAID1 config.
3. The installation is complete successfully but the LH path is mounted on the root system path instead of the data volume partition as below.
![image](https://user-images.githubusercontent.com/4569037/145784995-20f768d1-5d29-45ff-a1eb-49b78b95733a.png)

**Expected behavior**
LH path should be mounted to the data volume partition when either the `nodatapartition` is configured as false.

**Environment:**
```
NAME="Harvester"
ID="harvester"
ID_LIKE="suse opensuse"
VERSION_ID="20211130"
PRETTY_NAME="Harvester 56d24db"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/harvester/os2/issues"
HOME_URL="https://github.com/harvester/os2"
GRUB_ENTRY_NAME="Harvester 56d24db"
```

**Additional context**

```
serverurl: https://172.16.4.9:8443
token: a
os:
  sshauthorizedkeys: []
  writefiles: []
  hostname: bm-harv5
  modules:
  - kvm
  - vhost_net
  sysctls: {}
  ntpservers:
  - 0.suse.pool.ntp.org
  dnsnameservers:
  - 114.114.114.114
  wifi: []
  password: $6$Iis1EwtAIuTVuJ.Y$KeySuc9D2VF5Coo8hOQqSsGgBYIXQp9TYa4agKj8pVEx0YMioEZwuHtViWG3JHPek3e66i0wf6Go0aeU2VZ.n/
  environment: {}
  labels: {}
install:
  automatic: false
  mode: join
  networks:
    harvester-mgmt:
      interfaces:
      - name: eno1
        hwaddr: ""
      method: dhcp
      ip: ""
      subnetmask: ""
      gateway: ""
      defaultroute: true
      bondoptions:
        miimon: "100"
        mode: balance-tlb
      vlanid: 0
  vip: ""
  viphwaddr: ""
  vipmode: ""
  forceefi: false
  device: /dev/sdb
  configurl: ""
  silent: false
  isourl: ""
  poweroff: false
  noformat: false
  debug: false
  tty: tty1
  forcegpt: true
  forcembr: false
  nodatapartition: false
  webhooks: []
runtimeversion: v1.21.5+rke2r1
harvesterchartversion: 0.0.0-dev
monitoringchartversion: 100.0.0+up16.6.0
systemsettings: {}
```

**Comment by johnliu55tw** [comment]
`/run/cos/cos-layout.yaml` is missing the Longhorn partition mounting information:
```
OVERLAY="tmpfs:25%"
PERSISTENT_STATE_BIND="true"
PERSISTENT_STATE_PATHS="/etc/systemd /etc/rancher /etc/ssh /etc/iscsi  /etc/cni /home /opt /root /usr/libexec /var/log /var/lib/rancher /var/lib/kubelet /var/lib/wicked /var/lib/longhorn /var/lib/cni /var/crash"
RW_PATHS="/var /etc /srv /boot"
VOLUMES="LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
```

But it's in `/oem/99_custom.yaml`:
```
...
  rootfs:
  - commands: []
    files: []
    directories: []
    if: '[ ! -f "/run/cos/recovery_mode" ]'
    ensure_entities: []
    delete_entities: []
    dns:
      nameservers: []
      search: []
      options: []
      path: ""
    hostname: ""
    name: Rootfs layout overwrite
    sysctl: {}
    authorized_keys: {}
    node: ""
    users: {}
    modules: []
    systemctl:
      enable: []
      disable: []
      start: []
      mask: []
    environment:
      OVERLAY: tmpfs:25%
      PERSISTENT_STATE_BIND: "true"
      PERSISTENT_STATE_PATHS: /etc/systemd /etc/rancher /etc/ssh /etc/iscsi /etc/cni
        /home /opt /root /usr/libexec /var/log /var/lib/rancher /var/lib/kubelet /var/lib/wicked
        /var/lib/cni /var/crash
      RW_PATHS: /var /etc /srv /boot
      VOLUMES: LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local LABEL=HARV_LH_DEFAULT:/var/lib/longhorn
    environment_file: /run/cos/cos-layout.env
    datasource:
      providers: []
      path: ""
    layout:
      device: null
    systemd_firstboot: {}
    timesyncd: {}
```

And `journalctl` shows these messages:
```
Dec 07 10:47:21 localhost systemd[1]: dev-disk-by\x2dlabel-COS_OEM.device: Job dev-disk-by\x2dlabel-COS_OEM.device/start timed out.
Dec 07 10:47:21 localhost systemd[1]: Timed out waiting for device /dev/disk/by-label/COS_OEM.
Dec 07 10:47:21 localhost systemd[1]: Dependency failed for /oem.
Dec 07 10:47:21 localhost systemd[1]: oem.mount: Job oem.mount/start failed with result 'dependency'.
Dec 07 10:47:21 localhost systemd[1]: dev-disk-by\x2dlabel-COS_OEM.device: Job dev-disk-by\x2dlabel-COS_OEM.device/start failed with result 'timeout'.
```

I surmise this issue is caused by `/oem` is not mounted due to timed-out, so `rootfs` stage in `/oem/99_custom.yaml` is not executed, thus the `/run/cos/cos-layout.yaml` is not overwritten by the info provided in `/oem/99_custom.yaml`.

[journal.log](https://github.com/harvester/harvester/files/7704186/journal.log)
[99_custom.yaml.txt](https://github.com/harvester/harvester/files/7704204/99_custom.yaml.txt)
[cos-layout.env.txt](https://github.com/harvester/harvester/files/7704205/cos-layout.env.txt)
