### ISSUE TITLE
[BUG] Automatic disk provisioning result in unusable ghost disks on NVMe drives

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1718]
**Steps**

1. Install Harvester 1.0.0-rc2 on hardware servers with multiple NVMe disks
2. Add all the disks to Harvester using the global setting:

```
system_settings:
  auto-disk-provision-paths: /dev/nvme*
```

**Issue**

1. All the internal nvme drives seem to be active, but there are some ghost disks in the ui, that don't show up on the system or in blockdevices.harvesterhci.io
2. Even though all nodes have identical disks, the UI shows different amount of storage for each node

**Extra Info**

```
sandboxc1n10:~ # mount|grep extra-disk
/dev/nvme0n1p1 on /var/lib/harvester/extra-disks/8b964ba6f099f9c37ad67f7e0dcfbc88 type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme1n1p1 on /var/lib/harvester/extra-disks/9a2271cb4fe2209b47d01bc330294418 type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme2n1p1 on /var/lib/harvester/extra-disks/12df0e8f129b4bac41cb464be4f18c61 type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme3n1p1 on /var/lib/harvester/extra-disks/c0e69dd92a250119fc1acf9ee386587f type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme5n1p1 on /var/lib/harvester/extra-disks/c3c3365dfe86e88b61d0fa0a6bb275fa type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme4n1p1 on /var/lib/harvester/extra-disks/7f95ff328dda0610d5386f0e9b33447b type ext4 (rw,relatime,errors=remount-ro)
sandboxc1n10:~ # blkid|grep nvme
/dev/nvme3n1p1: UUID="24bd3f55-268b-4bbd-8f3e-7775e6c29609" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="df093500-30e2-4537-9a76-9d924a1f429a"
/dev/nvme2n1p1: UUID="2ce9698f-2ffb-463c-8851-329f9e504b9d" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="09e97962-91da-4495-af08-c1c939b0c0e6"
/dev/nvme5n1p1: UUID="0a82ba4a-e41d-4947-b2f4-22717316257e" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="0655ebc5-e9c2-4d9b-b75a-85200aa1f63b"
/dev/nvme4n1p1: UUID="02fc138d-1bdf-4d3d-8ade-b0d5485d4ae6" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="bf4ba988-055e-4f12-934f-1abb0d68691c"
/dev/nvme0n1p1: UUID="e1a1fb70-f364-48e1-bf98-b72f0e5ef87b" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="507fccff-b985-475d-8a94-5723416d5d24"
/dev/nvme1n1p1: UUID="1bc37ba2-581b-40f6-b645-64551fb705b6" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="54e2f0f7-efce-4cdc-b2b6-a13da4927bbf"
sandboxc1n10:~ # kubectl get blockdevices.harvesterhci.io -A|grep  sandboxc1n10
longhorn-system   066f7b2201a401ef819539085ed39e6e   part   /dev/nvme0n1p1   /var/lib/harvester/extra-disks/8b964ba6f099f9c37ad67f7e0dcfbc88   sandboxc1n10   Active   168m
longhorn-system   12df0e8f129b4bac41cb464be4f18c61   disk   /dev/nvme2n1                                                                       sandboxc1n10   Active   169m
longhorn-system   530df031e9355e37aec1e5be797258d1   part   /dev/nvme3n1p1   /var/lib/harvester/extra-disks/c0e69dd92a250119fc1acf9ee386587f   sandboxc1n10   Active   168m
longhorn-system   7f95ff328dda0610d5386f0e9b33447b   disk   /dev/nvme4n1                                                                       sandboxc1n10   Active   169m
longhorn-system   7ff2488850ed2651bbf3c3ac3b1e4a94   part   /dev/nvme2n1p1   /var/lib/harvester/extra-disks/12df0e8f129b4bac41cb464be4f18c61   sandboxc1n10   Active   168m
longhorn-system   863c7902d6a315a93d856e305ad9a005   part   /dev/nvme5n1p1   /var/lib/harvester/extra-disks/c3c3365dfe86e88b61d0fa0a6bb275fa   sandboxc1n10   Active   168m
longhorn-system   8b964ba6f099f9c37ad67f7e0dcfbc88   disk   /dev/nvme0n1                                                                       sandboxc1n10   Active   169m
longhorn-system   9a2271cb4fe2209b47d01bc330294418   disk   /dev/nvme1n1                                                                       sandboxc1n10   Active   169m
longhorn-system   ae2ee5767aa38eaea20bcdd9d9115224   part   /dev/nvme4n1p1   /var/lib/harvester/extra-disks/7f95ff328dda0610d5386f0e9b33447b   sandboxc1n10   Active   167m
longhorn-system   aefb46d3eceb78afdaead2fe35d070d7   part   /dev/nvme1n1p1   /var/lib/harvester/extra-disks/9a2271cb4fe2209b47d01bc330294418   sandboxc1n10   Active   168m
longhorn-system   c0e69dd92a250119fc1acf9ee386587f   disk   /dev/nvme3n1                                                                       sandboxc1n10   Active   169m
longhorn-system   c3c3365dfe86e88b61d0fa0a6bb275fa   disk   /dev/nvme5n1                                                                       sandboxc1n10   Active   169m
```
![image](https://user-images.githubusercontent.com/3813921/146808933-6307f29b-f840-4fa0-bd15-7f7f26d5a81e.png)

**Support bundle**

Available on request

**Comment by yasker** [comment]
There are tons of duplicated disks added into Longhorn and excluded by Longhorn duplicate disk detection mechanism.

**Comment by janeczku** [comment]
```
disks:
      1ab416049374044814972f7676c56d16:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f
        storageReserved: 0
        tags: []
      1e6c41b1e72f62451eadccb4ca9e0ca4:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/3ec6511eef63934beb219280c049361f
        storageReserved: 0
        tags: []
      2e3a93cf1a1194526cb36604759afc9e:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f
        storageReserved: 0
        tags: []
      3bf3a3e0bea81a1091c216ac6dfb0908:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944
        storageReserved: 0
        tags: []
      3dfe11250321b88d3a59cc9cf0c2fda8:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944
        storageReserved: 0
        tags: []
      3f67158889b3debba159e163b2baf47a:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f
        storageReserved: 0
        tags: []
      4c8af3ca3dc88b029542114970c0b67b:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f
        storageReserved: 0
        tags: []
....
    engineManagerCPURequest: 0
    evictionRequested: false
    name: sandboxc1n06
    replicaManagerCPURequest: 0
    tags: []
  status:
    conditions:
      MountPropagation:
        lastProbeTime: "null"
        lastTransitionTime: "2021-12-20T11:12:32Z"
        message: "null"
        reason: "null"
        status: "True"
        type: MountPropagation
      Ready:
        lastProbeTime: "null"
        lastTransitionTime: "2021-12-20T11:12:39Z"
        message: Node sandboxc1n06 is ready
        reason: "null"
        status: "True"
        type: Ready
      Schedulable:
        lastProbeTime: "null"
        lastTransitionTime: "2021-12-20T11:12:32Z"
        message: "null"
        reason: "null"
        status: "True"
        type: Schedulable
    diskStatus:
      0dce1419399e03e107ddb8b7bfa9042d:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:43:57Z"
            message: 'Disk 0dce1419399e03e107ddb8b7bfa9042d(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on node sandboxc1n06 is not ready: record diskUUID doesn''t match
              the one on the disk '
            reason: DiskFilesystemChanged
            status: "False"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:43:57Z"
            message: the disk 0dce1419399e03e107ddb8b7bfa9042d(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on the node sandboxc1n06 is not ready
            reason: DiskNotReady
            status: "False"
            type: Schedulable
        diskUUID: 1d5c8971-8cab-4d18-8166-db1004a430c9
        scheduledReplica: {}
        storageAvailable: 0
        storageMaximum: 0
        storageScheduled: 0
      1ab416049374044814972f7676c56d16:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:35:55Z"
            message: 'Disk 1ab416049374044814972f7676c56d16(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on node sandboxc1n06 is not ready: record diskUUID doesn''t match
              the one on the disk '
            reason: DiskFilesystemChanged
            status: "False"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:35:56Z"
            message: the disk 1ab416049374044814972f7676c56d16(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on the node sandboxc1n06 is not ready
            reason: DiskNotReady
            status: "False"
            type: Schedulable
        diskUUID: 2b7a8de1-5b75-42a9-b599-f50532173619
        scheduledReplica: {}
        storageAvailable: 0
        storageMaximum: 0
        storageScheduled: 0
      1e6c41b1e72f62451eadccb4ca9e0ca4:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:33:44Z"
            message: Disk 1e6c41b1e72f62451eadccb4ca9e0ca4(/var/lib/harvester/extra-disks/3ec6511eef63934beb219280c049361f)
              on node sandboxc1n06 is ready
            reason: "null"
            status: "True"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:33:44Z"
            message: Disk 1e6c41b1e72f62451eadccb4ca9e0ca4(/var/lib/harvester/extra-disks/3ec6511eef63934beb219280c049361f)
              on node sandboxc1n06 is schedulable
            reason: "null"
            status: "True"
            type: Schedulable
        diskUUID: 86c012c2-efb6-4da6-bfbd-bcffc5a24102
        scheduledReplica: {}
        storageAvailable: 1.5740174336e+12
        storageMaximum: 1.574047727616e+12
        storageScheduled: 0
      2e3a93cf1a1194526cb36604759afc9e:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:44:25Z"
            message: 'Disk 2e3a93cf1a1194526cb36604759afc9e(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on node sandboxc1n06 is not ready: record diskUUID doesn''t match
              the one on the disk '
            reason: DiskFilesystemChanged
            status: "False"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:44:25Z"
            message: the disk 2e3a93cf1a1194526cb36604759afc9e(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on the node sandboxc1n06 is not ready
            reason: DiskNotReady
            status: "False"
            type: Schedulable
        diskUUID: fe7906c0-04c7-4edd-bb25-88263df9cfa6
        scheduledReplica: {}
        storageAvailable: 0
        storageMaximum: 0
        storageScheduled: 0
      3bf3a3e0bea81a1091c216ac6dfb0908:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:38:58Z"
            message: Disk 3bf3a3e0bea81a1091c216ac6dfb0908(/var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944)
              on node sandboxc1n06 is ready
            reason: "null"
            status: "True"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:38:58Z"
            message: Disk 3bf3a3e0bea81a1091c216ac6dfb0908(/var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944)
              on node sandboxc1n06 is schedulable
            reason: "null"
            status: "True"
            type: Schedulable
        diskUUID: d9ba0b2c-3ecf-4a98-a606-6ec23cee5861
        scheduledReplica: {}
        storageAvailable: 1.5740174336e+12
        storageMaximum: 1.574047727616e+12
        storageScheduled: 0
      3dfe11250321b88d3a59cc9cf0c2fda8:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:36:28Z"
            message: 'Disk 3dfe11250321b88d3a59cc9cf0c2fda8(/var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944)
              on node sandboxc1n06 is not ready: record diskUUID doesn''t match
              the one on the disk '
            reason: DiskFilesystemChanged
            status: "False"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:36:28Z"
            message: the disk 3dfe11250321b88d3a59cc9cf0c2fda8(/var/lib/harvester/extra-disks/98b7f2dde9ccff3073341a6cbcf55944)
              on the node sandboxc1n06 is not ready
            reason: DiskNotReady
            status: "False"
            type: Schedulable
        diskUUID: 8f2e550f-0a68-449c-83be-2c8863ee4ea8
        scheduledReplica: {}
        storageAvailable: 0
        storageMaximum: 0
        storageScheduled: 0
      3f67158889b3debba159e163b2baf47a:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:42:57Z"
            message: 'Disk 3f67158889b3debba159e163b2baf47a(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on node sandboxc1n06 is not ready: record diskUUID doesn''t match
              the one on the disk '
            reason: DiskFilesystemChanged
            status: "False"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2021-12-20T11:42:58Z"
            message: the disk 3f67158889b3debba159e163b2baf47a(/var/lib/harvester/extra-disks/ce9c43e197c1e036e153be67ba6e778f)
              on the node sandboxc1n06 is not ready
            reason: DiskNotReady
            status: "False"
            type: Schedulable
        diskUUID: 9fa2c46b-8be3-43df-aa3c-2a0b6919c6fe
        scheduledReplica: {}
        storageAvailable: 0
        storageMaximum: 0
        storageScheduled: 0
      ...
    region: "null"
    zone: "null"
```
