### ISSUE TITLE
[BUG] Static VIP address (spec.loadBalancerIP field) does not work

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1772]
**Describe the bug**

Kube-VIP supports allocating a static VIP address to a service by setting the `spec.loadBalancerIP` field in the service manifest. 

Ref: https://kube-vip.io/usage/on-prem/#the-kube-vip-cloud-provider-configmap

When creating such service manifest in a Harvester guest cluster, then instead of assigning the address in `spec.loadBalancerIP` field, a random IP address from the pool is assigned.

**To Reproduce**

In a guest cluster, create a service resource with a static loadBalancerIP address:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: "10.65.100.10"
```

**Comment by yaocw2020** [comment]
It works well with the kube-vip of the 0.4 version. We have to upgrade the kube-vip to the latest version.

**Comment by yaocw2020** [comment]
For testing
- Set up a harvester
- Create a deployment and related load balancer type service
- Specify the field `spec.loadBalancerIP` with a static IP
- Request the svc through the load balancer IP

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-1a861fc1-head` and Rancher `da382a8`. with the test steps 



> For testing
> 
> * Set up a harvester
> * Create a deployment and related load balancer type service
> * Specify the field `spec.loadBalancerIP` with a static IP
> * Request the svc through the load balancer IP

I creted a deployment in Rancher with nginx, then created a load balancer service and specified the load balancer IP. It isn't routing it's still going to the endpoint that's in the YAML. The load balancer IP doesn't appear to be routing. Also the static IP I was trying to assign was in the same subnet as the one it randomly assigned.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-b09e3233-head`(02/14). Close this issue.

### Result
In Harvester cluster, we can create nginx service with static IP set on spec.loadBalancerIP. 
And can reach the services through the static IP  

```
harvester-one-220214:/home/rancher # kubectl describe service nginx
Name:                     nginx
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.53.137.109
IPs:                      10.53.137.109
IP:                       192.168.122.35
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  31251/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
```

```
curl http://192.168.122.35/
<a href="https://192.168.122.35/">Found</a>
```

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-b09e3233-head (02/14)

### Verify Steps
1. ssh to harvester node VIP
2. Prepare the service manifest yaml with content, set the static IP to spec.loadBalancerIP
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: nginx
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
    selector:
      app: nginx
    type: LoadBalancer
    loadBalancerIP: "10.65.100.10"
  ```
3. Run to `kubectl create -f ./service.yaml` to create service 
4. Run `kubectl describe service nginx` to check status
5. Run `curl http://192.168.122.35/` to request service through static IP
