### ISSUE TITLE
[FEATURE] Bump Kubevirt  to newer version 

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1783]
**Is your feature request related to a problem? Please describe.**
Bump dependency Kubevirt image to a newer version, e.g to v0.49.x, the minimum requirement is v0.46.x.

Dependency Issues:
https://github.com/harvester/harvester/issues/574

**Comment by guangbochen** [comment]
Move this issue to test and since this issue has bumped the kubevirt version, so the following testing cases will need to get covered:

- [x] Install the Harvester with the latest ISO build and verify all of the system components are running properly(`harvester-system, kube-system, longhorn-system & cattle-system`).
- [x] Doing some regression tests, e.g upload an image, create a VM and create a Volume, etc.
- [ ] Upgrade from v1.0.0 to the newer version will need to be verified via https://github.com/harvester/harvester/issues/1861

**Comment by TachunLin** [comment]
Verifying with `master-75cc3ced-head` (03/11).

- [x] Kubevirt image bump to the newer version: **`0.49.0-2`**

  ```
  rancher@harvester-node01-220311:~> sudo -i kubectl get deploy -n harvester-system virt-controller -o yaml | grep image
          - --launcher-image
          image: registry.suse.com/harvester-beta/virt-controller:0.49.0-2
          imagePullPolicy: IfNotPresent
  ```
  
- [x] All of the system components are running properly

* harvester-system pods running correctly without error
* kube-system pods running correctly without error
* longhorn-system pods running correctly without error
* cattle-system pods running correctly without error

**Comment by TachunLin** [comment]
### Basic regression test 

  - [x] Upload image from URL 
  
  - [x] Can Upload image from File 
  
  - [x] Create a VM from image 
  
  - [x] Can create volume from image 
  
  - [x] Can create VM from image 
  
  - [x] Can `Soft reboot` VM correctly 
  
    1. Can soft reboot to `running` status without showing status change 
    2. The IP Address of the VM  remain no change
    3. The State of the VM remain no change

**Comment by TachunLin** [comment]
### System Upgrade

- [x] Check the kubevirt version have bumped after upgrading from v1.0.0 to latest master-head 

  ```
  hpd8s7:~ # sudo -i kubectl get deploy -n harvester-system virt-controller -o yaml | grep image
          - --launcher-image
          image: registry.suse.com/harvester-beta/virt-controller:0.49.0-1
          imagePullPolicy: IfNotPresent
  ```
  
  
- [x] Regression test: Verified fixed on v1.0.1-rc2

**Comment by TachunLin** [comment]
We plan to combine the related Kubevirt bump verification steps into zero downtime upgrade accordingly in #1861 
Close this issue since the rest of the test scenarios have been correctly verified.

**Comment by TachunLin** [comment]
- [x] Check the kubevirt version have bumped to **`0.49.0-2`** after upgrading from v1.0.0 to `v1.0.1-rc2`

  ```
  node1:~ # kubectl get deploy -n harvester-system virt-controller -o yaml | grep image
          - --launcher-image
          image: registry.suse.com/harvester-beta/virt-controller:0.49.0-2
          imagePullPolicy: IfNotPresent
  ```

**Comment by FrankYang0529** [comment]
Validate that KubeVirt works fine after we upgrade harvester from v1.0.0 to v1.0.1-rc2.

1. Create a 3-node cluster with Harvester v1.0.0.
2. Create a VM.
3. Stop the VM.
4. Apply the following YAML.
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.0.1-rc2
  namespace: harvester-system
spec:
  isoChecksum: 2e8233e99589f735253255ccbe5ed039a37000f6766233fdb2dba5255180d27c8f8116548c8ba5b1b46a4dd605a3ffbe0284e59a912a50c5a6586957fa4e71d3
  isoURL: https://releases.rancher.com/harvester/v1.0.1-rc2/harvester-v1.0.1-rc2-amd64.iso
  minUpgradableVersion: v1.0.0
  releaseDate: "20220331"
  tags:
  - dev
```
5. Click the Upgrade button on the Dashboard.
6. After upgrade success, check KubeVirt version is `0.49.0-2`.
7. Check we can login/pause/unpause/stop/start/soft-reboot/migrate the VM.
