### ISSUE TITLE
[BUG]What label does a new node need, in order to run harvester pod?

### ISSUE THREAD

**Issue by wonleing** [harvester/harvester#1788]
**Describe the bug**

Harvester pod is CrashLoopBackOff, describe show following error.
FailedScheduling  6m57s (x2 over 6m58s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.
What kind of label I need to add into node?

**To Reproduce**
1. Add a new node into harvester cluster

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: harvester1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):Baremetal 

**Additional context**

**Comment by gitlawr** [comment]
From the message it's the pod anti-affinity rules that blocked the scheduling. The podAntiAffinity of Harvester deployment prevents running multiple Harvester pods on the same node.

```
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - harvester
          - key: app.kubernetes.io/component
            operator: In
            values:
            - apiserver
          - key: app.kubernetes.io/version
            operator: In
            values:
            - 0.1.x
        topologyKey: kubernetes.io/hostname
```

Can you provide a support bundle?
