### ISSUE TITLE
[FEATURE] Support update the dependency charts parameters in the harvester managedcharts

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1810]
**Is your feature request related to a problem? Please describe.**

During upgrading, the Harvester installer only allows updating the harvester chart version, not the dependency chart parameters. We should support it.

https://github.com/harvester/harvester/blob/ebde990de70056a975a7e6be389cbd594adf9fca/package/upgrade/upgrade_manifests.sh#L85-L91

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Chart values to update**
- [ ] Removal of kube-vip values in harvester/harvester-installer@f8a4c77
- [ ] Add defaultDataPath: "/var/lib/harvester/defaultdisk". Note this doesn't have any effect, just to be consistent.

**Comment by bk201** [comment]
For a context, this issue is used to track the removal of kube-vip values in https://github.com/harvester/harvester-installer/pull/216/commits/f8a4c77faa1ec87a1c3338b42ddc047b3956016a

**Comment by TachunLin** [comment]
Verified **fixed** on one click upgrade to v1.0.1-rc2. Close this issue.

### Result
1. **`kubevip.config`** did not exists
2.  Add defaultDataPath: longhorn.defaultSettings.defaultDataPath = **"/var/lib/harvester/defaultdisk"**

  `kubectl get managedcharts harvester -n fleet-local -o yaml | yq e '.spec.values' -`

  ```
  harvester-x4js2:~ # kubectl get managedcharts harvester -n fleet-local -o yaml | yq e '.spec.values' -
  containers:
    apiserver:
      hciMode: true
      image:
        imagePullPolicy: IfNotPresent
  harvester-load-balancer:
    enabled: true
  harvester-network-controller:
    enabled: true
    image:
      pullPolicy: IfNotPresent
    vipEnabled: true
  harvester-node-disk-manager:
    enabled: true
    image:
      pullPolicy: IfNotPresent
    labelFilter:
      - COS_*
      - HARV_*
  kube-vip:
    enabled: true
  kube-vip-cloud-provider:
    enabled: true
  kubevirt:
    spec:
      monitorAccount: rancher-monitoring-operator
      monitorNamespace: cattle-monitoring-system
  longhorn:
    defaultSettings:
      defaultDataPath: /var/lib/harvester/defaultdisk
      taintToleration: kubevirt.io/drain:NoSchedule
    enabled: true
  multus:
    enabled: false
  rancherEmbedded: true
  service:
    vip:
      enabled: true
      hwAddress: 52:54:00:3f:01:84
      ip: 10.84.44.124
      mode: dhcp
  webhook:
    image:
      imagePullPolicy: IfNotPresent
  ```

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: v1.0.0 GA to v1.0.1-rc2

### Verify Steps
1. Prepare v1.0.0 three nodes harvester cluster on Provo machines
2. Create a ubuntu and SLES JeOS image
3. Create a ubuntu and SLES virtual machine
4. Enable network to `harvester-mgmt`
5. Create a virtual network `vlan1` with id `1`
6. Setup back target to AWS S3
7. Create two backups for the ubuntu and SLES VM
8. Shutdown all VMs
9. Follow the steps to upgrade to v1.0.1-rc2
https://github.com/harvester/docs/blob/42598035cfe79856f7e159d4c47c4d7d29178900/docs/upgrade/automatic.md
10. Check the one click upgrade completely finished
11. SSH to management node 
12. Run `sudo -i kubectl get managedcharts harvester -n fleet-local -o yaml | yq e '.spec.values' - `
13. Check `kube-vip.config` not exists
14. Check `longhorn.defaultDataPath: /var/lib/harvester/defaultdisk` exists
