### ISSUE TITLE
[BUG] Unable to add node to RK2 cluster using node driver

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1823]
**Describe the bug**
After creating an RKE2 cluster, I am unable to add an additional node to the cluster by clicking +

**To Reproduce**
1. Create a cluster, with a single node pool
2. Click + to add another node to the node pool
3. Wait - see as the node is created in Harvester but never acknowledged by Rancher

**Expected behavior**
Another node should be added to the cluster

**Support bundle**
https://drive.google.com/file/d/16bgxeR5YeB2boqywmInSc-paxqMx-onG/view?usp=sharing

**Environment:**
 - Harvester ISO version: 1.0
 - Underlying Infrastructure: R620

**Additional context**
This should be easily reproducible

**Comment by FrankYang0529** [comment]
I can reproduce this issue with `SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2`, but not `focal-server-cloudimg-amd64.img`. Following is the error message in `rancher/machine` container.

```
Error creating machine: Error saving host to store after attempting creation: unable to load secret : error getting secret from kubernetes: Unauthorized
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

**Comment by abonillabeeche** [comment]
Correct. I can't reproduce with focal-server-cloudimg-amd64.img. Yet, while testing this, I clicked the - sign to delete that node I had just recently added, and my Harvester and Rancher clusters became unresponsive. @FrankYang0529 can you try and see if that happens to you too?

**Comment by FrankYang0529** [comment]
Looks like the issue isn't always reproducible. I can't reproduce with the same steps in a new Harvester cluster and Rancher.

In my old cluster, the error message is not always like my previous comment. Sometimes, the Job in Rancher is killed before the VM is ready, so the status of the Machine in Rancher is stuck in Provisioning. I have no idea which process kills the Job yet.

I think there may be a timeout config somewhere. If the Job is running for a long time and it will be killed. In my cluster, SLES takes 6m to finish `rancher/machine` Job. Focal only takes around 2m.

![Screen Shot 2022-01-19 at 2 23 40 PM](https://user-images.githubusercontent.com/4927361/150076608-13a25d62-2b98-4dd6-9e42-3b2fed79e411.png)
![Screen Shot 2022-01-19 at 2 29 09 PM](https://user-images.githubusercontent.com/4927361/150076621-334c336d-9716-4c3d-b8b8-1eace297ca74.png)

**Comment by FrankYang0529** [comment]
> Correct. I can't reproduce with focal-server-cloudimg-amd64.img. Yet, while testing this, I clicked the - sign to delete that node I had just recently added, and my Harvester and Rancher clusters became unresponsive. @FrankYang0529 can you try and see if that happens to you too?

@abonillabeeche, what do you mean about unresponsive? If a Machine in Rancher loses connection to a Harvester VM, the Machine CR can't be deleted caused of finalizers. My cluster still works, but I have to manually remove finalizers to remove Machine CR.

**Comment by FrankYang0529** [comment]
I can reproduce this issue sometime. If a job is deleted occasionally, we will get log like the following. The VM information is not stored to the Machine in Rancher, so the status of the Machine is stuck in Provisioning.
![Screen Shot 2022-01-20 at 5 46 35 PM](https://user-images.githubusercontent.com/4927361/150314616-4ecfb5aa-8a51-4558-a2ad-9ca4c7aa33e2.png)

Also, the job which doesn't really run for a long time still can be removed. From my previous comment, a 6m job can finish, but a 4m job may be killed.
![Screen Shot 2022-01-20 at 6 05 22 PM](https://user-images.githubusercontent.com/4927361/150318027-311f110c-b558-4774-a873-5efeff18acf7.png)


If a job is finished successfully, we can get log like the following.
![Screen Shot 2022-01-19 at 2 11 09 PM](https://user-images.githubusercontent.com/4927361/150314744-99e03acf-b42c-4c6a-9f5d-29dba301992d.png)

I still can't find which controller removes the job, but we can enable [Job tracking with finalizers](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-tracking-with-finalizers) after k8s 1.23.

**Comment by a-blender** [comment]
This is a bug in Rancher. As Rancher engineers, we cannot transfer this issue to the `rancher/rancher` repo because of lack of permissions. Could you please transfer it for us?

**Comment by thedadams** [comment]
@FrankYang0529 Before we confirm that this is a bug in Rancher, I would like to clarify a few things.

1. Is the job being killed or deleted? There is a big difference here. There is nothing in Rancher that will stop the job. There is something that will delete the job, but only after certain conditions are met on the Harvester machine object. I don't see any of the machine objects in the dump for this issue, so I can't be sure that these condition were or were not met for Rancher to clean up the job.
2. What is the exit status of the pod? The way rancher-machine works is the node drivers are started as gRPC servers and rancher-machine will send requests to them. The logs for the node drivers, therefore, don't show up in the logs for the pod because those are rancher-machine's logs. If the gRPC server (in this case, the Harvester node driver) exited uncleanly, then the pod would stop unexpectedly. In order to determine if this is the case, the pod would have to be inspected more closely. Depending on how far rancher-machine got, I would not expect the job to be deleted by the Rancher controllers.

**Comment by FrankYang0529** [comment]
@thedadams Because I can't get logs or YAML from a deleted pod/job, I try to do some experiments.

* Delete Job: I can get a similar result like my previous comment. Job and pod are all removed.
![Screen Shot 2022-02-14 at 9 56 43 PM](https://user-images.githubusercontent.com/4927361/153877489-883a5b25-38d0-4984-ba73-b685b85da446.png)

* Delete Pod: I assume if the gRPC server has an error and pod will be terminated, but the job will not. In this case, I can see another pod is created and has logs like the following. Also, the new pod will be in `Error` status.
![Screen Shot 2022-02-14 at 9 46 49 PM](https://user-images.githubusercontent.com/4927361/153876910-2aa93926-5e30-465a-b055-0b8d79a6b60d.png)

**Comment by thedadams** [comment]
@FrankYang0529 Unfortunately, deleting the pod or job manually doesn't give enough information into why this is happening. In order to fix the problem, we need to understand why the job or pod is being deleted by Rancher. It is very logical that deleting the job or pod manually will produce similar results to when it is deleted by Rancher, but we need to figure out what is going on.

The way I think is best to do this is to the following two commands while the job is running:
- `kubectl -n fleet-default get jobs -o yaml -w`
- `kubectl -n fleet-default get pods -o yaml -w`

These commands will output the information needed as the job is executing. If the job is deleted or fails, then the output of those two commands will gives us a clue as to how this is happening.

**Comment by FrankYang0529** [comment]
@thedadams thanks for your help. I can get the container exit code now! It's `137`. Looks like it's `OOMKilled`.

```
apiVersion: v1
kind: Pod
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T05:15:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T05:20:40Z"
    message: 'containers with unready status: [machine]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T05:20:40Z"
    message: 'containers with unready status: [machine]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T05:15:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://fded6a763f5289f4abd95cebe536414bb188fed5e7fd7efb9be6c8f4edfa6946
    image: docker.io/rancher/machine:v0.15.0-rancher73
    imageID: docker.io/rancher/machine@sha256:3baf7cb8bbc29fe9c16d45cd2b6c1a08a4deeb1bf6caff656fa264a4110c0d74
    lastState: {}
    name: machine
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://fded6a763f5289f4abd95cebe536414bb188fed5e7fd7efb9be6c8f4edfa6946
        exitCode: 137
        finishedAt: "2022-02-15T05:20:39Z"
        message: |
          Downloading driver from https://releases.rancher.com/harvester-node-driver/v0.3.4/docker-machine-driver-harvester-amd64.tar.gz
          docker-machine-driver-harvester-amd64.tar.gz
          docker-machine-driver-harvester-amd64.tar.gz: gzip compressed data, from Unix, original size 36115968
          Running pre-create checks...
          Creating machine...
          (rke2-in-jeos-4-pool1-8ace122d-vkmvc) Creating New SSH Key
          (rke2-in-jeos-4-pool1-8ace122d-vkmvc) Using public Key: /home/machine/.docker/machine/machines/rke2-in-jeos-4-pool1-8ace122d-vkmvc/id_rsa.pub
          (rke2-in-jeos-4-pool1-8ace122d-vkmvc) Start node
          (rke2-in-jeos-4-pool1-8ace122d-vkmvc) Waiting for node become Running
          (rke2-in-jeos-4-pool1-8ace122d-vkmvc) Waiting for node get ip
        reason: Error
        startedAt: "2022-02-15T05:15:38Z"
  hostIP: 172.17.0.2
  phase: Failed
  podIP: 10.42.0.24
  podIPs:
  - ip: 10.42.0.24
  qosClass: BestEffort
  startTime: "2022-02-15T05:15:35Z"
```

**Comment by FrankYang0529** [comment]
@thedadams , I run rancher as a docker container with `--oom-kill-disable`. I can get logs like the following in the job.

```
Error creating machine: Error saving host to store after attempting creation: unable to load secret : error getting secret from kubernetes: Unauthorized
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

In `kubectl -n fleet-default get pods -o yaml -w`, I also get exit code 137. I think they are related. From source code, above logs are from [here](https://github.com/rancher/machine/blob/7766c7065bfb384292c51747010c1e165ce6481e/libmachine/persist/secretstore.go#L88-L91). Do you know what situation may cause OOM kill here? Thank you.

```
apiVersion: v1
kind: Pod
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T08:13:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T08:20:06Z"
    message: 'containers with unready status: [machine]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T08:20:06Z"
    message: 'containers with unready status: [machine]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-15T08:13:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: rancher/machine:v0.15.0-rancher73
    imageID: ""
    lastState:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was deleted.  The
          container used to be Running
        reason: ContainerStatusUnknown
        startedAt: null
    name: machine
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.17.0.2
  phase: Failed
  podIP: 10.42.0.13
  podIPs:
  - ip: 10.42.0.13
  qosClass: BestEffort
  startTime: "2022-02-15T08:13:44Z"
```
