### ISSUE TITLE
[BUG] Additional virtual machine and images created during zero downtime upgrade should be deleted after completion 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1855]
**Describe the bug**

Additional virtual machine and images created and remains in harvester-system namespace after zero downtime upgrade 

* Additional virtual machine under harvester-system namespace
![image](https://user-images.githubusercontent.com/29251855/150509581-a79e2059-0380-4e02-b041-71e28426e433.png)

* Additional images created unser harvester-system namespace
![image](https://user-images.githubusercontent.com/29251855/150510207-308228c8-b67f-49fe-995e-3a4610828f2a.png)

**To Reproduce**
Do zero downtime upgrade from v1.0 to latest master head, steps refer to #1022 
1. Prepare 3 nodes harvester with 1.0.0 GA
2. Prepare latest master head iso 
3. Upload iso file to http or file server
4. ssh to harvester controller node 
5. Create the versions.yaml 
    ```
    cat > versions.yaml <<EOF
    apiVersion: harvesterhci.io/v1beta1
    kind: Version
    metadata:
      name: 1.0.2
      namespace: harvester-system
    spec:
      isoChecksum: 2765d89e5e8024347c81d36cc84b7168bf358a3a2f4da0c63164ad834a94bcbbaa13af4900aad4caa0a27550e4b4db5bf2c4726daa88664378e0c581a79ad2cb
      isoURL: http://10.10.0.1/harvester/harvester.iso
      minUpgradableVersion: 0.3.0
      releaseDate: "20211231"
      tags:
      - dev
      - test
    EOF
    ```
6. Run kubectl create -f versions.yaml
7. Refresh harvester page
8. Click the Upgrade button
9. Click the green circle to display upgrade status page 
10. Check the status and wait until zero downtime upgrade finish

**Expected behavior**

Additional virtual machine and image created during zero downtime upgrade should be deleted from harvester virtual machine and images page. 

**Support bundle**

[supportbundle_9f470b6f-44de-4cf9-891e-9bce00060bd7_2022-01-21T10-27-47Z.zip](https://github.com/harvester/harvester/files/7912467/supportbundle_9f470b6f-44de-4cf9-891e-9bce00060bd7_2022-01-21T10-27-47Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.0 GA upgrade to v1.0 master head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes harvester on provo bare machine
