### ISSUE TITLE
[Question] Redirect host requests to LoadBalancer

### ISSUE THREAD

**Issue by IArchi** [harvester/harvester#1877]
Hello,

I have the following setup:
![image](https://user-images.githubusercontent.com/92300377/151343136-bddbe1f9-d3ea-4e71-9acb-9be32a22ed2d.png)

- Two devices, running both a Harvester instance.
- A single Harvester Cluster
- A single K3S Cluster
- 4 K3S nodes
- 1 Pod (Empty Nginx)
- 1 Service to expose Nginx on port 2222 on LoadBalancer
- 1 Ingress to reach the service easier.

Full Yaml is available here:
<details>

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-demo
  name: nginx-demo
  namespace: customer
spec:
  ports:
    - name: "2222"
      port: 2222
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-demo
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-demo
  name: nginx-demo
  namespace: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx-demo
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  generation: 3
  name: nginx-demo
  namespace: customer
spec:
  rules:
    - host: nginx.192.168.1.24.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-demo
              servicePort: 2222
  tls: 
    - hosts:
        - nginx.192.168.1.24.nip.io
      secretName: nginx-demo-cert
```

</details>

My 4 nodes got the following IPs:

- 192.168.1.24
- 192.168.1.25
- 192.168.1.29
- 192.168.1.30

If I want to reach the LoadBalancer, I have to use one of the above.
For example, I can see the dummy nginx webpage at `https://192.168.1.24:2222` and at `https://nginx.192.168.1.24.nip.io`.

What I'd like to do is to use one of the host IPs (`Device #1` or `Device #2`).
For example, I'd like to use `https://192.168.1.99:2222` (or `https://nginx.192.168.1.99.nip.io`) which is `Device #1` IP.

Is there a way to achieve that ?

Thanks for your help.
