### ISSUE TITLE
[Bug] Shutdown from inside the VM results in VM rebooting/UI stuck?

### ISSUE THREAD

**Issue by nunix** [harvester/harvester#1882]
Hi team,

I'm currently seeing the following behavior for Linux and Windows VMs: when I try to shutdown the VM from the guest OS, Harvester restarts the VM automatically.

I tweaked the settings (see below) to reach a sort of middle ground: Harvester doesn't restart the VM anymore, however the Harvester UI is not reflecting the "true" state of the VM and stays in a "pending" state.

Here is what I did and which results I have:
- Create/Modify a VM > edit the YAML config
- Replace the `spec.running` by `spec.runStrategy`
```yaml
...
spec:
  runStrategy: RerunOnFailure
...
```
- Add the KubeVirt `spec.spec.domain.features.acpi` capability
```yaml
...
spec:
  spec:
    domain:
      features:
        acpi:
          enabled: true
...
```
- Start/Connect to the VM
- Shutdown the VM

Results:
While the VM will correctly shutdown, Harvester UI will "hang" on `Starting` with the message `Virt-launcher pod is terminating`.
The `kubectl get pods` will show the VM pod as `Completed`  and `kubectl get vm` will show the VM as `Stopped`:
![image](https://user-images.githubusercontent.com/905874/151219354-c18d8655-0078-4c43-bd55-76ab0f15ef29.png)

Additional notes/hints:
When the VM is stopped, if I click on `Stop` and check the VM config, I can see that `spec.runStrategy` has switched to `halted`.

I hope this is clear 😄

_Originally posted by @nunix in https://github.com/harvester/harvester/issues/574#issuecomment-1022457166_

**Comment by rebeccazzzz** [comment]
Changed estimation per @guangbochen's recommendation.

**Comment by tjjh89017** [comment]
note: `kubectl get vm test -o yaml` will show status `stopped`
```
status:
  conditions:
  - lastProbeTime: "2022-02-24T06:44:35Z"
    lastTransitionTime: "2022-02-24T06:44:35Z"
    message: virt-launcher pod is terminating
    reason: PodTerminating
    status: "False"
    type: Ready
  created: true
  printableStatus: Stopped
  volumeSnapshotStatuses:
  - enabled: true
    name: rootdisk
  - enabled: true
    name: cdrom-disk
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]

```
