### ISSUE TITLE
[BUG] Panic if the vlan nad config is without labels

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1886]
**Describe the bug**

Apply the below YAML config and the harvester network controller manager will be panic.
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1
  namespace: default
spec:
  config: '{"cniVersion":"0.3.1","name":"vlan178","type":"bridge","bridge":"harvester-br0","promiscMode":true,"vlan":1,"ipam":{}}'
```
```
E0201 13:33:50.201838       1 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 324 [running]:
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19f3600, 0x1e8a950)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x19f3600, 0x1e8a950)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/harvester/harvester-network-controller/pkg/controller/manager/nad.Handler.ensureLabels(0xc00004200a, 0x10, 0x7ffc22007e15, 0x27, 0x7f0030288198, 0xc00045f110, 0x1ee4048, 0xc000447680, 0x7f00302881f0, 0xc00045f1f0, ...)
	/go/src/github.com/harvester/harvester-network-controller/pkg/controller/manager/nad/controller.go:147 +0x18f
github.com/harvester/harvester-network-controller/pkg/controller/manager/nad.Handler.OnChange(0xc00004200a, 0x10, 0x7ffc22007e15, 0x27, 0x7f0030288198, 0xc00045f110, 0x1ee4048, 0xc000447680, 0x7f00302881f0, 0xc00045f1f0, ...)
	/go/src/github.com/harvester/harvester-network-controller/pkg/controller/manager/nad/controller.go:98 +0x188
github.com/harvester/harvester-network-controller/vendor/github.com/harvester/harvester/pkg/generated/controllers/k8s.cni.cncf.io/v1.FromNetworkAttachmentDefinitionHandlerToHandler.func1(0xc000b07360, 0xd, 0x1ec40e0, 0xc0002cd180, 0x8, 0x203000, 0x38, 0x413ebd)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/harvester/harvester/pkg/generated/controllers/k8s.cni.cncf.io/v1/networkattachmentdefinition.go:102 +0x6b
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00054ca20, 0xc000b07360, 0xd, 0x1ec40e0, 0xc0002cd180, 0x0, 0xc000820008, 0x40409a, 0xc000820000)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000447530, 0xc000b07360, 0xd, 0x1ec40e0, 0xc0002cd180, 0xc0005ee001, 0x0)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x115
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000139600, 0xc000b07360, 0xd, 0xc0007da118, 0xc000552660)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/controller.go:210 +0xd1
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000139600, 0x196fc20, 0xc000cc4040, 0x0, 0x0)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/controller.go:192 +0xe7
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000139600, 0x203000)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/controller.go:169 +0x54
github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/controller.go:158
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a24060)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a24060, 0x1ea4e80, 0xc000c88060, 0x1, 0xc00014d260)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a24060, 0x3b9aca00, 0x0, 0xc0004b0401, 0xc00014d260)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000a24060, 0x3b9aca00, 0xc00014d260)
	/go/src/github.com/harvester/harvester-network-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/lasso/pkg/controller/controller.go:129 +0x33b
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
```

**To Reproduce**
1. Set up a harvester cluster and apply the below YAML config.
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1
  namespace: default
spec:
  config: '{"cniVersion":"0.3.1","name":"vlan178","type":"bridge","bridge":"harvester-br0","promiscMode":true,"vlan":1,"ipam":{}}'
```

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version:  v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtual environment

**Additional context**

**Comment by yaocw2020** [comment]
For testing:
- Apply the YAML mentioned above manually.
- Observe whether the harvester-network-controller-manager pod is normal.

**Comment by noahgildersleeve** [comment]
Tested in `master-f303b27e-head`. 
[supportbundle_542027dd-7e8c-4fba-b5a1-0d45e9d72666_2022-02-08T19-42-30Z.zip](https://github.com/harvester/harvester/files/8026928/supportbundle_542027dd-7e8c-4fba-b5a1-0d45e9d72666_2022-02-08T19-42-30Z.zip)

## Verification Steps
Steps to reproduce the behavior:

1. Set up a harvester cluster
2. Add vlan interface
3. Apply the below YAML config. (I used embedded rancher to do it)
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1
  namespace: default
spec:
  config: '{"cniVersion":"0.3.1","name":"vlan178","type":"bridge","bridge":"harvester-br0","promiscMode":true,"vlan":1,"ipam":{}}'
```
4. Create VM 
5. Run VM health checks
