### ISSUE TITLE
[BUG] Document the way to update the memory limit for `rancher-monitoring`

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1887]
**Describe the bug**
To prevent the Prometheus from (OOM #1531), I've updated the `rancher-monitoring` chart manually on the bare metal cluster and applied a bigger memory limit e.g. `4000M`. It works initially, but it is always reverted back after a few hours or a couple of days. I am not sure what's the reason for the rollback.

**Expected behavior**
Either the setting shouldn't be rolled back, or we need to document the right want to update the `rancher-monitoring` chart's memory usage.

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Poweredge R630

**Comment by guangbochen** [comment]
manual workaround steps to fix the monitoring OOM issue:
1. ssh to one of the Harvester node or download the `kubeconfig` file via the `support` page.
2. run `$kubectl edit managedcharts -n fleet-local rancher-monitoring` and modify the resource request and limits of the `spec.values.prometheus.prometheusSpec` accordingly. e.g,:
```
  values:
    prometheus:
      prometheusSpec:
        evaluationInterval: 1m
        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
          requests:
            cpu: 750m
            memory: 750Mi
```
