### ISSUE TITLE
[BUG] DNS server not available during install 

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1903]
**Describe the bug**

When doing a PXE boot using DHCP it fails to fetch ssh keys from github due to DNS server not being available yet.
It works however when doing it later over ssh from the node;
```bash
# curl -v https://github.com/jellyfrog.keys
*   Trying 140.82.121.4:443...
* TCP_NODELAY set
* Connected to github.com (140.82.121.4) port 443 (#0)
* ...
```

**To Reproduce**
1. Install over PXE with the below config

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version:  master-f303b27e-head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vmware

**Additional context**
```
Feb 09 17:31:59 harvester-mw9l9 cos-setup[1318]: time="2022-02-09T17:31:59Z" level=error msg="1 error occurred:\n\t* failed fetching ssh key: failed while downloading key: failed while getting file: Get \"https://github.com/jellyfrog.keys\": dial tcp: lookup github.com on [::1]:53: read udp [::1]:39527->[::1]:53: read: connection refused\n\n"
Feb 09 17:32:00 harvester-mw9l9 cos-setup[1318]:         * failed fetching ssh key: failed while downloading key: failed while getting file: Get "https://github.com/jellyfrog.keys": dial tcp: lookup github.com on [::1]:53: read udp [::1]:39527->[::1]:53: read: connection refused
Feb 09 17:32:00 harvester-mw9l9 cos-setup[1318]:         * failed fetching ssh key: failed while downloading key: failed while getting file: Get "https://github.com/jellyfrog.keys": dial tcp: lookup github.com on [::1]:53: read udp [::1]:39527->[::1]:53: read: connection refused
```

```yaml
token: "token123"
os:
  ssh_authorized_keys:
    - github:jellyfrog
  password: admin
install:
  mode: create
  networks:
    harvester-mgmt:
      interfaces:
      - name: ens192
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
    harvester-vlan:
      interfaces:
      - name: ens224
      method: none
      bond_options:
        mode: balance-tlb
        miimon: 100
  device: /dev/sda
  iso_url: http://172.16.123.6/harvester/master/harvester-master-amd64.iso
  vip: 10.10.104.10
  vip_mode: static
```

**Comment by noahgildersleeve** [comment]
Tested in `master-bfd6a8a9-head`. 
## Verification Steps
### Without PXE
1. Start a new install
2. Set DNS as `8.8.8.8`
3. Add in github SSH keys
4. Finish install
5. SSH into node with SSH keys from github (`rancher@hostname`)
6. Verify login was successful

### With PXE
1. Got vagrant setup from https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester
2. Changed `settings.yml` DHCP config and added `dns: 8.8.8.8`
```
dhcp_server:
    ip: 192.168.0.254
    subnet: 192.168.0.0
    netmask: 255.255.255.0
    range: 192.168.0.50 192.168.0.130
    dns: 8.8.8.8
    https: false
```
Also changed `ssh_authorized_keys` and commented out default SSH key and added username for github
```
  ssh_authorized_keys:
    # Vagrant default unsecured SSH public key
    # - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    - github:username
```
3. Ran `sudo setup_harvester.sh`
4. Waited for install to finish
5. Verified I could SSH into the VIP at `192.168.0.131` with appropriate SSH key
