### ISSUE TITLE
Stuck in Setting up Harvester

### ISSUE THREAD

**Issue by BringerOD** [harvester/harvester#1922]
**Describe the bug**
Stuck in "Setting Up Harvester"

**To Reproduce**
IPXE Install with V1.0.0
1 Node,  1 Nic

**Expected behavior**
Expected to be in Ready State

**Environment:**
 - Harvester ISO version: V1.0.0,  I also tested the latest ISO
 - Baremetal Vultr
 - IPXE
 - CPU: 8 Cores - 16 Threads
 - RAM: 131072 MB
 - Storage:
 - 2x 2000GB NVMe

**Additional context**
I noticed the rancher/harvester-cluster-repo:v1.0.0 image could not be pulled.  Not sure why.  I tested locally and also was unable to pull the image.

I used IPXE
```

#!ipxe
kernel xxxxxxx/harvester-v1.0.0-vmlinuz-amd64 ip=dhcp rd.cos.disable rd.noverifyssl net.ifnames=1 root=live:xxxxxxx/harvester-v1.0.0-rootfs-amd64.squashfs console=tty1 harvester.install.automatic=false harvester.install.config_url=xxxxxxx/config.yaml
initrd xxxxxxx/harvester-v1.0.0-initrd-amd64
boot
```

config
```
#cloud-config
token: xxxxx
os:
  password: xxxxx
install:
  mode: create
  iso_url: https://releases.rancher.com/harvester/v1.0.0/harvester-v1.0.0-amd64.iso
```

The config really is not used, I just use pxe to get and load the ISO, to then configure it by hand.

![image](https://user-images.githubusercontent.com/7971305/154329814-5c02b3dc-70f3-4557-b466-f0fdbe62da88.png)

![image](https://user-images.githubusercontent.com/7971305/154329923-d6d3e10a-b98c-4064-b7d7-56f3f4a357a2.png)

![Untitled](https://user-images.githubusercontent.com/7971305/154347488-eb2852d0-3748-4f91-8d7a-40c8dcd503ce.png)

**Comment by bk201** [comment]
@BringerOD Loading the installation ISO (specified in the config) in a PXE boot installation is a critical step because it preloads container images to the target system. The `rancher/harvester-cluster-repo` image is only shipped with the ISO, that's why the cluster can't be up.

**Comment by BringerOD** [comment]
Aren't I doing that?  I believe I followed the examples in the documentation.  Sorry I am a bit confused. 

Not sure there is much of a diference but do you mean this?


```bash
#!ipxe
kernel https://xxxxxxxxx/pxe/harvester-v1.0.0-vmlinuz-amd64 ip=dhcp rd.cos.disable rd.noverifyssl net.ifnames=1 root=live:https://xxxxxxxxx/pxe/harvester-v1.0.0-rootfs-amd64.squashfs console=tty1 harvester.install.automatic=false harvester.install.config_url=https://xxxxxxxxx/pxe/config.yaml
initrd https://xxxxxxxxx/pxe/harvester-v1.0.0-initrd-amd64
boot
```

config
```yml
#cloud-config
token: xxxxxx           # replace with a desired token
os:
  password: xxxxxx   # replace with a your password
install:
  mode: create
  iso_url: https://xxxxxxxxxx/pxe/harvester-v1.0.0-amd64.iso
```
