### ISSUE TITLE
[Question] How do you add drives to harvester

### ISSUE THREAD

**Issue by BringerOD** [harvester/harvester#1943]
How do you add partition mount disks in harvester?   I am not very familiar with this type of procedure.

Current Steps
* sudo gdisk
* sudo mkfs.ext4 /dev/nvme0n1p1
* sudo mkdir /disk1 - This fails

```bash
rancher@node1:/> sudo mkdir /disk1
mkdir: cannot create directory ‘/disk1’: Read-only file system
```

I also set "auto-disk-provision-paths" to "dev/nvme*".  Which did not work for me.

Here is what I thought would be relevant.

![image](https://user-images.githubusercontent.com/7971305/155855921-7e0d2178-3ce7-49b4-b0e3-f8442992f4da.png)

![image](https://user-images.githubusercontent.com/7971305/155856189-c97739c7-7c50-4d04-8baf-dd99e76c83b7.png)

![image](https://user-images.githubusercontent.com/7971305/155855868-4aea8713-bc52-42be-ba2a-ec84f9b4bdc9.png)

![image](https://user-images.githubusercontent.com/7971305/155856091-3c3dc076-2057-4e3f-b86b-147ab6818ff0.png)

**Comment by simonflood** [comment]
Does https://docs.harvesterhci.io/v1.0/host/host/#multi-disk-management-tech-preview help?

**Comment by BringerOD** [comment]
The disks do not show up in the add disk dropdown.

**Comment by weihanglo** [comment]
Thanks for the report!

It seems that those disks are virtual disks. Could you add WWN for them? There is a limitation that Harvester currently requires each disk to have WWN in order to determine the uniqueness of the underlying data model.

To help us investigate the issue, it would be better if you can attach your environment information such as Harvester ISO version and underlying infrastructure (e.g. baremetal with Dell PowerEdge R630, qemu-kvm v6.2.0).

As a workaround, if you're using libvirt, you can add a line `<wwn>your-unique-wwn</wwn>` to the Virtual machine domain XML.

**Comment by BringerOD** [comment]
Provider:  Bare metal at Vultr.com

Harvester V1.0:  Latest as of 2/24/2022

DELL PowerEdge C6523

CPU: EPYC 7443P
24 Cores - 48 Threads
RAM:
262144 MB
Storage:
2x 480GB SSD
2x 1.9TB NVMe

```yaml
#cloud-config
token: xxx  
os:
  hostname: node1
  password: xxxx
  ssh_authorized_keys:
    - ssh-rsa xxx
    - github:xxxx
  dns_nameservers:
    - 8.8.8.8
    - 1.1.1.1
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
install:
  mode: create
  networks:
    harvester-mgmt:       # (Mandatory) The management bond name.
      interfaces:
      - name: eno12399np0
      default_route: true
      method: static
      ip: xxxx
      bond_options:
        mode: balance-tlb
        miimon: 100
      gateway: xxxx
      subnet_mask: 255.255.254.0
  debug: true
  device: /dev/sda       
  iso_url: https://xxxx/pxe/harvester-master-amd64.iso
  vip: xxxxx
  vip_mode: static       

```
