### ISSUE TITLE
[CI] Collect helpful information on a Vagrant installation test failure

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1988]
**Describe the bug**

The vagrant installation test in the harvester-installer project is triggered on each PRs to test the cluster deployment.
But it doesn't output useful information if a test fails. For example https://ci.harvesterhci.io/job/harvester-vagrant-installation-test/278/

We can improve this by collecting node logs, screenshots of VNC, support bundles, etc.

**Comment by FrankYang0529** [comment]
Proposal:
1. Update ansible playbook [boot_harvester_node.yml](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/ansible/boot_harvester_node.yml). If a node is not ready, we use supportconfig to generate support bundle and move generated files to host.
2. For CI, we post these files as artifacts, so we can download it if CI pipeline fail.



* Rely on https://github.com/harvester/harvester/pull/1881

**Comment by lanfon72** [comment]
added `not-require/test-plan`.
@guangbochen, as this is CI related, so I think QA can't not verify it?

**Comment by irishgordo** [comment]
@lanfon72 - would the goal then to be just to implement something like:
```go
cmd := exec.CommandContext(ctx, "/sbin/supportconfig", "-Q", "-B", fileName)
```
[executeSupportConfig's function from pkg.console.util.go from harvester-installer](https://github.com/ibrokethecloud/harvester-installer/blob/af48aeb0a08c6ff36a21ea9f8f62984308c78f8b/pkg/console/util.go#L685-L694)

[adding another task after this to try to hop on that node's vm and run /sbin/supportconfig?](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/ansible/boot_harvester_node.yml#L20-L29)

If it happens to timeout waiting for that node after 20 retries.
We may want to try to shell into the node that did fail, like registering something that it failed that step for that node.

Using [an inventory file like this](https://github.com/irishgordo/ipxe-examples/blob/feat/2096-air-gapped-rancher-single-node-proof-of-concept/vagrant-pxe-harvester/inventory) and having a separate playbook run to preform a triage of the node with a playbook looking maybe something like:
```yaml

---
- name: Generate SupportConfig Bundle For Harvester Node(s) That Failed To Come Online
  hosts: harvesternodes
  connection: local
  gather_facts: false
  become: yes
  
  tasks:
  - name: Generate SupportConfig Bundle
    shell: |
      /sbin/supportconfig -Q -B /tmp/harvester_node_{{node_number}}_support_config_bundle.txz
    when: not {{node_number}}.working | bool
    
  - name: Copy SupportConfig Bundle to Local Machine From Remote Harvester Node {{node_number}}
    fetch:
      src: /tmp/harvester_node_{{node_number}}_support_config_bundle.txz
      dest: /tmp/harvester_node_{{node_number}}_support_config_bundle.txz
    when: not {{node_number}}.working | bool
    
```
