### ISSUE TITLE
[BUG] Upgrade: longhorn-system can't be evicted

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2053]
**Describe the bug**
The upgrade progress is stuck and we can get error log in rancher pod.

```
evicting pod longhorn-system/instance-manager-r-262cb6bc
error when evicting pods/"instance-manager-r-262cb6bc" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

![Screen Shot 2022-03-21 at 5 00 28 PM](https://user-images.githubusercontent.com/4927361/159238119-1307d1a2-90ba-4583-8c79-fa521f5aeb33.png)

![Screen Shot 2022-03-21 at 4 59 38 PM](https://user-images.githubusercontent.com/4927361/159238230-0ba45fcc-814e-4223-a1a2-3c0e8932d5e5.png)

**To Reproduce**
1. Setup a 4-node v1.0.0 cluster.
2. Run `make default` to build latest image.
3. Create a Version CR for it.
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: 1.0.2
  namespace: harvester-system
spec:
  isoChecksum: 4f80b9c5a728246c36c79f42ef8f1ad02e538b95b32d6f3dd70acdfeddb94808693371eff06dcc1af14d51876ed75ce72ff14926a883efe9251b11f9f3d5b10a
  isoURL: http://192.168.18.6:8000/harvester-7cc04b5-dirty-amd64.iso
  minUpgradableVersion: 0.3.0
  releaseDate: "20211231"
  tags:
  - dev
  - test
```
4. Create a Upgrade CR.
```
apiVersion: harvesterhci.io/v1beta1
kind: Upgrade
metadata:
  generateName: hvst-upgrade-
  namespace: harvester-system
spec:
  version: "1.0.2"
```
5. Upgrade process starts but can't finish.

**Expected behavior**
Upgrade process can finish.

**Support bundle**
[upgrade-log.zip](https://github.com/harvester/harvester/files/8314345/upgrade-log.zip)

**Environment:**
 - Harvester ISO version: `v1.0.0` to `master-370eca2a-head`
 - Underlying Infrastructure: KVM

https://github.com/harvester/harvester/issues/1861
