### ISSUE TITLE
[BUG] Harvester fails to pull Rancher agent image from private registry

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2175]
**Describe the bug**
When registering Harvester with Rancher in an air-gapped infrastructure,  Harvester fails to pull the `cattle-cluster-agent` image from the private registry due to certificate errors.

**To Reproduce**

1. Create a private PKI consisting of root CA and server certificate
2. Setup a private container registry, e.g. Harbor, using the server certificate
3. Mirror the `rancher/rancher-agent` image to the private registry
4. Configure the private registry as "system-default-registry" in the Rancher settings
5. Configure the private CA root certificate in Harvester settings -> additional-ca
6. Register Harvester cluster in Rancher

**Expected behaviour**

Additional CA certificate is added to Harvester OS trust store. Harvester successfully pulls the image.

**Actual behaviour**

Registration fails. Harvester fails to pull the `cattle-cluster-agent` image  from the private registry because the certificate CA is not trusted.

**Comment by FrankYang0529** [comment]
Currently, the workaround for this issue is adding the crt file to `/etc/pki/trust/anchors` and running `update-ca-certificates` on each host.

If we want to fix this issue properly, we need to introduce `harvester-system-agent` for handling system stuff. I tried to use following YAML to mount host folder and `harvester-additional-ca` secret to a container. In this container, I try to move `additional-ca.pem` to `/host/etc/pki/truct/anchors` and run `update-ca-certificates`. Although the file appears on the host, running `update-ca-certificates` in the container cannot influence the host.

cc @guangbochen @bk201 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sync-additional-ca
  namespace: harvester-system
spec:
  selector:
    matchLabels:
      name: sync-additional-ca
  template:
    metadata:
      labels:
        name: sync-additional-ca
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: sync-additional-ca
        image: alpine
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: additional-ca
          mountPath: /var/ca
        - name: host
          mountPath: /host
      terminationGracePeriodSeconds: 30
      volumes:
      - name: additional-ca
        secret:
          secretName: harvester-additional-ca
      - name: host
        hostPath:
          path: /
```
