### ISSUE TITLE
[BUG] unable to use `external` cloud provder with k3s or rke2 with harvester node driver

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2213]
**Describe the bug**
when using the `external` option, cluster provisioning fails with error `waiting for cluster agent to connect`

**To Reproduce**
1. provision an rke2 or k3s cluster in rancher using the harvester node driver
  * Set cloud provider to `external`

**Expected behavior**
cluster fails to provision with error `waiting for cluster agent to connect`

**Support bundle**

[supportbundle_155a611c-191c-47af-9920-c2c29b580fb7_2022-04-29T20-55-10Z.zip](https://github.com/harvester/harvester/files/8594692/supportbundle_155a611c-191c-47af-9920-c2c29b580fb7_2022-04-29T20-55-10Z.zip)

**Environment:**
 - Harvester ISO version:  v1.0.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge r510

**Comment by ibrokethecloud** [comment]
@slickwarren did you deploy the external harvester cloud provider? 

I just ran a similar test with Rancher 2.6.5-rc6 and Harvester v1.0.2-rc1 and followed the following steps:

![image](https://user-images.githubusercontent.com/19664014/166180931-7bed9e34-95b2-4dd3-b79b-4dcc0ea86d5f.png)

Since there is no cloud provider enabled, I have added the same via Additional Manifests option:

![image](https://user-images.githubusercontent.com/19664014/166180952-349cfc39-131c-4432-a8e6-5b516b912127.png)

The harvester cloud provider helm chart needs the cloud credentials to be injected via a cloud-config file located at `/etc/kubernetes/cloud-config`

This was done via the userdata section and write_files directive:
![image](https://user-images.githubusercontent.com/19664014/166181094-737172b8-6f8f-4991-8016-776fd9c2612b.png)

After a few minutes the cluster should be running

![image](https://user-images.githubusercontent.com/19664014/166181115-8bec89d3-6180-426c-9939-1ddfea29229f.png)

![image](https://user-images.githubusercontent.com/19664014/166181128-7d965d50-3bab-41e0-ab69-aaa200d4da50.png)

**Comment by TachunLin** [comment]
Try to reproduce this issue on Rancher v2.6.5-rc6 with Harvester v1.0.2-rc1. 
Can provision K3s cluster with and without external cloud provider.

1. By default, while we select K3s version, there is no cloud provider drop down menu at the right side
  ![image](https://user-images.githubusercontent.com/29251855/166131452-010c32ed-270d-44ed-a437-1f41b0483232.png)

2. We can set `cloud-config=external` in the kubelet Args instead
  ![image](https://user-images.githubusercontent.com/29251855/166189212-d422a433-7ac7-4f26-80fd-452c6df966ae.png)

3. Then we can have provisioned K3s cluster in `Running` status 
  ![image](https://user-images.githubusercontent.com/29251855/166207644-282bcd36-d5fd-47df-92d0-fbc6320f0a45.png)
  ![image](https://user-images.githubusercontent.com/29251855/166207676-a39d95c1-8423-4ca0-abc5-2cc7f693de10.png)

#### Additional Context
Without setting `cloud-config=external`, we can also provision the K3s cluster to active status.

**Comment by slickwarren** [comment]
@ibrokethecloud could you share your setup with me offline? I attempted the following, but still could not get the cluster up:

provision an rke2 cluster (1.23.6+rke2r1) from rancher (v2.6-head 5e1bfc0)

* multi node cluster (1 etcd, 1 controlplane, 1 worker) also tested with a single node cluster (all roles, 1 node)
  * set cloud provider to `external`
  * add the following to the additional manifest section

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harvester-cloud-provider
  namespace: kube-system
spec:
  targetNamespace: kube-system
  bootstrap: true
  repo: https://charts.harvesterhci.io/
  chart: harvester-cloud-provider
  version: 0.1.12
  helmVersion: v3
```
  * and add the following under `user-data` for each node, replacing with your b64 encoded kubeconfig of the harvester cluster:
```
write_files:
  - content: >-
      <base64_encoded_kubeconfig_of_harvester_cluster>
    encoding: b64
    owner: root:root
    path: /etc/kubernetes/cloud-config
    permissions: '0644'
```

**Comment by TachunLin** [comment]
Try to reproduce this issue on Rancher v2.6.5-rc6 with Harvester v1.0.2-rc1. 

#### Result
By adding the 
1. Cloud credentials and namespace to user data cloud config
2. Add the helm chart to additional manifest section
 
Then we can provision RKE2 cluster with `external` harvester cloud provider.
  ![image](https://user-images.githubusercontent.com/29251855/166886929-df9bdeb7-4ec3-404e-ba95-c4afd857a189.png)
  ![image](https://user-images.githubusercontent.com/29251855/166887570-a6d0e21d-183f-44fe-9adf-d1283637f890.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: v1.0.2-rc1
* Rancher version: v2.6-head (4bbee59)

### Verify Steps
1. Import Harvester in Rancher UI
2. Create cloud credential 
3. Access Harvester dashboard 
4. Go to support page
5. Download KubeConfig yaml file to local drive
6. Add `namespace: default` under the context
  ![image](https://user-images.githubusercontent.com/29251855/166884511-29078c1e-5f2c-452c-b83e-537bc86acf69.png)
7. Execute `cat harv-provo.yaml | base64 -w 0 >> provo_output.txt` to generate the base64 encoded kubeconfig of harvester cluster and copy it. 
8. Provision a RKE2 cluster 
  ![image](https://user-images.githubusercontent.com/29251855/166884315-a2ca196a-5c75-4cbe-bd48-0e18739d36c0.png)
9. Paste the <base64_encoded_kubeconfig_of_harvester_cluster> to the User Data cloud config
```
 ​#cloud-config
 ​package_update: true
 ​packages:
   ​- qemu-guest-agent
 ​users:
   ​- default
   ​- groups: users
     ​lock_passwd: false
     ​name: demo
     ​passwd: <password>
     ​shell: /bin/bash
     ​sudo: ALL=(ALL) NOPASSWD:ALL
 ​write_files:
   ​- content: >-
       <base64_encoded_kubeconfig_of_harvester_cluster>​
     ​encoding: b64
     ​owner: root:root
     ​path: /etc/kubernetes/cloud-config
     ​permissions: '0644'
``` 
  ![image](https://user-images.githubusercontent.com/29251855/166885680-dfffc904-b574-40e7-b2ab-47add7fecc6d.png)

10. Select cloud provider option to `external`
  ![image](https://user-images.githubusercontent.com/29251855/166885362-ed96f101-b688-47df-aa50-1f573f94bdd1.png)
11. Add the following helm chart to additional manifest section
  ```
  apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    name: harvester-cloud-provider
    namespace: kube-system
  spec:
    targetNamespace: kube-system
    bootstrap: true
    repo: https://charts.harvesterhci.io/
    chart: harvester-cloud-provider
    version: 0.1.12
    helmVersion: v3
  ```
  ![image](https://user-images.githubusercontent.com/29251855/166885417-ae803196-833f-4bbc-9bab-4dbc43b14753.png)

12. Wait for the RKE2 provisioning finish 
13. Check the cloud provider apps
