### ISSUE TITLE
[FEATURE] Alternate endpoint to serve harvester IPXE artifacts

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#2226]
**Is your feature request related to a problem? Please describe.**

Currently Harvester IPXE artifacts are served via https://releases.rancher.com

After a change last year, which involved migrating the DNS hosting and SSL termination https://github.com/rancher/rancher/issues/35419 IPXE booting on public cloud providers like Equinix metal is broken.

This is likely because the cert chain is too large, and how IPXE handles the cert chain and more details can be found here: https://github.com/ipxe/ipxe/pull/116

Some additional context: https://github.com/flatcar-linux/Flatcar/issues/527

**Describe the solution you'd like**

A different artifact endpoint say `releases.harvesterhci.io` pointing to the same backend but serving a different (smaller) cert chain.

**Describe alternatives you've considered**

**Additional context**

**Comment by antonym** [comment]
Can confirm... unable to boot kernels directly from [releases.rancher.com](https://releases.rancher.com) endpoint via iPXE.

**Comment by hrittikhere** [comment]
Looking for updates. I can't boot via iPXE too

**Comment by antonym** [comment]
Ended up mirroring the release as a GitHub release which lets me boot from iPXE.

**Comment by hwinkel** [comment]
hey, it's vital to bring up a Harvester Cluster in our EQXM Locations. Can you fix this please otherwise it stucks

**Comment by hwinkel** [comment]
> Ended up mirroring the release as a GitHub release which lets me boot from iPXE.

can you provide some hints how to do it?

**Comment by antonym** [comment]
I have a release mirror here and iPXE seems to be fine with it downloading it from Github Releases:

https://github.com/netbootxyz/asset-mirror/releases/tag/v1.0.1-e4b9482d

The code to create the release is [here](https://github.com/netbootxyz/asset-mirror/tree/harvester), all it's doing is downloading it from releases.rancher.com/harvester and pushing it into a Github release.

**Comment by hwinkel** [comment]
many thanks, I will try the Release URLs for a trial and trial only.

**Comment by ibrokethecloud** [comment]
We are working to internally address the hosting aspect.

For now I have set up a sample endpoint for testing `https://harvester.ibrokethe.cloud`

A sample script leveraging the same to boot in equinix metal is available here: https://github.com/ibrokethecloud/custom_pxe/blob/master/mac.ipxe

**Comment by hrittikhere** [comment]
> We are working to internally address the hosting aspect.
> 
> For now I have set up a sample endpoint for testing `https://harvester.ibrokethe.cloud`
> 
> A sample script leveraging the same to boot in equinix metal is available here: https://github.com/ibrokethecloud/custom_pxe/blob/master/mac.ipxe

Hey @ibrokethecloud 
This helps to boot.
Can you also please provide the userdata? My SOS portal shows eth0 not found and I am confused about what to do next.

**Comment by ibrokethecloud** [comment]
@hrittikhere here is the full sample: https://github.com/ibrokethecloud/harvester-equinix-terraform-sample

You dont need to specify the management interfaces in userdata since that is now being looked up by the installer via the mac address info passed as kernel arguments.

**Comment by hrittikhere** [comment]
Thanks @ibrokethecloud ! Not that familiar with Terraform so I will look into it. Any ways to not go the terraform part and just change the interfaces in user data? 
```yaml
#cloud-config
token: token  # replace with a desired token
os:
  ssh_authorized_keys:
  - ssh-rsa ...  # replace with your public key
  password: p@ssword  # replace with a your password
install:
  mode: create
  networks:
    harvester-mgmt: # The management bond name. This is mandatory.
      interfaces:
      - name: eth0
      default_route: true
      method: dhcp
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  tty: ttyS1,115200n8
```
