### ISSUE TITLE
[FEATURE] Add upgrade information panel about versions

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2299]
**Is your feature request related to a problem? Please describe.**

The user can select a version from the drop-down list, but there is no further information about the selected version.

<img width="515" alt="upgrade_select_version" src="https://user-images.githubusercontent.com/1691518/169499099-e7428a7e-97cf-4972-a2f1-8314d7ad9bc9.png">

**Describe the solution you'd like**

We can display more information for a release, for example:
- Any important information or known issues before users perform an upgrade.
- Release notes or link to it.

**Describe alternatives you've considered**

**Additional context**

## Backend changes

We can add new fields in the Version CRD: https://github.com/harvester/harvester/blob/master/pkg/apis/harvesterhci.io/v1beta1/version.go and the field value should be content to display. It can be markdown text to be rendered pretty in the frontend.

**Comment by bk201** [comment]
After some discussion with @guangbochen and @WuJun2016, for now, we plan to add two links in the dialog:
- New version's release-note: For example, https://github.com/harvester/harvester/releases/tag/v1.0.2
- Upgrade document: https://docs.harvesterhci.io/v1.0/upgrade/automatic/, users can know version-specific notes and known issues.

**Comment by noahgildersleeve** [comment]
Tested with v1.0.3. 
## Verification steps
1. Create version.yaml on control node of Harvester
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.0.3
  namespace: harvester-system
spec:
  isoChecksum: ce7ed0a0042cb910505c4d3c99b68cb6cafc8838969d9c2d975e6e1d4e50a7ec600fdb76a48dee32a8c0486d86ae3953eafed4a1eeb47fa8115483bf5e12c146
  isoURL: https://releases.rancher.com/harvester/v1.0.3/harvester-v1.0.3-amd64.iso
```
2. Create version with kubectl on control node `kubectl create -f version.yaml`
3. Log in and click Upgrade button
![Screenshot_20220816_120948](https://user-images.githubusercontent.com/83787952/184962383-bd860a4e-e069-42d8-aff8-d903cce8c8c8.png)
4. Verify that upgrade page has associated text and links for `pre-upgrade checks` and `more info`
![Screenshot_20220816_120740](https://user-images.githubusercontent.com/83787952/184962561-b9a67bb0-6ab7-424a-9503-7ec5b5f20f9f.png)
5. Click through link for `pre-upgrade checks` and verify that it forwards to `https://docs.harvesterhci.io/v1.0/upgrade/automatic/`
![Screenshot_20220816_120647](https://user-images.githubusercontent.com/83787952/184962756-ba908824-6918-409f-b9b3-076873701129.png)
6. Click `More Info` and verify that it forwards to the release page for the version that you are upgrading to
![Screenshot_20220816_120749](https://user-images.githubusercontent.com/83787952/184962842-f174e486-7aea-4b58-a314-de2ae31d51d4.png)
