### ISSUE TITLE
[FEATURE] Integrate with IP address management system(s)

### ISSUE THREAD

**Issue by eshenayo** [harvester/harvester#2341]
**Is your feature request related to a problem? Please describe.**
When adding a static IP to a VM, there is (seemingly) no automated way to do this. 

**Describe the solution you'd like**
Provide an option to integrate with [Mice and Men](https://docs.menandmice.com/en/9.3/) - or some other IP address management system to enable credentialed queries for retrieving a free IP addresses in a range that can be assigned to the VM.

**Describe alternatives you've considered**
At present, I am using a network data template and modifying the address,

```yaml
network:
  version: 1
  config:
  - id: eth0
    name: eth0
    subnets:
    - address: x.x.x.x  # <-- address to modify
      gateway: x.x.x.x
      type: static
      dns_nameservers: 
      - x.x.x.x
    type: physical
```
**Additional context**
* [Mice and Men REST API](https://docs.menandmice.com/en/10.2/guides/user-manual/rest_api/)
