### ISSUE TITLE
[BUG] Instance metadata variables are not expanded

### ISSUE THREAD

**Issue by eshenayo** [harvester/harvester#2342]
**Describe the bug**
Cloud config templates do not expand [metadata variables](https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html)

In the VM, the instance-data.json file has the ds.meta_data.local-hostname variable
![image](https://user-images.githubusercontent.com/8902109/171301667-f3ca6040-704b-4349-82a2-21fa24ccb738.png)

When used in the cloud-init file [as documented](https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html), the variable expansion is not done, instead, the value is the string.

**To Reproduce**
```yaml
#cloud-config
write_files:
  - content: |
      #!/bin/bash
      vmName=$1
      echo "VM Name is: $vmName" > /run/cloud-init/cloudinitscript.log
    path: /run/cloud-init/exec_initscript.sh
    permissions: '0755'
runcmd:
  - - /run/cloud-init/exec_initscript.sh 
    - "{{ ds.meta_data.local-hostname }}"
```
1. Create VM using the above cloud-config template
2. Log into the VM and cat the file /run/cloud-init/cloudinitscript.log
3. You will see that instead of the VM name, you have the contents "{{ ds.meta_data.local-hostname }}"

**Expected behavior**
The file should contain the hostname of the VM. Example: If the VM hostname is testing123, the file should contain the string testing123.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal ProLiant BL460c Gen9

**Additional context**

**Comment by janeczku** [comment]
The steps to reproduce this issue are not correct, since in order to render metadata variables, the first line of the cloud-config / user-data must begin with  `## template: jinja`

>Both user-data scripts and #cloud-config data support jinja template rendering. When the first line of the provided user-data begins with, ## template: jinja cloud-init will use jinja to render that file. Any instance-data-sensitive.json variables are surfaced as jinja template variables because cloud-config modules are run as ‘root’ user.
Ref: https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html#instance-metadata

The bug appears to be that Harvester strips this line before storing the user-data in the config-drive.
So when configuring a cloud-config template starting with:

```
## template: jinja
#cloud-config
write_files:
```

the user-data included in the config-drive will actually become:

```
#cloud-config
write_files:
```
which then causes cloud-init *not* to expand the metadata template.

**Comment by eshenayo** [comment]
Yes, thank you for the correction!

**Comment by WuJun2016** [comment]
> **Describe the bug** Cloud config templates do not expand [metadata variables](https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html)
> 
> In the VM, the instance-data.json file has the ds.meta_data.local-hostname variable ![image](https://user-images.githubusercontent.com/8902109/171301667-f3ca6040-704b-4349-82a2-21fa24ccb738.png)
> 
> When used in the cloud-init file [as documented](https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html), the variable expansion is not done, instead, the value is the string.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> ```yaml
> #cloud-config
> write_files:
>   - content: |
>       #!/bin/bash
>       vmName=$1
>       echo "VM Name is: $vmName" > /run/cloud-init/cloudinitscript.log
>     path: /run/cloud-init/exec_initscript.sh
>     permissions: '0755'
> runcmd:
>   - - /run/cloud-init/exec_initscript.sh 
>     - "{{ ds.meta_data.local-hostname }}"
> ```
> 
> 1. Create VM using the above cloud-config template
> 2. Log into the VM and cat the file /run/cloud-init/cloudinitscript.log
> 3. You will see that instead of the VM name, you have the contents "{{ ds.meta_data.local-hostname }}"
> 
> **Expected behavior** The file should contain the hostname of the VM. Example: If the VM hostname is testing123, the file should contain the string testing123.
> 
> **Support bundle**
> 
> **Environment**
> 
> * Harvester ISO version: v1.0.0
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal ProLiant BL460c Gen9
> 
> **Additional context** Add any other context about the problem here.

Hi,  @eshenayo  I fixed the issue, but I couldn't get it to run using the cloud-config you provided, and I tested that the issue was fixed using another example.    https://github.com/harvester/dashboard/pull/345#issue-1279815731

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/177121301-f30bf8ec-0a70-4549-b11b-895161ee30ad.png)


Test Information
----
* Environment: **Bare metal DL160G9 5 nodes**
* Harvester Version: **master-949bbb0c-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM with following _CloudConfig_
```yaml
## template: jinja
#cloud-config
package_update: true
password: password
chpasswd: { expire: False }
sshpwauth: True
write_files:
  - content: |
      #!/bin/bash
      vmName=$1
      echo "VM Name is: $vmName" > /home/cloudinitscript.log
    path: /home/exec_initscript.sh
    permissions: '0755'
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - - echo
    - "{{ ds.meta_data.local_hostname }}"
  - - /home/exec_initscript.sh
    - "{{ ds.meta_data.local_hostname }}"
packages:
  - qemu-guest-agent
```

5. login to the VM
    - file `/home/exec_initscript.sh` should exists
    - file `/home/cloudinitscript.log` should exists
    - execute `cat /home/cloudinitscript.log`, VM name should be the same as the VM.
