### ISSUE TITLE
Broken deployment with  Equinix Metal - C3 family

### ISSUE THREAD

**Issue by all4innov** [harvester/harvester#2360]
It's impossible to deploy Harvester via **iPXE** in **Equinix Metal** - **C3 family**
 (Harvester last available demos/code was mainly based on old decommissioned **C1 family**)

In case of I am missing something, here the used config files :

**ipxe-install**
```
#!ipxe

kernel https://releases.rancher.com/harvester/v1.0.0/harvester-v1.0.0-vmlinuz-amd64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:https://releases.rancher.com/harvester/v1.0.0/harvester-rootfs-amd64.squashfs console=ttyS1,115200 harvester.install.automatic=true harvester.install.config_url=https://metadata.platformequinix.com/userdata
initrd https://releases.rancher.com/harvester/v1.0.0/harvester-v1.0.0-initrd-amd64
boot
```

**userdata-create.yaml**
```
#cloud-config
token: token
os:
  ssh_authorized_keys:
  - ssh-rsa AAAABxxxxxxxx
  password: password
install:
  mode: create
  networks:
    harvester-mgmt:
      interfaces:
      - name: eno1
      default_route: true
      method: dhcp
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/v1.0.0/harvester-v1.0.0-amd64.iso
  tty: ttyS1,115200n8
  ```

**Comment by all4innov** [comment]
@bk201 @robertvolkmann  any idea or return of experience ? Thanks in advance

**Comment by puttappa-raghavendra** [comment]
facing the same issue as @all4innov

**Comment by ibrokethecloud** [comment]
@all4innov @puttappa-raghavendra the issue stems from the pxe environment not trusting the CA cert on releases.rancher.com. We dont serve a http endpoint so the best idea would be to the harvester artifacts on an http endpoint and refer those in the PXE script.

**Comment by all4innov** [comment]
@ibrokethecloud  right and working when using local http server, big thanks

**Comment by puttappa-raghavendra** [comment]
@ibrokethecloud @all4innov While installing Harvester, I am getting the below error.

**Fetching https://metadata.platformequinix.com/userdata...  │
interface not found: eth0**

Even I tried to use **eno1**, but the result is the same (interface not found).

`https://metadata.platformequinix.com/userdata `- is this a valid endpoint?

` curl https://metadata.platformequinix.com/userdata` returns nothing inside the metal server.

--------
Configuration: 
----
Server type: c3.medium.x86
-----
```
#cloud-config
token: metal-token           
os:
  ssh_authorized_keys:
  - ssh-rsa ***
  password: metaltoken 
  hostname: harvester-rancher-01
install:
  mode: create
  networks:
    harvester-mgmt:
      interfaces:
      - name: eth0
      default_route: true
      method: dhcp
  device: /dev/sda
  iso_url: http://10.10.10.10/harvester/harvester-v1.0.0-amd64.iso 
  tty: ttyS1,115200n8
```

**Comment by all4innov** [comment]
@puttappa-raghavendra  same issue too 
i tried even other combination of the network interface  :
```
enp0s0f0np0
enp0s0f1np1
enp1s0f0np0
enp1s0f1np1
```

**Comment by robertvolkmann** [comment]
@all4innov try the following:
* Deactivate interface renaming by setting `net.ifnames=0` instead of `net.ifnames=1`
* Use eth0 as interface name
* Configure a static vip - allocate it beforehand in equinix

**Comment by cprivitere** [comment]
For the record, on a c3.medium.x86, it looks like the interface names are:
ens3f0
ens3f1

Also it looks like the userdata-create.yaml needs to have a VIP address in it for the install to work. So putting that all together, here's what worked for me.

1. Put the artifacts on a web server.
2. Allocate an Elastic IP to use for your VIP (you can also skip this and just use the public IP as the VIP IP, but you'd have to wait until after the server was created to know what that IP would be).
3. Here's what I used for a userdata-create.yaml (aka what i paste into userdata)
```
token: token
os:
  hostname: node1
  ssh_authorized_keys:
  - ssh-rsa <blahblahblah> username@hostname
  password: rancher
install:
  mode: create
  networks:
    harvester-mgmt:
      interfaces:
      - name: ens3f0
      - name: ens3f1
      method: dhcp
      bond_options:
        mode: 802.3ad
        miimon: 100
  device: /dev/sda
  iso_url: http://mywebserver.example.com/harvester-v1.0.0-amd64.iso
  vip: <elastic ip address>
  vip_mode: static
  tty: ttyS1,115200n8
```
4. Here's my ipxe-install:
```
#!ipxe
kernel harvester-v1.0.0-vmlinuz-amd64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl console=ttyS1,115200n8 root=live:http://cyclones.figarocastle.org:8443/harvester-v1.0.0-rootfs-amd64.squashfs harvester.install.automatic=true harvester.install.config_url=https://metadata.platformequinix.com/userdata
initrd harvester-v1.0.0-initrd-amd64
boot
```
5. Go ahead and provision the server in Equinix Metal just like the example guide says, pasting your userdata-create.yaml contents into userdata, and then while the server is booting, assign the Elastic IP you allocated earlier to the server.

**Comment by all4innov** [comment]
@cprivite big thanks as it works (even randomly sometimes not). Curious how we can find the interface names for other instance types with harvester deployment.

**Comment by cprivitere** [comment]
> @cprivite big thanks as it works (even randomly sometimes not). Curious how we can find the interface names for other instance types with harvester deployment.

Yeah I'm leaning towards the net.ifnames=0 direction to work around that, but so far my attempts using that option have all failed.

**Comment by ibrokethecloud** [comment]
Another possible option is to provide hwAddress instead of interface names, but that does mean that the mac address is known.

```
  networks:
    harvester-mgmt:
      interfaces:
      - hwAddr: '0c:c4:7a:6b:84:20'
```

It still leads to the minor issue that mac address is not known until you launch the instance. One option may be to launch the node with a pxe script which just runs the pxe shell. Once instance is provisioned the mac address can be queried from pxe prompt using `echo ${net0/mac}`. This can then be used to populate the userdata with the correct create / join configuration.

The PR: https://github.com/harvester/harvester-installer/pull/225, when available with the next release, will allow you to skip this step, as now the hwAddress arguments can be just passed via the kernel arguments.

So something like this ``` harvester.install.networks.harvester-mgmt.interfaces="hwAddr: ${net0/mac}" ``` as the kernel arguments in the pxe script will do the job.
