### ISSUE TITLE
[BUG] Could not bump Longhorn dependency to 1.3.0

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2404]
**Describe the bug**

When bumping Longhorn from 1.2.4 to 1.30 in a running cluster, longhorn-manager can't start with the error:
```
longhorn-manager time="2022-06-20T10:29:56Z" level=fatal msg="Error starting manager: fail to set the setting taint-toleration with invalid value kubevirt.io/drain:NoSchedule: cannot modify toleration setting before all volumes are detached"
```

This could be a blocker when the user wants to upgrade from v1.0.3 to v1.1.0.
**Note** A new cluster works well, this only happens during an upgrade.

**To Reproduce**
1. Create a cluster.
2. Edit cluster-repo deployment: `kubectl edit deployment/harvester-cluster-repo -n cattle-system`
3. Update `.spec.template.spec.containers[0]` from
    ```
        spec:
          containers:
          - image: rancher/harvester-cluster-repo:v1.0.2
            imagePullPolicy: IfNotPresent
    ```
    to
    ```
        spec:
          containers:
          - image: bk201z/harvester-cluster-repo:v1.0.2-lh-1.3.0
            imagePullPolicy: Always
    ```
    This uses a pre-packaged cluster-repo image that contains the Longhorn bump.
4. Wait for a while, the chart will be re-applied.
5. Seeing longhorn-manager errors:
    <img width="1185" alt="Screen Shot 2022-06-20 at 6 35 48 PM" src="https://user-images.githubusercontent.com/1691518/174712524-07b59aff-7162-4ff9-bceb-0391bdf7be6b.png">

Log: [longhorn-system-longhorn-manager-5dhd2-1655721003767997385.log](https://github.com/harvester/harvester/files/8945622/longhorn-system-longhorn-manager-5dhd2-1655721003767997385.log)

**Expected behavior**

Longhorn components should be upgraded.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Here are some comments from Longhorn team:

LH didn’t validate the settings from configmap before, so it was not a prob.
we do two new things in v1.3.0
- move the validation logic to webhook
- configmap can sync to settings CR during upgrade
So the syncing may error out caused by the validation failure in the webhook.

The issue is planned to be addressed in v1.3.1.
