### ISSUE TITLE
[Question] How do I change the DNS server used by the Harvester cluster?

### ISSUE THREAD

**Issue by reesericci** [harvester/harvester#2430]
It seems any change I make to either /etc/resolv.conf or /etc/sysconfig/network/config seems to be reversed on reboot, and I need to change the DNS server used by my cluster.

How can I change my DNS server permanently?

Thanks!

--reese

**Comment by Martin-Weiss** [comment]
I assume you have to adjust /oem/99_custom.yaml and then reboot.

**Comment by bk201** [comment]
@reesericci As a quick workaround without touching the original configuration file. You can create a file `/oem/99_more_custom.yaml` and replace the desired DNS server:
```
name: More Harvester Configuration
stages:
  initramfs:
  - commands:
    - sed -i 's/^NETCONFIG_DNS_STATIC_SERVERS.*/NETCONFIG_DNS_STATIC_SERVERS="8.8.8.8"/' /etc/sysconfig/network/config
```
