### ISSUE TITLE
[BUG] VM Cloud Config initial failed without any errors

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2468]
### Describe the bug
When Creating VM with customized **cloud config** as below, the cloud-init will failed without any errors.
```yaml
# cloud-config
password: password
chpasswd: { expire: False }
sshpwauth: True
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
```

### To Reproduce
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM with _the cloud config_ above
4. Start the VM and login via _Web VNC_
5. User should able to login with the password

### Expected behavior
Cloud config should be applied.

## Environment:
 - Harvester ISO version: **v1.0-3b6ab0d1-head** and **master-a926a44e-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
![image](https://user-images.githubusercontent.com/5169694/177765887-a61216e0-a0a8-49dc-9433-8cd7ff6dcc7f.png)
