### ISSUE TITLE
[BUG] VM's user data added via Edit as YAML will not display on config tab

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2584]
### Describe the bug
When user add/update `userData` or `networkData` by `Edit as YAML`, UI will not display those content.
This would be a bug when user create the VM by YAML, then update it by the form, cloudinit's data will lost.

#2503 should be encountered the same root cause.

### To Reproduce

https://user-images.githubusercontent.com/5169694/181270084-b7bb1177-85ba-4218-af42-1083624cb294.mp4

### Expected behavior
User should able to edit them via form or yaml.

## Environment:
 - Harvester ISO version: **v1.0.3-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

**Comment by lanfon72** [comment]
After edit by form, the will not able to start.

![image](https://user-images.githubusercontent.com/5169694/181271040-7b9f192b-c982-40d5-8a53-e62bc2cd0c79.png)

**Comment by lanfon72** [comment]
Verified this bug not fixed in the main case: 

https://user-images.githubusercontent.com/5169694/186124384-a8cd6a97-aae8-4002-ba53-56235a936e01.mp4

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-dc6a3089-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2584#issue-1319636738

**Comment by lanfon72** [comment]
@guangbochen, @WuJun2016 I think this issue might need some backend fix?

the latest fix still encountered same error:
![image](https://user-images.githubusercontent.com/5169694/187641764-4849b14b-b1af-4242-ad24-433aa2f1f4e7.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-4ea12f4f-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create an Image for VM creation
3. Create VM `vm1` by form with customized **User Data**
4. Update `vm1` by `Edit YAML`, replace `spec.spec.cloudInitNoCloud.secretRef` to `UserData` (plain text)[^1]
5. Restart `vm1`, VM should started successfully


[^1]:  ![image](https://user-images.githubusercontent.com/5169694/187644525-89d75a7e-5e18-420c-b900-433de823b6ed.png)

**Comment by WuJun2016** [comment]
@lanfon72  cloud-init will only take effect the first time you apply it, but the later changes will not take effect unless you go into os and make it take effect manually.

**Comment by lanfon72** [comment]
@WuJun2016 yeah the problem here is, VM will not able to start after update VM's cloudconfig via Edit YAML.

**Comment by WuJun2016** [comment]
@lanfon72  Sorry, I didn't notice the reproduction step

@futuretea   Can you help to see if you support saving cloudInit in both ways ?

**Comment by futuretea** [comment]
currently, 
1. networkData and userData use same secret
2. if user didn't specify any content in networkData input box. there are no `networkdata` key in the secret

@WuJun2016 solution: UI add `networkdata` key to the secret always

wrong:
```yaml
apiVersion: v1
data:
  userdata: I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlczoKICAtIHFlbXUtZ3Vlc3QtYWdlbnQKcnVuY21kOgogIC0gLSBzeXN0ZW1jdGwKICAgIC0gZW5hYmxlCiAgICAtIC0tbm93CiAgICAtIHFlbXUtZ3Vlc3QtYWdlbnQuc2VydmljZQo=
kind: Secret
metadata:
  labels:
    harvesterhci.io/cloud-init-template: harvester
  name: vm1-4xsyw
  namespace: default
type: secret
```

correct:
```yaml
apiVersion: v1
data:
  networkdata: ""
  userdata: I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlczoKICAtIHFlbXUtZ3Vlc3QtYWdlbnQKcnVuY21kOgogIC0gLSBzeXN0ZW1jdGwKICAgIC0gZW5hYmxlCiAgICAtIC0tbm93CiAgICAtIHFlbXUtZ3Vlc3QtYWdlbnQuc2VydmljZQo=
kind: Secret
metadata:
  labels:
    harvesterhci.io/cloud-init-template: harvester
  name: vm1-4xsyw
  namespace: default
type: secret
```
