### ISSUE TITLE
[BUG] fix alert VirtOperatorDown

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2615]
**Describe the bug**

When enableing `alertmanager`, continuous `VirtOperatorDown` is seeing.

**To Reproduce**
**Without `alertmanager` enabled:**

In below link, VirtOperatorDown alert is there.
https://the-cluster-vip/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/

**With `alertmanager` enabled:**

1.  Install harvester
2.  Enable alertmanager, add receiver
3.  `VirtOperatorDown` alert comes up

```
192.168.122.195:65393 - - [28/Jul/2022 08:35:32] "HTTP/1.1 POST /" - 200 OK
DATA RECEIVED:2022-07-28 08:45:07.627901
b'{"receiver":"test_py_receiver","status":"firing","alerts":[{"status":"firing","labels":
{"alertname":"VirtOperatorDown","kubernetes_operator_component":"kubevirt","kubernetes_operator_part_of":
"kubevirt","prometheus":"cattle-monitoring-system/rancher-monitoring-prometheus","severity":"critical"},"annotations":{"runbook_url":"https://kubevirt.io/monitoring/runbooks/VirtOperatorDown",
"summary":"All virt-operator servers are down."},"startsAt":"2022-07-28T08:44:37.618Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://rancher-monitoring-prometheus.cattle-monitoring-system:9090/graph?g0.expr=kubevirt_virt_operator_up_total+%3D%3D+0\\u0026g0.tab=1","fingerprint":"9463c3a7f5695fef"}],
"groupLabels":{"alertname":"VirtOperatorDown"},"commonLabels":{"alertname":"VirtOperatorDown","kubernetes_operator_component":"kubevirt","kubernetes_operator_part_of":"kubevirt",
"prometheus":"cattle-monitoring-system/rancher-monitoring-prometheus","severity":"critical"},"commonAnnotations":{"runbook_url":"https://kubevirt.io/monitoring/runbooks/VirtOperatorDown",
"summary":"All virt-operator servers are down."},"externalURL":"http://rancher-monitoring-alertmanager.cattle-monitoring-system:9093","version":"4","groupKey":"{}:{alertname=\\"VirtOperatorDown\\"}","truncatedAlerts":0}\n'

```

But the kube-virt related PODs are working well

```
arvester-system            virt-api-79bc89595-fkhjg                                 1/1     Running     33         12d
harvester-system            virt-api-79bc89595-tgn42                                 1/1     Running     32         12d
harvester-system            virt-controller-6c76d8659-7qgml                          1/1     Running     32         12d
harvester-system            virt-controller-6c76d8659-fsh5l                          1/1     Running     31         12d
harvester-system            virt-handler-25t2t                                       1/1     Running     29         12d
harvester-system            virt-operator-78b84587c9-5dvpd                           1/1     Running     34         12d
```

**Expected behavior**

There should not be such kind of alert.

**Support bundle**

**Environment**
 - Harvester ISO version:  V1.0 and master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM-based

**Additional context**

The issues was caused by that, the `virt-operator-*` POD does not set label `prometheus.kubevirt.io` as `true` , `prometheus` won't fetch POD status which has no such label.

```

harv1:~ # kk get pods -n harvester-system virt-handler-25t2t -o JSON | grep prom
            "prometheus.kubevirt.io": "true"

harv1:~ # kk get pods -n harvester-system virt-controller-6c76d8659-7qgml -o JSON | grep prom
            "prometheus.kubevirt.io": "true"

harv1:~ # kk get pods -n harvester-system virt-operator-78b84587c9-5dvpd -o JSON | grep prom
            "prometheus.kubevirt.io": ""

harv1:~ # kk get pods -n harvester-system harvester-756cd66d6d-dcv2g -o JSON | grep prom
harv1:~ # 
```

The alert `VirtOperatorDown` is defined as such:

```
    - expr: sum(up{namespace='harvester-system', pod=~'virt-operator-.*'}) or vector(0)
      record: kubevirt_virt_operator_up_total
      
    - alert: VirtOperatorDown
      annotations:
        runbook_url: https://kubevirt.io/monitoring/runbooks/VirtOperatorDown
        summary: All virt-operator servers are down.
      expr: kubevirt_virt_operator_up_total == 0
      for: 10m
      labels:
        kubernetes_operator_component: kubevirt
        kubernetes_operator_part_of: kubevirt
        severity: critical
```

More details about Harvester alert:

https://github.com/w13915984028/harvester/blob/fix2517/enhancements/20220720-alertmanager.md
