### ISSUE TITLE
[BUG] vm stuck scheduling when using older template

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#2656]
**Describe the bug**
VMs won't start when created with a template, stuck in Scheduling

**To Reproduce**
1. Use a template in Harvester 1.
2. Migrate to 1.0.3
3. Create a VM from template

**Expected behavior**
VM should start as defined by template

**Support bundle**
[supportbundle_c2c9cfb1-d5b4-4d28-b014-c7e0b7716cef_2022-08-11T19-52-00Z.zip](https://github.com/harvester/harvester/files/9311646/supportbundle_c2c9cfb1-d5b4-4d28-b014-c7e0b7716cef_2022-08-11T19-52-00Z.zip)

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure: R620

**Additional context**
[small-ubuntu-94b69.txt](https://github.com/harvester/harvester/files/9311640/small-ubuntu-94b69.txt)

**Comment by noahgildersleeve** [comment]
@abonillabeeche I was trying to get this to reproduce, but I wasn't able to yet. I can't get the template YAML to match based on UI options. Could you attach screenshots of the tabs in the UI for view config on that template? There's some empty fields that shouldn't exist if they aren't being used in the YAML.

Specifically these sections
```
              acpi: {}
              smm:
                enabled: false
            firmware:
              bootloader:
                efi:
                  secureBoot: false
```
and 
```
                    f:acpi: {}
                    f:smm:
                      .: {}
                      f:enabled: {}
                  f:firmware:
                    .: {}
                    f:bootloader:
                      .: {}
                      f:efi:
                        .: {}
                        f:secureBoot: {}

```

Also was this template originally created in v1.0.2 or in a previous version?
