### ISSUE TITLE
Harvester: Need a way to configure default replica of data / longhorn to 2 instead of 3

### ISSUE THREAD

**Issue by wjimenez5271** [harvester/harvester#2659]
We do not want to have replica=3 on the harvester cluster in our disaster recovery data center. Due to that we want to have two replicas, only. How can we change the default of "replica=3" to "replica=2".

**Comment by guangbochen** [comment]
StorageClass is immutable in the k8s design, so users are generally suggested to create a new SC instead. If users want to modify the replicas of `longhorn` storageClass(before Harvester v1.1.2, the csi-driver didn't accept passing custom storageClass name, so it will always default to use `longhorn` SC from the bare-metal Harvester cluster), the best approach would be: 

**TO TEST:**
- Before the upgrade, your current Harvester cluster is either v1.1.0 or v1.1.1.
  1. change its replica count to `2` via:
      ```
      $kubectl edit managedchart -n fleet-local harvester 
  
      # add the persistence and defaultClassReplicaCount to the managedchart spec
      spec:
        longhorn:
          defaultSettings:
            defaultDataPath: /var/lib/harvester/defaultdisk
            taintToleration: kubevirt.io/drain:NoSchedule
          enabled: true
          persistence: # add the persistence and defaultClassReplicaCount as below
            defaultClassReplicaCount: 2
      ```
    1. this will help to persist the `longhorn` storage class configuration, but you are also expecting to see the error message on its status as below.
       ```
        message: 'cannot patch "harvester-longhorn" with kind StorageClass: StorageClass.storage.k8s.io
        "harvester-longhorn" is invalid: parameters: Forbidden: updates to parameters
        are forbidden.'
       ```
   1. before the cluster upgrade, users must revert the managedChart config to the original one, otherwise, the upgrade will be stuck in the `upgrading system services` stage.
- after upgrading the Harvester cluster to a new version, e.g., v1.1.2-head ISO.
  ```
  1. $kubectl edit managedchart -n fleet-local harvester 
```
$kubectl edit managedchart -n fleet-local harvester 
# add the persistence and defaultClassReplicaCount to the managedchart spec
spec:
  longhorn:
    defaultSettings:
      defaultDataPath: /var/lib/harvester/defaultdisk
      taintToleration: kubevirt.io/drain:NoSchedule
    enabled: true
    persistence: # add the persistence and defaultClassReplicaCount as below
      defaultClassReplicaCount: 2
```

  1. you will expect to not see any errors on the harvester managedChart after the upgrade.
  1. create a new volume using the `longhorn` SC; its newly generated volume will only contain `2` replicas.

**Comment by TachunLin** [comment]
Verified **failed** on `v1.1.2-rc1`. Move the issue to implement

### Result
After we change its replica count to 2 via `$kubectl edit managedchart -n fleet-local harvester`
![image](https://user-images.githubusercontent.com/29251855/220557309-fa7b5bd9-7c7a-4405-ad1b-1fdca8a15fb3.png)

And upgrade from v1.1.1 to v1.1.2-rc1, we `failed` to upgrade since the process stuck in `Upgrading System Services` 
![image](https://user-images.githubusercontent.com/29251855/220576518-731686cf-4ede-4b1c-b25e-8b03af35f4bc.png)


### Test Information
* Test Environment: 2 nodes Harvester on local kvm machine
* Harvester version: v1.1.1 to v1.1.2-rc1

### Verify Steps
1. Check the longhorn storageClass is not the default one and replica number is 3
![image](https://user-images.githubusercontent.com/29251855/220556587-1336b469-31af-4bdd-b848-f4346f33c3b4.png)

2. Change its replica count to 2, under spec.value.longhorn 
  ```
  n1-111:~ # kubectl edit managedchart -n fleet-local harvester
  managedchart.management.cattle.io/harvester edited
  
  longhorn:
        defaultSettings:
          defaultDataPath: /var/lib/harvester/defaultdisk
          taintToleration: kubevirt.io/drain:NoSchedule
        enabled: true
        persistence: # add the persistence and defaultClassReplicaCount as below
          defaultClassReplicaCount: 2
         
  ```
  ![image](https://user-images.githubusercontent.com/29251855/220557309-fa7b5bd9-7c7a-4405-ad1b-1fdca8a15fb3.png)

3. Then upgrade to v1.1.2-rc1
![image](https://user-images.githubusercontent.com/29251855/220557902-33c306df-db65-4331-96a2-d89236c66746.png)

### Additional Context
* Support bundle 
  [supportbundle_dab56c69-ab45-46e3-8267-0bd42b008ce0_2023-02-22T09-15-27Z.zip](https://github.com/harvester/harvester/files/10801970/supportbundle_dab56c69-ab45-46e3-8267-0bd42b008ce0_2023-02-22T09-15-27Z.zip)
  [supportbundle_dab56c69-ab45-46e3-8267-0bd42b008ce0_2023-02-22T10-04-16Z.zip](https://github.com/harvester/harvester/files/10802385/supportbundle_dab56c69-ab45-46e3-8267-0bd42b008ce0_2023-02-22T10-04-16Z.zip)

**Comment by guangbochen** [comment]
@TachunLin I have updated the testing cases, and please help to verify it again using the upcoming v1.1.2-rc2, thanks.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.1.2-rc3`. Close this issue.

### Result
* After upgrade, we can update the default replica of longhorn storage class to 2 without error message 

```
longhorn:
      defaultClassReplicaCount: 2
      defaultSettings:
        defaultDataPath: /var/lib/harvester/defaultdisk
        taintToleration: kubevirt.io/drain:NoSchedule
      enabled: true
      persistence: # add the persistence and defaultClassReplicaCount as below
        defaultClassReplicaCount: 2
``` 

* The `longhorn` storage class have two number of replicas
![image](https://user-images.githubusercontent.com/29251855/224699603-fd111870-eb4f-44b6-8484-47ad20f471f5.png)

* We create a new volume on longhorn storage class, it now have two replicas
![image](https://user-images.githubusercontent.com/29251855/224699532-563e4620-96f0-4d01-8eb6-64692551df81.png)


### Test Information
* Test Environment: 3 nodes harvester on bare machines
* Harvester version: v1.1.2-rc3

### Verify Steps
1. Prepare a v1.1.1 three nodes Harvester cluster 
2. Change the longhorn storage replica count to 2 via
  ```
  kubectl edit managedchart -n fleet-local harvester
  ```
3. Run the same command to check the status
4. Upgrade to v1.1.2-rc3
5. Wait for upgrade complete
6. Change the longhorn storage replica count to 2 and wait the status into Ready
  ```
  $ kubectl edit managedchart -n fleet-local harvester 
  
  longhorn:
        defaultClassReplicaCount: 2
        defaultSettings:
          defaultDataPath: /var/lib/harvester/defaultdisk
          taintToleration: kubevirt.io/drain:NoSchedule
        enabled: true
        persistence:
          defaultClassReplicaCount: 2
  ...
  status: 
    conditions:
    - lastUpdateTime: "2023-03-13T12:09:02Z"
      status: "True"
      type: Ready
  
  ```

7. Check the longhorn replia number on dashboard UI
8. Create a new volume on longhorn storage class
9. Access the longhorn UI  `https://192.168.50.150/dashboard/c/local/longhorn`
10. Check details setting of newly created volume
