### ISSUE TITLE
IP management enhancement with using either static or DHCP

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#266]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. adding a second NIC on the create VM page
1. config the network settings on the advanced section with either using DHCP or static IP e.g. when using the Ubuntu cloud-init image:
```
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: static
        address: 10.10.1.110/24
        gateway: 10.10.1.0
```
1. either the static or DHCP IP can't be retrieved directly from the UI since it is not stored in any places and the user has to check it manually through the server console.

**Result:**
1. should help to retrieve the second NIC network IPs and save them to the annotations field, therefore the user can access it directly without login into the server console.
