### ISSUE TITLE
[FEATURE] Support backup and restore through harvester-csi-driver in guest cluster

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2661]
**Is your feature request related to a problem? Please describe.**
Currently, when users create PVC through harvester-csi-driver in the guest cluster, they don't have a convenient way to backup/restore PVCs in LH. I try following the steps, but I can't restore PVC to the guest cluster.

1. In LH page, click `Create Backup` for a PVC.
2. Restore latest Backup to a Volume.
3. Click `Create PV/PVC` on the Volume.
4. In Harvester page, click `Add Volume` to the guest cluster.
5. Try to apply following PV/PVC in the guest cluster, but it doesn't work.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: driver.harvesterhci.io
  name: pvc-37f9bfdf-3a57-46d3-b45f-ffab7068fa29
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.harvesterhci.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1660213625498-8081-driver.harvesterhci.io
    volumeHandle: pvc-37f9bfdf-3a57-46d3-b45f-ffab7068fa29
  persistentVolumeReclaimPolicy: Delete
  storageClassName: harvester
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.harvesterhci.io
    volume.kubernetes.io/storage-provisioner: driver.harvesterhci.io
  name: pvc-from-harvester
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: harvester
  volumeMode: Filesystem
  volumeName: pvc-37f9bfdf-3a57-46d3-b45f-ffab7068fa29
```

**Describe the solution you'd like**
Add support in harvester-csi-driver.

**Comment by FrankYang0529** [comment]
cc @yaocw2020 Do you have any idea for users to manually restore PVC to the guest cluster now? Thank you.

**Comment by bk201** [comment]
@Vicente-Cheng Please help check if backup/restore can be supported via CSI.

**Comment by anultravioletaurora** [comment]
This was a question that came to my mind recently. If I stand up a new Kubernetes cluster on Harvester and I want to use volumes provisioned by the CSI driver previously for a different cluster, is there a way to create PVCs in the new cluster that target the PVs provisioned by the old cluster? :eyes:  

I had tried the steps that @FrankYang0529 had tried but no luck :disappointed:

**Comment by dfaltum** [comment]
This is also quite problematic for us. @Vicente-Cheng do you have any workaround for this problem?
We're using Velero for backup because of this issue.

**Comment by DillonN** [comment]
@anultravioletaurora @dfaltum - I was able to get @FrankYang0529's steps to work by tweaking the PV/PVC created in Longhorn after restore. It looks like Longhorn makes them in Filesystem mode, but it should be Block if you look at other provisioned volumes. Also the access mode should be RWX. So I cloned the PV/PVC to make these changes, then updated `volumeHandle` to the new PVC name in the guest cluster, and a pod was able to successfully mount it and see the old files.

This process is a bit of a pain if you started from a dynamic vol, but if you provision static vols in the guest cluster and also ahead of time in Harvester, I think it's serviceable.

Ideally there'd also be a path for dynamic vols that doesn't require converting to static. One step that could make it easier is to bubble up the original PVC name from the guest, that way the backup repo has a stable name. Though I'm not sure if LH itself supports restoring dynamic vols from a backup, or if they always need to be converted to static

Update: I've found a semi-serviceable workaround with static provisioning in IaC

First off create the Longhorn vol in the Harvester cluster. Make sure to use a globally unique name that is 40 characters or less and all lowercase/numbers/dashes (I had a volume go over this and now it's stuck in a broken/undeletable state).

```yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  labels:
    recurring-job-group.longhorn.io/<group>: enabled  # Optionally enable backup group
  name: <globally-unique-name>
  namespace: longhorn-system
spec:
  accessMode: rwx
  dataEngine: v1
  dataLocality: best-effort
  fromBackup: '<backup-url>'  # Restores from a backup if nonempty, get from backup list in LH UI
  frontend: blockdev
  numberOfReplicas: 3
  migratable: true
  revisionCounterDisabled: true
  staleReplicaTimeout: 30
  size: '<size-in-bytes>'
```

Then create a PV/PVC combo in the Harvester cluster. Use `Block` volume mode for both, put the PVC in the same namespace as guest cluster VMs, and use CSI params in the PV:

```yaml
driver: "driver.longhorn.io",
# Update - these are necessary, Harvester UI assumes the section is present and vol/vm pages break without it
volumeAttributes:
    migratable: 'true'
    numberOfReplicas: '1'
    share: 'true'
    staleReplicaTimeout: '30'
volumeHandle: <longhorn-vol-name>
```

Then finally create PV/PVC in the guest cluster. Use `Filesystem` volume mode (maybe block works, haven't tried), and CSI params in the PV:

```yaml
driver: "driver.harvesterhci.io",
fsType: "ext4",
volumeHandle: <pvc-name-in-harvester-cluster>
```
