### ISSUE TITLE
[FEATURE] Create a harvester-specific StorageClass for Longhorn

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2692]
Longhorn chart creates a `longhorn` StorageClass by default and we are using it with [some modification](https://github.com/harvester/harvester/blob/dc6a30894d63a07ba8b6db5433a7054f71445fde/deploy/charts/harvester/templates/longhorn-storageclass-override.yaml).
This might cause some issues and we should create another one (e.g., `longhorn-harvester`).

### ToDos
- [x] For new clusters, update Prometheus, grafana, alertmanager, logging to use the new storageclass by default.
- [x] storage class change for the alert manager in upgrade path: https://github.com/harvester/harvester/pull/2721/files#diff-bdbacb497dee5a09e5becbca17802c0d09476c955d098ebd1d20b2bb20d5207eR19

**Comment by w13915984028** [comment]
@ibrokethecloud @bk201 @Vicente-Cheng 
Gaurav just talked about #2088 

A harvester specific default `storageclass` will leave longhorn default storageclass untouched. It is also used by `rancher-monitoring` etc. in bootstrap stage.


/go/src/github.com/harvester/harvester-installer/pkg/config/templates/rancherd-13-monitoring.yaml

```
...
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi
                storageClassName: longhorn  /////////////// replace here to the new one
                volumeMode: Filesystem
```
