### ISSUE TITLE
[FEATURE] Implement vSwitch for Internally routed networks

### ISSUE THREAD

**Issue by lostangel556** [harvester/harvester#2697]
Moving from VMware ESXI to Harvester and one thing that I find strange is that there is no internal switching in the cluster.
All network connections appear to have to switch via an external vlan aware switch through a single ethernet connection.

Implementing https://www.openvswitch.org/ would allow switching to occur internal to each host and an assigned uplink for each vSwitch would allow connectivity to each vlan

**Comment by yasker** [comment]
vSwitch is a beast... We might bring it in later, but we've decided to keep the network model simple at first and focus more on providing support to the guest Kubernetes's network.

**Comment by qrkourier** [comment]
> All network connections appear to have to switch via an external vlan aware switch through a single ethernet connection.

Is this accurate? Specifically, is it necessary to have a metal, VLAN-aware switch to effect layer 2 isolation with Harvester VM network VLANs?

**Comment by lordraiden** [comment]
Any news about this?
It is possible to create virtual nic not attached to a physical interface? Or configure virtual switches?

**Comment by w13915984028** [comment]
At the moment, there is no existing, easy solution to confiure virtual nic/vSwitch directly in Harvester.

On the other hand, back to the concern here:

The VLAN based isolation, is `switched` inside Harvester NODE when traffic is bettwen VMs in same NODE, there is one/some Linux Bridge(s) used (though it inherites the original name `bridge`, but indeed it has fair rich feature sets of `switch`), the same-NODE traffic is not depending on a physical switch.

**Comment by cpinkham-lumn** [comment]
> Any news about this? It is possible to create virtual nic not attached to a physical interface? Or configure virtual switches?

If you create a dummy network interface via a yaml file in /oem, you can then use the Harvester API (https://$IP/v1/harvester/network.harvesterhci.io.vlanconfigs) to attach the dummy interface to a cluster network and now you have a usable private network you can use to connect VMs together without having to have a physical interface or VLAN attached.

I use a simple yaml file like this:

```
name: "dummy0"
stages:
  initramfs:
  - files:
    - path: /etc/sysconfig/network/ifcfg-dummy0
      permissions: 384
      owner: 0
      group: 0
      content: |
        STARTMODE='hotplug'
        BOOTPROTO='none'
      encoding: ""
      ownerstring: ""
```
