### ISSUE TITLE
[FEATURE] increase 110 pods per node limit

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#2707]
## problem
k8s has default limit:  110 pods per node.
My harvester control node with 20 vm already used 100 pods now.

####  pod numbers by namespaces:
* cattle  13 pods
* kube-system 19 pods
* longhorn 29 pods
* harvester-system 15 pods
* user vm only 24 pods 

#### harvester k8 config shows 110 limit
```
  allocatable:
    cpu: "40"
    memory: 395731228Ki
    pods: "110"
  capacity:
    cpu: "40"
    memory: 395731228Ki
    pods: "110"
```

## Describe the solution you'd like
* need an easy way to increase the limit number 110 -> 200
* or make 200 as the default harvester limit

#### for normal k8s cluster
* kubelet args: `--max-pods 200`
* kubelet config file: `/var/lib/rancher/rke2/agent/kubelet.kubeconfig`
* rancher kubelet config extra_args:  `max-pods: 250`

## Describe alternatives you've considered
any chance to reduce harvester/rancher/longhorn pods?
