### ISSUE TITLE
[DOC] VLAN enhancement document

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2735]
**Is your feature request related to a problem? Please describe.**

Since the VLAN enhancement leads to a new UI, it's necessary to update the document.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
Just to mention.

I think it would be awesome if we could mention that there are some breaking changes with `v1.1.0` compared to `v1.0.X` with the [harvester-config](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#example_11) 

For example, a user/organization/customer can no longer have this in their remote Harvester configuration:
```
install:
  mode: create
  networks:
    harvester-mgmt:       # The management bond name. This is mandatory.
      interfaces:
      - name: ens5
        hwAddr: "B8:CA:3A:6A:64:7D"     # The hwAddr is optional
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
      mtu: 1492
    harvester-vlan:       # The VLAN network bond name. User can then input `harvester-vlan` in the VLAN NIC setting in the GUI.
      interfaces:
      - name: ens6
        hwAddr: "B8:CA:3A:6A:64:7E"     # The hwAddr is optional
      method: none
      bond_options:
        mode: balance-tlb
        miimon: 100
    bond0:
      interfaces:
      - name: ens8
        hwAddr: "B8:CA:3A:6A:64:7F"     # The hwAddr is optional
      method: static
      ip: 10.10.18.2
      subnet_mask: 255.255.255.0
      gateway: 192.168.11.1
      mtu: 9000
```
There is no longer the YAML parent property of `networks`.
There is no longer in the YAML the property called `harvester-mgmt`, instead Harvester management network is now called `management_interface`:
```
install:
  mode: create
  management_interface:
    interfaces:
    - name: ens5
    default_route: true
    method: dhcp
    bond_options:
      mode: balance-tlb
      miimon: 100
```
So if maybe we could add like a :warning: / "!!!warning"  label in the markdown of some sort that might be helpful.

I can see if a customer/organization/user have remote Harvester configurations for their nodes, that if they upgrade those nodes from v1.0.X to v1.0.1, their old configuration to provision the Harvester nodes will no longer work if they wish to provision a node that is running v1.1.X.  

A few use-cases may be:
- adding more Harvester nodes to their cluster, not realizing that their old configuration syntax will no longer work
- disaster recover, as in, one of their existing nodes breaks, they need to replace hardware, and then bringing that node back online in the cluster

That in order to build their VLAN networks the user will either need to:
- build their own CRDs, and apply those files directly to the Harvester cluster's kubeconfig
- manually create them in UI
