### ISSUE TITLE
[BUG] Upgrade: stuck at pre-drained state

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2741]
**Describe the bug**

We have spotted some situations instance-manager pod can't be drained out of a node:
- Longhorn is being upgraded, and there are 2 `instance-manager-r` pods on a node.
- A node is just drained and comes back; if we drain the next node, there is a high probability the next node is stuck.

**To Reproduce**
1. Upgrade to master ISO from v1.0.3. (which bumps Longhorn to 1.3.1).
2. Many users report upgrades being stuck in pre-drain problems.

**Expected behavior**

The upgrade should not be stuck.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
We can test this when other upgrade works are done.

**Comment by lanfon72** [comment]
Tested:
- [x] single node cluster upgrade

**Comment by noahgildersleeve** [comment]
Tested in 3 node ipxe-examples vagrant upgrade scenario with Harvester v1.0.3 -> v1.1.0-rc2. I did this with a Harvester v1.1.0-rc2 iso stored on the ipxe server.

It was stuck in pre-drained state for hours. 
![Screenshot_20221010_184101](https://user-images.githubusercontent.com/83787952/194978968-1c171f19-f07e-4254-9ee4-372715722c10.png)
![Screenshot_20221010_182239](https://user-images.githubusercontent.com/83787952/194978971-729bebf2-7dfc-497c-90af-0bd618b10b67.png)
![Screenshot_20221010_131925](https://user-images.githubusercontent.com/83787952/194978972-09272d6a-09c7-4268-9722-137189474058.png)



[supportbundle_63f35a4d-17ba-4f4c-bb61-9e58685a5305_2022-10-11T01-41-18Z.zip](https://github.com/harvester/harvester/files/9750298/supportbundle_63f35a4d-17ba-4f4c-bb61-9e58685a5305_2022-10-11T01-41-18Z.zip)
Here's the `version.yaml` I used. I used the steps for upgrading [here](https://docs.harvesterhci.io/v1.0/upgrade/automatic#prepare-an-air-gapped-upgrade)


```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.1.0-rc2
  namespace: harvester-system
spec:
  isoChecksum: 1d95b8808412e06916c48bed7939b002608f8c1d343bfadfc06acfd9d226e3272f961d63566a5f31d770e0d30dfdd4e5ef4edd1877e4d45e9a6efaa787ee4ac4
  isoURL: http://192.168.0.254/harvester/harvester.iso  # change to local ISO URL
  releaseDate: '20221007'
  ```
