### ISSUE TITLE
[FEATURE] Upgrade support of audit and event log 

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2750]
**Is your feature request related to a problem? Please describe.**

Requirement: 
https://github.com/harvester/harvester/issues/577
https://github.com/harvester/harvester/issues/578

`logging, event and audit` will be enabled by default in v1.1.0, how about the upgrade?

**Describe the solution you'd like**

Add upgrade of `logging, event and audit`.

![image](https://user-images.githubusercontent.com/31133476/192819988-4781a52d-a736-4ee4-80cf-7a7dc70a0593.png)

**Describe alternatives you've considered**

Manually deploy related resources after upgrading.

**Additional context**

HEP PR:
https://github.com/harvester/harvester/pull/2684
HEP 578 event and audit log

backend code PR:
https://github.com/harvester/harvester/pull/2844

**Comment by guangbochen** [comment]
For upgrade case, if UI can't get the related Logging CRDs, its pages should still work properly but adding a proper warning message, cc @WuJun2016

**Comment by DaiYuzeng** [comment]
Could you provide steps for displacing available logging crd to unavailable, thanks!
@w13915984028 

Expected behavior:

1. navi tabs should be visible if there is no logging crd.
2. warning tips should be visible on logging resource list pages.

**Comment by DaiYuzeng** [comment]
UI PR has been merged.
The current design:

#### if there is missing crd
![image](https://user-images.githubusercontent.com/15041915/193172854-65c26408-47c8-47e3-9716-ac1b26668d95.png)


I am going to be unassigned, if you have any concerns, just let me know. 
@w13915984028 @guangbochen

**Comment by w13915984028** [comment]
Test Plan:
```
1. Prepare v1.0.3 cluster, single-node and multi-node need to be tested separately
2. Upgrade to v1.1.0-rc2 / master-head
3. The upgrade should be successful, if not, check log and POD errors
4. After upgrade, check following PODs and files, there should be no error
```
https://github.com/harvester/harvester/pull/2844#issuecomment-1267574827

```
5. Config in the UI about log, event, aduit, all of them should work as in fresh installed v1.1.0 cluster
```

cc @joshmeranda @DaiYuzeng @bk201

**Comment by TachunLin** [comment]
### Singe node upgrade check 
1. Check the following files and pods have no error 

- [x] logging related pods 
  ```
  n1-103:~ # kubectl get pods -n cattle-logging-system 
  NAME                                                      READY   STATUS      RESTARTS      AGE
  harvester-default-event-tailer-0                          1/1     Running     3 (39m ago)   69m
  rancher-logging-574448c578-lhvbd                          1/1     Running     3 (39m ago)   70m
  rancher-logging-kube-audit-fluentbit-7kq99                1/1     Running     3 (39m ago)   69m
  rancher-logging-kube-audit-fluentd-0                      2/2     Running     6 (39m ago)   70m
  rancher-logging-kube-audit-fluentd-configcheck-ac2d4553   0/1     Completed   0             70m
  rancher-logging-rke2-journald-aggregator-4f9jl            1/1     Running     3 (39m ago)   70m
  rancher-logging-root-fluentbit-tcd7z                      1/1     Running     3 (39m ago)   69m
  rancher-logging-root-fluentd-0                            2/2     Running     6 (39m ago)   69m
  rancher-logging-root-fluentd-configcheck-ac2d4553         0/1     Completed   0             70m
  ```

- [x] config file exists 
  ```
  n1-103:~ # cat /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml
  cni: multus,canal
  cluster-cidr: 10.52.0.0/16
  service-cidr: 10.53.0.0/16
  cluster-dns: 10.53.0.10
  tls-san:
    - 192.168.122.141
  audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
  ```
  ```
  n1-103:~ # cat /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
  apiVersion: audit.k8s.io/v1
  kind: Policy
  omitStages:
    - "ResponseStarted"
    - "ResponseComplete"
  rules:
    # Any include/exclude rules are added here
    # A catch-all rule to log all other (create/delete/patch) requests at the Metadata level
    - level: Metadata
      verbs: ["create", "delete", "patch"]
      omitStages:
        - "ResponseStarted"
        - "ResponseComplete"
  ```

- [x] /oem/99_custom.yaml is patched 
  ```
  n1-103:~ # grep "92-harvester" /oem/99_custom.yaml -5
              cluster-cidr: 10.52.0.0/16
              service-cidr: 10.53.0.0/16
              cluster-dns: 10.53.0.10
              tls-san:
                - 192.168.122.141
              audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            encoding: ""
            ownerstring: ""
          - path: /etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml
            permissions: 384
            owner: 0
  --
                valuesContent: |-
                  flannel:
                    iface: harvester-mgmt
            encoding: ""
            ownerstring: ""
          - path: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            permissions: 384
            owner: 0
            group: 0
            content: |
              apiVersion: audit.k8s.io/v1
  ```
  ```
  vim /oem/99_custom.yaml
  
  - path: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            permissions: 384
            owner: 0
            group: 0
            content: |
              apiVersion: audit.k8s.io/v1
              kind: Policy
              omitStages:
                - "ResponseStarted"
                - "ResponseComplete"
              rules:
                # Any include/exclude rules are added here
                # A catch-all rule to log all other (create/delete/patch) requests at the Metadata level
                - level: Metadata
                  verbs: ["create", "delete", "patch"]
                  omitStages:
                    - "ResponseStarted"
                    - "ResponseComplete"
            encoding: ""
            ownerstring: ""
  ```

**Comment by TachunLin** [comment]
### Multi nodes upgrade check 
1. Check the following files and pods have no error 

- [x] logging related pods 
   ```
   n1-103:~ # kubectl get pods -n cattle-logging-system
  NAME                                             READY   STATUS    RESTARTS      AGE
  harvester-default-event-tailer-0                 1/1     Running   0             47m
  rancher-logging-574448c578-wv9wd                 1/1     Running   0             47m
  rancher-logging-kube-audit-fluentbit-dnxzr       1/1     Running   2 (38m ago)   59m
  rancher-logging-kube-audit-fluentbit-s9bfj       1/1     Running   2 (29m ago)   59m
  rancher-logging-kube-audit-fluentbit-snrml       1/1     Running   2 (49m ago)   59m
  rancher-logging-kube-audit-fluentd-0             2/2     Running   0             36m
  rancher-logging-rke2-journald-aggregator-c4kk4   1/1     Running   2 (49m ago)   59m
  rancher-logging-rke2-journald-aggregator-rc4gf   1/1     Running   2 (29m ago)   59m
  rancher-logging-rke2-journald-aggregator-sc56f   1/1     Running   2 (38m ago)   59m
  rancher-logging-root-fluentbit-fh9v9             1/1     Running   2 (49m ago)   59m
  rancher-logging-root-fluentbit-v65sz             1/1     Running   2 (38m ago)   59m
  rancher-logging-root-fluentbit-xkp8p             1/1     Running   2 (29m ago)   59m
  rancher-logging-root-fluentd-0                   2/2     Running   0             36m
   ```
- [x] kube-audit files
  - Check the kube-apiserver has param of audit
  ```
    n1-103:~ # ps aux | grep kube-apiserver
    root      2819 41.7  2.6 3468424 2196848 ?     Ssl  12:25  56:05 kube-apiserver --audit-policy-file=/etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log
  ```
  - The /var/lib/rancher/rke2/server/logs/audit.log have increasing content
  ```
  n1-103:~ # du -sh /var/lib/rancher/rke2/server/logs/audit.log
  8.0M	/var/lib/rancher/rke2/server/logs/audit.log
  
  n1-103:~ # du -sh /var/lib/rancher/rke2/server/logs/audit.log
  8.5M	/var/lib/rancher/rke2/server/logs/audit.log
  ```

- [x] config file exists 
  ```
  n1-103:~ # cat /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml
  cni: multus,canal
  cluster-cidr: 10.52.0.0/16
  service-cidr: 10.53.0.0/16
  cluster-dns: 10.53.0.10
  tls-san:
    - 192.168.50.199
  audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
  ```
  ```
  apiVersion: audit.k8s.io/v1
  kind: Policy
  omitStages:
    - "ResponseStarted"
    - "ResponseComplete"
  rules:
    # Any include/exclude rules are added here
    # A catch-all rule to log all other (create/delete/patch) requests at the Metadata level
    - level: Metadata
      verbs: ["create", "delete", "patch"]
      omitStages:
        - "ResponseStarted"
        - "ResponseComplete"
  
  ```
- [x] /oem/99_custom.yaml is patched 
  ```
  n1-103:~ # grep "92-harvester" /oem/99_custom.yaml -5
              cluster-cidr: 10.52.0.0/16
              service-cidr: 10.53.0.0/16
              cluster-dns: 10.53.0.10
              tls-san:
                - 192.168.50.199
              audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            encoding: ""
            ownerstring: ""
          - path: /etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml
            permissions: 384
            owner: 0
  --
                valuesContent: |-
                  flannel:
                    iface: harvester-mgmt
            encoding: ""
            ownerstring: ""
          - path: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            permissions: 384
            owner: 0
            group: 0
            content: |
              apiVersion: audit.k8s.io/v1
  ```
  ```
  - path: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
            permissions: 384
            owner: 0
            group: 0
            content: |
              apiVersion: audit.k8s.io/v1
              kind: Policy
              omitStages:
                - "ResponseStarted"
                - "ResponseComplete"
              rules:
                # Any include/exclude rules are added here
                # A catch-all rule to log all other (create/delete/patch) requests at the Metadata level
                - level: Metadata
                  verbs: ["create", "delete", "patch"]
                  omitStages:
                    - "ResponseStarted"
                    - "ResponseComplete"
            encoding: ""
            ownerstring: ""
  ```
