### ISSUE TITLE
[Doc] Harvester CSI driver can not provision PV - missing rights?

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2755]
**Describe the bug**
Have followed the procedure to create an RKE2 cluster with the harvester CPI and CSI drivers.
Then tried to deploy rancher-monitoring with the usage of the harvester storage class-
The PVCs are created but the PVs are never created and attached.

**To Reproduce**
Deploy RKE2 manually using the Harvester CSI/CPI drivers following the documentation.
Use https://github.com/harvester/cloud-provider-harvester/blob/master/deploy/generate_addon.sh to create the service account

**Expected behavior**
Provisioning and attaching of PVs work.

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal, centos 7.9 VM in Harvester, RKE2 1.22.9

**Additional context**
From the describe PVC:

`  Warning  ProvisioningFailed    16m (x5 over 16m)     driver.harvesterhci.io_harvester-csi-driver-controllers-8674589f75-kkrqr_e5c9b8fa-d3e0-4e97-8e46-90ebfe461184  failed to provision volume with StorageClass "harvester": rpc error: code = Internal desc = persistentvolumeclaims is forbidden: User "system:serviceaccount:default:rancher-production" cannot create resource "persistentvolumeclaims" in API group "" in the namespace "default"`

--> it seems that the required rights for PVs are not part of https://github.com/harvester/cloud-provider-harvester/blob/f2030b157b4e6c01caa9231200c900fcf9988d92/deploy/generate_addon.sh#L31

**Comment by Martin-Weiss** [comment]
It seems that the process should add these rights instead (based on  clusterrole  harvesterhci.io:cloudprovider)

```
rules:
- apiGroups:
  - loadbalancer.harvesterhci.io
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachines/addvolume
  - virtualmachines/removevolume
  - virtualmachineinstances/addvolume
  - virtualmachineinstances/removevolume
  verbs:
  - get
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - '*'

```

Or instead of creating its own role and rolebinding the service account created with https://github.com/harvester/cloud-provider-harvester/blob/master/deploy/generate_addon.sh should just assign the service account to the clusterrole clusterrole  harvesterhci.io:cloudprovider
