### ISSUE TITLE
[FEATURE] Track upstream alertmanager globalconfig

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2760]
**Is your feature request related to a problem? Please describe.**

After https://github.com/harvester/harvester/issues/2521, there is a known limitation:

The `AlertmanagerConfig` is enforced by namespace. But, not all alerts having namespace. Meanwhile, create same receiver in each namespace is also tedious.

The is a workaround as per below link. It allows to add a gloabl config to Alertmanager, which in turn removes namespace check in AlertmanagerConfig.
https://github.com/prometheus-operator/prometheus-operator/issues/3737#issuecomment-1220906714

Unfortunately, the alertmanagerConfiguration is supported in Harvester used rancher-monitoring.

**Describe the solution you'd like**

Wait for upstream's enhancement, when it is added to `rancher-monitoring`, then add to Harvester.

**Describe alternatives you've considered**

https://github.com/rancher/rancher/issues/38818#issuecomment-1238328588

**Additional context**

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#specify-global-alertmanager-config

The following example configuration creates an Alertmanager resource that specify an AlertmanagerConfig resource to be global(won't force add a namespace label in routes and inhibitRules):
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
  namespace: default
spec:
  replicas: 3
  alertmanagerConfiguration:
    name: example-config
```    
The `AlertmanagerConfig` resource named example-config in namespace default will be an global AlertmanagerConfig. When generating configs in alertmanager, routes and inhibitRules in the AlertmanagerConfig will not be force add a namespace label.
