### ISSUE TITLE
[BUG] LH V1.3.1 ref counting conflicts with fleet-agent

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2762]
**Describe the bug**

fleet-agent is always complaining those CRD resources are changed

![image](https://user-images.githubusercontent.com/31133476/189883679-9758778c-1e39-4f7d-8f95-96f762268227.png)

![image](https://user-images.githubusercontent.com/31133476/189883763-43848a73-b138-4904-bb0e-7b8169f940d4.png)

**To Reproduce**

Harvester master-head with LH v1.3.1

**Expected behavior**

satisfy fleet-agent.

This issue is not in LH v1.3.0 or before.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM based

**Additional context**

The difference is, CRD `engineimages.longhorn.io` has generation `2` after system installation, but normal CRD hais generation `1`, that's why `fleet-agent` complain.

![image](https://user-images.githubusercontent.com/31133476/193122711-6691d796-d348-401e-8f37-1f2df3816e87.png)

**Comment by w13915984028** [comment]
any complain from `fleet-agent` will trigger 
https://github.com/harvester/harvester/issues/1893

due to
https://github.com/rancher/rancher/issues/38035

**Comment by TachunLin** [comment]
Verified **fixed** on `master-8f2c9789-head` (10/06). Close this issue.

### Result
1. The `mcc-harvester` bundle no longer have modified status 
```
harv1006:~ # kubectl get bundle -n fleet-local mcc-harvester
NAME            BUNDLEDEPLOYMENTS-READY   STATUS
mcc-harvester   1/1
```
2. fleet-agent have no complaining CRD resources are changed
```
harv1006:~ # kubectl get pods -n cattle-fleet-local-system
NAME                          READY   STATUS    RESTARTS      AGE
fleet-agent-b98cf4c5d-wtmfg   1/1     Running   1 (62m ago)   6h29m
harv1006:~ # kubectl logs -n cattle-fleet-local-system fleet-agent-b98cf4c5d-wtmfg | grep engineimages
harv1006:~ # 

```
3. The following diff have added to the harvester managedchart
```
spec:
  chart: harvester
  defaultNamespace: harvester-system
  diff:
    comparePatches:
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
```
### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-8f2c9789-head` (10/06)

### Verify Steps
1. Fresh install v1.1.0 master Harvester
2. ssh to harvester node 
3. Execute `kubectl get bundle -n fleet-local mcc-harvester`
4. Execute `kubectl get pods -n cattle-fleet-local-system` follow by `kubectl logs -n cattle-fleet-local-system fleet-agent-b98cf4c5d-wtmfg | grep engineimages`
5. Execute `kubectl get managedchart harvester -n fleet-local -o yaml`
6. Check the `diff` section content under the spec
