### ISSUE TITLE
[BUG] Making a PCI Device Claim doesn't allow-list the device in KubeVirt

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#2820]
**Describe the bug**
When claiming a PCI Device for passthrough, the KubeVirt CR needs to be updated to include the device in it's list of `permittedHostDevices`.

**To Reproduce**
1. Go to Advanced -> PCI Devices
2. Click on a PCI Device and Enable Passthrough
3. Once the device is Enabled, go to Virutal Machines and add the device to a VM. 
4. Boot the VM
5. KubeVirt should fail because the device is not in the list of permittedHostDevices (see the list using this command)
```
k get kubevirts.kubevirt.io -n harvester-system kubevirt -o yaml | yq '.spec.configuration'                                                   git(f2f5…):fix-2819 k8s⎈ saturn 🪐
developerConfiguration:
  featureGates:
    - LiveMigration
    - HotplugVolumes
emulatedMachines:
  - q35
  - pc-q35*
  - pc
  - pc-i440fx*
network:
  defaultNetworkInterface: bridge
  permitBridgeInterfaceOnPodNetwork: true
  permitSlirpInterface: true
```
**Expected behavior**
The `permittedHostDevices block needs to be under `configuration`. Also the `HostDevices` feature gate needs to be added as well.
The VM with attached PCI device should boot and the PCI device should be visible inside the VM (should be able to install drivers for it, etc.)

**Environment**
 - Harvester ISO version: 1.1.0-rc1 (version: 008b5d50)
 - Underlying Infrastructure: Baremetal with Dell Precision T7500

**Comment by tlehman** [comment]
I merged the [DevicePlugins](https://github.com/harvester/pcidevices/pull/35) branch today, this addresses this problem.

**Comment by lanfon72** [comment]
milestone needed

**Comment by irishgordo** [comment]
@tlehman  thanks for the fix :+1: :smile: 

This looks good on 
 Version: v1.1-e1905897-head 

With `kubectl get kubevirts.kubevirt.io -n harvester-system kubevirt -o yaml | yq` as well:
```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - LiveMigration
        - HotplugVolumes
        - HostDevices
    emulatedMachines:
      - q35
      - pc-q35*
      - pc
      - pc-i440fx*
    network:
      defaultNetworkInterface: bridge
      permitBridgeInterfaceOnPodNetwork: true
      permitSlirpInterface: true
    permittedHostDevices:
      pciHostDevices:
        - externalResourceProvider: true
          pciVendorSelector: 8086:10bc
          resourceName: intel.com/82571EB_82571GB_GIGABIT_ETHERNET_CONTROLLER_COPPER
```
![Screenshot from 2023-03-14 19-13-25](https://user-images.githubusercontent.com/5370752/225187368-737cc8cb-cef4-40a7-933f-aa9b6b20ac97.png)
![Screenshot from 2023-03-14 19-09-00](https://user-images.githubusercontent.com/5370752/225187372-535bd337-d645-49c5-bcc2-e066f28857c2.png)
![Screenshot from 2023-03-14 16-01-53](https://user-images.githubusercontent.com/5370752/225187471-50a3c7d6-4504-4d64-b638-4c4157247626.png)
