### ISSUE TITLE
[BUG] Set Harvester containerd-registry to use default value also cleanup previous status setting

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2873]
**Describe the bug**

* When we already have setup valid setting in Harvester `containerd-registry`, after clicking the `Use default value` and save. 
![image](https://user-images.githubusercontent.com/29251855/193978425-28a00ea6-ce63-4c74-b720-6b66d94cd84c.png)

* We found the `status` field of the containerd registry setting also been cleanup to empty in K9s 
![image](https://user-images.githubusercontent.com/29251855/193995299-4969720a-d6dd-4b5b-a240-be182229d923.png)

* Which would cause no new `apply-sync-containerd` jobs trigger to update the containerd setting  
![image](https://user-images.githubusercontent.com/29251855/193995433-b12aed8a-2b65-4d70-b990-05c0f8717ff5.png)

**To Reproduce**
Follow the steps to prepare test environment https://github.com/harvester/tests/issues/476#issue-1355132277

1. Update the Harvester containerd-registry setting to use private registry
  ```
  {
  "Mirrors": {
    "docker.io": {
      "Endpoints": [
        "https://myregistry.local:5000"
      ],
      "Rewrites": null
    }
  },
  "Configs": {
    "myregistry.local:5000": {
      "Auth": null,
      "TLS": {
        "CAFile": "",
        "CertFile": "",
        "KeyFile": "",
        "InsecureSkipVerify": false
      }
    }
  },
  "Auths": null
}
  ```
2. Open K9s -> search -> secrets -> containerd -> y
  ![image](https://user-images.githubusercontent.com/29251855/193786543-ed43eb8a-f332-48b9-8b8a-afef8088f97f.png)
3. Check content in cattle-system/harvester-containerd-registry secret is changed. 
  ![image](https://user-images.githubusercontent.com/29251855/193787031-2ea11b68-e79c-4c10-8409-0bb337b5baf8.png)
4. Search jobs -> containerd -> l -> tail
5. Check there are new jobs to auto apply the new containerd-registry setting.
  ![image](https://user-images.githubusercontent.com/29251855/193786463-ca1e1f26-e37b-4e1b-b0d3-5e58b7d47bc1.png)
6. Apply following yaml in file 
    ```
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myregistry-nginx
    spec:
      selector:
        matchLabels:
          image: myregistry-nginx
      template:
        metadata:
          labels:
            image: myregistry-nginx
        spec:
          containers:
            - imagePullPolicy: Always
              image: myregistry.local:5000/nginx:latest
              name: nginx
    ```
    ```
    harvester-node-0:~ # kubectl apply -f deploy.yaml
    deployment.apps/myregistry-nginx created
    
    ```
7. search deployments -> default namespace -> myregsistry-nginx -> describe -> shift + g
8. Check the nginx can be deployed. 
9. Click the `default value` to update the Harvester containerd-registry setting to default empty 
10. In K9s, search settings -> containerd -> y 
11. Check the status field 
12. In K9s, search jobs -> containerd 
13. Check if new apply-sync-containerd jobs created

**Expected behavior**

When we set containerd registry back to default, the settings of container registry should retain the previous status 
And there should be new apply-sync-containerd jobs created to update the setting accordingly

**Support bundle**

[supportbundle_b03ed342-6a09-44e9-9236-be3a26dd0be4_2022-10-05T07-10-17Z.zip](https://github.com/harvester/harvester/files/9713496/supportbundle_b03ed342-6a09-44e9-9236-be3a26dd0be4_2022-10-05T07-10-17Z.zip)

**Environment**
 - Harvester ISO version: `master-75876dee-head` (10/05)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node local kvm machine 

**Additional context**
