### ISSUE TITLE
[BUG] Can't edit the existing Harvester containerd registry setting, it display empty content 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2874]
**Describe the bug**

When we already add values to containerd registry setting. 

* Then we click the edit settings button, we can't get the previous settings content to change  
![image](https://user-images.githubusercontent.com/29251855/194003823-876fd874-b00b-4155-ac89-bc33b46d0a02.png)

**To Reproduce**
1. Go to settings 
2. Add valid setting values (Mirror, config) to containerd registry setting
3. Save the settings
4. Edit the containerd registry setting 

**Expected behavior**

When edit containerd registry setting, can display previous saved settings 
Can edit existing setting and save correctly

**Support bundle**

**Environment**
 - Harvester ISO version: `master-75876dee-head` (10/4)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node local kvm machine

**Additional context**

**Comment by WuJun2016** [comment]
Hi, @TachunLin   I can't reproduce this on the Harvester `v1.1.0-rc2` version.

**Comment by irishgordo** [comment]
@WuJun2016 this looks good to me :smile:  thanks for the fix!

Testing on Harvester Version: master-937f333c-head  (10/12)

I used, ubuntu-focal-server cloud-img, to provision the private Docker Registry with:
```yaml
#cloud-config
password: ubuntupw
chpasswd:
  expire: false
ssh_pwauth: true
package_update: true
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - gnupg
  - lsb-release
  - software-properties-common
  - openssl
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - echo "127.0.0.1 myregistry.local" >> /etc/hosts
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)]
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
    docker-compose-plugin
  - systemctl enable --now qemu-guest-agent.service
  - systemctl enable docker
  - systemctl start docker
  - cd /home/ubuntu && mkdir -p certs
  - cd /home/ubuntu && mkdir -p auth
  - docker run --entrypoint htpasswd httpd:2 -Bbn testuser testpassword > /home/ubuntu/auth/htpasswd
  - openssl req -newkey rsa:4096 -nodes -sha256 -keyout /home/ubuntu/certs/domain.key -addext "subjectAltName = DNS:myregistry.local" -subj "/C=US/ST=CA/O=Acme, Inc./CN=myregistry.local" -x509 -days 365 -out /home/ubuntu/certs/domain.crt
  - mkdir -p /etc/docker/certs.d/myregistry.local:5000
  - cp /home/ubuntu/certs/domain.crt /etc/docker/certs.d/myregistry.local:5000/domain.crt
  - docker run -d \
    -p 5000:5000 \
    --restart=always \
    --name registry \
    -v /home/ubuntu/certs:/certs \
    -v /home/ubuntu/registry:/var/lib/registry \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
    -v /home/ubuntu/auth:/auth \
    -e "REGISTRY_AUTH=htpasswd" \
    -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
    -e REGISTRY_AUTH_HTPASSWD_PATH=auth/htpasswd \
    registry:2
  - docker login myregistry.local:5000 -u testuser -p testpassword
  - docker pull nginx:latest
  - docker tag nginx:latest myregistry.local:5000/nginx:latest
  - docker push myregistry.local:5000/nginx:latest
  - docker pull nginx:1.22
  - docker tag nginx:latest myregistry.local:5000/nginx:1.22
  - docker push myregistry.local:5000/nginx:1.22
```

![Screenshot from 2022-10-12 13-41-23](https://user-images.githubusercontent.com/5370752/195443655-5da03e69-5999-4eba-9e58-cd9ff122738d.png)

And validated that we can edit the containerd registry setting multiple times, after initially setting the values:
![Screenshot from 2022-10-12 13-37-46](https://user-images.githubusercontent.com/5370752/195443766-3a8a8d8e-08d6-4153-a8fd-ff7ea8558430.png)
![Screenshot from 2022-10-12 13-37-20](https://user-images.githubusercontent.com/5370752/195443769-8137fffb-b59d-4789-93c9-b66f41b1e557.png)
