### ISSUE TITLE
[ENHANCEMENT] Upgrade path: tool to do semantic version comparison

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2877]
**Is your feature request related to a problem? Please describe.**

In the upgrade path, we need to compare semantic versions in many places. 
Neither the bash `<` operator nor `sort` command performs well.

**Describe the solution you'd like**

We need a handy tool to be called in the upgrade scripts.

**Describe alternatives you've considered**

Build our tool, leverage library like https://github.com/Masterminds/semver.

**Additional context**

**Comment by starbops** [comment]
## The Ultimate Policy of Harvester Upgrade

### Glossary

- Formal release versions: a semantic version with no suffices, e.g. v1.2.2 and v1.3.0
- Prerelease versions: a semantic version with a suffix, e.g. v1.2.2-rc1
- Dev versions: any version that falls outside of the two above, e.g. v1.2-ab12cd34
- Minimum upgrade requirements: each formal release/prerelease version will incorporate an upgrade matrix file specifying the minimal upgradable version for such a version

### Rules

Since there are various upgrade paths, we explicitly enforce a set of rules to prohibit specific upgrade paths to ensure the stability of Harvester upgrades and reduce the maintenance burden for the Harvester team:

- Users are not allowed to upgrade from any version to a lower version (effectively downgrade)
- Users are not allowed to upgrade from any formal release version lower than the minimal upgrade requirement of the targeting formal release version
- Users are not allowed to upgrade from any dev version to a formal release version[^1]
- Users are not allowed to upgrade from any dev version to a prerelease version[^1]
- Users are allowed to upgrade from any lower prerelease version to a higher one within the same release version but not across different release versions

Upgrade paths other than the ones stated above are all legal. As a side note, we listed several peculiar upgrade paths that seem illegal but are actually doable below:

- Same-version upgrades are always allowed, no matter what the version is
- Upgrade from a formal release or prerelease version to a dev version is always allowed
- Upgrade from any dev version to another dev version is always allowed
- Upgrade from any prerelease version to a corresponding formal release version or another newer prerelease version within the same release version, e.g. v1.2.2-rc1 to v1.2.2-rc2

[^1]: By default, the strict mode is enabled to prevent any informal upgrades from happening. It could be disabled to loosen such a restriction.

Please feel free to add comments if the above rules are incomplete or need improvement. Thank you. cc @bk201  @khushboo-rancher

**Comment by brandboat** [comment]
Test ok with v1.4.0-rc4, will close the issue

# Environment
- single node (12c/16G/500G)

Only test pre-release related upgrade as this enhancement was introduced in v1.4.0-rc
# Test Plan
## v1.3.2 -> v1.4.0.-rc3 (verify upgrade to pre-release should success)
```shell
kubectl apply -f - << EOF
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.4.0-rc3
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-v1.4.0-rc3-amd64.iso
EOF
```
![image](https://github.com/user-attachments/assets/8816335c-c85f-471a-8c01-4f9bcc839548)

## v1.4.0-rc3 -> v1.3.2 (verify downgrade should fail)
```shell
kubectl apply -f - << EOF
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.3.2
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-v1.3.2-amd64.iso
EOF
```
![image](https://github.com/user-attachments/assets/657d56fd-ce5e-47f2-ba7f-73475eb57023)

## v1.4.0-rc3 -> v1.4.0-rc4 (verify we can upgrade from pre-release to another pre-release)
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.4.0-rc4
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-v1.4.0-rc4-amd64.iso
```
![image](https://github.com/user-attachments/assets/d4ad0abe-8b20-4be1-ae63-29a95335e6b2)
![image](https://github.com/user-attachments/assets/d6525715-8038-411d-b22a-c614d5e9e4a5)

## v1.4.0-rc4 -> v1.4.0-rc4 (verify we can upgrade same version)
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.4.0-rc4
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-v1.4.0-rc4-amd64.iso
```
![image](https://github.com/user-attachments/assets/cd6600c1-b421-4acb-b9ff-63e1dfa67733)
![image](https://github.com/user-attachments/assets/7f07bdbb-1f19-46fd-b4e0-76e8228309f4)

## v1.4.0-rc4 -> master (verify we can upgrade from pre-release to dev)
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: master
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-master-amd64.iso
```
![image](https://github.com/user-attachments/assets/82530d79-eda8-4f09-b9c4-3ca05d03cef6)
![image](https://github.com/user-attachments/assets/3863fefd-9005-47bd-9ffc-cfc64216228c)

## master -> v1.4.0-rc4 (verify upgrade from dev to pre-release should fail)
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.4.0-rc4
  namespace: harvester-system
spec:
  isoURL: http://192.168.100.1:8000/harvester-v1.4.0-rc4-amd64.iso
```
![image](https://github.com/user-attachments/assets/d4edf8d2-c602-4fd3-9031-995dd27e3b1e)
