### ISSUE TITLE
[BUG] "Power Off virtual machine" task errors in vSphere on "VirtualMachineImport" resource creation with vm-import-controller

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2879]
**Describe the bug**
Case: in vSphere there is a non-zero chance that an individual/group/org could have alerts of some kind set up on failed operations for "Tasks"...possibly.

In the "vm-import-controller" that's partially relying on the set of enum types from the `vmware/govmomi/vim25/types` (vmware go library) - there are the sets of:
https://github.com/vmware/govmomi/blob/master/vim25/types/enum.go#L4885-L4922

In the implementation in the `virtualmachine.triggerExport` function:
https://github.com/harvester/vm-import-controller/blob/6705d755c1aaca66fc268a739d2f069e3502e714/pkg/controllers/migration/virtualmachine.go#L226-L294

More specifically in:
https://github.com/harvester/vm-import-controller/blob/6705d755c1aaca66fc268a739d2f069e3502e714/pkg/controllers/migration/virtualmachine.go#L274-L291

I'm not sure, though, thinking that:
https://github.com/vmware/govmomi/blob/master/vim25/types/enum.go#L4912-L4916
Maps to something more generic in (to handle both VMWare & OpenStack based calls):
https://github.com/harvester/vm-import-controller/blob/6705d755c1aaca66fc268a739d2f069e3502e714/pkg/apis/migration.harvesterhci.io/v1beta1/virtualmachines.go#L59-L75

Something is taking place where the "Task" in vSphere, will show an "Operation Failed"-like message if the VM in vSphere was already powered off and you tried to import it.

Example:
![error-in-task](https://user-images.githubusercontent.com/5370752/194145989-ef7d1005-7466-49b1-921d-74b19471b388.png)

**To Reproduce**
1. Go to vSphere, power off a VM that you wish to import - that you haven't imported yet
1. Create the `VirtualMachineImport` YAML
1. Apply `VirtualMachineImport` YAML to Harvester Cluster
1. View "Tasks" in vSphere, audit for the: "The attempted operation cannot be performed in the current state ("Powered off")"

**Expected behavior**
Maybe some sort of additional check to not try to fire off a "power off this vm" API call out to vSphere with the `vmware/govmomi` library if the VM is already turned off?
Not seeing: "The attempted operation cannot be performed in the current state ("Powered off")".
So not producing failed tasks / "operation cannot be preformed" tasks within the task log / recent tasks in vSphere as a side-effect of creating a "VirtualMachineImport" resource in the Harvester Cluster.

**Support bundle**
N/A
As this has more to due with the Task log Operation failures like:
```
Power Off virtual machine
Status:
The attempted operation cannot be performed in the current state ("Powered off").

Initiator: blah.com\mrussell

Target:
alpine-export-test

Server: server-place-location-wherever.com

Related events:
10/05/2022, 11:05:33 AM
	
Task: Power Off virtual machine
```

**Environment**
 - Harvester ISO version: v1.1.0-rc1
 - Underlying Infrastructure: qemu/kvm

**Additional context**
- vSphere Version: 6.7.0.48000
- VirtualMachineImport YAML:
```YAML
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: apline-export-test
  namespace: default
spec: 
  virtualMachineName: "alpine-export-test"  
  networkMapping:
  - sourceNetwork: "dvSwitch 1"
    destinationNetwork: "default/mgmt-vlan"
  - sourceNetwork: "dvSwitch 2"
    destinationNetwork: "default/mgmt-vlan"
  sourceCluster: 
    name: vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```
