### ISSUE TITLE
[BUG] VirtualMachineImport Adds Additional Network Device From OpenStack

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2890]
**Describe the bug**
When importing an OpenStack with one network interface - there tends to be an additional network interface added.

**To Reproduce**
1. Go to your OpenStack (stable/train) instance, build a VM
1. Have that VM only have 1 network interface
1. Create the CRD YAML for the `VirtualMachineImport` 
1. Import the VM into your Harvester

**Expected behavior**
The VM would only have 1 NIC not two

**Support bundle**

[supportbundle_287fe6a4-7974-4609-983a-4a61acd31a78_2022-10-04T00-01-41Z.zip](https://github.com/harvester/harvester/files/9701806/supportbundle_287fe6a4-7974-4609-983a-4a61acd31a78_2022-10-04T00-01-41Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc1
 - Underlying Infrastructure: Dell PowerEdge R720
 
**Additional context**
![Screenshot from 2022-10-03 16-56-59](https://user-images.githubusercontent.com/5370752/193706377-4854c098-42e4-45e0-92ac-820fd4065901.png)
![Screenshot from 2022-10-03 16-51-27](https://user-images.githubusercontent.com/5370752/193706381-6d5bc882-4393-43c3-a992-8d2b91fe3ac4.png)
![Screenshot from 2022-10-03 16-44-58](https://user-images.githubusercontent.com/5370752/193706383-43f7d7b8-4e50-4397-9337-45cb8c2774c4.png)

You can reference the OpenStack version only has one interface - whereas the Harvester imported VM from OpenStack seemingly has two interfaces (same mac address)

**Comment by ibrokethecloud** [comment]
I will need to check this VM. On a local devstack instance I perform a migration with the following spec
```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: openstack-demo
  namespace: default
spec: 
  virtualMachineName: "openstack-demo" #Name or UUID for instance
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/fremont"
  - sourceNetwork: "public"
    destinationNetwork: "default/fremont"
  sourceCluster: 
    name: devstack
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

And I only got one interface created
![image](https://user-images.githubusercontent.com/19664014/194440440-f75b9501-c185-47da-beda-c66a2f9360eb.png)
