### ISSUE TITLE
[BUG] The upgrade version check does not handle prerelease cases

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3040]
**Describe the bug**

Users reported in #3044 the upgrade from v1.1.0-rc3 to v1.1.0 will fail with the following message:

```
The current version v1.1.0-rc3 is less than the minimum upgradable version v1.0.3.
```

**To Reproduce**
1. Prepare a v1.1.0-rc3 Harvester cluster with any number of nodes
2. Kickstart the upgrade to v1.1.0
3. The upgrade should fail in the early stage complaining "The current version v1.1.0-rc3 is less than the minimum upgradable version v1.0.3."

**Expected behavior**

Though we do not support upgrades from a prerelease version, the version-checking logic and the error message should not be confusing.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Workaround: ~~fake the current version `kubectl edit settings.harvesterhci.io server-version` and edit the value from a prerelease version to a formal release version, e.g. from `v1.1.0-rc3` to `v1.1.0`.~~

Please check the comment [below](https://github.com/harvester/harvester/issues/3040#issuecomment-1298057127) for the updated workaround.

**Comment by starbops** [comment]
In the case of upgrading from prerelease versions, either we block such behaviors or let users take the risks doing that.

Regardless of either case, we need to warn the users, both on the documentation and the UI.

**Comment by w13915984028** [comment]
It is discussed in https://github.com/harvester/harvester/pull/2829#discussion_r987636298,  

`v1.1.0` is lexically < `v1.1.0-rc*`

And @bk201 created an issue: https://github.com/harvester/harvester/issues/2877  [FEATURE] Upgrade path: tool to do semantic version comparison

**Comment by w13915984028** [comment]
cc @guangbochen

**Comment by irishgordo** [comment]
:eyes: - looking into this

**Comment by irishgordo** [comment]
This can be easily reproduced on `rc-3` for instance.
```YAML
vm-v110-rc3-test:~ # curl http://192.168.1.44/version_v110_our_release_day_forced_upgrade_yaml_for_testing_only.yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.1.0
  namespace: harvester-system
spec:
  isoChecksum: '11b3bfd2ab1eac07c8179d9b3ccf75dd48c4f029d72801931a96a6e4452bddce532029d7045e23096380e2cae7cb8410fef8b2f2ce4c0b23281198b73b3d54ac'
  isoURL: http://192.168.1.44/harvester-v1.1.0-amd64.iso
  releaseDate: '20221025'
```

Though, I can not get the work-around to work.
Variants I've tried have been:
1. Process A:
   - delete the resourced created, `kubectl delete -f` 
   - delete the upgrade in K9s 
   - edit the settings.harvesterhci.io server-version, to `v1.1.0` no `-rc*` 
   - create the resource, retry upgrade
1. Process B:
   - delete the resourced created, `kubectl delete -f` 
   - delete the upgrade in K9s 
   - edit the settings.harvesterhci.io server-version, to `v1.0.3` ` 
   - create the resource, retry upgrade

For the comparison we could possibly try to just sanitize the rc version string. 
With something like:
```go
        // whereas currentVersion was like: "v1.1.0-rc3"
	versionTemp := currentVersion
	versionSanitized := strings.Split(versionTemp, "-rc")[0]
	fmt.Println(versionSanitized)
```
But, I understand that there are probably some downstream effects because we'd just be mutating or creating another variable from, `currentVersion` in the function signature of:
https://github.com/harvester/harvester/blob/a4872361145e0d0b99c4afeb6052f344acd48f30/pkg/controller/master/upgrade/version_syncer.go#L187-L198

I do like the idea of building the tool to do the version comparisons like mentioned:
https://github.com/harvester/harvester/pull/2829#discussion_r987636298

![Screenshot from 2022-10-27 16-10-41](https://user-images.githubusercontent.com/5370752/198415818-21c6b016-00b5-42f2-aff7-bc865d66e134.png)
![Screenshot from 2022-10-27 16-09-51](https://user-images.githubusercontent.com/5370752/198415823-c829632f-9174-4804-b250-f9c9a698f58a.png)
![Screenshot from 2022-10-27 16-06-03](https://user-images.githubusercontent.com/5370752/198415824-85aa7820-d9f5-410d-bbd9-5f9cf0250fe7.png)
![Screenshot from 2022-10-27 16-04-05](https://user-images.githubusercontent.com/5370752/198415827-6e12928b-89cd-40ef-b082-fc8e5cd3eb68.png)


Harvester Version: v1.1.0-rc3
Infra: kvm/qemu

File-server, Caddy on 192.168.1.44 for yaml crd & iso.
