### ISSUE TITLE
[BUG] migrate_harv_mgmt_to_mgmt_br.sh should remove ClusterNetwork resource

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#3047]
**Describe the bug**

migrate_harv_mgmt_to_mgmt_br.sh should remove ClusterNetwork reousrce to avoid migration again.
If users deploy Harvester v1.0.3 with cluster_networks option and value is "harvester-mgmt".
migrate_harv_mgmt_to_mgmt_br.sh will be executed over and over again

**To Reproduce**
1. Install harvester v1.0.3 with cluster_networks option and value is "harvester-mgmt"
2. upgrade to v1.1.0
3. and reboot first node (create mode), migrate_harv_mgmt_to_mgmt_br.sh will be executed every reboot.

**Expected behavior**

Only execute migrate_harv_mgmt_to_mgmt_br.sh once

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 

**Additional context**

**Comment by tjjh89017** [comment]
## Test Step

1. Install harvester v1.0.3 with cluster_networks setting in config.yaml (installation stage)
2. Upgrade to new version harvester
3. /oem/99_custom.yaml should not have "21-harvester-clusternetworks.yaml"

## Workaround

### Method 1
1. Execute this script after the node is rebooted and network is disconnected.
2. https://gist.github.com/tjjh89017/dc3c91384aa14764a9458be6de3c8e5c

### Method 2
remove the file "21-harvester-clusternetworks.yaml" from /oem/99_custom.yaml

**Comment by TachunLin** [comment]
Verified **fixed** on `v.1.1.1-rc1`. Close this issue.

### Result
When we Install harvester v1.0.3 with cluster_networks option and value is **harvester-mgmt** and set 
And bond `harvester-mgmt` network on multiple NICs plus bond custom `vlan` network on multiple NICs 
Then upgrade to v1.1.1-rc1

1. We can successfully upgrade from v1.0.3 to `v1.1.1-rc1`
  ![image](https://user-images.githubusercontent.com/29251855/201100800-bba004ad-cb14-49fb-bd22-8c01a5830b6c.png)

2. After upgrade complete, /oem/99_custom.yaml should not have "21-harvester-clusternetworks.yaml"
  ```
  harvester-node-0:/oem # cat 99_custom.yaml | grep "21-harvester-clusternetworks.yaml"
  harvester-node-0:/oem # 
  ```
4. Cluster Network exists
  ![image](https://user-images.githubusercontent.com/29251855/201101725-a028bc80-da8d-4708-8ecf-d3b5c7c66d0d.png)
5. Can create Vlan 1  and route correctly
  ![image](https://user-images.githubusercontent.com/29251855/201102502-347d6c1b-06e1-4853-a119-f72fc1e19dcd.png)

```

```
### Test Information
* Test Environment: 1 node local kvm machine
* Harvester version: `v1.1.1-rc1`

### Verify Steps
1. Prepare v1.0 ipxe-example 
2. Add three additional Network interface in Vagrantfile 
3. Edit the /ansible/role/harvester/template/config-create.yaml.j2 
4. Add the cluster_network and defaultPysicalNIC to `harvester-mgmt` 
  ```
  cluster_networks:
    vlan:
      enable: true
      description: "some description about this cluster network"
      config:
        defaultPhysicalNIC: harvester-mgmt
  
  ```
5. Bond multiple NICs on `harvester-mgmt` and `harvester-vlan` networks
  ```
  networks:
      harvester-mgmt:
        interfaces:
        - name: {{ settings['harvester_network_config']['cluster'][0]['mgmt_interface'] }}  # The management interface name
        - name: ens9
        method: dhcp
      bond0:
        interfaces:
        - name: {{ settings['harvester_network_config']['cluster'][0]['vagrant_interface'] }}
        method: dhcp
      harvester-vlan:
        interfaces:
        - name: ens7
        - name: ens8
        method: none
  
  ```
6. Provision v1.0.3 Harvester 
7. Check /oem/99_custom.yaml have "21-harvester-clusternetworks.yaml"
  ```
  rancher@harvester-node-0:/oem> cat 99_custom.yaml | grep "21-harvester-clusternetworks.yaml"
      - path: /etc/rancher/rancherd/config.yaml.d/21-harvester-clusternetworks.yaml
  ```
8. Offline upgrade to v1.1.1-rc1
9. Check can successfully upgrade 
10. Check the /oem/99_custom.yaml should not contain "21-harvester-clusternetworks.yaml"
11. Create vlan 1 on `mgmt` interface, check the connectivity

### Addition Context 
IP status after upgrade 
  ```
  rancher@harvester-node-0:~> ip a
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
  2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
      link/ether 52:54:00:13:f7:2f brd ff:ff:ff:ff:ff:ff
      altname enp0s5
  3: ens6: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP group default qlen 1000
      link/ether 02:00:00:0d:62:e2 brd ff:ff:ff:ff:ff:ff
      altname enp0s6
  4: ens7: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master vlan-bo state UP group default qlen 1000
      link/ether 52:54:00:ed:7a:57 brd ff:ff:ff:ff:ff:ff
      altname enp0s7
  5: ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
      link/ether 52:54:00:1b:9c:2f brd ff:ff:ff:ff:ff:ff
      altname enp0s8
  6: ens9: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP group default qlen 1000
      link/ether 52:54:00:6e:64:80 brd ff:ff:ff:ff:ff:ff
      altname enp0s9
  7: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP group default qlen 1000
      link/ether 02:00:00:0d:62:e2 brd ff:ff:ff:ff:ff:ff
  8: mgmt-br: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
      link/ether 02:00:00:0d:62:e2 brd ff:ff:ff:ff:ff:ff
      inet 192.168.0.30/24 brd 192.168.0.255 scope global mgmt-br
         valid_lft forever preferred_lft forever
      inet 192.168.0.131/32 scope global mgmt-br
         valid_lft forever preferred_lft forever
  ```
