### ISSUE TITLE
[Need Static IP assignment with terraform]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3050]
We are trying to provision VM's through terraform. We are using cloudinit config to create the static IP but its not working it.

We are using below code to provision the static IP but it's not giving any error during terraform apply but its not creating the network..

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      package_update: true
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent.service
      EOF
    network_data = <<-EOF
      network:
        version: 1
        config:
          - type: physical
            name: eth0
            subnets:
              - type: static
                addresses: "${var.host_ip}/${var.network_subnet}"
                gateway: "${var.network_gateway}"
    EOF
  }

**Comment by Martin-Weiss** [comment]
What OS Image do you use and what do you see in the cloud-init logs? Why are you using version 1?

This works for me:

```
    network_data = <<-EOF
      version: 2
      ethernets:
        eth0:
          dhcp4: false
          addresses:
            - 10.1.1.11/24
          gateway4: 10.1.1.1
          nameservers:
            search: [suse]
            addresses: [10.1.1.1,192.168.0.31]
      EOF
```
