### ISSUE TITLE
[FEATURE] Storage Tiering support of the Harvester CSI Driver

### ISSUE THREAD

**Issue by dmytrobabeshko** [harvester/harvester#3052]
Hello,

Storage tiering was introduced in Harveser v1.1.0 recently https://github.com/harvester/harvester/issues/2147

Currently, the `harveste-csi-driver` doesn't have the option to have several storage classes which are bound to different storage classes in the harvester.

Currently, the name of the storage class used by the driver is taken from env variable from `harvester-csi-driver-pod`.
https://github.com/harvester/harvester-csi-driver/blob/0f6455e0bc7a4e53dd01ab811eab37182ba6030e/main.go#L39

Thank you in advance!

**Comment by guangbochen** [comment]
this is a known limitation of the v1.1.0 version, we will consider adding support in its future releases, and transfer the issue to the harvester repo.

**Comment by Vicente-Cheng** [comment]
Update the user story and controller flow:

Users want to create volumes with different purposes (which means different performance/capability requirements) on the `harvester` cluster at this guest cluster.

With v1.1.0, we could create different tiers (StorageClass) on the harvester. Now, `harvester-CSI-driver` should support creating PVC on the specific tier on the host.
For example, the user needs 2 replicas for some data, which only needs lower data reliability.
We could create a StorageClass for it like following:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harvester-replica-2
provisioner: driver.harvesterhci.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  hostTierName: replica-2
```
Then, the user could use this StorageClass `harvester-replica-2` to create PVC with only 2 replica.
If the user wants to create the default tier on the host, use the default StorageClass `harvester` or simply not specify any for it.

The controller flow:

PVC StorageClass would be set up from StorageClass parameter `hostTierName` or controller config `host-storage-class`.
The prioritize is SC parameter > controller config.
If w/o any definition, PVC would use the default StorageClass on the host cluster.

cc @bk201, @guangbochen
