### ISSUE TITLE
Cant get HTML config file to read on ISO install

### ISSUE THREAD

**Issue by KyleSponz** [harvester/harvester#3092]
I am testing an ISO file to fix an SFP issue I am having in [3081](https://github.com/harvester/harvester/issues/3081) virtually

I have a ubuntu vm running apache serving this config file 

```
scheme_version: 1
server_url: https://192.168.1.55:443
token: 1qaz2wsx3#

os:
  write_files:
  - content: |
     options ixgbe allow_unsupported_sfp=1
    path: /etc/modprobe.d/ixgbe.conf
  - content: |
      name: "reload ixgbe module"
      stages:
        boot:
          - commands:
            - rmmod ixgbe && modprobe ixgbe
    path: /oem/99_ixgbe.yaml
```

harvester is freezing saying: 

![Screen Shot 2022-11-02 at 4 50 21 PM](https://user-images.githubusercontent.com/2746903/199599915-5a6e6eae-bcf6-4114-9649-3e81ac458ad2.png)
