### ISSUE TITLE
[Question] GitOps Tools Available

### ISSUE THREAD

**Issue by mircea-pavel-anton** [harvester/harvester#3101]
Hello!

I was just wondering if we can use the same gitops tools that we use to manage "regular" kubernetes cluster (say for example Flux) to manage a Harvester cluster as well.

**Comment by ibrokethecloud** [comment]
what aspects of harvester would you like to be managed by gitops?

**Comment by mircea-pavel-anton** [comment]
It would be nice if I could have a directory full of yml files that describe all my VMs and their configuration (networking, pci devices etc).

I don't necessarily want to write them out by hand, but rather to create some VMs, then get the yml, put it in a repo and be able to tear down and recreate the environment, or easily go from testing to production envs.

**Comment by ibrokethecloud** [comment]
creating networks, vm's should be straight forward. 

PCIDevices I will need to check since the UI does additional CRD creation in the background for PCIDeviceClaims.

**Comment by mircea-pavel-anton** [comment]
Correct me if I am wrong, but the CRD creation is happening when the actual device is "enabled" for passthrough, right? Not when the VM is created.

So there should be a separate yaml file with the CRD to "represent" the action of enabling the device.

**Comment by ibrokethecloud** [comment]
There are 2 CRDs, the PCIDevices are created out of band, with the controller regularly checking the node for pcidevice lists and creating the objects. When the user assigns the PCIDevice to a VM, a claim is created to bind the PCIDevice to the VM.

**Comment by mircea-pavel-anton** [comment]
I have a small update on this, as well as a follow-up question.

I deployed harvester v1.1.1 on a server and enabled the `pcidevices-controller` via the GUI. I then proceeded to try and figure out what are all of the resources created in the background and then extract the yaml so I can do a `kubectl apply -f .` to enable pci passthrough.

Thus far, I identified the following resources:

- ClusterRole: `harvester-pcidevices-controller`
- ServiceAccount: `harvester-pcidevices-controller`
- ServiceAccount: `helm-pcidevices-controller`
- ClusterRoleBinding: `harvester-pcidevices-controller`
- ClusterRoleBinding: `helm-harvester-system-pcidevices-controller`
- Service: `pcidevices-webhook`
- Secret: `pcidevices-webhook-ca`
- Secret: `pcidevices-webhook-tls`
- ConfigMap: `chart-values-pcidevices-controller`
- ConfigMap: `chart-content-pcidevices-controller`
- DaemonSet: `harvester-pcidevices-controller`
- Job: `helm-install-pcidevices-controller`
- CRD: `pcidevices.devices.harvesterhci.io`
- CRD: `pcideviceclaims.devices.harvesterhci.io`

However, after applying all these, via `kubectl` the UI still shows the pcidevices-controller as disabled. What am I missing here?

**Comment by mircea-pavel-anton** [comment]
Update, I simply have to patch the `Addon` object like so:

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  annotations:
  generation: 16
  labels:
    addon.harvesterhci.io/experimental: "true"
  name: pcidevices-controller
  namespace: harvester-system
spec:
  chart: harvester-pcidevices-controller
  enabled: true
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v0.2.3
    fullnameOverride: harvester-pcidevices-controller
  version: 0.2.3
```

by setting the `spec.enabled` to `true` and everything seems to work as intended.
