### ISSUE TITLE
Configuring the containerd registry doesn't work anymore during installation

### ISSUE THREAD

**Issue by joeyloman** [harvester/harvester#3116]
**Describe the bug**
We run our clusters in an air gapped environment which needs a container registry proxy so it can download the matched rancher-agent version of the running Rancher when applying the cluster-registration-url.

When installing v1.1.0 the /etc/rancher/rke2/registries.yaml file, which is created in our environment using "os.write_files" in the config-create.yaml,  gets overwritten by the new introduced containerd-registry setting in Harvester. However this setting is not allowed/configurable in the config-create.yaml file during installation.

**To Reproduce**
1. Add the "system_settings.containerd-registry" option to the config-create.yaml
2. Install the Harvester server using v1.1.0
3. An error message appears that the containerd-registry option is not a valid option.

**Expected behavior**
This option should be allowed so we can use a container registry proxy.

**Environment**
 - Harvester ISO version:  v1.1.0
 - Rancher version: 2.6.9

**Additional information**
The following PR fixes this problem: https://github.com/harvester/harvester-installer/pull/376

**Comment by irishgordo** [comment]
@joeyloman thanks for the fix :smile: !

I've tested on Harvester Version: master-5a18d059-head

With a deployment.yaml of:
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myregistry-nginx
spec:
  selector:
    matchLabels:
      image: myregistry-nginx
  template:
    metadata:
      labels:
        image: myregistry-nginx
    spec:
      containers:
        - imagePullPolicy: Always
          image: myregistry.local:5000/nginx:latest
          name: nginx

```

Via the ipxe-examples, modifying the config-create.yaml.j2:
![Screenshot from 2022-11-07 14-53-50](https://user-images.githubusercontent.com/5370752/200432904-1596d244-3884-4bb7-8a33-ccaee8e80beb.png)
![Screenshot from 2022-11-07 14-52-47](https://user-images.githubusercontent.com/5370752/200432906-a6a34228-a4d1-49d6-af40-86181f93554f.png)
![Screenshot from 2022-11-07 14-45-02](https://user-images.githubusercontent.com/5370752/200432908-a8dc71cb-987a-47a7-a280-9af76ae00b96.png)

Via, just as a user utilizing the installer, and specifying a remote-config url, that had a config-create.yaml on a file-server (Caddy)  available:
![Screenshot from 2022-11-07 11-29-36](https://user-images.githubusercontent.com/5370752/200433688-4316a071-433d-45c5-a4d8-ec5cdbe06e8c.png)
![Screenshot from 2022-11-07 11-30-08](https://user-images.githubusercontent.com/5370752/200433722-421b13f7-33db-4ecf-8943-2de319ea6377.png)
![Screenshot from 2022-11-07 11-15-07](https://user-images.githubusercontent.com/5370752/200433193-8bcf428a-b402-48bd-9df7-0ec2d189a44e.png)
![Screenshot from 2022-11-07 11-27-59](https://user-images.githubusercontent.com/5370752/200433235-5735a98b-ebd7-45e2-bdee-51743f48e883.png)

This looks good :+1:  - I'll go ahead and close it out
