### ISSUE TITLE
[BUG] Upgrade: mismatched ISO checksum is not detected and backing image is stuck at in-progress

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3123]
**Describe the bug**

This was spotted when testing an upgrade from v1.1.0 to master ISO, and later the remote ISO was updated, so the expected checksum changed.

The download image progress is stuck at 99%.
<img width="567" alt="Screen Shot 2022-11-08 at 10 37 54 PM" src="https://user-images.githubusercontent.com/1691518/200593301-e0e320f3-8ca1-4814-8f16-55c5b2271855.png">

Checking the VirtualMachineImage
```
spec:
  checksum: cc6fae7d2103d3748b565eb626eec96bf2ddd29c44d071205405e7d0c4e7d60b73928e7f54f6f40a40bc5b36052e9f384c893a6270d24d50eb2fb3eee75634ed
  displayName: hvst-upgrade-ksdtm-v1.1.0-5a18d059
  pvcName: ""
  pvcNamespace: ""
  sourceType: download
  storageClassParameters:
    migratable: "true"
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
  url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
status:
  appliedUrl: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  conditions:
  - reason: Importing
    status: Unknown
    type: Imported
  - lastUpdateTime: "2022-11-08T11:31:18Z"
    reason: Initialized
    status: "True"
    type: Initialized
  progress: 99
  size: 5006032896
  storageClassName: longhorn-harvester-iso-z8rx5
```

From Longhorn GUI, we can see the backing image has mismatched checksum:
<img width="760" alt="Screen Shot 2022-11-08 at 10 23 10 PM" src="https://user-images.githubusercontent.com/1691518/200593777-2556b5e0-34f2-4086-92fe-53db07bd1a53.png">
And the backing image resource:
```
spec:
  checksum: cc6fae7d2103d3748b565eb626eec96bf2ddd29c44d071205405e7d0c4e7d60b73928e7f54f6f40a40bc5b36052e9f384c893a6270d24d50eb2fb3eee75634ed
  disks:
    1e46e345-e065-4cc8-b88e-210320c93823: ""
  imageURL: ""
  sourceParameters:
    url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  sourceType: download
status:
  checksum: a366e973cc346817ac25d62405193072c44f3e6ba0d0565506dede5104b3da711913255ee21ab6284ca38982083b3bebf21dcd91b685619a3a9a3e3d234e7e01
  diskDownloadProgressMap: null
  diskDownloadStateMap: {}
  diskFileStatusMap:
    1e46e345-e065-4cc8-b88e-210320c93823:
      lastStateTransitionTime: "2022-11-08T11:31:26Z"
      message: ""
      progress: 100
      state: in-progress
  diskLastRefAtMap:
    1e46e345-e065-4cc8-b88e-210320c93823: "2022-11-08T11:31:18Z"
  ownerID: harvester-z622q
  size: 5006032896
  uuid: 21e8526b
```

The state is `in-progess`.

**To Reproduce**
1. Create a version with mismatched checksums, for example, the `isoChecksum` has a wrong value:
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.1.0-5a18d059
  namespace: harvester-system
spec:
  isoChecksum: cc6fae7d2103d3748b565eb626eec96bf2ddd29c44d071205405e7d0c4e7d60b73928e7f54f6f40a40bc5b36052e9f384c893a6270d24d50eb2fb3eee75634ed
  isoURL: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  releaseDate: '20221108'
```
2. Upgrade to the version.

**Expected behavior**

The checksum mismatched should be detected,  and the upgrade should fail, not stuck at 99%.

**Support bundle**

[supportbundle_8aab8f77-c143-4518-9c7e-239decd2aeda_2022-11-08T14-33-21Z.zip](https://github.com/harvester/harvester/files/9962345/supportbundle_8aab8f77-c143-4518-9c7e-239decd2aeda_2022-11-08T14-33-21Z.zip)

**Environment**
 - Harvester ISO version: master 5a18d059
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
I see the same error when creating a VirtualMachineImage with an incorrect checksum.
Create a dependency issue: https://github.com/longhorn/longhorn/issues/4852

**Comment by khushboo-rancher** [comment]
@bk201 Just to understand the functionality, is the check of mismatched checksum included in the precheck of the upgrade?

cc: @noahgildersleeve

**Comment by noahgildersleeve** [comment]
It's worth noting that when I was testing this I put in the accurate checksum to my version.yaml file. It's just that the ISO was corrupt in some way so the checksum didn't match the distributed on on the release page. However I ran the checksum on my local ISO and it was correct in the yaml. It allows you to set it like you do in an AirGapped upgrade.

**Comment by bk201** [comment]
>> @bk201 Just to understand the functionality, is the check of mismatched checksum included in the precheck of the upgrade?
@khushboo-rancher Yes!

**Comment by bk201** [comment]
The issue is ready for testing with v1.2.0-rc3 since we bump LH.

**Comment by albinsun** [comment]
Reproduced in `v1.1.0` -> `v1.2.0-rc3`, will test `v1.2.0-rc2` -> `v1.2.0-rc3`

## Test Environment
* Harvester
  * version: `v1.1.0`
  * profile: QEMU/KVM, single node (8C/16G/250G)
  * **ui-source**: Auto


## Verification
1. Prepare an air-gapped upgrade w/ wrong checksum
   <details>

   Ref. https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
   * harvester-v1.2.0-rc3-version-wrongmd5.yaml
     ```
     apiVersion: harvesterhci.io/v1beta1
     kind: Version
     metadata:
       name: v1.2.0-rc3
       namespace: harvester-system
     spec:
       isoChecksum: 'f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb7777777777777777777777777777777777777777777777777777777777777777777777'
       isoURL: http://172.17.0.1:8080/harvester-v1.2.0-rc3-amd64.iso
       releaseDate: '20230707'
     ```
   * Correct checksum is `f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb77af706f03f4b67eace5d13dce5791edb055ca63f7df4d6cc8122b8780657e867af749`

   </details>
3. In Harvester UI, trigger Upgrade.
4. Upgrade should fail due to mismatched checksum. $~~$ :x: $\color{red}{\textsf{Upgrade stuck at Download Upgrade Image 99\\%}}$ 
   ![image](https://github.com/harvester/harvester/assets/2773781/6ab7d307-d21b-4b1c-9aea-bbc216224e69)


## Note
1. Longhorn shows backing image has mismatched checksum
   ![image](https://github.com/harvester/harvester/assets/2773781/82ba4b6c-a012-416c-9f29-97721597906d)
3. k8s BackingImage shows 100% in-progress
   ```
   $ kubectl -n longhorn-system describe BackingImage/harvester-system-harvester-iso-fsxwn
   ...
   Spec:
    Checksum:  f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb7777777777777777777777777777777777777777777777777777777777777777777777
    Disks:
      942b905a-ddc2-4ea7-bf82-e1996aee431c:  
    Image URL:                               
    Source Parameters:
      URL:        http://172.17.0.1:8080/harvester-v1.2.0-rc3-amd64.iso
    Source Type:  download
   Status:
    Checksum:                    f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb77af706f03f4b67eace5d13dce5791edb055ca63f7df4d6cc8122b8780657e867af749
    Disk Download Progress Map:  <nil>
    Disk Download State Map:
    Disk File Status Map:
      942b905a-ddc2-4ea7-bf82-e1996aee431c:
        Last State Transition Time:  2023-07-17T02:59:51Z
        Message:                     
        Progress:                    100
        State:                       in-progress
   ...
   ```

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc2` with single & 3 nodes profile, close as fixed.

## Test Environment
* Harvester
  * version: `v1.2.0-rc2`
  * profile: QEMU/KVM, 8C/16G/250G per node
    * single node
    * 3 nodes 
  * **ui-source**: Auto
* Upgrade Target
  * version: `v1.2.0-rc3`
  * checksum: `f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb77af706f03f4b67eace5d13dce5791edb055ca63f7df4d6cc8122b8780657e867af749`
  * Ref. https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade


## Verification
> **Note** Click "▸" to expand details.
1. <details><summary>Prepare an air-gapped upgrade to v1.2.0-rc3 w/ wrong checksum</summary>
   
   ```
   harvester-node-0:~ # kubectl create -f http://172.17.0.1:8080/harvester-v1.2.0-rc3-version-wrongcs.yaml
   version.harvesterhci.io/v1.2.0-rc3 created
   ```
   
   harvester-v1.2.0-rc3-version-wrongcs.yaml
   ```
   apiVersion: harvesterhci.io/v1beta1
   kind: Version
   metadata:
     name: v1.2.0-rc3
     namespace: harvester-system
   spec:
     isoChecksum: 'f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb7777777777777777777777777777777777777777777777777777777777777777777777'
     isoURL: http://172.17.0.1:8080/harvester-v1.2.0-rc3-amd64.iso
     releaseDate: '20230707'
   ```

   </details>

2. <details><summary>Trigger upgrade to v1.2.0-rc3</summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/71c466ec-fabf-49d7-b684-03fbdfbe11c1)
   
   </details>

3. Upgrade should fail due to mismatched checksum $~~$ :heavy_check_mark: 
   [hvst-upgrade-h7hfx-upgradelog-archive-2023-07-17T06-44-57Z.zip](https://github.com/harvester/harvester/files/12066627/hvst-upgrade-h7hfx-upgradelog-archive-2023-07-17T06-44-57Z.zip)  
   ![image](https://github.com/harvester/harvester/assets/2773781/2a9a7427-67e2-4312-a3c3-9430b0a4f9de)

4. <details><summary>Prepare an air-gapped upgrade to v1.2.0-rc3 w/ correct checksum</summary>

   ```
   harvester-node-0:~ # kubectl create -f http://172.17.0.1:8080/harvester-v1.2.0-rc3-refresh-version.yaml
   version.harvesterhci.io/v1.2.0-rc3-refresh created
   ```
   
   harvester-v1.2.0-rc3-refresh-version.yaml
   ```
   apiVersion: harvesterhci.io/v1beta1
   kind: Version
   metadata:
     name: v1.2.0-rc3-refresh
     namespace: harvester-system
   spec:
     isoChecksum: 'f9c163a9a11e65f141892006bc147fed5f832158fcdf741b6ef9ac11bb77af706f03f4b67eace5d13dce5791edb055ca63f7df4d6cc8122b8780657e867af749'
     isoURL: https://releases.rancher.com/harvester/v1.2.0-rc3/harvester-v1.2.0-rc3-amd64.iso
     releaseDate: '20230707'
   ```

   </details>

6. <details><summary>Trigger upgrade to v1.2.0-rc3-refresh</summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/9f768f6f-9386-4aa3-92fd-ce177b3900ad)
   
   </details>

7. Upgrade should success $~~$ :heavy_check_mark:
   * <details><summary>Download Upgrade Image $~~$ :heavy_check_mark:</summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/257dea41-7fb5-466a-83d8-637e56fa137a)

     </details>

   * <details><summary>Upgrading System Service $~~$ :heavy_check_mark:</summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cf10f945-5e42-4d94-b74f-a747e8826ae0)

     </details>

   * <details><summary>Upgrading Node $~~$ :heavy_check_mark:</summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6941100e-d125-4810-9dae-833e6523ac25)

     </details>

   
## Note
1. Test also passes in 3 nodes cluster
   * <details><summary>Upgrade fails due to mismatched checksum $~~$ :heavy_check_mark:</summary>

     [hvst-upgrade-lngzb-upgradelog-archive-2023-07-17T09-22-54Z.zip](https://github.com/harvester/harvester/files/12067754/hvst-upgrade-lngzb-upgradelog-archive-2023-07-17T09-22-54Z.zip)
     ![image](https://github.com/harvester/harvester/assets/2773781/b4e064cc-c15a-44ef-b8e7-970db3b924d0)

     Backing image is cleaned.
     ```
     harvester-node-0:~ # kubectl -n longhorn-system get BackingImage
     No resources found in longhorn-system namespace.
     ```
     </details>

   * <details><summary>Upgrade success with correct checksum $~~$ :heavy_check_mark:</summary>

     [hvst-upgrade-jqvlf-upgradelog-archive-3nodes.zip](https://github.com/harvester/harvester/files/12069031/hvst-upgrade-jqvlf-upgradelog-archive-3nodes.zip)
     
     * Trigger Upgrade
       ![image](https://github.com/harvester/harvester/assets/2773781/69eb0cf5-7fe0-4b27-a813-e05bc2f749a9)
     * Download Upgrade Image
       ![image](https://github.com/harvester/harvester/assets/2773781/ff436363-2a4f-4ff6-b8af-832571d8e5f9)
     * Upgrading System Service
       ![image](https://github.com/harvester/harvester/assets/2773781/5d147c81-af4e-4cda-bed7-00b499a344d0)
     * Upgrading Node
       ![image](https://github.com/harvester/harvester/assets/2773781/c7d4c3a5-5421-4a20-8203-af9c60291a24)

     </details>
