### ISSUE TITLE
[BUG] When creating storageclasses, selecting node/disk tag and remove it will make the storageclass unavailable

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3125]
**Describe the bug**

When creating the storageclass, selecting selector to remove it will make the storageclass unavailable

**To Reproduce**
1. Go to `Advanced >Storage Classes`
2. Click `Create`
3. input a storageclass `Name`
4. select a node/disk tag in `NodeSelector`/`DiskSelector`
5. remove the node/disk tag from `NodeSelector`/`DiskSelector`
6. Click `Create`
7. use the storage to create an image, and create a vm

the vm will always pending.

root cause:
After remove the node/disk tag from `NodeSelector`/`DiskSelector`, UI set diskSelector/nodeSelector to an empty string.
```
parameters:
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
  diskSelector: ''
  nodeSelector: ''
  migratable: 'true'
```
UI should remove the empty diskSelector and nodeSelector.

**Expected behavior**

vm will running

If the user does not select any disk/node tag, the storageClass parameters do not have the diskSelector/nodeSelector key 

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
### Question:
@futuretea I was curious, if we upload an image `uuid: 2921be3f`:
```
╭─mike at suse-workstation-team-harvester in ~
╰─○ kubectl get backingimages --all-namespaces -o wide
NAMESPACE         NAME                  UUID       SOURCETYPE   SIZE       AGE
longhorn-system   default-image-4n59p   2921be3f   upload       16338944   6m20s
longhorn-system   default-image-5krtq   f5d7e258   upload       16338944   60m

```
And in that image is using a custom storage class called "other":
![Screenshot from 2022-11-09 14-57-59](https://user-images.githubusercontent.com/5370752/200960141-6a91634e-6ebb-43db-89b0-0e74620cbacc.png)
![Screenshot from 2022-11-09 14-57-38](https://user-images.githubusercontent.com/5370752/200960143-9ad55c26-415d-4091-9110-db53741f5326.png)

But the Storage Class "other" has an empty Node Selector and empty Disk Selector.

It's looking like an image manager (backing-image-manager), upon uploading that image (backing image)(cirros) - ends up being built that is targeting the "extra-disks" - should it in the instance be targeting a "defaultdisk" instead.
Since the Storage Class "other" doesn't have any Node/Disk selectors.


### Examples:

```
╭─mike at suse-workstation-team-harvester in ~
╰─○ kubectl get backingimagemanager --all-namespaces
NAMESPACE         NAME                              STATE     IMAGE                                          NODE               DISKUUID                               DISKPATH                                                          AGE
longhorn-system   backing-image-manager-d7ad-1b56   running   longhornio/backing-image-manager:v3_20221003   harvester-node-0   1b568655-e7a5-4420-b4a8-6d8d3f330b99   /var/lib/harvester/defaultdisk                                    60m
longhorn-system   backing-image-manager-d7ad-a4be   running   longhornio/backing-image-manager:v3_20221003   harvester-node-0   a4bec3ad-f56d-49bd-afba-fe762cf1c1e9   /var/lib/harvester/extra-disks/8d1c5876c8b2fb6388eb3206fb156236   6m32s
```
![Screenshot from 2022-11-09 15-02-12](https://user-images.githubusercontent.com/5370752/200960638-29514fd3-f6ff-455f-954b-47cb27d0bca3.png)
![Screenshot from 2022-11-09 15-01-33](https://user-images.githubusercontent.com/5370752/200960642-da2e0c16-e86e-4e17-9b49-3c233147bfd9.png)

Support-bundle:
[supportbundle_d62f9ed5-1cb6-468e-a458-e0d82d2f98ac_2022-11-09T23-00-46Z.zip](https://github.com/harvester/harvester/files/9975778/supportbundle_d62f9ed5-1cb6-468e-a458-e0d82d2f98ac_2022-11-09T23-00-46Z.zip)


Describe backing image manager:
```YAML
╭─mike at suse-workstation-team-harvester in ~
╰─○ kubectl describe backingimagemanager backing-image-manager-d7ad-a4be -n longhorn-system
Name:         backing-image-manager-d7ad-a4be
Namespace:    longhorn-system
Labels:       longhorn.io/component=backing-image-manager
              longhorn.io/disk-uuid=a4bec3ad-f56d-49bd-afba-fe762cf1c1e9
              longhorn.io/managed-by=longhorn-manager
              longhorn.io/node=harvester-node-0
Annotations:  <none>
API Version:  longhorn.io/v1beta2
Kind:         BackingImageManager
Metadata:
  Creation Timestamp:  2022-11-09T22:48:29Z
  Generation:          1
  Managed Fields:
    API Version:  longhorn.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:longhorn.io/component:
          f:longhorn.io/disk-uuid:
          f:longhorn.io/managed-by:
          f:longhorn.io/node:
      f:spec:
        .:
        f:backingImages:
          .:
          f:default-image-4n59p:
        f:diskPath:
        f:diskUUID:
        f:image:
        f:nodeID:
    Manager:      longhorn-manager
    Operation:    Update
    Time:         2022-11-09T22:48:29Z
    API Version:  longhorn.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:apiMinVersion:
        f:apiVersion:
        f:backingImageFileMap:
          .:
          f:default-image-4n59p:
            .:
            f:currentChecksum:
            f:directory:
            f:downloadProgress:
            f:message:
            f:name:
            f:progress:
            f:senderManagerAddress:
            f:sendingReference:
            f:size:
            f:state:
            f:url:
            f:uuid:
        f:currentState:
        f:ip:
        f:ownerID:
        f:storageIP:
    Manager:         longhorn-manager
    Operation:       Update
    Subresource:     status
    Time:            2022-11-09T22:48:43Z
  Resource Version:  72186
  UID:               79216806-7789-449d-b926-b340990f9da0
Spec:
  Backing Images:
    default-image-4n59p:  2921be3f
  Disk Path:              /var/lib/harvester/extra-disks/8d1c5876c8b2fb6388eb3206fb156236
  Disk UUID:              a4bec3ad-f56d-49bd-afba-fe762cf1c1e9
  Image:                  longhornio/backing-image-manager:v3_20221003
  Node ID:                harvester-node-0
Status:
  API Min Version:  3
  API Version:      3
  Backing Image File Map:
    default-image-4n59p:
      Current Checksum:        553d220ed58cfee7dafe003c446a9f197ab5edf8ffc09396c74187cf83873c877e7ae041cb80f3b91489acf687183adcd689b53b38e3ddd22e627e7f98a09c46
      Directory:               
      Download Progress:       0
      Message:                 
      Name:                    default-image-4n59p
      Progress:                100
      Sender Manager Address:  
      Sending Reference:       0
      Size:                    16338944
      State:                   ready
      URL:                     
      Uuid:                    2921be3f
  Current State:               running
  Ip:                          10.52.0.178
  Owner ID:                    harvester-node-0
  Storage IP:                  10.52.0.178
Events:
  Type    Reason    Age   From                                       Message
  ----    ------    ----  ----                                       -------
  Normal  Create    16m   longhorn-backing-image-manager-controller  Creating backing image manager pod backing-image-manager-d7ad-a4be for disk a4bec3ad-f56d-49bd-afba-fe762cf1c1e9 on node harvester-node-0. Backing image manager state will become starting
  Normal  Update    16m   longhorn-backing-image-manager-controller  Backing image manager becomes state running
  Normal  Fetching  15m   longhorn-backing-image-manager-controller  Fetched the first file for backing image default-image-4n59p in disk a4bec3ad-f56d-49bd-afba-fe762cf1c1e9 on node harvester-node-0

```
