### ISSUE TITLE
[BUG] Upgrade: finished upgrades interfere with newer ones

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3152]
**Describe the bug**
This is spotted when debugging https://github.com/harvester/harvester/issues/2248#issuecomment-1313656552. A previous successful or failed upgrade can interfere with new upgrades.

**To Reproduce**
1. Create a failed upgrade. An easy way is to create an upgrade CR with a non-existent version.
    ```
    apiVersion: harvesterhci.io/v1beta1
    kind: Upgrade
    metadata:
      generateName: hvst-upgrade-
      namespace: harvester-system
    spec:
      version: "v8.8.8"
    ```
2. Create another valid upgrade. The upgrade may be stuck during the upgrading nodes phase, but somehow all nodes' Kubernetes runtime is upgraded to the newer version.

**Expected behavior**

The upgrade should complete, and nodes should upgrade in order.

**Support bundle**

[supportbundle_c7adddb8-a8ff-47b2-be67-bba2ba5b2fa5_2022-11-14T13-45-10Z.zip](https://github.com/harvester/harvester/files/10013378/supportbundle_c7adddb8-a8ff-47b2-be67-bba2ba5b2fa5_2022-11-14T13-45-10Z.zip)

**Environment**
 - Harvester ISO version: v1.0.3 -> v1.1.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

1. The cluster has 3 nodes:
    ```
    NAME              STATUS                     ROLES                       AGE    VERSION
    harvester-2mkvs   Ready,SchedulingDisabled   control-plane,etcd,master   6d4h   v1.24.7+rke2r1
    harvester-9bx6c   Ready                      control-plane,etcd,master   6d4h   v1.24.7+rke2r1    <--- second upgrade
    harvester-mrrzx   Ready                      control-plane,etcd,master   6d4h   v1.24.7+rke2r1    <--- upgrade first and done
    ```
2. Two upgrades:
    ```
    NAMESPACE          NAME                 AGE
    harvester-system   hvst-upgrade-642kq   28h  <--- create first but fail with user error (mismatched checksum)
    harvester-system   hvst-upgrade-xm6dq   28h  <--- create later, on-going.
    ```
3. When we first see the environment, we can confirm this known issue (https://github.com/rancher/rancher/issues/39167) happens. Node `harvester-mrrzx` is upgraded. Node `harvester-9bx6c` is in its post-drain phase, but the upgrade-repo VM can't start because it can't bind its volume. The support bundle included is captured at this moment.
4. Check Longhorn GUI: All volumes' replicas can't turn into healthy, even if the node is alive (`harvester-mrrzx` is upgraded and back to ready).
https://user-images.githubusercontent.com/1691518/201942344-f706aa6c-e3b7-4f14-8141-ae4cc0b67474.mov
5. After some hours, the replicas are back again, and the post-drain job of the node `harvester-9bx6c` is finished. The node is upgraded and rebooted to ready.
6. The last node, `harvester-2mkvs`, is in the pre-drain phase and waiting for all volumes to be healthy. Due to the issue https://github.com/rancher/rancher/issues/39167, the node is cordoned, and replicas on the node can't be up.
7. We found Kubernetes runtime on all nodes are upgraded to `v1.24.7+rke2r1` and `rkeConfig` in the cluster CR is reset:
    ```
      rkeConfig:
        chartValues: null
        machineGlobalConfig: null
        provisionGeneration: 1
        upgradeStrategy:
          controlPlaneDrainOptions:
            timeout: 0
          workerDrainOptions:
            timeout: 0
    ```
8. The upgrade is still in progress, but we can see the log. ([code](https://github.com/harvester/harvester/blob/02168a2396e382496426fe691c7703d48b7e22e9/pkg/controller/master/upgrade/upgrade_controller.go#L263-L288))
    ```
    2022-11-14T11:33:09.906964889Z time="2022-11-14T11:33:09Z" level=info msg="Reset RKEConfig and set provisionGeneration to 1"
    2022-11-14T11:33:09.906990579Z time="2022-11-14T11:33:09Z" level=info msg="Update cluster fleet-local/local"
    ```
9. We found the RKEConfig reset is caused by the first failed upgrade (`hvst-upgrade-642kq`).  If a Harvester backend restarts, the watched CRs' `OnChange` call run again. There are many points that the Harvester backend can restart, like the apply_manifest job, when a node is back to readiness, or a slave becomes master. I suspect this could cause the volume instability at point 4 because all RKE2 servers upgrade simultaneously.
