### ISSUE TITLE
[BUG] Harvester Cloud Provider pod fails to start / CSI storage not functional

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#3162]
**Describe the bug**
After updating the node pool of an existing RKE2 cluster running on Harvester, the harvester-cloud-provider pod failed to start. This then caused Longhorn storage volumes to fail to attach.

Similar to this issue: https://github.com/harvester/harvester/issues/2042

Events:
```
FailedMount | Pod harvester-cloud-provider-5d49884d84-rrs7kMountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
```

Example LH volume not able to attach due to harvester-cloud-provider not running:

```
[Pod prometheus-rancher-monitoring-prometheus-0](https://rancher.susedemo.com/dashboard/c/c-m-47fsvlmp/explorer/event/cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-0.17280ae56ef7bf87)
(combined from similar events): Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[prometheus-nginx nginx-home kube-api-access-bkhp8 tls-assets config-out prometheus-rancher-monitoring-prometheus-rulefiles-0 web-config config prometheus-rancher-monitoring-prometheus-db]: timed out waiting for the condition
```

**Support bundle**

[demo-pool-workers-generic-e06f987b-5j4lp-2022-11-16_15_21_56.tar.gz](https://github.com/harvester/harvester/files/10023130/demo-pool-workers-generic-e06f987b-5j4lp-2022-11-16_15_21_56.tar.gz)

**Environment**
Harvester: 1.1.0
Rancher: 2.6.9
RKE2 cluster: v1.23.10+rke2r1

**Comment by RegisWeduLabs** [comment]
I literally just had this issue.  What I've done is to edit the harvester-cloud-provider deployment in the cluster - Pod tab - Storage and changed the path to /var/lib/rancher/rke2/etc/config-files/cloud-provider-config (was /etc/kubernetes/cloud-config.

Yaml:
      volumes:
        - hostPath:
            path: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
            type: File
          name: cloud-config

**Comment by janeczku** [comment]
I can confirm that the hostPath in the harvester-cloud-provider config was set to `/etc/kubernetes/cloud-config`. And manually changing to `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` fixed the issue.

Thanks @RegisHubelia

**Comment by janeczku** [comment]
Seems to be a regression as the issue with an incorrect cloud-config path was fixed here before: https://github.com/harvester/harvester/issues/2546

**Comment by RegisWeduLabs** [comment]
@janeczku, not sure it is a regression - I'm on 1.0.3...

**Comment by janeczku** [comment]
Regression, based on the notion that there was a fix for this issue shipped in 1.0.3. #2546 
What RKE2 version was your cluster on when you encountered the issue @RegisHubelia ?

**Comment by futuretea** [comment]
I can reproduce this with rke2 version v1.23.10+rke2r1
![image](https://user-images.githubusercontent.com/15064560/203301343-c91beb16-46fe-43ee-ab02-aea4876cb949.png)
![image](https://user-images.githubusercontent.com/15064560/203301229-76880762-c5fa-41aa-975f-68684945bda9.png)
but cannot be reproduced in the latest rke2 version `v1.24.7+rke2r1`
![image](https://user-images.githubusercontent.com/15064560/203331674-8944e24c-9a37-4839-8d4d-0905e7c82b90.png)

**Comment by RegisWeduLabs** [comment]
> Regression, based on the notion that there was a fix for this issue shipped in 1.0.3. #2546 What RKE2 version was your cluster on when you encountered the issue @RegisHubelia ?

Sorry - just saw this.  RKE v1.24.7+rke2r1

**Comment by qrkourier** [comment]
I encountered this issue in v1.24.11 +rke2r1 after changing the layout of the guest cluster created in RMS. The workaround was to change the hostPath in the deployment to `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config`.

**Comment by futuretea** [comment]
@qrkourier, Hi, I can not reproduce this issue using v1.24.11+rke2r1. Can you help to describe in detail the procedure for reproducing and the version of Harvester, Rancher used, Thanks.

**Comment by qrkourier** [comment]
It was Harvester v1.1.1 and Rancher 2.6.11. I encountered the issue when I added a second pool and changed the first pool's per-node memory allocation simultaneously. The first pool was running without this issue for a couple of weeks.

**Comment by staedter** [comment]
I have run into similar issues. I created a issue in the rancher repo, maybe that was the wrong place [https://github.com/rancher/rancher/issues/41943](https://github.com/rancher/rancher/issues/41943)

I have also now encountered it with cluster created through a custom generic cluster template. The problem there is also, that I have no cloud-config file in either of the hostpaths (/var/lib/rancher/rke2/etc/config-files/cloud-provider-config  and /etc/kubernetes/cloud-config)

At which point is the cloud-config injected on the hosts and can I controll in which path it is mounted?

edit: I have closed the original issue because my problem was created by a firewall rule that I was unaware of. But I still would like to find out where I can controll the harvester-cloud-config injection for downstream clusters

**Comment by danielbjornadal** [comment]
> I have run into similar issues. I created a issue in the rancher repo, maybe that was the wrong place [rancher/rancher#41943](https://github.com/rancher/rancher/issues/41943)
> 
> I have also now encountered it with cluster created through a custom generic cluster template. The problem there is also, that I have no cloud-config file in either of the hostpaths (/var/lib/rancher/rke2/etc/config-files/cloud-provider-config and /etc/kubernetes/cloud-config)
> 
> At which point is the cloud-config injected on the hosts and can I controll in which path it is mounted?
> 
> edit: I have closed the original issue because my problem was created by a firewall rule that I was unaware of. But I still would like to find out where I can controll the harvester-cloud-config injection for downstream clusters

Did you find a cure for this?

**Comment by RegisWeduLabs** [comment]
If you edit the yaml of your cluster, you should be able to set this:

```
  rkeConfig:
    chartValues:
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
        global:
          cattle:
            clusterName: (nameofthecluster - as it sometime causes issues with load balancers for IP pools)
```

**Comment by HoustonDad** [comment]
Rancher v2.8.5 and Harvester v1.3.0

The workaround does not work for me. I get this error after setting rkeConfig.chartValues.harvester-cloud-provider.cloudConfigPath now:

```
│   Warning  FailedMount       15s (x7 over 47s)  kubelet            MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config is not a file
```

The path '/var/lib/rancher/rke2/etc' does not exist on my VMs. It seems if we simply `mkdir -p` the needed directory and `touch` cloud-config, things seem to work and the container starts, but gets further errors, so it feels like this file is supposed to be on disk, but isn't?

```
│ F0905 16:49:37.175605       1 main.go:73] Cloud provider harvester could not be initialized: could not init cloud provider "harvester": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```


I can replicate this 100% of the time when using the following configurations:

```
  rkeConfig:
    chartValues:
      rke2-cilium:
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        ipv6:
          enabled: false
        k8sServiceHost: 127.0.0.1
        k8sServicePort: '6443'
        kubeProxyReplacement: true
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config

####################
    machineGlobalConfig:
      cluster-cidr: 10.42.0.0/16
      cni: cilium
      disable-kube-proxy: true
      etcd-expose-metrics: false
      service-cidr: 10.43.0.0/16
      profile: null
```
