### ISSUE TITLE
[BUG] Upgrade: new CRDs in a dependency chart are not created 

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3185]
**Describe the bug**

We introduce the [whereabouts dependency chart](https://github.com/harvester/harvester/tree/master/deploy/charts/harvester/dependency_charts/whereabouts) in v1.1.0 and found upgrading from v1.0.3 to v1.1.0 doesn't create the [CRDs](https://github.com/harvester/harvester/tree/master/deploy/charts/harvester/dependency_charts/whereabouts/crds) it wants.

This could apply to all dependency charts of a ManagedChart.

**To Reproduce**
1. Upgrade from v1.0.3 to v1.1.0.
2. [Whereabouts CRDs](https://github.com/harvester/harvester/tree/master/deploy/charts/harvester/dependency_charts/whereabouts/crds) are not created.
    ```
    # return error!
    kubectl get crds ipools.whereabouts.cni.cncf.io
    ```

**Expected behavior**

The CRDs should be created.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
We implement a workaround in v1.1.1 (https://github.com/harvester/harvester/issues/3168), but we still need to figure out the root cause.

**Comment by khushboo-rancher** [comment]
We should have these checks in our test automation.
cc @harvester/qa

**Comment by w13915984028** [comment]
I suspect this is due to our release naming management:

Both Harvester-CRD and Harvester do not have an increasing nameing in each release, they all have:

https://github.com/harvester/harvester/blob/master/deploy/charts/harvester-crd/Chart.yaml#L3
version: 0.0.0-dev

https://github.com/harvester/harvester/blob/master/deploy/charts/harvester/Chart.yaml#L3
version: 0.0.0-dev

The unchanged version will confuse fleet-agent/helm to upgrade them.

@bk201 @guangbochen do we have plan to naming them in each release ?

**Comment by w13915984028** [comment]
For `manangedchart`, there are releases naming like:
```
harv2:~ # kk get managedchart -n fleet-local harvester-crd -oyaml
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
..
  creationTimestamp: "2023-02-20T10:27:22Z"
  generation: 1
  name: harvester-crd
  namespace: fleet-local

spec:
  chart: harvester-crd
  defaultNamespace: harvester-system
  releaseName: harvester-crd
  repoName: harvester-charts
..
  values: {}
  version: 0.0.0-master-653a581
```
fleet-agent will see this version.

But the Harvester chart itself, we have static `0.0.0-dev` version, in the view of Helm (fleet-agent will finally call helm), it does not change.

Comparing, the LH chart version
https://github.com/longhorn/longhorn/blob/master/chart/Chart.yaml#L3
```
version: 1.4.0-dev
appVersion: v1.4.0-dev
kubeVersion: ">=1.21.0-0"
```
