### ISSUE TITLE
[BUG] Upgrade from 1.0.3 to 1.1.0 stuck in phase3 (after failed previous attempt?)

### ISSUE THREAD

**Issue by zensonic** [harvester/harvester#3202]
**Describe the bug**

We have tried to upgrade from 1.0.3 to 1.1.0. That failed/hung due to the cluster not fully being provisioned 14 days ago (had two ghost nodes for unknown reasons). We remove, the upgrade continued somewhat, but eventually failed and we retried. See #3201 

On second attempt the upgrade VM fails with:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-23T17:22:27Z"
    message: 'containers with unready status: [compute]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  - lastProbeTime: "2022-11-23T17:24:12Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  created: true
  printableStatus: Running
  volumeSnapshotStatuses:
  - enabled: true
    name: disk-0
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
```

**To Reproduce**
1. Install 4 node cluster. Somehow get 2 ghost nodes to remain in provisioning state
2. Attempt upgrade from 1.0.3 to 1.1.0
3. Kill ghost nodes
4. Restart upgrade

**Expected behavior**
Upgrade can be restarted even after failure. 

**Support bundle**
Will be provided if needed

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Cisco C240-M4 x 4

**Additional context**
