### ISSUE TITLE
[Question]how to use cloud config to default setting user and password

### ISSUE THREAD

**Issue by huangkaiyan10** [harvester/harvester#3289]
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
system_info:
  default_user:
    name: root
    lock_passwd: false
    shell: /bin/bash

# vim:syntax=yaml
chpasswd:
  list: |
    root:root
  expire: false

![image](https://user-images.githubusercontent.com/5146180/208038921-00ef1795-5809-448e-8f73-4f4d98bbc7a2.png)

but i use root/root  can not login in .

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/208039096-c418d3fd-58db-4f33-9390-e32d8bce0aa4.png)

**Comment by bk201** [comment]
Perhaps try:
```
password: xxx
chpasswd: {expire: False}
ssh_pwauth: True
```

Please keep in mind using SSH keys is more secure.

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/208048964-89d2f04d-1f10-4b0a-ac31-abb62ae1871b.png)
Set it this way doesn't work either
![image](https://user-images.githubusercontent.com/5146180/208048963-c6d3f696-ac4d-409d-84f7-09aba9576fb4.png)

**Comment by huangkaiyan10** [comment]
> 
not work

**Comment by bk201** [comment]
Is the cloud-init installed? What's the image you are using. Thanks.

**Comment by huangkaiyan10** [comment]
> Is the cloud-init installed? What's the image you are using. Thanks.
openEuler-22.09-x86_64.qcow2

**Comment by ApolloDS** [comment]
For a cloud-init user you need to specify a password as described here:
https://cloudinit.readthedocs.io/en/latest/topics/examples.html

passwd: The hash -- not the password itself -- of the password you want
 to use for this user. You can generate a hash via:
``` 
mkpasswd --method=SHA-512 --rounds=4096
```
 (the above command would create from stdin an SHA-512 password hash with 4096 salt rounds)

I use the following in the Cloud config template:
```
users:
  - default
  - name: myusername
    ssh_authorized_keys:
      - ssh-rsa ABCDEFGHI..... user@domain.com
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
  - name: myanotherusername
    passwd: $4$rounds=4096$./ABCDEFGHI......
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa ABCDEFGHI...... user@domain.com
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
```
