### ISSUE TITLE
[BUG] Check node health, cluster, managedchart, and machine status before upgrade

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#3298]
**Describe the bug**
1. A cluster with unhealthy node can get into the upgrade.

2. Rancher cluster status

Need to add an additional check of Rancher cluster phase (clusters.cluster.x-k8s.io local -n fleet-local), if it is not in `Provisioned`, we should prevent upgrade, otherweise the POD may keep waiting for Provisioned, but never success.

https://github.com/harvester/harvester/blob/master/package/upgrade/upgrade_manifests.sh#L247

PR https://github.com/harvester/harvester/pull/2836 adds check in`Delete`, but `Create` seems should also check rancher cluster status.

PR https://github.com/harvester/harvester/pull/3093 will include more.

3. Managedchart status

Meanwhile, should also check the status of managedchart, to ensure they are ready.
```
status:
  conditions:
  - lastUpdateTime: "2023-02-13T10:18:52Z"
    status: "True"
    type: Ready
```

```
kubectl get managedchart -n fleet-local
NAME                                      AGE
harvester                                 2d17h
harvester-crd                             2d17h
local-managed-system-upgrade-controller   2d17h
rancher-logging-crd                       2d17h
rancher-monitoring-crd                    2d17h
```

**To Reproduce**
1. Create a 2-node harvester cluster.
2. Stop the agent node.
3. Apply a new version.
```
cat <<EOF | kubectl apply -f -
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: master-head
  namespace: harvester-system
spec:
  isoURL: "http://192.168.0.181:8000/harvester-master-amd64.iso"
EOF
```
4. Click the upgrade on the dashboard.

**Expected behavior**
Webhook should stop the upgrade.

We also want to check if the CAPI cluster is provisioned and if all managed charts are ready. (consolidated from https://github.com/harvester/harvester/issues/3391#top)

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by TachunLin** [comment]
Verified **fixed** on `master-365036c5-head` . Close this issue.

### Result
#### Test Case 1: A cluster with any non-ready node can't be upgraded
When we stop the worker node and upgrade to the same master version
When we upgrade, webhook should stop the upgrade because a node is not ready.
![image](https://user-images.githubusercontent.com/29251855/235588808-eaad0022-49d9-4e6a-b5c1-b05c58987c09.png)



#### Test Case 2: A cluster with any maintenance node can't be upgraded.
When we stop one of the management node and upgrade to the same master version
When we upgrade, webhook should stop the upgrade because a node is not ready.
![image](https://user-images.githubusercontent.com/29251855/235595572-b3671b65-4284-4ab4-aa48-d235732e1642.png)




#### Test Case 3: A cluster with any non-ready managed chart can't be upgraded.
After we change the the harvester-webhook image in the cluster to make the ManagedChart in `not ready`.

```
containers:
  - env:
    - name: HARVESTER_WEBHOOK_SERVER_HTTPS_PORT
      value: "9443"
    - name: NAMESPACE
      valueFrom: 
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: HARVESTER_DEBUG
      value: "false"
    - name: HARVESTER_CONTROLLER_USER_NAME
      value: system:serviceaccount:harvester-system:harvester
    image: davidtclin58/harvester-webhook-master:test
    imagePullPolicy: IfNotPresent
    name: harvester-webhook
```

When we upgrade, webhook should stop the upgrade because a node is not ready.
![image](https://user-images.githubusercontent.com/29251855/235616516-6943bd40-a1a2-4347-b824-7227021086eb.png)



### Test Information
* Test Environment: 3 nodes harvester on bare machine
* Harvester version: `master-365036c5-head`

### Verify Steps
https://github.com/harvester/harvester/issues/3500#issuecomment-1449273183

#### Case 3 details steps
1. Create a 3-node harvester cluster. 
2. Create another harvester-webhook image with a different name.
  ```
  $ sudo docker pull rancher/harvester-webhook:master-head
  $ sudo docker tag rancher/harvester-webhook:master-head davidtclin58/harvester-webhook-master:test
  $ sudo docker push davidtclin58/harvester-webhook-master:test
  ```

3. Change the harvester-webhook image in the cluster. (k9s -> search deployments -> harvester-webhook)
```
containers:
  - env:
    - name: HARVESTER_WEBHOOK_SERVER_HTTPS_PORT
      value: "9443"
    - name: NAMESPACE
      valueFrom: 
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: HARVESTER_DEBUG
      value: "false"
    - name: HARVESTER_CONTROLLER_USER_NAME
      value: system:serviceaccount:harvester-system:harvester
    image: davidtclin58/harvester-webhook-master:test
    imagePullPolicy: IfNotPresent
    name: harvester-webhook
```
4. Check the harvester ManagedChart is not ready.
5. Click the upgrade on the dashboard.
6. Webhook should stop the upgrade because the harvester ManagedChart is not ready.
