### ISSUE TITLE
[BUG] vm backup lost ReservedMemory config

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#3301]
**Describe the bug**
this option in vm's edit config page: **Advance Options** - **ShowMore** - **Reserved Memory**
![reserved-mem-200](https://user-images.githubusercontent.com/987637/208570203-2fa71fb1-090d-4504-a6e1-a9aaaf963998.PNG)
when backup vm, this config not saved.  then restored vm lost this config.

**To Reproduce**
1. create a normal vm-1 mem=2G  (default ReservedMemory is 100M), check yaml Memory-guest=**1948Mi**
2. create a vm-2 mem=2G ReservedMemory=200M 
3. check the created vm yaml, Memory-guest=**1848Mi**
4. backup this vm
5. restore this backup to vm-3, check yaml Memory-guest=**1948Mi**

vm-1
```
        memory:
          guest: 1948Mi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
```

vm-2
```
         memory:
          guest: 1848Mi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
```

vm-3
```
        memory:
          guest: 1948Mi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
```

**Expected behavior**
this config should be backup & restored,  or the calculated memory value.

**Environment**
 - Harvester ISO version:  v1.0.2,  v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
