### ISSUE TITLE
[BUG] An empty log-level value gets error

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#3340]
**Describe the bug**
Update log-level value and then update it back to empty. We will get error message in status.

```
status:
  conditions:
  - lastUpdateTime: "2023-01-05T06:13:19Z"
    message: 'not a valid logrus Level: ""'
    status: "False"
    type: configured
```

**To Reproduce**
1. Update `log-level` setting to `debug`
2. Update `log-level` setting to empty.
3. We get error in status.

**Expected behavior**
The `log-level` should use default value.

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM
