### ISSUE TITLE
[Enhancement] Doc to remove a disk safely

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3345]
**Is your feature request related to a problem? Please describe.**
We have a [doc](https://docs.harvesterhci.io/v1.1/host/#add-additional-disks) to add new disks. But there is no doc for removing existing disks safely.

**Describe the solution you'd like**

Add a doc to describe how to remove disks safely.
Before https://github.com/harvester/harvester/issues/3344 is implemented, the user needs to evict data from Longhorn GUI first. 

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Follow the preview document of the following to remove disk on bare metal machines. 
* https://deploy-preview-289--harvester-preview.netlify.app/dev/host/#remove-disks 
* https://github.com/harvester/harvesterhci.io/pull/34 

We can correctly remove the disk from node on Harvester `v1.1.2-rc6`. Close this issue 

#### Identify the disk to remove (Harvester dashboard)
* Find the disk mount path for the eviction
![image](https://user-images.githubusercontent.com/29251855/231079261-145e890b-8265-4292-81af-77fb77b89f16.png)

#### Evict replicas (Longhorn dashboard)
* We can find the disk to be removed from Longhorn UI 
![image](https://user-images.githubusercontent.com/29251855/231081215-9e78cae8-fac2-41a5-b603-4b2d47a020fd.png)

* Can disable scheduling and enable eviction
![image](https://user-images.githubusercontent.com/29251855/231082180-341e1ce0-ae4c-487e-9723-e7218b43b067.png)


#### Remove the disk (Harvester dashboard)
* Can remove disk from node on Harvester host page
![image](https://user-images.githubusercontent.com/29251855/231083125-9702426b-094f-433a-a969-e7056b5b740b.png)

* The disk already removed from Longhorn UI
![image](https://user-images.githubusercontent.com/29251855/231083346-999e2c46-68a5-46a3-b486-3a93c423bd42.png)






* Evict disk from CLI
  ```
  spec:
    allowScheduling: true
    disks:
      9da6d91c6c767911424340686114b517:
        allowScheduling: false
        evictionRequested: true
        path: /var/lib/harvester/extra-disks/9da6d91c6c767911424340686114b517
        storageReserved: 0
      default-disk-22addffabd1dfca:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/defaultdisk
        storageReserved: 255991551590
        tags:
        - ssd
  ```

  ```
  node1:~ # kubectl get -n longhorn-system nodes.longhorn.io node1 -o yaml | yq e '.status.diskStatus.9da6d91c6c767911424340686114b517.scheduledReplica'
  {}
  ```

* Check the longhorn UI, the disk already been disabled
![image](https://user-images.githubusercontent.com/29251855/231086687-5eb24b8e-a529-4e1a-a6fe-19cf23dcb817.png)

### Test Information
* Test Environment: 3 nodes harvester bare machines
* Harvester version: `v1.1.2-rc6`
