### ISSUE TITLE
[BUG] the status of rke2 cluster will stuck after add a static NIC by `Edit Config`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3384]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/213156577-db22a38d-d977-45c7-bec8-b917e94f9a65.png)

**To Reproduce**
1. node driver v0.6.1
2. create a rke2 cluster with one NIC
![image](https://user-images.githubusercontent.com/15064560/213146013-9fe0656e-ccd7-468e-bd5e-a9addc534b64.png)
4. wait until the cluster status changes to `Active`
5. edit config
6. add a Network
7. set static ip by networkdata
```yaml
network:
  version: 1
  config:
   - type: physical
     name: enp1s0
     subnets:
     - type: dhcp
   - type: physical
     name: enp2s0
     subnets:
     - type: static
       address: 192.168.5.91/24
```
![image](https://user-images.githubusercontent.com/15064560/213145404-e8cc8d3b-887e-441e-b691-cd93064e3020.png)

**Expected behavior**

Cluster update succeeded

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
