### ISSUE TITLE
[BUG] installer: vip_hw_addr from config file is ignored when no vip is specified

### ISSUE THREAD

**Issue by ldruschk** [harvester/harvester#3437]
**Describe the bug**
We are installing Harvester using an automated setup and by specifying an installer config. We set `vip_mode` to `dhcp` and specify `vip_hw_addr` to some mac address. After the installation, the specified `vip_hw_addr` is ignored.

**To Reproduce**
1. create a config file such as the following:
```
scheme_version: 1
token: token
os:
  hostname: harvester-01
  password: password
install:
  mode: create
  management_interface:
    interfaces:
    - name: eno1
    method: dhcp
  device: /dev/sda
  iso_url: ...
  vip_mode: dhcp
  vip_hw_addr: aa:bb:cc:dd:ee:ff
```
2. Run the installer and provide the config
3. after the installation, check the vip mac address using `kubectl get -o yaml cm -n harvester-system vip`
4. notice that the hwAddr does not match the one from the config file

**Expected behavior**
The `vip` should not be needed when using `vip_mode: dhcp` (at least in create mode), since as far as I can tell it is not used anyways.

**Support bundle**
not necessary I believe

**Environment**
 - Harvester ISO version: 1.1.1

**Additional context**
https://github.com/harvester/harvester-installer/blob/cc79bf2e64acc55d5b91df2514747386e9050ff2/pkg/config/templates/rancherd-10-harvester.yaml#L110
I could not find a way to open an issue over there, so I hope this is the correct repository.
