### ISSUE TITLE
[BUG] RKE2 stuck in creating (2 NICs) nodes with error: flags provided: missing section: network

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3443]
### Describe the bug
Nodes shows errors like:
> Failed creating server [fleet-default/rke2-p-2ee3dc0e-pv7k6] of kind (HarvesterMachine) for machine rke2-p-68578bd8bf-bhdb6 in infrastructure provider: CreateError: Downloading driver from https://<internal_rancher_IP>/assets/docker-machine-driver-harvester Doing /etc/rancher/ssl docker-machine-driver-harvester docker-machine-driver-harvester: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key [cmdCreateInner] error setting machine configuration from flags provided: missing section: network

then trying to re-creating

### To Reproduce
1. Install Harvester `v1.1-head` with any nodes
2. Create image and VM Network for RKE2
3. Install Rancher `v2.7-head`
4. Import Harvester
5. Create RKE2 cluster with the image and 2 NICs (duplicate VM Network)
6. RKE2 stuck in provisioning

### Expected behavior
RKE2 should provisioned successfully

## Environment:
 - Harvester ISO version: **v1.1-ad597fd1-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**
- Rancher Version: **v2.7-569feaa66ac4bcb015c14c4adce098b36e7e0d9c-head**
- Harvester Node Driver Version: **Built-in**  == `v0.6.1`

**Comment by lanfon72** [comment]
Nodes with 1 NIC will not encounter the error.

**Comment by futuretea** [comment]
The error may be due to the incorrect format of networkdata being used,
such as:
```yaml
netwoork:
  version: 1
  config:
   - type: physical
     name: enp1s0
     subnets:
     - type: dhcp
   - type: physical
     name: enp2s0
     subnets:
     - type: dhcp
```

s/netwoork/network/

**Comment by futuretea** [comment]
the root cause is using an incorrect networkdata format:
```yaml
#cloud-config
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: dhcp
```
which missing the `network` section,

the correct format should be：
```yaml
network:
  version: 1
  config:
   - type: physical
     name: enp1s0
     subnets:
     - type: dhcp
   - type: physical
     name: enp2s0
     subnets:
     - type: dhcp
```

refer to:
https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#
http://kubevirt.io/user-guide/virtual_machines/startup_scripts/#network-config

**Comment by guangbochen** [comment]
Let's also add the requirements and limitations to the doc so users can refer to it properly; thanks.

**Comment by futuretea** [comment]
It has been tested that using the configuration directly on the vm page without the network section can properly configure the network：
```yaml
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: dhcp
```
So I think we should support this configuration for users, CC @guangbochen

**Comment by lanfon72** [comment]
I found that a discussion said the `network` key is not required[^1] but I can't find it in official document. :thinking: 
Consider that both format are supported in kubevirt, I would suggest that we should align kubevirt's behavior.
But as we still can use another format to spawn RKE2, I thought this issue could be defer to `v1.2.0`.

[^1]: https://askubuntu.com/a/1405307

**Comment by futuretea** [comment]
Rancher issue: https://github.com/rancher/rancher/issues/40633
Rancher v2.7 PR: https://github.com/rancher/rancher/pull/40634
Rancher v2.6 PR: https://github.com/rancher/rancher/pull/40635

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/220833538-4a9831b2-11d9-455f-a247-8384fe1234c5.png)
![image](https://user-images.githubusercontent.com/5169694/220833700-65eb0a79-5003-44a9-9460-a305ed19de7f.png)
![image](https://user-images.githubusercontent.com/5169694/220833596-4c36838f-f196-4f5c-9b97-57a2c66158ec.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-7c60dc0856e19c278d520946d4d2e7ea2b86d70f-head** and **v2.6-657d8ec456f572efb4503d3499f2eedff0edab96-head** (Docker Image: **cf565c7e2276** and **964540586c5c**)

### Verify Steps:
1. Follow **Step to Reproduce** in https://github.com/harvester/harvester/issues/3443#issue-1579797654
2. use the **Network Data** like:
```yaml
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: dhcp
```
