### ISSUE TITLE
[BUG] Operating System and RKE2 logs missing PROGRAMNAME

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3470]
**Describe the bug**
It seems that we are missing journald logs and kubelet.log of RKE2 and maybe more -> can we enable "all" logs to be forwarded via the logging system?

-> basically the logs come to the central place via syslog but they are all ending up with an unknown source as "PROGRAMNAME" seems to be missing

**To Reproduce**
Configure Harvester Logging to forward everything via syslog to a central rsyslog server.

**Expected behavior**
All logs are forwarded and can be separated to different files based on their source.

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by w13915984028** [comment]
As discussed, most of those logs are collected by default.
https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-15-logging.yaml#L27

rke2 collects kubelet.log
https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-logging/100.1.1%2Bup3.17.3/templates/loggings/rke2/daemonset.yaml#L34

**Comment by Martin-Weiss** [comment]
Thanks - seems the problem is that these logs are forwarded via syslog in a way that is missing the right "PROGRAMNAME".. the container/pod logs come well but the OS logs not..

In rsyslogd we have this configured:

`$template RemoteLogs,“/data/logging/%HOSTNAME%/%PROGRAMNAME%.log`

but we just get a file "`-.log`" for the logs comming from tbe above ones (i.e. `kubelet.log`).

-> do we have any idea how we get get the PROGRAMNAME added properly in the "OS side of logs" as well?

**Comment by w13915984028** [comment]
Please refer
https://github.com/w13915984028/harvester-develop-summary/blob/main/filter-and-customize-system-logs.md

May define a new pair of ClusterFlow and ClusterOutput to filter and customize the system related logs, and use the newly added record fields.

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: logging-system
  namespace: cattle-logging-system
spec:
  filters:
  - grep:
     regexp:
     - key: SYSLOG_IDENTIFIER
       pattern: /(^.*rke2.*$|^.*wicked.*$|^.*iscsid.*$|^kernel$)/
  - record_transformer:
      records:
      - appname: ${record["SYSLOG_IDENTIFIER"]}
  - tag_normaliser: {}
  match: 
  globalOutputRefs:
    - logging-system
```


```
clusteroutput:
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: logging-system
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      ...
    format:
      app_name_field: appname
```
