### ISSUE TITLE
[BUG] Upgrade stuck in waiting the degraded volume that not start rebuilding

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3526]
### Describe the bug
The volume is not created by user.

![image](https://user-images.githubusercontent.com/5169694/220706681-4bb59c06-6b24-474f-baf5-7b1b7876c0b8.png)

### To Reproduce
1. Install Harvester with 4 nodes
2. Create Image for VM creation
3. Create VM Network
4. Setup backup-target
5. Import Harvester to Rancher
6. Create RKE2 with 3 machines
7. Take backup for each RKE2 VM
8. Create VM `vm1`, write some data
9. Back up `vm1`
10. Perform upgrade

### Expected behavior
Volume should rebuild automatically or should be skip waiting

## Environment:
 - Harvester ISO version: **v1.1.1** upgrade to **v1.1.2-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360G9 4 nodes**

### Additional context
regression test of 4 nodes upgrade

**Comment by Vicente-Cheng** [comment]
The problematic volume: `pvc-79ee3ece-3e7f-492d-b8cb-ad04274fe16d-r-f899faea`
Figure out the longhorn-manager log as follows:
```
2023-02-22T01:10:37.712779486Z stderr F time="2023-02-22T01:10:37Z" level=debug msg="Prepare to create instance pvc-79ee3ece-3e7f-492d-b8cb-ad04274fe16d-r-f899faea"
2023-02-22T01:10:37.712807572Z stderr F time="2023-02-22T01:10:37Z" level=debug msg="Replica pvc-79ee3ece-3e7f-492d-b8cb-ad04274fe16d-r-f899faea will ask backing image harvester-system-harvester-iso-8wrjm to download file to node harvester-gctnr disk e0b00dd4-c795-446b-9fdc-1b9f50ed7c3d" controller=longhorn-replica dataPath= node=harvester-gctnr nodeID=harvester-gctnr ownerID=harvester-gctnr replica=pvc-79ee3ece-3e7f-492d-b8cb-ad04274fe16d-r-f899faea 
```
Then we try to check on the backing-image-manager log.
```
2023-02-22T01:10:37.978516107Z stderr F time="2023-02-22T01:10:37Z" level=info msg="Backing Image Manager: prepare to sync backing image" biName=harvester-system-harvester-iso-8wrjm biUUID=d0801fdd component=backing-image-manager diskPath=/data/ diskUUID=e0b00dd4-c795-446b-9fdc-1b9f50ed7c3d fromAddress="10.52.1.52:8000"
.
.
.
.
.
// failed here
2023-02-23T01:10:38.986784403Z stderr F time="2023-02-23T01:10:38Z" level=error msg="Backing Image Manager: timeout waiting before releasing port 30002" biName=harvester-system-harvester-iso-8wrjm biUUID=d0801fdd component=backing-image-manager diskPath=/data/ diskUUID=e0b00dd4-c795-446b-9fdc-1b9f50ed7c3d error="failed to wait for backing image harvester-system-harvester-iso-8wrjm(d0801fdd) becoming an ending state, current state in-progress" fromAddress="10.52.1.52:8000"
```
So we know the backing image would be synced from `10.52.1.52`.
We tried to find the pod with 10.52.1.52  on node `harvester-5gvfc` and could not find any pod with this IP.
Check again with backing-image-manager on the node `harvester-5gvfc`.
```
creationTimestamp: "2023-02-22T01:18:31Z"                                                                                                        
labels:                                                                                                                                          
  longhorn.io/component: backing-image-manager                                                                                                   
  longhorn.io/disk-uuid: 3b1ea50b-ff43-42c9-bc13-b4d9c72ef82a                                                                                    
  longhorn.io/managed-by: longhorn-manager                                                                                                       
  longhorn.io/node: harvester-5gvfc                                                                                                              
name: backing-image-manager-d7ad-3b1e
```
We only know the old backing-image-manager pod is somehow dead and caused the backing image syncing to fail.
Try a workaround like https://docs.harvesterhci.io/v1.0/upgrade/v1-0-2-to-v1-0-3#2-an-upgrade-is-stuck-a-node-is-in-pre-drained-state-case-1 and looks like work (means the backing image re-sync).

Similar issue as https://github.com/harvester/harvester/issues/2053, https://github.com/longhorn/longhorn/issues/4305
