### ISSUE TITLE
[BUG] The configmap against rke2-ingress-nginx has no effect

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3554]
**Describe the bug**

In troubleshooting https://github.com/harvester/harvester/issues/3450, we observed the configmap against rke2-ingress-nginx has no effect.

**To Reproduce**
1.  get current related configmap
```
harv2:~ # kk get configmap -n kube-system rke2-ingress-nginx-controller -o yaml
apiVersion: v1
data:
  allow-snippet-annotations: "false"
  proxy-body-size: "0"
  proxy-request-buffering: "off"
```

2. those configs are not in nginx config
```
www-data@rke2-ingress-nginx-controller-s5lkv:/etc/nginx> grep "proxy-body-size" /etc/nginx/nginx.conf
www-data@rke2-ingress-nginx-controller-s5lkv:/etc/nginx> grep "proxy-request-buffering" /etc/nginx/nginx.conf
```

3. when adding new config items in this configmap, it aslo has no effect
```
harv2:~ # kk get configmap -n kube-system rke2-ingress-nginx-controller -o yaml
apiVersion: v1
data:
  allow-snippet-annotations: "false"
  proxy-body-size: "0"
  proxy-read-timeout: 120s
  proxy-request-buffering: "off"
  proxy-send-timeout: 120s
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: rke2-ingress-nginx
    meta.helm.sh/release-namespace: kube-system
```

we can only skip the issue with a workaround 
https://github.com/harvester/harvester/issues/3450#issuecomment-1443937746

**Expected behavior**

The configmap is used by `rke2-ingress-nginx`, it should be valid.

```
harv2:~ # kk get pods -n kube-system rke2-ingress-nginx-controller-kl2kj -o yaml
apiVersion: v1
kind: Pod
...
  containers:
  - args:
    - /nginx-ingress-controller
    - --election-id=ingress-controller-leader
    - --controller-class=k8s.io/ingress-nginx
    - --ingress-class=nginx
    - --configmap=$(POD_NAMESPACE)/rke2-ingress-nginx-controller --------- specified configmap, but not working
    - --validating-webhook=:8444
    - --validating-webhook-certificate=/usr/local/certificates/cert
    - --validating-webhook-key=/usr/local/certificates/key
    - --watch-ingress-without-class=true
    - --default-ssl-certificate=cattle-system/tls-rancher-internal
```

**Support bundle**

**Environment**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
