### ISSUE TITLE
[BUG] Harvester single node upgrade will get `another operation (install/upgrade/rollback) is in progress` error

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3616]
**Describe the bug**
Harvester single node upgrade will encounter `another operation (install/upgrade/rollback) is in progress` error after node reboot. Therefore, it will block the next Harvester upgrade or managedChart update. Potentially related to https://github.com/helm/helm/issues/8987#issuecomment-786149813

**To Reproduce**
1. Install a Harvester cluster with an old version, e.g., v1.1.1
2. upgrade the Harvester cluster to a newer version, e.g., v1.1.2-head.iso
3. after the upgrade is complete, the upgrade status shows success, then check the `harvester` managedChart status and it will contain an error of:
```
conditions:
  - lastUpdateTime: "2023-03-08T05:42:32Z"
    message: 'ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback)
      is in progress]; daemonset.apps harvester-system/kube-vip [progressing] Available:
      0/1; kubevirt.kubevirt.io harvester-system/kubevirt [progressing] Deployin
```

**Expected behavior**
single node upgrade should not contain the above error.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1 upgrade
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Workaround can be referred to https://github.com/helm/helm/issues/8987#issuecomment-786149813; however, ensure the rollback version is correct.

**Comment by bk201** [comment]
@w13915984028 I guess this is not completely addressed or perhaps a new regression.

**Comment by w13915984028** [comment]
@bk201 looks so, this issue still happens, I will look into fleet-agent's new code when free.

@guangbochen do you have a support-bundle file ?

**Comment by w13915984028** [comment]
reproduced in a single-node upgrade:

from the helm release history, the `harvester` chart is upgraded several times inbetween upgrade, the last 3 times are in almost same time, will continue check why this happens.

```
harv31:~ # kk get bundle -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]; daemonset.apps longhorn-system/longhorn-manager [progressing] Available: 0/1; deployment.apps longhorn-system/longhorn-admission-webhook [progressing] Deployment does not have minimum availability., Available: 1/2; deployment.apps longhorn-system/longhorn-driver-deployer [progressing] Deployment does not have minimum availability., Available: 0/1; deployment.apps longhorn-system/longhorn-ui [progressing] Deployment does not have minimum availability., Available: 0/1


harvester-system                         sh.helm.release.v1.harvester.v1                                     helm.sh/release.v1                            1      82m
harvester-system                         sh.helm.release.v1.harvester.v2                                     helm.sh/release.v1                            1      79m

harvester-system                         sh.helm.release.v1.harvester.v3                                     helm.sh/release.v1                            1      18m
harvester-system                         sh.helm.release.v1.harvester.v4                                     helm.sh/release.v1                            1      18m
harvester-system                         sh.helm.release.v1.harvester.v5                                     helm.sh/release.v1                            1      16m

harv31:~ # uptime
 22:04:11  up   0:08,  1 user,  load average: 1.18, 2.30, 1.39
 
```

**Comment by abonillabeeche** [comment]
I just ran into this issue.

**Comment by w13915984028** [comment]
Did more tests, there are 2 possibilites:

(1) when `fleet-agent` is busy upgrading those managedcharts, the POD is replaced by the upgrading procssing of Rancher, which causes the fleet-agent cannot update the status of release

(2) the `kube-apiserver` process is killed and recreated by RKE2 before system rebooting, which may cause fleet-agent update release status fail

continue...

**Comment by w13915984028** [comment]
add some debug in `upgrade_node.sh`, the root cause looks to be:

the `fleet-agent` is busing upgrading all bundles, even when `wait_rke2_upgrade` is met. the `upgrade_os` will cause the `fleet-agent` POD restart once, the ongoing upgrading does not finish ontime, and when `fleet-agent` runs again, it finds the previous upgrading is there and complains.

Solution: before `upgrade_os`, wait `fleet-agent` does all its job on bundle. 
will validate next day.


```
  # Upgarde RKE2
  upgrade_rke2
    wait_rke2_upgrade
  clean_rke2_archives
  convert_nodenetwork_to_vlanconfig
  ..........--------------------------> check all bundle,
    # Upgrade OS
  upgrade_os
```
....
```
+ echo 'check bundle 24'
+ kubectl get bundle -A
NODE_CURRENT_HARVESTER_VERSION is: v1.1.1
The UPGRADE_PREVIOUS_VERSION is v1.1.1, NODE_CURRENT_HARVESTER_VERSION is v1.1.1, will check nodenetwork upgrade node option
There is nothing to do in nodenetwork
check bundle 24
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps cattle-fleet-local-system/fleet-agent [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 0/1                       WaitApplied(1) [Cluster fleet-local/local]
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps cattle-system/system-upgrade-controller [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-logging                           0/1                       NotReady(1) [Cluster fleet-local/local]; daemonset.apps cattle-logging-system/rancher-logging-rke2-journald-aggregator [progressing] Available: 0/1; deployment.apps cattle-logging-system/rancher-logging [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-logging-crd                       1/1
fleet-local   mcc-rancher-monitoring                        0/1                       WaitApplied(1) [Cluster fleet-local/local]
fleet-local   mcc-rancher-monitoring-crd                    0/1                       WaitApplied(1) [Cluster fleet-local/local]
+ kubectl get pods -n cattle-fleet-local-system -o wide
NAME                           READY   STATUS    RESTARTS   AGE    IP            NODE     NOMINATED NODE   READINESS GATES
fleet-agent-6ffcdc7f94-45sfm   1/1     Running   0          6m4s   10.52.0.170   harv31   <none>           <none>

```
.....

```
+ echo 'check bundle 25'
+ kubectl get bundle -A
check bundle 25
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-logging                           0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps cattle-logging-system/rancher-logging [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-logging-crd                       1/1
fleet-local   mcc-rancher-monitoring                        0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
fleet-local   mcc-rancher-monitoring-crd                    0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
+ kubectl get pods -n cattle-fleet-local-system -o wide
NAME                           READY   STATUS    RESTARTS      AGE     IP            NODE     NOMINATED NODE   READINESS GATES
fleet-agent-6ffcdc7f94-45sfm   1/1     Running   1 (77s ago)   7m16s   10.52.0.170   harv31   <none>           <none>
```

![image](https://user-images.githubusercontent.com/31133476/224575137-e5e32765-c53b-4feb-853f-b32c213f01f4.png)

**Comment by bk201** [comment]
> (2) the kube-apiserver process is killed and recreated by RKE2 before system rebooting, which may cause fleet-agent update release status fail

My investigation also shows this might be the cause. The kube-api server restarting causes fleet-agent restart:
```
2023-03-09T15:50:08.015756181Z stderr F E0309 15:50:08.015634       1 leaderelection.go:330] error retrieving resource lock cattle-fleet-system/fleet-controller-lock: Get "https://10.53.0.1:443/api/v1/namespaces/cattle-fleet-system/configmaps/fleet-controller-lock": dial tcp 10.53.0.1:443: connect: connection refused
2023-03-09T15:50:10.015384725Z stderr F E0309 15:50:10.015323       1 leaderelection.go:330] error retrieving resource lock cattle-fleet-system/fleet-controller-lock: Get "https://10.53.0.1:443/api/v1/namespaces/cattle-fleet-system/configmaps/fleet-controller-lock": dial tcp 10.53.0.1:443: connect: connection refused
2023-03-09T15:50:12.015483831Z stderr F E0309 15:50:12.015408       1 leaderelection.go:330] error retrieving resource lock cattle-fleet-system/fleet-controller-lock: Get "https://10.53.0.1:443/api/v1/namespaces/cattle-fleet-system/configmaps/fleet-controller-lock": dial tcp 10.53.0.1:443: connect: connection refused
2023-03-09T15:50:14.015143534Z stderr F E0309 15:50:14.015050       1 leaderelection.go:330] error retrieving resource lock cattle-fleet-system/fleet-controller-lock: Get "https://10.53.0.1:443/api/v1/namespaces/cattle-fleet-system/configmaps/fleet-controller-lock": dial tcp 10.53.0.1:443: connect: connection refused
2023-03-09T15:50:15.999192207Z stderr F I0309 15:50:15.998968       1 leaderelection.go:283] failed to renew lease cattle-fleet-system/fleet-controller-lock: timed out waiting for the condition
2023-03-09T15:50:15.999200182Z stderr F E0309 15:50:15.999031       1 leaderelection.go:306] Failed to release lock: resource name may not be empty
2023-03-09T15:50:16.000134925Z stderr F time="2023-03-09T15:50:15Z" level=info msg="Shutting down fleet.cattle.io/v1alpha1, Kind=BundleNamespaceMapping workers"
2023-03-09T15:50:16.000150003Z stderr F time="2023-03-09T15:50:15Z" level=info msg="Shutting down fleet.cattle.io/v1alpha1, Kind=Content workers"
2023-03-09T15:50:16.000226467Z stderr F time="2023-03-09T15:50:15Z" level=info msg="Shutting down fleet.cattle.io/v1alpha1, Kind=ClusterRegistration workers"
2023-03-09T15:50:16.000250712Z stderr F time="2023-03-09T15:50:16Z" level=fatal msg="leaderelection lost for fleet-controller-lock"
```
Agent log: [0.log](https://github.com/harvester/harvester/files/10954645/0.log), if there is an on-going bundle application, the state might be stuck. One idea is to scale fleet-agent deployment to 0 replicas before upgrading RKE2 and bring it back once the RKE2 is upgraded...

**Comment by bk201** [comment]
Attempt to fix by scaling fleet agent replicas to 0 before upgrading RKE2 and scale it back to 1 later: https://github.com/harvester/harvester/pull/3641

**Comment by w13915984028** [comment]
A new test to wait for bundle:

before `upgrade_os`, `fleet-agent` took 120+s to settle all bundle down,  the `upgrade-os` will restart the POD, if we do not wait bundle to be ready, `fleet-agent` will hit he issue `when upgrading bundles but POD is rebooted`

I will commit another patch to solve this issue.

```
  wait_for_fleet_bundles

  # Upgrade OS
  upgrade_os
```

+ wait_for_fleet_bundles
..
Mon Mar 13 11:57:06 UTC 2023
...
```
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps cattle-fleet-local-system/fleet-agent [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       NotReady(1) [Cluster fleet-local/local]; daemonset.apps harvester-system/harvester-network-controller [progressing] Available: 0/1; daemonset.apps harvester-system/harvester-node-manager [progressing] Available: 0/1; daemonset.apps harvester-system/kube-vip [progressing] Available: 0/1; deployment.apps harvester-system/harvester-load-balancer [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps cattle-system/system-upgrade-controller [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-logging                           0/1                       NotReady(1) [Cluster fleet-local/local]; daemonset.apps cattle-logging-system/rancher-logging-rke2-journald-aggregator [progressing] Available: 0/1; deployment.apps cattle-logging-system/rancher-logging [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring                        0/1                       NotReady(1) [Cluster fleet-local/local]; apiservice.apiregistration.k8s.io v1beta1.custom.metrics.k8s.io [progressing] endpoints for service/rancher-monitoring-prometheus-adapter in "cattle-monitoring-system" have no addresses with port name "", Resource is current; daemonset.apps cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter [progressing] Available: 0/1; deployment.apps cattle-monitoring-system/rancher-monitoring-kube-state-metrics [progressing] Deployment does not have minimum availability., Available: 0/1; deployment.apps cattle-monitoring-system/rancher-monitoring-operator [progressing] Deployment does not have minimum availability., Available: 0/1
fleet-local   mcc-rancher-monitoring-crd                    1/1   
```
....

Mon Mar 13 11:59:20 UTC 2023
++ kubectl get bundle.fleet.cattle.io -A -o 'jsonpath={.items[*].status.conditions[?(@.type=="Ready")].status}'
+ bsr='True True True True True True True True True'

upgrade OS:
```
Flag --directory has been deprecated, 'directory' is deprecated please use 'system' instead
[36mINFO[0m[2023-03-13T11:59:25Z] Starting elemental version v0.1.1            
[33mWARN[0m[2023-03-13T11:59:25Z] failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory 
[36mINFO[0m[2023-03-13T11:59:26Z] Upgrade called   
...
+ GRUBENV_FILE=/oem/grubenv
+ chroot /host /bin/bash -c 'if ! [ -f /oem/grubenv ]; then grub2-editenv /oem/grubenv create; fi'
+ umount /host/usr/bin/elemental
...
+ kubectl get pods -n cattle-fleet-local-system -o wide
NAME                           READY   STATUS    RESTARTS        AGE     IP          NODE     NOMINATED NODE   READINESS GATES
fleet-agent-6ffcdc7f94-g9fkm   1/1     Running   1 (2m42s ago)   8m22s   10.52.0.8   harv31   <none>           <none>
sleep 60
```

**Comment by bk201** [comment]
Update rancher side issue: https://github.com/rancher/fleet/issues/637#issuecomment-1469446802
We're using a workaround here only.

**Comment by irishgordo** [comment]
@bk201 should the `Conditions` contain an error, as I'm not able to see one listed? in the describe on the managed charts of:
- harvester
- harvester-crd
In the fleet-local namespace:
```yaml
Spec:
  Chart:              harvester
  Default Namespace:  harvester-system
  Diff:
    Compare Patches:
      API Version:  apiextensions.k8s.io/v1
      Json Pointers:
        /status/acceptedNames
        /status/conditions
        /status/storedVersions
      Kind:         CustomResourceDefinition
      Name:         engineimages.longhorn.io
      API Version:  apiextensions.k8s.io/v1
      Json Pointers:
        /status/acceptedNames
        /status/conditions
        /status/storedVersions
      Kind:         CustomResourceDefinition
      Name:         nodes.longhorn.io
      API Version:  apiextensions.k8s.io/v1
      Json Pointers:
        /status/acceptedNames
        /status/conditions
        /status/storedVersions
      Kind:      CustomResourceDefinition
      Name:      volumes.longhorn.io
  Paused:        false
  Release Name:  harvester
  Repo Name:     harvester-charts
  Targets:
    Cluster Name:  local
    Cluster Selector:
      Match Expressions:
        Key:       provisioning.cattle.io/unmanaged-system-agent
        Operator:  DoesNotExist
  Values:
    Containers:
      Apiserver:
        Hci Mode:  true
        Image:
          Image Pull Policy:  IfNotPresent
    Harvester - Load - Balancer:
      Enabled:  true
    Harvester - Network - Controller:
      Enabled:  true
      Image:
        Pull Policy:  IfNotPresent
      Vip Enabled:    true
    Harvester - Node - Disk - Manager:
      Enabled:  true
      Image:
        Pull Policy:  IfNotPresent
      Label Filter:
        COS_*
        HARV_*
    Kube - Vip:
      Enabled:  true
    Kube - Vip - Cloud - Provider:
      Enabled:  true
    Kubevirt:
      Spec:
        Monitor Account:    rancher-monitoring-operator
        Monitor Namespace:  cattle-monitoring-system
    Longhorn:
      Default Settings:
        Default Data Path:  /var/lib/harvester/defaultdisk
        Taint Toleration:   kubevirt.io/drain:NoSchedule
      Enabled:              true
    Multus:
      Enabled:         false
    Rancher Embedded:  true
    Service:
      Vip:
        Enabled:     true
        Hw Address:  5a:d7:d0:48:7b:39
        Ip:          192.168.122.218
        Mode:        dhcp
    Webhook:
      Image:
        Image Pull Policy:  IfNotPresent
  Version:                  0.0.0-v1-1-e257df76
Status:
  Conditions:
    Last Update Time:  2023-03-22T19:51:31Z
    Status:            True
    Type:              Ready
    Last Update Time:  2023-03-22T19:51:31Z
    Status:            True
    Type:              Processed
    Last Update Time:  2023-03-22T19:55:45Z
    Status:            True
    Type:              Defined
```
and
```yaml
Spec:
  Chart:              harvester-crd
  Default Namespace:  harvester-system
  Paused:             false
  Release Name:       harvester-crd
  Repo Name:          harvester-charts
  Take Ownership:     true
  Targets:
    Cluster Name:  local
    Cluster Selector:
      Match Expressions:
        Key:       provisioning.cattle.io/unmanaged-system-agent
        Operator:  DoesNotExist
  Values:
  Version:  0.0.0-v1-1-e257df76
Status:
  Conditions:
    Last Update Time:  2023-03-22T19:50:08Z
    Status:            True
    Type:              Ready
    Last Update Time:  2023-03-22T19:50:08Z
    Status:            True
    Type:              Processed
    Last Update Time:  2023-03-22T19:55:45Z
    Status:            True
    Type:              Defined
```
With upgrading a single-node v1.1 -> Harvester Version: v1.1-e257df76-head.
Rancher is still v2.6.11 as expected off of v1.1-head.
![Screenshot from 2023-03-22 13-04-38](https://user-images.githubusercontent.com/5370752/227025143-7e86c409-11b1-47d0-80e3-055fa6c20786.png)
![Screenshot from 2023-03-22 12-54-27](https://user-images.githubusercontent.com/5370752/227025148-e9891c03-0529-4280-a108-3eb488aef459.png)

**Comment by bk201** [comment]
> With upgrading a single-node v1.1 -> Harvester Version: v1.1-e257df76-head.
Rancher is still v2.6.11 as expected off of v1.1-head.

@irishgordo that's expected. Rancher has its own version and we upgrade from v2.6.9 to v2.6.11.

**Comment by irishgordo** [comment]
@bk201 if I wasn't encountering the issue - should I retest with rc4?

**Comment by bk201** [comment]
@irishgordo Yes. please help test with rc4. This should be quite easy to reproduce with rc3 (single node)...

**Comment by irishgordo** [comment]
@bk201  - on a v1.1.0 3 Node cluster airgapped, I'm noticing that after applying the fix for slow disks of:
```
harvester-node-0:~ # cat > /tmp/fix.yaml <<EOF
> spec:
>   values:
>     systemUpgradeJobActiveDeadlineSeconds: "3600"
> EOF
```
And:
```
harvester-node-0:~ # kubectl patch managedcharts.management.cattle.io local-managed-system-upgrade-controller --namespace fleet-local --patch-file=/tmp/fix.yaml --type merge
```
And:
```
harvester-node-0:~ # kubectl -n cattle-system rollout restart deploy/system-upgrade-controller
```
That this:
```
harvester-node-0:~ # kubectl get managedcharts -A
NAMESPACE     NAME                                      AGE
fleet-local   harvester                                 2d23h
fleet-local   harvester-crd                             2d23h
fleet-local   local-managed-system-upgrade-controller   2d23h
fleet-local   rancher-logging                           2d23h
fleet-local   rancher-logging-crd                       2d23h
fleet-local   rancher-monitoring                        2d23h
fleet-local   rancher-monitoring-crd                    2d23h
harvester-node-0:~ # kubectl get bundle -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 1/1                       
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   1/1                       
fleet-local   mcc-rancher-logging                           1/1                       
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring                        1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1  
```
Is Present.

Describing the bundle:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
  namespace: cattle-fleet-local-system
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

    Name:  agent.yaml
  Targets:
    Cluster Name:  local
    Cluster Selector:
      Match Expressions:
        Key:       fleet.cattle.io/non-managed-agent
        Operator:  DoesNotExist
Status:
  Conditions:
    Last Update Time:  2023-03-24T21:10:18Z
    Message:           ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
    Status:            False
    Type:              Ready
    Last Update Time:  2023-03-24T21:10:19Z
    Status:            True
    Type:              Processed
  #####################################################################
  #####################################################################
  Summary:
    Desired Ready:  1
    Err Applied:    1
    Non Ready Resources:
      Bundle State:        ErrApplied
      Message:             another operation (install/upgrade/rollback) is in progress
      Name:                fleet-local/local
    Ready:                 0
  Unavailable:             1
  Unavailable Partitions:  0
  ```
  
  Should the adjustments for slow-disk be reverted and then re-applied?
