### ISSUE TITLE
[ENHANCEMENT] Be Able To View Cloud Init Failures/Errs For VMs Without Needing to SSH into VM

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3669]
**Is your enhancement related to a problem? Please describe.**
An ability to view cloud-init failures/errors for VMs that get provisioned with something like terraform without needing to log in to the vm to view the cloud init output log.  Just providing a single-pane-of-glass approach to view Harvester VMs provisioning with the cloud-init - currently the only way to see the cloud init output in detail is through jumping on the vm directly and depending how the VM's cloud-init was configured.  There is no place to visibly see errors / debug logs / reporting items through Harvester on the VMs that get spun up and are running.

Given:
```yaml
    output:
      init:
          output: "> /var/log/cloud-init.out"
          error: "> /var/log/cloud-init.err"
      config: "tee -a /var/log/cloud-config.log"
      final:
          - ">> /var/log/cloud-final.out"
          - "/var/log/cloud-final.err"
```
There could also be other variants in the YAML structure for logging:
https://cloudinit.readthedocs.io/en/23.1.1/development/logging.html#command-output

Maybe if a value is present, for any configuration of `output` then some additional logic happens at a controller level to dig deeper to determine whether or not to provide the end user that information.

**Describe the solution you'd like**
Perhaps just on the VM index page a "Warning" icon with a message of (when hovered over):
"Warning: cloud-init had error"
Then clicking into the VM from the index page we could dive deeper and see exactly what/where the error came from.

**Describe alternatives you've considered**
Leveraging Event Reporting:
https://cloudinit.readthedocs.io/en/23.1.1/development/logging.html#event-reporting

Perhaps Harvester could have a centralized place, that instead of scraping the cloud-config/cloud-init logs from the VM, if the VM specified something like:
```yaml
reporting:
  <user-defined name>:
    type: webhook
    endpoint: <url>
    timeout: <timeout in seconds>
    retries: <number of retries>
    consumer_key: <OAuth consumer key>
    token_key: <OAuth token key>
    token_secret: <OAuth token secret>
    consumer_secret: <OAuth consumer secret>
```
With some Harvester provided credentials that get generated much like how API Keys get generated.
Then maybe it's just reporting that happens to a centralized location that can be viewed without ssh'ing into the VM.

Maybe something can be gathered back from KubeVirt after VM is up:
https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_cloudinit_test.go#L578-L661

**Additional context**
Example:
```log
ubuntu@docker-rancher-27-head:~$ cat /var/log/cloud-final.err 
Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'modules:final' at Thu, 16 Mar 2023 21:24:04 +0000. Up 21.73 seconds.
/var/lib/cloud/instance/scripts/runcmd: 2: systemctl - enable - --now - qemu-guest-agent.service: not found
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Synchronizing state of qemu-guest-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable qemu-guest-agent
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
sysctl: setting key "net.ipv4.conf.all.accept_source_route": Invalid argument
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
Unable to find image 'rancher/rancher:v2.7.2' locally
docker: Error response from daemon: manifest for rancher/rancher:v2.7.2 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
2023-03-16 21:24:37,647 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-03-16 21:24:37,647 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2-0ubuntu0~22.04.1 finished at Thu, 16 Mar 2023 21:24:37 +0000. Datasource DataSourceNoCloud [seed=/dev/vdb][dsmode=net].  Up 82.03 seconds
```
In that example, the issue was that `rancher:v2.7.2` was unknown, the only available one at the time of this creation of enhancement request is `v2.7.2-rc6`.
