### ISSUE TITLE
[FEATURE] Allow the user to install additional packages during installation through Harvester configuration

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3689]
**Is your feature request related to a problem? Please describe.**

Currently, we can only do this by enable the `debugrw mode`: https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only

It is better to support it through Harvester configuration

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Maybe the [after-install-chroot](https://rancher.github.io/elemental-toolkit/docs/customizing/stages/#after-install-chroot) can help

**Comment by bk201** [comment]
Add required doc, we need to update the doc for the new configuration too.

**Comment by futuretea** [comment]
**Test Plan**
1. Install Harvester with any nodes with configure option:
```yaml
os:
  afterInstallChrootCommands:
    - "rm -f /etc/resolv.conf && echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf"
    - "mkdir -p /usr/local/bin"
    - "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh"
    - "rm -f /etc/resolv.conf && ln -s /var/run/netconfig/resolv.conf /etc/resolv.conf"
 ```
2. Harvester should installed successfully
3. Login to console, command `helm` should exist
4. Reboot the node, command `helm` should still exist
