### ISSUE TITLE
[BUG] Clear network resources when the node is removed

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3697]
**Describe the bug**

- The link status of the removed node should be deleted in all link monitor.
- The node should be removed from the vlanconfig annotation `network.harvesterhci.io/matched-nodes`.
- The related vlanstatus should be deleted. 

**To Reproduce**
1. Set up a cluster no less than 2 nodes.
2. Delete a computing node.

**Expected behavior**

- The link status of the removed node should be deleted in all link monitor.
- The node should be removed from the vlanconfig annotation `network.harvesterhci.io/matched-nodes`.
- The related vlanstatus should be deleted. 

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.2-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**
Test plan:
1. Set up a cluster of no less than 2 nodes.
2. Create a new cluster network and the related network config to select one compute node. 
3. Delete the compute node. 
   - Check link status again and the link statuses of the remove node are deleted. 
       - `kubectl get lm -o yaml`
   - Check vlanconfigs which selects the node before. It should be removed from annotation `network.harvesterhci.io/matched-nodes`
       - `kubectl get vc <vc> -o yaml`
   - Check related vlanstatus. There should be no vlanstatus related to the removed node.
       - `kubectl get vs -l network.harvesterhci.io/node=<node>`
       
 ** Work around**
Delete the related resources manually.

**Comment by yaocw2020** [comment]
Please use the Harvester v1.1.2-rc4 environment to verify the issue.

**Comment by TachunLin** [comment]
Verifying on **fixed** `v1.1.2-rc4` (03/24). Close this issue
 
### Result
When we create a network config and specify the compute node `harvester-wtvt4` 
Then we delete this node on the Host page.
  ![image](https://user-images.githubusercontent.com/29251855/227932830-c143230c-d78b-4603-bdcf-9a9a352be5ad.png)

1. After deleted node, the link status of the deleted node `harvester-wtvt4` have been removed.

```
status:
    linkStatus:
      harvester-2zwd2:
      - index: 2
        mac: 8c:dc:d4:0e:ed:00
        masterIndex: 5
        name: ens1f0
        state: up
        type: device
      - index: 3
        mac: 8c:dc:d4:0e:ed:04
        name: ens1f1
        state: up
        type: device
      harvester-4r5rw:
      - index: 2
        mac: 8c:dc:d4:02:36:d8
        masterIndex: 5
        name: ens1f0
        state: up
        type: device
      - index: 3
        mac: 8c:dc:d4:02:36:dc
        name: ens1f1
        state: up
        type: device
      harvester-57hc6:
      - index: 2
        mac: 8c:dc:d4:0f:1b:10
        masterIndex: 5
        name: ens1f0
        state: up
        type: device
      - index: 3
        mac: 8c:dc:d4:0f:1b:14
        name: ens1f1
        state: up
        type: device

```
2. Check vlanconfigs . The deleted node should be removed from annotation `network.harvesterhci.io/matched-nodes`
```
harvester-57hc6:~ # kubectl get vc nc -o yaml
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  annotations:
    network.harvesterhci.io/matched-nodes: '[]'
  creationTimestamp: "2023-03-27T11:00:00Z"

```

3. Check related vlanstatus. There should be no vlanstatus related to the removed node.
```
harvester-57hc6:~ #  kubectl get vs -l network.harvesterhci.io/node=harvester-wtvt4
No resources found
```


### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: `v1.1.2-rc4` (03/24)

### Verify Steps
1. Provision a 4 nodes Harvester cluster
2. Create a new cluster network and the related network config to select one compute node. 
3. Delete the compute node. 
4. Check link status again and the link statuses of the remove node are deleted. 
       - `kubectl get lm -o yaml`
5. Check vlanconfigs which selects the node before. It should be removed from annotation `network.harvesterhci.io/matched-nodes`
       - `kubectl get vc <vc> -o yaml`
6. Check related vlanstatus. There should be no vlanstatus related to the removed node.
       - `kubectl get vs -l network.harvesterhci.io/node=<node>`
