### ISSUE TITLE
[ENHANCEMENT] Adapt toleration change in SBK

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3702]
**Is your enhancement related to a problem? Please describe.**

SBK adds a flag to specify tolerations for agent pods and remove the default value.

https://github.com/rancher/support-bundle-kit/pull/68

**Describe the solution you'd like**

We need to specify the toleration in the backend code. The agent pods need to run on draining/maintenance nodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
Currently when a harvester node is placed in maintenance mode, the node is marked unschedulable and tainted with the `NoSchedule` effect as shown below:

```
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2023-05-30T02:13:14Z"
  unschedulable: true
```

This does not impact the running of the sbk agent daemonset as the daemonset controller automatically adds these taint tolerations to the pods:

https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations
