### ISSUE TITLE
[FEATURE] Implement CSI Snapshotting in the Harvester CSI Driver

### ISSUE THREAD

**Issue by sarahhenkens** [harvester/harvester#3778]
**Describe the solution you'd like**

Add support for [Volume Snapshots](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) in the `harvester-csi-driver`.

It would allow users to leverage the GA snapshotting feature of the kubernetes API to create snapshots for volumes provisioned via a CSI provider:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
spec:
  source:
    volumeSnapshotContentName: test-content
```

When implemented, users can also use tools like Velero to automate full cluster backups. (Velero's CSI snapshot support: https://velero.io/blog/csi-integration/)

**Describe alternatives you've considered**

**Additional context**

The `harvester-csi-driver` claims to have the snapshotting capability in its registration [code](https://github.com/harvester/harvester-csi-driver/blob/v1.0/pkg/csi/controller_server.go#L271-L281):

```go
caps: getControllerServiceCapabilities(
	[]csi.ControllerServiceCapability_RPC_Type{
		csi.ControllerServiceCapability_RPC_CREATE_DELETE_VOLUME,
		csi.ControllerServiceCapability_RPC_PUBLISH_UNPUBLISH_VOLUME,
		csi.ControllerServiceCapability_RPC_EXPAND_VOLUME,
		csi.ControllerServiceCapability_RPC_CREATE_DELETE_SNAPSHOT,
	}),
``` 

But the methods do not have any implementation:
https://github.com/harvester/harvester-csi-driver/blob/v1.0/pkg/csi/controller_server.go#L271-L281
```go
func (cs *ControllerServer) CreateSnapshot(ctx context.Context, req *csi.CreateSnapshotRequest) (*csi.CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "")
}

func (cs *ControllerServer) DeleteSnapshot(ctx context.Context, req *csi.DeleteSnapshotRequest) (*csi.DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "")
}

func (cs *ControllerServer) ListSnapshots(context.Context, *csi.ListSnapshotsRequest) (*csi.ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "")
}
```

**Comment by FrankYang0529** [comment]
This issue is similar to https://github.com/harvester/harvester/issues/2661.

**Comment by mattmattox** [comment]
This feature would be very helpful for tools like velero to allow backing up PVCs for nested clusters running on top of Harvester.

**Comment by irony** [comment]
Could someone please provide a good manual step-by-step guide on how to do this manually in the meantime until this is a feature within Harvester/Rancher?

**Comment by Daemonslayer2048** [comment]
Adding a note from @CamrynCarter for tracking purposes: SURE-10209

**Comment by Daemonslayer2048** [comment]
This issue looks to have been pushed off from as far back as v1.3.0, but this really is a fairly big deal. The inability for a guest cluster to backup its own data in a reliable manner is a very huge deal. Given what I know about the underpinnings of the Harvester CSI and Longhorn I see how this could be a challenging request but its pretty big deal to resolve.

**Comment by DillonN** [comment]
FYI in the related ticket for backup/restore, I put some notes on a manual workaround I've been using via static provisioning. Should work for snapshots too. https://github.com/harvester/harvester/issues/2661#issuecomment-2542818974

I wouldn't recommend this for production use, since I don't think static provisioning is officially supported in Harvester (yet) and it is a bit finnicky to setup. But once I got it integrated into IaC deployments, it's been a pretty rock-solid solution for the last ~6mo. So some of the details there may help others with manual workarounds until official support is available.

**Comment by innobead** [comment]
Several duplicated issues. Let's track volume backup & restore for guest cluster at #2661 . 

cc @Vicente-Cheng @WebberHuang1118

**Comment by WebberHuang1118** [comment]
Hi @innobead 

This ticket is for guest cluster volume snapshots, while #2661 focuses on remote backup and restore of guest cluster volumes. So, as I understand it, these are addressing different concerns?. cc @Vicente-Cheng

**Comment by innobead** [comment]
> Hi [@innobead](https://github.com/innobead)
> 
> This ticket is for guest cluster volume snapshots, while [#2661](https://github.com/harvester/harvester/issues/2661) focuses on remote backup and restore of guest cluster volumes. So, as I understand it, these are addressing different concerns?. cc [@Vicente-Cheng](https://github.com/Vicente-Cheng)

Thanks @WebberHuang1118 for clarifying. 

- This issue focuses on the CSI snapshot capacity supported by third-party storage solutions in general.  
- #2661 pertains to Longhorn backup and restore, still via the CSI protocol.

cc @harvester/storage

**Comment by Daemonslayer2048** [comment]
Hey @innobead I just want to make a quick clarification, this issue has nothing to do with a third-party storage solution. This pertains to the Harvester CSIs ability to create a snapshot in general. I think your original assessment of this issue being a duplicate of 2661 is accurate.

**Comment by innobead** [comment]
> Hey [@innobead](https://github.com/innobead) I just want to make a quick clarification, this issue has nothing to do with a third-party storage solution. This pertains to the Harvester CSIs ability to create a snapshot in general. I think your original assessment of this issue being a duplicate of 2661 is accurate.

Thanks for the feedback. You're right that from a general CSI interface perspective, this is how it should work. However, the Harvester CSI driver is specifically designed to provision volumes for guest cluster workloads by passing them through to the underlying storage on the Harvester cluster. This means we still need to ensure that snapshot/revert functions are a storage-neutral solution, not just for the built-in Longhorn storage.

**Comment by WebberHuang1118** [comment]
**Testing Plan for QA verification:**

  - Create a guest cluster with Rancher `2.12`
  - Add the repo `https://github.com/WebberHuang1118/rancher-charts.git` with the branch `v2.12-bump-harvester-csi-driver-0.1.25` to the guest cluster’s app repositories.
  - Upgrade Harvester CSI driver to `107.0.3+up0.1.25`.

**Case 1: CSI snapshot based on host’s Longhorn volume**

* Create a block PVC.
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: blk-vol
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    volumeMode: Block
  ```
* Mount the block PVC to a pod, write some data, ensure the data is persisted, then remove the pod.
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: pod-blk-vol
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true  
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/blk-vol
        name: blk-vol
    volumes:
      - name: blk-vol
        persistentVolumeClaim:
          claimName: blk-vol
   ```
* Take a snapshot of the block PVC.
  ```
  apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    name: snapshot-blk-vol
    namespace: default
  spec:
    volumeSnapshotClassName: harvester-snapshot
    source:
      persistentVolumeClaimName: blk-vol
  ```
* Restore the snapshot to a new PVC.
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: restore-blk-vol
    namespace: default
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: harvester
    dataSource:
      apiGroup: snapshot.storage.k8s.io  
      kind: VolumeSnapshot
      name: snapshot-blk-vol
    volumeMode: Block
  ```
* Mount both the source and restored PVCs to a pod.
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: pod-restore-blk-vol
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true  
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/blk-vol
        name: blk-vol
      - devicePath: /dev/restore-blk-vol
        name: restore-blk-vol
    volumes:
      - name: blk-vol
        persistentVolumeClaim:
          claimName: blk-vol
      - name: restore-blk-vol
        persistentVolumeClaim:
          claimName: restore-blk-vol
  ```
* Compare the content between the two PVCs within the pod.
* The two PVCs should have identical content.

**Case 2: CSI snapshot based on host’s NFS filesystem volume**

* Deploy the NFS CSI driver on Harvester.
* In the guest cluster, create a custom StorageClass as described [here](https://docs.harvesterhci.io/v1.7/rancher/csi-driver#passthrough-custom-storageclass) that points to the host’s NFS StorageClass, and set the custom StorageClass as default.
* Create a filesystem PVC.
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-vol
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 2Gi
  ```
* Mount the filesystem PVC to a pod, write some data, ensure the data is persisted, then remove the pod.
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: pod-fs-vol
  spec:
    containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
          - name: fs-vol
            mountPath: /data-fs-vol
    volumes:
      - name: fs-vol
        persistentVolumeClaim:
          claimName: fs-vol
  ```
* Take a snapshot of the filesystem PVC.
  ```
  apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    name: snapshot-fs-vol
    namespace: default
  spec:
    volumeSnapshotClassName: harvester-snapshot
    source:
      persistentVolumeClaimName: fs-vol
  ```
* Restore the snapshot to a new PVC.
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: restore-fs-vol
    namespace: default
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: harvester
    dataSource:
      apiGroup: snapshot.storage.k8s.io  
      kind: VolumeSnapshot
      name: snapshot-fs-vol
    volumeMode: Filesystem
  ```
* Mount both the source and restored PVCs to a pod.
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: pod-fs-vol
  spec:
    containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
          - name: fs-vol
            mountPath: /data-fs-vol
          - name: restore-fs-vol
            mountPath: /data-restore-fs-vol
    volumes:
      - name: fs-vol
        persistentVolumeClaim:
          claimName: fs-vol
      - name: restore-fs-vol
        persistentVolumeClaim:
          claimName: restore-fs-vol
  ```
* Compare the content between the two PVCs within the pod.
* The two PVCs should have identical content.
