### ISSUE TITLE
[BUG] Prometheus has warning message of `Evaluating rule failed` against KubeVirtComponentExceedsRequestedMemory

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3792]
**Describe the bug**

In prometheus log, there is error of `Evaluating rule failed` against `KubeVirtComponentExceedsRequestedMemory`

**To Reproduce**

1. fetch log of POD `prometheus-rancher-monitoring-prometheus-0`

`kubectl  -n cattle-monitoring-system logs prometheus-rancher-monitoring-prometheus-0`

2. there are lots of such warning message

> level=warn ts=2023-04-19T08:56:37.628Z caller=manager.go:603 component="rule manager" group=kubevirt.rules msg="Evaluating rule failed" rule="alert: KubeVirtComponentExceedsRequestedMemory\nexpr: ((kube_pod_container_resource_requests{container=~\"virt-controller|virt-api|virt-handler|virt-operator\",namespace=\"harvester-system\",resource=\"memory\"})\n  - on(pod) group_left(node) container_memory_working_set_bytes{container=\"\",namespace=\"harvester-system\"})\n  < 0\nfor: 5m\nlabels:\n  kubernetes_operator_component: kubevirt\n  kubernetes_operator_part_of: kubevirt\n  severity: warning\nannotations:\n  description: Container {{ $labels.container }} in pod {{ $labels.pod }} memory usage\n    exceeds the memory requested\n  runbook_url: https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedMemory\n  summary: The container is using more memory than what is defined in the containers\n    resource requests\n" err="found duplicate series for the match group {pod=\"kube-vip-cloud-provider-0\"} on the right hand-side of the operation: [{__name__=\"container_memory_working_set_bytes\", endpoint=\"https-metrics\", id=\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3483397c_e5e4_4f1b_ae47_e8c70f65341c.slice/cri-containerd-cdaf78aac3bd426acc98a4704eb550da59ab7ac6c7a38e3b0d19149bc2df50f4.scope\", image=\"docker.io/rancher/pause:3.6\", instance=\"192.168.122.131:10250\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", name=\"cdaf78aac3bd426acc98a4704eb550da59ab7ac6c7a38e3b0d19149bc2df50f4\", namespace=\"harvester-system\", node=\"harv31\", pod=\"kube-vip-cloud-provider-0\", service=\"rancher-monitoring-kubelet\"}, {__name__=\"container_memory_working_set_bytes\", endpoint=\"https-metrics\", id=\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3483397c_e5e4_4f1b_ae47_e8c70f65341c.slice\", instance=\"192.168.122.131:10250\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"harvester-system\", node=\"harv31\", pod=\"kube-vip-cloud-provider-0\", service=\"rancher-monitoring-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"

**Expected behavior**

Fix such error.

**Support bundle**

**Environment**
 - Harvester ISO version:  V1.1.1/v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM

**Additional context**

**Comment by w13915984028** [comment]
looks similar with https://github.com/harvester/harvester/issues/3472

**Comment by w13915984028** [comment]
The related issue posted in kubeivrt: https://github.com/kubevirt/kubevirt/issues/8439

The upstrea fix: https://github.com/kubevirt/kubevirt/pull/8306
![image](https://user-images.githubusercontent.com/31133476/235846597-42754cb1-5ffa-40e7-b51d-6ae7f727bfcc.png)

But even with the upstream fix, there are still errors from prometheus `many-to-many matching not allowed: matching labels must be unique on one side`

**Comment by w13915984028** [comment]
Run those rules in prometheus directly in a single-node k8s cluster (havester):

**Left hand:**
`kube_pod_container_resource_requests{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system",resource="memory"}`

**Only 5 return results.**

![image](https://user-images.githubusercontent.com/31133476/235852070-ff3c804d-930c-4c4b-8c2a-5ee810a009eb.png)

**Right hand:**
`container_memory_working_set_bytes{container="",namespace="harvester-system"}`

**There are much more (30) return results** 
`Load time: 34ms   Resolution: 14s   Result series: 30`

![image](https://user-images.githubusercontent.com/31133476/235852353-f2452486-83db-4095-b77c-640101e0254c.png)

**Comment by w13915984028** [comment]
With
> ```((kube_pod_container_resource_requests{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system",resource="memory"}) - on(pod) group_left(node) container_memory_working_set_bytes{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system"})```

Prometheus exeutes:
![image](https://user-images.githubusercontent.com/31133476/235869983-96ee149c-f4f7-4217-9e5c-16194b03b27c.png)


With

>  ```((kube_pod_container_resource_requests{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system",resource="memory"}) - on(pod) group_left(node) container_memory_working_set_bytes{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system"}) < 0 ```

Prometheus exeutes:

![image](https://user-images.githubusercontent.com/31133476/235869903-6350dd1b-97cd-4725-adaf-b61a8696a84c.png)

**Comment by w13915984028** [comment]
With a customized `prometheus rule`,  it works correctly (no `many-to-many matching not allowed: matching labels must be unique on one side` any more), and there are 3 alerts, indicating that `virt-api` and `virt-controller` are exceeding the required memory.


```
cat > extendedrule.yaml << 'EOF'
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus.kubevirt.io: "true"
  name: prometheus-kubevirt-rules-customized
  namespace: harvester-system
spec:
  groups:
  - name: kubevirtextended.rules
    rules:
    - alert: KubeVirtComponentExceedsRequestedMemoryCustomized
      annotations:
        description: Container {{ $labels.container }} in pod {{ $labels.pod }} memory
          usage exceeds the memory requested
        runbook_url: https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedMemoryCustomized
        summary: The container is using more memory than what is defined in the containers
          resource requests
      expr: ((kube_pod_container_resource_requests{namespace="harvester-system",container=~"virt-controller|virt-api|virt-handler|virt-operator",resource="memory"})
        - on(pod) group_left(node) container_memory_working_set_bytes{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system"})
        < 0
      for: 5m
      labels:
        kubernetes_operator_component: kubevirt
        kubernetes_operator_part_of: kubevirt
        severity: warning
EOF
```


![image](https://user-images.githubusercontent.com/31133476/235877121-d5158a5c-55c1-4c48-a870-60c942ebf98e.png)
