### ISSUE TITLE
[BUG] Harvester Node Driver `sh /usr/local/custom_script/install.sh ` should be injected at the end of runcmd list

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3855]
**Describe the bug**

When deploying rke2 via harvester node driver we can see this resulting runcmd: 
```yaml
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - sh /usr/local/custom_script/install.sh 
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
```
in the runcmd section, the injected part `sh /usr/local/custom_script/install.sh ` was injected at beginning.

**To Reproduce**
1. Use Harvester node driver to provision a RKE2 cluster
2. Check the created VM's cloud config

**Expected behavior**

in the runcmd section, the injected part `sh /usr/local/custom_script/install.sh ` should be injected at end
```yaml
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
  - sh /usr/local/custom_script/install.sh 
```
**Support bundle**

**Environment**
 - Harvester ISO version: master
 - Rancher version: v2.7.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on node driver `v0.6.5` with Harvester `v1.2.0-rc1`. Close this issue.

### Result
Checked on Rancher v2.7.3, update the node driver to `v0.6.5` and provision RKE2 cluster of the following kubernetes versions:
1. RKE2+v1.25.9
2. RKE2+V1.24.7
3. RKE2+v1.23.14

After RKE2 guest cluster ready, check the created VM on Harvester edit config page
* We can find the `- sh /usr/local/custom_script/install.sh` located at the correct place under the runcmd field
![image](https://github.com/harvester/harvester/assets/29251855/44eeda18-2e45-49b7-8f7b-aa67ee4a674c)

  ```
  #cloud-config
  hostname: rke2-v1259-pool1-da0c81b8-pxdkc
  package_update: true
  packages:
  - qemu-guest-agent
  runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - sh /usr/local/custom_script/install.sh
  ssh_authorized_keys:
  ...
  ``` 

### Test Information
* Test Environment: single nodes Harvester bare machines
* Harvester version: v1.2.0-rc1
* Rancher version: v2.7.3

### Verify Steps
Ref: https://github.com/harvester/docker-machine-driver-harvester/pull/46#issue-1696956755

1. Go to the Rancher UI and click Cluster Management > Drivers > Node Drivers. In the Node Drivers list, find  Harvester and then click ⋮ > View in API.
2. Click Edit.
3. Uncheck the builtin checkbox.
4. Change the *url to https://releases.rancher.com/harvester-node-driver/v0.6.5/docker-machine-driver-harvester-amd64.tar.gz.
5. Change the checksum to 8de48b07dd2e8b7ee60ec99b8456925e9c16a7523affb61a5f1788868bb1f8f6.
6. Click Show Request > Send Request.
7. Click Reload util the value of status.appliedChecksum and status.appliedURL change to the value we set.
  ![image](https://github.com/harvester/harvester/assets/29251855/8a386ea0-e59a-44e0-b320-d547af60b4d4)
8. Ensure the Harvester node driver version is `v0.6.5`
  ![image](https://github.com/harvester/harvester/assets/29251855/86a5d029-6137-4eb5-95a0-1f90ed022e94)
9. Use Harvester node driver to provision a RKE2 cluster with different kubernetes version
10. Ensure the RKE2 provisioned in Active state
11. Open Harvester virtual machine page
12. Check the created VM's cloud config user data
