### ISSUE TITLE
[Question] How to set up the VM IP via harveste

### ISSUE THREAD

**Issue by Borisyang3321** [harvester/harvester#3923]
I can assign NICs with VLAN to a VM through the Harvester UI, but I can only configure the VM IP within the operating system (OS) whether it's Windows or Linux . I would like to inquire if there is a method to set the VM IP without accessing the OS?

**Comment by w13915984028** [comment]
@Borisyang3321 If you are using DHCP mode, you do not need touch the OS. 

If static mode, it will via https://docs.harvesterhci.io/v1.1/vm/access-to-the-vm/#dynamic-ssh-key-injection-via-qemu-guest-agent.

@futuretea Do you have an example of setting IP with qemu agent, thanks.

**Comment by futuretea** [comment]
@Borisyang3321 you can set IP via cloud-init's networkdata
https://docs.harvesterhci.io/v1.1/vm/create-vm#cloud-configuration
https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#subnet-static-example

**Comment by Borisyang3321** [comment]
Thanks for your information!
Is it possible to achieve this through RestAPI or API resource during the provision VM?

**Comment by futuretea** [comment]
@Borisyang3321 Yes, you can set it through the VM api
- Kubevirt VM cloudinit api reference: http://kubevirt.io/api-reference/v0.54.0/definitions.html#_v1_cloudinitnocloudsource
- Harvester REST api reference: https://github.com/harvester/harvester/blob/master/api/openapi-spec/swagger.json
- terraform-provider-harvester vm api reference: https://registry.terraform.io/providers/harvester/harvester/latest/docs/resources/virtualmachine#example-usage

**Comment by Borisyang3321** [comment]
I check Harvester Rest API before,  but I'm not sure which field can be used to input the VM IP, do you have an example?

I will study cloudinit api and terraform-provider-harvester vm api.
Thank you for your assistance!

**Comment by Borisyang3321** [comment]
> @Borisyang3321 you can set IP via cloud-init's networkdata https://docs.harvesterhci.io/v1.1/vm/create-vm#cloud-configuration https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#subnet-static-example

@futuretea  I tried using cloud-init through Harvester UI to create an Ubuntu VM, but it didn't work. Is there a way for me to troubleshoot this issue?
 Also, can I use cloud-init to create a Windows VM as well?

The template I used is as follows.
```

network:
  version: 1
  config:
    - type: physical
      name: enp1s0
      mac_address: '00:11:22:33:44:55'
      subnets:
        - type: static
          address: 192.168.23.14/27
          gateway: 192.168.23.1

```

**Comment by fangfenghuang** [comment]
> > @Borisyang3321 you can set IP via cloud-init's networkdata https://docs.harvesterhci.io/v1.1/vm/create-vm#cloud-configuration https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#subnet-static-example
> 
> @futuretea I tried using cloud-init through Harvester UI to create an Ubuntu VM, but it didn't work. Is there a way for me to troubleshoot this issue? Also, can I use cloud-init to create a Windows VM as well?
> 
> The template I used is as follows.
> 
> ```
> 
> network:
>   version: 1
>   config:
>     - type: physical
>       name: enp1s0
>       mac_address: '00:11:22:33:44:55'
>       subnets:
>         - type: static
>           address: 192.168.23.14/27
>           gateway: 192.168.23.1
> ```

you should use version 2, here is my example:
```
version: 2
ethernets:
  eth0:
    dhcp4: no
    addresses: [{{cidrIP}}]
    gateway4: {{gateway}}
    nameservers:
      addresses: [{{dnsServer}}]
    match:
      name: e*
```
