### ISSUE TITLE
kubevir CDI CRD reconcile loop issue

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4]
**Issue:**
kubevirt's `datavoulems` and `cdiconfigs` keep updating its `managedFields.time` field and it leads to steve keeps refreshing its loaded schema.

**Reproduce steps:**
`kubectl get crds -w` and the following two CRDs keeps updating
```
datavolumes.cdi.kubevirt.io                                     2020-07-15T05:52:53Z
cdiconfigs.cdi.kubevirt.io                                      2020-07-15T05:52:53Z
```
check the VM server logs and it will print refreshing schema message in every 2-3 seconds:
```
INFO[0013] Refreshing all schemas                       
INFO[0014] Refreshing all schemas                       
INFO[0014] APIVersion /v1 Kind Bindin
...
```

Expected:
there are two ways to address this issue:
1. since the `managedFields.time` is introduced in k8s 1.18 and only used as object metadata, it should not be updated continuously - `preferred`.
2. ensure steve only refreshing updated CRD schema instead of all.

**Comment by guangbochen** [comment]
the current latest release of kubevirt CDI is `v1.20.1` and this is a known issue in https://github.com/kubevirt/containerized-data-importer/commit/72d47353a29c8c9a7c6e3c2874618103ce0e79b9, for now, we can use the `latest` image to remit this bug, deploy the CDI example YAML as below:
```YAML
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.cdi.kubevirt.io: ""
  name: cdis.cdi.kubevirt.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.phase
    name: Phase
    type: string
  conversion:
    strategy: None
  group: cdi.kubevirt.io
  names:
    categories:
    - all
    kind: CDI
    listKind: CDIList
    plural: cdis
    shortNames:
    - cdi
    - cdis
    singular: cdi
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            imagePullPolicy:
              enum:
              - Always
              - IfNotPresent
              - Never
              type: string
            uninstallStrategy:
              enum:
              - RemoveWorkloads
              - BlockUninstallIfWorkloadsExist
              type: string
          type: object
        status:
          description: The most recently observed status of the CDI resource
          properties:
            conditions:
              description: A list of current conditions of the CDI resource
              items:
                properties:
                  lastHeartbeatTime:
                    description: Last time the state of the condition was checked
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: Last time the state of the condition changed
                    format: date-time
                    type: string
                  message:
                    description: Message related to the last condition change
                    type: string
                  reason:
                    description: Reason the last condition changed
                    type: string
                  status:
                    description: Current status of the condition, True, False, Unknown
                    type: string
                type: object
              type: array
            observedVersion:
              description: The observed version of the CDI resource
              type: string
            operatorVersion:
              description: The version of the CDI resource as defined by the operator
              type: string
            phase:
              description: The current phase of the CDI resource
              type: string
            targetVersion:
              description: The desired version of the CDI resource
              type: string
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    operator.cdi.kubevirt.io: ""
  name: cdi-operator-cluster
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - cdi.kubevirt.io
  - upload.cdi.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - list
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - cdis
  verbs:
  - get
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - cdis/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  - pods/finalizers
  - volumesnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    operator.cdi.kubevirt.io: ""
  name: cdi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator-cluster
subjects:
- kind: ServiceAccount
  name: cdi-operator
  namespace: cdi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    operator.cdi.kubevirt.io: ""
  name: cdi-operator
  namespace: cdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-operator
  namespace: cdi
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - events
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-operator
  namespace: cdi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-operator
subjects:
- kind: ServiceAccount
  name: cdi-operator
  namespace: cdi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: latest
        - name: CONTROLLER_IMAGE
          value: kubevirt/cdi-controller:latest
        - name: IMPORTER_IMAGE
          value: kubevirt/cdi-importer:latest
        - name: CLONER_IMAGE
          value: kubevirt/cdi-cloner:latest
        - name: APISERVER_IMAGE
          value: kubevirt/cdi-apiserver:latest
        - name: UPLOAD_SERVER_IMAGE
          value: kubevirt/cdi-uploadserver:latest
        - name: UPLOAD_PROXY_IMAGE
          value: kubevirt/cdi-uploadproxy:latest
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        image: kubevirt/cdi-operator:latest
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    operator.cdi.kubevirt.io: ""
  name: cdi-operator-leader-election-helper
  namespace: cdi

```
