### ISSUE TITLE
[ENHANCEMENT] let user could setup `HostStorageClass` with helm option

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4045]
**Is your enhancement related to a problem? Please describe.**
The environment variable `HostStorageClass` could be set for the default StorageClass associated with the bare-metal harvester cluster of the harvester CSI driver.
We may expose this variable to set it up when deploying the downstream cluster.

**Describe the solution you'd like**
Expose the `HostStorageClass` with the helm chart

**Describe alternatives you've considered**
None

**Additional context**
Reference for this variable:
https://github.com/harvester/harvester-csi-driver/blob/master/main.go#L41

**Comment by irishgordo** [comment]
Hi, @Vicente-Cheng - I've been working through testing this but had some validation questions.

Is it possible to validate this by "re-deploying" the harvester-csi-driver App from Rancher UI w/ "Edit YAML" and on the `helm options`:
- Cleanup on Failure
- Execute chart hooks
- Force
- Reset Values
- Wait
( all boxes checked )
to update it?

As I've been trying with separate loadouts of "Edit YAML" either taking the shape of the following.

Edited YAML Example A:
```yaml
cloudConfig:
  hostPath: /var/lib/rancher/rke2/etc/config-files/
  secretName: ''
fullnameOverride: ''
global:
  cattle:
    systemProjectId: p-cgbv4
  clusterCIDR: 10.42.0.0/16
  clusterCIDRv4: 10.42.0.0/16
  clusterDNS: 10.43.0.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 10.43.0.0/16
image:
  csi:
    attacher:
      repository: rancher/mirrored-longhornio-csi-attacher
      tag: v3.2.1
    nodeDriverRegistrar:
      repository: rancher/mirrored-longhornio-csi-node-driver-registrar
      tag: v2.3.0
    provisioner:
      repository: rancher/mirrored-longhornio-csi-provisioner
      tag: v2.1.2
    resizer:
      repository: rancher/mirrored-longhornio-csi-resizer
      tag: v1.2.0
  harvester:
    csiDriver:
      repository: rancher/harvester-csi-driver
      tag: v0.1.5
      args:
        - '--host-storage-class=extrasc'
  pullPolicy: IfNotPresent
kubeletRootDir: /var/lib/kubelet
nameOverride: ''
nodeSelector:
  kubernetes.io/os: linux
replicasCount: 3
tolerations:
  - effect: NoSchedule
    key: kubevirt.io/drain
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Equal
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

Edited YAML Example B:
```yaml
cloudConfig:
  hostPath: /var/lib/rancher/rke2/etc/config-files/
  secretName: ''
fullnameOverride: ''
global:
  cattle:
    systemProjectId: p-cgbv4
  clusterCIDR: 10.42.0.0/16
  clusterCIDRv4: 10.42.0.0/16
  clusterDNS: 10.43.0.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 10.43.0.0/16
image:
  csi:
    attacher:
      repository: rancher/mirrored-longhornio-csi-attacher
      tag: v3.2.1
    nodeDriverRegistrar:
      repository: rancher/mirrored-longhornio-csi-node-driver-registrar
      tag: v2.3.0
    provisioner:
      repository: rancher/mirrored-longhornio-csi-provisioner
      tag: v2.1.2
    resizer:
      repository: rancher/mirrored-longhornio-csi-resizer
      tag: v1.2.0
  harvester:
    csiDriver:
      repository: rancher/harvester-csi-driver
      tag: v0.1.5
      env:
        - name: HOST_STORAGE_CLASS
          value: extrasc
  pullPolicy: IfNotPresent
kubeletRootDir: /var/lib/kubelet
nameOverride: ''
nodeSelector:
  kubernetes.io/os: linux
replicasCount: 3
tolerations:
  - effect: NoSchedule
    key: kubevirt.io/drain
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Equal
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

With either edited yaml loadouts on:
- Harvester v1.3.0-rc2
- Rancher v2.8.1 (on rancher-vcluster addon)

I'm not able to build a PVC for the RKE2 (Kubernetes Version: v1.27.10 +rke2r1) cluster that when selecting `harvester` will utilize the `extrasc` storage class, it's still all defaulting to the default storage-class.

Artifacts:
![Screenshot from 2024-02-13 16-00-48](https://github.com/harvester/harvester/assets/5370752/9ae87b53-d6df-42f5-9614-aeb1aefec958)
![Screenshot from 2024-02-13 15-59-58](https://github.com/harvester/harvester/assets/5370752/19ffd49f-aa9e-4f46-87b0-284dd760873a)
![Screenshot from 2024-02-13 15-56-06](https://github.com/harvester/harvester/assets/5370752/43ba925c-f145-4cdc-9596-f31c5a9bf2dd)
![Screenshot from 2024-02-13 15-44-43](https://github.com/harvester/harvester/assets/5370752/ece118c5-487c-4e8a-b21c-e40732535bfc)
