### ISSUE TITLE
[ENHANCEMENT] Minimum disk requirement seems excessive

### ISSUE THREAD

**Issue by gsuess** [harvester/harvester#4133]
**Is your enhancement related to a problem? Please describe.**

I am attempting to install 1.2.0-rc2 and I see that the minimum disk size requirement is now set at 250Gi.

> Disk size is too small. Minimum 250Gi is required.

This may make sense if no additional disk is used, but not when a separate disk is used for the "data disk". I cannot see how system files can possibly use up so much space.

![rpviewer (1)](https://github.com/harvester/harvester/assets/1558575/8d1963a7-b3e2-4041-b5dd-389d3d34cac2)

**Describe the solution you'd like**
How about asking if a user-space partition is to be used, and the dynamical adapt these constraints? IMO this should be done before  there is an official release for 1.2.0.

**Describe alternatives you've considered**

If possible just keep the mininum disk size constraint at 90Gi.

**Comment by Vicente-Cheng** [comment]
Hi @gsuess, 

Thanks for your feedback!
This change is introduced on https://github.com/harvester/harvester-installer/pull/499

For some tests, we may only need a little disk space.
But for the general cases, we prefer to reserve enough disk space for upgrades and general cases.

Could you describe what use cases you would like to use?
That may help us to consider more cases.

Thanks!

**Comment by gsuess** [comment]
The use-case is to avoid wasting unused disk-space. My assumption here was that it is set so high for the case where the installation target is shared with the data disk. Given that VM data and container volumes will be stored on the data disk, I wonder why the installation target needs to much space. What kind of tests are you running? And why not just used the other volume for the tests?

**Comment by gsuess** [comment]
After installation on 13% of the 256GB are being used.

**Comment by Vicente-Cheng** [comment]
Hi @gsuess,
The main disk usage of an OS disk is a persistent partition.

We increase the minimum persistent size (100G -> 150G) and make it a hard limit.
The persistent partition would store our system data, like `logs`, `images`.
Also, we need to pre-load some images to the system when we upgrade. To prevent the gc caused by disk pressure so we changed the design.
 
You could just allocate the minimum persistent size (150G), and you still have around 100G for default longhorn storage.

Try to explain why we do this change, and surely we will discuss your suggestions.
We would like a better way to make the OS disk more efficient.

Thanks!

**Comment by gsuess** [comment]
@Vicente-Cheng 

> We increase the minimum persistent size (100G -> 150G) and make it a hard limit.

It seems the hard limit is 250G now

> The persistent partition would store our system data, like `logs`, `images.`

Thanks for clarifying. I would have expected them to be on the data disk, instead.

> Also, we need to pre-load some images to the system when we upgrade. To prevent the gc caused by disk pressure so we changed the design.

But that doesn't explain why only about 13% of the 250G are used. Also note that for v1.1.0 the limit of 96G.

> You could just allocate the minimum persistent size (150G), and you still have around 100G for default longhorn storage.

The installer doesn't have the option once you select a second drive for disk storage.

> Try to explain why we do this change, and surely we will discuss your suggestions.

Not sure why more justification is needed, other than not having unused space lying around. Perhaps I am wrong about the space being unused. If its not unused then we can close this, however I still don't understand what it's used for.

**Comment by jmcglock** [comment]
![Screenshot 2023-06-28 at 4 15 06 PM](https://github.com/harvester/harvester/assets/85720969/1559a1b2-ca47-441d-99a5-4830415dc3f3)
It would be helpful if this could be overridden in the config-create file when installing over pxe boot.
Also, most Equinix metal machines come with 240GB SSD drives which are very close to the minimum but not quite there.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/harvester/harvester/assets/5169694/42fb85e4-48cd-4361-a0c3-0346a70b3ac4)
![image](https://github.com/harvester/harvester/assets/5169694/dcef84d8-e22b-4aeb-bb06-7254546a40d1)
![image](https://github.com/harvester/harvester/assets/5169694/2cba8502-6e0c-452c-ac8f-f3a1789c098e)
![image](https://github.com/harvester/harvester/assets/5169694/b5d223a6-7250-44f9-af98-3731141d41fc)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2-961753c6-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes having at least 2 disks manually
2. User should able to select **Data Disk** on another physical disk
3. User should able to install Harvester on the disk `>180Gi` when **Data Disk** selected to another physical disk
4. User should NOT able to install Harvester on the disk `<250Gi` when using same disk for **Data Disk**
5. Harvester should installed successfully

**Comment by johnwc** [comment]
@lanfon72 @Vicente-Cheng This issue still exists in v1.2.2 when installing via pxe and using config file.

```yaml
scheme_version: 1
server_url: https://10.100.1.100:443
token: ...
os:
  hostname: hyper08
  labels:
    topology.kubernetes.io/region: us-southc-1
    topology.kubernetes.io/zone: us-southc-1c
  password: ...
  dns_nameservers:
    - 10.100.1.7
    - 10.100.1.5
  ntp_servers:
    - 0.north-america.pool.ntp.org
    - 1.north-america.pool.ntp.org
install:
  mode: join
  management_interface:
    interfaces:
      - hwAddr: "xx:xx:xx:06:91:88"
      - hwAddr: "xx:xx:xx:06:91:8C"
    method: static
    vlan_id: 10
    ip: 10.100.1.38
    subnet_mask: 255.255.255.0
    gateway: 10.100.1.1
    default_route: true
    bond_options:
      mode: balance-xor
      miimon: 100
  force_efi: true
  device: /dev/sdb
  data_disk: /dev/sda
  iso_url: http://10.100.0.20/os/harvester/harvester-v1.2.2-amd64.iso
```

![image](https://github.com/harvester/harvester/assets/2798441/7b468557-c6f9-4419-be93-693f9e9166b7)
