### ISSUE TITLE
support i440fx machine type

### ISSUE THREAD

**Issue by chifu1234** [harvester/harvester#417]
We had some trouble to deploy a citrix adc vpx kvm to harvester. It seems like that freebsd os only supports  i440FX on KVM and not just Q35. If there is no reason to limit VMs only running on Q35 architecture, I would suggest to change the behavior that Q35 and I440FX are supported:
```
    emulatedMachines:
    - q35
    - pc-q35*
    - pc-i440fx*
```

https://github.com/rancher/harvester/blob/766abd06561b059c1af623aacc4e505db471ceee/deploy/charts/harvester/dependency_charts/kubevirt/values.yaml#L107

**Comment by guangbochen** [comment]
What are your installation method(ISO/App mode) and setup environment?

**Comment by guangbochen** [comment]
the default configuration should support both i440fx and q35 classes of chipsets for x86_64, when creating the VM u probably need to specify the machine type to be `pc-i440fx-2.10` instead of `q35`.
for more details, u may refer to https://kubevirt.io/user-guide/#/creation/devices?id=machine-type
```
metadata:
  name: myvmi
spec:
  domain:
    machine:
      # This value indicates QEMU machine type.
      type: pc-i440fx-2.10
    resources:
      requests:
        memory: 512M
    devices:
      disks:
      - name: myimage
        disk: {}
  volumes:
    - name: myimage
      persistentVolumeClaim:
        claimName: myclaim
```
