### ISSUE TITLE
[BUG] Storage Network Allows Duplicate `exclude` IPv4 CIDR items in list

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4217]
**Describe the bug**
When creating a storage network, that builds network-attachment-definitions per:
https://github.com/tjjh89017/harvester/blob/78d268cc810db037ba1b73bf6e50d30f86763cd2/enhancements/20220822-storage-network/20220822-storage-network.md
And https://github.com/harvester/harvester/issues/3867
Storage Network setting built allows for duplicate exludes.

**To Reproduce**
1. Goto build Storage Network setting
1. Set up storage network
1. Pass in multiple of the same excludes, creating duplicates

**Expected behavior**
Filtering out the duplicates, at the webhook level or just when the Network Attachment Definition gets created in the config, just ignoring the duplicates.

**Environment**
 - Harvester ISO version: v1.2.0-rc3
 - Underlying Infrastructure: qemu/kvm

**Additional context**

```bash
╭─mike at suse-workstation-team-harvester in ~/Projects/test_3867
╰─○ kubectl get network-attachment-definitions -n harvester-system -o wide
NAME                   AGE
storagenetwork-2f52q   4m15s
storagenetwork-d6jcb   4m15s
storagenetwork-spg8p   4m15s
```

```yaml
Name:         storagenetwork-spg8p
Namespace:    harvester-system
Labels:       network.harvesterhci.io/clusternetwork=additional
              network.harvesterhci.io/ready=true
              network.harvesterhci.io/type=L2VlanNetwork
              network.harvesterhci.io/vlan-id=1
Annotations:  storage-network.settings.harvesterhci.io: true
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2023-07-10T21:31:42Z
  Finalizers:
    wrangler.cattle.io/harvester-network-nad-controller
    wrangler.cattle.io/harvester-network-manager-nad-controller
  Generate Name:  storagenetwork-
  Generation:     1
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:storage-network.settings.harvesterhci.io:
        f:generateName:
      f:spec:
        .:
        f:config:
    Manager:      harvester
    Operation:    Update
    Time:         2023-07-10T21:31:42Z
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"wrangler.cattle.io/harvester-network-manager-nad-controller":
          v:"wrangler.cattle.io/harvester-network-nad-controller":
        f:labels:
          .:
          f:network.harvesterhci.io/clusternetwork:
          f:network.harvesterhci.io/ready:
          f:network.harvesterhci.io/type:
          f:network.harvesterhci.io/vlan-id:
    Manager:         harvester-network-controller
    Operation:       Update
    Time:            2023-07-10T21:31:43Z
  Resource Version:  58028
  UID:               f6fdfbae-0687-4a81-b771-8b5a54d6dfeb
Spec:
  Config:  {"cniVersion":"0.3.1","type":"bridge","dns":{},"bridge":"additional-br","promiscMode":true,"vlan":1,"ipam":{"type":"whereabouts","range":"172.16.0.0/24","exclude":["172.168.0.1/24","172.168.0.1/24"]}}
Events:    <none>
```

But I'm not sure if via `whereabouts` having 'duplicate' excludes breaks anything? :thinking: :
https://github.com/k8snetworkplumbingwg/whereabouts/blob/9b72da837a6475ea15a6dcf965372d0d6b09b6c0/cmd/whereabouts_test.go#L274-L300
( however, I don't note a unit test within the whereabouts_test.go where they pass in duplicate IPv4 addresses to the exclude )

`whereabouts` might not care, since we're utilizing that, so I'm setting this at a lower severity :smile:
