### ISSUE TITLE
[BUG] Error on addon details page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4306]
**Describe the bug**

The state of the addons is fine, but the `metadata.state` in the api shows an error

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/2c76444f-9b66-482f-bb2b-ac9b023718df)

<img width="1713" alt="image" src="https://github.com/harvester/harvester/assets/24985926/38e74a5a-aac4-4716-987f-689454afc5a9">

**To Reproduce**
1.  install harvester-v1.2.0-rc4
2. go to addon lists page
3. Click `rancher-monitoring` addon name to go to the details page

**Expected behavior**

There should be no error messages.   （`metadata.state.name` equals error, meaning that there is an error in the current resource， if there is no error then `name` should not be equal to error.）

**Support bundle**

**Environment**
 - Harvester ISO version:  harvester-v1.2.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
@ibrokethecloud any insights? 
could it be that: the addon.status.conditions[] transfer implicitly triggers the Rancher (hacked) part assumes error?

**Comment by w13915984028** [comment]
The condition `Failed` has `error: true` generated on 20230724, maybe it was poped up to metadata.status by wrangler framework internally.  

Later, 20230725, the `func markCompletedCondition(aObj *harvesterv1.Addon) {` did not revert the above.
https://github.com/harvester/harvester/blob/08b6939d614df9a8ff1ce86fa2b92a787e1977d3/pkg/controller/master/addon/common.go#L194 
```
	harvesterv1.AddonOperationFailed.False(aObj)
	harvesterv1.AddonOperationFailed.Reason(aObj, "")
	harvesterv1.AddonOperationFailed.Message(aObj, "")
```

How wrangler does the trick to add a new filed `Error` ? no idea yet.

https://github.com/rancher/wrangler/blob/201b4da5bdaf5c913c2ffe954476723042dbb9c0/pkg/condition/condition.go#L17

@ibrokethecloud any insights?

**Comment by w13915984028** [comment]
@WuJun2016 @irishgordo :

Do you have more context of this issue ? seemed the rancher-monitoring addon failed once but later was OK.

**Comment by w13915984028** [comment]
@ibrokethecloud @WuJun2016 :

It seems to be applied to any addons (with latest code), if this addon is enabled, then the detailed page will have an error state.

What @WuJun2016 shared is from `view in API`, there are addional fields added by Rancher framework, but from `kubectl`, there is no such info like `metadata.status` or `status.conditions[].error`.

I suspect below functions, which will set the `Failed` condition, and no matter true/false, the Rancher framework will propogate this error to internal.

```
func markCompletedCondition(aObj *harvesterv1.Addon) {
	now := time.Now().UTC().Format(time.RFC3339)
	harvesterv1.AddonOperationCompleted.True(aObj)
	harvesterv1.AddonOperationCompleted.LastUpdated(aObj, now)
	harvesterv1.AddonOperationInProgress.False(aObj)
	
	harvesterv1.AddonOperationFailed.False(aObj)  ----------------->
	harvesterv1.AddonOperationFailed.Reason(aObj, "")
	harvesterv1.AddonOperationFailed.Message(aObj, "")
}
```

@ibrokethecloud Please also take a look at your environment. thanks.

**Comment by ibrokethecloud** [comment]
i can confirm that i see the error, i am just going to check what are our options.

**Comment by ibrokethecloud** [comment]
I suspect this is being caused because `Failed` seems to be a reserved condition.Type
https://github.com/rancher/wrangler/blob/master/pkg/summary/summarizers.go#L81

and when summary is generated the condition is met, which causes the generation of the summary error:
https://github.com/rancher/wrangler/blob/master/pkg/summary/summarizers.go#L221

easiest fix is to rename condition "Failed" to "OperationFailed" and that fixes the error:

sample build `gmehta3/harvester:addon-upgrade-fixes-head` has the fix: 

![image](https://github.com/harvester/harvester/assets/19664014/0ebac615-43ea-4356-9fc0-8c83188e4dce)

Post this change the summary error is gone.

To test on an existing cluster, please edit the existing addon resources as follows:

`kubectl edit addon.harvester $addon-name --subresource=status` and remove the `Failed` condition.

Disable/Enabling the addon will trigger reprocessing with new conditions and the summary error will be cleared.

**Comment by w13915984028** [comment]
UI also needs some additional work.

We tried to reuse `Failed` condition to simplify UI's process to show proper error message on the web page. As addon can be enabled/disabled/updated continuously, the Rancher reserved `Failed` condition seems not a good option here.

Now we have two options:
(1) Rename `Failed` to `OperationFailed` and UI changes the place to fetch error message
(2) Keep `Failed` condtion, UI hides the `internal error` in detailed page / other related page.

@WuJun2016 @DaiYuzeng Please double check. thanks.
 cc @ibrokethecloud

**Comment by ibrokethecloud** [comment]
I dont think any UI changes are needed as we still set a condition in error, which is picked up by steve:

here is a sample addon I used and the errors from conditions are reflected in the UI:
```
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: fake-addon
  namespace: harvester-system
spec:
  chart: fake-addon
  enabled: false
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v0.1.0-rc3
    fullnameOverride: fake-addon
  version: 0.1.0-rc3
```

![image](https://github.com/harvester/harvester/assets/19664014/6b2adf95-16d6-4f1b-aa2e-a91892b12f6b)

![image](https://github.com/harvester/harvester/assets/19664014/8655cf9e-5e88-45f1-97d0-974b39d80361)

**Comment by DaiYuzeng** [comment]
Hi @ibrokethecloud ! The logic of error message's displaying is as follows:

```
get stateDescription() {
  const failedCondition = (this.status?.conditions || []).find(C => C.type === 'Failed');

  return failedCondition?.message || super.stateDescription;
}
```

As you can see, there is a `type` filter. If we replace `Failed` with `OperationFailed`, the error message should be invisible. Could you double-check this?

cc @w13915984028 @WuJun2016 

Thank you!

**Comment by ibrokethecloud** [comment]
# To Test this change
use v1.2-head image

## Successful case
* Enabling an inbuilt addon say monitoring or logging
* once the addon is enable, browse to addon details
* no failure message is reported: 
![image](https://github.com/harvester/harvester/assets/19664014/3d9ea66d-ff11-4d08-9202-a97c3da48ab1)

## Failure case
* create a fake addon using the following manifest `kubectl apply -f fake-addon.yaml`
```
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: fake-addon
  namespace: harvester-system
spec:
  chart: fake-addon
  enabled: false
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v0.1.0-rc3
    fullnameOverride: fake-addon
  version: 0.1.0-rc3
```
* enable the fake-addon, and wait for it to fail
![image](https://github.com/harvester/harvester/assets/19664014/1f81664f-10e0-4c69-97df-3ff5718e13d4)
* query addon using api or kubectl and confirm that new failue condition `OperationFailed` is set on the addon
```
status:
  conditions:
  - lastUpdateTime: "2023-07-26T23:18:37Z"
    status: "False"
    type: Completed
  - lastUpdateTime: "2023-07-26T23:21:52Z"
    status: "False"
    type: InProgress
  - lastUpdateTime: "2023-07-26T23:21:52Z"
    message: addon deployment job helm-install-fake-addon failed
    reason: Error
    status: "True"
    type: OperationFailed
  status: AddonEnabling
```
