### ISSUE TITLE
[ENHANCEMENT] Ensure the cluster network to have same MTU and propagate to NADs

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#4355]
**Is your enhancement related to a problem? Please describe.**

<del>
The MTU is a global attribute across all the devices in the cluster network. To achieve code decoupling, it would be more reasonable to configure the MTU value in the cluster network rather than in the VLAN configuration. This approach facilitates easier synchronization of the MTU value across VLAN configurations and virtual machine networks.
</del>

updated by Jian Wang at 2025.08.07

Ensure the cluster network to have same MTU and propagate to NADs

1. When building a clusternetwork, all the participating nodes need to have same MTU value, different MTU will cause potential issues, Harvester document has explained the detailed steps, but still expect the controller can ensure the process

https://docs.harvesterhci.io/v1.5/networking/index#change-the-mtu-of-a-network-configuration-with-no-attached-storage-network

2. When a cluster has configured or changed the MTU to a new value, all the NADs under this clusternetwork should inheriate the MTU correctly

**Describe the solution you'd like**

<del>
Support configure MTU in the cluster network
</del>

1. Ensure the cluster network to have same MTU;
2. Propagate MTU to NADs;
3. Document the limitation on mgmt clusternetwork;

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
@w13915984028 Please help check the issue and if we can make it in 1.3.0.

**Comment by bk201** [comment]
@w13915984028 gentle ping to check the issue again.

**Comment by w13915984028** [comment]
@bk201 I will check and add it to v140 list. thanks.

**Comment by w13915984028** [comment]
Currently, the `ClusterNetwork` is more like a top level concept, the only useful field is `name`.

The `VlanConfig` defines which node is involving in a `ClusterNetwork` and the related `uplink` and other parameters. A `ClusterNetwork` can have a group of `VlanConfig`.

Based on following considerations:
(1) Keep the simplicity of `ClusterNetwork`
(2) Like configuring the MTU on each server port, switch port, configuring the MTU on the bonded uplink also looks normal.

Would suggest Harvester to keep current UI and implementation. We can add a hint in [step 3 of how-to-create-a-new-cluster-network](https://docs.harvesterhci.io/v1.3/networking/index#how-to-create-a-new-cluster-network) that the MTU under a  `ClusterNetwork` should keep identical. Will check if validator hook also makes sure this.

@bk201 @starbops @mingshuoqiu WDYT? thanks.

```
apiVersion: network.harvesterhci.io/v1beta1
kind: ClusterNetwork
metadata:
  name: data
status:
  conditions:
  - status: "True"
    type: ready


apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  annotations:
    network.harvesterhci.io/matched-nodes: '["harv41"]'
  labels:
    network.harvesterhci.io/clusternetwork: data
  name: data-1
spec:
  clusterNetwork: data
  uplink:
    bondOptions:
      miimon: -1
      mode: active-backup
    linkAttributes:
      mtu: 1500
      txQLen: -1
    nics:
    - ens8
```

**Comment by w13915984028** [comment]
Currently, the `ClusterNetwork` is more like a top level concept, the only useful field is `name`.

The `VlanConfig` defines which node is involving in a `ClusterNetwork` and the related `uplink` and other parameters. A `ClusterNetwork` can have a group of `VlanConfig`.

Based on following considerations:
(1) Keep the simplicity of `ClusterNetwork`
(2) Like configuring the MTU on each server port, switch port, configuring the MTU on the bonded uplink also looks normal.

Would suggest Harvester to keep current UI and implementation. We can add a hint in [step 3 of how-to-create-a-new-cluster-network](https://docs.harvesterhci.io/v1.3/networking/index#how-to-create-a-new-cluster-network) that the MTU under a  `ClusterNetwork` should keep identical. Will check if validator hook also makes sure this.

@bk201 @starbops @mingshuoqiu WDYT? thanks.

```
apiVersion: network.harvesterhci.io/v1beta1
kind: ClusterNetwork
metadata:
  name: data
status:
  conditions:
  - status: "True"
    type: ready


apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  annotations:
    network.harvesterhci.io/matched-nodes: '["harv41"]'
  labels:
    network.harvesterhci.io/clusternetwork: data
  name: data-1
spec:
  clusterNetwork: data
  uplink:
    bondOptions:
      miimon: -1
      mode: active-backup
    linkAttributes:
      mtu: 1500
      txQLen: -1
    nics:
    - ens8
```

**Comment by starbops** [comment]
@w13915984028 I think CanWu originally suggested moving the MTU setting from VlanConfig to ClusterNetwork because, semantically, it's a parameter that applies to cluster-wide underlay networks. On the other hand, NADs are just overlay networks, so they need to follow some of the parameters that the underlay network they are associated with is using, including MTU.

Currently, the MTU setting spreads in two places:

- VlanConfig's linkAttr
- NetworkAttachmentDefinition's networkConf

Consider the two independently, the MTU value in VlanConfig's linkAttr only affects the underlying bond and bridge interfaces; the MTU value in NAD's networkConf affects all the workloads (pods) attaching to the NAD. But NAD's MTU value is implicit:

1. We rely on the mutator to patch the MTU value according to the relevant VlanConfig's linkAttr during NAD creation
2. It's not exposed as a dedicated field in the CRD
3. All NADs that are associated with a specific ClusterNetwork should have the same MTU value set

So there are two downsides come after them:

1. After updating the MTU value in VlanConfig, the new value will not be propagated to all of the associated NADs
2. Users are unable to specify the MTU value for NAD via UI easily


IMO, the NAD's MTU value should always be propagated from an object representing the underlay network, i.e. ClusterNetwork, not being explicitly set by users.

Additionally, do you think the fix for #4752 will conflict with this enhancement? I plan to modify the VlanConfig mutator to update the corresponding NADs' MTU value when an UPDATE request comes in.

Thank you.

**Comment by w13915984028** [comment]
FYI: We are working on an document about how to change the MTU on existing `Network Config/Cluster Network`.

**Comment by w13915984028** [comment]
Move issue to v1.5.0. The document PR https://github.com/harvester/docs/pull/640 is reviewing, it will help user to manually change MTU.

**Comment by w13915984028** [comment]
With PR https://github.com/harvester/network-controller-harvester/pull/149, the UI does not change, users also does not need to configure the cluster network MTU explicitly.

Instead, the MTU is obtained from the first vlanconfig of a clusternetwork, and if later vlanconfig has different MTU, it is not allowed.

If the only vlanconfig changes the MTU, it is allowed and the MTU is synced to clusternetwork and all NADs automatically.

**Comment by innobead** [comment]
This is not a priority. 

cc @ihcsim

**Comment by w13915984028** [comment]
doc task:

Massive enhancements are done via PR https://github.com/harvester/network-controller-harvester/pull/149;  related documents should be updated.

**Comment by Vicente-Cheng** [comment]
Hi @w13915984028, 

Could we move this to Ready For Testing?

**Comment by w13915984028** [comment]
The code has been merged, I will move this to testing now. The detailed test plans are on: https://github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

The document will be updated on another PR, it does no block the validation.

**Comment by irishgordo** [comment]
Still testing things.
Discovered: https://github.com/harvester/harvester/issues/8783

**Comment by irishgordo** [comment]
@w13915984028 @rrajendran17  - still testing but there is a baseline validation issue on this, see the failure.
Will continue testing however.
Echoing this out sooner than later.

### Cluster Network, User Defined

<details><summary>$\color{green}{\textsf{PASS}}$ Creating Cluster Network (non-mgmt) with uplink-mtu annotation and value of 1500 fails as expected $~~$</summary>

  1. When attempting to create Cluster Network "testing", error of: `admission webhook "validator.harvester-system.harvester-network-webhook" denied the request: Internal error occurred: can't create cluster network testing because annotation network.harvesterhci.io/uplink-mtu can't be added` as expected


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Creating Cluster Network (non-mgmt) with uplink-mtu annotation and value of 1400 fails as expected when creating as yaml $~~$</summary>

  1. When attempting to create Cluster Network `new-testing` with uplink-mtu: 1400 via editing as YAML on form fails as expected


 </details>

<details><summary>$\color{red}{\textsf{FAIL}}$ Adding uplink-mtu annotation to Cluster Network when there are no valid vlanconfigs $~~$</summary>

  1. When editing a Cluster Network with 0 cluster network configurations the annotation can be added with a value like 1400
  2. When the a new network configuration is added we unfortunately do not see the network.harvesterhci.io/uplink-mtu there and present on the network configuration after it is added, it is not auto-populated as an annotation when building the resource in the UI nor is it present after the resource has been created when auditing the linkAttributes property
  3. Additionally, it causes issues as when `nc1` is built, it's building the MTU for `nc1` as 0
  4. Extra additionally, when the user goes back to view the `uplink-mtu` on the `testing` cluster network it has silently modified that value, shifting it surprisingly from 1400 -> 1500

<img width="1138" height="828" alt="Image" src="https://github.com/user-attachments/assets/428b4ec2-9ab0-4c17-a015-674237c57972" />
<img width="1140" height="827" alt="Image" src="https://github.com/user-attachments/assets/1b7965c0-b855-4b23-a5c1-362ef7d4e07c" />
<img width="1127" height="834" alt="Image" src="https://github.com/user-attachments/assets/77dbc8be-2098-4c0e-97fc-155b6440aa0d" />
<img width="1127" height="835" alt="Image" src="https://github.com/user-attachments/assets/096539f7-fb8d-491c-b8a2-82e4802e4806" />
<img width="1138" height="831" alt="Image" src="https://github.com/user-attachments/assets/255686e5-7c6e-4823-9db8-7b4d78f60be9" />

 </details>

**Comment by irishgordo** [comment]
@rrajendran17 @w13915984028  - additionally noticing:
- https://github.com/harvester/harvester/issues/8784

**Comment by irishgordo** [comment]
@rrajendran17 @w13915984028  also opened up:
- https://github.com/harvester/harvester/issues/8788

**Comment by irishgordo** [comment]
@rrajendran17 @w13915984028 opening up:
- https://github.com/harvester/harvester/issues/8805

**Comment by irishgordo** [comment]
@rrajendran17 for the failure on:
- https://github.com/harvester/harvester/issues/4355#issuecomment-3141057794
The gist is when building a `Cluster Network Configuration` the MTU value is empty, when creating it, it's not "seeding" the uplink-mtu value from the parent cluster-network.

<img width="1894" height="1886" alt="Image" src="https://github.com/user-attachments/assets/259708b0-8c17-4b93-ae02-377052d6ba6d" />
<img width="1891" height="1901" alt="Image" src="https://github.com/user-attachments/assets/881f5441-a0c7-4066-8a18-0bf95e528f15" />

So the user then is relegated to the following since:
1. manually enter 1400, though the uplink mtu on the cluster network it's annotation, when there are 0 network configs, is 1400...

But maybe this behavior is expected?

I guess the thought would be:
1. MTU gets auto populated for Network Configuration Creation of "first" NC in Cluster Network, when Cluster Network has already defined MTU as an annotation
2. If a user does not change the MTU to a different value, it sees just the auto populated one from the parent and then is able to just use that
3. When the MTU is blank show "0" instead of "empty"?

<img width="1915" height="1932" alt="Image" src="https://github.com/user-attachments/assets/063d72a0-9426-4fc2-946f-4ae58de15fab" />

I can see that if the Cluster Network, is set at 1400, that there are no network configs, that if the MTU is entered at 1350 (and it's the first network config) that looks good and does update the parent cluster network annotation accurately

**Comment by irishgordo** [comment]
@rrajendran17 @w13915984028  opening: https://github.com/harvester/harvester/issues/8806

**Comment by irishgordo** [comment]
@rrajendran17 @w13915984028 generally this looks good, outside of the other issues opened & some of the comments on the other issues.

### Cluster Network, User Defined

<details><summary>$\color{green}{\textsf{PASS}}$ Creating Cluster Network (non-mgmt) with uplink-mtu annotation and value of 1500 fails as expected $~~$</summary>

  1. When attempting to create Cluster Network "testing", error of: `admission webhook "validator.harvester-system.harvester-network-webhook" denied the request: Internal error occurred: can't create cluster network testing because annotation network.harvesterhci.io/uplink-mtu can't be added` as expected

<img width="1119" height="818" alt="Image" src="https://github.com/user-attachments/assets/fcb1698a-a81a-4edc-b148-dec42d1ba899" />

  
 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Creating Cluster Network (non-mgmt) with uplink-mtu annotation and value of 1400 fails as expected when creating as yaml $~~$</summary>

  1. When attempting to create Cluster Network `new-testing` with uplink-mtu: 1400 via editing as YAML on form fails as expected

<img width="1129" height="815" alt="Image" src="https://github.com/user-attachments/assets/cf5cc2f8-0280-41f6-b796-b45dc1669b2a" />

<img width="1134" height="806" alt="Image" src="https://github.com/user-attachments/assets/f52b1fcf-de41-4fb2-9ea7-ba1475f5fe16" />

 </details>

<details><summary>$\color{red}{\textsf{FAIL}}$ Adding uplink-mtu annotation to Cluster Network when there are no valid vlanconfigs $~~$</summary>

  1. When editing a Cluster Network with 0 cluster network configurations the annotation can be added with a value like 1400
  2. When the a new network configuration is added we unfortunately do not see the network.harvesterhci.io/uplink-mtu there and present on the network configuration after it is added, it is not auto-populated as an annotation when building the resource in the UI nor is it present after the resource has been created when auditing the linkAttributes property
  3. Additionally, it causes issues as when `nc1` is built, it's building the MTU for `nc1` as 0
  4. Extra additionally, when the user goes back to view the `uplink-mtu` on the `testing` cluster network it has silently modified that value, shifting it surprisingly from 1400 -> 1500

<img width="1138" height="828" alt="Screenshot from 2025-07-31 12-03-37" src="https://gist.github.com/user-attachments/assets/77368546-4717-43a8-97e3-8c4c5be2cc5e" />
<img width="1140" height="827" alt="Screenshot from 2025-07-31 12-03-08" src="https://gist.github.com/user-attachments/assets/2538066b-ee88-45b2-958a-0a690664f85a" />
<img width="1127" height="834" alt="Screenshot from 2025-07-31 12-02-37" src="https://gist.github.com/user-attachments/assets/0a0be312-08ae-465f-a23a-71ba8646cdcc" />
<img width="1127" height="835" alt="Screenshot from 2025-07-31 12-01-56" src="https://gist.github.com/user-attachments/assets/903b2050-830d-4786-b813-0524484e33ed" />
<img width="1138" height="831" alt="Screenshot from 2025-07-31 12-00-10" src="https://gist.github.com/user-attachments/assets/426f82d9-046a-47d6-905b-d1ffab283531" />

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Attempting to change Cluster Network uplink-mtu to 1450 from 1400 when nc1 is using MTU of 1400 fails $~~$</summary>

  1. When cluster network has uplink-mtu set to 1400
  2. When cluster network configuration nc1 is built and 1400 is input as cluster network confgiuration manually 
  3. When user trys to change the uplink-mtu on the cluster network to 1450 from 1400, it fails as expected because nc1 is 1400 

<img width="1149" height="840" alt="Screenshot from 2025-07-31 12-17-50" src="https://gist.github.com/user-attachments/assets/9548d3d6-48fa-4aa5-9ba3-37863edf0995" />
<img width="1152" height="826" alt="Screenshot from 2025-07-31 12-17-22" src="https://gist.github.com/user-attachments/assets/d991b2b8-0b68-4de2-b855-26e06621ab1b" />
<img width="1145" height="811" alt="Screenshot from 2025-07-31 12-16-55" src="https://gist.github.com/user-attachments/assets/d4ade28f-5ea0-4e15-b68d-6b0a8c4bace9" />

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Creating a Cluster Network with MTU of 1400, Network Configuration nc1 (target node a) w/ MTU of 1400, then trying to create Network Configuration nc2 (target node b) of MTU 1450 will fail $~~$</summary>

  1. When Cluster network testing is built
  2. testing, has mtu set to 1400
  3. inside testing cluster network: nc1 is built targeting node a, w/ mtu 1400
  4. inside testing cluster network: nc2 is built targeting node b, w/ mtu 1450, failure is observed as expected: `admission webhook "validator.harvester-system.harvester-network-webhook" denied the request: Internal error occurred: can't create vlanConfig nc2 because the vlanconfig nc2 MTU 1450 is different with another vlanconfig nc1 MTU 1400, all vlanconfigs on one clusternetwork need to have same MTU
`

<img width="1158" height="827" alt="Screenshot from 2025-07-31 13-23-04" src="https://gist.github.com/user-attachments/assets/ed97f2f0-175a-4f18-9403-98b02120ce27" />
 
 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Deleting a cluster network will fail with active network configurations $~~$</summary>

  1. When a cluster network has one or more network configurations w/ configured MTUS
  2. Attempting to delete the parent cluster network should fail
<img width="1889" height="1924" alt="Screenshot from 2025-07-31 15-13-22" src="https://gist.github.com/user-attachments/assets/299bd3bf-6c41-4e8d-8a93-83d6e8b8bb64" />

 </details>
 
 <details><summary>$\color{green}{\textsf{PASS}}$ Migrating a set MTU Network Configuration from one cluster network to the other will fail when VM is running $~~$</summary>

  1. When vm is running using the network configuration, in a vm network
  2. VM has one or more nics tied to vm network
  3. MTU Network Configuration Migration will fail when trying to move to other Cluster Network

<img width="2204" height="1924" alt="Screenshot from 2025-07-31 15-50-15" src="https://gist.github.com/user-attachments/assets/0700170d-f098-4ee2-9fbb-4667adccc24f" />


 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Attempting to delete network configuration w/ set MTU that has a VM network and a VM using that VM Network will fail $~~$</summary>

  1. When vm is running using the network configuration, in a vm network
  2. VM has one or more nics tied to vm network
  3. MTU Network Configuration will fail to delete as expected, you must stop the VM first before the vlanConfig can be deleted
<img width="2213" height="1739" alt="Screenshot from 2025-07-31 15-53-25" src="https://gist.github.com/user-attachments/assets/378dff5c-1d89-4278-a34a-4a241b5f715b" />



 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ A VM Network (NAD) that was built using a specific Cluster Network w/ set MTU plus a Network Config on that Cluster Network w/ set MTU -> when that Network Config for the Cluster Network is removed, the Cluster Network should still fail to delete because the NAD (VM Network) is still existing $~~$</summary>

  1. When a VM Network is built from a Cluster Network + Network Config (both with set MTU values)
  2. The VM Network is used in a VM
  3. The VM is powered off
  4. The Cluster Network's Network Configuration is removed
  5. The VM Network will be degraded
  6. Then attempting to delete the Cluster Network with set MTU, will fail, because the VM Network (NAD) still exists

<img width="2232" height="1963" alt="Screenshot from 2025-07-31 15-56-40" src="https://gist.github.com/user-attachments/assets/fbff7152-1bdb-4b87-8b67-caf404e032c9" />


 </details>

### MGMT Network based, not user defined

 <details><summary>$\color{green}{\textsf{PASS}}$ User can not build a VM Network (NAD) with a set MTU on MGMT Network, that is different than MGMT Network's MTU  $~~$</summary>

  1. When a mgmt nad is built like:
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: mgmt-nad-1
  annotations:
    field.cattle.io/description: mgmt nad 1
    #  key: string
  labels:
    {}
    #  key: string
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"mgmt-nad-1","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":2011,"ipam":{}, "mtu":1500}
__clone: true
```
2. then gets modified from 1500 to 1480
3. Failure is to be expected if cluster network MTU is 1500


<img width="2213" height="1943" alt="Screenshot from 2025-07-31 16-41-28" src="https://gist.github.com/user-attachments/assets/5d7640db-36e1-4a6d-a89e-0b445345839c" />


 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ VM Network (NAD) on MGMT Network, it's MTU can not be set to impproper values  $~~$</summary>

<img width="2223" height="1935" alt="Screenshot from 2025-07-31 16-47-34" src="https://gist.github.com/user-attachments/assets/e5485c07-de85-4a56-84f0-3f3bf8d91527" />
<img width="2243" height="1928" alt="Screenshot from 2025-07-31 16-46-36" src="https://gist.github.com/user-attachments/assets/1d6ce768-299d-451d-99b0-e8f84ecfb056" />
<img width="2232" height="1937" alt="Screenshot from 2025-07-31 16-45-15" src="https://gist.github.com/user-attachments/assets/a977bf59-41c6-4afa-93e9-185fc447e792" />
<img width="2285" height="1949" alt="Screenshot from 2025-07-31 16-44-39" src="https://gist.github.com/user-attachments/assets/45f17063-159b-4724-b3bc-d44d644f2ceb" />
<img width="2217" height="1939" alt="Screenshot from 2025-07-31 16-43-55" src="https://gist.github.com/user-attachments/assets/832cbe7f-151f-42dd-8b7b-de91f053ee92" />
<img width="2213" height="1943" alt="Screenshot from 2025-07-31 16-41-28" src="https://gist.github.com/user-attachments/assets/21207092-82f1-4608-a2a7-2836fd53a6eb" />



 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Modifying K9s/Kubectl (not from UI) the MGMT Network We Can Add MTU Annotation $~~$</summary>

  1. when there is a VM Network built off of MGMT Network
  2. w/ kubectl/k9s modifying the MGMT network adding the `mtu` annotation like:
```yaml
Name:         mgmt                                                                                                                                          
Namespace:                                                                                                                                                  
Labels:       <none>                                                                                                                                        
Annotations:  network.harvesterhci.io/uplink-mtu: 1400                                                                                                      
API Version:  network.harvesterhci.io/v1beta1                                                                                                               
Kind:         ClusterNetwork                                                                                                                                
Metadata:                                                                                                                                                   
  Creation Timestamp:  2025-07-29T22:56:19Z                                                                                                                 
  Finalizers:                                                                                                                                               
    wrangler.cattle.io/harvester-network-manager-cn-controller                                                                                              
  Generation:        1                                                                                                                                      
  Resource Version:  2173805                                                                                                                                
  UID:               c5624bd7-45a6-4427-b3fe-b747f32876a1                                                                                                   
Status:                                                                                                                                                     
  Conditions:                                                                                                                                               
    Last Update Time:  2025-07-29T22:56:19Z                                                                                                                 
    Status:            True                                                                                                                                 
    Type:              ready                                                                                                                                
Events:                <none>                                                                                                                              
                                       
```
  3. the corresponding vm network (nad) built off of the MGMT cluster network will see the MTU value present

<img width="2217" height="1924" alt="Screenshot from 2025-07-31 17-04-24" src="https://gist.github.com/user-attachments/assets/4d1618b5-aafc-435a-b764-826779bbee0b" />

 </details>

### VlanConfig

 <details><summary>$\color{green}{\textsf{PASS}}$ Create (pending other issue, passing... overlap likely expected behavior) $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Update Passing $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336
<img width="1581" height="1004" alt="Screenshot from 2025-08-04 17-22-30" src="https://gist.github.com/user-attachments/assets/585a1924-6ed9-45ca-8acb-434be0b1a2f1" />
<img width="2654" height="1932" alt="Screenshot from 2025-08-04 17-12-20" src="https://gist.github.com/user-attachments/assets/ff85419f-7920-4ae7-b6ba-2c78f3d5fc4f" />
<img width="2696" height="1943" alt="Screenshot from 2025-08-04 17-11-16" src="https://gist.github.com/user-attachments/assets/efb2b9ef-94e5-40b2-b7b4-b1b84500cdce" />
<img width="2686" height="1931" alt="Screenshot from 2025-08-04 17-10-25" src="https://gist.github.com/user-attachments/assets/0ceb27c2-9099-41e2-9c4d-2eed805cd614" />
<img width="2688" height="1952" alt="Screenshot from 2025-08-04 17-09-11" src="https://gist.github.com/user-attachments/assets/ded0badc-6d68-4120-ac17-3d63d0fc8921" />
<img width="2712" height="1953" alt="Screenshot from 2025-08-04 17-05-03" src="https://gist.github.com/user-attachments/assets/2069683f-84d0-4500-85b0-df040ddf071b" />
<img width="2680" height="1946" alt="Screenshot from 2025-08-04 16-58-47" src="https://gist.github.com/user-attachments/assets/dbb45097-cc8b-49d6-8830-e699c02e9060" />
<img width="1119" height="221" alt="Screenshot from 2025-08-04 17-32-17" src="https://gist.github.com/user-attachments/assets/f7ad4076-23cc-493c-8f70-d3f6302f35fd" />
<img width="2688" height="1935" alt="Screenshot from 2025-08-04 17-28-50" src="https://gist.github.com/user-attachments/assets/9f7bd0b1-dc29-4c62-a266-49c2c8934bf2" />


 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Delete $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

<img width="2692" height="1945" alt="Screenshot from 2025-08-04 17-46-15" src="https://gist.github.com/user-attachments/assets/17c1763f-a34a-4546-9239-eeaed783c86d" />


 </details>

### NAD

 <details><summary>$\color{green}{\textsf{PASS}}$ Create $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

<img width="1134" height="932" alt="Screenshot from 2025-08-04 17-54-46" src="https://gist.github.com/user-attachments/assets/1cc30b9e-255b-4554-a816-6fa9718fbbf6" />
<img width="1516" height="894" alt="Screenshot from 2025-08-04 17-51-09" src="https://gist.github.com/user-attachments/assets/6487d944-01b0-4f1e-ba45-3e32607dfc1f" />

 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Update (mostly all, noting still elements with: https://www.github.com/harvester/harvester/issues/8788#issuecomment-3152942073 ) $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

<img width="1149" height="1973" alt="Screenshot from 2025-08-04 18-08-58" src="https://gist.github.com/user-attachments/assets/a0873d65-b878-40c3-bd24-04984774f007" />
<img width="2700" height="922" alt="Screenshot from 2025-08-04 18-06-10" src="https://gist.github.com/user-attachments/assets/b8c2bcd2-b9a6-41c7-b6bf-76c73072e852" />
<img width="2682" height="935" alt="Screenshot from 2025-08-04 18-04-48" src="https://gist.github.com/user-attachments/assets/55c77381-5592-4125-b401-ae3bddf410aa" />
<img width="1546" height="894" alt="Screenshot from 2025-08-04 18-03-01" src="https://gist.github.com/user-attachments/assets/4fecf711-c7cb-4b0d-bcc7-ff6caa2fec74" />


 </details>

 <details><summary>$\color{green}{\textsf{PASS}}$ Delete $~~$</summary>

  1. https://www.github.com/harvester/network-controller-harvester/pull/149#issuecomment-2697974336

<img width="1546" height="1266" alt="Screenshot from 2025-08-04 18-31-50" src="https://gist.github.com/user-attachments/assets/4cfa2df0-48fe-4ed6-9fa1-cec39a9bc62c" />
<img width="1553" height="1272" alt="Screenshot from 2025-08-04 18-31-31" src="https://gist.github.com/user-attachments/assets/538a0cea-8533-4a4b-9b63-855ba7c018d2" />
<img width="1527" height="872" alt="Screenshot from 2025-08-04 18-21-25" src="https://gist.github.com/user-attachments/assets/aa8ff661-e079-472e-97f1-78212cb78442" />
<img width="1534" height="875" alt="Screenshot from 2025-08-04 18-21-04" src="https://gist.github.com/user-attachments/assets/1cfe548d-1420-4554-b888-2bf670139803" />


 </details>

(original [gist](https://gist.github.com/irishgordo/ccd214817c040453e732d70df5ee034f) where pictures render cleaner)
