### ISSUE TITLE
[BUG] Harvester load balancer controller matches wrong IP pool

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#4372]
**Describe the bug**

The harvester load balancer LB1 has the annotations as follows.
```
    loadbalancer.harvesterhci.io/namespace: default
    loadbalancer.harvesterhci.io/network: ""
    loadbalancer.harvesterhci.io/project: c-m-7977dtdj/p-wh6j8
```
There are two IP pools as below.
```
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  labels:
    loadbalancer.harvesterhci.io/global-ip-pool: "false"
    loadbalancer.harvesterhci.io/vid: "0"
  name: default
spec:
  ranges:
  - subnet: 172.19.110.192/27
  selector:
    scope:
    - guestCluster: '*'
      namespace: default
      project: '*'
---
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  labels:
    loadbalancer.harvesterhci.io/global-ip-pool: "true"
    loadbalancer.harvesterhci.io/vid: "0"
  name: global
spec:
  ranges:
  - subnet: 172.19.111.192/27
  selector:
    scope:
    - guestCluster: '*'
      namespace: '*'
      project: '*'
```

According to the IP pool matching rules, the Harvester load balancer controller will assign an IP for LB1 from the IP pool `default`, but it assigns an IP from the IP pool `global` and display the selected pool is `default`.
```
status:
  address: 172.19.111.194
  allocatedAddress:
    ip: 172.19.111.194
    ipPool: default
```

**To Reproduce**
1. Spin up a Harvester v1.1.2 and a guest cluster in default namespace with Harvester cloud provider
2. Set vip-pools.
    
<img width="1527" alt="image" src="https://github.com/harvester/harvester/assets/7421463/63c665f0-fd98-42e5-a71f-2018e18bacc5">

3. Create a service with pool ipam mode.
4. Upgrade Harvester to v1.2.0-rc4

**Expected behavior**

Harvester load balancer controller must follow the [selection policy](https://github.com/harvester/docs/blob/391962928dfec6eaec4f37c7e14752a3baac963f/docs/networking/ippool.md#selection-policy) and display the right LB status.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.2 to v1.2.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**
