### ISSUE TITLE
[ENHANCEMENT] Add some checking mechanism for the single replica volume

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4467]
**Is your enhancement related to a problem? Please describe.**
In some specific environments, we will upgrade with the single replica volume.
That will cause the draining to hang with this volume (single replica volume).

**Describe the solution you'd like**
We could add some checking mechanisms on the harvester webhook.
Then, let the user know the potential risk before the upgrade.

**Describe alternatives you've considered**
Add the document for the upgrade.

**Additional context**
None

**Comment by starbops** [comment]
We're going to add the corresponding check in the upgrade helper script first, and will eventually implement the check in the harvester-webhook before users initiate the upgrade.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.3.0-rc1` (24/01/25). Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Confirm the message of single replica volume exists on vm when trying to upgrade $~~$</summary>

When we trigger the upgrade button while a single replicas exists on vm, it would prompt the error message to prevent to procedd
  ```
  admission webhook "validator.harvesterhci.io" denied the request: The backing volumes of the following PVCs have single replica configured, please consider shutdown the corresponding workload before upgrade: default/test-vm-disk-0-tabep
  ```
  ![image](https://github.com/harvester/harvester/assets/29251855/fd8e654c-482f-43e1-b682-f202921a9e12)

 </details>

### Test Information
* Test Environment: 3 nodes harvester on remote kvm machines
* Harvester version: `v1.3.0-rc1` (24/01/25)

### Verify Steps
<details><summary> Confirm the message of single replica volume exists on vm when trying to upgrade </summary>

1. Prepare a Harvester cluster with 2+ nodes (installed with the version including the commit of this PR)
2. Create a new VM, say, `test-vm`
3. Shutdown the newly created VM
4. Find the LH volume of the VM and adjust its replica count in the field `.spec.numberOfReplicas` to 1
  ```
  harvester-node-0:~ # kubectl get volumes -A
  NAMESPACE         NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE               AGE
  longhorn-system   pvc-c645dca6-268c-44c1-8f64-73aee7a17216   v1            attached   healthy                  10737418240   harvester-node-2   3m9s
  harvester-node-0:~ # kubectl edit volume pvc-c645dca6-268c-44c1-8f64-73aee7a17216 -n longhorn-system
  volume.longhorn.io/pvc-c645dca6-268c-44c1-8f64-73aee7a17216 edited
  ```
  
  
  ```
  spec:
    Standby: false
    accessMode: rwx
    backendStoreDriver: ""
    backingImage: default-image-v2kfc
    backupCompressionMethod: lz4
    dataEngine: v1
    dataLocality: disabled
    dataSource: ""
    disableFrontend: false
    diskSelector: []
    encrypted: false
    engineImage: ""
    fromBackup: ""
    frontend: blockdev
    image: longhornio/longhorn-engine:v1.6.0-rc2
    lastAttachedBy: ""
    migratable: true
    migrationNodeID: ""
    nodeID: harvester-node-2
    nodeSelector: []
    numberOfReplicas: 1
    offlineReplicaRebuilding: disabled
    replicaAutoBalance: ignored
    replicaDiskSoftAntiAffinity: ignored
    replicaSoftAntiAffinity: ignored
    replicaZoneSoftAntiAffinity: ignored
  ```
5. Start the VM
6. Create the v1.3.0-rc1 version CR 
  ```
  curl https://releases.rancher.com/harvester/v1.3.0-rc1/version.yaml -o version.yaml
  ```
7. When kick off the upgrade by clicking the "Upgrade" button, would prompt the webhook error message to prevent to proceed.  

</details>
