### ISSUE TITLE
[BUG] The status of system-upgrade-controller is not updated actively in Rancher

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4525]
**Describe the bug**

One Harvester cluster is upgrading from v1.1.2 to v1.2.0, and it stucks in starting the NODE upgrade.

![image](https://github.com/harvester/harvester/assets/31133476/032b517e-38ff-45e8-a645-f89c3073e1ef)

From the log/yaml, we observed:
(1) 3 Rancher related objects have such error:
```
namespaced/fleet-local/cluster.x-k8s.io/v1beta1/clusters.yaml:      message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting
namespaced/fleet-local/rke.cattle.io/v1/rkecontrolplanes.yaml:      message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting
namespaced/fleet-local/provisioning.cattle.io/v1/clusters.yaml:      message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting
namespaced/fleet-local/provisioning.cattle.io/v1/clusters.yaml:      message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting
namespaced/fleet-local/provisioning.cattle.io/v1/clusters.yaml:      message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting


e.g. Cluster CR:

  - lastUpdateTime: "2023-09-12T10:23:32Z"                                                                                                  
    message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting                                                      
      for system-upgrade-controller bundle roll out'                                                                                        
    reason: Waiting                                                                                                                         
    status: Unknown                                                                                                                         
    type: Provisioned                                                                                                                       
  - lastUpdateTime: "2023-09-12T10:23:32Z"                                                                                                  
    message: 'waiting for system-upgrade-controller helm chart reconciliation: waiting                                                      
      for system-upgrade-controller bundle roll out'                                                                                        
    reason: Waiting                                                                                                                         
    status: Unknown                                                                                                                         
    type: Updated
It can’t go further until they are ready.
```

(2) But the `system-upgrade-controller` was already rolled out, the `bundle` shows:
```
from : ./namespaced/fleet-local/fleet.cattle.io/v1alpha1/bundles.yaml
- apiVersion: fleet.cattle.io/v1alpha1
  kind: Bundle

    name: mcc-local-managed-system-upgrade-controller
    namespace: fleet-local
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      blockOwnerDeletion: true
      controller: true
      kind: ManagedChart
      name: local-managed-system-upgrade-controller
      uid: 83e16fbe-0a84-40b3-a8f4-63acf6fd529e
...
  status:
    conditions:
    - lastUpdateTime: "2023-09-12T10:23:34Z"
      status: "True"
      type: Ready
    - lastUpdateTime: "2023-09-12T10:23:34Z"
      status: "True"
      type: Processed
    display:
      readyClusters: 1/1
    maxNew: 50
    maxUnavailable: 1
    maxUnavailablePartitions: 0
    observedGeneration: 6
    partitions:
    - count: 1
      maxUnavailable: 1
      name: All
      summary:
        desiredReady: 1
        ready: 1
    summary:
      desiredReady: 1
      ready: 1
    unavailable: 0
    unavailablePartitions: 0
```
and the POD logs also looked OK.

note the time gap:
```
bundle: lastUpdateTime: "2023-09-12T10:23:34Z"

rancher objects: lastUpdateTime: "2023-09-12T10:23:32Z"  
```

(3) After check the code, we suspect this commit:
https://github.com/rancher/rancher/commit/4097e8bb454ba0542d1d5df713f4e22eb416a5a6

```
// syncSystemUpgradeControllerStatus queries the managed system-upgrade-controller chart and determines if it is properly configured for a given
// version of Kubernetes. It applies a condition onto the control-plane object to be used by the planner when handling Kubernetes upgrades.
func (h *handler) syncSystemUpgradeControllerStatus(obj *rkev1.RKEControlPlane, status rkev1.RKEControlPlaneStatus) (rkev1.RKEControlPlaneStatus, error) {
```

could have a bug: 

> it cann't actively update the system-upgrade-controller's bundle status , as it is not base on bundle's change, but on rkecontroleplane's  change, which causes the upgrade stuck currently:  the suc is ready, but rancher does not think so

(4) The upgrade `plan` object looked normal, it was waiting the `system-upgrade-controller` to trigger further node upgrade plan. But even replaced the `system-upgrade-controller`, still had no luck.

```
:~ # kubectl -n cattle-system get plan hvst-upgrade-pxw5j-prepare -o yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  creationTimestamp: "2023-09-11T15:01:55Z"
  generation: 1
  labels:
    harvesterhci.io/upgrade: hvst-upgrade-pxw5j
    harvesterhci.io/upgradeComponent: node
..
  name: hvst-upgrade-pxw5j-prepare
  namespace: cattle-system
  resourceVersion: "81709373"
  uid: 42a372d0-0491-462d-a8c0-f4122c098351
spec:
  concurrency: 1
  nodeSelector:
    matchLabels:
      harvesterhci.io/managed: "true"
  serviceAccountName: system-upgrade-controller
  ...
  upgrade:
    args:
    - prepare
    command:
    - do_upgrade_node.sh
    envs:
    - name: HARVESTER_UPGRADE_NAME
      value: hvst-upgrade-pxw5j
    image: rancher/harvester-upgrade:v1.1.2
  version: hvst-upgrade-pxw5j
status:
  conditions:
  - lastUpdateTime: "2023-09-13T06:58:52Z"
    reason: Version
    status: "True"
    type: LatestResolved
  - lastUpdateTime: "2023-09-13T06:58:52Z"
    reason: PlanIsValid
    status: "True"
    type: Validated
  latestHash: 0524853b1b7848a67d3c08ced99da2d33db7471efa9d3d14af84578a
  latestVersion: hvst-upgrade-pxw5j
```  

**To Reproduce**

Have chance to reproduce.

**Expected behavior**

Upgrade successfully.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.1.2 -> v1.2.0 upgrade
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare-metal servers

**Additional context**

Observed after the workaround against issue https://github.com/harvester/harvester/issues/4519

**Comment by w13915984028** [comment]
Following updates:

(1) RKEControlPlane get `SystemUpgradeControllerReady` at 2023-09-12T20:14:18Z, and then, the new error: 

```
 - lastUpdateTime: "2023-09-12T20:14:18Z"
  message: 'configuring bootstrap node(s) custom-18f4ec0eb29e: waiting for probes:
   kube-controller-manager, kube-scheduler'
```

```
susemanager:~ # kubectl get rkecontrolplanes.rke.cattle.io -n fleet-local local -oyaml
apiVersion: rke.cattle.io/v1
kind: RKEControlPlane
metadata:
...
 conditions:
 - lastUpdateTime: "2022-06-30T08:42:54Z"
  status: "True"
  type: Provisioned
 - lastUpdateTime: "2023-09-12T20:14:18Z"
  message: 'configuring bootstrap node(s) custom-18f4ec0eb29e: waiting for probes:
   kube-controller-manager, kube-scheduler'
  reason: Waiting
  status: Unknown
  type: Ready
 - lastUpdateTime: "2023-09-11T15:52:20Z"
  message: RKEControlPlane has not been fully reconciled yet
  reason: Waiting
  status: Unknown
  type: Reconciled
 - lastUpdateTime: "2023-09-11T15:52:20Z"
  status: "True"
  type: Bootstrapped
 - lastUpdateTime: "2023-09-12T20:14:18Z"
  message: eyJQc3BFbmFibGVkIjpmYWxzZX0=
  status: "True"
  type: SystemUpgradeControllerReady
 initialized: true
 observedGeneration: 18
 ready: true
 ```
 
 (2) The POD `rancher-system-agent`  log:

>Sep 13 11:56:37 harvester2 systemd[1]: Started Rancher System Agent.
Sep 13 11:56:38 harvester2 rancher-system-agent[22342]: time="2023-09-13T11:56:38Z" level=info msg="Rancher System Agent version v0.3.3 (9e827a5) is starting"
Sep 13 11:56:38 harvester2 rancher-system-agent[22342]: time="2023-09-13T11:56:38Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Sep 13 11:56:38 harvester2 rancher-system-agent[22342]: time="2023-09-13T11:56:38Z" level=info msg="Starting remote watch of plans"
Sep 13 11:56:38 harvester2 rancher-system-agent[22342]: time="2023-09-13T11:56:38Z" level=fatal msg="error while connecting to Kubernetes cluster: Get \"https://192.168.0.34/version\": x509: cannot validate certificate for 192.168.0.34 because it doesn't contain any IP SANs"
