### ISSUE TITLE
[Question] Expected Behaviour with Rancher addon

### ISSUE THREAD

**Issue by devclef** [harvester/harvester#4533]
Hi,

A question, then perhaps a suggestion to update docs (which happy to try to help do :)). I included what I think is the answer.

Assumption:
Harvester node that is not currently managed by rancher. -- Cluster reg url is empty.
One enables the expiremental rancher addon.

1.) Does one still provision the cluster as if it was an external rancher (Add harvester to virtualization section of rancher)
Answer: I believe Yes. Without this, nothing happens.

2.) If you have harvester.your.domain, and then set rancher.your.domain within the addon configuration. Both should point to the same IP address (Per Docs). Should both URLs continue to  be accessible?

**Answer**: I've observed two situations. At one point I had both harvester.your.domain(Taking me to the normal harvester page). As well Rancher.your.domain took me to rancher. But somehow, 'magically', one morning harvester.my.domain stopped working and only rancher.your.domian worked. To access harvester you went via the virtualization manage page.

_comment_:Checking ingress on the harvester internal cluster I belive you see a difference in ingress. When both 'work', you have 2 entries. a / and a ranchevr-vcluster. When only one worked, I think only a single ingress existed. -- I did not file a bug as I was doing allot of triage on other issues and unclear if I introduced a strange state or had a I actually achieved the intended state.. :)

3.) If any clear 'Dos/Don'ts when looking at normal rancher docs. Should one still use cert-manager to manage the rancher. Should one reconfigure values.yaml and upgrade helm, etc. -- And if not, how should one address the certs of the rancher manager addon, or should one ignore them? 

**Answer**: I don't know. I managed to mess up allot of cert stuff and/or in my attempt to work with some of the SSL fleet agent bugs I made things worse :) Which led me to documentation and I found myself unclear when to follow generic rancher guides or if somethings were meant to be 'ignored'. 

4.) A guide on the certification interplay be nice. 

- When you set certs in SSL settings of harvester, is this also propogating to the rancher addon? 
- Which certs should one 'manage' and which should be left to the inner stack.  

Perhaps I just did something odd, but i've spent allot of the week trying to reverse this and understand this relationship as I found myself with incorrect certs/CAs and ultimately 'corrupted' one of my guest clusters and could not seemingly get a new kubeconfig generated. Again I probably induced this by fiddling with things I should not of -- Still learning the inner complexities of kubernetes.  The harvester+rancher+guest cluster is quite a sandwhich of multiple kubernetes, and ranchers before you even add your first cluster :)

Thank you for a great product/stack!

(If this is incorrect way to propose/ask this, feel free to reject. Just thought after spending a week of trying to setup a fresh harvester+rancher-addon was worth sharing questions/docs that of helped 'me'. Perhaps the answer is I just need to understand kubernetes better :) )

**Comment by ER-EPR** [comment]
@slackspace-io 
1.YES

2.Both works，if one of them stop working perhaps there is something wrong with the ingress setting.

3.the vcluster addon first install a cert-manager for rancher, and default setting is to use rancher private CA to sign a SSL certificate. several hours after you install the vcluster, the SSL cert will be active for rancher.

4.1"When you set certs in SSL settings of harvester, is this also propogating to the rancher addon?"
Yes, the rancher-vcluster will user SSL from harvester for a while, but after the cert-manager issue the new SSL according to the rancher setting, it will change the certificate in a few hours, or at a certain time, I haven't dig into the exact mechanisms, but it will first use the existing harvester SSL and change to a new SSL later. 

4.2I spend 3 days to make the let's encrypt SSL using DNS01 challenge to work for the rancher-vcluster, by editing the yaml of the rancher-vcluster addon. It is finally working but I have to add a credential secret after the creation of the vcluster, because the init script for secret i wrote in the vcluster yaml hasn't been successful. But it will work, just a little manual effort needed.
You can see the init script in the rancher-vcluster yaml by click on the three dot to the right of this add-on, and click edit yaml.
Scroll down to the bottom you will see something like this, but "ingress.tls.source" is default to rancher which by the rancker documents will init a private CA to sign a SSL for rancher using cert-manager. What I edited is to use a DNS01 challenge to issue a let's encrypt SSL certificate using a issuer I preconfigured, which named letsencrypt-prod. 
```
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/stable/
          chart: rancher
          version: {{ .Values.rancherVersion }}
          set:
            ingress.tls.source: secret
            ingress.extraAnnotations.cert-manager\.io/cluster-issuer: letsencrypt-prod
            hostname: {{ .Values.hostname }}
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: {{ .Values.bootstrapPassword }}
          helmVersion: v3
```
