### ISSUE TITLE
[BUG] Sending ctrl-alt-delete does not have any reaction on a windows VM

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#4535]
**Describe the bug**
Here we do not have any reaction:

![grafik](https://github.com/harvester/harvester/assets/13362573/3154e6fe-9f42-4cc7-a503-87b8af1a62ec)

**To Reproduce**
Have a windows 2022 VM and try to send ctrl-alt-del

**Expected behavior**
ctrl-alt-del is received and we can login

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): not relevant
 - Browser: Firefox 117.0 on Mac (M1)

**Additional context**
Workaround on Mac: use control+option+delete on the keyboard

**Comment by joshfranzen** [comment]
Same issue here running on Harvester 1.2.0

here is the VM config:

```
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
        harvesterhci.io/waitForLeaseInterfaceNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/creator: terraform-provider-harvester
        harvesterhci.io/vmName: d-n-win-image
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: harvesterhci.io/creator
                      operator: Exists
                topologyKey: kubernetes.io/hostname
              weight: 100
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: cdrom-disk
              cdrom:
                bus: sata
              bootOrder: 1
            - name: osdisk
              disk:
                bus: sata
              bootOrder: 2
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - masquerade: {}
              macAddress: 52:54:00:e1:5c:be
              model: e1000
              name: nic-1
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        machine:
          type: q35
        memory:
          guest: 1948Mi
        resources:
          limits:
            cpu: '4'
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1365Mi
      evictionStrategy: LiveMigrate
      hostname: d-n-win-image
      networks:
        - name: nic-1
          pod: {}
      terminationGracePeriodSeconds: 120
      volumes:
        - name: cdrom-disk
          persistentVolumeClaim:
            claimName: d-n-win-image-cdrom-disk-cpfhh
        - name: osdisk
          persistentVolumeClaim:
            claimName: d-n-win-image-osdisk-bphjg
```
