### ISSUE TITLE
Inconsistent kernel driver unbinding leaves some devices bound to vfio-pci

### ISSUE THREAD

**Issue by staedter** [harvester/harvester#4562]
#### Summary:
When enabling or disabling PCI passthrough on bulk via the Harvester GUI, there appears to be an inconsistency in the 'KERNEL DRIVER TO UNBIND' for PCI device claims. This inconsistency results in devices being left bound to the wrong driver upon disabling passthrough.

#### Steps to Reproduce:
1. Navigate to the Harvester GUI.
2. Select multiple PCI devices.
3. Enable/disable passthrough in bulk.
4. `kubectl get pcideviceclaim` 
5. Verify the inconsistencies in the 'KERNEL DRIVER TO UNBIND' of the pci-deviceclaims

#### Expected Results:
- All selected devices should be correctly bound or unbound to/from the vfio-pci driver based on the user's selection in the Harvester GUI.

#### Actual Results:
- Some devices remain bound to the vfio-pci driver, even when passthrough is disabled in the GUI.

#### Details:
The issue manifests in the following ways:

1. Inconsistent 'KERNEL DRIVER TO UNBIND' in PCI Device Claim: When enabling or disabling PCI passthrough on bulk, the 'KERNEL DRIVER TO UNBIND' for PCI device claims is set inconsistently. This leads to the wrong driver binding, with some devices remaining bound to the vfio-pci driver while they should have been unbound.
2. Inconsistent Unbinding from vfio-pci Driver: Despite being disabled for passthrough in the GUI, some devices remain listed under /sys/bus/pci/drivers/vfio-pci/, indicating an issue with unbinding devices from the vfio-pci driver.

#### Environment:
- Harvester version: 1.1.2

##### Enabled on bulk
![image](https://github.com/harvester/pcidevices/assets/46670623/46446d40-ee85-4cd4-9528-019a265ab092)

![image](https://github.com/harvester/pcidevices/assets/46670623/f24bc6f1-486c-427e-acec-70e2bf95a2d3)

##### Disabled on bulk
![image](https://github.com/harvester/pcidevices/assets/46670623/b1867147-0d61-4cd6-a5d9-3fa35bf4af77)
![image](https://github.com/harvester/pcidevices/assets/46670623/4ac70a29-f11f-47ae-844d-2bb573ecaaa7)

**Comment by staedter** [comment]
At @ibrokethecloud suggestion in the harvester user slack I already tried using the latest pcidevices-addon version 0.2.5 from https://github.com/harvester/charts/releases/download/harvester-pcidevices-controller-0.2.5/harvester-pcidevices-controller-0.2.5.tgz

But the issues keep persisting. And for some of the passthrough-enabled devices it is not possible to create VMs with those drives attached.

![image](https://github.com/harvester/pcidevices/assets/46670623/e670acc4-eafa-441e-9e76-684bc4dc36ba)

I have send a support-bundle to @ibrokethecloud but please let me know if there is any more information you need to debug the issue.

Thank you in advance

**Comment by ibrokethecloud** [comment]
hi @staedter thanks for the support bundle. I had a quick look at it and can see that the pcideviceclaim seems setup correctly:

```
apiVersion: devices.harvesterhci.io/v1beta1
kind: PCIDeviceClaim
metadata:
  annotations:
    sim.harvesterhci.io/creationTimestamp: "2023-08-29T10:12:35Z"
  creationTimestamp: "2023-08-29T10:12:35Z"
  finalizers:
  - wrangler.cattle.io/PCIDeviceClaimOnRemove
  generation: 1
  name: haa-devops-harvester01-host03-000082000
  ownerReferences:
  - apiVersion: devices.harvesterhci.io/v1beta1
    kind: PCIDevice
    name: haa-devops-harvester01-host03-000082000
    uid: 327b5a68-34a0-4b88-a89c-bb205fd32e16
  resourceVersion: "589"
  uid: 040a15b0-854a-4960-bd4b-68022bbb9b4d
spec:
  address: 0000:82:00.0
  nodeName: haa-devops-harvester01-host03
  userName: admin
status:
  kernelDriverToUnbind: vfio-pci
  passthroughEnabled: true
```

```
2023-08-29T10:12:35.384251808Z time="2023-08-29T10:12:35Z" level=info msg="Enabling passthrough for PDC: haa-devops-harvester01-host03-000082000"
2023-08-29T10:12:35.384315210Z time="2023-08-29T10:12:35Z" level=info msg="Binding device haa-devops-harvester01-host03-000082000 [1b96 2400] to vfio-pci"
2023-08-29T10:12:35.384327043Z time="2023-08-29T10:12:35Z" level=info msg="Binding device 0000:82:00.0 vfio-pci"
```

the device plugin seems to have updated the node status:

```
allocatable:
  cpu: "128"
  devices.kubevirt.io/kvm: 1k
  devices.kubevirt.io/tun: 1k
  devices.kubevirt.io/vhost-net: 1k
  ephemeral-storage: "3567118004294"
  hugepages-1Gi: "0"
  hugepages-2Mi: "0"
  memory: 1056627872Ki
  pods: "110"
  western.com/ULTRASTAR_DC_SN640_NVME_SSD: "3"
capacity:
  cpu: "128"
  devices.kubevirt.io/kvm: 1k
  devices.kubevirt.io/tun: 1k
  devices.kubevirt.io/vhost-net: 1k
  ephemeral-storage: 3666856504Ki
  hugepages-1Gi: "0"
  hugepages-2Mi: "0"
  memory: 1056627872Ki
  pods: "110"
  western.com/ULTRASTAR_DC_SN640_NVME_SSD: "4"
```

I assume the node has 4 disks, of which 1 is already in use.

I also see nothing obvious in the nodes kernel logs.

The current support bundle does not have the info about the launcher pods. Any chance we could have another support bundle with the info from additional namespaces included: https://docs.harvesterhci.io/dev/advanced/settings#support-bundle-namespaces
