### ISSUE TITLE
[BUG] Can't backup VMs with volumes created with Containerized Data Importer

### ISSUE THREAD

**Issue by andyrue** [harvester/harvester#4575]
**Describe the bug**
I have installed the KubeVirt CDI so I can persist ContainerDisks in VMs. When I create a VirtualMachine with `dataVolumeTemplate` the volume is created properly and the VM works as intended, but in the Harvester UI the Volume doesn't show that it is attached to a VM and the associated VM doesn't show that it has any Volumes. A side effect I'm experiencing seems to be I can't take any Backups of the VM. How can I resolve this? 

**To Reproduce**
1. Install the KubeVirt CDI
2. Create a VM using a manifest with a `dataVolumeTemplates` spec (sample below)
3. Observe the Volumes show no VM attached and the VM shows no Volumes.

**Expected behavior**
Volumes should show as being attached to the appropriate VM and vice versa.

**Support bundle**
Bundle too big to attach, but can be found in the related Slack thread.
https://rancher-users.slack.com/archives/C01GKHKAG0K/p1695815435730789

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**

Manifest

```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k8s-control1
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
  - metadata:
      name: k8s-control1-volume
    spec:
      storage:
        volumeMode: Block
        resources:
          requests:
            storage: 20Gi
        accessModes:
          - ReadWriteMany
      source:
        registry:
          url: "docker://quay.io/fedora/fedora-coreos-kubevirt:stable"
  template:
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: k8s-control1-root
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
          interfaces:
            - bridge: {}
              model: virtio
              name: nic-0
        machine:
          type: q35
        memory:
          guest: 3996Mi
        resources:
          limits:
            cpu: '4'
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 2730Mi
      evictionStrategy: LiveMigrate
      hostname: k8s-control1
      networks:
        - multus:
            networkName: k8s
          name: nic-0
      volumes:
      - dataVolume:
          name: k8s-control1-volume
        name: k8s-control1-root
      - cloudInitConfigDrive:
          secretRef:
            name: k8s-control1-ignition
        name: cloudinitdisk
      

```
