### ISSUE TITLE
[BUG] Node pool anti-affinity rules are not working as expected

### ISSUE THREAD

**Issue by berkitamas** [harvester/harvester#4588]
**Describe the bug**
In the Harvester version v1.2.0, it is possible to set up anti-affinity rules. It is a useful feature for creating pools which are AZ-aware and highly available. Unfortunately it doesn't work as expected. In the anti-affinity rule page a person is able to define the topology key and the rules.
The topology key must match a label of the node and the **rule must match a label of the virtual machine pod**. It is not possible to add/remove/update the Pod labels (at least on GUI level, I have not looked on API level as the `kubectl explain` throws a big nothing).
By default we have the following labels:
- harvesterhci.io/creator
  - same for all VMs
  - useless for scheduling
- harvesterhci.io/vmName
  - unique for all VMs
  - useless for scheduling

It is possible to specify Kubernetes node labels for the pool but it is only set on guest cluster level, it is not propagated upwards as a VM Pod label.

**To Reproduce**
Create a 3 node pool with the following anti-affinity parameters:
![image](https://github.com/harvester/harvester/assets/6505186/9c993f9e-6cfd-4291-ac5b-0c7c18b7a645)
It will produce the following anti-affinity configuration for the VM:
```yaml
spec:
  affinity:
    nodeAffinity:
      # Default affinity rules
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: foo
                operator: In
                values:
                  - bar
          topologyKey: topology.kubernetes.io/zone
```
Outcome:
The three node pool will not care about the anti affinity rule.
For 100% reproducibility test it on a three node Harvester environment, where one of the node is in cordoned state.

**Expected behavior**
In a three node Harvester environment all the node should be on a unique hypervisor. In case one Harvester node is in cordoned state, one of the three VM must not start.

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Some of the possible solutions:
- It is possible to specify labels on VM level
  - Might raise security issues
- Have more meaningful labels by default
  - Name of the pool, name of the cluster

**Comment by ibrokethecloud** [comment]
### To verify this change:

* Build a compile `docker-machine-driver-harvester` by running `make`
* Copy the `docker-machine-driver-harvester` binary to an existing rancher installation. This can be done by copying the binary to `/usr/share/rancher/ui/assets/docker-machine-driver-harvester` in the rancher pod.
```
kubectl cp docker-machine-driver-harvester $rancher-pod-name:/usr/share/rancher/ui/assets/docker-machine-driver-harvester
```
* Once the binary is copied, import a 3 node harvester cluster into rancher
* Ensure that the label `topology.kubernetes.io/zone` and a different zone value, say zone-1, zone-2, zone-3 is added to each node of the harvester cluster.
* Launch a downstream 3 Node HA cluster using rancher on this imported harvester cluster, and specify the following VM scheduling rule:
<img width="1254" alt="image" src="https://github.com/harvester/harvester/assets/19664014/d8b6f69d-30bb-4d24-a4d9-5a4445c57ae4">
* When using this new machine driver, the VM's will be spread across the three different nodes of the underlying harvester cluster.

#### Additional verification from harvester
* Each VM launched will have an additional label added.
```
  labels:
    harvesterhci.io/machineSetName: $pool-name-prefix
```
* The anti-affinity rule on the VM will leverage this label to ensure VM's are spread across in the cluster
```
podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  harvesterhci.io/machineSetName: $pool-name-prefix
              topologyKey: kubernetes.io/hostname
            weight: 1
```
