### ISSUE TITLE
The rancher-vcluster addon default rancher replicas set to 1, why? Should I change it to 3?[Question]

### ISSUE THREAD

**Issue by ER-EPR** [harvester/harvester#4596]
@ibrokethecloud  @guangbochen @bk201 
install the experimental addon rancher-vcluster. I notice the default rancher replicas is set to 1. My harvester cluster have 3 nodes. Should I change the replicas to 3? Or it's not necessary when using the vcluster.
``` 
       ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/stable/
          chart: rancher
          version: {{ .Values.rancherVersion }}
          set:
            ingress.tls.source: secret
            ingress.extraAnnotations.cert-manager\.io/cluster-issuer: letsencrypt-prod
            hostname: {{ .Values.hostname }}
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: {{ .Values.bootstrapPassword }}
          helmVersion: v3
```
