### ISSUE TITLE
[BUG] Upgrade from v1.1.2 to v1.2.1-rc1 stuck in upgrading system service, with pending rancher-monitoring pods

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4599]
**Describe the bug**

Try to upgrade the single nodes Harvester from v1.1.2 to v1.2.1-rc1, the process stuck in `Upgrading System Service` 
  ![image](https://github.com/harvester/harvester/assets/29251855/1d66079d-3bc6-4161-b560-456727a7ac58)

Check the `hvst-upgrade-qngtb-apply-manifests` job logs, it display `Waiting for 1 pods to be ready...` 

  ```
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk harvester-system           pcidevices-controller   http://harvester-cluster-repo.cattle-system.svc/charts   harvester-pcidevices-controller   fal │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk harvester-system           vm-import-controller    http://harvester-cluster-repo.cattle-system.svc/charts   harvester-vm-import-controller    fal │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk wait for rollout of monitoring                                                                                                                    │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk deployment "rancher-monitoring-operator" successfully rolled out                                                                                  │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk Waiting for deployment "rancher-monitoring-prometheus-adapter" rollout to finish: 0 of 1 updated replicas are available...                        │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk deployment "rancher-monitoring-prometheus-adapter" successfully rolled out                                                                        │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk deployment "rancher-monitoring-kube-state-metrics" successfully rolled out                                                                        │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk Waiting for deployment "rancher-monitoring-grafana" rollout to finish: 0 of 1 updated replicas are available...                                   │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk deployment "rancher-monitoring-grafana" successfully rolled out                                                                                   │
  │ hvst-upgrade-qngtb-apply-manifests-wjvsk Waiting for 1 pods to be ready...       
  
  ```

Two pods kept in pending state

- cattle-monitoring-system   alertmanager-rancher-monitoring-alertmanager-0
- cattle-monitoring-system   prometheus-rancher-monitoring-prometheus-0

![image](https://github.com/harvester/harvester/assets/29251855/0c791b2e-e3f4-4e8f-9599-1713f7f00cb6)

**To Reproduce**
1. Prepare a single node Harvester 
2. Create the vlan1 network and another external vlan network
3. Set the backup target to nfs server
4. Create a VM and keep in running state
5. Create some file and record the checksum value
6. Create a backup from the running VM
7. Create another file and record the checksum value 
8. Create a snapshot from the running VM
9. Create another vm and keep in stop state
10. Repeat step 6, 7, 8 to prepare backup and snapshot backup
11. Keep on VM in running and another in Stopped
12. Upgrade to v1.2.1-rc1

**Expected behavior**

Can upgrade the single nodes Harvester from v1.1.2 to v1.2.1 sucessfully

**Support bundle**

[supportbundle_9978bde7-4d72-434a-9031-130998856615_2023-10-11T10-20-17Z.zip](https://github.com/harvester/harvester/files/12868280/supportbundle_9978bde7-4d72-434a-9031-130998856615_2023-10-11T10-20-17Z.zip)

**Upgrade log**

[hvst-upgrade-qngtb-upgradelog-archive-2023-10-11T10-30-13Z.zip](https://github.com/harvester/harvester/files/12868292/hvst-upgrade-qngtb-upgradelog-archive-2023-10-11T10-30-13Z.zip)

**Environment**

 - Harvester ISO version: v1.1.2 to v1.2.1-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on bare machine

**Comment by w13915984028** [comment]
@TachunLin The upgrade will not stuck here, even when those 2 PODs are not deployed successfully, it will wait at most 6 minutes, and then continue following upgrade steps.

**Comment by w13915984028** [comment]
@TachunLin 

From the SB file `yamls/namespaced/cattle-monitoring-system/v1/pods.yaml`, those 2 PODs are the victims of Insufficient CPU.

```
    name: prometheus-rancher-monitoring-prometheus-0
    namespace: cattle-monitoring-system
    
  status:
    conditions:
    - lastProbeTime: "null"
      lastTransitionTime: "2023-10-11T07:34:58Z"
      message: '0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes
        are available: 1 No preemption victims found for incoming pod.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable

      time: "2023-10-11T07:34:56Z"
    name: alertmanager-rancher-monitoring-alertmanager-0
    namespace: cattle-monitoring-system
  status:
    conditions:
    - lastProbeTime: "null"
      lastTransitionTime: "2023-10-11T07:34:56Z"
      message: '0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes
        are available: 1 No preemption victims found for incoming pod.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
 ```
