### ISSUE TITLE
[BUG] Unable to upgrade from Harvester v1.1.2 to v1.2.0 because of wrong API group version in version.yaml

### ISSUE THREAD

**Issue by belgaied2** [harvester/harvester#4634]
**Describe the bug**
Harvester's upgrade to v1.2.0 does not appear in the UI in non-airgapped mode.
When trying to apply the airgapped procedure manually, I downloaded the version.yaml from [here](https://releases.rancher.com/harvester/v1.2.9/version.yaml), and I was not able to deploy because of the version in the YAML.

In the version.yaml file, the kind `Version` is associated with the group/version: `harvesterhci.io/v2beta1` which does not exist in Harvester v1.1.2. Replacing in the YAML, `v2beta1` by `v1beta1` and applying the file makes the upgrade option appear in the UI.

**To Reproduce**
Have a Harvester v1.1.2 in an environment with access to internet, and see that the upgrade to v1.2.0 never appears.

**Expected behavior**
Since the `version.yaml` exists, the upgrade option should appear.

**Support bundle**
None needed.

**Workaround**
 - Download the file `version.yaml` file from [here](https://releases.rancher.com/harvester/v1.2.9/version.yaml).
 - Modify it to change `v2beta1` to `v1beta1` 
 - Run `kubectl apply -f version.yaml` with the modified file on a management node
 - See the upgrade option appear in the UI, and proceed.

Alternatively, use this corrected content for the `version.yaml` file:
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.2.0
  namespace: harvester-system
spec:
  isoChecksum: '267d65117f6d9601383150b4e513065e673cccba86db9a8c6e7d3cb36a04f6202162f1b95c3c545a7389c4f20f82f5fff6c6e498ff74fcb61e8513992b83e1fb'
  isoURL: https://releases.rancher.com/harvester/v1.2.0/harvester-v1.2.0-amd64.iso
  releaseDate: '20230908'
```
