### ISSUE TITLE
[BUG] Show SupportBundle custom resource incorrectly

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#4643]
**Describe the bug**
When getting SupportBundle custom resource, it doesn't show right information because specifying wrong json path here https://github.com/harvester/harvester/blob/master/deploy/charts/harvester-crd/templates/harvesterhci.io_supportbundles.yaml#L23. 

**To Reproduce**

1. Create a custom resource with issueURL and description like below and create it.
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: SupportBundle
metadata:
    name: "test01"
spec:
    issueURL: "this is issueURL"
    description: "this is description"
```
2.  Execute the command `kubectl get supportbundles`
3.  `issueURL` is empty.

![image](https://github.com/harvester/harvester/assets/6960289/586a31a8-3305-4946-bf73-53e57720c4e8)

**Expected behavior**
`issueURL` shouldn't be empty.

![image](https://github.com/harvester/harvester/assets/6960289/1768713b-a99c-47f4-92a6-10f8bc39a865)

**Support bundle**
No need for this.

**Environment**
 - Harvester ISO version: v1.2.1-rc1
 - Underlying Infrastructure: Lenovo P16 G1

**Additional context**
Found from https://github.com/harvester/harvester/issues/4630#issuecomment-1772296750.
