### ISSUE TITLE
[BUG] Unable to successfully create LoadBalancer service from Guest cluster post 1.2.1 upgrade

### ISSUE THREAD

**Issue by ionfury** [harvester/harvester#4678]
**Describe the bug**
I'm unable to create a `LoadBalancer` type service successfully from a guest cluster post `1.1.2` > `1.2.1` upgrade.  The guest cluster was upgraded from `1.24.14` > `1.25.x` > `1.26.8` post harvester upgrade.  On the guest cluster, took a service that was created successfully in `1.1.2` and tried to create a renamed copy.  The ExternalIP of the new service is stuck in a pending state.

The `LoadBalancer` is created on the harvester cluster, but the status never progresses beyond the following:

``` yaml
status:
  allocatedAddress:
    ip: 0.0.0.0
```

**To Reproduce**
0. [IaC Repo](https://github.com/ionfury/homelab/tree/main/terraform/clusters/homelab-1)
1. Create single node harvester cluster `1.1.2`
2. (Via tf provider `2.0.0`) Manage with [Rancher `2.7.6`](https://github.com/ionfury/homelab/tree/main/terraform/.modules/rancher)
3. (via tf provider `2.0.0` / `0.6.2`) Create guest [rke2 cluster `v1.24.14`](https://github.com/ionfury/homelab/blob/main/terraform/clusters/homelab-1/main.tf)
4. (via UI) Upgrade harvester cluster to `1.2.1`
5. (via UI) Upgrade guest cluster to `v1.25.x`
6. (via UI) Upgrade guest cluster to `v1.26.8`
7. Attempt to create the following service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: blocky-app-2
  namespace: network
    cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 53
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    app.kubernetes.io/instance: blocky-app
    app.kubernetes.io/name: blocky-app
```

```yaml
❯ kubectl describe svc -n network blocky-app-2        ─╯
...
Events:
  Type     Reason                  Age                    From                Message
  ----     ------                  ----                   ----                -------
  Warning  SyncLoadBalancerFailed  4m47s                  service-controller  Error syncing load balancer: failed to ensure load balancer: update load balancer IP of service network/blocky-app-2 failed, error: Operation cannot be fulfilled on services "blocky-app-2": the object has been modified; please apply your changes to the latest version and try again
  Normal   EnsuringLoadBalancer    4m41s (x3 over 4m48s)  service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer     4m41s (x2 over 4m41s)  service-controller  Ensured load balancer
```

(In the harvester cluster:)
```yaml
❯ kubectl get loadbalancer kubernetes-network-blocky-app-2-36cc76c5 -o yaml      ─╯
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: LoadBalancer
metadata:
  annotations:
    loadbalancer.harvesterhci.io/cluster: kubernetes
    loadbalancer.harvesterhci.io/namespace: default
    loadbalancer.harvesterhci.io/network: ""
    loadbalancer.harvesterhci.io/project: c-m-l48qzz2c/p-b9rb8
  creationTimestamp: "2023-10-31T03:14:39Z"
  finalizers:
  - wrangler.cattle.io/harvester-lb-controller
  generation: 2
  labels:
    cloudprovider.harvesterhci.io/cluster: kubernetes
    cloudprovider.harvesterhci.io/serviceName: blocky-app-2
    cloudprovider.harvesterhci.io/serviceNamespace: network
  name: kubernetes-network-blocky-app-2-36cc76c5
  namespace: default
  resourceVersion: "171040444"
  uid: ebd2b06b-1e63-4f46-a2d7-d1c76642f8c9
spec:
  ipam: dhcp
  workloadType: cluster
status:
  allocatedAddress:
    ip: 0.0.0.0
  conditions:
  - lastUpdateTime: "2023-10-31T03:14:39Z"
    status: "True"
    type: Ready
```

The load balancer never progresses beyond this state.  I can see no relevant logs in the harvester load balancer or harvester load balancer webhook pods.

**Expected behavior**
`blocky-app-2` service is given an ExternalIP

**Support bundle**
[supportbundle_fcbdc367-ccb7-4fd3-88eb-4503731e8766_2023-10-31T03-16-05Z.zip](https://github.com/harvester/harvester/files/13211668/supportbundle_fcbdc367-ccb7-4fd3-88eb-4503731e8766_2023-10-31T03-16-05Z.zip)

**Environment**
 - Harvester ISO version: `1.1.2` > `1.2.1`
 - Underlying Infrastructure: Baremetal r720xd

**Additional context**
The [cloud controller manager](https://github.com/harvester/cloud-provider-harvester/blob/master/pkg/cloud-controller-manager/loadbalancer.go#L210) seems to be doing what it's supposed to.  I'd expect the `LoadBalancer` manfiest to be injected with a `spec.backendServerSelector` value matching the guest cluster VMI labels, but I can't find anywhere where that would happen.  Not sure what the next step for the `LoadBalancer` is to get linked up to the guest cluster.

**Comment by ionfury** [comment]
I ended up working through this issue with the help of @starbops in a [slack thread](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1698691756114329)

The cause of the issue is that `kube-vip` was not running on the guest cluster due to taints not matching tolerations.

Kube vip tolerations:
```yaml
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
```

Control Plane taints:
```yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
```

Adding a toleration to `kube-vip` for the etcd role got it running and LB ip binding working again.

I believe this bug is caused by the `kube-vip` [helm chart/values](https://github.com/harvester/charts/blob/2d2a9321cdcbd07ce191dc9b7f30170732e66d50/charts/harvester-cloud-provider/dependency_charts/kube-vip/values.yaml#L62) not tolerating the `etcd` role.  This cluster was created via the [rancher2 terraform provider](https://github.com/ionfury/homelab/blob/dd162e9502f4cea31ccdd14b4b731bdd68683192/terraform/.modules/rancher-harvester-cluster/main.tf#L128), which should be compatible.

**Comment by devclef** [comment]
Hi, I created a bug for this a bit ago

https://github.com/harvester/harvester/issues/4538

Had the same findings, to add you only trigger this when having workers split from etcd/control from my testing. Clusters with nodes having all roles did not have this bug.


Nice to see it reproduced by someone else, started to think I had done something odd :)

**Comment by w13915984028** [comment]
connect: https://github.com/harvester/harvester/issues/4689

**Comment by Yu-Jack** [comment]
Add context from slack thread, there is a another similar way to reproduce this. 

- Create harvester (1.2.1)
- Create rancher (2.7.9)
- Create guest cluster with harvester cloud provider and two pool
  - One pool for control-plane and ETCD
  - One pool for worker
- Create load balancer type service (ref: [Harvester Cloud Provider | Harvester](https://docs.harvesterhci.io/v1.2/rancher/cloud-provider/#ipam))

**Comment by TachunLin** [comment]
Verified **fixed** on `master-804669f7-head` (24/01/19) with `cloud provider 0.2.3` on Rancher `v2.7.9`.
Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ control-plane, ETCD and worker in same pool $~~$</summary>

* Can sucessfully create LoadBalancer service on v1.26.11 RKE2 guest cluster 
![image](https://github.com/harvester/harvester/assets/29251855/0cd8887c-700f-491c-be89-747db74116ca)

* All load balance type service have assigned the EXTERNAL_IP
![image](https://github.com/harvester/harvester/assets/29251855/4cfa525b-aa08-4f35-aa95-9e3c4741163f)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ control-plane and ETCD in A pool, worker in B pool $~~$</summary>

* Can sucessfully create LoadBalancer service on v1.26.11 RKE2 guest cluster 
![image](https://github.com/harvester/harvester/assets/29251855/31c2104f-f19a-49ed-86f9-e22e058a3bb9)

* All load balance type service have assigned the EXTERNAL_IP
![image](https://github.com/harvester/harvester/assets/29251855/128f47d4-b7e3-4847-917d-767fec6cc109)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ control-plane in A pool, ETCD in B pool and worker in C pool $~~$</summary>

* Can sucessfully create LoadBalancer service on v1.26.11 RKE2 guest cluster 
![image](https://github.com/harvester/harvester/assets/29251855/c4811b51-fdd1-46b6-80c6-458d3b1f8732)

* All load balance type service have assigned the EXTERNAL_IP
![image](https://github.com/harvester/harvester/assets/29251855/e8ee7362-3b30-4c94-a96c-c5cbfe252c56)


 </details>

### Test Information
* Test Environment: Three nodes harvester on remote kvm machine
* Harvester version: `master-804669f7-head` (24/01/19)
* Rancher version: v2.7.9
* cloud provider version: `0.2.3`

### Verify Steps
<details><summary> Control-plane and ETCD in A pool, worker in B pool  </summary>

  1. Prepare three nodes Harvester and import with Rancher 
  2. Provision a RKE2 guest cluster in Rancher
  3. Create the first pool, specify the `etcd` and `control plane` roles
  
   ![image](https://github.com/harvester/harvester/assets/29251855/63889940-f51d-4b59-b335-9d63c42a6055)

  4. Create the second pool, specify the `work` role only
  
   ![image](https://github.com/harvester/harvester/assets/29251855/1dc856d4-bd6d-46d3-b67f-4bef37c2550c)

  5. Add the following cloud config in the `User Data` of each pool 
  ```
  write_files:
  - encoding: b64
    content: {harvester's kube config, the cluster namespace should be same as the pool you created (base64 enconded)}
    owner: root:root
    path: /etc/kubernetes/cloud-config
    permission: '0644'
  ```
  6. Get the Harvester kubeconfig file, remember to add the namespace (should be the same with the guest cluster)
  ```
  contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"
    namespace: "default" ---------------------> Add this line
  ```
  7. Output the Harvester kubeconfig into base64 format without new line 
  ```
  cat local.yaml | base64 -w 0
  ```
  8. Copy the base64 encoded kubeconfig to the cloud config write file sections above
  
  ![image](https://github.com/harvester/harvester/assets/29251855/08b536b7-2b46-4e13-bf0e-d4090f5e1c11)

  9. Provision the RKE2 guest cluster 
  10. After pools are created, we remove the harvester-cloud-provider in Apps > Installed Apps (kube-system namesapce).
  ![image](https://github.com/harvester/harvester/assets/29251855/381b2cb9-a69f-45e7-8d9c-93fc3f511ffe)
  11. Add new charts in Apps > Repositories, use `https://charts.harvesterhci.io` to install and select `0.2.3`.
  
  ![image](https://github.com/harvester/harvester/assets/29251855/e729d6e0-ae57-4789-aebe-cb7571765ba0)

  12. Install Harvester cloud provider 0.2.3 from market 
  
  ![image](https://github.com/harvester/harvester/assets/29251855/b681155b-0e11-4860-bc15-e0c1fdddd316)
  ![image](https://github.com/harvester/harvester/assets/29251855/7aa6e2fb-af0a-448e-86e4-03ffc4a92e3a)
  ![image](https://github.com/harvester/harvester/assets/29251855/10c5b6fe-d1a2-4274-9cd8-667b27ae7f6f)

  13. Create a nginx deployment using Harvester storage class 
  14. Create a load balancer service with dhcp type and bind to nginx deployment
  ![image](https://github.com/harvester/harvester/assets/29251855/4f5da242-cdb0-4b33-8302-3f52b9148aac)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/e2de7abe-b22b-46a8-9784-8c7b5d154351)

  15. Check can install the load balancer
  16. Create a standalone load balancer service, set the following annotation
  ```
  cloudprovider.harvesterhci.io/ipam: dhcp
  ```
  
  ![image](https://github.com/harvester/harvester/assets/29251855/1d74e851-d0d3-4f2a-ad23-3d45b0a907f4)

  17. Access to the guest cluster VM, check the load balancer service can get `EXTERNAL_IP` 

</details>

<details><summary> Control-plane in A pool, ETCD in B pool and worker in C pool </summary>

  1. Prepare three nodes Harvester and import with Rancher 
  2. Provision a RKE2 guest cluster in Rancher
  3. Create the first pool, specif the `control plane` role only
  
  ![image](https://github.com/harvester/harvester/assets/29251855/465b9fc2-643e-4624-a0d9-0c29db199ced)

  4. Create the second pool, specify the `etcd` role only
  
  ![image](https://github.com/harvester/harvester/assets/29251855/2516fd10-0be2-4199-bd7c-d18db40befd5)

  5. Create the third pool, specify the `worker` role only

  ![image](https://github.com/harvester/harvester/assets/29251855/213bca8d-040f-4dd3-8786-3758af7c9d22)

</details>

<details><summary> Control-plane, ETCD and worker in same pool </summary>

  1. Prepare three nodes Harvester and import with Rancher 
  2. Provision a RKE2 guest cluster in Rancher
  3. Create the only one pool, specif the `control plane`, `etcd` and `workers` roles 
  
  ![image](https://github.com/harvester/harvester/assets/29251855/ae4a5fa3-39bf-40d1-a038-396bac3d8b36)

</details>

**Comment by DovydasNavickas** [comment]
Not sure if this should have been fixed in 1.3.0, but I have 1.3.0 Harvester cluster with Rancher provisioned rke cluster inside and I still had this problem.
My cluster has:
`system-pool`: nodes for `etcd` and `control-plane` roles
`default-pool`: nodes for `worker` role

And `kube-vip` DaemonSet did not have a second toleration, so I had to add it via FluxCD patch:
```yaml
---
# yaml-language-server: $schema=./daemon-set-patch.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: harvester-cloud-provider
      app.kubernetes.io/name: kube-vip
  template:
    spec:
      metadata:
        labels:
          app.kubernetes.io/instance: harvester-cloud-provider
          app.kubernetes.io/name: kube-vip
      containers: []
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
```

After adding this patch, `kube-vip` started 3 replicas on the `control-plane` nodes and services with type `LoadBalancer` started resolving external IPs.

Hope this helps someone.

**Comment by w13915984028** [comment]
@DovydasNavickas Thanks.

The issue regarding RKE2 guest cluster was fixed after this issue in Harvester v1.3.0;  but for RKE (namely, RKE1) guest cluster, it was not fixed in v1.3.0  with cloud-provider-harvester v0.2.3.  The coming v0.2.4 will fix it. Refer https://github.com/rancher/charts/pull/3601

**Comment by DovydasNavickas** [comment]
Hmmm... My cluster is RKE2, so it should have worked fine, I guess. I can try creating another cluster and see if there is still an issue. Although I used Rancher 2.8.3-rc6 to create the cluster before, now I've upgraded to 2.8.3 stable version.

**Comment by DovydasNavickas** [comment]
Just created a new RKE2 cluster:
Rancher `2.8.3`
Kubernetes version: `1.28.8+rke2r1`

And I see this:
![image](https://github.com/harvester/harvester/assets/7989797/d34442b0-22b4-4ff8-a8a5-4a3ffd9636f1)

Tolerations OOTB are:
```yaml
tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
```

I add the toleration for etcd manually:
```yaml
tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
```

And pods spin up:
![image](https://github.com/harvester/harvester/assets/7989797/0ea4a101-155e-4102-8a8d-fd6e5b88ce80)

Do I understand right that this is the situation described above?
