### ISSUE TITLE
[BUG]The local cluster stuck at configuring state, Waiting for  marking control plane as initialized and ready, while the control planes are ready

### ISSUE THREAD

**Issue by ER-EPR** [harvester/harvester#4683]
**Describe the bug**

The local cluster under fleet-local stuck at configuring state from the day I create the 3 nodes cluster using v1.2.0 iso, while actually the control planes are ready. Is there a work around I can apply to force the state to become ready.
![image](https://github.com/harvester/harvester/assets/38782737/9d867a64-1123-49eb-b309-d0e9d930df20)
```
status:
  clientSecretName: local-kubeconfig
  clusterName: local
  conditions:
    - lastUpdateTime: '2023-09-12T14:35:18Z'
      message: marking control plane as initialized and ready
      reason: Waiting
      status: Unknown
      type: Ready
    - status: Unknown
      type: DefaultProjectCreated
    - status: Unknown
      type: SystemProjectCreated
    - lastUpdateTime: '2023-09-12T14:33:43Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-09-12T14:33:43Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-10-31T14:35:50Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-09-12T14:33:57Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: Provisioned
  observedGeneration: 8
  ready: true
```
```
sm2harvester:~ # kubectl get nodes
NAME           STATUS   ROLES                       AGE     VERSION
sm1harvester   Ready    control-plane,etcd,master   3h57m   v1.25.9+rke2r1
sm2harvester   Ready    control-plane,etcd,master   49d     v1.25.9+rke2r1
sm3harvester   Ready    control-plane,etcd,master   3h34m   v1.25.9+rke2r1
```
```
sm2harvester:~ # kubectl get machines.cluster.x-k8s.io -A
NAMESPACE     NAME                  CLUSTER   NODENAME       PROVIDERID            PHASE     AGE   VERSION
fleet-local   custom-4448382d7258   local     sm1harvester   rke2://sm1harvester   Running   70m
fleet-local   custom-47daed416fc7   local     sm2harvester   rke2://sm2harvester   Running   49d
fleet-local   custom-c84273264f35   local     sm3harvester   rke2://sm3harvester   Running   46m
```
**To Reproduce**
Background:
I'm not sure what is the exact cause.  I didn't notice the problem until recently I decide to upgrade to v1.2.1. The upgrade failed at phase 4.  Only node 2 go through phase 4 post-drain and success, node 1 started draining but stuck at pre-draining.  I didn't find any solution. Doc said not to start over a update at phase 4, but I have 1 node survived, so I decide to recover the cluster by deleting two other nodes, install from 1.2.1 ISO and rejoining them.  And I have to use the work around mentioned in #4511 and #2194. It looks like I fist configure the VIP as IP address, then I install a SSL with only FQDN SAN. So I have to change IP to FQDN to join nodes, and FQDN to internal IP to promote nodes.
Possible cause:
I remember I install the 1.2.0 nodes in a hurry. I guess I may have changed settings, especially the SSL settings which related to joining problem, while joining new nodes and recover & spin up lots of VMs from backup. Something may have gone wrong during the process changing of settings while adding nodes, so that the cluster control plane ready state was never set. But I don't remember whether the nodes are properly promoted or not before I delete and rejoin them, I guess yes. Because now the nodes are joined and promoted while the cluster still stuck at configuring.

**Expected behavior**

The cluster local should be fully configured state, instead of waiting state.

**Support bundle**

[supportbundle_8697e286-65dd-464c-89db-2b61e89182c4_2023-11-01T10-42-52Z.zip](https://github.com/harvester/harvester/files/13226337/supportbundle_8697e286-65dd-464c-89db-2b61e89182c4_2023-11-01T10-42-52Z.zip)
I need to use 7z to compress it under 25M, and repackage it to zip.

**Environment**
 - Harvester ISO version: 1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): supermicro x99 X10DRi with intel2680v4

**Additional context**
