### ISSUE TITLE
[Doc] Update IP Pool examples to match the current implementation

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4696]
**Is your doc request related to a problem? Please describe or add related issue ID.**

[The examples of IP Pools](https://docs.harvesterhci.io/v1.3/networking/ippool) in the Harvester docs is outdated.

```
spec:
  ranges:
  - subnet: 192.168.10.0/24
    rangeStart: 192.168.10.10
    rangeEnd: 192.168.10.20
  selector:
    network: default/vlan1
    scope:
      project: product
      namespace: default
      cluster: rke2
```

It should be updated to:

```
spec:
  ranges:
  - subnet: 192.168.10.0/24
    rangeStart: 192.168.10.10
    rangeEnd: 192.168.10.20
  selector:
    network: default/vlan1
    scope:
    - project: product
      namespace: default
      guestCluster: rke2
```

**Describe the solution you'd like**

Update the examples with the latest CRD
