### ISSUE TITLE
[ENHANCEMENT] Create a webhook for CloudInit CRDs to protect system files under /oem

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4710]
**Is your enhancement related to a problem? Please describe.**

A new webhook is required to protect other files under `/oem`, such as:

* elemental.config
* grubenv
* harvester.config
* install
* 90_custom.yaml
* 99_settings.yaml

This defends against a CloudInit object whose spec's filename could overwrite
a system file:

```yaml
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: bad-document
spec:
  matchSelector: {}
  filename: grubenv
  contents: |
    Hello, world
```

The webhook should also prevent the creation of CloudInit CRs whose filename field conflicts with an already-existing CloudInit CR with that same filename.

**Describe the solution you'd like**

A new webhook should be included in the harvester-node-manager to protect well-known files.

**Describe alternatives you've considered**

A quick allow-list could be hard-coded into the controller, and this may be the first step to allow the enhancement to merge incrementally instead of having one giant PR.

**Additional context**

**Comment by irishgordo** [comment]
Hi @connorkuehl  I had a small validation question on the WebHook handling the CRD creations.

**Validation Questions:**
- Is it to be expected that though the files may be protected there are secondary files built?
- Is it to be expected that under `metadata.name` that is given for the CRD, that the filename in the `/oem/` directory will have `.yaml` appended to it, if it is not provided?

**Scenario Steps:**
- create a large yaml to be applied to the cluster with:
```yaml
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access
spec:
  matchSelector: {}
  filename: 99_ssh.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm michael.russell@suse.com
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: grubcustom
spec:
  matchSelector: {}
  filename: grubcustom
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: 99settings
spec:
  matchSelector: {}
  filename: 99_settings.yaml
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: 90custom
spec:
  matchSelector: {}
  filename: 90_custom.yaml
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: elemental.config
spec:
  matchSelector: {}
  filename: elemental.config
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: grubenv
spec:
  matchSelector: {}
  filename: grubenv
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: harvesterconfig
spec:
  matchSelector: {}
  filename: harvester.config
  contents: |
    hello there
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: install
spec:
  matchSelector: {}
  filename: install
  contents: |
    hello there

```
- apply it to the cluster `kubectl create -f filename.yaml`
- you'll see this yielded back:
```bash
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester-fleet-demo on main✘✘✘
╰─± kubectl create -f cloudinit/cloudinit.yaml
cloudinit.node.harvesterhci.io/ssh-access created
cloudinit.node.harvesterhci.io/grubcustom created
cloudinit.node.harvesterhci.io/elemental.config created
cloudinit.node.harvesterhci.io/grubenv created
cloudinit.node.harvesterhci.io/harvesterconfig created
cloudinit.node.harvesterhci.io/install created
Error from server (InternalError): error when creating "cloudinit/cloudinit.yaml": admission webhook "validator.harvester-system.harvester-node-manager-webhook" denied the request: Internal error occurred: filename conflicts with a critical system-owned file
Error from server (InternalError): error when creating "cloudinit/cloudinit.yaml": admission webhook "validator.harvester-system.harvester-node-manager-webhook" denied the request: Internal error occurred: filename conflicts with a critical system-owned file
```
- log on to the Harvester Node run `ls -alh /oem` you'll see:
```bash
rancher@test-mstr-head:~> ls -alh /oem/
total 123K
drwxr-xr-x   4 root root 1.0K Feb  6 00:27 .
drwxr-xr-x. 22 root root 4.0K Feb  5 18:59 ..
-rw-rw-rw-   1 root root  94K Feb  5 18:48 90_custom.yaml
-rw-r--r--   1 root root  238 Feb  5 19:09 99_settings.yaml
-rw-------   1 root root  177 Feb  6 00:27 99_ssh.yaml
-rwxr-xr-x   1 root root  585 Feb  5 18:49 elemental.config
-rw-------   1 root root   12 Feb  6 00:27 elemental.config.yaml
-rw-r--r--   1 root root    0 Feb  5 18:59 grubcustom
-rw-------   1 root root   12 Feb  6 00:27 grubcustom.yaml
-rw-r--r--   1 root root 1.0K Feb  5 18:59 grubenv
-rw-------   1 root root   12 Feb  6 00:27 grubenv.yaml
-rw-------   1 root root 1.8K Feb  5 18:49 harvester.config
-rw-------   1 root root   12 Feb  6 00:27 harvester.config.yaml
drwxr-xr-x   2 root root 1.0K Feb  5 18:59 install
-rw-------   1 root root   12 Feb  6 00:27 install.yaml
drwx------   2 root root  12K Feb  5 18:47 lost+found
```
- you can then visually audit that it built the files, though it didn't effect the main protected resource ones with:
```bash

sudo echo "oem install.yaml built: " && echo "" && sudo cat /oem/install.yaml && echo "" && echo "harvester.config.yaml built..." && echo "" && sudo cat /oem/harvester.config.yaml && echo "" && echo "grubenv.yaml built..." && echo "" && sudo cat /oem/grubenv.yaml && echo "" && echo "grubcustom.yaml built..." && echo "" && sudo cat /oem/grubcustom.yaml && echo "" && echo "elemental.config.yaml built ..." && echo "" && sudo cat /oem/elemental.config.yaml 
```
Yielding:
```
oem install.yaml built: 

hello there

harvester.config.yaml built...

hello there

grubenv.yaml built...

hello there

grubcustom.yaml built...

hello there

elemental.config.yaml built ...

hello there
```


**Additional Validation Question:**
- given: 
```
---
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: consolelogoverwrite
spec:
  matchSelector: {}
  filename: /oem/install/console.log
  contents: |
    hello there
```
- it will build `/oem/console.log.yaml`
- With:
```yaml
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester-fleet-demo on main✘✘✘
╰─± kubectl describe cloudinit/consolelogoverwrite     
Name:         consolelogoverwrite
Namespace:    
Labels:       <none>
Annotations:  node.harvesterhci.io/cloudinit-hash: aadc1955c030f723e9d89ed9d486b4eef5b0d1c6945be0dd6b7b340d42928ec9
API Version:  node.harvesterhci.io/v1beta1
Kind:         CloudInit
Metadata:
  Creation Timestamp:  2024-02-06T00:49:34Z
  Finalizers:
    wrangler.cattle.io/harvester-node-cloud-init-controller
  Generation:  1
  Managed Fields:
    API Version:  node.harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:node.harvesterhci.io/cloudinit-hash:
        f:finalizers:
          .:
          v:"wrangler.cattle.io/harvester-node-cloud-init-controller":
    Manager:      harvester-node-manager
    Operation:    Update
    Time:         2024-02-06T00:49:34Z
    API Version:  node.harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:rollouts:
          .:
          f:test-mstr-head:
            .:
            f:conditions:
    Manager:      harvester-node-manager
    Operation:    Update
    Subresource:  status
    Time:         2024-02-06T00:49:34Z
    API Version:  node.harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:contents:
        f:filename:
        f:matchSelector:
    Manager:         kubectl-create
    Operation:       Update
    Time:            2024-02-06T00:49:34Z
  Resource Version:  329968
  UID:               99e9afa0-3019-4075-9c9b-7bc89d88b25c
Spec:
  Contents:  hello there

  Filename:  console.log.yaml
  Match Selector:
Status:
  Rollouts:
    Test - Mstr - Head:
      Conditions:
        Last Transition Time:  2024-02-06T00:49:34Z
        Message:               
        Reason:                CloudInitApplicable
        Status:                True
        Type:                  Applicable
        Last Transition Time:  2024-02-06T00:49:34Z
        Message:               Local file checksum is the same as the CloudInit checksum
        Reason:                CloudInitChecksumMatch
        Status:                False
        Type:                  OutOfSync
        Last Transition Time:  2024-02-06T00:49:34Z
        Message:               console.log.yaml is present under /oem
        Reason:                CloudInitPresentOnDisk
        Status:                True
        Type:                  Present
Events:                        <none>

```
- Is that to be expected?

**Comment by connorkuehl** [comment]
> * Is it to be expected that though the files may be protected there are secondary files built?

Yeah, there's a mutating webhook that just appends a yaml suffix to the filename if one doesn't exist. The resulting CloudInit spec if you `kubectl get cloudinit <blah>` will show the updated filename that is created as a result.

> * Is it to be expected that under `metadata.name` that is given for the CRD, that the filename in the `/oem/` directory will have `.yaml` appended to it, if it is not provided?

:thinking:  No, it should use the .spec.filename for appending .yaml if .spec.filename does not end in .yml or .yaml 

> Is that to be expected?

Yeah, similarly the mutating webhook ensures the files absolute path is just `/oem/filename` and it will mutate away any other directory entries in the path put in.

**Comment by irishgordo** [comment]
@connorkuehl 
> 🤔 No, it should use the .spec.filename for appending .yaml if .spec.filename does not end in .yml or .yaml

Ahhh okay, yeah I was noticing that it was if given something like `console.log` mutating it to `console.log.yaml` - so that's an expected behavior that the suffix will mutate the original filename in spec.filename if it ends in anything other than .yaml or .yml.

I in that example had the `metadata.name` and `spec.filename` mostly the same so when I had originally mentioned that I guess my eyes were staring at the `metadata.name` like with something like:
```yaml
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: grubcustom
spec:
  matchSelector: {}
  filename: grubcustom
  contents: |
    hello there
```
Sorry for the confusion :sweat_smile:
