### ISSUE TITLE
[BUG] Upgrade 1.2.0 -> 1.2.1 is stuck in “Waiting for VM live-migration or shutdown...(1 left)” even though there is NO VM running

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#4725]
**Describe the bug**
During the upgrade of Harvester 1.2.0 to 1.2.1 the upgrade gets stuck with the message "`Waiting for VM live-migration or shutdown...(1 left)`"

But no VM is running at all:
![grafik](https://github.com/harvester/harvester/assets/13362573/b8850acf-0ac4-4ffa-a1db-2646c8c2229f)

Status of the VM:
```
status:
  conditions:
    - lastProbeTime: '2023-09-15T09:54:53Z'
      lastTransitionTime: '2023-09-15T09:54:53Z'
      message: virt-launcher pod is terminating
      reason: PodTerminating
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: 'True'
      type: LiveMigratable
  created: true
  printableStatus: Stopped
  volumeSnapshotStatuses:
    - enabled: false
      name: cdrom-disk
      reason: 2 matching VolumeSnapshotClasses for longhorn-image-dzr67
    - enabled: false
      name: rootdisk
      reason: 2 matching VolumeSnapshotClasses for longhorn
    - enabled: false
      name: virtio-container-disk
      reason: >-
        Snapshot is not supported for this volumeSource type
        [virtio-container-disk]
    - enabled: false
      name: cloudinitdisk
      reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
```

**To Reproduce**
Upgrade a 3 node harvester cluster from 1.2.0 to 1.2.1 with all VMs stopped while one VM has a similar status as above.

**Expected behavior**
Upgrade does not get stuck based on "not running VMs"

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal
