### ISSUE TITLE
[FEATURE] OVF import

### ISSUE THREAD

**Issue by mortenn** [harvester/harvester#4742]
**Is your feature request related to a problem? Please describe.**
I have an old ESXi host without vsphere and would like to move VMs over to harvester, but I cannot see a way to import an ovf template.

**Describe the solution you'd like**
On the virtual machine page, there should be an import button in addition to the create button.
The new import machine page should let the user upload and .ovf and associated vmdk files.
It also needs to present the user with a list of interfaces used by the vm and give the user the opportunity to associate the interfaces with vlans.

**Describe alternatives you've considered**
Setting up everything from scratch

**Additional context**
![image](https://github.com/harvester/harvester/assets/640095/5db278a2-4a9c-4a48-8d6c-f2c5690069e5)
![image](https://github.com/harvester/harvester/assets/640095/660b9ea5-9291-4812-b90e-5b7c54736486)
![image](https://github.com/harvester/harvester/assets/640095/4b40d623-6acb-4e3b-8ac0-830c6485a5fe)

**Comment by forbesguthrie** [comment]
@votdev can you confirm that we also support importing single OVA files as part of this?

**Comment by votdev** [comment]
> [@votdev](https://github.com/votdev) can you confirm that we also support importing single OVA files as part of this?

I think we should only support that because handling the upload of several files makes it much more complicated than processing only a single file.

**Comment by votdev** [comment]
Are there any specific requirements for this feature, particularly regarding how the data to be imported is provided?
Since we do not yet have a UI for VM import, there will be no UI support for this feature either. This raises the question of how the user provides the OVA file. 

There are now several possible solutions.

1. The user uploads the file via SSH to the node on which the VM Importer is running. In the VmwareSource CR, there is then a field that specifies the path of the file to be imported. The downside here is that the user must know on which node the VM Importer is running.

2. In VmwareSource CR, a new field is used to specify the URL from which the OVA file to be imported can be downloaded. The problem here is that the user must provide the file via an HTTP server. This is actually just a one-liner using Python, but it is not really end-user friendly.

3. Any suggestions?

What I want to avoid is cobbling together some quick fix in the UI for this feature. The VM Importer will need a sensible UI solution at some point, but for this feature we should find an independent solution that can currently only be implemented via CLI.

@ibrokethecloud

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.7.0-rc1`. Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Test 1: Import from Ubuntu OVA file $~~$</summary>

1. Can correctly import the Ubutu OVA file to create Harvester virtual machine

  ```
  harvester-node-0:~ # kubectl apply -f ova_source_ubuntu.yaml
  ovasource.migration.harvesterhci.io/ubuntu-noble created
  harvester-node-0:~ # kubectl get OvaSource -A
  NAMESPACE   NAME           STATUS
  default     ubuntu-noble   clusterReady
  harvester-node-0:~ # kubectl apply -f ova_vmi_ubuntu.yaml
  virtualmachineimport.migration.harvesterhci.io/ubuntu-noble created
  harvester-node-0:~ # kubectl get VirtualMachineImport -A
  NAMESPACE   NAME           STATUS
  default     ubuntu-noble   sourceReady
  ```
  
  <img width="1577" height="724" alt="Image" src="https://github.com/user-attachments/assets/43251e87-27f5-4b66-ae14-95a0a3017451" />


2. Check the imported vm content on UI:
  - The number of CPUs is 2.

  <img width="1600" height="777" alt="Image" src="https://github.com/user-attachments/assets/1b5c6b85-ed68-4602-8398-e119874376e3" />

  - The network card should be a virtio.

  <img width="1596" height="783" alt="Image" src="https://github.com/user-attachments/assets/3cac8bd8-9768-4dae-970d-b2ce2f81d913" />

  - The bus type of the root disk is SCSI and has a size of 10 GiB.

  <img width="1593" height="791" alt="Image" src="https://github.com/user-attachments/assets/36f295f3-f2d6-4e7a-b28e-1734029260b8" />

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Test 2: Import from Wazuh OVA file $~~$</summary>

1. Can correctly import the Wazuh OVA file to create Harvester virtual machine

  ```
  harvester-node-0:~ # kubectl apply -f ova_source_wazuh.yaml
  ovasource.migration.harvesterhci.io/wazuh created
  harvester-node-0:~ # kubectl get OvaSource -A | grep wazuh
  default     wazuh          clusterReady
  harvester-node-0:~ # kubectl apply -f ova_vmi_wazuh.yaml
  virtualmachineimport.migration.harvesterhci.io/wazuh created
  harvester-node-0:~ # kubectl get VirtualMachineImport -A | grep wazuh
  default     wazuh          sourceReady
  harvester-node-0:~ # kubectl get VirtualMachineImport -A | grep wazuh
  default     wazuh          diskImageSubmitted
  harvester-node-0:~ # kubectl get VirtualMachineImport -A | grep wazuh
  default     wazuh          diskImageSubmitted
  harvester-node-0:~ # kubectl get VirtualMachineImport -A | grep wazuh
  default     wazuh          virtualMachineCreated
  ```
  
  <img width="1589" height="756" alt="Image" src="https://github.com/user-attachments/assets/6a103d7f-1574-4bc5-93b6-088441f5b4de" />

2. Check the imported vm content on UI:
  - The network card should be `e1000`


  <img width="1600" height="784" alt="Image" src="https://github.com/user-attachments/assets/b234fb40-1c41-4fb1-aca9-c16f010859b0" />

 </details>

### Test Information
* Test Environment: Single node Harvester on kvm machine
* Harvester version: v1.7.0-rc1

### Verify Steps
<details><summary> Test steps </summary>

Refer to: https://github.com/harvester/vm-import-controller/pull/121#issue-3510305593

 1. Enable the vm-import-controller addon
 2. Create the Ubuntu `OvaSource` CR

  ```
  apiVersion: migration.harvesterhci.io/v1beta1
  kind: OvaSource
  metadata:
    name: ubuntu-noble
    namespace: default
  spec:
    url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.ova"
  ```

 3. Create the Ubuntu `VirtualMachineImport` CR

  ```
  apiVersion: migration.harvesterhci.io/v1beta1
  kind: VirtualMachineImport
  metadata:
    name: ubuntu-noble
    namespace: default
  spec: 
    virtualMachineName: "ubuntu-noble"
    networkMapping:
    - sourceNetwork: "VM Network"
      destinationNetwork: "default/vlan1"
    sourceCluster:
      name: ubuntu-noble
      namespace: default
      kind: OvaSource
      apiVersion: migration.harvesterhci.io/v1beta1
  ```

4. Import the CRs

  ```
  $ kubectl apply -f ova_source_ubuntu.yaml
  $ kubectl apply -f ova_vmi_ubuntu.yaml
  ```
  
5. Check the import pod log should have message for import should succeed

5. Check the imported vm is start in running state
6. Edit config of the vm
7. Check the following
  - The number of CPUs is 2.
  - The network card should be a virtio.
  - The bus type of the root disk is SCSI and has a size of 10 GiB.


 8. Create the Wazuh `OvaSource` CR

  ```
  apiVersion: migration.harvesterhci.io/v1beta1
  kind: OvaSource
  metadata:
    name: wazuh
    namespace: default
  spec:
    url: "https://packages.wazuh.com/4.x/vm/wazuh-4.13.1.ova"
    httpTimeoutSeconds: 900
  ```


 9. Create the Wazuh `VirtualMachineImport` CR

  ```
  apiVersion: migration.harvesterhci.io/v1beta1
  kind: VirtualMachineImport
  metadata:
    name: wazuh
    namespace: default
  spec: 
    virtualMachineName: "wazuh"
    networkMapping:
    - sourceNetwork: "VM Network"
      destinationNetwork: "default/vlan1"
    sourceCluster:
      name: wazuh
      namespace: default
      kind: OvaSource
      apiVersion: migration.harvesterhci.io/v1beta1
  ```

10. Import the CRs

  ```
  $ kubectl apply -f ova_source_wazuh.yaml
  $ kubectl apply -f ova_vmi_wazuh.yaml
  ```
11. Check the import pod log should have message for import should succeed

12. Check the imported vm is start in running state
13. Edit config of the vm
14. Check the following
  - The network card should be a e1000



</details>
