### ISSUE TITLE
[FEATURE] Support EFI mode in harvester node driver

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4777]
**Is your feature request related to a problem? Please describe.**
We can create a VM with EFI mode in harvester. However, we can't do it via Rancher.

**Describe the solution you'd like**
Add EFI setting to [Driver](https://github.com/harvester/docker-machine-driver-harvester/blob/c439e3fb5f68b51f43cf2ba385382e04042d8528/harvester/harvester.go#L31-L72) structure.

**Comment by lanfon72** [comment]
@bk201, @FrankYang0529 It looks this issue added the `EFI mode` option in backend, but for QA, we need the interface to verify it, either via `terraform`(https://github.com/rancher/terraform-provider-rancher2/pull/1281) or Rancher UI(#5224), so I think this issue is not ready for testing yet.
As the way from UI is separated in #5224, I would suggest this issue focus on terraform.

**Comment by bk201** [comment]
That sounds good to me!

**Comment by lanfon72** [comment]
Verified this feature is partially applied, move back to implement.
We can enable **EFI** but unable to enable both **EFI** and **secure boot**.

![image](https://github.com/harvester/harvester/assets/5169694/759067f1-2c64-43ae-b6fb-32075df4bcba)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.3.0-rc4**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7.11-rc3** by `docker run --privileged -d --name=rancher --restart=unless-stopped -p 8080:80 -p 6443:443 -e CATTLE_AGENT_IMAGE=stgregistry.suse.com/rancher/rancher-agent:v2.7.11-rc3 stgregistry.suse.com/rancher/rancher:v2.7.11-rc3`

### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Follow https://github.com/harvester/docker-machine-driver-harvester/pull/51#issue-2050304227 to do the test plan
    - Golang is required, I use `go1.20` installed by https://github.com/moovweb/gvm
    - add `enable_secure_boot = true` to test enable both **EFI** and **secure boot**

**Comment by FrankYang0529** [comment]
Hi @lanfon72, could you use following test steps to test again? I can run it in Rancher v2.9.3 and v2.10.1 without error. For terraform-provider-rancher2, I think we can use another ticket to trace it, because we also need to add TPM / CPU pinning in https://github.com/harvester/harvester/issues/7365. Thanks.

1. Import harvester cluster to rancher (i.e. `cluster-registration-url`).
2. In rancher container, apply the following yaml files to deploy rke2 guest cluster to harvester. (make sure you fill in all fields start with `<YOUR_...` in the yaml examples.)
   - harvesterconfig.yaml
   ```yaml
    apiVersion: rke-machine-config.cattle.io/v1
    enableEfi: true
    enableSecureBoot: true
    diskInfo: '{"disks":[{"imageName":"default/<YOUR_IMAGE_UNDER_DEFAULT_NS>","bootOrder":1,"size":40}]}'
    kind: HarvesterConfig
    memorySize: "4"
    metadata:
      name: test
      namespace: fleet-default
    networkInfo: '{"interfaces":[{"networkName":"default/<YOUR_VM_NERWORK_UNDER_DEFAULT_NS>","macAddress":""}]}'
    sshPort: "22"
    sshUser: ubuntu
    userData: I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlczoKICAtIHFlbXUtZ3Vlc3QtYWdlbnQKcnVuY21kOgogIC0gLSBzeXN0ZW1jdGwKICAgIC0gZW5hYmxlCiAgICAtICctLW5vdycKICAgIC0gcWVtdS1ndWVzdC1hZ2VudC5zZXJ2aWNlCnBhc3N3b3JkOiB0ZXN0CmNocGFzc3dkOgogIGV4cGlyZTogZmFsc2UKc3NoX3B3YXV0aDogdHJ1ZQoK
    vmNamespace: default
   ```
   - cluster.yaml
   ```yaml
    apiVersion: provisioning.cattle.io/v1
    kind: Cluster
    metadata:
      name: foobar
      namespace: fleet-default
    spec:
      cloudCredentialSecretName: cattle-global-data:<YOUR_CLOUD_CREDENTIAL_SECRET_NAME>
      kubernetesVersion: v1.30.8+rke2r1
      rkeConfig:
        chartValues:
          harvester-cloud-provider:
            cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
            global:
              cattle:
                clusterName: foobar
        etcd:
          disableSnapshots: false
          snapshotRetention: 5
          snapshotScheduleCron: 0 */5 * * *
        machineGlobalConfig:
          cni: calico
          disable-kube-proxy: false
          etcd-expose-metrics: false
        machinePools:
          - name: pool1
            etcdRole: true
            controlPlaneRole: true
            workerRole: true
            quantity: 1
            unhealthyNodeTimeout: 0m
            machineConfigRef:
              kind: HarvesterConfig
              name: test
            drainBeforeDelete: true
            labels: {}
        machineSelectorConfig:
          - config:
              cloud-provider-name: harvester
              protect-kernel-defaults: false
        upgradeStrategy:
          controlPlaneConcurrency: '1'
          controlPlaneDrainOptions:
            deleteEmptyDirData: true
            disableEviction: false
            enabled: false
            force: false
            gracePeriod: -1
            ignoreDaemonSets: true
            skipWaitForDeleteTimeoutSeconds: 0
            timeout: 120
          workerConcurrency: '1'
          workerDrainOptions:
            deleteEmptyDirData: true
            disableEviction: false
            enabled: false
            force: false
            gracePeriod: -1
            ignoreDaemonSets: true
            skipWaitForDeleteTimeoutSeconds: 0
            timeout: 120
   ```
3. Run command to generate kubeconfig for harvester-cloud-provider in an environment which can reach harvester cluster.
   ```
   curl -sfL https://raw.githubusercontent.com/harvester/cloud-provider-harvester/master/deploy/generate_addon.sh | bash -s foobar default
   ```
4. Copy the kubeconfig into `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` under the VM (password is `test`). 
5. Go to harvester UI, navigate to Virtual Machines page, check the vm have the following attribute.
   ```yaml
    firmware:
      bootloader:
        efi:
          secureBoot: true
   ```
