### ISSUE TITLE
[BUG] VM template stores PCI device details

### ISSUE THREAD

**Issue by ianb-mp** [harvester/harvester#4792]
**Describe the bug**

I created a template from a VM that has a PCI device configured. I noticed that the template stored the PCI details. And VMs created from that template use the same PCI details!

Here is an example snippet from my template file showing the PCI network device:
```yaml
          devices:
              disks:
                - bootOrder: 1
                  disk:
                    bus: virtio
                  name: rootdisk
                - bootOrder: 2
                  cdrom:
                    bus: sata
                  name: cdrom-disk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              hostDevices:
                - deviceName: intel.com/ETHERNET_VIRTUAL_FUNCTION_700_SERIES
                  name: xxx-lab-vr-3-00005e020
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
```

Additionally, when editing the template via the web UI, PCI device details are not visible/editable.

**To Reproduce**
1. Create a VM that uses a PCI device
2. Create a template from that VM
3. Create a new VM using the template
4. Observe that both VMs are using the same PCI device

**Expected behavior**

It shouldn't be possible to launch multiple VMs using the same PCI device. As such, does it make sense to store these details in a template to begin with? At least, a check should be done when a VM is created from a template to see if a PCI device is already in use.

**Support bundle**
(please contact me)

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure: bare metal on Cisco C220 M5
