### ISSUE TITLE
[BUG] Create RKE2 guest cluster on Rancher v2.6.13, the default User Data have no content

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4853]
**Describe the bug**

While creating the RKE2 guest cluster on Rancher v2.6.13, expand the advance settings
There is no content in the `User Data` section. 
![image](https://github.com/harvester/harvester/assets/29251855/3fabb826-ed49-423b-bc65-3d3532b19794)

* User need to manually provide like the following user data content.
* No such information provided would cause the provisioning RKE2 guest failed on Rancher v2.6.13
  ```
  #cloud-config
  package_update: true
  packages:
    - qemu-guest-agent
  runcmd:
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
  ```

* In contract to Rancher v2.7.9, it provide the default User data content 

**To Reproduce**
1. Prepare three nodes `v1.1.3-rc2` Harvester cluster
2. Import Rancher v2.6.13 with Harvester
3. Provision the RKE2 guest cluster
4. Expand the advanced setting
5. Check the default `User Data` section

**Expected behavior**

The User Data section of the RKE2 guest cluster creation page should by default provide the available User Data for provisioning guest cluster 

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.3-rc2 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Three nodes remote kvm machines
 - Rancher version: v2.6.13 
 - RKE2 version: v1.24.17
