### ISSUE TITLE
[BUG] IP Pool create/edit menu does not allow specifying guestCluster or project scopes, only namespace scope

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4890]
**Describe the bug**

The IP Pool's scope[1] can be limited via namespace, project, or guestCluster, but the UI only allows selecting a Namespace scope.

When a guest cluster uses cloud-provider-harvester and creates a Service of type: LoadBalancer, the Harvester load balancer is stuck in a pending state with this error:

```
Allocate ip for lb default/x failed, error: fail to select the pool for lb default/x,
error: no matching IP pool with requirement &{
    Network:default/NET-NAME
    Project:x Namespace:default
    Cluster:CLUSTER-NAME
}
```

The workaround is to edit the IP Pool YAML:

```yaml
spec:
  selector:
    network: default/NET-NAME
    scope:
      - guestCluster: 'CLUSTER-NAME'
        namespace: 'default'
        project: '*'
```

Or make it a global IP Pool:

```yaml
spec:
  selector:
    network: default/NET-NAME
    scope:
      - guestCluster: '*'
        namespace: '*'
        project: '*'
```

[1] https://github.com/harvester/load-balancer-harvester/blob/f126dae3da1a2bec44bff4966d3519c793d31a02/pkg/apis/loadbalancer.harvesterhci.io/v1beta1/ippool.go#L50

**To Reproduce**
1. Go to **Harvester dashboard** > **Networks** > **IP Pools**
1. Click **Create** > **Selector**
1. Click **Add scope**
1. Observe that only the Namespace scope can be specified on the UI.

Similar steps can be used for a pre-existing IP Pool, just click **Edit Config** > **Selector**.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
