### ISSUE TITLE
[ENHANCEMENT] Support bundle resource clean up

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4922]
**Is your enhancement related to a problem? Please describe.**

When creating a support bundle from GUI, the SupportBundle resources are only deleted after the bundle is fully downloaded ([ref](https://github.com/harvester/harvester/blob/fb1e5ae8fd817cdd879bb93a31966cbaf3749a3d/pkg/api/supportbundle/download_handler.go#L117-L122)). There are cases that downloads can't finish and there will be many unused SB and support-bundle-manager pods left in the cluster. This can occupy cluster resources and stop users from provisioning more VMs or services.

**Describe the solution you'd like**

Clean up unused support bundle resources after a certain period. We can consider if we should retain the bundle file.

**Describe alternatives you've considered**

**Additional context**

**Comment by Yu-Jack** [comment]
## Add more context

When I test to create multiple support bundle in harvester at the same time, I observe following situation.

## Create multiple support bundle at the same time

```yaml
# Longhorn's apiVersion is `longhorn.io/v1beta2`, and namespace is `longhorn-system`

apiVersion: harvesterhci.io/v1beta1
kind: SupportBundle
metadata:
  name: bundle-a1
  namespace: harvester-system
spec:
  issueURL: "this is issueURL"
  description: "this is description"
---
apiVersion: harvesterhci.io/v1beta1
kind: SupportBundle
metadata:
  name: bundle-a2
  namespace: harvester-system
spec:
  issueURL: "this is issueURL"
  description: "this is description"
---
apiVersion: harvesterhci.io/v1beta1
kind: SupportBundle
metadata:
  name: bundle-a3
  namespace: harvester-system
spec:
  issueURL: "this is issueURL"
  description: "this is description"
```

### In Harvester

It causes the support bundle manager failed to start agent Daemonset, the reason is [this condition](https://github.com/rancher/support-bundle-kit/blob/4c92b3e4902ca6aa1339e4f35cb6422a4958a7f3/pkg/manager/manager.go#L370-L373) is always `false`. 

When you create three support bundle at the same time, it creates three Daemonset. But `len(pods.Items)` is 3, and the `daemonSet.Status.DesiredNumberScheduled` is 1, that's why it gets `false`.

### In Longhorn

Because there is a [admission webhook](https://github.com/longhorn/longhorn-manager/blob/be088500bd083ad062eff6261a0d610046c681e6/webhook/resources/supportbundle/validator.go#L51-L69), so it won't allow multiple support bundle get created. And it will replace the old one if new one is created.

### Conclusion

There are two things we could solve 

- [ ] Longhorn Mechanism
    Although longhorn prevent this thing from happening, but I think it will cost too much effort if we implement same mechanism in harvester. We might delete harvester/longhorn support bundle from support bundle kit, such as callback.
- [x] Support Bundle Kit (related PR https://github.com/rancher/support-bundle-kit/pull/91)
   We should fix the condition, the condition should be like this I think. 
  ```diff
  // Check if all desired Pods have been scheduled
  -if len(filteredPods) != 0 && len(pods.Items) == int(daemonSet.Status.DesiredNumberScheduled) {
  +if len(filteredPods) != 0 && len(filteredPods) == int(daemonSet.Status.DesiredNumberScheduled) {
    return &v1.PodList{Items: filteredPods}, nil
  }
  ```
