### ISSUE TITLE
image status is not showing correctly

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#50]
**Description:**
In the UI the image status showing as `active` when uploading image was failed, e.g
![image](https://user-images.githubusercontent.com/4569037/90465030-17676f80-e141-11ea-9670-69f148c011c6.png)

```YAML
status:
  appliedUrl: https://launchpad.net/cirros/trunk/0.3.2/+download/cirros-0.3.2-source.tar.gz
  conditions:
  - lastUpdateTime: "2020-08-18T10:43:46+08:00"
    message: started image importing
    reason: 'Get http://example.com:9000/vm-images/?location=: dial tcp 93.184.216.34:9000:
      i/o timeout'
    status: "False"
    type: imported
  downloadUrl: ""
  progress: 0
```

**Expected:**
change status to `failed` and display the error message.
