### ISSUE TITLE
[BUG] The `StorageReserved` should not be zero on extra disks

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5042]
**Describe the bug**
When we provision the extra disk to longhorn. 
The `StorageReserved` should not be zero. (like the following)
```
// This is disk status of `nodes.longhorn.io`
spec:
  allowScheduling: true
  disks:
    a827440145f11f652f00f2a6ae656ed0:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/harvester/extra-disks/a827440145f11f652f00f2a6ae656ed0
      storageReserved: 0
      tags: []
```

**To Reproduce**
1. create extra storage to Longhorn (by harvester UI)
2. Check the `nodes.longhorn.io` CR
3. You can see the `storageReserved` is `0`

**Expected behavior**
`storageReserved` should not be `0`, the default storage reserved of longhorn is 30%
(Configurable after Longhorn v1.5.0)

**Support bundle**
None

**Environment**
 - Harvester ISO version: Harvester v1.1.2 and later version
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM, 3 nodes cluster

**Additional context**
None
