### ISSUE TITLE
[ENHANCEMENT] Support filter list on NDM

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5059]
**Is your enhancement related to a problem? Please describe.**
Now, NDM can filter out like `vendor`, `label`, and `path` by ENV or parameter
We could have the filter list to include the above. That would be more convenient.

**Describe the solution you'd like**
Add a filter list, and NDM can filter with this.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by innobead** [comment]
Discussed with @Vicente-Cheng . He will share the detailed idea and proposal for this improvement. I would expect @tserong can drive the implementation.

**Comment by tserong** [comment]
I discussed with @Vicente-Cheng a bit last week - he suggested maybe using a ConfigMap for the filters. I've done some experimenting, and we could do something like this pretty easily:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: harvester-node-disk-manager
  namespace: harvester-system
data:
  label_filter: "COS_*,HARV_*"
  path_filter: "/mount/path/you/want/to/exclude"
  # also vendor_filter, auto_provision_filter
```

Then in the NDM daemonset:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: harvester-node-disk-manager
  namespace: harvester-system
  # [...]
spec:
  # [...]
  template:
    spec:
      containers:
      - command:
        - node-disk-manager
        env:
        - name: NDM_LABEL_FILTER
          valueFrom:
            configMapKeyRef:
              key: label_filter
              name: harvester-node-disk-manager
        - name: NDM_PATH_FILTER
          valueFrom:
            configMapKeyRef:
              key: path_filter
              name: harvester-node-disk-manager
        # ...and so on for other filters...
```

The startup logic with environment variables could remain the same, but we'd of course need to add something to monitor for changes to the ConfigMap at runtime. Or, we get rid of the environment variables and just have NDM check the ConfigMap at startup (I'm not sure yet which would make the most sense).

Some further thoughts:

- The current implementation means the same set of filters are applied to all nodes. Are we likely to need to have filters that only apply to specific nodes? Or that are somehow different on a per-node basis?
- I can imagine a couple of ways in which the existing filter sets could be enhanced (e.g. we don't seem to currently have exclude by device path, but I can see that being potentially useful).
- It would be helpful to make the debug logging a bit more verbose, to say which filter was matched when something was included/excluded.

**Comment by Vicente-Cheng** [comment]
Hi @tserong,

Thanks for the quick check! Very clear.

For the original idea, I would like to drop `NDM_LABEL_FILTER` and `NDM_PATH_FILTER` and introduce the checking mechanism on the scanner.

The simple idea is that the device change will trigger the scanner to scan. After the scanner updates or adds any block device CR, the controller handles the corresponding operations.

So, we could add the checking mechanism (with data from the configMap) to ensure that we know how to handle the devices.

Currently, I do not have a very clear data structure for each configMap data, but as you mentioned, we could provide a way to handle different devices on different nodes.

Surely, if we use the configMap, we need a new webhook to validate this data.

WDYT for that?

cc @bk201

**Comment by bk201** [comment]
> The current implementation means the same set of filters are applied to all nodes. Are we likely to need to have filters that only apply to specific nodes? Or that are somehow different on a per-node basis?

I believe it's not an uncommon case. I will +1 to have the per-node configuration.

**Comment by tserong** [comment]
> For the original idea, I would like to drop `NDM_LABEL_FILTER` and `NDM_PATH_FILTER` and introduce the checking mechanism on the scanner.
> 
> The simple idea is that the device change will trigger the scanner to scan. After the scanner updates or adds any block device CR, the controller handles the corresponding operations.
> 
> So, we could add the checking mechanism (with data from the configMap) to ensure that we know how to handle the devices.

I've done some more experimenting, and the above should work just fine. I'm reading a configmap in `Scanner.scanBlockDevicesOnNode()`, and if I go edit the configmap (`kubectl -n harvester-system edit cm/node-disk-manager`) then trigger a udev event by (un)plugging a device, I can see that NDM gets the new values from the configmap. I haven't hooked this up to the filters yet, but it proves the idea works.

> Currently, I do not have a very clear data structure for each configMap data, but as you mentioned, we could provide a way to handle different devices on different nodes.
> 
> Surely, if we use the configMap, we need a new webhook to validate this data.

Right now, we have the following customizable exclude filters:

- `vendor_filter` (will always include "longhorn")
- `path_filter` (will always include "/")
- `label_filter` (defaults to `COS_*,HARV_*` based on chart values that come from https://github.com/harvester/harvester-installer/blob/1e7572e3822c70adf5730d71ef94f071a15dde82/pkg/config/templates/rancherd-10-harvester.yaml#L186-L188)

We also have an internal `drive_type_filter` and `part_type_filter`, which aren't exposed to the user. These two make sure that we're only operating on HDDs/SSDs (not floppies or optical disks, or some unknown type of disk), and that we ignore BIOS boot partitions.

Then there's the `auto_provision_filter` which is a list of device paths that will be automatically provisioned and formatted. This can be set by the `auto-disk-provision-paths` setting in Harvester which is currently marked experimental (https://docs.harvesterhci.io/v1.3/advanced/index#auto-disk-provision-paths-experimental). That setting pushes the value specified through the chart values so it ends up embedded in the NDM daemonset as an environment variable, same as the other filters.

Right now, all filters are global for the cluster. In addition to what we've got above, I think we want:

- One more exclude filter (by device path, as opposed to mount path)
- The ability for all filters to optionally specify a node or nodes (as mentioned in previous comments)
- The ability for auto_provision_filter to specify the provisioner type (to tie in with https://github.com/harvester/harvester/issues/6014)
- I personally would like to rename the filters, to more clearly state their purpose, so instead of `vendor_filter` it would be `exclude_vendors`, instead of `path_filter` it would be `exclude_paths` and so on.

In a configmap, we just have key:value pairs, where the value is a string. Given we have some extra (optional?) things to express (node name, provisioner type) I was kinda hoping we'd be able to put structured data in values... and we _can_ if we make the string be JSON or something, but that might get irritating for people to edit (we'd definitely want some sort of hook for validating that!)

So I've come up with a couple of ideas for how we could structure this:

1. Try to stick to reasonably simple strings for the filters, much as we have now for the env vars, where each is a comma delimited list of globs, but expand this to allow an optional colon-delimited hostname prefix, for example:

```yaml
# exclude "QEMU" vendor on all nodes
exclude_vendors: "QEMU"
# exclude "/mnt" on all nodes, and "/extra-data" on node2
exclude_paths: "/mnt,node2:/extra-data"
# exclude "/dev/sd*" on all nodes
exclude_devices: "/dev/sd*"
# exclude "COS_*" and "HARV_*" lables on all nodes,
# and exclude "MY_LABEL" on node1
exclude_labels: "COS_*,HARV_*,node1:MY_LABEL"
```

With the autoprovision filter, I'm not sure how best to allow for provisioner types as well as optional hostnames. One way would be extra keys per provisioner type, e.g.:

```yaml
auto_provision_devices_longhornv1: "/dev/nvme*"
auto_provision_devices_longhornv2: "/dev/whatever"
auto_provision_devices_lvm: "..."
```

Or we somehow embed the provisioner type into the value, while keeping an optional hostname. Maybe that means provisioner type is always required, e.g.:

```yaml
# auto provision all NVME devices as longhorn v2 volumes on
# all nodes and provision /dev/sdb for LVM on node1
auto_provision_devices: "longhornv2:/dev/nvme*,node1:lvm:/dev/sdb"
```

I'm not 100% happy with either of the above, but I think I prefer the second form. I guess we could look at suffixes instead of prefixes, or having a different delimiter for provisioner type, but anyway, my point is, overall this approach (I hope!) keeps the filter strings reasonably simple to read, write and understand.

2. Use a blob, or blobs of JSON. This could be structured any number of ways, from one blob of JSON for everything to one blob per filter type. It kinda depends on what's easiest to read and understand while also allowing global and node-specific filters. Here's the most concise form I could think of which provides the same filter set outlined above. The first hash in the array of filters doesn't specify a hostname so is applied globally. The others apply only to the specified hosts. All elements are optional:

```yaml
# one blob of JSON in a configmap representing all filters
filters: |
  [
     {
        "auto_provision_devices" : {
           "longhornv2" : [
              "/dev/nvme*"
           ]
        },
        "exclude_devices" : [
           "/dev/sd*"
        ],
        "exclude_labels" : [
           "COS_*",
           "HARV_*"
        ],
        "exclude_paths" : [
           "/mnt"
        ],
        "exclude_vendors" : [
           "QEMU"
        ]
     },
     {
        "auto_provision_devices" : {
           "lvm" : [
              "/dev/sdb"
           ]
        },
        "exclude_labels" : [
           "MY_LABEL"
        ],
        "hostname" : "node1"
     },
     {
        "exclude_paths" : "/extra-data",
        "hostname" : "node2"
     }
  ]
```

This is arguably more expressive than the string-based approach, but TBH I find it really irritating to write by hand, and pretty annoying to read as well ;-)

So. What looks cleanest to you folks? What approach would be the most obvious to others familiar with k8s?

One other note: if we switch to using a configmap for filters, I think we can probably remove all the filter settings from the NDM chart, and maybe also remove that `auto-disk-provision-paths` setting from harvester - anyone wanting to tweak the filters just needs to edit the configmap directly. I'm not sure what this would mean for upgrades though (I guess we'd need some sort of chart value -> configmap migration thingy).
