### ISSUE TITLE
[BUG] The embedded DHCP server IP is not validated

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5065]
**Describe the bug**

https://github.com/harvester/harvester/pull/4960#discussion_r1470915415

> It assumes that the serverIP is in same range with next item cidr, is this checked by the webhook?

To use the managed DHCP feature, the user must create an IPPool object before allocating IP addresses for VMs. The user is responsible for defining the embedded DHCP server's IP address in the object in the current implementation (<= v0.1.0). Usually, users don't bother to determine the DHCP server IP address. A UX enhancement is needed here and was tracked in #5045. However, there are no checks against the server IP validation during the IPPool creation nor prompt error reporting by the controller for such cases. The result is a misconfigured agent Pod created, and the embedded DHCP server cannot serve DHCP requests.

For example, with the following out-of-subnet DHCP server IP:

```
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    serverIP: 172.18.100.100
    cidr: 172.19.0.0/16
    pool:
      start: 172.19.0.2
      end: 172.19.254.254
    router: 172.19.100.254
    leaseTime: 300
  networkName: default/test-net
```

The IPPool is initialized without any error reported:

```
$ kubectl get ippools.network.harvesterhci.io test-net                 
NAME       NETWORK            AVAILABLE   USED   REGISTERED   CACHEREADY   AGENTREADY
test-net   default/test-net   65277       0      True         True         True
```

However, look into the agent Pod definition:

```
$ kubectl -n harvester-system get pods default-test-net-agent -o yaml
...
  initContainers:
  - command:
    - /bin/sh
    - -c
    - |2

      #!/usr/bin/env sh
      set -ex

      ip address flush dev eth1
      ip address add 172.18.100.100/16 dev eth1
    image: busybox
    imagePullPolicy: Always
    name: ip-setter
...
```

The agent Pod is attached to the network but configured with an IP that is not within the subnet.

**To Reproduce**

1. Install the vm-dhcp-controller chart
2. Create an IPPool object with misconfigured `.spec.ipv4Config.serverIP`
3. The invalid IPPool object is created without errors, and the corresponding agent Pod is spawned
4. The embedded DHCP server could not serve any DHCP requests due to the misconfigured IP address

**Expected behavior**

The webhook should reject any IPPool objects with an invalid server IP defined. Also, the agent Pod should not be spawned in such cases. The controller should report an error on the incident.

**Support bundle**

N/A

**Environment**
 - Harvester ISO version: v1.2.1 (with vm-dhcp-controller v0.1.0)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

N/A

**Comment by w13915984028** [comment]
BTW, the `serverIP`, `pool start/end`, `router`, `exclude` should all in same CIRD now.

```
    serverIP: 172.18.100.100
    cidr: 172.19.0.0/16
    pool:
      start: 172.19.0.2
      end: 172.19.254.254
    router: 172.19.100.254
```

**Comment by irishgordo** [comment]
**validation issue:**

@starbops I'm seeing a bit of a validation issue with this.

Setting up the expiremental addon via:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/crop-bushels on main✘✘✘
╰─± kubectl create -f https://raw.githubusercontent.com/harvester/experimental-addons/main/harvester-vm-dhcp-controller/harvester-vm-dhcp-controller.yaml
addon.harvesterhci.io/harvester-vm-dhcp-controller created

```

And enabling it on Settings -> Addons in v1.3.0-rc3, two node bare metal cluster.

Yielding:
```
helm-install-harvester-vm-dhcp-controller-v26hj         0/1     Completed   0              18m

```

So the loadout like:
```yaml

╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl describe network-attachment-definition/test-net
Name:         test-net
Namespace:    default
Labels:       network.harvesterhci.io/clusternetwork=sample
              network.harvesterhci.io/ready=true
              network.harvesterhci.io/type=L2VlanNetwork
              network.harvesterhci.io/vlan-id=30
Annotations:  network.harvesterhci.io/route: {"mode":"manual","cidr":"192.168.30.1/24","gateway":"192.168.30.1","connectivity":"true"}
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2024-02-23T22:33:37Z
  Finalizers:
    wrangler.cattle.io/harvester-network-nad-controller
    wrangler.cattle.io/harvester-network-manager-nad-controller
  Generation:  1
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
      f:spec:
        .:
        f:config:
    Manager:      harvester
    Operation:    Update
    Time:         2024-02-23T22:33:37Z
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:network.harvesterhci.io/route:
        f:finalizers:
          .:
          v:"wrangler.cattle.io/harvester-network-manager-nad-controller":
          v:"wrangler.cattle.io/harvester-network-nad-controller":
        f:labels:
          .:
          f:network.harvesterhci.io/clusternetwork:
          f:network.harvesterhci.io/ready:
          f:network.harvesterhci.io/type:
          f:network.harvesterhci.io/vlan-id:
    Manager:         harvester-network-controller
    Operation:       Update
    Time:            2024-02-23T22:33:45Z
  Resource Version:  109386
  UID:               d760c5bf-5fff-44e3-89e8-4e2013d65654
Spec:
  Config:  {"cniVersion":"0.3.1","name":"test-net","type":"bridge","bridge":"sample-br","promiscMode":true,"vlan":30,"ipam":{}}
Events:    <none>
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ cat ippool.yaml 
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    serverIP: 192.168.30.256
    cidr: 192.168.30.1/24
    pool:
      start: 192.168.30.2
      end: 192.168.30.250
    router: 192.168.30.1
    leaseTime: 300
  networkName: default/test-net

```

Where `spec.ipv4Config.serverIP` is outside the scope of the block of IPs on the network.
Gateway IP: 192.168.30.1
Brodcast IP: 192.168.30.255
Subnet Mask: 255.255.255.0
VLAN ID: 30
DHCP Mode: None

VLAN Config of:
```yaml

apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  annotations:
    network.harvesterhci.io/matched-nodes: '["node6-v130rc3","node5-v130rc3"]'
  creationTimestamp: '2024-02-23T22:31:07Z'
  finalizers:
    - wrangler.cattle.io/harvester-network-vlanconfig-controller
  generation: 1
  labels:
    network.harvesterhci.io/clusternetwork: sample
  managedFields:
    - apiVersion: network.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:clusterNetwork: {}
          f:uplink:
            .: {}
            f:bondOptions:
              .: {}
              f:miimon: {}
              f:mode: {}
            f:linkAttributes:
              .: {}
              f:txQLen: {}
            f:nics: {}
      manager: harvester
      operation: Update
      time: '2024-02-23T22:31:07Z'
    - apiVersion: network.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-network-vlanconfig-controller": {}
      manager: harvester-network-controller
      operation: Update
      time: '2024-02-23T22:31:07Z'
  name: test-net
  resourceVersion: '106704'
  uid: 0b9a3310-89ec-47d3-8637-8dd96b8071f8
spec:
  clusterNetwork: sample
  uplink:
    bondOptions:
      miimon: -1
      mode: active-backup
    linkAttributes:
      txQLen: -1
    nics:
      - enp11s0
```


The `serverIP` set to `192.168.30.256` is valid and the webhook does not reject it.
```
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl create -f ippool.yaml 
ippool.network.harvesterhci.io/test-net created
```

That IPPool CRD should be rejected, correct?

**Comment by starbops** [comment]
@irishgordo Thanks for looking into this. We've just [bumped the harvester-vm-dhcp-controller add-on today](https://github.com/harvester/experimental-addons/pull/11) with the defaulting v0.2.1 app version. The default app version for the add-on was v0.1.0 before. The fix was released in [v0.2.0](https://github.com/harvester/vm-dhcp-controller/releases/tag/v0.2.0), so I guess what you tested did not contain the fix yet. If you still have the environment, you could check the image used for harvester-vm-dhcp-controller Pod to verify if that's the case.

I will update the test plan with more details. Thanks again!

**Comment by irishgordo** [comment]
@starbops this looks good testing with variations of:
```bash

╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ cat ippool.yaml 
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    serverIP: 192.168.30.256
    cidr: 192.168.30.1/24
    pool:
      start: 192.168.30.2
      end: 192.168.30.250
    router: 192.168.30.1
    leaseTime: 300
  networkName: default/test-net
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl create -f ippool.yaml 
The IPPool "test-net" is invalid: 
* spec.ipv4Config.serverIP: Invalid value: "192.168.30.256": spec.ipv4Config.serverIP in body must be of type ipv4: "192.168.30.256"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ nvim ippool.yaml 
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl create -f ippool.yaml
error: error validating "ippool.yaml": error validating data: ValidationError(IPPool.spec.ipv4Config.leaseTime): invalid type for io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config.leaseTime: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ nvim ippool.yaml 
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl create -f ippool.yaml
The IPPool "test-net" is invalid: 
* spec.ipv4Config.leaseTime: Invalid value: "number": spec.ipv4Config.leaseTime in body must be of type integer: "number"
* spec.ipv4Config.serverIP: Invalid value: "192.168.30.256": spec.ipv4Config.serverIP in body must be of type ipv4: "192.168.30.256"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
╭─mike at 
```

It is now validating the CRD's server IP and other elements.
Due to this not being in rc3, built a 2 node cluster on bare-metal dl160s, testing off of:
` Version: v1.3-7cb8315c-head`

I am open to close this out but I did have one last validation question.

If given something like:
```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    serverIP: 192.168.30.200
    cidr: 192.168.30.1/24
    pool:
      start: 192.168.30.2
      end: 192.168.30.250
    router: 192.168.30.1
    leaseTime: 300
  networkName: default/test-net
```
**Question:** Is it allowed for a User to build an IPPool CRD where the `spec.ipv4Config.serverIP` 's IPv4 Address is "within" the `spec.ipv4Config.pool` range?
As I'm not sure if this should be allowed or not allowed - as it will "create" successfully.
But unsure if the "pool"'s start->end is going to be able to juggle having the `spec.ipv4Config.serverIP` existing within that IP block range
