### ISSUE TITLE
[BUG] VM Backup Created before v1.3 Should Not Report The Progress After Upgrade

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#5068]
**Describe the bug**
VM backup created before v1.3 should not show the progress after the upgrade to v1.3 and above

**To Reproduce**
1. Building Harvester with v1.2.1
2. Creating VM and doing VM Backup
3. Upgrade to Harvester v1.3.0
4. VM Backup has the status `ReadyToUse` but the progress stays at `0%` ![vmbackup](https://github.com/harvester/harvester/assets/19387129/cb979f9f-b7e2-4f11-863e-5b9c1735b08b)

**Expected behavior**
VM Backup should hide the progress report in this condition

**Environment**
 - Harvester ISO version: master-head branch (commit `12d5e49354cdbdd9da88ffe46d452e55217cfee8`)

**Additional Context**
For the VMBackup object created before the upgrade, it would have an empty value for the field `.status.progress` and `.status.volumeBackups[*].progress`, in the mean time, the field `.status.readyToUse` is already true, for example:

  VMBackup created before upgrade:
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: VirtualMachineBackup
  metadata:
    name: vm-b1
    namespace: default
  spec:
    source:
      apiGroup: kubevirt.io
      kind: VirtualMachine
      name: vm
    type: backup
  status:
    ....
    readyToUse: true
    ....
      name: vm-fzs6h
    volumeBackups:
    - creationTime: "2024-01-31T04:27:21Z"
      ....
      name: vm-b1-volume-vm-disk-0-jyd92
      persistentVolumeClaim:
      ....
      readyToUse: true
      volumeName: disk-0
  ```

  VMBackup created after upgrade:
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: VirtualMachineBackup
  metadata:
    name: vm-b2
    ....
  spec:
    source:
      apiGroup: kubevirt.io
      kind: VirtualMachine
      name: vm
    type: backup
  status:
    ....
    progress: 100
    readyToUse: true
    ....
    volumeBackups:
    - creationTime: "2024-01-31T08:31:56Z"
      ....
      name: vm-b2-volume-vm-disk-0-jyd92
      progress: 100
      readyToUse: true
      volumeName: disk-0
      volumeSize: 10737418240
  ```
