### ISSUE TITLE
[BUG] Creating VM Images with Identical Namespace-Name Combination Makes Creation Stuck

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#5123]
**Describe the bug**
Creating two virtual images with the same `<namespace>-<name>` combination will lead to one virtual image stuck in creation (progress stays 0%)

**To Reproduce**
- Creating a namespace `harvester`
- Applying the following two manifests at the same time
    ```
    apiVersion: harvesterhci.io/v1beta1
    kind: VirtualMachineImage
    metadata:
      name: ubuntu
      namespace: harvester-public
    spec:
      displayName: ubuntu
      retry: 3
      sourceType: download
      storageClassParameters:
        migratable: "true"
        numberOfReplicas: "1"
        staleReplicaTimeout: "30"
      url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    ```
    ```
    apiVersion: harvesterhci.io/v1beta1
    kind: VirtualMachineImage
    metadata:
      name: public-ubuntu
      namespace: harvester
    spec:
      displayName: public-ubuntu
      retry: 3
      sourceType: download
      storageClassParameters:
        migratable: "true"
        numberOfReplicas: "1"
        staleReplicaTimeout: "30"
      url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    ```
- The creation of one image is stuck at progress 0%

**Expected behavior**
The two images should be created successfully and could be used to provide a VM

**Environment**
 - Harvester ISO version: master-head (commit `6baab11c6df53620c50b12439f913d2dbbd7574e`)
