### ISSUE TITLE
[BUG] Patching of a Cloud-Init Resource Only Creates Additive Change

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5130]
**Describe the bug**
Given a CloudInit Resource is built targeting a single node in a cluster of nodes with a specific label.
That CloudInit Resource get's applied, applies the change.
On reboot of that node the change is reflected.
Patching the CloudInit Resource, then Rebooting the node, the change is only reflected if the change is "adding" content, not removing it.

**To Reproduce**
1. Build a multi-node cluster, provide at least one `os.ssh_authorized_key` at cluster inception 
1. Create a label on one of the nodes (Edit Host -> Labels)
1. Apply the example-pre-reboot.yaml 
1. Examine the node has the appropriate changes
1. Reboot the node
1. Verify changes work
1. Patch the CRD (see patching non-appending) w/ example-post-reboot-patch-non-appending.yaml (either option)
1. Examine that `/oem/filename` changed & `kubectl describe` on that resource reflects the patch
1. Reboot the node
1. See that example-post-reboot-patch-non-appending.yaml, was ignored under the `~/.ssh/authorized_keys`
1. Patch the CRD (see patching appending) w/ example-post-reboot-patch-appending.yaml
1. Examine that `/oem/filename` changed & `kubectl describe` on that resource reflects the patch
1. Reboot the node
1. See that example-post-reboot-patch-appending, was acknowledged under the `~/.ssh/authorized_keys`

**Expected behavior**
Patching the CloudInit CRD would always be the correct reflection of the underlying elemental toolkit stage's items.
Not only "additive" in nature.

**Environment**
 - Harvester ISO version: v1.3.0-rc2
 - Underlying Infrastructure: qemu/kvm

**Additional context**

`example-pre-reboot.yaml: `

```
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access-node-1-only
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_ssh_node_1_only.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHYl9ZFAxCTCQDVw+ngsWQu8Jo0LhmSF5KFh+G8Qxt67
```

`patching example a:`
```
kubectl patch --patch-file filepath/example-post-reboot-patch-non-appending.yaml cloudinits/ssh-access-node-1-only --type=merge
```
`patching example b`
```
kubectl patch --patch-file filepath/example-post-reboot-patch-appending.yaml cloudinits/ssh-access-node-1-only --type=merge
```

`example-post-reboot-patch-non-appending.yaml  - option a:`
```
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access-node-1-only
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_ssh_node_1_only.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
```
`example-post-reboot-patch-non-appending.yaml  - option b:`
```
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access-node-1-only
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_ssh_node_1_only.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519
```
`example-post-reboot-patch-appending.yaml:`
```
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access-node-1-only
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_ssh_node_1_only.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm
```

**Comment by irishgordo** [comment]
I guess I'm curious if the Cloud-Init resource can modify "existing" configuration.
Given that a cluster was provisioned with a remote configuration that holds something like:
```
scheme_version: 1
server_url: https://cluster-VIP:443
token: TOKEN_VALUE
os:
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
```
In which we have the `os.ssh_authorized_keys` defined at inception of the cluster.

We can add a key this way as well with, `example-add-key-with-write.yaml`:
```yaml

apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: write-authorized-key-file
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_write_authorizedkeys_file.yaml
  contents: |
    stages:
      fs:
        - name: "write authorized_keys file"
          commands:
            - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm michael.russell@suse.com" > /home/rancher/.ssh/authorized_keys
```
Which will then yield, post reboot:
```
rancher@harvester-node-1:~> cat ~/.ssh/authorized_keys 
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm michael.russell@suse.com
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
```


But when I think of a command like: `echo "" > /filepath/a-file-that-will-be-overwritten.txt` - I would expect a `cat /filepath/a-file-that-will-be-overwritten.txt` to be "empty".
But what actually happens with a `kubectl patch --patch-file cloudinit/cloud-init-but-write-files.yaml cloudinits/write-authorized-key-file --type=merge` with the yaml taking the form in:
```yaml
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: write-authorized-key-file
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_write_authorizedkeys_file.yaml
  contents: |
    stages:
      fs:
        - name: "write authorized_keys file"
          commands:
            - echo "" > /home/rancher/.ssh/authorized_keys

```
Is interesting.
It does not "erase", overwrite that file... 
It ends up yielding directly:
```bash
rancher@harvester-node-1:~> cat ~/.ssh/authorized_keys 

ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
```

So the original configuration on the cluster cant' seem to be overwritten at least with ~/.ssh/authorized_keys - either through:
```yaml
    stages:
      network:
        - authorized_keys:
            rancher:
```
Or through:
```yaml
    stages:
      fs:
        - name: "write authorized_keys file"
          commands:
            - echo "" > /home/rancher/.ssh/authorized_keys
```
