### ISSUE TITLE
[ENHANCEMENT] Allow adding `Checksum` when creating a new `Image` from URL

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5141]
**Is your enhancement related to a problem? Please describe.**

When creating a new `Image` from `URL`, it would be great to specify the expected SHA512 checksum to do a validation after download. This feature is already available in the Longhorn UI. And since Harvester uses Longhorn's `BackingImage` for the images under the hood, the functionality is already given.

![grafik](https://github.com/harvester/harvester/assets/1897962/de929f6d-7d98-4e16-978c-eab719c9520a)

**Describe the solution you'd like**
Add a input field in the UI to specify the SHA512 checksum of the downloaded file. Under the hood, the `BackingImage` API `checksum` field is populated with the `checksum` entered in the UI.

```
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: foo
  namespace: longhorn-system
spec:
  checksum: xxxxxx
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by votdev** [comment]
The backend seems to supports this already.

```
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: image-systemrescue
  namespace: default
spec:
  retry: 0
  checksum: "10a3145a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35"
  displayName: systemrescue-11.00-amd64.iso
  sourceType: download
  url: https://fastly-cdn.system-rescue.org/releases/11.00/systemrescue-11.00-amd64.iso
```

Modify the `checksum` to make it invalid.

![grafik](https://github.com/harvester/harvester/assets/1897962/d8c0af71-7768-42fb-a906-74d1de02c342)
