### ISSUE TITLE
[BUG] Incomplete Documentation for Installation Options

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester#5146]
**Describe the bug**

The [documentation](https://docs.harvesterhci.io/v1.3/install/harvester-configuration) for the installer configuration is missing several fields. Both descriptions of what the fields do as well as examples or specifications for the expected input is missing

**To Reproduce**

Read the [documentation](https://docs.harvesterhci.io/v1.3/install/harvester-configuration) and compare with [actually available fields](https://github.com/harvester/harvester-installer/blob/master/pkg/config/config.go)

**Expected behavior**
All fields accepted in the configuration YAML should be documented
In particular:
```
os:
  persistentStatePaths:
  sshd:
  
install:
  forceGpt:
  role:
  withNetImages:
  Webhooks:
  persistentPartitionSize:
  configUrl:
  skipchecks:
  automatic:
  
system_settings:
  additional-ca:
  cluster-registration-url:
  ui-index:
  ui-path:
  ui-source:
  volume-snapshot-class:
  backup-target:
  upgrade-checker-enabled:
  upgrade-checker-url:
  release-download-url:
  log-level:
  ssl-certificates:
  ssl-parameters:
  support-bundle-image:
  support-bundle-namespaces:
  support-bundle-timeout:
  default-storage-class:
  http-proxy:
  vm-force-reset-policy:
  overcommit-config:
  vip-pools:
  containerd-registry:
```

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: v1.2.x, v.1.3.x

**Additional context**
In a similar context, [seeder](https://github.com/harvester/seeder) is not able to propagate all fields from the cluster definition to the installers configuration. This probably doesn't affect users badly, but it's a major pain for internal testing

**Comment by irishgordo** [comment]
Somewhat related as well to install options w/ regards to Elemental Toolkit CloudInit (mappings, stages, etc):
https://github.com/harvester/harvester/issues/4708#issuecomment-1936445884

**Comment by jillian-maroket** [comment]
@m-ildefons I scanned the doc and found that many of the fields that you listed are already there. I'll add descriptions and sample code (if necessary) with help from @bk201. Structure and navigation are major issues so I'll work on those as well.

```
os:
  persistentStatePaths: - In /install/harvester-configuration.md
  sshd: - In /install/harvester-configuration.md
  
install:
  forceGpt: - NOT DOCUMENTED
  role: - In /install/harvester-configuration.md
  withNetImages: - NOT DOCUMENTED
  Webhooks: - NOT DOCUMENTED
  persistentPartitionSize: - In /install/harvester-configuration.md
  configUrl: - NOT DOCUMENTED
  skipchecks: - In /install/harvester-configuration.md
  automatic: - In /install/harvester-configuration.md

system_settings:
  additional-ca: - In advanced/index/settings.md
  cluster-registration-url: - In advanced/index/settings.md
  ui-index: - In advanced/index/settings.md
  ui-path: - NOT DOCUMENTED
  ui-source: - In advanced/index/settings.md
  volume-snapshot-class: - NOT DOCUMENTED
  backup-target: - In advanced/index/settings.md
  upgrade-checker-enabled: - In advanced/index/settings.md
  upgrade-checker-url: - In advanced/index/settings.md
  release-download-url: - In advanced/index/settings.md
  log-level: - In advanced/index/settings.md
  ssl-certificates: - In advanced/index/settings.md
  ssl-parameters: - In advanced/index/settings.md
  support-bundle-image: - In advanced/index/settings.md
  support-bundle-namespaces: - In advanced/index/settings.md
  support-bundle-timeout: - In advanced/index/settings.md
  default-storage-class: - NOT DOCUMENTED
  http-proxy: - In advanced/index/settings.md
  vm-force-reset-policy: - In advanced/index/settings.md
  overcommit-config: - In advanced/index/settings.md
  vip-pools: - In advanced/index/settings.md
  containerd-registry: - In advanced/index/settings.md
```

Note: [system-settings](https://docs.harvesterhci.io/v1.3/install/harvester-configuration/#system_settings) in the **Harvester Configuration** file links to the [**Settings**](https://docs.harvesterhci.io/v1.3/advanced/index/) file in the **Advanced** section.
