### ISSUE TITLE
[BUG] storage class name conflicts for different namespace vmimages with a same name

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5165]
**Describe the bug**

We use `longhorn-<vmimage name>` as storage class name. The StorageClass doesn't have namesapce, but vmimage has. If there are same vmimage name in different namespace, storage class name will be conflicts.

https://github.com/harvester/harvester/blob/1e8c677c49005dfd312c7143f23a2632b83c42e5/pkg/controller/master/image/vm_image_controller.go#L214-L217

**To Reproduce**
1. Create a Harvester.
2. Using terraform to create two vmimage `default/test-image` and `harvester-public/test-image`.
3. After two vmimage are ready, deleting `default/test-image`.
4. Create a VM with `harvester-public/test-image` vmimage. The root disk PVC can't be provisioned.

**Expected behavior**
The storage class name doesn't conflict.

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Comment by bk201** [comment]
We can only support this with a Harvester version plus some Rancher patch versions because the Rancher need to have the updated node driver included. For example.

~~Harvester v1.5.0 + Rancher v2.8.x~~
~~Harvester v1.5.0 + Rancher v2.9.3~~
Harvester v1.5.0 + Rancher v2.11.0

Update: Harvester v1.5.0 will only support Rancher v2.11

**Comment by bk201** [comment]
The fix won't be backport to v1.3/v1.4 because the node drivers in supported Ranchers might not support this change.
In Harvester v1.5.0, we'll support only Rancher v2.11. In this way, we can assure Rancher has a correct node driver.

**Comment by WebberHuang1118** [comment]
I will create a new PR after [VM Image Controller, Webhook and Download/Upload Refactor for Various Backend Support](https://github.com/harvester/harvester/pull/7170) is merged.

**Comment by bk201** [comment]
move to 1.6.0 and target Rancher 2.12.0

**Comment by Vicente-Cheng** [comment]
Hi @WebberHuang1118, 
Any update on this issue? I saw the above PRs were merged.
Thanks!

**Comment by WebberHuang1118** [comment]
> Hi [@WebberHuang1118](https://github.com/WebberHuang1118), Any update on this issue? I saw the above PRs were merged. Thanks!

Hi @Vicente-Cheng 

This ticket will require a new implementation following the introduction of [VM Image Multiple Backend Support](https://github.com/harvester/harvester/blob/master/enhancements/20241227-vm-image-multiple-backend-support.md). 

I'm currently working on it and will provide updates as progress is made. Thanks!

**Comment by Vicente-Cheng** [comment]
moved to next milestone

**Comment by DamiaSan** [comment]
Hi @WebberHuang1118 , what solution do you suggest? We could put vmimage namespace's name before the prefix `longhorn`, or put a progressive after vmimage's name. What else?

**Comment by DamiaSan** [comment]
Any idea @Vicente-Cheng @FrankYang0529 ?

**Comment by WebberHuang1118** [comment]
> Hi [@WebberHuang1118](https://github.com/WebberHuang1118) , what solution do you suggest? We could put vmimage namespace's name before the prefix `longhorn`, or put a progressive after vmimage's name. What else?

You may refer to @FrankYang0529’s [PR](https://github.com/harvester/harvester/pull/5459), which essentially uses the VMI’s UUID to name the related StorageClass and avoid conflicts.

[PR 5459](https://github.com/harvester/harvester/pull/5459) was reverted due to a compatibility issue with Terraform. Since the VM Image now has a new framework to support various backends ([see here](https://github.com/harvester/harvester/pull/7170)), the original PR needs to be redesigned to fit the current VMI framework.

**Comment by DamiaSan** [comment]
Hi @FrankYang0529 , about the **Case 4: Create VM Template without error** in your [PR](https://github.com/harvester/harvester/pull/5459), could you explain the steps to do for _generating Template with data_? Is it related to https://docs.harvesterhci.io/v1.7/api/create-namespaced-virtual-machine-image? If so, could you make a real example?
Thanks.

**Comment by FrankYang0529** [comment]
@DamiaSan You can just click `Generate Template` on a VM and there is a `With Data` checkbox.

<img width="1309" height="731" alt="Image" src="https://github.com/user-attachments/assets/390d98ad-6a59-423a-8846-9ad8d6179ef4" />
<img width="602" height="312" alt="Image" src="https://github.com/user-attachments/assets/25ab586e-93e6-4987-8b1c-83a951adf642" />

**Comment by DamiaSan** [comment]
Related PR: https://github.com/harvester/harvester/pull/9392
The test plan is in the description of the PR.

**Comment by m-ildefons** [comment]
@FrankYang0529 I can not reproduce the issue with Harvester v1.6.1 using the web UI. Is this issue limited to the Terraform provider?

**Comment by ravarga** [comment]
Yes it is TF only issue

**Comment by Vicente-Cheng** [comment]
Since this one is the TF only issue, keep it on severity 2

**Comment by m-ildefons** [comment]
It seems that this issue is not just limited to the Terraform provider, since the following manifest would also create two problematic images:
```yaml
---
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: harvester-longhorn
  name: test-image
  namespace: harvester-public
spec:
  backend: backingimage
  displayName: public-test
  sourceType: download
  storageClassParameters:
    migratable: 'true'
    numberOfReplicas: '1'
    staleReplicaTimeout: '30'
  targetStorageClassName: harvester-longhorn
  url: http://192.168.0.254/artifacts/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2
---
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: harvester-longhorn
  name: test-image
  namespace: default
spec:
  backend: backingimage
  displayName: public-test
  sourceType: download
  storageClassParameters:
    migratable: 'true'
    numberOfReplicas: '1'
    staleReplicaTimeout: '30'
  targetStorageClassName: harvester-longhorn
  url: http://192.168.0.254/artifacts/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2
```
Therefore it can't be fixed only in the Terraform provider.
We should therefore go forward with the proposed solution in https://github.com/harvester/harvester/pull/9392
rather than trying to fix it only in the Terraform provider.
However the Terraform provider should probably behave more similar to the web UI to make the user experience more consistent.
What do you think, @Vicente-Cheng ?
