### ISSUE TITLE
[BUG] Existing agent Pods are not upgraded after harvester-vm-dhcp-controller is upgraded

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5188]
**Describe the bug**

We introduced the agent upgrade in harvester/vm-dhcp-controller#17. However, a later fix (harvester/vm-dhcp-controller#22) shadowed the original execution path. Currently, agent upgrade feature is broken.

**To Reproduce**

1. Prepare a Harvester cluster in v1.2.1
2. Install the harvester-vm-dhcp-controller add-on
3. Enable the add-on
4. Create an IPPool object
5. Make sure the agent Pod is running with v0.2.1 image
6. Upgrade harvester-vm-dhcp-controller to `main-head` by editing its Addon object
7. You'll see the controller and webhook Pods are upgraded, but not the agent

**Expected behavior**

Agent Pods should also be upgraded by the controller.

**Support bundle**

N/A

**Environment**
 - Harvester ISO version: v1.2.1 (harvester-vm-dhcp-controller v0.2.1)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

Users encountering this issue could manually delete the agent Pods to make the controller recreate them with the new image as a workaround.

**Comment by w13915984028** [comment]
Should this feature be available in v1.2.1, or limit it to only be available in 1.3.0+?

**Comment by starbops** [comment]
This should be Harvester-version agnostic. I just test it on Harvester v1.2.1 cluster. Officially, it should be used with Harvester v1.3.0+.

**Comment by w13915984028** [comment]
If we limit it to be in harvester v1.3.0+, then the chart can have some checks.

e.g. Rancher charts https://github.com/rancher/charts/commit/ecee848be09eb1fa34b47e10bb8640b619e8e70e#diff-08c65c1b5ef8384ef0200558777c52f4110afcbbacc880ac5375d555ca97ee3e has two annotations to control:
```
      catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.30.0-0'
..
      catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'
```

It does not make too much sense to install it on v1.2.1 and then upgrade to v1.3.0. If not supported, just let installation in v1.2.1 failed.

**Comment by starbops** [comment]
Thanks for the suggestion. But I think that's a different topic we should track in a new issue. This issue is talking about upgrading the harvester-vm-dhcp-controller itself. As an experimental add-on, it can be upgraded out-of-band.

**Comment by lanfon72** [comment]
@starbops please add milestone, thanks

**Comment by m-ildefons** [comment]
Validation instructions didn't work for me:
- Harvester version v1.2.1 is already released and this issue is planned for v1.3.0 milestone
- Unclear which IPPool object is meant: `ippools.crd.projectcalico.org`, `ippools.loadbalancer.harvesterhci.io`, `ippools.network.harvesterhci.io`, `ippools.whereabouts.cni.cncf.io`
- The addon installs a chart from the `charts.harvesterhci.io` repository, but there is no version `main-head` of the `harvester-vm-dhcp-controller` chart in that repository

As a result the validation instructions were modified as follows:

1. Prepare Harvester **v1.3.0-rc4** environment
2. Install `harvester-vm-dhcp-controller` addon from [experimental addons repository](https://github.com/harvester/experimental-addons/tree/main) in version **v0.2.0**
3. Enable the addon
4. Create both a **VM network** and `ippool.network.harvester.io` resource [as per instructions](https://github.com/harvester/vm-dhcp-controller?tab=readme-ov-file#usage)
5. Confirm Agent Pod is running container image version v0.2.1
6. Edit addon resource and specify version **v0.3.0** of the addon
7. Wait until the upgrade is complete _and_ the agent pod has been recreated, confirm the agent pod is running image version v0.3.0

---

1. Prepare Harvester v1.3.0-rc4 environment
```
│ ~ │► kubectl get settings.harvesterhci.io server-version 
NAME             VALUE
server-version   v1.3.0-rc4
```
2. Install `harvester-vm-dhcp-controller` addon v0.2.0
```
│ ~/repos/harvester/experimental-addons/harvester-vm-dhcp-controller │► cat harvester-vm-dhcp-controller.yaml 
apiVersion: harvesterhci.io/v1beta1                                                                                                                                                                                 
kind: Addon                                                                                                                                                                                                                                                                                                                                                                                                                              
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                                
  name: harvester-vm-dhcp-controller                                                                                                                                                                                                                                                                                                                                                                                                     
  namespace: harvester-system                                                                                                                                                                                                                                                                                                                                                                                                            
  labels:                                                                                                                                                                                                                                                                                                                                                                                                                                
    addon.harvesterhci.io/experimental: "true"                                                                                                                                                                                                                                                                                                                                                                                           
spec:                                                                                                                                                                                                               
  enabled: false                                                                                                                                                                                                                                                                                                                                                                                                                         
  repo: https://charts.harvesterhci.io                                                                                                                                                                                                                                                                                                                                                                                                   
  version: "v0.2.0"                                                                                                                                                                                                                                                                                                                                                                                                                      
  chart: harvester-vm-dhcp-controller                                                                                                                                                                                                                                                                                                                                                                                                    
  valuesContent: ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
│ ~/repos/harvester/experimental-addons/harvester-vm-dhcp-controller │► kubectl apply -f harvester-vm-dhcp-controller.yaml 
addon.harvesterhci.io/harvester-vm-dhcp-controller created  
```
3. Enable the addon
![Screenshot at 2024-03-07 16-25-19](https://github.com/harvester/harvester/assets/17141774/e139afaf-5e85-4ec2-996f-f910f989f54d)

4. Create both a VM network and `ippool.network.harvester.io`
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    network.harvesterhci.io/route: '{"mode":"auto","cidr":"10.168.0.0/24","gateway":"10.168.0.1","connectivity":"true"}'
  labels:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "1"
  name: net-48
  namespace: default
spec:
  config: '{"cniVersion":"0.3.1","name":"net-48","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":1,"ipam":{}}'
```
```
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  name: net-48
  namespace: default
spec:
  ipv4Config:
    cidr: 192.168.48.0/24
    dns:
    - 8.8.8.8
    domainName: foo.bar
    domainSearch:
    - foo.bar
    leaseTime: 300
    ntp:
    - pool.ntp.org
    pool:
      end: 192.168.48.90
      exclude:
      - 192.168.48.85
      start: 192.168.48.81
    router: 192.168.48.1
    serverIP: 192.168.48.77
  networkName: default/net-48
```

5. :white_check_mark: Confirm Agent Pod is running image version v0.2.1
```
│ ~/repos/harvester/experimental-addons/harvester-vm-dhcp-controller │► kubectl -n harvester-system describe pod default-net-48-agent
Name:             default-net-48-agent                                                        
Namespace:        harvester-system                                                            
Priority:         0                                                                          
Service Account:  harvester-vm-dhcp-controller-agent                                                                                                                                                                
Node:             harvester-node-1/10.168.0.31                                                                                                                                                                      
Start Time:       Thu, 07 Mar 2024 16:03:25 +0100                                                                                                                                                                                                                                                                                                                                                                                        
Labels:           network.harvesterhci.io/ippool-name=net-48                                                                                                                                                                                                                                                                                                                                                                             
                  network.harvesterhci.io/ippool-namespace=default                                                                                                                                                                                                                                                                                                                                                                       
                  network.harvesterhci.io/vm-dhcp-controller=agent                                                                                                                                                                                                                                                                                                                                                                       
Annotations:      cni.projectcalico.org/containerID: 1bac4e8ef2a7087de7c9e1fc4bf638409a07bcc7d2e82c18ab5a07c2768077f2                                                                                                                                                                                                                                                                                                                    
                  cni.projectcalico.org/podIP: 10.52.1.21/32                                                                                                                                                                                                                                                                                                                                                                             
                  cni.projectcalico.org/podIPs: 10.52.1.21/32                                                                                                                                                                                                                                                                                                                                                                            
                  k8s.v1.cni.cncf.io/network-status:                                                                                                                                                                                                                                                                                                                                                                                     
                    [{                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "name": "k8s-pod-network",                                                                                                                                                                  
                        "ips": [                                                                                                                                                                                    
                            "10.52.1.21"                                                                                                                                                                            
                        ],                                                                                                                                                                                          
                        "default": true,         
                        "dns": {}                                                                                                                                                                                   
                    },{                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "name": "default/net-48",                                                                                                                                                                   
                        "interface": "eth1",                                           
                        "mac": "e6:51:87:5f:ed:e2",                                    
                        "dns": {}                                                                                                                                                                                   
                    }]                                                           
                  k8s.v1.cni.cncf.io/networks: [{"namespace":"default","name":"net-48","interface":"eth1"}]
Status:           Running                                                             
IP:               10.52.1.21                                                            
IPs:                                                                                                                                                                                                                
  IP:  10.52.1.21                                                                
Init Containers:                                                                 
  ip-setter:                                                                                                                                                                                                                                                                                                                                                                                                                             
    Container ID:  containerd://45ed7cb01434b3d516e3c3d0b9a6732bbc63e1f334df4fcdeb4a3bac7bd735f0                                                                                                                    
    Image:         busybox                                                                                                                                                                                          
    Image ID:      docker.io/library/busybox@sha256:478209e7be50e5f5c9fd47a6a71d43c119dd44c393160e49dc4bb86f99a439de                                                                                                
    Port:          <none>                                                                                                                                                                                           
    Host Port:     <none>                                                                                                                                                                                           
    Command:                                                                                                                                                                                                                                                                                                                                                                                                                             
      /bin/sh                                                                                                                                                                                                       
      -c                                                                                                                                                                                                            
                                                                                                                                                                                                                    
      #!/usr/bin/env sh                                                                      
      set -ex                                                                                
                                                                                                                                                                                                                    
      ip address flush dev eth1                                                                                                                                                                                     
      ip address add 192.168.48.77/24 dev eth1                                               
                                                                                             
    State:          Terminated                                                                                                                                                                                      
      Reason:       Completed                                                                         
      Exit Code:    0                                                                                                                                                                                               
      Started:      Thu, 07 Mar 2024 16:03:49 +0100                                          
      Finished:     Thu, 07 Mar 2024 16:03:49 +0100                                          
    Ready:          True                                                                                                                                                                                            
    Restart Count:  0                                                                            
    Environment:    <none>                                                                                                                                                                                          
    Mounts:                                                                                                                                                                                                         
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6tjv2 (ro)               
Containers:                                                                                       
  agent:                                                                                                                                                                                                            
    Container ID:  containerd://df153619b769cfa6cc8032910673e519b1149e1c96afa67edfe6801143869fa1                                                                                                                                                                                                                                                                                                                                         
    Image:         rancher/harvester-vm-dhcp-agent:v0.2.1                                                                                                                                                                                                                                                                                                                                                                                
    Image ID:      docker.io/rancher/harvester-vm-dhcp-agent@sha256:4fb007e7a7de98c86196d61a157652e73175f786f9511cbeace47e9cb0130933                                                                                                                                                                                                                                                                                                     
    Port:          <none>                                                                                                                                                                                                                                                                                                                                                                                                                
    Host Port:     <none>                                                                                                                                                                                                                                                                                                                                                                                                                
    Args:                                                                                                                                                                                                                                                                                                                                                                                                                                
      --ippool-ref                                                                                                                                                                                                  
      default/net-48                                                                                                                                                                                                                                                                                                                                                                                                                     
    State:          Running                                                                                                                                                                                                                                                                                                                                                                                                              
      Started:      Thu, 07 Mar 2024 16:04:40 +0100                                                                                                                                                                                                                                                                                                                                                                                      
    Ready:          True                                                                                                                                                                                                                                                                                                                                                                                                                 
    Restart Count:  0                                                                                                                                                                                                                                                                                                                                                                                                                    
    Liveness:       http-get http://:8080/healthz delay=0s timeout=1s period=10s #success=1 #failure=3                                                                                                                                                                                                                                                                                                                                   
    Readiness:      http-get http://:8080/readyz delay=0s timeout=1s period=10s #success=1 #failure=3                                                                                                               
    Environment:                                                                                                                                                                                                                                                                                                                                                                                                                         
      VM_DHCP_AGENT_NAME:  default-net-48-agent                                                                                                                                                                     
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6tjv2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-6tjv2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason          Age    From               Message
  ----    ------          ----   ----               -------
  Normal  Scheduled       8m9s   default-scheduler  Successfully assigned harvester-system/default-net-48-agent to harvester-node-1
  Normal  AddedInterface  8m9s   multus             Add eth0 [10.52.1.21/32] from k8s-pod-network
  Normal  AddedInterface  8m9s   multus             Add eth1 [] from default/net-48
  Normal  Pulling         8m9s   kubelet            Pulling image "busybox"
  Normal  Pulled          7m46s  kubelet            Successfully pulled image "busybox" in 23.157336629s (23.157350562s including waiting)
  Normal  Created         7m46s  kubelet            Created container ip-setter
  Normal  Started         7m45s  kubelet            Started container ip-setter
  Normal  Pulling         7m45s  kubelet            Pulling image "rancher/harvester-vm-dhcp-agent:v0.2.1" 
  Normal  Pulled          6m54s  kubelet            Successfully pulled image "rancher/harvester-vm-dhcp-agent:v0.2.1" in 51.169253394s (51.169264444s including waiting)
  Normal  Created         6m54s  kubelet            Created container agent
  Normal  Started         6m54s  kubelet            Started container agent
```
6. Edit addon resource and specify version v0.3.0 of the addon
![Screenshot at 2024-03-07 16-29-26](https://github.com/harvester/harvester/assets/17141774/7ab9ec5d-2abf-4ed9-976a-9ee3e07965c4)

7. :white_check_mark: Wait until the upgrade is complete _and_ the agent pod has been recreated, confirm the agent pod is running image version v0.3.0
```
│ ~/repos/harvester/experimental-addons/harvester-vm-dhcp-controller │► kubectl -n harvester-system describe pod default-net-48-agent 
Name:             default-net-48-agent
Namespace:        harvester-system
Priority:         0
Service Account:  harvester-vm-dhcp-controller-agent
Node:             harvester-node-2/10.168.0.32
Start Time:       Thu, 07 Mar 2024 16:13:49 +0100
Labels:           network.harvesterhci.io/ippool-name=net-48
                  network.harvesterhci.io/ippool-namespace=default
                  network.harvesterhci.io/vm-dhcp-controller=agent
Annotations:      cni.projectcalico.org/containerID: 5ebb135c32b77d15c10b364561d02ac419eec74a63ab1a2f30aeed6fbe7d7aa0
                  cni.projectcalico.org/podIP: 10.52.2.24/32
                  cni.projectcalico.org/podIPs: 10.52.2.24/32
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "k8s-pod-network",
                        "ips": [
                            "10.52.2.24"
                        ],
                        "default": true,
                        "dns": {}
                    },{
                        "name": "default/net-48",
                        "interface": "eth1",
                        "mac": "5a:09:ac:fa:ce:f6",
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks: [{"namespace":"default","name":"net-48","interface":"eth1"}]
Status:           Running
IP:               10.52.2.24
IPs:
  IP:  10.52.2.24
Init Containers:
  ip-setter:
    Container ID:  containerd://130d7ac14824823258cd7cf1570300fcf9d135313cc9249fd3755b1f4419f0aa
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:478209e7be50e5f5c9fd47a6a71d43c119dd44c393160e49dc4bb86f99a439de
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      
      #!/usr/bin/env sh
      set -ex
      
      ip address flush dev eth1
      ip address add 192.168.48.77/24 dev eth1
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 07 Mar 2024 16:13:58 +0100
      Finished:     Thu, 07 Mar 2024 16:13:58 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nxfdr (ro)
Containers:
  agent:
    Container ID:  containerd://3bcaada9a147ec786c0998b4d54bb1339dde075c803ff9481c6a97f42015c5cd
    Image:         rancher/harvester-vm-dhcp-agent:v0.3.0
    Image ID:      docker.io/rancher/harvester-vm-dhcp-agent@sha256:951cfa5b0cc9cec588c6be2b7232fe3928a039ea3f46d0a5ec8a35f1d8f407a3
    Port:          <none>
    Host Port:     <none>
    Args:
      --ippool-ref
      default/net-48
    State:          Running
      Started:      Thu, 07 Mar 2024 16:14:15 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      VM_DHCP_AGENT_NAME:  default-net-48-agent
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nxfdr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-nxfdr:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       16m   default-scheduler  Successfully assigned harvester-system/default-net-48-agent to harvester-node-2
  Normal  AddedInterface  16m   multus             Add eth0 [10.52.2.24/32] from k8s-pod-network
  Normal  AddedInterface  16m   multus             Add eth1 [] from default/net-48
  Normal  Pulling         16m   kubelet            Pulling image "busybox"
  Normal  Pulled          16m   kubelet            Successfully pulled image "busybox" in 8.228357413s (8.228370668s including waiting)
  Normal  Created         16m   kubelet            Created container ip-setter
  Normal  Started         16m   kubelet            Started container ip-setter
  Normal  Pulling         16m   kubelet            Pulling image "rancher/harvester-vm-dhcp-agent:v0.3.0"
  Normal  Pulled          15m   kubelet            Successfully pulled image "rancher/harvester-vm-dhcp-agent:v0.3.0" in 16.515071431s (16.515080064s including waiting)
  Normal  Created         15m   kubelet            Created container agent
  Normal  Started         15m   kubelet            Started container agent
```

:white_check_mark: Validated successfully using Harvester v1.3.0-rc4
