### ISSUE TITLE
[BUG] Reserved IP addresses should be skipped when checking the embedded DHCP server IP in validating admission webhook

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5225]
**Describe the bug**

In Harvester's `vm-dhcp-controller` design, the embedded DHCP server's IP address could reside within the allocatable pool range when creating an IPPool object. The IP address that is occupied by the DHCP server will be marked as `RESERVED` under the `.status.ipv4.allocated` field:

```
...
spec:
  ipv4Config:
    cidr: 10.52.0.0/16
    leaseTime: 300
    pool:
      end: 10.52.255.254
      start: 10.52.0.2
    serverIP: 10.52.0.2
  networkName: default/overlap-net
status:
  ...
  ipv4:
    allocated:
      10.52.0.2: RESERVED
      10.52.221.40: 1a:63:91:aa:4a:a6
    available: 65531
    used: 1
```

However, we didn't respect reserved IP addresses in the admission webhook. As `harvester-vm-dhcp-controller`'s log indicated, the update request was rejected by `harvester-vm-dhcp-controller-webhook`:

```
time="2024-02-27T01:26:56Z" level=error msg="error syncing 'default/overlap-net': handler vm-dhcp-ippool-controller: admission webhook \"validator.harvester-system.harvester-vm-dhcp-controller-webhook\" denied the request: Internal error occurred: could not update IPPool default/overlap-net because server ip 10.52.0.2 is already allocated, requeuing"
```

Also, the following line could be found in the webhook's log:

```
time="2024-02-27T02:07:49Z" level=error msg="could not update IPPool default/overlap-net because server ip 10.52.0.2 is already allocated"
```

With that said, the entire IP allocation/deallocation process is still in a good shape. Newly created VMs could get IP addresses from the embedded DHCP server.

**To Reproduce**

1. Enable the harvester-vm-dhcp-controller add-on
2. Create a VM Network
3. Create an IPPool object whose `serverIP` falls into the range of the pool, for example:
   ```
   apiVersion: network.harvesterhci.io/v1alpha1
   kind: IPPool
   metadata:
     namespace: default
     name: overlap-net
   spec:
     ipv4Config:
       serverIP: 10.52.0.2
       cidr: 10.52.0.0/16
       pool:
         start: 10.52.0.2
         end: 10.52.255.254
       leaseTime: 300
     networkName: default/overlap-net
   ```
5. Observe the controller and webhook's log

**Expected behavior**

Not showing such messages in both controller and webhook's log.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1 (with harvester-vm-dhcp-controller v0.2.1)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

N/A

**Comment by starbops** [comment]
For such cases, the agent Pod cannot be cleaned up after the IPPool object is deleted. Users need to manually remove the agent Pod if they want to re-create the same IPPool object.

**Comment by irishgordo** [comment]
@starbops tested off of v1.3-head
And version 0.3.0 charts:
```
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  labels:
    addon.harvesterhci.io/experimental: "true"
  namespace: harvester-system
  name: harvester-vm-dhcp-controller
spec:
  chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io
  valuesContent: |
    image:
      repository: starbops/harvester-vm-dhcp-controller
      tag: fix-5225-head
    agent:
      image:
        repository: starbops/harvester-vm-dhcp-agent
        tag: fix-5225-head
    webhook:
      image:
        repository: starbops/harvester-vm-dhcp-webhook
        tag: fix-5225-head
  version: 0.3.0
```
And this looks good :smile: 
I'll go ahead and close this out :+1: 
![Screenshot from 2024-03-11 17-21-21](https://github.com/harvester/harvester/assets/5370752/25ddd5fa-bf27-4194-b253-993abcf17cee)
