### ISSUE TITLE
[BUG] CloudInit resource conditions [OutOfSync, Present] have zero-value for last transition time if file is removed

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5245]
**Describe the bug**

When the stat call fails due to the file having been removed, the CloudInit controller leaves a zero-value timestamp for the transition time.

```yaml
status:
  rollouts:
    harvester-dngmf:
      conditions:
      - lastTransitionTime: "2024-02-28T22:31:23Z"
        message: ""
        reason: CloudInitApplicable
        status: "True"
        type: Applicable
      - lastTransitionTime: "1970-01-01T00:00:00Z" <--------
        message: 'Open file: open /host/oem/99_ssh.yaml: no such file or directory'
        reason: CloudInitError
        status: Unknown
        type: OutOfSync
      - lastTransitionTime: "1970-01-01T00:00:00Z" <--------
        message: 99_ssh.yaml is absent from /oem
        reason: CloudInitAbsentFromDisk
        status: "False"
        type: Present
```

**To Reproduce**

1. Apply a CloudInit resource:

```
apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access
spec:
  matchSelector: {}
  filename: 99_ssh.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPCUNsQEnKj0nl1GS07Qr5RDCCbCim4wu06hCzQZDmTk ckuehl@suselaptop
```

2. Set `paused: true` in the CloudInit resource
3. Remove the file from the node `rm /oem/99_ssh.yaml`

**Expected behavior**

The last transition times should either be the time the controller removed the file or the time that it first noticed that it was removed.

Here is where the Stat call fails: https://github.com/harvester/node-manager/blob/786b1b222bba52272a9afe70f0a16a3c61ae564f/pkg/controller/cloudinit/controller.go#L160

But the values are unconditionally passed in regardless

https://github.com/harvester/node-manager/blob/786b1b222bba52272a9afe70f0a16a3c61ae564f/pkg/controller/cloudinit/controller.go#L186

https://github.com/harvester/node-manager/blob/786b1b222bba52272a9afe70f0a16a3c61ae564f/pkg/controller/cloudinit/controller.go#L190
