### ISSUE TITLE
[BUG] After cold reboot in a period of time or restart node machine, all vms stuck in "Starting" state

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5272]
**Describe the bug**

With Harvester already have some virtual machines running, power off the node machine, wait a period of time then power on the machine. 

* Checking all the vms stuck in the Starting state 
![image](https://github.com/harvester/harvester/assets/29251855/bb81eba9-701c-4c61-8b91-08baa71878dd)
 
* Check the events of vm, it stuck in the action with message
```
Pod virt-launcher-vm1-nginx-ltmzp
Container image "registry.suse.com/suse/sles/15.5/virt-launcher:1.1.0-150500.8.6.1" already present on machine
```

![image](https://github.com/harvester/harvester/assets/29251855/24ee541e-4bdc-4e7c-9f3c-3690f240565d)

* **When we restart the node machine, we also have the chance to encounter the same result**

**To Reproduce**
1. Create a vlan 1 network on management interface
2. Create two VMs on vlan1 and mgmt network with nginx service installed
  ```
  #cloud-config
  package_update: true
  packages:
    - qemu-guest-agent
    - nginx
  runcmd:
    - - systemctl
      - enable
      - --now
      - qemu-guest-agent.service
      - systemctl start nginx
      - systemctl enable nginx
  password: 123456
  chpasswd: { expire: false }
  ssh_pwauth: True
  ``` 
3. Set vm labels to each VM
4. Create two IP pools one for default and another for harvester-public namespace
5. Create some load balancer set on the above IP pools and bind to the
6. Power off the Harvester node VM 
7. Power on the Harvester node VM again after 1 hour
8. Check the VM status and events

**Expected behavior**

**Support bundle**

[supportbundle_e9d19d9f-3065-416e-b76d-1dcd5bf5d828_2024-03-01T10-31-24Z.zip](https://github.com/harvester/harvester/files/14459895/supportbundle_e9d19d9f-3065-416e-b76d-1dcd5bf5d828_2024-03-01T10-31-24Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine

**Additional context**
This issue was first found in #4033 but in Harvester v1.3.0-rc release we can still hit the issue. 
And since the virtual machine event display different message. 
After discussion, we create a separate issue to track this behavior.

**Comment by bk201** [comment]
@TachunLin  it's a normal event on any VM start.
> Check the events of vm, it stuck in the action with message
> ```
> Pod virt-launcher-vm1-nginx-ltmzp
> Container image "registry.suse.com/suse/sles/15.5/virt-launcher:1.1.0-150500.8.6.1" already present on machine
> ```


@w13915984028 Can you help verify if this one is duplicated with https://github.com/harvester/harvester/issues/5109 ?

**Comment by w13915984028** [comment]
From the support bundle, there is such keywords `not a device node` in file `yamls/namespaced/default/v1/pods.yaml`, this is exact the root cause identified on #5109 .

The #4033 looks to be fixed in new version.

```
    name: virt-launcher-vm1-nginx-ltmzp
    namespace: default
...
    containerStatuses:
    - image: registry.suse.com/suse/sles/15.5/virt-launcher:1.1.0-150500.8.6.1
      imageID: "null"
      lastState: {}
      name: compute
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: 'failed to generate container "f5160682ae54ffed74327b28f3b6c08ae181dc146a2ed7f4927a39dabb2609f5"
            spec: failed to generate spec: not a device node'
          reason: CreateContainerError
```
