### ISSUE TITLE
[BUG] Harvester VM DHCP Controller Doesn't Allocate/Exclude IPPool `spec.ipv4Config.serverIP` if `serverIP` is within pool's start -> end

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5273]
**Describe the bug**
The [Harvester VM DHCP Controller Addon](https://github.com/harvester/experimental-addons/blob/main/harvester-vm-dhcp-controller/harvester-vm-dhcp-controller.yaml) it the IPPool `spec.ipv4Config.serverIP` is within the range of `spec.ipv4Config.pool.start` -> `spec.ipv4Config.pool.end` , it's not added to the `status.ipv4` 's allocated / excluded.

**Pre-requisites**
1. Have a Harvester cluster off of v1.3-head
1. Build the addon chart: `kubectl create -f https://raw.githubusercontent.com/harvester/experimental-addons/main/harvester-vm-dhcp-controller/harvester-vm-dhcp-controller.yaml` 
1. Enable the addon
1. Have a NON-DHCP Network within your infrastructure, IE: a network that accepts VLAN tagging but does not have a functioning DHCP server
1. Create a Cluster-Network that ties into your infrastructure
1. Create a Cluster Network's Network-Config that ties into your infrastructure
1. Build a VM Network called `test-net` (in the default namespace) that ties into Cluster-Network-Network-Config -> Cluster-Network ( your underlying network infrastructure )
1. Have [yq installed](https://github.com/mikefarah/yq)

**To Reproduce**
1. Please note, these are rough steps as your underlying network infrastructure will dictate what this needs to be.  Create a YAML CRD of IPPool that takes the sample of this:
```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    serverIP: 192.168.30.125
    cidr: 192.168.30.1/24
    pool:
      start: 192.168.30.2
      end: 192.168.30.250
    router: 192.168.30.1
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    leaseTime: 300
  networkName: default/test-net
```
2.  Create a `VirtualMachineNetworkConfig` Object that takes the shape of something like this YAML:
```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: VirtualMachineNetworkConfig
metadata:
  name: test-vmnetcfg
  namespace: default 
spec:
  vmName: test-vmnetcfg
  networkConfigs:
  - macAddress: "fa:cf:8e:50:82:fc"
    networkName: default/test-net
    ipAddress: 192.168.30.120
```
3.  Get the output of: 
```
echo -e "\n\nserverIP of IPPool Created Is:\n $(kubectl get ippls.network test-net -o yaml | yq .spec.ipv4Config.serverIP) \n\nAND- to note, the current loadout of the IPPool is:\n\n $(kubectl get ippls.network test-net -o yaml | yq .spec.ipv4Config)\n\nAdditionally, we have the allocation/exclusion of:\n\n$(kubectl get ippls.network test-net -o yaml | yq .status.ipv4)\n\nWe would expect the serverIP to be in the exclusion/allocated list in the status of the IPPool..."
```

**Expected behavior**
Since in this loadout, the server ip is 192.168.30.125 of the VM DHCP Controller, we would expect it to be excluded, since it sits within the pool's start and end.  But it is not excluded or showing that it's allocated.  Whereas the VirtualMachineNetworkConfig, is present and is showing that it's allocated.

**Environment**
 - Harvester ISO Version: v1.3-d60468f1-head 
 - Underlying Infrastructure: HP Proliant DL160 Gen9 + Custom Network Infrastructure through Ubiquiti Unifi

**Suggested Workaround**
Let's say your pool range is:
192.168.30.2 -> 192.168.30.250
Simply, don't set the `serverIP` address to be "within" that range, have it outside that range, like something like 192.168.30.251.

**Comment by starbops** [comment]
Hi @irishgordo Thank you for raising the ticket. If the embedded DHCP server's IP address is within the allocatable pool range, it should be marked as `RESERVED`. This behavior has been implemented and merged (ref: harvester/vm-dhcp-controller#15) into the main branch but has not yet been released. If you still have the environment up, please try to upgrade the `harvester-vm-dhcp-controller` add-on with the `main-head` tag to see if the issue still exists:

```
...
spec:
  chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io
  valuesContent: |
    image:
      tag: main-head
    agent:
      image:
        tag: main-head
    webhook:
      image:
        tag: main-head
  version: v0.2.0
```

The IPPool object should be something like the following:

```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"network.harvesterhci.io/v1alpha1","kind":"IPPool","metadata":{"annotations":{},"name":"test-net","namespace":"default"},"spec":{"ipv4Config":{"cidr":"192.168.30.1/24","dns":["1.1.1.1","8.8.8.8","8.8.4.4"],"leaseTime":300,"pool":{"end":"192.168.30.250","start":"192.168.30.2"},"router":"192.168.30.1","serverIP":"192.168.30.125"},"networkName":"default/test-net"}}
  creationTimestamp: "2024-03-03T15:30:29Z"
  finalizers:
  - wrangler.cattle.io/vm-dhcp-ippool-controller
  generation: 1
  name: test-net
  namespace: default
  resourceVersion: "348756059"
  uid: 55344cd8-1b09-4e6f-885c-7061928a0368
spec:
  ipv4Config:
    cidr: 192.168.30.1/24
    dns:
    - 1.1.1.1
    - 8.8.8.8
    - 8.8.4.4
    leaseTime: 300
    pool:
      end: 192.168.30.250
      start: 192.168.30.2
    router: 192.168.30.1
    serverIP: 192.168.30.125
  networkName: default/test-net
status:
  agentPodRef:
    image: rancher/harvester-vm-dhcp-agent:main-head
    name: default-test-net-agent
    namespace: harvester-system
    uid: e8050169-6513-44d3-bb22-cc63c1411f71
  conditions:
  - lastUpdateTime: "2024-03-03T15:32:39Z"
    status: "True"
    type: Registered
  - lastUpdateTime: "2024-03-03T15:32:39Z"
    status: "True"
    type: CacheReady
  - lastUpdateTime: "2024-03-03T15:33:08Z"
    status: "True"
    type: AgentReady
  - lastUpdateTime: "2024-03-03T15:30:29Z"
    status: "False"
    type: Stopped
  ipv4:
    allocated:
      192.168.30.125: RESERVED
    available: 248
    used: 0
  lastUpdate: "2024-03-03T15:32:40Z"
```

I hope that makes sense.

**Comment by irishgordo** [comment]
@starbops this works great :smile: :+1: 

Yielding:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065/vm-dhcp-controller on main✔
╰─± echo -e "\n\nserverIP of IPPool Created Is:\n $(kubectl get ippls.network test-net -o yaml | yq .spec.ipv4Config.serverIP) \n\nAND- to note, the current loadout of the IPPool is:\n\n $(kubectl get ippls.network test-net -o yaml | yq .spec.ipv4Config)\n\nAdditionally, we have the allocation/exclusion of:\n\n$(kubectl get ippls.network test-net -o yaml | yq .status.ipv4)\n\nWe would expect the serverIP to be in the exclusion/allocated list in the status of the IPPool..."


serverIP of IPPool Created Is:
 192.168.30.125 

AND- to note, the current loadout of the IPPool is:

 cidr: 192.168.30.1/24
dns:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
leaseTime: 300
pool:
  end: 192.168.30.250
  start: 192.168.30.2
router: 192.168.30.1
serverIP: 192.168.30.125

Additionally, we have the allocation/exclusion of:

allocated:
  192.168.30.125: RESERVED
available: 248
used: 0

We would expect the serverIP to be in the exclusion/allocated list in the status of the IPPool...
```

So it is indeed "RESERVED" now :smile: :+1: 


Rolled out via:
```
1. git clone https://github.com/harvester/vm-dhcp-controller.git
2. built the values.yaml:
spec:
  chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io
  valuesContent: |
    image:
      tag: main-head
    agent:
      image:
        tag: main-head
    webhook:
      image:
        tag: main-head
  version: v0.2.0
3. helm upgrade --install harvester-vm-dhcp-controller ./chart --namespace=harvester-system -f ../harvester-vm-dhcp-controller-values.yaml
4. Checked the replica sets to ensure new was in existence
5. created the ippool.yaml object resource
6. checked that object built
```


On:
- 3 node harvester  Version: v1.3-4372cbc4-head , hp proliant dl160 gen 9 

This looks great!
I'll go ahead and close this out :smile: 
Thanks again!
