### ISSUE TITLE
Project storage reservation quota

### ISSUE THREAD

**Issue by jcambronero** [harvester/harvester#5291]
**Is your enhancement related to a problem? Please describe.**
It's currently not possible to use the Rancher UI to configure a storage reservation quota for a project.

**Describe the solution you'd like**
Rancher allows to configure storage quota for regular Kubernetes projects, but not for Harvester projects (the Storage Reservation option is not available for Harvester projects):
![image](https://github.com/harvester/harvester/assets/6895571/f2ccb4b9-7ddd-44ee-8ac5-ab0a4247be11)

**Describe alternatives you've considered**
As a workaround this can be achieved by editing the project's YAML, e.g.:
```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-12345
spec:
  displayName: my-project
  namespaceDefaultResourceQuota:
    limit:
      requestsStorage: 300Gi
  resourceQuota:
    limit:
      requestsStorage: 300Gi
```

But it would be better to use the Rancher UI to configure the storage reservation quota.
