### ISSUE TITLE
[Question] How can I disable /debug/pprof on node_ip:6060 ?

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#5308]
When I access {$node_ip}:6060/debug/pprof/, I can see debug info on it.
![image](https://github.com/harvester/harvester/assets/38560218/c5279bdb-477a-49cb-99f8-59c1e7ccdd3b)
Can I disable /debug/pprof on {$node_ip}:6060, or limit its access permission?

It may related to node-disk-manager.
@https://github.com/harvester/node-disk-manager/blob/master/main.go#L14

**Comment by Vicente-Cheng** [comment]
Hi @W0n9,

I thought this related to [[ENHANCEMENT] Do not expose port 6060 with NDM](https://github.com/harvester/harvester/issues/4212#top)

It would be resolved with v1.3.0.

In the previous version, please change the parameter `profile-listen-address` to `""` to avoid enabling profiler by default

**Comment by W0n9** [comment]
> Hi @W0n9,
> 
> I thought this related to [[ENHANCEMENT] Do not expose port 6060 with NDM](https://github.com/harvester/harvester/issues/4212#top)
> 
> It would be resolved with v1.3.0.
> 
> In the previous version, please change the parameter `profile-listen-address` to `""` to avoid enabling profiler by default

I have applied args to container, LGTM, thanks
```yaml
spec:
      containers:
        - args:
            - '--profile-listen-address'
            - ''
          command:
            - node-disk-manager
```
