### ISSUE TITLE
[FEATURE] Support vGPU's with container workloads

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#5321]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

Harvester v1.3.0 introduces vGPU support. Combined with baremetal workload support introduced in v1.2.0, we need to allow users to leverage vGPU's with container workloads.

PCIDevices controller is already providing the device plugin which ensures the node objects always the correct capacity/allocation count for different vGPU profiles. 

However GPU enhanced workloads may need access to nvidia-container-runtime https://github.com/NVIDIA/nvidia-container-toolkit. 

We should investigate means to deploy this to the harvester cluster.

**Describe alternatives you've considered**

**Additional context**

**Comment by asettle** [comment]
Adding a note that this is for vGPU support for bare-metal workloads feature

**Comment by innobead** [comment]
I discussed this with @ibrokethecloud and moved it to 1.10.0 because the implementation approach is still being researched and will require more time. This will be listed as a known limitation for #5820. A notice should be included in the 1.9.0 release notes. 

cc @harvester/tpm @harvester/pm @harvester/release

**Comment by ibrokethecloud** [comment]
Install Harvester v1.9.0-rc2 or higher on 2 or more node cluster, where each Node has a GPU supporting vGPUs.

Please refer to HEP https://github.com/harvester/harvester/pull/11046 for details on how to setup environment and testing the changes.

**Comment by asc5543** [comment]
## Test result
Test PASS

## Environment
* Harvester ISO version: `v1.9.0-rc5`
* Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `2 node Baremetal`


## Test Scenario
### Preparation
1. <details> <summary> Install Harvester to 2 or more node cluster, where at least 2 nodes have supported GPU's </summary>

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/61a46597-d64a-49fc-8d7b-07065f623994" />

   </details>

1. <details> <summary> Enable PCIDevices controller </summary>

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/8e227405-b688-4dec-bb65-fadd4d99e787" />
    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/6a7bd3d4-0f5f-4022-9365-92200b947ce9" />

   </details>

1. <details> <summary> Enable nvidia-driver-toolkit with the correct AIE driver and Image Tag </summary>
    
    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/39b63ad8-fde9-4ba9-a694-e54692e42b62" />
    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/374d55b1-2431-4769-9ac2-c4a3ec686e44" />
    
   </details>

1. <details> <summary> Wait till SRIOVGPUDevice object is available </summary>

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/476a37e0-6381-422c-8bab-0f42a918613a" />

   </details>


### Test Steps

1. <details>
   <summary> ✔ Enable vGPU Device of hp-130
   </summary>

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/d5d63bd2-6da9-46ed-bad4-8bcfb138ca2e" />
    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/513b113d-b350-4cf6-bb27-b6fbcd1c985d" />
    
   </details>

1. <details>
   <summary> ✔ Use the label `harvesterhci.io/gpu-baremetal-workloads: "true"` to hp-142 for running containerized GPU workloads
   </summary>

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/5808a1de-dd60-4cec-b008-0db24b599ffc" />
    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/d7b82a4b-2014-439b-93d7-567d6d55fd1d" />

   </details>

1. <details>
   <summary> ✔ Apply the labels below to nodes running on `vGPU` workloads
   </summary>

    ```
    kubectl label node $NODENAME nvidia.com/gpu.deploy.operands=false
    ```

    ```
    hp-130-tink-system:~ # kubectl label node hp-130-tink-system nvidia.com/gpu.deploy.operands=false
    node/hp-130-tink-system labeled
    ```

    <img width="1915" height="1002" alt="Image" src="https://github.com/user-attachments/assets/f288f76e-7171-4a65-8913-b30bb03fb3bf" />

   </details>

1. <details>
   <summary> ✔ Install GPU operator directly on the harvester cluster
   </summary>

    ```yaml
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: gpu-operator
      namespace: kube-system
    spec:
      repo: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      version: v26.3.2
      targetNamespace: gpu-operator
      createNamespace: true
      valuesContent: |-
        cdi:
          nriPluginEnabled: true
        driver:
          repository: registry.suse.com/third-party/nvidia
          usePrecompiled: true
          version: 595 # This depends on the nvidia driver that works with your GPU architecture
    ``` 

    ```
    # kubectl create -f gpu-operator.yaml 
    helmchart.helm.cattle.io/gpu-operator created
    ```

   </details>

1. <details>
   <summary> ✔ Wait for GPU workloads to be deployed
   </summary>

    <img width="1915" height="972" alt="Image" src="https://github.com/user-attachments/assets/b523ec39-d9f9-4daf-8be9-b3cddf69bdaf" />
    
   </details>

1. <details>
   <summary> ✔ Run containerized workloads needing GPU workloads, check it uses hp-142's baremetal gpu
   </summary>
  
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: nbody-gpu-benchmark
      namespace: default
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cuda-container
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody
        args: ["nbody", "-gpu", "-benchmark"]
        resources:
          limits:
            nvidia.com/gpu: 1
    ```
    
    ```
    # kubectl create -f nbody-gpu-benchmark.yaml 
    pod/nbody-gpu-benchmark created
    ```

    ```
    # kubectl get pods
    NAME                  READY   STATUS      RESTARTS   AGE
    nbody-gpu-benchmark   0/1     Completed   0          44s
    ```

    ```
    Events:
      Type    Reason          Age    From               Message
      ----    ------          ----   ----               -------
      Normal  Scheduled       4m40s  default-scheduler  Successfully assigned default/nbody-gpu-benchmark to hp-142-tink-system
      Normal  AddedInterface  4m40s  multus             Add eth0 [10.52.1.46/32] from k8s-pod-network
      Normal  Pulling         4m39s  kubelet            spec.containers{cuda-container}: Pulling image "nvcr.io/nvidia/k8s/cuda-sample:nbody"
      Normal  Pulled          4m34s  kubelet            spec.containers{cuda-container}: Successfully pulled image "nvcr.io/nvidia/k8s/cuda-sample:nbody" in 5.202s (5.202s including waiting). Image size: 122383440 bytes.
      Normal  Created         4m34s  kubelet            spec.containers{cuda-container}: Container created
      Normal  Started         4m34s  kubelet            spec.containers{cuda-container}: Container started
    ```

    ```
    # kubectl logs nbody-gpu-benchmark
    Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
            -fullscreen       (run n-body simulation in fullscreen mode)
            -fp64             (use double precision floating point values for simulation)
            -hostmem          (stores simulation data in host memory)
            -benchmark        (run benchmark to measure performance) 
            -numbodies=<N>    (number of bodies (>= 1) to run in simulation) 
            -device=<d>       (where d=0,1,2.... for the CUDA device to use)
            -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
            -compare          (compares simulation results running once on the default GPU and once on the CPU)
            -cpu              (run n-body simulation on the CPU)
            -tipsy=<file.bin> (load a tipsy model file for simulation)
    
    NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
    
    > Windowed mode
    > Simulation data stored in video memory
    > Single precision floating point simulation
    > 1 Devices used for simulation
    GPU Device 0: "Ampere" with compute capability 8.6
    
    > Compute 8.6 CUDA device: [NVIDIA A2]
    10240 bodies, total time for 10 iterations: 8.353 ms
    = 125.539 billion interactions per second
    = 2510.785 single-precision GFLOP/s at 20 flops per interaction
    ```

   </details>

1. <details> <summary> ✔ Check SRIOVGPUDevice page, there should only hp-130 exist </summary>

    <img width="1915" height="972" alt="Image" src="https://github.com/user-attachments/assets/7ed1af7f-246c-4207-8910-d13d78223fb5" />

   </details>
