### ISSUE TITLE
[FEATURE] Create DHCP pools alongside VM Networks

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5356]
**Is your feature request related to a problem? Please describe.**

Users who want to leverage the [harvester-vm-dhcp-controller add-on](https://github.com/harvester/experimental-addons/tree/main/harvester-vm-dhcp-controller) to provide IP addresses to VMs must manually create IPPool objects by `kubectl` after VM Networks (NetworkAttachmentDefinitions) are made. Jumping between the dashboard and command line interface is inconvenient and cluttered regarding user experience.

We need a more integrated way to create VM Networks with in-cluster DHCP feature enabled.

**Describe the solution you'd like**

We already have the harvester-vm-dhcp-controller released as an experimental add-on, so the backend functionality is pretty self-contained. On the other hand, we'd like the Harvester dashboard to provide an additional sub-tab called **Pool (DHCP)** alongside the exiting **Basics** and **Route** sub-tabs under the VM Network creation/config page.

<img width="1725" alt="create-network-auto-3618d9cd389a84ca8185fb09b041592e" src="https://github.com/harvester/harvester/assets/1827717/a261e350-1ed1-430e-b50d-659ee1b4c1e1">

With the sub-tab selected, relevant fields will pop up for users to input the details for the to-be-created IPPool objects. A typical example of an IPPool object looks like the following:

```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    cidr: 192.168.100.0/24
    pool:
      start: 192.168.100.101
      end: 192.168.100.200
      exclude:
      - 192.168.100.150
    router: 192.168.100.1
    dns:
    - 1.1.1.1
    - 8.8.8.8
    domainName: example.com
    domainSearch:
    - example.com
    ntp:
    - pool.ntp.org
  networkName: default/test-net
```

For the `cidr` and `pool` fields, we could reuse the part from the load balancer's IP Pool creation page:

![image](https://github.com/harvester/harvester/assets/1827717/715fcfb6-01d0-463e-996f-6c1127967742)

**Describe alternatives you've considered**

Separate the creation of DHCP pools from VM Networks and put it on an entirely new page at the same level as the load balancer's IP Pool page. In this case, we will need an additional field on the UI for users to specify which VM Network this pool will associate with.

**Additional context**

Due to the add-on essence, the UI must detect whether the add-on is enabled and take respective actions, i.e., show the additional sub-tab only if the harvester-vm-dhcp-controller add-on is enabled. And there are more complicated interactions between Harvester and the add-on that need to be discussed:

- If a VM Network was created with a DHCP pool configured, what must we do if the add-on is turned off later?
- When the add-on is later turned off, the created IPPool objects might be unable to be deleted due to finalizers.
