### ISSUE TITLE
[ENHANCEMENT] Refactor `harvesterhci.io/owned-by` annotation on PVC

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5383]
**Is your enhancement related to a problem? Please describe.**

The `harvesterhci.io/owned-by` annotation is for checking PVC used by which VM. If there is resizing/deleting/attaching PVC request, the system uses it to check whether PVC is used on a running VM.

However, the annotation may be updated by users. In this case, the system can't do correct determination for the PVC.

**Describe the solution you'd like**

Introduce a new index `VMByPVCIndex`, this indexer can search PVC correspond to which VM by PVC name. It doesn't rely on annotation, so users don't have chance to update it.

**Additional context**

https://github.com/harvester/harvester/pull/5031

**Comment by TachunLin** [comment]
Verified **PASS** on `master-49d172b-head` (24/07/28). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Case 1: a volume on a running VM can't be resized $~~$</summary>

1. When we try to resize the volume already attached to vm, the webhook would prevent and prompt message

  ```
  admission webhook "validator.harvesterhci.io" denied the request: resizing is only supported for detached volumes. The volume is being used by VM default/vm1. Please stop the VM first.
  ```

  ![image](https://github.com/user-attachments/assets/1aee818f-9013-4a45-9994-f73e5f894252)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 2: a volume on a stopped VM can be resized $~~$</summary>

1. Can resize volume when vm is off
  
    ![image](https://github.com/user-attachments/assets/221aa1d6-4909-4639-87e3-cb24f8b7f2cc)
    
    ![image](https://github.com/user-attachments/assets/a9aeff49-6c09-4317-8f38-743102227a2c)
    
    
    
    https://github.com/user-attachments/assets/0c777e12-5308-48c2-8af1-cae85e9bebf7




2. Can start the vm in running after volume resized


  https://github.com/user-attachments/assets/809f7dcc-0a8d-4d3e-9c39-eaa60b200b00



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 3: a volume on a VM can't be deleted $~~$</summary>

1. Can't delete the volume already attached to a VM.

    ![image](https://github.com/user-attachments/assets/4204cabf-8635-457a-8e9d-795b752047f1)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 4: a volume without VM can be deleted $~~$</summary>

1. After VM have been removed and select not delete volume, then we can delete the volume without error


    https://github.com/user-attachments/assets/080cee5c-619b-486d-83e2-59a8bb09ec49



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 5: delete a VM with volume can work $~~$</summary>


1. Can delete VM along with the attached volume


    https://github.com/user-attachments/assets/f9d88534-2079-4fea-9b33-15401fceddd3



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 6: A volume can't be attached to another VM $~~$</summary>


1. When a volume already attached to the VM, it can't be attached to another vm, webhook would prompt failure
  ![image](https://github.com/user-attachments/assets/1f71c2bc-0432-4f30-962e-12faedbf764d)



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Case 7: Old VM can work with new controller $~~$</summary>



1. VM has `harvesterhci.io/VMController.UnsetOwnerOfPVCs` finalizer
  ```
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      harvesterhci.io/vmRunStrategy: RerunOnFailure
      harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"vm1-disk-0-rnotg","annotations":{"harvesterhci.io/imageId":"default/image-x6z76"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-x6z76"}}]'
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      network.harvesterhci.io/ips: '[]'
    creationTimestamp: "2024-07-29T09:30:26Z"
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    - harvesterhci.io/VMController.UnsetOwnerOfPVCs
  ```


2. VMI has `wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs`
  ```
  apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  metadata:
    annotations:
      harvesterhci.io/sshNames: '[]'
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      kubevirt.io/vm-generation: "2"
    creationTimestamp: "2024-07-29T09:30:26Z"
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    - foregroundDeleteVirtualMachine
    - wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs
    - wrangler.cattle.io/harvester-lb-vmi-controller
  
  ```

3. Delete vm will also delete the volume without error 


  https://github.com/user-attachments/assets/0ecf547a-bb3f-438d-ad61-9939bd910a56




 </details>

### Test Information
* Test Environment: Four nodes on baremetal machines
* Harvester version: `master-49d172b-head` (24/07/28)

### Verify Steps
<details><summary>Case 1: a volume on a running VM can't be resized</summary>

1. Create a VM and make sure VM is running.
2. Resize the VM volume and webhook will deny the request.

</details>

<details><summary>Case 2: a volume on a stopped VM can be resized</summary>

1. Stop the running VM
2. Resize the VM volume in volumes page
3. Check can resize the VM volume without any error.
4. Check can start the VM again without any error.

</details>

<details><summary>Case 3: a volume on a VM can't be deleted</summary>

1. Follow with Case 2
2. Delete the volume of the VM
3. Check the webhook will deny the request.


</details>


<details><summary>Case 4: a volume without VM can be deleted</summary>

1. Follow with Case 3.
2. Delete the VM but not the volume.
  ![image](https://github.com/user-attachments/assets/1a4b7d33-f86e-497f-a45e-5afd335bb3d4)

3. After VM removed
4. Check can delete the volume without any error.


</details>

<details><summary>Case 5: delete a VM with volume can work</summary>

1. Create a new VM.
2. Delete the VM with volume.
3. Both VM and volume are removed.

</details>

<details><summary>Case 6: A volume can't be attached to another VM </summary>

  1. Create 2 VMs. (vm1 and vm2)
  2. Create a data volume `vol-001`
  3. Use the `Add volume` on vm menu to attach `vol-001` to vm1
  4. Edit the yaml of vm2 
  5. Try to attach the data volume to another VM 
  ![image](https://github.com/user-attachments/assets/b136a2bf-8653-4688-b6c1-1afc1dd313e5)

  6. Check the webhook will deny the request.

</details>

<details><summary>Case 7: Old VM can work with new controller</summary>

1. Create a v1.3.0 harvester.
2. Create a VM. 
3. Check **VM** has `harvesterhci.io/VMController.UnsetOwnerOfPVCs finalizer` and **VMI** has `wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs.`

4. Change the harvester and harvester-webhook image to this branch. (K9s -> search harvester and harvester-wehbook pod

  - harvester pod
    ```
      containers:
      - env:
        - name: HARVESTER_SERVER_HTTPS_PORT
          value: "8443"
        - name: HARVESTER_DEBUG
          value: "false"
        - name: HARVESTER_SERVER_HTTP_PORT 
          value: "0"
        - name: HCI_MODE
          value: "true"
        - name: RANCHER_EMBEDDED
          value: "true"
        - name: NAMESPACE
          valueFrom: 
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: rancher/harvester:master-head
        imagePullPolicy: IfNotPresent
    ```


  - harvester-wehbook pod
    ```
      containers:
      - env:
        - name: HARVESTER_WEBHOOK_SERVER_HTTPS_PORT
          value: "9443"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: HARVESTER_DEBUG
          value: "false"
        - name: HARVESTER_CONTROLLER_USER_NAME
          value: system:serviceaccount:harvester-system:harvester
        image: rancher/harvester-webhook:master-head
        imagePullPolicy: IfNotPresent
        name: harvester-webhook
    
    ```

7. Delete the VM with volume.
8. Check both resources will be removed.


</details>


### Additional context
We may also check whether this change would impact existing e2e automation test
https://github.com/harvester/harvester/pull/5406#issuecomment-2209227249
