### ISSUE TITLE
[BUG] Harvester Node Driver cloudinitdisk order

### ISSUE THREAD

**Issue by chad-jones** [harvester/harvester#5410]
**Describe the bug**
cloudinitdisk order is different when provisioning virtual machines via Rancher (Harvester Node Driver) vs directly in Harvester

**To Reproduce**
Provision a VM in Harvester. The cloudinit disk will be the last disk.

```
devices:
  disks:
    - bootOrder: 1
      disk:
        bus: virtio
      name: disk-0
    - bootOrder: 2
      disk:
        bus: virtio
      name: disk-1
    - disk:
        bus: virtio
      name: cloudinitdisk
```

Provision a VM in Rancher with the Harvester Node Driver. The cloudinit disk will be the first disk.

```
devices:
  disks:
    - disk:
        bus: virtio
      name: cloudinitdisk
    - bootOrder: 1
      disk:
        bus: virtio
      name: disk-0
    - bootOrder: 2
      disk:
        bus: virtio
      name: disk-1
```

**Expected behavior**
Consistent disk order

**Environment**
 - Harvester v1.2.1
 - Rancher v2.8.2
 - Baremetal with HPE ProLiantDL385Gen10Plusv2

**Comment by Yu-Jack** [comment]
Hi @chad-jones, did you encounter any problem about this inconsistent disk order?

**Comment by chad-jones** [comment]
Yes, most of our VMs have multiple disks which are configured/mounted via cloud-init which relies on predictable disk order.
In the example above disk-1 is /dev/vdb with Harvester and /dev/vdc with Rancher.

**Comment by Yu-Jack** [comment]
@chad-jones, could you elaborate more detail about how do you use this order with example? thanks!

**Comment by chad-jones** [comment]
I create a machine with two disks in Harvester with something like the below in my cloud config. 

```
fs_setup:
  - label: rancher
    device: /dev/vdb
    filesystem: xfs

mounts:
  - [ /dev/vdb, /var/lib/rancher ]
  ```
  
  
  In the VM the two disks are /dev/vda & /dev/vdb and the volume is mounted as expected.  The cloudinitdisk is  /dev/vdc.
  ```
  NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
vda    254:0    0  40G  0 disk
├─vda1 254:1    0   2M  0 part
├─vda2 254:2    0  20M  0 part /boot/efi
└─vda3 254:3    0  40G  0 part /usr/local
                               /srv
                               /opt
                               /home
                               /boot/grub2/x86_64-efi
                               /boot/writable
                               /boot/grub2/i386-pc
                               /.snapshots
                               /var
                               /root
                               /
vdb    254:16   0  50G  0 disk /var/lib/rancher
vdc    254:32   0   1M  0 disk
  ```
  
Doing the same from Rancher however, the two disks in the VM are /dev/vdb & /dev/vdc.  The cloudinitdisk is  /dev/vda. Mounting the volume fails obviously.
  ```
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
vda    253:0    0   1M  0 disk
vdb    253:16   0  40G  0 disk
├─vdb1 253:17   0   2M  0 part
├─vdb2 253:18   0  20M  0 part /boot/efi
└─vdb3 253:19   0  40G  0 part /usr/local
                               /srv
                               /opt
                               /home
                               /boot/writable
                               /boot/grub2/x86_64-efi
                               /boot/grub2/i386-pc
                               /.snapshots
                               /var
                               /root
                               /
vdc    253:32   0  50G  0 disk
  ```
