### ISSUE TITLE
[BUG] Incorrect port available for Health Check in Load Balancer

### ISSUE THREAD

**Issue by bharath144** [harvester/harvester#5444]
**Describe the bug**

When creating a LoadBalancer, in the Health Check screen, the list of ports shown are incorrect. The list shows incoming ports where as it should show backend ports.

**To Reproduce**
1. Go to LoadBalancer Screen
2. Create a new LoadBalancer
3. Define a listener, add an incoming port, backend port
4. Define server selector
5. On the Health Check screen try to select the backend port in the drop down list. Notice the backend port isn't available for selection.

**Expected behavior**

List of ports must show backend ports. Note that it is possible to edit YAML to add the correct port manually.

**Support bundle**

<img width="1350" alt="image" src="https://github.com/harvester/harvester/assets/1856100/da4a0cfc-f095-4edd-bf25-5ad341bd1ebe">
<img width="1350" alt="image" src="https://github.com/harvester/harvester/assets/1856100/655b34e6-777f-466a-98cb-96e91e5036e8">
<img width="1350" alt="image" src="https://github.com/harvester/harvester/assets/1856100/3d91c213-8fb8-4942-9202-5dc4a754d45c">

**Environment**
 - Harvester ISO version: 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HPE Proliant Gen9

**Additional context**

**Comment by Yu-Jack** [comment]
Hi, @bharath144 thank for raising this issue. According to [documentation](https://docs.harvesterhci.io/v1.3/networking/loadbalancer#health-checks):

`Health Check Port` means `Specifies the port. The prober will access the address composed of the backend server IP and the port.` Currently it shows and writes load balancer port, but I could modify config by `Edit YAML` to make it correct. This [frontend code](https://github.com/harvester/dashboard/blob/0eec95c8069fd187167d707845b13ef596348788/pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/HealthCheck.vue#L40-L45) provide options from listeners.port, and [backend code](https://github.com/harvester/load-balancer-harvester/blob/f0aaac2c5fb19ca61235637505ee7ba26346adf5/pkg/lb/servicelb/manager.go#L191-L195) fetches `HealthCheck.Port` to probe. So, I think it's a GUI Issue because it should provide option from listeners.backendPort.

For more details of workaround, let's say if we have listener port is `8080`, and backport is `7777`. 

After created by GUI, the YAML will be:

```yaml
  healthCheck:
    failureThreshold: 1
    periodSeconds: 2
    port: 8080
    successThreshold: 2
    timeoutSeconds: 2
  ipam: dhcp
  listeners:
    - backendPort: 7777
      name: myport
      port: 8080
      protocol: TCP
```

But, it should be:

```yaml
  healthCheck:
    failureThreshold: 1
    periodSeconds: 2
    port: 7777
    successThreshold: 2
    timeoutSeconds: 2
  ipam: dhcp
  listeners:
    - backendPort: 7777
      name: myport
      port: 8080
      protocol: TCP
```
