### ISSUE TITLE
[BUG] Harvester chart marked as modified when upgrading to v1.2-head

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5566]
**Describe the bug**

While upgrading Harvester from v1.2.1 to v1.2-head, the apply-manifests job can't continue because the harvester chart is considered "Modified".

**To Reproduce**
1. Create a harvester v1.2.1 cluster.
2. Upgrade to v1.2-head.
3. The `hvst-upgrade-xxxxx-apply-manifests` job keep waiting for Harvester chart to become Ready:
```
Current version: 0.0.0-test-pr-4881-0f11c106, Current state: Modified, Current generation: 4
Sleep for 5 seconds to retry
Current version: 0.0.0-test-pr-4881-0f11c106, Current state: Modified, Current generation: 4
Sleep for 5 seconds to retry
```
4. Check the harvester fleet bundle, it's in Modified:
```
  summary:
    desiredReady: 1
    modified: 1
    nonReadyResources:
    - bundleState: Modified
      modifiedStatus:
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: engines.longhorn.io
        patch: '{"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}'
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: instancemanagers.longhorn.io
        patch: '{"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}'
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: replicas.longhorn.io
        patch: '{"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}'
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: settings.longhorn.io
        patch: '{"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}'
      name: fleet-local/local
```

**Expected behavior**

The upgrade should continue.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1 -> v1.2-head (1a44ad321d3023cefe597c5ba92f9215419dc9ba)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

I can add these diff.comparePatches to the Harvester managed chart to bypass the fleet complaint:
```
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: settings.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: replicas.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: instancemanagers.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: engines.longhorn.io
```
