### ISSUE TITLE
[BUG] CreateImage fails to download image if `checksum` is set

### ISSUE THREAD

**Issue by drewmullen** [harvester/harvester#5578]
**Describe the bug**

If you specify a `spec.checksum` value, harvester fails to initiate downloads for vm images. 

<img width="885" alt="image" src="https://github.com/harvester/harvester/assets/3812162/928adc61-065f-42d0-9e2c-aaedbea73184">

**To Reproduce**

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: #string
  annotations:
    harvesterhci.io/storageClassName: harvester-longhorn
    #  key: string
  generateName: image-
  labels:
    harvesterhci.io/image-type: raw_qcow2
    harvesterhci.io/os-type: ubuntu
    #  key: string
  namespace: drew
spec:
  checksum: "d007256eeaa02936f4b9d096e631eaf2"
  displayName: checksumtest
  sourceType: download
  url: >-
    http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
__clone: true
```

I dont think it matters but I tried both:
- shasum: http://cloud-images.ubuntu.com/releases/focal/release/SHA256SUMS
- md5sum: http://cloud-images.ubuntu.com/releases/focal/release/MD5SUMS

**Environment**
 - Harvester ISO version: v1.2.1 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): intel nucs

**Additional context**
