### ISSUE TITLE
[Doc] Add pre-condition of registering Harvester to Rancher

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5658]
**Is your doc request related to a problem? Please describe or add related issue ID.**

When importing Harvester to Rancher https://docs.harvesterhci.io/v1.2/rancher/virtualization-management#importing-harvester-cluster, a dynamic container image like `rancher/rancher-agent:v2.7.9` is required but it is not packed into Harvester ISO. When internet is not reachable for Harvester cluster, the registering will stuck due to image not available.

```
`state:
        waiting:
          message: Back-off pulling image "rancher/rancher-agent:v2.7.9"null
          reason: ImagePullBackOff`
```

**Describe the solution you'd like**

Add pre-condition to the document.
