### ISSUE TITLE
[ENHANCEMENT] Verify there is a default route during the installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5675]
**Is your enhancement related to a problem? Please describe.**

RKE2 requires a default route to start, some installations are stuck with no obvious message if there is no default route on the system.

**Describe the solution you'd like**

Add a check in the installer after the network configuration panel. PXE installation should be considered as well.

**Describe alternatives you've considered**

**Additional context**

https://github.com/rancher/rke2/issues/1242#issuecomment-872661413

**Comment by mingshuoqiu** [comment]
The [rancher/rke2#1242 (comment)](https://github.com/rancher/rke2/issues/1242#issuecomment-872661413) means we don't need to valid route for the internet connectivity, right?

**Comment by bk201** [comment]
@mingshuoqiu no we don't. RKE2 just needs a default route present.

**Comment by mingshuoqiu** [comment]
PXE installation requires the `option routers` to be configured in DHCP server to start the installation. https://docs.harvesterhci.io/v1.3/install/pxe-boot-install.
Will do the check in normal installation process.

**Comment by mingshuoqiu** [comment]
Here's the console log of my iPXE installation failure

```
time="2024-09-16T08:30:31Z" level=info msg="my tty is /dev/tty1"
time="2024-09-16T08:30:31Z" level=info msg="Start automatic installation..."
time="2024-09-16T08:30:31Z" level=info msg="Local config: {SchemeVersion:0 ServerURL: Token: OS:{AfterInstallChrootCommands:[] SSHAuthorizedKeys:[] WriteFiles:[] Hostname: Modules:[kvm vhost_net] Sysctls:map[] NTPServers:[] DNSNameservers:[] Wifi:[] Password: Environment:map[] Labels:map[] SSHD:{SFTP:false} PersistentStatePaths:[]} Install:{Automatic:true SkipChecks:false Mode: ManagementInterface:{Interfaces:[] Method: IP: SubnetMask: Gateway: DefaultRoute:false BondOptions:map[] MTU:0 VlanID:0} Vip: VipHwAddr: VipMode: ForceEFI:false Device: ConfigURL:http://172.24.1.19/harvester/config-create.yaml Silent:false ISOURL: PowerOff:false NoFormat:false Debug:false TTY: ForceGPT:false Role: WithNetImages:false WipeDisks:false ForceMBR:false DataDisk: Webhooks:[] Addons:map[] Harvester:{StorageClass:{ReplicaCount:0} Longhorn:{DefaultSettings:{GuaranteedEngineManagerCPU:<nil> GuaranteedReplicaManagerCPU:<nil> GuaranteedInstanceManagerCPU:<nil>}} EnableGoCoverDir:false} RawDiskImagePath: PersistentPartitionSize:} RuntimeVersion: RancherVersion: HarvesterChartVersion: MonitoringChartVersion: SystemSettings:map[] LoggingChartVersion:}"
time="2024-09-16T08:30:31Z" level=info msg="Remote config: {SchemeVersion:1 ServerURL: Token:*** OS:{AfterInstallChrootCommands:[] SSHAuthorizedKeys:[ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4dPexLIQWUjATwjGGX0LbKXADFSj9mUWFACYDqVRzDF3Dx+G7OssPekHKKFREN1MQOMfHQgJep1avdrQom0HEEjjzWxuKHi8J8wfcb3H7xZr6ojTv6xPpJfvY9IWDqWjLpvXkSeb9dmUClXZk7mvhAIt7s+wtUhlG8ZRDWZ8k2R17tcy9L73oHzW+7DyLflkJoetjYPrew9ifyaH/WFIqtEX7NHdIHHSQoxlWNxf+QzVB4DmYMOzf/FHiKCwNuqEUhbB4h3yWUUKiB/5/psD2CGDnAlN0whHXGSJqn6DeyG7xBnsxg0T5k9OsX65KNSOAgrr/1grtL0Nz7+ll0Ylp] WriteFiles:[] Hostname:ming Modules:[] Sysctls:map[] NTPServers:[] DNSNameservers:[8.8.8.8 1.1.1.1] Wifi:[] Password:*** Environment:map[] Labels:map[] SSHD:{SFTP:false} PersistentStatePaths:[]} Install:{Automatic:false SkipChecks:true Mode:create ManagementInterface:{Interfaces:[{Name:enp1s0 HwAddr:}] Method:dhcp IP: SubnetMask: Gateway: DefaultRoute:false BondOptions:map[miimon:100 mode:balance-tlb] MTU:0 VlanID:0} Vip:172.24.1.92 VipHwAddr: VipMode:static ForceEFI:false Device:/dev/nvme0n1 ConfigURL: Silent:false ISOURL:http://172.24.1.19/harvester/harvester-v1.3.2-rc2-amd64.iso PowerOff:false NoFormat:false Debug:false TTY: ForceGPT:false Role: WithNetImages:false WipeDisks:false ForceMBR:false DataDisk: Webhooks:[] Addons:map[] Harvester:{StorageClass:{ReplicaCount:0} Longhorn:{DefaultSettings:{GuaranteedEngineManagerCPU:<nil> GuaranteedReplicaManagerCPU:<nil> GuaranteedInstanceManagerCPU:<nil>}} EnableGoCoverDir:false} RawDiskImagePath: PersistentPartitionSize:} RuntimeVersion: RancherVersion: HarvesterChartVersion: MonitoringChartVersion: SystemSettings:map[] LoggingChartVersion:}"
time="2024-09-16T08:30:31Z" level=info msg="Local config (merged): {SchemeVersion:1 ServerURL: Token:*** OS:{AfterInstallChrootCommands:[] SSHAuthorizedKeys:[ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4dPexLIQWUjATwjGGX0LbKXADFSj9mUWFACYDqVRzDF3Dx+G7OssPekHKKFREN1MQOMfHQgJep1avdrQom0HEEjjzWxuKHi8J8wfcb3H7xZr6ojTv6xPpJfvY9IWDqWjLpvXkSeb9dmUClXZk7mvhAIt7s+wtUhlG8ZRDWZ8k2R17tcy9L73oHzW+7DyLflkJoetjYPrew9ifyaH/WFIqtEX7NHdIHHSQoxlWNxf+QzVB4DmYMOzf/FHiKCwNuqEUhbB4h3yWUUKiB/5/psD2CGDnAlN0whHXGSJqn6DeyG7xBnsxg0T5k9OsX65KNSOAgrr/1grtL0Nz7+ll0Ylp] WriteFiles:[] Hostname:ming Modules:[kvm vhost_net] Sysctls:map[] NTPServers:[] DNSNameservers:[8.8.8.8 1.1.1.1] Wifi:[] Password:*** Environment:map[] Labels:map[] SSHD:{SFTP:false} PersistentStatePaths:[]} Install:{Automatic:true SkipChecks:true Mode:create ManagementInterface:{Interfaces:[{Name:enp1s0 HwAddr:}] Method:dhcp IP: SubnetMask: Gateway: DefaultRoute:false BondOptions:map[miimon:100 mode:balance-tlb] MTU:0 VlanID:0} Vip:172.24.1.92 VipHwAddr: VipMode:static ForceEFI:false Device:/dev/nvme0n1 ConfigURL:http://172.24.1.19/harvester/config-create.yaml Silent:false ISOURL:http://172.24.1.19/harvester/harvester-v1.3.2-rc2-amd64.iso PowerOff:false NoFormat:false Debug:false TTY: ForceGPT:false Role: WithNetImages:false WipeDisks:false ForceMBR:false DataDisk: Webhooks:[] Addons:map[] Harvester:{StorageClass:{ReplicaCount:0} Longhorn:{DefaultSettings:{GuaranteedEngineManagerCPU:<nil> GuaranteedReplicaManagerCPU:<nil> GuaranteedInstanceManagerCPU:<nil>}} EnableGoCoverDir:false} RawDiskImagePath: PersistentPartitionSize:} RuntimeVersion: RancherVersion: HarvesterChartVersion: MonitoringChartVersion: SystemSettings:map[] LoggingChartVersion:}"
time="2024-09-16T08:30:31Z" level=warning msg="12 CPU cores detected. Harvester requires at least 16 cores for production use."
time="2024-09-16T08:30:31Z" level=warning msg="Only 16GiB RAM detected. Harvester requires at least 32GiB for testing and 64GiB for production use."
time="2024-09-16T08:30:31Z" level=warning msg="Link speed of enp1s0 is 1Gbps. Harvester requires at least 10Gbps for production use."
time="2024-09-16T08:30:31Z" level=info msg="Installation will proceed (harvester.install.skipchecks = true)"
time="2024-09-16T08:30:31Z" level=error msg="No default route found. Please check the router setting on the DHCP server."
```

and there's no default route entry by checking the output of `ip route show`

**Comment by albinsun** [comment]
## Test Result
Test FAIL in **ipxe-example** env., do failed but no explicit error message relates to route.


### Environment
* `harvester-v1.4.0-dev-20240830`
  * Profile: Single node QEMU/KVM (8C/16G/500G)
  * ui-source: `Auto`


### Prerequisite
1. <details>
   <summary> Drop <coe>option routers</code> and <code>next-server</code> from <i>ipxe-examples/vagrant-pxe/harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3a41187c-b9c2-47e3-ad9e-3b516a221668)
   </details>


### Steps 
1. <details>
   <summary> Execute <code>./setup_harvester.sh</code> :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/bb947071-1cb3-40e5-89aa-a594452e304b)
   </details>

1. <details open>
   <summary> DHCP/PXE server up :heavy_check_mark: 
   </summary>
  
   * Console
     ![image](https://github.com/user-attachments/assets/099f0939-47d1-4ce3-bb1d-e23eea598c1d)
   * /etc/dhcp/dhcpd.conf
      ```
      ddns-update-style none;
      
      # option domain-name "example.org";
      include "/etc/dhcp/ipxe.conf";
      option arch code 93 = unsigned integer 16;
      option user-class code 77 = string;
      
      default-lease-time 600;
      max-lease-time 7200;
      authoritative;
      log-facility local7;
      
      subnet 192.168.0.0 netmask 255.255.255.0 {
          range 192.168.0.50 192.168.0.130;
          option domain-name-servers 1.1.1.1, 192.168.0.254, 8.8.8.8;
      
         if exists user-class and option user-class = "iPXE" {
              filename "[http://192.168.0.254/harvester/${net1/mac}](http://192.168.0.254/harvester/$%7Bnet1/mac%7D)";
          } elsif option arch != 00:00 {
              filename "ipxe/ipxe.efi";
          } else {
              filename "ipxe/undionly.kpxe";
          }
      }
      
      host harvest_vip {
          hardware ethernet 02:00:00:03:3D:61;
          fixed-address 192.168.0.131;
      }
      ...
      ```
   * /var/www/harvester/config-create.yaml
      ```
      # example from https://github.com/harvester/ipxe-examples/blob/main/general/config-create.yaml
      
      scheme_version: 1
      token: token
      os:
        hostname: harvester-node-0
        dns_nameservers:
        - 192.168.0.254
        - 8.8.8.8
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5pxdRzCj0awHSFLUmocoDoENOLeYapqh4v0/x3/VyH+cPNVxdKGX+wDnCXhFA+eX9pLiWDZbdhnEhind8g41prQubUfzD3kb0vEPoo1uDU+UaBqhnVAEtd27abOBE03m6z3x94yZj+GoWrs3uLfv36MJRo4GyEfrJWqeC3P5SkuXllPbnaO/tl9nO/WH7ZSSN8ntESHuBepKfrFCRZzeOvZZu2a4mDCNvnHLpt7qh8zxXm+a2ekgbTbnXQ2Kk9yi7ztJhTWdhhiqQDG9CpQzhGtx7QDM2qOj/XOwgtD9c34wZpzs9hqt6NQoBDRVtnobxnuIUkua6KronAaf81D5PJyFmVqPlfycCcqs6ZQKj/M05L8UZ1ahFRRoZkpBye0xPX2MPPyB/S9drldOKp/i8udvJ96ONSq+rZtcsR/ybIbdULutdR8/UQa/JPxDe8vSXBWrKVq0FwtUBUBw1bvMvZuHSLKcDAlSMQjMhtSepxGy9B1FNG71kjeNj10gmfss= albin.sun
        password: p@ssword
        ntp_servers:
          - 0.suse.pool.ntp.org
          - 1.suse.pool.ntp.org
        sshd:
          sftp: True
      install:
        mode: create
        management_interface:
          interfaces:
          - name: ens6  # The management interface name
          method: dhcp
        device: /dev/vda       # The target disk to install
        iso_url: http://192.168.121.105/harvester/harvester-amd64.iso
      #  tty: ttyS1,115200n8   # For machines without a VGA console
        tty: ttyS0
        vip: 192.168.0.131
        vip_mode: DHCP
        vip_hw_addr: 02:00:00:03:3D:61
      ```
   </details>

1. <details open>
   <summary> Installation should fail with <code>No default route found</code> :x: 
   </summary>
   
   > Installation failed but no message <code>No default route found</code>
   * VM Console
     ![image](https://github.com/user-attachments/assets/7e7cb52d-e4fd-4749-84bc-4b13f332ecdd)
   * /var/log/console.log
      ```
      rancher@harvester-node-0:~> head /var/log/console.log 
      time="2024-09-16T07:50:45Z" level=info msg="state: {installed:false firstHost:true managementURL:}"
      time="2024-09-16T07:50:45Z" level=info msg="default gateway is not existing. Fallback to harvester-mgmt"
      time="2024-09-16T07:50:45Z" level=warning msg="Device harvester-mgmt didn't have IP address"
      time="2024-09-16T07:50:45Z" level=error msg="exit status 1E0916 07:50:45.384380    1977 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.384677    1977 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.385912    1977 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.386033    1977 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.387320    1977 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
      time="2024-09-16T07:50:45Z" level=error msg="exit status 1%!(EXTRA string=)"
      time="2024-09-16T07:50:45Z" level=error msg="exit status 1E0916 07:50:45.384859    1972 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.385029    1972 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.386320    1972 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.386595    1972 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:50:45.388352    1972 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
      time="2024-09-16T07:51:15Z" level=info msg="default gateway is not existing. Fallback to harvester-mgmt"
      time="2024-09-16T07:51:15Z" level=error msg="exit status 1%!(EXTRA string=)"
      time="2024-09-16T07:51:15Z" level=error msg="exit status 1E0916 07:51:15.478156    2018 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:51:15.478450    2018 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:51:15.479763    2018 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:51:15.479913    2018 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0916 07:51:15.481294    2018 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
      time="2024-09-16T07:51:15Z" level=warning msg="Device harvester-mgmt didn't have IP address"
      ...
      ```
   * Check node-0 default route by `ip route show`
     ```
     rancher@harvester-node-0:~> ip route show
     192.168.0.0/24 dev mgmt-br proto kernel scope link src 192.168.0.30`
     ```
   </details>


### Supportbundle
n/a

### Note
1. Same behavior as `v1.3`, see harvester/harvester/issues/5818


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
