### ISSUE TITLE
[FEATURE] Restrict Load balancer IP usage in the guest clusters

### ISSUE THREAD

**Issue by jtamas96** [harvester/harvester#5685]
Currently if there is a DHCP on the network, handing out load balancer IPs cannot be restricted in the guest kubernetes clusters, so users can use up too many IPs on the cluster with the DHCP solution.

It would be good to have a feature to restrict the number of IPs for namespaces in the guest clusters, or even disable DHCP IP requests as a whole.

**Comment by w13915984028** [comment]
@jtamas96 Do you have more details about your Harvester cluster version,  the steps to produce/reproduce, the related yaml output the CRD objects ... ? thanks.

**Comment by starbops** [comment]
Though the feature is not well-integrated into Harvester, there are manual ways to restrict the number of IP addresses being requested. It depends on where you want to enforce such a restriction. The main idea is to add a limitation for the LoadBalancer type of Service or LoadBalancer objects that could be created. This is done by specifying the corresponding values in the ResourceQuota object for the namespace in which users will create LB-type services or the Project containing the Kubernetes guest cluster.

1. Adding the restriction against the LoadBalancer type of Service objects that could be created **on the Kubernetes guest cluster**. By specifying the number of LB type of Service objects allowed to be created, we can therefore limit the number of IP addresses being requested via DHCP. Such a restriction only applies to the namespace the ResourceQuota object is associated with. For example, the following `test-rq` ResourceQuota restricts the number of LB-type Services that can be created to one for the `test-ns` namespace:

   ```yaml
   apiVersion: v1
   kind: ResourceQuota
   metadata:
     name: test-rq
     namespace: test-ns
   spec:
     hard:
       services.loadbalancers: "1" # <-- means the maximum allowed number of LB-type of Services is 1
   ```

3. Adding the restriction against the LoadBalancer objects that could be created **on the Harvester cluster**. This allows users to restrict the number of LoadBalancer objects being created on the Harvester cluster for a specific namespace. When a Kubernetes guest cluster is created under that specific namespace, the number of LB-type of Service objects that could be created across all the namespaces on the guest cluster will be restricted by the ResourceQuota object. This is the only namespace-agnostic way to restrict the number of LB-type of Service objects being created because Harvester creates LoadBalancer objects for each LB-type of Service object created on the guest cluster under the hood. For example, the following `default-csx6j` ResourceQuota restricts the number of LoadBalancer objects that can be created to one for the `test-ns` namespace:

   ```yaml
   apiVersion: v1
   kind: ResourceQuota
   metadata:
     name: default-csx6j
     namespace: test-ns
   spec:
     hard:
       count/loadbalancers.loadbalancer.harvesterhci.io: "1" # <-- means the maximum allowed number of LBs is 1
   ```
