### ISSUE TITLE
[BUG] After upgraded to v1.2.2-rc1, failed to upgrade to v1.3.0, prompt less than minimum upgrade version

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5686]
**Describe the bug**

After successfully upgrade from v1.2.1 to `v1.2.2.-rc1` and trigger a new upgrade to `v1.3.0`
![image](https://github.com/harvester/harvester/assets/29251855/2ad0d712-42a6-4dd5-81c2-3fdce3ed531f)

The upgrade dashboard would prompt message to prevent downloading upgrade image
```
The current version v1.2.2-rc1 is less than the minimum upgradable version v1.2.2.
```
![image](https://github.com/harvester/harvester/assets/29251855/173c0c17-5498-4c13-9dc0-75e9a2f3f6b7)

**To Reproduce**
1. Prepare single node Harvester 
2. Integrate with Rancher v2.8.2 and create RKE2 guest cluster
3. Upgrade to v1.2.2-rc1 
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: v1.2.2-rc1
    namespace: harvester-system
  spec:
    isoChecksum: '9b4ca2adc8c7b65738f46dd432ac6d832894ae557815f8d323a6c9c2e999bb74eff755fdfd4d7831ac4c0a7cd59676471074883cebfa5fd8b5f14db33ad8db85'
    isoURL: https://releases.rancher.com/harvester/v1.2.2-rc1/harvester-v1.2.2-rc1-amd64.iso
    releaseDate: '20240423'
  ```
4. After upgrade complete, trigger another upgrade to v1.3.0-rc1
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: v1.3.0
    namespace: harvester-system
  spec:
    isoChecksum: '045e3ec2394ac621c72487db8d6f3328228a32bee4ac1ce43b740fafcc8194039e7213f8905020b52f31373d99057c483863e72cca55f8607029bf9cf1362a55'
    isoURL: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64.iso
    releaseDate: '20240315'
  ```

5. Check the upgrade process

**Expected behavior**

After upgraded to v1.2.2-rc, can upgrade to v1.3.0 correctly afterward.

**Support bundle**

[supportbundle_8a56b2de-291c-4d11-b592-7195a366320d_2024-04-25T15-21-45Z.zip](https://github.com/harvester/harvester/files/15112297/supportbundle_8a56b2de-291c-4d11-b592-7195a366320d_2024-04-25T15-21-45Z.zip)

**Environment**
 - Harvester ISO version: `v1.2.2-rc1`, `v1.3.0`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node local kvm machine
