### ISSUE TITLE
[BUG]Management URL is unavailable after installation

### ISSUE THREAD

**Issue by zengqingfu1442** [harvester/harvester#5718]
**Describe the bug**

After installation, the management url is unavailable. The VIP cannot be accessed.
![img_v3_02ae_574dffd3-fd87-489e-a736-be074e53f1fg](https://github.com/harvester/harvester/assets/14928378/a835df41-9c22-4e96-90bc-4927c0236807)

**To Reproduce**
1. Boot from a usb drive which is wrritten into the harvester 1.3.0 iso image.
2. Select the drive /dev/sda as the installation disk as well as the data disk.
3. Follow the prompts and configure the parameters. The harvester config can be found in the following support bundle.

**Expected behavior**

harvester cluster is up and the VIP can be accessed.

**Support bundle**

```yaml
920lab20:/oem # cat harvester.config
schemeversion: 1
serverurl: ""
token: xxx
os:
    afterinstallchrootcommands: []
    sshauthorizedkeys: []
    writefiles: []
    hostname: 920lab20
    modules:
        - kvm
        - vhost_net
    sysctls: {}
    ntpservers:
        - ntp.aliyun.com
    dnsnameservers:
        - 172.16.12.10
    wifi: []
    password: $6$PtFYN3jjt4avZ.V0$CxxQG3sI0VmeylidB9jxxxxxxX0V24lpIgmaKZEMgYXSetnzgvwGMZxzNC.
    environment: {}
    labels: {}
    sshd:
        sftp: false
    persistentstatepaths: []
install:
    automatic: false
    skipchecks: true
    mode: create
    managementinterface:
        interfaces:
            - name: eno1
              hwaddr: e4:54:e8:c9:e3:d2
        method: static
        ip: 172.16.12.110
        subnetmask: 255.255.254.0
        gateway: 172.16.12.1
        defaultroute: true
        bondoptions:
            miimon: "100"
            mode: active-backup
        mtu: 0
        vlanid: 0
    vip: 172.16.12.116
    viphwaddr: ""
    vipmode: static
    forceefi: false
    device: /dev/sda
    configurl: ""
    silent: false
    isourl: ""
    poweroff: false
    noformat: false
    debug: false
    tty: tty1
    forcegpt: true
    role: default
    withnetimages: false
    wipedisks: false
    forcembr: false
    datadisk: ""
    webhooks: []
    addons: {}
    harvester:
        storageclass:
            replicacount: 0
        longhorn:
            defaultsettings:
                guaranteedenginemanagercpu: null
                guaranteedreplicamanagercpu: null
        enablegocoverdir: false
    rawdiskimagepath: ""
    persistentpartitionsize: 279Gi
runtimeversion: v1.27.10+rke2r1
rancherversion: v2.8.2
harvesterchartversion: 1.3.0
monitoringchartversion: 103.0.3+up45.31.1
systemsettings:
    ntp-servers: '{"ntpServers":["ntp.aliyun.com"]}'
loggingchartversion: 103.0.0+up3.17.10
```

**Environment**
 - Harvester ISO version:  1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  Baremetal with Dell Inc OptiPlex 5070

**Additional context**
CPU: 8 cores,
Mem: 32g

The content of `/var/log/console.log` is:
```
920lab20:/oem # cat /var/log/console.log
time="2024-04-30T10:06:33Z" level=info msg="state: {installed:false firstHost:true managementURL:}"
time="2024-04-30T10:06:34Z" level=error msg="exit status 1W0430 10:06:34.536114    2008 loader.go:222] Config not found: /etc/rancher/rke2/rke2.yaml\nE0430 10:06:34.542359    2008 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.542484    2008 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.543932    2008 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.544115    2008 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.545317    2008 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
time="2024-04-30T10:06:34Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:06:34Z" level=error msg="exit status 1W0430 10:06:34.536112    2002 loader.go:222] Config not found: /etc/rancher/rke2/rke2.yaml\nE0430 10:06:34.542342    2002 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.542555    2002 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.544057    2002 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.544632    2002 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:06:34.545864    2002 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
time="2024-04-30T10:07:05Z" level=error msg="exit status 1W0430 10:07:05.117331    2399 loader.go:222] Config not found: /etc/rancher/rke2/rke2.yaml\nE0430 10:07:05.118091    2399 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.118264    2399 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.119553    2399 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.119723    2399 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.120978    2399 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
time="2024-04-30T10:07:05Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:07:05Z" level=error msg="exit status 1W0430 10:07:05.122400    2397 loader.go:222] Config not found: /etc/rancher/rke2/rke2.yaml\nE0430 10:07:05.122977    2397 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.123242    2397 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.124339    2397 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.124504    2397 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0430 10:07:05.125692    2397 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n"
time="2024-04-30T10:07:35Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:08:06Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:08:35Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:09:05Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:09:35Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:10:05Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:12:56Z" level=info msg="state: {installed:false firstHost:true managementURL:}"
time="2024-04-30T10:12:57Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:13:27Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:13:58Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2024-04-30T10:14:27Z" level=error msg="exit status 1%!(EXTRA string=)"
```
