### ISSUE TITLE
[ENHANCEMENT] Reported VM "IP Address" is a VIP instead of VM IP

### ISSUE THREAD

**Issue by DovydasNavickas** [harvester/harvester#5794]
**Is your enhancement related to a problem? Please describe.**

When I create multiple VMs, in this case 3 Rancher VMs, at first I see their true IPs they got from DHCP. But after running k3s inside and configuring a VIP via ARP for the cluster with kube-vip, I start seeing that VIP reported instead of the IP of the VM itself:
<img width="1676" alt="image" src="https://github.com/harvester/harvester/assets/7989797/bbfc0379-d65f-4d3c-ac58-038c58bc5f70">

All of 10.80.1.X are the IPs coming from DHCP.
10.80.4.1 is the VIP.

**Describe the solution you'd like**

Reported only DHCP IPs or together with VIP as multiple IPs.

**Describe alternatives you've considered**

I can restart the VM and the "true IP" will be reported at first:
![image](https://github.com/harvester/harvester/assets/7989797/d78a05e1-47e6-41ba-b108-253c85991a2c)

I can also check the "true IP" by looking at the MAC address of the VM and finding out the IP from DHCP lease, but that is not convenient at all, especially when using DHCP server provided by Harvester.

**Additional context**

**Comment by innobead** [comment]
cc @mingshuoqiu

**Comment by mingshuoqiu** [comment]
@DovydasNavickas could you please post the result of the command `ip addr show` on each VM?  We need to make sure that the IP assigned on VM is correct and if it's the IP display problem caused by other modules. Thanks

**Comment by mingshuoqiu** [comment]
Could u also share the steps to reproduce in detail? We simply  manually install the k3s + kube-vip but can’t observe the same symptom

**Comment by DovydasNavickas** [comment]
Here are `ip addr show` for every node:

<details>

<summary>rancher-01</summary>

```sh
$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether f2:b9:40:03:19:74 brd ff:ff:ff:ff:ff:ff
    inet 10.80.1.29/16 metric 100 brd 10.80.255.255 scope global dynamic enp1s0
       valid_lft 196sec preferred_lft 196sec
    inet 10.80.4.1/32 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::f0b9:40ff:fe03:1974/64 scope link
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 6e:19:74:3f:29:ab brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::6c19:74ff:fe3f:29ab/64 scope link
       valid_lft forever preferred_lft forever
4: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether fe:aa:f5:88:ba:5d brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.1/24 brd 10.42.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::fcaa:f5ff:fe88:ba5d/64 scope link
       valid_lft forever preferred_lft forever
5: veth014e5838@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether e6:76:f3:e3:45:dc brd ff:ff:ff:ff:ff:ff link-netns cni-da3e166f-817a-c49b-148b-b9144d9b460f
    inet6 fe80::e476:f3ff:fee3:45dc/64 scope link
       valid_lft forever preferred_lft forever
6: veth1771e088@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 3a:9a:8c:0d:dc:0b brd ff:ff:ff:ff:ff:ff link-netns cni-8c0fc802-252c-fc1b-5196-f93c81fab65f
    inet6 fe80::389a:8cff:fe0d:dc0b/64 scope link
       valid_lft forever preferred_lft forever
7: veth98a14f73@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 1e:8c:de:f4:3e:8e brd ff:ff:ff:ff:ff:ff link-netns cni-e883536b-9e5d-e006-e507-0d5b6fcf85bf
    inet6 fe80::1c8c:deff:fef4:3e8e/64 scope link
       valid_lft forever preferred_lft forever
8: veth7e1f0d30@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 16:8c:4a:ca:6e:e3 brd ff:ff:ff:ff:ff:ff link-netns cni-3221833f-7360-c0ff-f9f5-9919afd699e7
    inet6 fe80::148c:4aff:feca:6ee3/64 scope link
       valid_lft forever preferred_lft forever
9: vethe5123ffe@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 2a:2d:3b:fc:59:99 brd ff:ff:ff:ff:ff:ff link-netns cni-ee2863ad-a690-3ff7-e0ca-0f3c413bd168
    inet6 fe80::282d:3bff:fefc:5999/64 scope link
       valid_lft forever preferred_lft forever
10: vethff91f453@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 66:78:24:dc:05:0b brd ff:ff:ff:ff:ff:ff link-netns cni-20172dfc-ed4c-cf09-6828-30c91dcfbb2f
    inet6 fe80::6478:24ff:fedc:50b/64 scope link
       valid_lft forever preferred_lft forever
11: vetha95e9b3a@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether a2:57:a3:84:77:b8 brd ff:ff:ff:ff:ff:ff link-netns cni-ff04fa9f-1d46-9b6f-0562-20bfcb809c02
    inet6 fe80::a057:a3ff:fe84:77b8/64 scope link
       valid_lft forever preferred_lft forever
12: veth9cfecdd5@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether b6:57:16:48:c7:4f brd ff:ff:ff:ff:ff:ff link-netns cni-33249095-80bf-9064-c2d6-9a25ddf511ed
    inet6 fe80::b457:16ff:fe48:c74f/64 scope link
       valid_lft forever preferred_lft forever
14: vethfe05219d@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether f2:7d:a8:63:e8:19 brd ff:ff:ff:ff:ff:ff link-netns cni-5467db14-808a-df5f-9432-5d33b3ea8aec
    inet6 fe80::f07d:a8ff:fe63:e819/64 scope link
       valid_lft forever preferred_lft forever
15: veth1459e7c9@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 2a:ab:51:09:c6:a4 brd ff:ff:ff:ff:ff:ff link-netns cni-62b417ff-6613-0657-b6dd-21f2a0b83454
    inet6 fe80::28ab:51ff:fe09:c6a4/64 scope link
       valid_lft forever preferred_lft forever
16: vethefb4324f@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether de:ef:ca:42:37:4e brd ff:ff:ff:ff:ff:ff link-netns cni-dc0ad511-7102-4bc3-dd80-780af66aa434
    inet6 fe80::dcef:caff:fe42:374e/64 scope link
       valid_lft forever preferred_lft forever
17: veth9bd25e0e@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 82:1e:a6:f5:c7:35 brd ff:ff:ff:ff:ff:ff link-netns cni-90913391-fb14-f520-a3d5-bc27172065cc
    inet6 fe80::801e:a6ff:fef5:c735/64 scope link
       valid_lft forever preferred_lft forever
18: vethcdbcb970@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 42:ed:5e:1d:4d:10 brd ff:ff:ff:ff:ff:ff link-netns cni-397feb1a-1c7a-a680-fdef-d5fde1e69b5e
    inet6 fe80::40ed:5eff:fe1d:4d10/64 scope link
       valid_lft forever preferred_lft forever
19: veth2d501312@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 3a:87:4d:95:47:53 brd ff:ff:ff:ff:ff:ff link-netns cni-8cd2fd98-724b-640c-dcbf-3da50a946f21
    inet6 fe80::3887:4dff:fe95:4753/64 scope link
       valid_lft forever preferred_lft forever
21: veth0c9f6426@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 5e:c6:c2:38:d9:ee brd ff:ff:ff:ff:ff:ff link-netns cni-3b3dce63-1183-d67f-f00c-48566d915883
    inet6 fe80::5cc6:c2ff:fe38:d9ee/64 scope link
       valid_lft forever preferred_lft forever
23: veth2829373c@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether aa:83:2a:c2:c5:4e brd ff:ff:ff:ff:ff:ff link-netns cni-c4162ce6-e82b-5a3e-e1ef-52252056c2fb
    inet6 fe80::a883:2aff:fec2:c54e/64 scope link
       valid_lft forever preferred_lft forever
24: vethaff8ec92@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether c6:82:3b:ff:82:68 brd ff:ff:ff:ff:ff:ff link-netns cni-59c0352e-2512-5f7c-8088-ee434fc8ad58
    inet6 fe80::c482:3bff:feff:8268/64 scope link
       valid_lft forever preferred_lft forever
25: veth8778f9ac@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ae:0c:cf:d3:1b:5e brd ff:ff:ff:ff:ff:ff link-netns cni-8653b06b-55ca-a42d-5979-438b48f1d9aa
    inet6 fe80::ac0c:cfff:fed3:1b5e/64 scope link
       valid_lft forever preferred_lft forever
35: veth3d6dda8f@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 3a:7e:ea:08:e4:bf brd ff:ff:ff:ff:ff:ff link-netns cni-a4d3556c-ca35-84e7-027e-ef8f0c0ef1a0
    inet6 fe80::387e:eaff:fe08:e4bf/64 scope link
       valid_lft forever preferred_lft forever
44: veth791abbc5@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 5a:57:9d:10:79:91 brd ff:ff:ff:ff:ff:ff link-netns cni-28399490-81c1-1b00-e76b-deba09d87de7
    inet6 fe80::5857:9dff:fe10:7991/64 scope link
       valid_lft forever preferred_lft forever
49: veth9aa55bb6@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ee:d8:fc:d7:77:7a brd ff:ff:ff:ff:ff:ff link-netns cni-9f7bf168-2e6c-e57b-a51d-91ebf4f90d89
    inet6 fe80::ecd8:fcff:fed7:777a/64 scope link
       valid_lft forever preferred_lft forever
50: veth189a0841@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ae:6e:59:d3:f2:00 brd ff:ff:ff:ff:ff:ff link-netns cni-6a339ecb-4e28-f173-ab00-03cc1489d30b
    inet6 fe80::ac6e:59ff:fed3:f200/64 scope link
       valid_lft forever preferred_lft forever
53: veth505bea3b@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 86:e1:22:17:da:15 brd ff:ff:ff:ff:ff:ff link-netns cni-eee685e3-11ab-9155-3577-499048b1af6c
    inet6 fe80::84e1:22ff:fe17:da15/64 scope link
       valid_lft forever preferred_lft forever
```

</details>

<details>

<summary>rancher-02</summary>

```sh
$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 42:69:ab:86:95:b5 brd ff:ff:ff:ff:ff:ff
    inet 10.80.1.138/16 metric 100 brd 10.80.255.255 scope global dynamic enp1s0
       valid_lft 281sec preferred_lft 281sec
    inet6 fe80::4069:abff:fe86:95b5/64 scope link
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether f2:34:2f:56:a8:b4 brd ff:ff:ff:ff:ff:ff
    inet 10.42.1.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::f034:2fff:fe56:a8b4/64 scope link
       valid_lft forever preferred_lft forever
```

</details>

<details>

<summary>rancher-03</summary>

```sh
$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c6:0b:37:8a:a5:5f brd ff:ff:ff:ff:ff:ff
    inet 10.80.1.116/16 metric 100 brd 10.80.255.255 scope global dynamic enp1s0
       valid_lft 188sec preferred_lft 188sec
    inet6 fe80::c40b:37ff:fe8a:a55f/64 scope link
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether ea:70:01:18:fd:f7 brd ff:ff:ff:ff:ff:ff
    inet 10.42.2.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::e870:1ff:fe18:fdf7/64 scope link
       valid_lft forever preferred_lft forever
```

</details>

The problem is that it only shows up VIP sometimes. But when it does, the VIP seems to persist in the UI until the VM is restarted. I am not sure if there is something else specific that I've done, because those were empty Debian machines running `debian-12-genericcloud-amd64.qcow2` VM image and I've used this command to install k3s:
```sh
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.9+k3s1 sh -s - server \
    --tls-san=rancher-vip.example.com \
    --tls-san=rancher-vip.another-example.com \
    --disable=traefik,servicelb \
    --cluster-init
```

After this I've setup `kube-vip` with:

<details>

<summary>DaemonSet</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip
  template:
    metadata:
      labels:
        name: kube-vip
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.7.2
          imagePullPolicy: IfNotPresent
          args: ["manager"]
          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: svc_enable
              value: "false"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            - name: address
              value: "${KUBE_VIP_IP}"
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
      hostAliases:
        - hostnames:
            - kubernetes
          ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
```

RBAC
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
```

</details>

When I got the VIP in Harvester UI other nodes were not even connected to the cluster yet, so it was a single-node k3s cluster.
