### ISSUE TITLE
[FEATURE] Live migration network

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5848]
**Is your enhancement related to a problem? Please describe.**
Currently, VM live migration uses the management network. It might bring some issues when many VM want to migrate simultaneously. We need to sync the memory dirty (through the mgmt network), and then the migration could be done.
The migration might take longer if the mgmt network has only 1GB capability.

**Describe the solution you'd like**
kubevirt already provides a way to config another interface for live migration.
Ref: https://kubevirt.io/user-guide/operations/live_migration/#using-a-different-network-for-migrations
We could check this and then try to introduce it in future releases.

**Describe alternatives you've considered**
None

**Additional context**
TBD

**Comment by richevanscybermyte** [comment]
This is needed but I wrote up a workaround in case there is anyone that needs faster then 1G for live migrations and are willing to get into the cli (kubectl)

https://cybermyte.io/blog/rancher-harvester-live-migration-network/

It was something I was also struggling with in my production so I set out to solve it myself. I unfortunately have no GUI skillz (as of today) so I cannot help on that side but at least this solution works in the mean time. Let me know if there are any questions.

**Comment by FrankYang0529** [comment]
Manual steps to setup live migration network:
1. Use ipxe to setup 3-node cluster. https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester
2. Add new network "Virtual network 'harvester'" on each node.
    <img width="760" alt="Image" src="https://github.com/user-attachments/assets/dd8de2f6-b209-47a7-b8cf-d3a18e6796c9" />
3. Run `ip a` on each node and there is `ens7` on each node.
4. Run `ip link set ens7 up` on each node.
5. Create `thisistest` Cluster Network.
6. Create Network with "Select all nodes" and and NIC "ens7".
7. Create net-attach-def.
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    network.harvesterhci.io/route: '{"mode":"auto","cidr":"192.168.3.0/24","gateway":"192.168.3.1","connectivity":"true"}'
  labels:
    network.harvesterhci.io/clusternetwork: thisistest
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "1"
  name: vlan1
  namespace: harvester-system
spec:
  config: '{"cniVersion":"0.3.1","name":"vlan1","type":"bridge","bridge":"thisistest-br","promiscMode":true,"vlan":1,"ipam":{"type":"whereabouts","range": "10.1.1.0/24"}}'
```
8. Update `harvester-system/kubevirt` with following:
```
    migrations:
      network: vlan1
```
9. Create VM.
10. Migrate VM to another host without error. Monitor network interface with `nload` on the host. Check there is data.

Thanks @tjjh89017 for help.
