### ISSUE TITLE
[BUG] Backup and snapshot can not have same name

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5855]
**Describe the bug**
Backup and snapshot can not have same name, even from different VM.

**To Reproduce**
1. <details>
   <summary> Create a VM <code>johndoe</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f4c214c8-c676-400b-ba0c-85d5fd2ec93a)
   </details>

2. <details>
   <summary> Backup VM <code>johndoe</code> with name <code>john</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/acb4a100-73fb-4894-af81-934d42ecb18d)
   </details>

3. <details>
   <summary> :red_circle: Snapshot <code>johndoe</code> with same name <code>john</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/b5ea69d3-4eea-4847-ab1f-8f4dfc602361)
   </details>

   > `virtualmachinebackups.harvesterhci.io "john" already exists`

4. <details>
   <summary> :red_circle: Snapshot another VM with same name <code>john</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/eff9e8ea-481b-4522-8b89-179c8f399897)
   </details>

   > `virtualmachinebackups.harvesterhci.io "john" already exists`

**Expected behavior**
If we regard **backup** and **snapshot** different features, and they should not affect each other. 

**Support bundle**
[supportbundle_BackupAndSnapshot.zip](https://github.com/harvester/harvester/files/15410516/supportbundle_BackupAndSnapshot.zip)

**Environment**
* Harvester
  * Version: `v1.2.2`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`

**Additional context**
1. <details>
   <summary> :red_circle: Reversing test order, namely snapshot then backup, also gives similiar problem.
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/98cddc90-79b2-414b-a7e3-b350341b7647)
   </details>

   > `failed to create VM backup, error: virtualmachinebackups.harvesterhci.io "john" already exists`

**Comment by Yu-Jack** [comment]
Add some contexts, when creating backup and snapshot, it created two `virtualmachinebackups.harvesterhci.io` with different type. So, it's not able to create same name backup and snapshot.

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineBackup
metadata:
  name: test-backup
  namespace: default
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: test2
  type: backup

apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineBackup
metadata:
  name: test-snapshot
  namespace: default
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: test1
  type: snapshot
```
