### ISSUE TITLE
[BUG] GPU stuck in undefined state while attempting to pass-through

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#5957]
**Describe the bug**
I have 3 nodes cluster.
Only one node (name: t7920) has GPU: nVidia P5000
Harvester 1.3.0 installed.
Add-on enabled:
- PCI Devices. 
- only one PCI device enabled: "t7920-0000d5000	VGA compatible controller: NVIDIA Corporation GP104GL [Quadro P5000]	t7920	0000:d5:00.0	10de	1bb0"

nvidia-driver-toolkit add-on is NOT enabled, because my GPU doesn't support vGPU.

I created VM (Ubuntu 22), added the PCI device, mentioned above and everything was working great.

Then I experienced power loss, the node was rebooted.

Now, when I try to start that VM, I'm getting this error:

> 0/3 nodes are available: 1 Insufficient nvidia.com/GP104GL_QUADRO_P5000, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/etcd: true}. preemption: 0/3 nodes are available: 1 No preemption victims found for incoming pod, 2 Preemption is not helpful for scheduling..

Not sure, what should I do. So, I tried to disable the PCI device first and re-enable it later. But I can't disable it:

> Error disabling passthrough on t7920-0000d5000
admission webhook "pcidevices.harvesterhci.io" denied the request: pcideviceclaim t7920-0000d5000 is already in use with vm ub22gpu in namespace default

**Expected behavior**
I expect that VM with attached PCI device should be capable of handling node reboot.

**Support bundle**
https://s3.fursov.family/shares/supportbundle_06b15f17-7231-42ca-9fbe-58f9e910f3b6_2024-06-04T16-10-18Z.zip

**Environment**
3 nodes cluster. 2 nodes are VMs
1 node is baremetal DELL T7920, Xeon 5218, 64GB RAM, nVidia P5000, 10GE NIC
Harvester 1.3.0

**Comment by WebberHuang1118** [comment]
Hi @SlavikCA 
It seems the device plugin for the pcidevice does not work correctly. Can you stop the VM first, disable the device, wait until the CR pcideviceclaim is deleted, and enable the pcidevice again?

**Comment by SlavikCA** [comment]
@WebberHuang1118 
VM is stopped since power loss reboot. Can't start it, because of the error.

Can't disable the PCI device because I'm getting: 
> Error disabling passthrough on t7920-0000d5000
admission webhook "pcidevices.harvesterhci.io" denied the request: pcideviceclaim t7920-0000d5000 is already in use with vm ub22gpu in namespace default

**Comment by WebberHuang1118** [comment]
Can you configure the VM to remove the pcideivce first?

**Comment by SlavikCA** [comment]
Doing it this way, I was able to:
- delete PCI device from VM
- disable nVidia device on the ADVANCED -> PCI Devices page

I waited few minutes. Enabled that device again.
Added to VM.
Started it, and now see another error:

> k describe virtualmachineinstance.kubevirt.io/ub22gpu
Status:
  Conditions:
    Last Probe Time:       2024-06-05T04:16:57Z
    Last Transition Time:  2024-06-05T04:16:57Z
    Message:               virt-launcher pod has not yet been scheduled
    Reason:                PodNotExists
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  2024-06-05T04:16:57Z
    Message:               failed to render launch manifest: HostDevice nvidia.com/GP104GL_QUADRO_P5000 is not permitted in permittedHostDevices configuration
    Reason:                FailedCreate
    Status:                False
    Type:                  Synchronized

**Comment by SlavikCA** [comment]
I can see both nVidia PCI devices in the list:
```
kubectl get pcideviceclaim 
NAME              ADDRESS        NODE NAME   USER NAME   KERNEL DRIVER ΤΟ UNBIND   PASSTHROUGH ENABLED
t7920-0000d5000   0000:d5:00.0   t7920       admin       vfio-pci                  true
t7920-0000d5001   0000:d5:00.1   t7920       admin       vfio-pci                  true
```

kubevirt config appears to be incorrect - it's missing GP104GL_QUADRO_P5000:
```
kubectl get kubevirt -n harvester-system -o yaml
...
      permittedHostDevices:
        pciHostDevices:
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
```

**Comment by SlavikCA** [comment]
I haven't done anything. Went to sleep.

And in the morning, when I looked at the cluster, I see that VM with GPU is running for about 3 hours now!
The VM started at [Wed Jun  5 12:46:21 2024]

Details:
```
kubectl get kubevirt -n harvester-system -o yaml
...
      permittedHostDevices:
        pciHostDevices:
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:1bb0
          resourceName: nvidia.com/GP104GL_QUADRO_P5000
```

so, somehow my GPU device `GP104GL_QUADRO_P5000` was added to the `permittedHostDevices`, which enabled the VM to start. Mystery...

Is there any log I can inspect for hints?

**Comment by ibrokethecloud** [comment]
are you able to please tell me the timing for the outage? the controller would have likely eventually reconcilled. 

the messages would be in the pcidevices controller pods in the harvester-system namespace

**Comment by SlavikCA** [comment]
by running `dmesg` I see that system booted:

[Thu May 30 13:52:43 2024] Linux version 5.14.21-150400.24.108-default 

At that time I had issue with `not a device node`:
https://docs.harvesterhci.io/v1.3/troubleshooting/vm#vm-stuck-in-starting-state-with-error-messsage-not-a-device-node

But I didn't want to go through the `umount` procedure. So, I left it alone. 
To my surprise, it recovered by itself after a day or so.

But the VM still wouldn't boot. That's when I saw that issue with PCI device, which you can see in my 1st message.
When I saw reply from Webber, I 
- deleted PCI device from VM
- disabled nVidia device on the ADVANCED -> PCI Devices page
- waited few minutes
- enabled nVidia device on the ADVANCED -> PCI Devices page
- added PCI device to VM
- started it
Got the error:
> 2024-06-05T04:16:57Z  failed to render launch manifest: HostDevice nvidia.com/GP104GL_QUADRO_P5000 is not permitted in permittedHostDevices configuration

I left it alone, and after few hours:
[Jun 5 12:46:21 2024] VM started

**Comment by SlavikCA** [comment]
Thank you for pointing to `harvester-pcidevices-controller` logs.

Here are few messages I see ~5 minutes before VM got "healed":

> t7920:/home/rancher # k logs -n harvester-system harvester-pcidevices-controller-smcdm
time="2024-06-05T12:41:06Z" level=info msg="Sleeping for 15 seconds then applying webhook config"
time="2024-06-05T12:41:06Z" level=info msg="Updating TLS secret for harvester-system/pcidevices-webhook-tls (count: 1): map[listener.cattle.io/cn-pcidevices-webhook.harvester-system.svc:pcidevices-webhook.harvester-system.svc listener.cattle.io/fingerprint:SHA1=CC9653B04A7D581C4805542D1CA4159CA2C07265]"
time="2024-06-05T12:41:15Z" level=info msg="Adding t7920-0000d5001 to KubeVirt list of permitted devices"
W0605 12:41:15.869387       1 warnings.go:70] kubevirt.io/v1alpha3 is now deprecated and will be removed in a future release.
time="2024-06-05T12:41:16Z" level=info msg="Adding t7920-0000d5000 to KubeVirt list of permitted devices"
W0605 12:41:16.071136       1 warnings.go:70] kubevirt.io/v1alpha3 is now deprecated and will be removed in a future release.
W0605 12:41:16.119233       1 warnings.go:70] kubevirt.io/v1alpha3 is now deprecated and will be removed in a future release.
I0605 16:20:01.542123       1 request.go:665] Waited for 1.092642829s due to client-side throttling, not priority and fairness, request: PUT:https://10.53.0.1:443/apis/devices.harvesterhci.io/v1beta1/pcidevices/t7920-0000001f6/status
time="2024-06-05T22:41:06Z" level=info msg="Sleeping for 15 seconds then applying webhook config"
time="2024-06-05T22:41:07Z" level=info msg="Updating TLS secret for harvester-system/pcidevices-webhook-tls (count: 1): map[listener.cattle.io/cn-pcidevices-webhook.harvester-system.svc:pcidevices-webhook.harvester-system.svc listener.cattle.io/fingerprint:SHA1=CC9653B04A7D581C4805542D1CA4159CA2C07265]"
time="2024-06-05T22:41:15Z" level=info msg="Adding t7920-0000d5001 to KubeVirt list of permitted devices"

I wonder, why it took so long to add it to permitted devices?
Could I have done it manually earlier?

By the way here is how that list looks now:
```
kubectl get kubevirt -n harvester-system -o yaml
...
       permittedHostDevices:
        pciHostDevices:
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:10f0
          resourceName: nvidia.com/GP104_HIGH_DEFINITION_AUDIO_CONTROLLER
        - externalResourceProvider: true
          pciVendorSelector: 10de:1bb0
          resourceName: nvidia.com/GP104GL_QUADRO_P5000
        - externalResourceProvider: true
          pciVendorSelector: 10de:1bb0
          resourceName: nvidia.com/GP104GL_QUADRO_P5000
```

Why so many duplicates in that list?
