### ISSUE TITLE
[BUG] Upgrade v1.2.2->v1.3.1 stuck at Draining node even the node has been updated, cause upgrade process hang

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#6022]
**Describe the bug**

![image](https://github.com/harvester/harvester/assets/38560218/914d9811-b0bc-4cda-85d3-e20e4bdfeba1)
![image](https://github.com/harvester/harvester/assets/38560218/471dd479-8434-4e11-95b8-99359bf5dbf4)
![image](https://github.com/harvester/harvester/assets/38560218/de6afbff-c4ee-42f0-ac8a-eee3b5662a88)
![image](https://github.com/harvester/harvester/assets/38560218/942e7ed9-9656-431c-a952-9b639eceda26)

**To Reproduce**
1. Upgrade harvester from v1.2.2 to v1.3.1
2. (Perhaps): Modify Advanced - Settings - containerd - regeisty during updating due to `docker.io` has been blocked in China recently.

**Expected behavior**

Cluster should be upgraded successfully

**Support bundle**

[hvst-upgrade-wjzc2-upgradelog-archive-2024-06-14T07-55-46Z.zip](https://github.com/user-attachments/files/15834827/hvst-upgrade-wjzc2-upgradelog-archive-2024-06-14T07-55-46Z.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.001.zip](https://github.com/user-attachments/files/15834915/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.001.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.002.zip](https://github.com/user-attachments/files/15834931/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.002.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.003.zip](https://github.com/user-attachments/files/15834937/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-14T07-56-12Z.003.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure: Baremetal with Dell PowerEdge R630

**Additional context**
I tried to delete Machine custom-fb4dda4acb64, and the second node update successfully, but the third node stuck again.

**Comment by irishgordo** [comment]
@W0n9 did you update your [containerd-registry setting](https://docs.harvesterhci.io/v1.3/advanced/index#containerd-registry) after the upgrade had already started?

Did you have multiple mirrors and multiple configs listed, something like?
```json
{
  "Mirrors": {
    "docker.io": {
      "Endpoints": [
        "https://airgap-docker-registry.192.168.120.175.sslip.io:5000/"
      ],
      "Rewrites": null
    },
    "airgap-docker-registry.192.168.120.175.sslip.io:5000": {
      "Endpoints": [
        "192.168.120.175:5000"
      ],
      "Rewrites": {}
    }
  },
  "Configs": {
    "airgap-docker-registry.192.168.120.175.sslip.io:5000": {
      "Auth": {
        "Username": "",
        "Password": "",
        "Auth": "",
        "IdentityToken": ""
      },
      "TLS": {
        "CAFile": "",
        "CertFile": "",
        "KeyFile": "",
        "InsecureSkipVerify": true
      }
    },
    "192.168.120.175:5000": {
      "Auth": {
        "Username": "",
        "Password": "",
        "Auth": "",
        "IdentityToken": ""
      },
      "TLS": {
        "InsecureSkipVerify": true
      }
    }
  }
}
```

**Comment by W0n9** [comment]
Hi @irishgordo 
Exactly, I have updated my containerd-registry setting after the upgrade had already started.
But my mirrors config like this:
```json
{
  "Mirrors": {
    "docker.io": {
      "Endpoints": [
        "https://mirrors1",
        "https://mirrors2"
      ],
      "Rewrites": null
    }
  },
  "Configs": null,
  "Auths": null
}
```
And I have changed the config via SSH follow [RKE2 docs](https://docs.rke2.io/install/containerd_registry_configuration), which is multiple mirrors config, just like:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://mirrors1"
      -  "https://mirrors2"
  registry.example.com:
    endpoint:
      - "https://registry.example.com:5000"
```

**Comment by starbops** [comment]
Hi @W0n9 

A couple of things need to be clarified, and I hope you can provide more details:

- You mentioned you removed the machine `custom-fb4dda4acb64`. Do you remember removing it before or after generating the support bundle file? If so, would you please generate a new one for us? With that said, I would say removing the machine object is a bold move, and I do not recommend it even in regular times, not to say the cluster was under upgrading.
- Do you remember when you updated the containerd-registry setting? Was it during the first node draining?

We're checking whether the accidental draining on the first node is due to the containerd registry setting update during the upgrade that triggered the cluster upgrade mechanism to rerun. The first node of the cluster was under the draining process, and there was a pre-drain annotation on the machine's secret object `custom-fb4dda4acb64-machine-plan`. Our plan is to help the Rancher Manager think the first node completed the pre-draining/draining/post-draining so the overall upgrade process can proceed to the remaining nodes. The helper scripts could be found [here](https://github.com/bk201/misc/tree/main/rancher). But I suggest not taking action until we get the latest support bundle file.

Thank you.

**Comment by W0n9** [comment]
Hi @starbops 
1. I removed the machine `custom-fb4dda4acb64` after generating the support bundle file. Here is my latest support bundle.
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.001.zip](https://github.com/user-attachments/files/15863970/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.001.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.002.zip](https://github.com/user-attachments/files/15863976/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.002.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.003.zip](https://github.com/user-attachments/files/15863978/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-17T08-07-36Z.003.zip)


2. I updated the containerd-registry setting during the first node stuck at pre-draining, because I metioned that it raised an error about network issues to `docker.io`

And I tried to delete `custom-3b78a7b9d849` this morning, which made node `harvester-dc-2` dead, so I delete this node and reinstall harvester in this node later🥲.
And more, I have followed [this](https://docs.harvesterhci.io/v1.3/upgrade/troubleshooting#start-over-an-upgrade) to pause the upgrade now.

**Comment by starbops** [comment]
Since you've removed the latest Upgrade CR, it's hard to determine the cluster status from Harvester's POV. From the SB file, it seems Rancher is waiting for the `custom-b2c31fbb0694` machine, which is `harvester-dc-3`. The machine's Secrete `custom-b2c31fbb0694-machine-plan` has a `rke.cattle.io/pre-drain` annotation. Please [follow these steps](https://github.com/harvester/harvester/issues/4698#issuecomment-1818363857) to make the cluster stable first, and we'll see how to proceed next (please attach a new SB file once you've done the above steps).

**Comment by W0n9** [comment]
Hi @starbops 
I have excuted `./pre-drain.sh harvester-dc-3`.
Here is drain-status
```yaml
harvester-dc-3 (custom-b2c31fbb0694)
  rke-pre-drain: {"deleteEmptyDirData":true,"disableEviction":false,"enabled":true,"force":true,"gracePeriod":0,"ignoreDaemonSets":true,"ignoreErrors":false,"postDrainHooks":[{"annotation":"harvesterhci.io/post-hook"}],"preDrainHooks":[{"annotation":"harvesterhci.io/pre-hook"}],"skipWaitForDeleteTimeoutSeconds":0,"timeout":0}
  harvester-pre-hook {"deleteEmptyDirData":true,"disableEviction":false,"enabled":true,"force":true,"gracePeriod":0,"ignoreDaemonSets":true,"ignoreErrors":false,"postDrainHooks":[{"annotation":"harvesterhci.io/post-hook"}],"preDrainHooks":[{"annotation":"harvesterhci.io/pre-hook"}],"skipWaitForDeleteTimeoutSeconds":0,"timeout":0}
  rke-post-drain: null
  harvester-post-hook: null
```
And rancher-manager changed to raise
```
error when evicting pods/"instance-manager-711b9c134175947eb1a667910cf0df49" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod longhorn-system/instance-manager-711b9c134175947eb1a667910cf0df49
```
Here is my latest support bundle
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.001.zip](https://github.com/user-attachments/files/15884488/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.001.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.002.zip](https://github.com/user-attachments/files/15884489/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.002.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.003.zip](https://github.com/user-attachments/files/15884490/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-18T10-02-28Z.003.zip)

**Comment by starbops** [comment]
Hi @W0n9 

Are the pod eviction error messages still appearing? If yes, please try to shut down all the VM on the cluster. Next, please remove the PDB with the following command:

```sh
kubectl -n longhorn-system delete pdb instance-manager-711b9c134175947eb1a667910cf0df49
```

After removing the PDB, please observe the rancher-manager's log to see if new instance-manager Pods failed to evict and remove their PDB object to resolve the issue. Once such a situation is no longer present, run the `drain-status.sh` again to see if the `rke-post-drain` pops up with data. If that's the case, run the `post-drain.sh` script against the node. Please generate a new support bundle for us after conducting the above steps.

**Comment by W0n9** [comment]
Hi @starbops 
I have excuted the command above, and got rid of evicting pods problem.
But the `rke-post-drain` still report `null`, here is the drain-status
```yaml
harvester-dc-0 (custom-fb4dda4acb64)
Error from server (NotFound): secrets "custom-fb4dda4acb64-machine-plan" not found
  rke-pre-drain: null
  harvester-pre-hook null
  rke-post-drain: null
  harvester-post-hook: null

harvester-dc-1 (custom-10890feba805)
  rke-pre-drain: null
  harvester-pre-hook null
  rke-post-drain: null
  harvester-post-hook: null

harvester-dc-3 (custom-b2c31fbb0694)
  rke-pre-drain: {"deleteEmptyDirData":true,"disableEviction":false,"enabled":true,"force":true,"gracePeriod":0,"ignoreDaemonSets":true,"ignoreErrors":false,"postDrainHooks":[{"annotation":"harvesterhci.io/post-hook"}],"preDrainHooks":[{"annotation":"harvesterhci.io/pre-hook"}],"skipWaitForDeleteTimeoutSeconds":0,"timeout":0}
  harvester-pre-hook {"deleteEmptyDirData":true,"disableEviction":false,"enabled":true,"force":true,"gracePeriod":0,"ignoreDaemonSets":true,"ignoreErrors":false,"postDrainHooks":[{"annotation":"harvesterhci.io/post-hook"}],"preDrainHooks":[{"annotation":"harvesterhci.io/pre-hook"}],"skipWaitForDeleteTimeoutSeconds":0,"timeout":0}
  rke-post-drain: null
  harvester-post-hook: null
```
And rancher-manager changed to raise
```
2024/06/19 07:00:00 [ERROR] rkecluster fleet-local/local: error while retrieving management cluster from cache: management cluster cache was nil
2024/06/19 07:00:00 [INFO] [planner] rkecluster fleet-local/local: configuring etcd node(s) custom-b2c31fbb0694: waiting for probes: etcd, kube-apiserver, kube-controller-manager, kube-scheduler
```
Here is my latest support bundle files:
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.001.zip](https://github.com/user-attachments/files/15897276/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.001.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.002.zip](https://github.com/user-attachments/files/15897278/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.002.zip)
[supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.003.zip](https://github.com/user-attachments/files/15897283/supportbundle_7e8aefe3-479a-4fa4-97d8-af2f283e4577_2024-06-19T07-42-35Z.003.zip)
