### ISSUE TITLE
[BUG] IPPool Config should provide same content as YAML

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6046]
**Describe the bug**
1. IP pool content via Config is NOT the same as YAML
2. Shouldn't **Edit YAML** and **Edit Config** -> **Edit as YAML** gives same YAML content?

**To Reproduce**
1. Create IP pool **cidr-subnet**
   ![image](https://github.com/harvester/harvester/assets/2773781/eea10bcd-6600-4bb2-8018-4e6620d94401)
   * <details>
     <summary> :green_circle: Edit YAML
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/08fa7406-5095-4968-bd3c-082b9ea516bf)
     </details>
   * <details>
     <summary> :green_circle: Check Config
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/f78ae007-cd67-4f72-aa99-6bd00af0f926)
     </details>

1. Create IP pool **range-subnet-start-end**
   ![image](https://github.com/harvester/harvester/assets/2773781/4d3fdc0a-8556-461c-a0ef-71092f858bc9)

   * <details>
     <summary> :green_circle: Edit YAML
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/36c0d633-526c-48e0-9b12-0feae83c0e93)
     </details>
   * <details>
     <summary> :green_circle: Check Config
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/c2d77ecf-f0bc-44c9-9a07-8845da27921a)
     </details>

1. Create IP pool **range-subnet-start**
   ![image](https://github.com/harvester/harvester/assets/2773781/fe042718-f05a-450d-a06e-19119196b64c)

   * <details>
     <summary> :green_circle: Edit YAML
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/3b288749-9b0f-426f-9080-0e82a9baa2d0)
     </details>
   * <details open>
     <summary> :red_circle: Check Config
     </summary>

     * **View Config**
       No StartIP
       ![image](https://github.com/harvester/harvester/assets/2773781/25da5dd5-2a61-4774-bc0d-89403bbba96c)
     * **Edit Config**
       No StartIP
       ![image](https://github.com/harvester/harvester/assets/2773781/7c585f30-ad50-4fab-8fe9-dee46f197ece)
     * **Edit Config** -> **Edit as YAML**
       Not the same as **Edit YAML**
       ![image](https://github.com/harvester/harvester/assets/2773781/8aef9ead-575b-4de8-9ea0-2e494778a903)
     </details>

1. Create IP pool **range-subnet-end**
   ![image](https://github.com/harvester/harvester/assets/2773781/0348b78c-3903-4e6b-a279-564da9971e6e)

   * <details>
     <summary> :green_circle: Edit YAML
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/35d321c7-4dce-4b5e-9920-684dd3e2fb90)
     </details>
   * <details open>
     <summary> :red_circle: Check Config
     </summary>

     * **View Config**
       No EndIP
       ![image](https://github.com/harvester/harvester/assets/2773781/ecf5abb1-04b1-427f-a089-10a30ce5afa1)
     * **Edit Config**
       No EndIP
       ![image](https://github.com/harvester/harvester/assets/2773781/5e89593f-a670-4dc8-a0c3-39c8db843836)
     * **Edit Config** -> **Edit as YAML**
       Not the same as **Edit YAML**
      ![image](https://github.com/harvester/harvester/assets/2773781/f33bfa62-d51e-4954-98c2-7ff46d9725a6)
     </details>
 

**Expected behavior**
1. IP pool content should be the same no matter via YAML or Config
2. Shouldn't **Edit YAML** and **Edit Config** -> **Edit as YAML** gives same YAML content?

**Support bundle**
[supportbundle_ippoolConfig_2024-06-20T06-53-58Z.zip](https://github.com/user-attachments/files/15910012/supportbundle_ippoolConfig_2024-06-20T06-53-58Z.zip)

**Environment**
* **harvester-`v1.3.1`**
  * Profile: Single node QEMU/KVM (8C/32G/500G)
  * ui-source: `Auto`

**Additional context**
n/a

**Comment by houhoucoop** [comment]
@albinsun 
When clicking `Edit YAML`, it retrieves data directly from the CRD.
When clicking `Edit Config → Edit as YAML`, it converts form data into YAML content.
The content will look different, but I think it's expected.

**Comment by asc5543** [comment]
## Test result
Test PASS, the IP Pools information is the same even create by config or yaml

## Environment
* Harvester ISO version: `v1.6-9b417305-head`
* Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node Baremetal

## Test Scope

* IP Pools -> Create -> Add Range
  * Subnet
    * No other content (cidr-subnet)
    * With Start IP & End IP (range-subnet-start-end)
    * With Start IP (range-subnet-start)
    * With End IP (range-subnet-end)

## Test Scenario

1. <details>
   <summary> ✔ Create IP Pool with <b>cidr-subnet</b>
   </summary>

   * <details>
     <summary> Fill in information on "Edit config", then click "Edit as YAML"
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/3870d35b-59fc-4448-ba1c-48b1c66d2240" />

     </details>

   * <details>
     <summary> Click "Create" on "Edit as YAML" page
     </summary>

     ```
     apiVersion: loadbalancer.harvesterhci.io/v1beta1
     kind: IPPool
     metadata:
       name: test
       annotations:
         {}
         #  key: string
       labels:
         {}
         #  key: string
     spec:
       selector:
         network: ''
     #    priority: int
     #    scope:
     #      - guestCluster: string
     #        namespace: string
     #        project: string
       ranges:
         - subnet: 192.168.0.0/24
           gateway: ''
           type: cidr
     #    - gateway: string
     #      rangeEnd: string
     #      rangeStart: string
     #      subnet: string
     #  description: string
     __clone: true
     ```

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/5099b0c5-00f6-437c-80ee-6384ead38eda" />

     </details>

   * <details>
     <summary> Click "Edit Config" and check the config, Subnet exist
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/b085e67a-e81f-4fad-a105-48915289b4e0" />
     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/f3382a31-44f6-4fc3-834d-894e67f2117a" />

     </details>
   </details>

1. <details>
   <summary> ✔ Create IP Pool with <b>range-subnet-start-end</b>
   </summary>

   * <details>
     <summary> Fill in information on "Edit config", then click "Edit as YAML"
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/4d01de7b-beb0-4516-908b-f8c791f3d26a" />

     </details>

   * <details>
     <summary> Click "Create" on "Edit as YAML" page
     </summary>

     ```
     apiVersion: loadbalancer.harvesterhci.io/v1beta1
     kind: IPPool
     metadata:
       name: test
       annotations:
         {}
         #  key: string
       labels:
         {}
         #  key: string
     spec:
       selector:
         network: ''
     #    priority: int
     #    scope:
     #      - guestCluster: string
     #        namespace: string
     #        project: string
       ranges:
         - subnet: 192.168.0.0/24
           gateway: ''
           rangeStart: 192.168.0.20
           rangeEnd: 192.168.0.29
           type: range
     #    - gateway: string
     #      rangeEnd: string
     #      rangeStart: string
     #      subnet: string
     #  description: string
     __clone: true
     ```

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/104fb430-b3c3-43e6-bac7-ca32499bed2a" />

     </details>

   * <details>
     <summary> Click "Edit Config" and check the config, Subnet, Start IP and End IP exist
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/bed7bd6b-2ebc-4f1d-846c-5efa1ae1751b" />
     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/fc377349-9821-4fd4-80dd-f72c9f7d3068" />

     </details>
   </details>

1. <details>
   <summary> ✔ Create IP Pool with <b>range-subnet-start</b>
   </summary>

   * <details>
     <summary> Fill in information on "Edit config", then click "Edit as YAML"
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/e4383d46-9407-40f8-acdb-155fb58c3635" />

     </details>

   * <details>
     <summary> Click "Create" on "Edit as YAML" page
     </summary>

     ```
     apiVersion: loadbalancer.harvesterhci.io/v1beta1
     kind: IPPool
     metadata:
       name: test
       annotations:
         {}
         #  key: string
       labels:
         {}
         #  key: string
     spec:
       selector:
         network: ''
     #    priority: int
     #    scope:
     #      - guestCluster: string
     #        namespace: string
     #        project: string
       ranges:
         - subnet: 192.168.0.0/24
           gateway: ''
           rangeStart: 192.168.0.30
           rangeEnd: ''
           type: range
     #    - gateway: string
     #      rangeEnd: string
     #      rangeStart: string
     #      subnet: string
     #  description: string
     __clone: true
     ```

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/d42fe03c-304b-4d51-9c56-0bc08b3bf46d" />

     </details>

   * <details>
     <summary> Click "Edit Config" and check the config, Subnet and Start IP exist
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/cfd0d3f6-b7d7-45f4-972a-babe1ed1019d" />
     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/35f71c4b-9ae8-4d15-aa01-f0a0368a87bd" />

     </details>
   </details>

1. <details>
   <summary> ✔ Create IP Pool with <b>range-subnet-end</b>
   </summary>

   * <details>
     <summary> Fill in information on "Edit config", then click "Edit as YAML"
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/00c28dd1-de04-4d6a-89b5-bcd00898adb2" />

     </details>

   * <details>
     <summary> Click "Create" on "Edit as YAML" page
     </summary>

     ```
     apiVersion: loadbalancer.harvesterhci.io/v1beta1
     kind: IPPool
     metadata:
       name: test
       annotations:
         {}
         #  key: string
       labels:
         {}
         #  key: string
     spec:
       selector:
         network: ''
     #    priority: int
     #    scope:
     #      - guestCluster: string
     #        namespace: string
     #        project: string
       ranges:
         - subnet: 192.168.0.0/24
           gateway: ''
           rangeStart: ''
           rangeEnd: 192.168.0.19
           type: range
     #    - gateway: string
     #      rangeEnd: string
     #      rangeStart: string
     #      subnet: string
     #  description: string
     __clone: true
     ```

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/3a1e14ac-bffb-497b-94fd-f83017aec596" />

     </details>

   * <details>
     <summary> Click "Edit Config" and check the config, Subnet, Start IP and End IP exist
     </summary>

     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/c4924e51-1551-4fb7-94ad-e1148d8b8ed5" />
     <img width="1908" height="973" alt="Image" src="https://github.com/user-attachments/assets/27e3dd56-d848-4a09-aa8b-9d3ace740bf5" />

     </details>
   </details>
