### ISSUE TITLE
[Question] Is virtio-net multiqueue supported in Harvester?

### ISSUE THREAD

**Issue by tahvane1** [harvester/harvester#6068]
I'm trying to get cilium work properly with guest cluster and XDP acceleration and I'm running into issues with NIC multiqueue.
Hence i'm asking if virtio-net multiqueue supported in Harvester?

In Kubevirt it is configured like

kind: VM
spec:
  domain:
    devices:
      networkInterfaceMultiqueue: true

More details from https://kubevirt.io/user-guide/network/interfaces_and_networks/#virtio-net-multiqueue

**Comment by m-ildefons** [comment]
Hi Erkka,

It should work, but it's not supported in the UI.
You'll need to enable it at this path in the YAML manifest when creating the VM:

![Screenshot at 2024-06-27 11-55-21](https://github.com/harvester/harvester/assets/17141774/f69de727-402a-4a26-8f14-c2d168bbcbfc)

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
spec:
  template:
    spec:
      domain:
        devices:
          networkInterfaceMultiqueue: true
          interfaces:
            - macAddress: 8a:8f:93:ed:c6:72
              masquerade: {}
              model: virtio
              name: default
```

With this, I was successfully able to create a VM on Harvester v1.3.0 with multiple queues on a virtio interface:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
[...]
status:
  interfaces:
    - infoSource: domain, guest-agent
      interfaceName: eth0
      ipAddress: 10.52.0.182
      ipAddresses:
        - 10.52.0.182
      mac: 8a:8f:93:ed:c6:72
      name: default
      queueCount: 4
```

There no option in the UI to enable this behavior and you'll have to edit the VM manifest by hand. Also I've not confirmed within the VM if the network interface actually shows up with multiple queues.

Hope this helps.
