### ISSUE TITLE
[BUG] A manual attached LH volume breaks Harvester maintenance mode

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6264]
**Describe the bug**

A manual attached LH volume breaks Harvester maintenance mode

**To Reproduce**

1. Create a volume manually on Harveter UI and attache this volume to a node from harvester embedded LH UI
![image](https://github.com/user-attachments/assets/4d7c8e47-7015-4160-a5c6-67072ea6c5fc)

after attaching
![image](https://github.com/user-attachments/assets/3e061328-9700-4fc0-990d-e9943716ebe0)

2. Put this node into `maintenance mode`

3. The node may stuck on `Cordoned` status, and the menu, `Enable maintenance mode` is available again

![image](https://github.com/user-attachments/assets/260a53b1-a840-4c25-a79a-143fa1baff11)

4. There are continuously reported such error on Harvester pod, it fails to evict LH pod

```
time="2024-08-05T09:51:06Z" level=info msg="evicting pod longhorn-system/instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7"
time="2024-08-05T09:51:06Z" level=info msg="error when evicting pods/\"instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7\" -n \"longhorn-system\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget."
```

the error was also reported on https://github.com/longhorn/longhorn/issues/5910

LH fails silently https://github.com/longhorn/longhorn/issues/9183

**Expected behavior**

1. Put into `enable maintenance mode` should report proper error/emit event to show the error
3. It should fail after certain time

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

LH CRD object also have evidence:

The LH UI attached volume:

```
- apiVersion: longhorn.io/v1beta2
  kind: VolumeAttachment
...
  spec:
    attachmentTickets:
      longhorn-ui:
        generation: 0
        id: longhorn-ui
        nodeID: s37570031
        parameters:
          disableFrontend: "false"
          lastAttachedBy: "null"
        type: longhorn-api
    volume: pvc-9b35136c-f59e-414b-aa55-b84b9b21ff89
```

The CSI attached volume:

```
  spec:
    attachmentTickets:
      csi-b5097155cddde50b4683b0e659923e379cbfc3873b5b2ee776deb3874102e9bf:
        generation: 0
        id: csi-b5097155cddde50b4683b0e659923e379cbfc3873b5b2ee776deb3874102e9bf
        nodeID: s37570032
        parameters:
          disableFrontend: "false"
          lastAttachedBy: "null"
        type: csi-attacher
    volume: pvc-3c6403cd-f1cd-4b84-9b46-162f746b9667          
```
