### ISSUE TITLE
[BUG] UpgradeLog can't be ready cause of fluentd PVC doesn't give access mode

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#6272]
**Describe the bug**
When testing upgrade with log enabled on master branch, the upgradelog can't be ready cause of fluentd statefulset is not ready. The reason is that PVC spec doesn't have access mode, so PVC can't be created.

hvst-upgrade-pgdtp-upgradelog-infra-fluentd event:
```
  Warning  FailedCreate  2m44s (x18 over 13m)  statefulset-controller  create Claim hvst-upgrade-pgdtp-upgradelog-infra-hvst-upgrade-pgdtp-upgradelog-log-archive-hvst-upgrade-pgdtp-upgradelog-infra-fluentd-0 for Pod hvst-upgrade-pgdtp-upgradelog-infra-fluentd-0 in StatefulSet hvst-upgrade-pgdtp-upgradelog-infra-fluentd failed error: PersistentVolumeClaim "hvst-upgrade-pgdtp-upgradelog-infra-hvst-upgrade-pgdtp-upgradelog-log-archive-hvst-upgrade-pgdtp-upgradelog-infra-fluentd-0" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]
```

hvst-upgrade-pgdtp-upgradelog-infra-fluentd statefulset spec:
```yaml
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: fluentd
        app.kubernetes.io/managed-by: hvst-upgrade-pgdtp-upgradelog-infra
        app.kubernetes.io/name: fluentd
        harvesterhci.io/upgradeLog: hvst-upgrade-pgdtp-upgradelog
        harvesterhci.io/upgradeLogComponent: aggregator
      name: hvst-upgrade-pgdtp-upgradelog-infra-hvst-upgrade-pgdtp-upgradelog-log-archive
      namespace: harvester-system
      ownerReferences:
      - apiVersion: logging.banzaicloud.io/v1beta1
        controller: true
        kind: Logging
        name: hvst-upgrade-pgdtp-upgradelog-infra
        uid: 6d7089d5-3bf4-448a-be13-3630fd556a10
    spec:
      resources: {}
      volumeMode: Filesystem
    status:
      phase: Pending
```

**To Reproduce**
1. Create a Harvester cluster with master branch.
2. Create a version:
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: master-head
  namespace: harvester-system
spec:
  isoURL: http://192.168.0.181:8000/harvester-master-amd64.iso
  minUpgradableVersion: 1.3.1
  releaseDate: "202401231"
  tags:
  - dev
  - test
```
3. Click upgrade with log.

**Expected behavior**
The upgrade log can be ready.

**Environment**
 - Harvester ISO version: master-e5403aa-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Comment by starbops** [comment]
Thanks for raising the issue. We just bumped the rancher-logging chart from 103.0.0+up3.17.10 to 103.1.0+up4.4.0 in harvester/harvester-installer#766. An upstream PR kube-logging/logging-operator#1304 changed how it handles the ExtraVolumes for fluentd, and it was introduced since v4.2.0.

The PVC posted in the issue description is created by the Logging CR (see OwnerReference), not UpgradeLog CR. There might be conflicts between the current upgrade log mechanics and the newly introduced (actually, it's not so new in terms of the version) logging-operator behavior.

We should update our upgrade log implementation to adapt to the new upstream behavior.

Note: since the rancher-logging bumping PR was backported to v1.4 branch, I think upgrading from v1.4 to v1.4 will encounter the same issue.

**Comment by w13915984028** [comment]
BTW: I am considering not to bump `rancher-logging` chart version on v1.3.2 and backport the fix for this issue to v1.3.2, then we are safe to upgrade from v1.3.2 to v1.4.0. WDYT?

https://github.com/harvester/harvester-installer/pull/790

**Comment by starbops** [comment]
After investigation, I have to say it's a bit complicated:

We leveraged the ExtraVolumes for fluentd Pod to mount an external PVC that's created independently to the creation of the Logging CR. We did this because of the following:

1. We need a dedicated volume for the fluentd Pod to store the collected logs locally. At the time being, we cannot make it create a PVC for the fluentd StatefulSet by specifying `.spec.fluentd.extraVolumes[].volume.pvc.spec`. It was a bug. So we leveraged `.spec.fluentd.extraVolumes[].volume.pvc.source` to make it use a pre-created PVC, which was done by our controller, to spin up fluentd. And the workaround worked perfectly.
2. Creating a dedicated PVC achieves yet another essential objective of the upgradelog mechanics: distinct of lifecycle. We want users to download those logs even after the Logging CR is removed.

As I mentioned, kube-logging/logging-operator#1304 changed how it handles ExtraVolumes for fluentd. That PR basically tried to solve (1), but somewhat broke the path we used it. After v4.2.0, [it will **always** populate a volume claim for the fluentd StatefulSet](https://github.com/kube-logging/logging-operator/blob/cb0f36bfd3accbbe2ef943343872d9a50e052032/pkg/resources/fluentd/statefulset.go#L51-L57) if `.spec.fluentd.extraVolumes[].volume.pvc` is not empty. We only specified `.spec.fluentd.extraVolumes[].volume.pvc.source` but not `.spec.fluentd.extraVolumes[].volume.pvc.spec`, so the populated volume claim is buggy (no access modes are specified, which are required values):

```
  ...
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      ...
      name: hvst-upgrade-d2rg7-upgradelog-infra-hvst-upgrade-d2rg7-upgradelog-log-archive
      namespace: harvester-system
      ...
    spec:
      resources: {}
      volumeMode: Filesystem
    status:
      phase: Pending
...
```

Thus the error message (from the fluentd StatefulSet):

```
PersistentVolumeClaim "hvst-upgrade-pgdtp-upgradelog-infra-hvst-upgrade-pgdtp-upgradelog-log-archive-hvst-upgrade-pgdtp-upgradelog-infra-fluentd-0" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value
```

This behavior was fixed in v4.6.0, introduced by PR kube-logging/logging-operator#1617. [It will try to use the existing PVC for the fluentd Pod](https://github.com/kube-logging/logging-operator/blob/421fefebc813cb78d0ce26edd767ada97923519b/pkg/resources/fluentd/statefulset.go#L56-L59).

Back to now, we're bumping `rancher-logging` to 103.1.0+up4.4.0, which is the affected version. But it seems v4.4.0 is the only version we can jump to as the embedded Rancher is of version v2.8.x. I need more time to figure out how to adapt this...

---

> BTW: I am considering not to bump rancher-logging chart version on v1.3.2 and backport the fix for this issue to v1.3.2, then we are safe to upgrade from v1.3.2 to v1.4.0. WDYT?

@w13915984028 Thanks for noting. I think it's okay to not bump it for v1.3.2 since the upgrade log mechanics starts at the very beginning of the Harvester upgrade procedure, it will always use the old version. We just need to make sure as long as we bump `rancher-logging`, we have also to ship the fix for upgrade log.

**Comment by starbops** [comment]
The best way I can think of, given that we bumped `rancher-logging` to  103.1.0+up4.4.0, is to give up creating and using the PVC ourselves. Instead, we will embrace the new behavior to specify the spec of the PVC to let the logging-operator create the volume claim for the fluentd StatefulSet. The catch is that the UpgradeLog controller will now add a finalizer to the PVC to prevent it from being removed after the Logging CR is deleted.

**Comment by starbops** [comment]
The new implementation will be adding the UpgradeLog as an OwnerReference to the PVC. Adding a finalizer is not feasible because the PVC still enters the terminating state when its owner (Logging CR) is purged. As a result, the packager Job could not attach to the volume.

**Comment by brandboat** [comment]
Test failed, gentle ping @starbops

### 1. Upgrade a Harvester cluster from v1.4.0-dev-20240918 to master (https://github.com/harvester/harvester/commit/9d5b63eb3afd5679cfe3e60b0be0b6f01153d6e0)
<details>
<summary>Environment</summary>

* [`v1.4.0-dev-20240918`](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`
* upgrade.yaml
  ```yaml
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: master
    namespace: harvester-system
  spec:
    isoURL: http://192.168.100.1:8000/harvester-master-amd64.iso
  ---
  apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/skip-version-check: "true"
      harvesterhci.io/skipWebhook: "true"
    generateName: hvst-upgrade-
    namespace: harvester-system
  spec:
    version: "master"
    logEnabled: true
  ```
  
</details>

<details>
<summary>✅  We can download upgrade log during the upgrade</summary>
  <img width="1661" alt="截圖 2024-09-23 下午4 49 18" src="https://github.com/user-attachments/assets/fe3d8eb8-e4ba-4b81-9314-a408c79fe684">
</details>
<details>
<summary>✅  We can download upgrade after the upgrade finished</summary>
  <img width="1669" alt="image" src="https://github.com/user-attachments/assets/516a2e78-7702-4678-afdc-fdbf4f51e88d">
</details>

### 2. Upgrade a Harvester cluster from v1.3.2 to v1.4.0-dev-20240918

<details>
<summary>Environment</summary>

* [`v1.3.2`](https://github.com/harvester/harvester/releases/tag/v1.3.2)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`
* upgrade.yaml
  ```yaml
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: v1.4.0-dev-20240918
    namespace: harvester-system
  spec:
    isoURL: http://192.168.100.1:8000/harvester-v1.4.0-dev-20240918-amd64.iso
  ---
  apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/skip-version-check: "true"
      harvesterhci.io/skipWebhook: "true"
    generateName: hvst-upgrade-
    namespace: harvester-system
  spec:
    version: "v1.4.0-dev-20240918"
    logEnabled: true
  ```
</details>

<details>
<summary>✅  We can download upgrade log during the upgrade</summary>
  <img width="1677" alt="image" src="https://github.com/user-attachments/assets/52f2eb73-009e-4c94-80a1-adecd4ae0841">
</details>
<details open>
<summary> ❌ We can download upgrade log after the upgrade finished </summary>

  ![image](https://github.com/user-attachments/assets/28f35ec3-99a2-42ef-b891-5c4b9d1279cd)
  Press the `Download log` button, after waiting over 10mins, I can't download upgrade log. Looking into the `hvst-upgrade-rl8vx-upgradelog-packager-zhmhz-ch269` and it complains the PVC is missing. 
  ```
  harvester-node-0:~ # kubectl events pods hvst-upgrade-rl8vx-upgradelog-packager-zhmhz-ch269 -n harvester-system | tail -n 1
  6m29s (x2 over 11m)   Warning   FailedScheduling         Pod/hvst-upgrade-rl8vx-upgradelog-packager-zhmhz-ch269                0/2 nodes are available: persistentvolumeclaim "hvst-upgrade-rl8vx-upgradelog-infra-log-archive-hvst-upgrade-rl8vx-upgradelog-infra-fluentd-0" not found. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling..
  ```

  ```
  harvester-node-0:~ # kubectl get pvc -n harvester-system
  NAME                                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
  hvst-upgrade-rl8vx-upgradelog-log-archive   Bound    pvc-45338f21-3769-41f7-8c5f-9225fc280114   1Gi        RWO            harvester-longhorn   57m
  ``` 
  
</details>

**Comment by starbops** [comment]
@brandboat This is because the harvester pod is of the new version, the logic for selecting the target PVC is already the new implementation. We need to update the implementation to ensure it's backward compatible.

**Comment by brandboat** [comment]
All tests passed, thanks @starbops !

### 1. Upgrade a Harvester cluster from v1.4.0-head (https://github.com/harvester/harvester/commit/1428e5a9dd1250a87ebcfa2e7eb1d4627f4029db) to master (https://github.com/harvester/harvester/commit/89628d3927553a0a858d11e6071c3274c15e601e)
<details>
<summary>Environment</summary>

* `v1.4.0-head`
  * Profile: 1 node QEMU/KVM (8C/16G/250G)
  * ui-source: `Auto`
* upgrade.yaml
  ```yaml
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: master
    namespace: harvester-system
  spec:
    isoURL: http://192.168.100.1:8000/harvester-master-amd64.iso
  ---
  apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/skip-version-check: "true"
      harvesterhci.io/skipWebhook: "true"
    generateName: hvst-upgrade-
    namespace: harvester-system
  spec:
    version: "master"
    logEnabled: true
  ```
  
</details>

✅  We can download upgrade log during the upgrade</summary>
✅  We can download upgrade after the upgrade finished

### 2. Upgrade a Harvester cluster from v1.3.2 to v1.4.0-head (https://github.com/harvester/harvester/commit/1428e5a9dd1250a87ebcfa2e7eb1d4627f4029db)

<details>
<summary>Environment</summary>

* [`v1.3.2`](https://github.com/harvester/harvester/releases/tag/v1.3.2)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`
* upgrade.yaml
  ```yaml
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: v1.4.0-dev-20240918
    namespace: harvester-system
  spec:
    isoURL: http://192.168.100.1:8000/harvester-v1.4.0-dev-20240918-amd64.iso
  ---
  apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/skip-version-check: "true"
      harvesterhci.io/skipWebhook: "true"
    generateName: hvst-upgrade-
    namespace: harvester-system
  spec:
    version: "v1.4.0-dev-20240918"
    logEnabled: true
  ```
</details>

✅  We can download upgrade log during the upgrade
✅ We can download upgrade log after the upgrade finished
