### ISSUE TITLE
[BUG] The default settings to Longhorn seems not updated to Longhorn

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6273]
**Describe the bug**

Harvester sets a few LH options from the managedchart, but seems to be broken now.

https://github.com/harvester/harvester-installer/blob/677447c880710793ab29d676c513caaae1170b55/pkg/config/templates/rancherd-10-harvester.yaml#L173

```
managedchart -n fleet-local harvester -oyaml

apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  annotations:
...
    longhorn:
      defaultSettings:
        defaultDataPath: /var/lib/harvester/defaultdisk  // original
        detachManuallyAttachedVolumesWhenCordoned: true // new ones
        nodeDrainPolicy: allowIfReplicaIsStopped // new ones
        taintToleration: kubevirt.io/drain:NoSchedule // original
```

longhorn:
```
settings.longhorn.io -A
NAMESPACE         NAME                                                              VALUE                                             APPLIED   AGE
...
longhorn-system   default-data-path                                                 /var/lib/longhorn/                                true      7m30s
...
longhorn-system   node-down-pod-deletion-policy                                     do-nothing                                        true      7m30s
longhorn-system   node-drain-policy                                                 block-if-contains-last-replica                    true      7m30s
...
longhorn-system   taint-toleration                                                                                                    true      7m30s
```

**To Reproduce**
1. New install with Harvester v1.4.0 ISO

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
The reason is as such:

The yaml 
https://github.com/harvester/harvester-installer/blob/677447c880710793ab29d676c513caaae1170b55/pkg/config/templates/rancherd-10-harvester.yaml#L171

is updated with new values

```
        defaultSettings:
          taintToleration: "kubevirt.io/drain:NoSchedule"
          defaultDataPath: "/var/lib/harvester/defaultdisk"
          {{- if .Harvester.Longhorn.DefaultSettings.GuaranteedInstanceManagerCPU }}
          guaranteedInstanceManagerCPU: {{ .Harvester.Longhorn.DefaultSettings.GuaranteedInstanceManagerCPU }}
          {{- end }}
          detachManuallyAttachedVolumesWhenCordoned: true
          nodeDrainPolicy: "allowIfReplicaIsStopped"
```

And it was converted to a configmap

```
configmap -n longhorn-system longhorn-default-setting -oyaml
apiVersion: v1
data:
  default-setting.yaml: |-
    default-data-path: /var/lib/harvester/defaultdisk
    taint-toleration: kubevirt.io/drain:NoSchedule
    priority-class: system-cluster-critical
    node-drain-policy: allowIfReplicaIsStopped
    detach-manually-attached-volumes-when-cordoned: true
    disable-revision-counter: true
    concurrent-automatic-engine-upgrade-per-node-limit: 3
    auto-cleanup-when-delete-backup: true
kind: ConfigMap
```

Unfortunately, the `node-drain-policy` should be `allow-if-replica-is-stopped` instead of `allowIfReplicaIsStopped`.  with the `allowIfReplicaIsStopped`. The LH manager has such error:

>time="2024-08-06T09:02:07Z" level=error msg="Customized settings are invalid, will give up using them: the value of customized setting node-drain-policy is invalid" func=types.GetCustomizedDefaultSettings file="setting.go:1611" error="value allowIfReplicaIsStopped of settings node-drain-policy is invalid: failed to validate the setting node-drain-policy: value allowIfReplicaIsStopped is not a valid choice, available choices [block-for-eviction block-for-eviction-if-contains-last-replica block-if-contains-last-replica allow-if-replica-is-stopped always-allow]"
