### ISSUE TITLE
[ENHANCEMENT] Add installer commit hash to /etc/harvester-release.yaml

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6285]
**Is your enhancement related to a problem? Please describe.**
As seen when testing https://github.com/harvester/harvester/issues/6215, we had an ISO build from a stable branch (v1.3) which was missing a change from harvester-installer, because that change happened after the latest change in the harvester repo. This fact was not obvious, and required checking the commit history of the harvester and harvester-installer repos to figure out relative dates and build times.

**Describe the solution you'd like**
Add the commit hash of harvester-installer to the version information in /etc/harvester-release.yaml. This will make it easy to quickly verify exactly which version of the harvester-installer code was used in a given build.

**Describe alternatives you've considered**
Refactor the ISO build process as describe in https://github.com/harvester/harvester/issues/5859, but we're not there yet :-)

**Additional context**
N/A

**Comment by w13915984028** [comment]
From `harvester-v1.4.0-dev-20240918-amd64.iso` we get:

![image](https://github.com/user-attachments/assets/bee7b3b2-f6ae-459a-9540-3adccb0fbb5d)


```
$cat /etc/harvester-release.yaml 
harvester: v1.4.0-dev-20240918
harvesterChart: 1.4.0-dev-20240918
installer: 00d3a70 <----------------------------------------installer commit id
os: Harvester v1.4.0-dev-20240918
kubernetes: v1.28.12+rke2r1
rancher: v2.8.5
monitoringChart: 103.1.1+up45.31.1
loggingChart: 103.1.0+up4.4.0
kubevirt: 1.2.2-150500.8.21.1
minUpgradableVersion: 'v1.3.1'
rancherDependencies:
  fleet:
    chart: 103.1.5+up0.9.5
    app: 0.9.5
  fleet-crd:
    chart: 103.1.5+up0.9.5
    app: 0.9.5
  rancher-webhook:
    chart: 103.0.6+up0.4.7
    app: 0.4.7
```

And the installer commit can help link to:
https://github.com/harvester/harvester-installer/commit/00d3a70a597e24b3a034925369933b3e8c7def20
