### ISSUE TITLE
[BUG] Unable to provision custom RKE2 cluster, stuck in waiting for cluster agent to connect

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#6286]
**Describe the bug**

When we try to provision a custom RKE2 cluster on Harvester v1.4.0 master with Rancher v2.8.5 

The custom RKE2 cluster would stuck in `waiting for cluster agent to connect` and can't turn into running

  ![image](https://github.com/user-attachments/assets/d87869b2-2f16-4e0f-99dc-a5f5a640def4)

* Check the rke2-server status would display error message
  ```
  Aug 07 06:13:50 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:50Z" level=error msg="error syncing 'kube-system/rke2-calico-crd': handler helm-contro>
  Aug 07 06:13:50 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:50Z" level=error msg="error syncing 'kube-system/rke2-calico': handler helm-controller>
  Aug 07 06:13:51 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:51Z" level=error msg="error syncing 'kube-system/rke2-coredns': handler helm-controlle>
  Aug 07 06:13:52 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:52Z" level=info msg="Adding node myrke2-custom-node0-0fd39a26 etcd status condition"
  Aug 07 06:13:53 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:53Z" level=error msg="error syncing 'kube-system/rke2-ingress-nginx': handler helm-con>
  Aug 07 06:13:54 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:54Z" level=error msg="error syncing 'kube-system/rke2-metrics-server': handler helm-co>
  Aug 07 06:13:54 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:54Z" level=error msg="error syncing 'kube-system/rke2-snapshot-controller-crd': handle>
  Aug 07 06:13:55 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:55Z" level=error msg="error syncing 'kube-system/rke2-snapshot-controller': handler he>
  Aug 07 06:13:56 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:13:56Z" level=error msg="error syncing 'kube-system/rke2-snapshot-validation-webhook': ha>
  Aug 07 06:15:47 myrke2-custom-node0 rke2[2575]: time="2024-08-07T06:15:47Z" level=info msg="Tunnel authorizer set Kubelet Port 10250"
  ```

* Check the rke2-agent service is not running
  ```
  root@myrke2-custom-node0:~# systemctl status rke2-agent.service
  ● rke2-agent.service - Rancher Kubernetes Engine v2 (agent)
       Loaded: loaded (/usr/local/lib/systemd/system/rke2-agent.service; disabled; vendor preset: enabled)
       Active: inactive (dead)
         Docs: https://github.com/rancher/rke2#readme
  ```

* Check lots of pods are still in Pending state
  ```
  root@myrke2-custom-node0:~# kubectl get pods -A
  NAMESPACE         NAME                                                    READY   STATUS      RESTARTS   AGE
  calico-system     calico-kube-controllers-b4cb7855c-l8fk5                 0/1     Pending     0          30m
  calico-system     calico-node-pcwzg                                       0/1     Running     0          30m
  calico-system     calico-typha-74767db7c4-2k4zf                           0/1     Pending     0          30m
  cattle-system     cattle-cluster-agent-c4c85d947-kxs26                    0/1     Pending     0          31m
  kube-system       etcd-myrke2-custom-node0                                1/1     Running     0          31m
  kube-system       harvester-cloud-provider-65c7cfc7cf-pqxq6               1/1     Running     0          31m
  kube-system       harvester-csi-driver-controllers-78dd8cd7b4-7z2l4       0/3     Pending     0          31m
  kube-system       harvester-csi-driver-controllers-78dd8cd7b4-spxzs       0/3     Pending     0          31m
  kube-system       harvester-csi-driver-controllers-78dd8cd7b4-zgxwx       0/3     Pending     0          31m
  kube-system       helm-install-harvester-cloud-provider-8b6fb             0/1     Completed   0          31m
  kube-system       helm-install-harvester-csi-driver-r774k                 0/1     Completed   0          31m
  kube-system       helm-install-rke2-calico-crd-6xfs2                      0/1     Completed   0          31m
  kube-system       helm-install-rke2-calico-qrrqd                          0/1     Completed   2          31m
  kube-system       helm-install-rke2-coredns-448fv                         0/1     Completed   0          31m
  kube-system       helm-install-rke2-ingress-nginx-m4lgc                   0/1     Pending     0          31m
  kube-system       helm-install-rke2-metrics-server-j7cfs                  0/1     Pending     0          31m
  kube-system       helm-install-rke2-snapshot-controller-5m56m             0/1     Pending     0          31m
  kube-system       helm-install-rke2-snapshot-controller-crd-46tcq         0/1     Pending     0          31m
  kube-system       helm-install-rke2-snapshot-validation-webhook-cfl6t     0/1     Pending     0          31m
  kube-system       kube-apiserver-myrke2-custom-node0                      1/1     Running     0          31m
  kube-system       kube-controller-manager-myrke2-custom-node0             1/1     Running     0          32m
  kube-system       kube-proxy-myrke2-custom-node0                          1/1     Running     0          32m
  kube-system       kube-scheduler-myrke2-custom-node0                      1/1     Running     0          32m
  kube-system       rke2-coredns-rke2-coredns-864fbd7785-4szkd              0/1     Pending     0          31m
  kube-system       rke2-coredns-rke2-coredns-autoscaler-6c87968579-dxx89   0/1     Pending     0          31m
  tigera-operator   tigera-operator-dfdd9d849-cvx4n                         1/1     Running     0          31m
  ```

**To Reproduce**
Refer to https://github.com/harvester/tests/issues/1312#issuecomment-2153298512
1. On Harvester, prepare KUBECONFIG with harvester VIP and generate cloud-config
  ```
   rancher@harvester-node-0:~> export KUBECONFIG=~/.kube/config/rke2.yaml 
   rancher@harvester-node-0:~> curl -sfL https://raw.githubusercontent.com/harvester/cloud-provider-harvester/master/deploy/generate_addon.sh | bash -s myrke2-custom default
   ...
   
   ########## cloud-init user data ############
   write_files:
   - encoding: b64
     content: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKbFZFTkRRVklyWjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVd0TlUwbDNTVUZaUkZaUlVVUkVRbXg1WVRKVmVVeFlUbXdLWTI1YWJHTnBNV3BaVlVGNFRucEZNMDlVWnpKTlZGRXlUVUkwV0VSVVNUQk5SRmw0VFVSQmVVMXFTWGxPYkc5WVJGUk5NRTFFV1hkUFJFRjVUV3BKZVFwT2JHOTNTa1JGYVUxRFFVZEJNVlZGUVhkM1dtTnRkR3hOYVRGNldsaEtNbHBZU1hSWk1rWkJUVlJqZUU1NmF6Uk9ha1V3VG1wQ1drMUNUVWRDZVhGSENsTk5ORGxCWjBWSFEwTnhSMU5OTkRsQmQwVklRVEJKUVVKRFMyMXlRMmRzTlZsVlQyZ3hhMmwyTmxKUmFtbGxTek5CYVRCVWNITmxhMFZvZDNGVVFVY0tjRFpaUTFwdE5ETmFObEZsZFU1RlJDODNjV2R1Tm5OMlVtTTBlREExVVU0eVRqVXdlVFZYY1dvNWExaHhVVWRxVVdwQ1FVMUJORWRCTVZWa1JIZEZRZ292ZDFGRlFYZEpRM0JFUVZCQ1owNVdTRkpOUWtGbU9FVkNWRUZFUVZGSUwwMUNNRWRCTVZWa1JHZFJWMEpDVkhBMlJUZHNZa2hMWjFKblJFVk9jWGxDQ205VFQwVkJVMU0xZGtSQlMwSm5aM0ZvYTJwUFVGRlJSRUZuVGtsQlJFSkdRV2xGUVhWQ1VYRTFOV05VUVdkQ1lqSmlkbk00ZVZaMU9FTlZaMWxuTUZVS0wwWkViVXRCZVZwRFlXVXpaWFpKUTBsSWJuTnpOVzlpZUhWMlJGUjVSSHBuT1ZwWFJXMVFTRVV5VlVKM1ExQmFXamh3YmxwaVZIcFlWRllyQ2kwdExTMHRSVTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzBLCiAgICBzZXJ2ZXI6IGh0dHBzOi8vMTkyLjE2OC4wLjEzMTo2NDQzCiAgbmFtZTogZGVmYXVsdApjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogZGVmYXVsdAogICAgbmFtZXNwYWNlOiBkZWZhdWx0CiAgICB1c2VyOiBteXJrZTItY3VzdG9tLWRlZmF1bHQtZGVmYXVsdAogIG5hbWU6IG15cmtlMi1jdXN0b20tZGVmYXVsdC1kZWZhdWx0CmN1cnJlbnQtY29udGV4dDogbXlya2UyLWN1c3RvbS1kZWZhdWx0LWRlZmF1bHQKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBteXJrZTItY3VzdG9tLWRlZmF1bHQtZGVmYXVsdAogIHVzZXI6CiAgICB0b2tlbjogZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklreGplRWwyU25wNVZXZDNPVFJPVVY4MlVtMUNWMGxUUlVReFJYQkJXbnAyVEZKVU1XWm5NV1ZsYTNNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbTE1Y210bE1pMWpkWE4wYjIwdGRHOXJaVzRpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pYlhseWEyVXlMV04xYzNSdmJTSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMblZwWkNJNklqRmlZV0UxWmpFMUxXUXdPR0l0TkRZMFpTMWhZalUwTFRFM1pHVmtORE5rTWpaaE9DSXNJbk4xWWlJNkluTjVjM1JsYlRwelpYSjJhV05sWVdOamIzVnVkRHBrWldaaGRXeDBPbTE1Y210bE1pMWpkWE4wYjIwaWZRLmJuUnotVnVaNVU2REVhMlJ3U181SHp3emtQX1l5QXBNV3BiaWFCRTNIaVNzVXlCVGNqNFE2UkRXSHd6THpOR00tNEtpeEtnRlBLRFZxRXJhLVVfZGZoaksxaldlNUVuQVRmdVh5UEU5Y2pTbDV2T29VclZTUnR1aVJuN0wxQ1ZET1ZTSndsbTIxQU1ranlLS3V6dnA4ZEFFdWFKNnZ6c3UwYzBKUm1MNk5SQUYwb1lWWlJfclFCN2piT2JEUlM1REMyQlBHY2QzZXBiOUxZeEJMTUxBWjZySEtUaTdiTTdaMEt3U215MlZBWDdEaDdzZ3YtMUdZVzZIWndfaGV5bkIzaWM2RmxYZ1dYeUpEd2Z3SjhhSGdHcTc5cFlseEVjNjd1NV94LVk0NlRscU9TRHYzQTNHNER4V1o3WlJLa3BIQktNRDc3MXB0ZXJRWEVNWlJvTTlwdwo=
   owner: root:root
   path: /etc/kubernetes/cloud-config
   permissions: '0644'
  ```

2. On Rancher, create a custom cluster and get the registration command
  ![image](https://github.com/user-attachments/assets/f3aa7a92-28f7-404e-a334-36d233e9c03f)

3. On Harvester, create a VM with cloud-config and execute Registration Command
  ![image](https://github.com/user-attachments/assets/f3d6929e-ffe7-4069-afea-f132cfb15952)
  
  ![image](https://github.com/user-attachments/assets/04320730-2dde-45a5-87f5-e5485ddc60d9)

**Expected behavior**

Can provision the custom RKE2 cluster running well on Rancher 

**Support bundle**

[supportbundle_881cf6d8-4091-46a7-ab2d-ea5e19ff5e79_2024-08-07T06-53-25Z.zip](https://github.com/user-attachments/files/16519478/supportbundle_881cf6d8-4091-46a7-ab2d-ea5e19ff5e79_2024-08-07T06-53-25Z.zip)

**Environment**
 - Harvester ISO version: `master-16b587a-head` (v1.4.0)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes remote kvm machines
 - Rancher version: v2.8.5
 - RKE2 version: v1.28.11, v1.27.15
