### ISSUE TITLE
[BUG] vgpu passthrough failure with NVIDIA RTX5000 ADA GPUs

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#6294]
**Describe the bug**

With certain GPUs like NVIDIA RTX5000 ADA, the vgpu profile names returned by parsing the vgpu profiles in /sys tree contain lower case characters

```
NAME                      ADDRESS        NODE NAME       ENABLED   UUID                                   VGPUTYPE                PARENTGPUDEVICE
harvesterdev7-00000b004   0000:0b:00.4   harvesterdev7   true      6f520761-e091-4a9d-b012-dab7ac476f4d   NVIDIA RTX5000-Ada-8Q   0000:0b:00.0
harvesterdev7-00000b005   0000:0b:00.5   harvesterdev7   true      475c556b-4efb-4714-974c-e080715f8a6d   NVIDIA RTX5000-Ada-8Q   0000:0b:00.0
harvesterdev7-00000b006   0000:0b:00.6   harvesterdev7   true      5bbbece9-d755-4e38-a34f-cae18bfeda0b   NVIDIA RTX5000-Ada-8Q   0000:0b:00.0
harvesterdev7-00000b007   0000:0b:00.7   harvesterdev7   true      77e13f64-dd22-42f2-a8c8-ab3f3c4a0e37   NVIDIA RTX5000-Ada-8Q   0000:0b:00.0
```

The device plugin setup by pcidevices controller converts device types to a upper case string, and same conversion is applied when setting up the permitted devices in kubevirt crd.

```
cpu: "64"
devices.kubevirt.io/kvm: 1k
devices.kubevirt.io/tun: 1k
devices.kubevirt.io/vhost-net: 1k
ephemeral-storage: 153707984Ki
hugepages-1Gi: "0"
hugepages-2Mi: "0"
memory: 115285220Ki
nvidia.com/NVIDIA_RTX5000-ADA-8Q: "8"
pods: "200"
```

```
      mediatedDevices:
      - externalResourceProvider: true
        mdevNameSelector: NVIDIA RTX5000-Ada-8Q
        resourceName: nvidia.com/NVIDIA_RTX5000-ADA-8Q
```

The Harvester UI generates the name however does not convert the `deviceName` to uppercase which causes the VM to not be scheduled as the device requested in VM spec is not a permitted device in kubevirt cr.

```
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-0
          gpus:
          - deviceName: nvidia.com/NVIDIA_RTX5000-Ada-8Q
            name: harvesterdev7-00000b004
```

As a result the VM never schedules, and needs manual intervention by user to edit and convert the deviceName to an uppercase string.

**To Reproduce**
1. Setup NVIDIA RTX5000 ADA GPU
2. Enable PCIDevices / nvidia driver toolkit
3. Enable sriovgpu device
4. Configure a vGPU profile 
5. Passthrough vGPU to a VM

VM will not schedule.

**Expected behavior**

VM should schedule and vGPU should be passed through fine.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by ibrokethecloud** [comment]
change are merged in master and can be easily tested by editing image tag to `master-head` when enabling the pcidevices controller addon

**Comment by innobead** [comment]
@Yu-Jack as you are learning GPU part, can you help with this testing? If having any questions, consult with @ibrokethecloud . 

cc @Vicente-Cheng

**Comment by Yu-Jack** [comment]
🟢 Passed with v1.6.0-rc5


## VM

1. Enable PCI passthrough addon
2. Enable nvidia-driver-toolkit addon
3. Enable SR-IOV GPU
4. Add 4 vGPU profiles (3 for guest cluster)
5. Create VM with one vGPU manually
```
ubuntu@test:~$ lspci | grep NVIDIA
0a:00.0 VGA compatible controller: NVIDIA Corporation Device 25b6 (rev a1)
```

## Guest Cluster

1. Install rancher-vcluster with this:

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: true
  repo: https://charts.loft.sh
  version: "v0.26.0"
  chart: vcluster
  valuesContent: |-
    controlPlane:
      distro:
        k3s:
          enabled: true
          image:
            repository: "rancher/k3s"
            tag: v1.33.2-k3s1
    sync:
      toHost:
        ingresses:
          enabled: true
    experimental:
      deploy:
        vcluster:
          manifests: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cattle-system
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager
              labels:
                certmanager.k8s.io/disable-validation: "true"
          helm:
            - chart:
                name: cert-manager
                repo: https://charts.jetstack.io
                version: v1.15.3
              values: |-
                installCRDs: true
              release:
                name: cert-manager
                namespace: cert-manager
            - chart:
                name: rancher
                repo: https://releases.rancher.com/server-charts/latest
                version: v2.12.0
              release:
                name: rancher
                namespace: cattle-system
              values: |-
                hostname: rancher.{ip}.sslip.io
                replicas: 1
                bootstrapPassword: "testtesttest"
                rancherImage: rancher/rancher
                rancherImageTag: "v2.12.0"
                ingress:
                  tls:
                    source: rancher
                global:
                  cattle:
                    psp:
                      enabled: "false"
```
2. Create a guest cluster and passthrough the vGPU profile

<img width="1180" height="1187" alt="Image" src="https://github.com/user-attachments/assets/ca240144-2996-47ed-9286-030756e4e902" />
