### ISSUE TITLE
[BUG] Some system settings are not allowed during the IPXE installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6329]
**Describe the bug**

We have an allow list in the installer: https://github.com/harvester/harvester-installer/blob/14913a95dc7cd28585814b52393285fb376a9b99/pkg/config/config.go#L41 to validate if provides a valid setting, but the list doesn't catch up the changes in the [harvester backend side](https://github.com/harvester/harvester/blob/0fa939f85ea57148160b9bd5fa48125906e97c5e/pkg/settings/settings.go#L22).

**To Reproduce**
1. Do an IPXE Install and add a missing system setting like `auto-rotate-rke2-certs`
2. The installation fails and the installer complains the setting is an unknown system setting.

![image](https://github.com/user-attachments/assets/a86b7e65-f76e-440b-a441-2a8787399709)

**Expected behavior**

The installation should proceed (for all supported settings).  The short-term solution is to add the missing setting back. But for the long-term solution, we need to have a way to sync the setting between the harvester backend code and the installer.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by Martin-Weiss** [comment]
Maybe also a problem for "branding"?

**Comment by votdev** [comment]
> Maybe also a problem for "branding"?

`branding`is not listed as a setting in [Harvester](https://github.com/harvester/harvester/blob/0fa939f85ea57148160b9bd5fa48125906e97c5e/pkg/settings/settings.go#L22) but mentioned in the [documentation](https://docs.harvesterhci.io/v1.3/advanced/index/#branding). So it looks to me this is a bug in Harvester as well. Right?

See https://github.com/harvester/harvester/issues/6331

**Comment by brandboat** [comment]
Test OK on [v1.4.0-rc1](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc1), close as fixed.

## Environment
* [v1.4.0-rc1](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc1)
  * Profile: 1 node QEMU/KVM (8C/16G/250G)
  * ui-source: `Auto`

## Test Steps
1. Prepare a http server and provide the following harvester config
  ```yaml
  schemeversion: 1
  systemsettings:
    ui-plugin-index: 'https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js'
    support-bundle-expiration: '60'
    support-bundle-node-collection-timeout: '60'
    csi-driver-config: '{"driver.longhorn.io": {"volumeSnapshotClassName": "longhorn-snapshot","backupVolumeSnapshotClassName": "longhorn"}}'
    storage-network: '{"vlan": 100, "clusterNetwork": "storage", "range": "192.168.0.0/24"}'
    default-vm-termination-grace-period-seconds: '180'
    auto-rotate-rke2-certs: '{"enable":true,"expiringInHours":48}'
    kubeconfig-default-token-ttl-minutes: '60'
    harvester-csi-ccm-versions: '{"harvester-cloud-provider":">=0.0.1 <0.3.0","harvester-csi-provider":">=0.0.1 <0.3.0"}'
  ```
2. Install harvester single node, and fill in the remote harvester config url
3. After installation finished, check setting CR and make sure all setting are setup correctly.

```text
test:~ # kubectl get settings
NAME                                          VALUE
additional-ca
additional-guest-memory-overhead-ratio
api-ui-version                                1.1.9
auto-disk-provision-paths
auto-rotate-rke2-certs                        {"enable":true,"expiringInHours":48}
backup-target
cluster-registration-url
containerd-registry
csi-driver-config                             {"driver.longhorn.io": {"volumeSnapshotClassName": "longhorn-snapshot","backupVolumeSnapshotClassName": "longhorn"}}
default-storage-class
default-vm-termination-grace-period-seconds   180
harvester-csi-ccm-versions                    {"harvester-cloud-provider":">=0.0.1 <0.3.0","harvester-csi-provider":">=0.0.1 <0.3.0"}
http-proxy
kubeconfig-default-token-ttl-minutes          60
log-level
longhorn-v2-data-engine-enabled
ntp-servers                                   {"ntpServers":["0.suse.pool.ntp.org"]}
overcommit-config
release-download-url
server-version                                v1.4.0-rc1
ssl-certificates
ssl-parameters
storage-network                               {"vlan": 100, "clusterNetwork": "storage", "range": "192.168.0.0/24"}
support-bundle-expiration                     60
support-bundle-image
support-bundle-namespaces
support-bundle-node-collection-timeout        60
support-bundle-timeout
ui-index
ui-path                                       /usr/share/harvester/harvester
ui-plugin-index                               https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js
ui-source
upgradable-versions
upgrade-checker-enabled
upgrade-checker-url
upgrade-config
vip-pools
vm-force-reset-policy
volume-snapshot-class
```
