### ISSUE TITLE
[QUESTION] Harvester single node stuck on `Setting up node/Harvester` after connecting to new router.

### ISSUE THREAD

**Issue by TeRua** [harvester/harvester#6377]
I recently moved my home and subscribed new ISP.
After I reconnected my Harvester server to the router, Web UI is no longer accessible.

I've been searching around and saw that Management IP cannot be changed,
So I configured Static IP for the NIC with IP addresses I remember (192.168.1.81, 192.168.1.176)
But both didn't work too.

Next, I tried to check logs and found that etcd is no longer creating log files.
in `journalctl -xeu rke2-server` command result, it seems like etcd and kube-api are not started properly but I am not sure why.
I cannot use `kubectl` commands as kube-api is not running.

[rke2-log-harvester.log](https://github.com/user-attachments/files/16657910/rke2-log-harvester.log)

Can anybody help me to recover the node from this?

**Comment by SnakebiteEF2000** [comment]
did the subnet change?

**Comment by TeRua** [comment]
> did the subnet change?

I used same IP range on new router, (192.168.1.0/24)

**Comment by w13915984028** [comment]
@TeRua From the attached log, the RKE2 server looked to use ip `192.168.1.176`.

```
Aug 19 08:29:22 ms-harvester rke2[9072]: time="2024-08-19T08:29:22Z" level=info msg="To join server node to cluster: rke2 server -s https://192.168.1.176:9345 -t ${SERVER_NODE_TOKEN}"
```

Please check the `/oem/harvester.config` file, which has the information about how to get the IP for management interface (DHCP/staic).

```
 cat /oem/harvester.config 
schemeversion: 1
...
install:
    automatic: false
    skipchecks: true
    mode: create
    managementinterface:
        interfaces:
            - name: ens3
              hwaddr: 52:54:00:03:3a:e4
        method: dhcp  // the mode
        ip: ""
        subnetmask: ""
        gateway: ""
        defaultroute: true
        bondoptions:
            miimon: "100"
            mode: active-backup
        mtu: 0
        vlanid: 0
    vip: 192.168.122.144 // the VIP
    viphwaddr: ""
```

>So I configured Static IP for the NIC with IP addresses I remember (192.168.1.81, 192.168.1.176)

How did you do?
