### ISSUE TITLE
[BUG] Missing Add-on config page of load balancer in RKE2 guest cluster with external cloud provider installed  

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#6393]
**Describe the bug**

On the RKE2 guest cluster provisioned in Rancher `v2.9.1-rc1` and `v2.8.7-rc4`. (with cloud provider 0.2.6) 
When create load balancer service, the `Add-on config page` disappear and not exists.

![image](https://github.com/user-attachments/assets/5fb9fc70-eb0b-4280-89ee-c5a01d21b22e)

* User can't create the `Pool` type load balancer service

* This issue only exists using the `External` cloud provider to provision RKE2 cluster
* Use the default Harvester cloud provider to provision RKE2 cluster is fine 

**To Reproduce**
Steps to reproduce the behavior: (click to expand detailed steps)
<details><summary>Manually deploy cloud provider 0.2.6 on RKE2 cluster on Rancher </summary>

* Reference: https://docs.harvesterhci.io/v1.4/rancher/cloud-provider#deploying-to-the-k3s-cluster-with-harvester-node-driver-experimental

1. SSH to Harvester node
2. Copy the kubeconfig  
  ```
  $ sudo cp /etc/rancher/rke2/rke2.yaml ~/.kube/config/rke2.yaml
  ```
3. Edit the kubeconfig, set the URL to Harvester VIP 
  ```
  $ sudo vim ~/.kube/config/rke2.yaml
  ```
4. Export the kubeconfig 
  ```
  export KUBECONFIG=~/.kube/config/rke2.yaml
  ```
5. Add execute permission to the kubeconfig file 
  ```
  sudo chmod 444 ~/.kube/config/rke2.yaml
  ```
6. Use the cloud provider master generate addon script to generate the config file ( Use RKE2 cluster name and namespace for the last arguments)
  ```
  $ curl -sfL https://raw.githubusercontent.com/harvester/cloud-provider-harvester/master/deploy/generate_addon.sh | bash -s rke2-v12811-external default
  ```
7. Copy the `cloud-init user data` content starting with the `write _files` 
  ![image](https://github.com/user-attachments/assets/35d9d720-d75c-467b-b6c2-ec1de8096867)

8. Create the RKE2 cluster on Rancher 
9. Add the copied `cloud-init user data` content  to the `Show Advanced -> Machine Pools -> User Data`
  ![image](https://github.com/user-attachments/assets/a455b43c-eb8b-482c-ac00-9f0a3bc85a22)

10. Set the Cloud Provider to `External`
![image](https://github.com/user-attachments/assets/5103e9db-fede-4de4-a3b1-f3e6c0550eaf)

11. Add the cloud provider Helm chart information to the Add-on Config -> Additional Manifest
  - For Rancher v2.8.x
    ```
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: harvester-cloud-provider
      namespace: kube-system
    spec:
      targetNamespace: kube-system
      bootstrap: true
      repo: https://raw.githubusercontent.com/rancher/charts/dev-v2.8
      chart: harvester-cloud-provider
      version: 103.0.3+up0.2.6
      helmVersion: v3
    ```
  
   
  - For Rancher v2.9.x
    ```
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: harvester-cloud-provider
      namespace: kube-system
    spec:
      targetNamespace: kube-system
      bootstrap: true
      repo: https://raw.githubusercontent.com/rancher/charts/dev-v2.9
      chart: harvester-cloud-provider
      version: 104.0.2+up0.2.6
      helmVersion: v3
    ```

12. Save to create the RKE2 cluster 
13. After RKE2 cluster up to running 
14. Open the Installed Apps page to check the cloud provider already installed with the desired version

</details>

**Expected behavior**

Should display the Add-on config page of load balancer in RKE2 guest cluster with external cloud provider installed

**Support bundle**

[supportbundle_83b5c214-6fa3-4487-8351-953c8d12b469_2024-08-21T14-23-02Z.zip](https://github.com/user-attachments/files/16693058/supportbundle_83b5c214-6fa3-4487-8351-953c8d12b469_2024-08-21T14-23-02Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on kvm machine
 - Rancher version: `v2.8.7-rc4`, `v2.9.1-rc1`
 - RKE2 version: `v1.30.2`, `v1.28.11`

**Comment by w13915984028** [comment]
@torchiaf @a110605 Could you help check why Rancher Manager does not load the `addon` config page, thanks.

**Comment by torchiaf** [comment]
@TachunLin provided me a test environment (Thanks David).
The condition to show the Harvester configs tab is false:

It should be
```
cloudProvider === 'harvester'
```

but we have

```
cloudProvider === 'external'
```

where cloudProvider source is: `spec.rkeConfig.machineSelectorConfig[0].config['cloud-provider-name']`

We use this condition everywhere in the UI to identify Harvester clusters. Do we have another source field to use in this case ?

Probably, we could use the `machinePools.provider` field, it needs to be confirmed.
WDYT ? @TachunLin @w13915984028

**Comment by TachunLin** [comment]
Will the proposed changes to use `machinePools.provider` filed affect any Rancher integration usage. (e.g create load balancer on regular RKE2 cluster when we set the cloud provider to Harvester or none during the creation)

**Comment by innobead** [comment]
@harvester/ui is this still a valid case for UI extension?

**Comment by innobead** [comment]
>This issue only exists using the External cloud provider to provision RKE2 cluster
> Use the default Harvester cloud provider to provision RKE2 cluster is fine

Moving to a later version instead.

**Comment by a110605** [comment]
This issue is not related to harvester-ui-extension. It should be fixed in rancher/dashboard.

Discussed with @TachunLin , he will try to add annotation `cloudprovider.harvesterhci.io/ipam: <dhcp|pool>` to see this issue still reproduable.
Refer https://docs.harvesterhci.io/v1.5/rancher/cloud-provider/#manually-deploying-to-the-rke2-cluster

**Comment by Vicente-Cheng** [comment]
Hi @TachunLin, 
Could you help to validate it again? (with above suggestion)

**Comment by TachunLin** [comment]
Hi @Vicente-Cheng , @a110605

Just validated the suggestion works on latest v1.5-head with Rancher `v2.11.3`

* With RKE2 cluster created with `external` cloud provider 0.2.4

* We can add the annotation `cloudprovider.harvesterhci.io/ipam: dhcp` to the load balancer service.

  <img width="1600" height="783" alt="Image" src="https://github.com/user-attachments/assets/c32fd1c3-099c-40eb-86b2-42e24241eeff" />

* Then we can create the dhcp type load balancer and route to it.

  <img width="1598" height="801" alt="Image" src="https://github.com/user-attachments/assets/0c73a143-65f3-4de0-97b3-1f30f2cb26eb" />

  https://github.com/user-attachments/assets/f9770d72-ca5e-4abe-a700-cd6702918bb1


### Conclusion
Thus we can use this as a workaround for RKE2 cluster with external cloud provider installed. 


### Test Information
* Test Environment: Three nodes kvm machines
* Harvester version: v1.5-5211232c-head (25/09/02)
* Rancher version: v2.11.3
* cloud provider: 0.2.4
* csi-driver: 0.1.23 (manually installed from apps chart)

### Reproduce steps

* Refer to: https://docs.harvesterhci.io/v1.6/rancher/cloud-provider/#manually-deploying-to-the-rke2-cluster
* Replace with the following additional manifest

  ```
  apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    name: harvester-cloud-provider
    namespace: kube-system
  spec:
    targetNamespace: kube-system
    bootstrap: true
    repo: https://charts.harvesterhci.io/
    chart: harvester-cloud-provider
    version: 0.2.4
    helmVersion: v3
  ```
