### ISSUE TITLE
[FEATURE] cloud-init configuration enhancement

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#640]
**Describe the solution you'd like**
Add cloud-init configuration enhancement with:
1. [x] add a select option to install the guest agent plugin
2. [x] do not create a cloud-init disk when it has an empty value
3. [x] add cloud-init template in VM

**Comment by futuretea** [comment]
install qemu-guest-agent by cloudinit:
```yaml
package_update: true
packages:
- qemu-guest-agent
runcmd:
- [systemctl, enable, --now, qemu-guest-agent]
```
