### ISSUE TITLE
[BUG] Interactive ISO Install NTP-Servers Don't Remove Duplicates W/ Config URL

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6417]
**Describe the bug**
If setting up Harvester via Interactive ISO Installation, when the panel asks for NTP servers, a user inputs one.  When prompeted for a configuration URL that holds the YAML like:
```
scheme_version: 1
os:
  ntp_servers:
    - 192.168.120.29
  dns_nameservers:
    - 192.168.120.121
install:
  wipeDisks: true
system_settings:
  backup-target: '{"type":"s3","endpoint":"http://192.168.120.20:9000","accessKeyId":"myuserserviceaccount","secretAccessKey":"myuserserviceaccountsecret","bucketName":"harvester-vm-backup-bucket","bucketRegion":"sample-test-1","cert":"","virtualHostedStyle":false}'
  ui-source: auto
```
If the user entered `192.168.120.29` during the Interactive ISO Install Panel prompt.
Harvester will not recognize that the NTP Servers are duplicates.
So when install finishes there will be two of the same in the Harvester -> Settings.

**To Reproduce**
1. Create a configuration somewhere hosted
1. Install Harvester, input the same NTP Server that you use in the Configuration
1. Let install finish, check Harvester->Settings

**Expected behavior**
Duplicates to be ignored / some sort of merging logic when bringing in a Config URL during Interactive ISO Install time.

**Workaround**
- manually clean up duplicates after install

**Environment**
 - Harvester ISO version:  v1.3.1 , v1.3.2-rc2
 - Underlying Infrastructure: bare-metal HP DL160s

**Additional context**
![Screenshot from 2024-08-23 16-04-16](https://github.com/user-attachments/assets/691d9cb2-d391-4290-aef5-ad967be7fc63)
