### ISSUE TITLE
[BUG] In Rancher v2.9.0/v2.9.1 w/ Harvester v1.3.2-rc2 "Support" Link Doesn't Link To Support

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6442]
**Describe the bug**
Clicking "Support" through Rancher v2.9.0/v2.9.1 w/ Harvester v1.3.2-rc2 doesn't take Rancher user to Harvester Support, it redirects them back to their Local Cluster Homepage for Rancher

**To Reproduce**
1. Import Harvester into Rancher
2. In Rancher build a custom-role template, with some content:
```
apiVersion: management.cattle.io/v3
displayName: do-some-things
kind: GlobalRole
##############
rules:
  - apiGroups:
      - harvesterhci.io.management
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - VirtualMachineTemplate
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - VirtualMachienInstance
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - VirtualMachineImage
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - Networks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - ClusterNetworks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - harvesterhci.io
    resources:
      - NodeNetworks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
```
3. In Rancher build another user called "test" password "testtesttest" - w/ Standard User & User-Base global permissions, additionally add the custom-role to that User "test"
4. As Admin in Rancher, create create a Harvester Cluster, adding "test" (Local) as a "Cluster Member"
5. In Harvester, enter in the Cluster Registration URL
6. In Rancher two windows ( one login as Admin ) - second (private window), login as "test" 
7. Navigate to Virtualization Management (as both users) -> Click the Cluster -> As Harvester Loads, click "support", you are re-directed

**Expected behavior**
Support link not to re-direct users, as some custom RBAC users in Rancher have limited Harvester permissions and "usually" get the Kubeconfig from "Support" link.  But also may generate support bundles, and this limits that ability to do so.  Plus additionally may want embedded Harvester Rancher or Longhorn link 

**Workaround for Kubeconfig**
1. Users, in Virtualization Management -> Harvester Clusters, clicking the three elipsis icon on the far right, allows user like "test" to download the Kubeconfig

**Workaround Unknown**
- Unknown workaround for a Rancher RBAC user (or admin) to generate a Support Bundle...?

**Environment**
 - Harvester ISO version: v1.3.2-rc2
 - Rancher v2.9.0, v2.9.1 
 - Underlying Infrastructure: qemu-kvm

**Additional context**

https://github.com/user-attachments/assets/371ee823-a60f-43df-9861-732fa5d17661
