### ISSUE TITLE
[BUG] VM Import for OpenStack (2023.1/stable [devstack]) & vSphere 7.0.3  creates additional NIC with same MAC for Multi-Subnet Network

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6451]
**Describe the bug**
When importing an OpensStack (Devstack, 2023.1/stable) VM that has 3 Networks attached:

| NetworkName   |      Subnets Associated      |  MAC |
|----------|:-------------:|------:|
| shared |  192.168233.0/24 |  fa:16:3e:25:e5:b5  |
| public | 172.24.4.0/24 & 2001:db8:/64 |     fa:16:3e:54:ab:3d  |
| newpub | 192.168.104.0/24 |     fa:16:3e:f7:7e:fc  |

"public" that has two subnets associated, ipv4 & ipv6 on OpenStack, ends up creating an additional NIC.
Whereas, on the VM on OpenStack, there is only one link/nic shown with that MAC address instead of two.

When importing a vSphere v7.0.3 instance with two NICs of adapter type VMXNET 3, DirectPath I/O
Cross reference Screenshot:
- https://github.com/harvester/harvester/issues/6451#issuecomment-2322211026

**To Reproduce**
Steps to reproduce the behavior OpenStack:
1. Have a Devstack 2023.1/stabel instance for testing
2. Build a VM using 2 nics, one multi subnet associated network & one regular single associated subnet network
3. Enable vm-import addon
4. Create the OpenStackSource & OpenStackSource secret & VM Import
5. You'll see that the vm import is successful, but there are now two nics instead of the "one" that was prevelent in OpenStack
Steps to reproduce the behavior vSphere:
1. Have vSphere v7.0.3 available
2. Build out the vSphere credentials 
3. Have a vSphere v7.0.3 VM with two NICs, VMXNET 3 
4. Import that VM into Harvester
5. Import is successfull, but you'll see there are now "four" nics present when there were only two on vSphere side

**Expected behavior**
Multi-Network Associated Subnet Networks for OpenStack VMs to not cause the VM Import into Harvester to add an additional NIC with the same network mac address

**Environment**
 - Harvester ISO version:  v1.3.2-rc2
 - Underlying Infrastructure: bare-metal , hp-dl160s & dell poweredge r720

**Additional context**
![Screenshot from 2024-08-29 16-24-15](https://github.com/user-attachments/assets/2a3215e0-7826-452f-ab6b-dbe99acbcbce)
![Screenshot from 2024-08-29 15-41-53](https://github.com/user-attachments/assets/509b6172-f845-4c32-bf5c-656fe340fa92)

**Workaround**
- User can just manually delete the extra-nic, post VM import.

**Comment by irishgordo** [comment]
#### To Note, this is also present with vSphere VMs

![Screenshot from 2024-08-30 12-29-23](https://github.com/user-attachments/assets/a90a5c17-4fc5-45e0-9ef0-76f96e341b3d)
![Screenshot from 2024-08-30 12-26-37](https://github.com/user-attachments/assets/cc94b079-31bc-44aa-a5cd-e02201e4606a)

**Comment by ibrokethecloud** [comment]
there are different causes for this behaviour.

In case of openstack, if the network is dual stacked, then the api reports the network interface details twice, once with ipv4 and ipv6 addressing which causes the additional network mapping to appear. This is now fixed with a dedup of nics based on mac addresses

in case of vmware, this behaviour only happens when the same sourceNetwork appears in the import spec twice, without that multi-homed VM's get imported without any nic duplication. For example the following spec will trigger the duplication of nics.  The easy fix is to dedup the source networks during the preflight check to allow the user to fix their network definitions and allow user to correct the spec.

```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: ubuntu-import
  namespace: default
spec:
  virtualMachineName: "gm-ubuntu-test"
  networkMapping:
  - sourceNetwork: "VM Network"
    destinationNetwork: "default/workload"
  - sourceNetwork: "VM Network"
    destinationNetwork: "default/workload"
  sourceCluster:
    name: wrangler
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

**Comment by irishgordo** [comment]
On v1.4.0-rc3 with the Deployment of:
```yaml
Name:               vm-import-controller-harvester-vm-import-controller                                                                                                                                             
Namespace:          harvester-system                                                                                                                                                                                
CreationTimestamp:  Thu, 24 Oct 2024 14:02:27 -0700                                                                                                                                                                 
Labels:             app.kubernetes.io/instance=vm-import-controller                                                                                                                                                 
                    app.kubernetes.io/managed-by=Helm                                                                                                                                                               
                    app.kubernetes.io/name=harvester-vm-import-controller                                                                                                                                           
                    app.kubernetes.io/version=v0.4.0                                                                                                                                                                
                    helm.sh/chart=harvester-vm-import-controller-0.4.1                                                                                                                                              
Annotations:        deployment.kubernetes.io/revision: 2                                                                                                                                                            
                    meta.helm.sh/release-name: vm-import-controller                                                                                                                                                 
                    meta.helm.sh/release-namespace: harvester-system                                                                                                                                                
Selector:           app.kubernetes.io/instance=vm-import-controller,app.kubernetes.io/name=harvester-vm-import-controller                                                                                           
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable                                                                                                                                   
StrategyType:       Recreate                                                                                                                                                                                        
MinReadySeconds:    0                                                                                                                                                                                               
Pod Template:                                                                                                                                                                                                       
  Labels:           app.kubernetes.io/instance=vm-import-controller                                                                                                                                                 
                    app.kubernetes.io/name=harvester-vm-import-controller                                                                                                                                           
  Service Account:  vm-import-controller-harvester-vm-import-controller                                                                                                                                             
  Containers:                                                                                                                                                                                                       
   harvester-vm-import-controller:                                                                                                                                                                                  
    Image:      rancher/harvester-vm-import-controller:v0.4.1                                                                                                                                                       
    Port:       <none>                                                                                                                                                                                              
    Host Port:  <none>                                                                                                                                                                                              
    Limits:                                                                                                                                                                                                         
      cpu:     4                                                                                                                                                                                                    
      memory:  8Gi                                                                                                                                                                                                  
    Requests:                                                                                                                                                                                                       
      cpu:        2                                                                                                                                                                                                 
      memory:     4Gi                                                                                                                                                                                               
    Environment:  <none>                                                                                                                                                                                            
    Mounts:                                                                                                                                                                                                         
      /tmp from storage (rw)                                                                                                                                                                                        
  Volumes:                                                                                                                                                                                                          
   storage:                                                                                                                                                                                                         
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)                                                                                                                
    ClaimName:  vm-import-controller-harvester-vm-import-controller                                                                                                                                                 
    ReadOnly:   false                                                                                                                                                                                               
Conditions:                                                                                                                                                                                                         
  Type           Status  Reason                                                                                                                                                                                     
  ----           ------  ------                                                                                                                                                                                     
  Available      True    MinimumReplicasAvailable                                                                                                                                                                   
  Progressing    True    NewReplicaSetAvailable                                                                                                                                                                     
OldReplicaSets:  vm-import-controller-harvester-vm-import-controller-cbfb59b4b (0/0 replicas created)                                                                                                               
NewReplicaSet:   vm-import-controller-harvester-vm-import-controller-7fc5bdfc65 (1/1 replicas created)                                                                                                              
Events:                                                                                                                                                                                                             
  Type    Reason             Age   From                   Message                                                                                                                                                   
  ----    ------             ----  ----                   -------                                                                                                                                                   
  Normal  ScalingReplicaSet  50m   deployment-controller  Scaled down replica set vm-import-controller-harvester-vm-import-controller-cbfb59b4b to 0 from 1                                                         
  Normal  ScalingReplicaSet  50m   deployment-controller  Scaled up replica set vm-import-controller-harvester-vm-import-controller-7fc5bdfc65 to 1     
```

This looks great :+1:  and is performing as expected on both OpenStack/DevStack(stable/2023.1) & vSphere.

W/ yaml of:
```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-ubuntu
  namespace: default
spec: 
  virtualMachineName: "mr-ubuntu"
  networkMapping:
  - sourceNetwork: "VM Network"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: mike-vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: description
  namespace: default
spec: 
  virtualMachineName: "description"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan1"
  - sourceNetwork: "private"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: mike-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---

```

![Screenshot from 2024-10-24 16-48-26](https://github.com/user-attachments/assets/a0a02ec0-59fe-4693-b8aa-026588d2b6c2)
![Screenshot from 2024-10-24 16-21-52](https://github.com/user-attachments/assets/95033787-cf57-45b1-bc47-5b4e7edeaced)
![Screenshot from 2024-10-24 16-17-01](https://github.com/user-attachments/assets/a85ab636-22a5-47a4-9b79-2ef169dd6bf3)
![Screenshot from 2024-10-24 17-29-12](https://github.com/user-attachments/assets/3f8c74ff-0c39-46bd-ab97-b5959020e831)


Thanks for this fix @ibrokethecloud :smile: 
I'll go ahead and close this out
