### ISSUE TITLE
[BUG] `virtualMachineName` must be the `ID` of the OpenStack server when importing.

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#6500]
**Describe the bug**
To import a OpenStack server as VM, the field `virtualMachineName` must be the `ID`, e.g. `0319fde2-fb59-4926-85ad-ff7fdfaa3384` of the server, otherwise the import stucks with the error
```
time="2024-09-04T13:28:09Z" level=error msg="error syncing 'default/long-name': handler virtualmachine-import-job-change: error in poweroff call: noServerFound, requeuing"
```
Additionally the `VirtualMachine` resource is populated with the incorrect name (see [here](https://github.com/harvester/vm-import-controller/blob/bda1e6284a0ad24c4a69f023a6958f24070ec825/pkg/source/openstack/client.go#L356)), the specified `spec.virtualMachineName` of the `VirtualMachineImport` is used, which is in case of OpenStack NOT the name but the `ID`.

The correct code should look like
```
	newVM := &kubevirt.VirtualMachine{
		ObjectMeta: metav1.ObjectMeta{
			Name:      vmObj.Name,
			Namespace: vm.Namespace,
		},
	}
```
This applies also to this [code](https://github.com/harvester/vm-import-controller/blob/bda1e6284a0ad24c4a69f023a6958f24070ec825/pkg/source/openstack/client.go#L366).

![grafik](https://github.com/user-attachments/assets/bd3f07a8-082a-4ee5-8d81-64e726f20834)

![grafik](https://github.com/user-attachments/assets/d0613cb6-4c45-4b1e-b62c-d9cfbc4210b2)

**To Reproduce**
Import a OpenStack server.

**Expected behavior**
From the example, i suspect the name `cirros-tiny` is used.

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
Hi @votdev  - I'd like to close this out if possible and perhaps open this as an enhancement.

The gist is that a user may need to build "multiple" OpenStack Credentials to target different "project_names".

Given:
```yaml
apiVersion: v1
kind: Secret
metadata: 
  name: devstack-credentials
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "admin"
  "domain_name": "default"
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: devstack
  namespace: default
spec:
  endpoint: "http://a.b.c.182/identity"  
  region: "RegionOne"
  credentials:
    name: devstack-credentials
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: sml-cirros
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: devstack
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

"cirros-tiny" will fail, because it is not in the "admin" project_name.
It is in the "demo" project_name, in this instance.

So this requires users to build something like this:
```yaml
---
apiVersion: v1
kind: Secret
metadata: 
  name: devstack-credentials-admin
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "admin"
  "domain_name": "default"
---
apiVersion: v1
kind: Secret
metadata: 
  name: devstack-credentials-demo
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "demo"
  "domain_name": "default"
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: devstack-project-admin
  namespace: default
spec:
  endpoint: "http://a.b.c.182/identity"  
  region: "RegionOne"
  credentials:
    name: devstack-credentials-admin
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: devstack-project-demo
  namespace: default
spec:
  endpoint: "http://a.b.c.182/identity"  
  region: "RegionOne"
  credentials:
    name: devstack-credentials-demo
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: sml-cirros
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: devstack-project-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

Then `devstack-project-demo` would work to bring `cirros-tiny` accross the wire as a VM by "name" and not UUID.

So, in some ways, perhaps this could just be an Enhancement... to allow something like:
```yaml
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: sml-cirros
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  projectNamespace: "demo"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: devstack
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```
The VM Object to just have a project_name, so that the user wouldn't need to build "N"/# of credentials but could just build one, so, their corresponding secret would just be something like:
```yaml
apiVersion: v1
kind: Secret
metadata: 
  name: devstack-general-credentials
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "domain_name": "default"
```
