### ISSUE TITLE
[BUG] OpenStack VM Import Can't Handle Source VM if Source VM has Camel Case

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6505]
**Describe the bug**
```
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=error msg="vm migration target openSUSE-uefi-secure in VM mr-opensuse-uefi-secre in namespace default is not RFC 1123 compliant"                          
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=info msg="vm mr-opensuse-uefi-secre in namespace default has an invalid spec"                                                                             
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=info msg="reconcilling openstack soure :default/mike-demo"                                                                                                
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=info msg="found 7 servers"                                                                                                                                
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=info msg="reconcilling openstack soure :default/mike-admin"                                                                                               
harvester-vm-import-controller-84b88445cd-9z84n time="2024-09-05T01:42:49Z" level=info msg="reconcilling openstack soure :default/mike-demo"                                                                                                                                                                                                                                                                                                                                  
```

In:
```yaml
---
apiVersion: v1
kind: Secret
metadata: 
  name: mike-test-admin
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "admin"
  "domain_name": "default"
---
apiVersion: v1
kind: Secret
metadata: 
  name: mike-test-demo
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "demo"
  "domain_name": "default"
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: mike-admin
  namespace: default
spec:
  endpoint: "http://a.b.c.182/identity"  
  region: "RegionOne"
  credentials:
    name: mike-test-admin
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: mike-demo
  namespace: default
spec:
  endpoint: "http://a.b.c.182/identity"  
  region: "RegionOne"
  credentials:
    name: mike-test-demo
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-opensuse-uefi-secre
  namespace: default
spec: 
  virtualMachineName: "openSUSE-uefi-secure"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan1"
  sourceCluster: 
    name: mike-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

The VM Import won't work by "source machine's virttual vm name" -> so in OpenStack, if the source VM name is camelCased -> we can only import by UUID and not by name.

**To Reproduce**
1. openstack, just have a vm with a camelcase name
1. try to import by name
1. it won't work, in the logs `kubectl logs svc/vm-import-controller` it will complain that the source vm isn't meeting RFC naming conventions, but the source VM may have been out of the control of the Harvester user/admin/org, so they were just using an already present name

**Workaround**
- In openstack change the name of the VM to not be camelcase 
- Then import will work by name

**Expected behavior**
Maybe some sanitization on RFC compliance with names from VMs from OpenStack I'm not sure...

**Environment**
 - Harvester ISO version: v1.3.2-rc2 
 - Underlying Infrastructure: bare-metal

cc: @TachunLin

**Comment by votdev** [comment]
I think the problem is [this](https://github.com/harvester/vm-import-controller/blob/bda1e6284a0ad24c4a69f023a6958f24070ec825/pkg/controllers/migration/virtualmachine.go#L146) code. IMO the [IsDNS1123Label](https://github.com/kubernetes/apimachinery/blob/2465dc5239ab8827a637148a78b380c278b4a5f4/pkg/util/validation/validation.go#L187) is used to validate a label key, but what should be tested here is whether it is a valid [label value](https://github.com/kubernetes/apimachinery/blob/2465dc5239ab8827a637148a78b380c278b4a5f4/pkg/util/validation/validation.go#L166).

**Comment by votdev** [comment]
It's not possible to have object names with upper case characters, otherwise this will happen:
```
time="2024-09-05T11:29:21Z" level=error msg="error syncing 'default/foo-test': handler virtualmachine-import-job-change: error creating kubevirt VM in createVirtualMachine :VirtualMachine.kubevirt.io \"foo-Test\" is invalid: metadata.name: Invalid value: \"foo-Test\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing"
```
See https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by votdev** [comment]
As already mentioned above, we could adapt the name during import so that Kubernetes does not interfere with it. To do this, however, the entire code of the vm-import-controller must be extended because `spec.virtualMachineName` is accessed in many places. We cannot simply change/sanitize the value of this field as this is also used when importing the VMs and if we change the name in any way, the source VM will no longer be found in the client. Therefore, the structure must be extended by a field that contains the corrected/sanitized `virtualMachineName`.

**Comment by votdev** [comment]
We could add a new field to the [VirtualMachineImportStatus](https://github.com/harvester/vm-import-controller/blob/bda1e6284a0ad24c4a69f023a6958f24070ec825/pkg/apis/migration.harvesterhci.io/v1beta1/virtualmachines.go#L32), e.g.
```
type VirtualMachineImportStatus struct {
	// The sanitized name of the target virtual machine object.
    VirtualMachineName string             `json:"virtualMachineName,omitempty"`
	Status             ImportStatus       `json:"importStatus,omitempty"`
	DiskImportStatus   []DiskInfo         `json:"diskImportStatus,omitempty"`
	ImportConditions   []common.Condition `json:"importConditions,omitempty"`
	NewVirtualMachine  string             `json:"newVirtualMachine,omitempty"`
}
```
This would also be helpful for the issue https://github.com/harvester/harvester/issues/6500 where the importer has to convert the ID of the source VM into the origin name at some point.

**Comment by irishgordo** [comment]
@votdev for:

```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable-new-camel
  namespace: default
spec: 
  virtualMachineName: "newTestJammy"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vmnet"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1

```

I do see:
```go
harvester-vm-import-controller-fbb669547-6qnn5 time="2025-02-08T01:35:22Z" level=info msg="Running preflight checks ..." name=mr-jammy-2023-stable-new
-camel namespace=default spec.virtualMachineName=newTestJammy                                                                                         
harvester-vm-import-controller-fbb669547-6qnn5 time="2025-02-08T01:35:22Z" level=error msg="vm migration target newTestJammy in VM mr-jammy-2023-stabl
e-new-camel in namespace default is not RFC 1123 compliant"                                                                                           
harvester-vm-import-controller-fbb669547-6qnn5 time="2025-02-08T01:35:22Z" level=error msg="The VM import spec is invalid" name=mr-jammy-2023-stable-n
ew-camel namespace=default spec.virtualMachineName=newTestJammy              
```

And then the user once seeing the `virtualMachineInvalid` status on VirtualMachineImports, could pivot to just utilize the `ID` instead


```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable-new-camel
  namespace: default
spec: 
  virtualMachineName: "6ff4b75c-b166-4971-9f84-ea088b7c1e9b"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vmnet"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

It does import.

This looks good w/ v1.5.0-dev-20250203 w/ the edits to the ClusterRole + main image
I can go ahead and close this out 😄
