### ISSUE TITLE
[BUG] improve identification of VM's pinned to hostnames during maintenance operations

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#6509]
**Describe the bug**

As part of the requirements for issue: https://github.com/harvester/harvester/issues/4888 we introduced additional logic to identify VM's which cannot be scheduled to other nodes due to
* HostDevices
* Scheduling or Zone constraints
* Unhealthy longhorn replicas

The change did not include identifying VM's where a specific node scheduling has been specified for the VM.  In such scenarios hostname is added using `kubernetes.io/hostname` label to VM node selector

**To Reproduce**
1. Create a VM in harvester which is scheduled to run on a specific host
2. Attempt to place the host into maintenance mode.

**Expected behavior**

Expect to see the VM reported in the list of VM's which cannot be migrated since the `hostname` based scheduling criteria cannot be met on another node in the cluster
**Support bundle**

**Environment**
 - Harvester ISO version: v1.3-head, v1.4-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Additional info is available here: https://github.com/harvester/harvester/issues/5911#issuecomment-2302882601

**Comment by lanfon72** [comment]
Verified this bug is not fix yet, move back to implement.


https://github.com/user-attachments/assets/a2711ad0-0d5b-423a-81d6-009f916688cc




Test Information
----
* Environment: **bare metal DL360G9 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 2 nodes having PCI devices
2. Create an image for VM creation
3. Create VM that scheduling on specific node (using `spec.spec.nodeSelector`) and start it
4. Enable maintenance mode without **force** on the node hosting VM
6. Error message displayed and VMs should NOT be shut down automatically
7. The node should NOT enter maintenance mode
8. Enable maintenance mode with **force** on the node hosting VMs
9. VMs should be shut down automatically
10. The node should enter maintenance mode

**Comment by w13915984028** [comment]
@lanfon72 Your failure test case https://github.com/harvester/harvester/issues/6509#issuecomment-2427066405 looks to be possibly related to `KubeVirt` change. Please also check the yaml of your VM, if it is similar to following.

--

Harvester code has following assumption:

https://github.com/harvester/harvester/blob/d4c699718434682dda46c201cbbd87e80d23db8d/pkg/controller/master/nodedrain/nodedrain_controller.go#L356

https://github.com/harvester/harvester/blob/d4c699718434682dda46c201cbbd87e80d23db8d/pkg/controller/master/nodedrain/nodedrain_controller.go#L411

It assumes `kubevirt` will mark a VM as non-migratable in the condition.

`VirtualMachineInstanceIsMigratable VirtualMachineInstanceConditionType = "LiveMigratable"`

--
However,  from the test of below VM on harvester v1.4. It has empty `affinity`, but a `nodeSelector`  to simply pin a node.

KubeVirt marks this VM as `LiveMigratable` "True", but the `migrationMethod` is `BlockMigration`.

```
  migrationMethod: BlockMigration
  ...
  conditions:
    status: "True"
    type: LiveMigratable
```
--
From the below source code `calculateLiveMigrationCondition`, the above status is possible. This means Harvester code needs to change.

https://github.com/kubevirt/kubevirt/blob/c346dee068a2d0c515270810b7ab7a952b060ad6/pkg/virt-handler/vm.go#L1623-L1666

```
A simple host-pinned VM definition:

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
..
..
  labels:
    harvesterhci.io/vmName: vm4
    kubevirt.io/nodeName: harv41
  name: vm4
  namespace: default
..
spec:
  affinity: {}
  architecture: amd64
  domain:
    cpu:
      cores: 1
      model: host-model
..
..
  evictionStrategy: LiveMigrateIfPossible
  hostname: vm4
..
  nodeSelector:
    kubernetes.io/hostname: harv41
  terminationGracePeriodSeconds: 120
..
status:
  activePods:
    37481a5b-42b4-4001-923b-22e461bdbf71: harv41
  conditions:
..
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
..

  migrationMethod: BlockMigration
  migrationTransport: Unix
...

```
