### ISSUE TITLE
[BUG] Can't select the harvester version to upgrade in Rancher UI

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#6522]
**Describe the bug**

When I want to upgrade from harvester v1.3.1 to v1.3.2 in Rancher v2.9.1 UI, I found that version select box did not show the version v1.3.2, but it shows in harvester embedded UI.
![微信截图_20240907113121](https://github.com/user-attachments/assets/514b4cbe-9dd5-42c4-9033-acb002648c4e)
![微信截图_20240907113040](https://github.com/user-attachments/assets/87e9b925-73df-4b6a-b1c0-aad504bbbc4e)

**To Reproduce**
1.  Apply `version.yaml` via kubectl ref. [prepare-an-air-gapped-upgrade](https://docs.harvesterhci.io/v1.3/upgrade/index#prepare-an-air-gapped-upgrade)
2. Click upgrade button in Rancher v2.9.1 UI

**Expected behavior**

The upgrade version should be appeared at the Rancher UI.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
@W0n9 We haven't published the version to the responder yet, did you add the version file on your own?

**Comment by W0n9** [comment]
@bk201 Yes, I created the version file according to [prepare-an-air-gapped-upgrade](https://docs.harvesterhci.io/v1.3/upgrade/index#prepare-an-air-gapped-upgrade).

**Comment by brandboat** [comment]
I can reproduce this issue, after executing `kubectl apply -f version.yaml` in harvester cluster
```yaml
# version.yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.3.2
  namespace: harvester-system
spec:
  isoChecksum: '2b99b0870d3363b393bb7900c53b8a1f529e150519558cea672e9ff8eab19ba0dac3f35688e49cdc2ac3ba0d253017fd3d8790cb229856735e30c524f56f22a7'
  isoURL: https://releases.rancher.com/harvester/v1.3.2/harvester-v1.3.2-amd64.iso
  releaseDate: '20240906'
```
you can see the upgrade button in Harvester and Rancher UI, but after clicking the Upgrade button, there is no v1.3.2 in 
`AVAILABLE COMPATIBLE VERSIONS` dropdown menu in Rancher `Update Software` panel

I'm not sure if this is related to UI or something else. c.c. @a110605, @torchiaf
