### ISSUE TITLE
[ENHANCEMENT] seeder improvements

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#6535]
**Is your enhancement related to a problem? Please describe.**

Issue to track general seeder improvements to support the following:
* ipxe for machines in uefi mode
* arm machine support
* support for tinkerbell workflows to leverage new image streaming mode
* customisation of inventory provider ports
* move provisioning to leverage upstream boots, there by dropping need for a custom boots with harvester specific provisioning logic

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
bumping rufio should also help address: https://github.com/harvester/harvester/issues/4629

**Comment by khushboo-rancher** [comment]
@albinsun Can we consider that seeder support for ARM is working fine based on your https://github.com/harvester/harvester/issues/6257#issuecomment-2732593725 comment?

**Comment by irishgordo** [comment]
@ibrokethecloud for:
- https://github.com/harvester/seeder/blob/9cb5a89fd80ed2f231e49a515a81b1afb8bc0a9f/pkg/api/v1alpha1/cluster_types.go#L51

Do you have an example of what the CustomProvisioningTemplate would be?

Would it just be that it's referencing a TinkerBell Template?

So there would have to be a Template built, something like:
```yaml
apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: ntp-tester
  namespace: tink-system
spec:
  data: |
    name: ubuntu
    version: "0.1"
    global_timeout: 9800
    tasks:
      - name: "ntp-testing"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          GLOBAL_VALUE: "my global value"
        actions:
          - name: "check ntp"
            image: docker.io/irishgordo/cattledogs-ntp-validator:dev
            timeout: 300
            pid: host
          - name: "power off"
            image: ghcr.io/jacobweinstock/waitdaemon:latest
            timeout: 90
            pid: host
            command: ["poweroff"]
            environment:
              IMAGE: alpine
              WAIT_SECONDS: 5
```

So then it would be
```yaml
apiVersion: metal.harvesterhci.io/v1alpha1
kind: Cluster
metadata:
  name: test
  namespace: tink-system
spec:
  clusterConfig:
    customProvisioningTemplate: ntp-tester
```

^ plus the other content in a Cluster

**Comment by albinsun** [comment]
> [@albinsun](https://github.com/albinsun) Can we consider that seeder support for ARM is working fine based on your [#6257 (comment)](https://github.com/harvester/harvester/issues/6257#issuecomment-2732593725) comment?

In my understanding, seeder does not support ARM machines in lab yet. My test were provision by manual via remote console.
@ibrokethecloud, is that correct? or do we already support it?

**Comment by ibrokethecloud** [comment]
we support arm nodes, our lab has a specific limitation for ipxe boot off tagged vlans from the nics. In old DC we were able to use seeder for arm machines too

**Comment by ibrokethecloud** [comment]
@irishgordo by default seeder will create a `template` and `workflow` object associated with each inventory item

for example

```
apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  creationTimestamp: "2025-04-02T04:22:35Z"
  generation: 1
  name: hp-97
  namespace: tink-system
  ownerReferences:
  - apiVersion: metal.harvesterhci.io/v1alpha1
    kind: Cluster
    name: webber-97-107-cluster
    uid: 0b4f7ec6-7a48-492c-b682-508b8f92d17e
  resourceVersion: "119269114"
  uid: a552d1e7-0e71-4561-ba3b-968ae4cfca6b
spec:
  data: |
    version: "0.1"
    name: harvester-installation
    id: ""
    global_timeout: 36000
    tasks:
        - name: harvester-os-installation
          worker: '{{.device_1}}'
          actions:
            - name: stream-harvester
              image: gmehta3/image2disk:dev
              timeout: 3000
              environment:
                COMPRESSED: "true"
                DEST_DISK: /dev/nvme0n1
                IMG_URL: http://endpoint/iso/harvester//v1.3.2/harvester-v1.3.2-amd64.raw.gz
            - name: configure-harvester
              image: gmehta3/configure-harvester:latest
              timeout: 90
              environment:
                HARVESTER_DEVICE: /dev/nvme0n1
                HARVESTER_STREAMDISK_CLOUDINIT_URL: http://1hegelendpoint:50061/2009-04-04/user-data
                HARVESTER_TTY: tty1
            - name: reboot-harvester
              image: gmehta3/reboot:latest
              timeout: 90
              volumes:
                - /worker:/worker
          volumes:
            - /dev:/dev
            - /dev/console:/dev/console
            - /lib/firmware:/lib/firmware
```

Each inventory is associated with a workflow as well.

The workflow based provisioning leverages harvester stream image mode which we have not really leveraged much and was designed specifically for equinix metal.

You will need to build a stream image mode artifact before you can leverage this.

Once this is done the cluster spec, needs `spec.clusterConfig.streamImageMode` set to `true` in the cluster definition to leverage workflow based provisioning.

**Comment by irishgordo** [comment]
@ibrokethecloud  thanks for that mention.
I'm struggling finding ARM machines.
Based around:
```
kubectl get inventories -o wide -n tink-system -o json | jq -r '.items[] | select(any(.spec.baseboardSpec.connection.host; IN("a", "b", "c"))) | "the iLO address is: " + .spec.baseboardSpec.connection.host  + " IP addr should be empty: " + .status.pxeBootConfig.address + " ssh password should be empty: " + .status.generatedPassword + " - name of node: " + .metadata.name'
```

Replace `a, b, c` with the iLO of the ARM machines.
The inventories don't seem to be present.
But unsure if @albinsun is using any of the ARM machines, or if anyone else may be 🤔 

cc: @khushboo-rancher

**Comment by irishgordo** [comment]
In general this looks good 😄 👍  - thanks for the enhancement @ibrokethecloud 
We'll track the ARM side here:
- https://github.com/harvester/harvester/issues/8087

I'll go ahead and close this out

Additionally harvester-seeder upgrade in rs from v1.4.2 -> v1.5.0-rc4 looks to be okay:
```YAML
Name:             harvester-seeder-9c879cf6f-qxs8g                                                                                                                                                                 
Namespace:        harvester-system                                                                                                                                                                                 
Priority:         0                                                                                                                                                                                                
Service Account:  harvester-seeder                                                                                                                                                                                 
Node:             node-93-airgap/10.115.16.93                                                                                                                                                                      
Start Time:       Wed, 16 Apr 2025 17:09:58 -0700                                                                                                                                                                  
Labels:           app.kubernetes.io/instance=harvester-seeder                                                                                                                                                      
                  app.kubernetes.io/name=harvester-seeder                                                                                                                                                          
                  pod-template-hash=9c879cf6f                                                                                                                                                                      
Annotations:      cni.projectcalico.org/containerID: 7e358a9b0bac1908df8ad3dddab410f48078b9bfff5e3d34040281554e0a7b01                                                                                              
                  cni.projectcalico.org/podIP: 10.52.0.2/32                                                                                                                                                        
                  cni.projectcalico.org/podIPs: 10.52.0.2/32                                                                                                                                                       
                  k8s.v1.cni.cncf.io/network-status:                                                                                                                                                               
                    [{                                                                                                                                                                                             
                        "name": "k8s-pod-network",                                                                                                                                                                 
                        "ips": [                                                                                                                                                                                   
                            "10.52.0.2"                                                                                                                                                                            
                        ],                                                                                                                                                                                         
                        "default": true,                                                                                                                                                                           
                        "dns": {}                                                                                                                                                                                  
                    }]                                                                                                                                                                                             
Status:           Running                                                                                                                                                                                          
IP:               10.52.0.2                                                                                                                                                                                        
IPs:                                                                                                                                                                                                               
  IP:           10.52.0.2                                                                                                                                                                                          
Controlled By:  ReplicaSet/harvester-seeder-9c879cf6f                                                                                                                                                              
Containers:                                                                                                                                                                                                        
  harvester-seeder:                                                                                                                                                                                                
    Container ID:   containerd://dd9d526ac259b5bfc80a75606e93475a6ec512a517eec3c4e1da7eac3bfa2630                                                                                                                  
    Image:          rancher/harvester-seeder:v1.5.0-rc4                                                                                                                                                            
    Image ID:       sha256:dcf54686193cd703930edd94e56eca69c90c8e70b75b6198955480fd92369f26                                                                                                                        
    Ports:          8080/TCP, 8081/TCP, 9443/TCP, 443/TCP                                                                                                                                                          
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP                                                                                                                                                                     
    State:          Running                                                                                                                                                                                        
      Started:      Wed, 16 Apr 2025 17:10:00 -0700                                                                                                                                                                
    Ready:          True                                                                                                                                                                                           
    Restart Count:  0                                                                                                                                                                                              
    Limits:                                                                                                                                                                                                        
      cpu:     500m                                                                                                                                                                                                
      memory:  500Mi                                                                                                                                                                                               
    Requests:                                                                                                                                                                                                      
      cpu:      250m                                                                                                                                                                                               
      memory:   250Mi                                                                                                                                                                                              
    Liveness:   http-get http://:http/metrics delay=0s timeout=1s period=10s #success=1 #failure=3                                                                                                                 
    Readiness:  http-get http://:http/metrics delay=0s timeout=1s period=10s #success=1 #failure=3                                                                                                                 
    Environment:                                                                                                                                                                                                   
      SEEDER_EMBEDDED_MODE:       true                                                                                                                                                                             
      LEADER_ELECTION_NAMESPACE:  harvester-system (v1:metadata.namespace)                                                                                                                                         
    Mounts:                                                                                                                                                                                                        
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-c8klj (ro)                                                                                                                                
Conditions:                                                                                                                                                                                                        
  Type                        Status                                                                                                                                                                               
  PodReadyToStartContainers   True                                                                                                                                                                                 
  Initialized                 True                                                                                                                                                                                 
  Ready                       True                                                                                                                                                                                 
  ContainersReady             True                                                                                                                                                                                 
  PodScheduled                True                                                                                                                                                                                 
Volumes:                                                                                                                                                                                                           
  kube-api-access-c8klj:                                                                                                                                                                                           
    Type:                    Projected (a volume that contains injected data from multiple sources)                                                                                                                
    TokenExpirationSeconds:  3607                                                                                                                                                                                  
    ConfigMapName:           kube-root-ca.crt                                                                                                                                                                      
    ConfigMapOptional:       <nil>                                                                                                                                                                                 
    DownwardAPI:             true                                                                                                                                                                                  
QoS Class:                   Burstable                                                                                                                                                                             
Node-Selectors:              <none>                                                                                                                                                                                
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s                                                                                                                             
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s                                                                                                                           
Events:                                                                                                                                                                                                            
  Type    Reason          Age   From               Message                                                                                                                                                         
  ----    ------          ----  ----               -------                                                                                                                                                         
  Normal  Scheduled       2m6s  default-scheduler  Successfully assigned harvester-system/harvester-seeder-9c879cf6f-qxs8g to node-93-airgap                                                                       
  Normal  AddedInterface  2m6s  multus             Add eth0 [10.52.0.2/32] from k8s-pod-network                                                                                                                    
  Normal  Pulled          2m6s  kubelet            Container image "rancher/harvester-seeder:v1.5.0-rc4" already present on machine                                                                                
  Normal  Created         2m6s  kubelet            Created container harvester-seeder                                                                                                                              
  Normal  Started         2m5s  kubelet            Started container harvester-seeder                                                                                                                              
                                                                                            
```
