### ISSUE TITLE
[ENHANCEMENT] DeviceName (Resource Name) in HostDevices/GPUs should be verified

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#6542]
**Is your enhancement related to a problem? Please describe.**
When testing with pcidevices-controller add-on, it won't complain any errors when deviceName (resource name) is invalid.

```yaml
hostDevices:
- deviceName: "{prefix}/not-found"
   name: "a name" 
gpus:
- deviceName: "{prefix}/not-found"
   name: "a name" 
```

**Describe the solution you'd like**
We could check those names to see if they match. But, we need to be careful that there might not be only a PCI device and a USB device. For example, if the device name is not found in the USB device, it could be in the PCI device, including other devices (if they have).

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/harvester/dashboard/pull/1069#issuecomment-2342852626
