### ISSUE TITLE
[BUG] HA mode is not enabled after setting up a Harvester cluster with 3 nodes

### ISSUE THREAD

**Issue by yas51ne** [harvester/harvester#6546]
**Describe the bug**
After setting up a Harvester cluster with 3 nodes (harvester-01, harvester-02, and harvester-03), I encountered issues where new nodes successfully join the cluster but are not recognized as control-plane or etcd nodes. As a result, I am unable to place the first node (harvester-01) into maintenance mode because the cluster seems to still be operating in a single control-plane configuration, despite the additional nodes.

**To Reproduce**
Set up a Harvester cluster with 3 nodes:

- harvester-01: Control-plane, etcd, master
- harvester-02: Worker (attempting to add as control-plane and etcd)
- harvester-03: Worker (also attempting to add as control-plane and etcd)

The new nodes (harvester-02 and harvester-03) join the cluster but are not promoted to control-plane or etcd roles.
Attempting to manually add the roles using kubectl label does not schedule etcd or control-plane pods on the new nodes.

- Create config:
```yaml
scheme_version: 1
token: ....
os:
  hostname: harvester-01
  ssh_authorized_keys:
    - github:...
    - "ssh-rsa ..."
  password: .....
  dns_nameservers:
    - 192.168.100.1
    - 8.8.8.8
    - 1.1.1.1
  ntp_servers:
  - 192.168.100.1
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
  labels:
    topology.kubernetes.io/zone: zone1
    region: europecentral
    cloud: homelab.ai
install:
  mode: create
  role: default
  automatic: true
  skipchecks: true
  management_interface:
    interfaces:
    - name: enp4s0
    default_route: true
    method: static
    ip: 192.168.100.10
    subnet_mask: 255.255.255.0
    gateway: 192.168.100.1
    bond_options:
      mode: balance-tlb
      miimon: 100
  device: /dev/nvme0n1       # The target disk to install
  iso_url: http://192.168.200.138:8080/asset-mirror/releases/download/http/harvester/harvester-v1.3.2-amd64.iso
  #tty: tty1 #,115200n8  # For machines without a VGA console

  vip: 192.168.100.9
  vip_mode: static
  vip_hw_addr: ""

```
- Join config:
```yaml
scheme_version: 1
server_url: https://192.168.100.9:443
token: .....
os:
  hostname: harvester-03
  ssh_authorized_keys:
    - github:...
    - "ssh-rsa ..."
  password: .... 
  dns_nameservers:
    - 192.168.100.1
    - 8.8.8.8
    - 1.1.1.1
  ntp_servers:
  - 192.168.100.1
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
  labels:
    topology.kubernetes.io/zone: zone1
    region: europecentral
    cloud: homelab.ai
install:
  mode: join
  automatic: true
  skipchecks: true
  management_interface:
    interfaces:
    - name: enp4s0
    default_route: true
    method: static
    ip: 192.168.100.12
    subnet_mask: 255.255.255.0
    gateway: 192.168.100.1
    bond_options:
      mode: balance-tlb
      miimon: 100
  device: /dev/nvme0n1       # The target disk to install
  iso_url: http://192.168.200.138:8080/asset-mirror/releases/download/http/harvester/harvester-v1.3.2-amd64.iso
  tty: ttyS1,115200n8   # For machines without a VGA console
```
**Expected behavior**
The additional nodes should be promoted to control-plane and etcd roles, resulting in a High Availability (HA) cluster where all control-plane nodes can be put into maintenance mode independently.

**Support bundle**
[supportbundle_282cf640-adc6-47d4-aed4-766a4cd7d751_2024-09-11T19-30-38Z.zip](https://github.com/user-attachments/files/16969247/supportbundle_282cf640-adc6-47d4-aed4-766a4cd7d751_2024-09-11T19-30-38Z.zip)

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure: Baremetal with ACEMAGICIAN AM06 Pro

**Additional context**
Actual Behavior

- The additional nodes (harvester-02 and harvester-03) join the cluster but are only recognized as worker nodes.
- The first node (harvester-01) remains the sole control-plane and etcd node.
- When attempting to place harvester-01 into maintenance mode, I receive the error: Single control-plane cluster, cannot place control-plane in maintenance mode.
- No etcd pods are scheduled on harvester-02 or harvester-03 despite manually applying control-plane and etcd labels.

Screenshots

- Harvester UI - Hosts Overview:
harvester-02 and harvester-03 appear as active but do not have control-plane or etcd labels.
<img width="1505" alt="Screenshot 2024-09-11 at 21 45 31" src="https://github.com/user-attachments/assets/c2bdea1b-4523-46f5-963a-f92ffb9d882e">

- Rancher UI - Nodes Overview:
The nodes are visible, but only harvester-01 has the control-plane and etcd roles.
<img width="1500" alt="Screenshot 2024-09-11 at 21 45 16" src="https://github.com/user-attachments/assets/d4945ef4-8fe1-4474-9e8b-047be2de6a3c">

- Logs and Outputs

kubectl get nodes : Output showing that the additional nodes are labeled as control-plane and etcd but no etcd or control-plane pods are scheduled.
```bash
harvester-01:/home/rancher # kubectl get nodes
NAME           STATUS   ROLES                       AGE     VERSION
harvester-01   Ready    control-plane,etcd,master   5h47m   v1.28.12+rke2r1
harvester-02   Ready    <none>                      48m     v1.28.12+rke2r1
harvester-03   Ready    <none>                      4h3m    v1.28.12+rke2r1
```

kubectl get pods -n kube-system -l component=etcd -o wide: Output showing etcd pods running only on harvester-01.
```bash
harvester-01:/home/rancher # kubectl get pods -n kube-system -l component=etcd -o wide
NAME                READY   STATUS    RESTARTS   AGE   IP               NODE           NOMINATED NODE   READINESS GATES
etcd-harvester-01   1/1     Running   2          80m   192.168.100.10   harvester-01   <none>           <none>
```

etcdctl member list: Output showing only harvester-01 as a member of the etcd cluster.
```bash
harvester-01:/home/rancher # kubectl exec -n kube-system etcd-harvester-01 -- etcdctl   --endpoints=https://127.0.0.1:2379   --cacert=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt   --cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt   --key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key  member list
c2bde6fe848e75ba, started, harvester-01-933e1269, https://192.168.100.10:2380, https://192.168.100.10:2379, false
```

I have attempted the following steps:

- Recreating nodes (harvester-02 and harvester-03) and ensuring they join the cluster.
- Manually adding control-plane and etcd roles via kubectl label.

Despite these efforts, the nodes remain as worker nodes, and etcd/control-plane pods are not scheduled on them.
