### ISSUE TITLE
[QUESTION] How to restore PVC for Windows VM from backup?

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#6553]
I had Windows VM (Windows Server 2019), which had
- backing image 
- disc

I didn't use VM backup, but used Longhorn backup for volumes.

On new Harvester cluster (version 1.3.2), I created image, using same backing image.

Then, using Longhorn I restored volume for the disc.

But before I can use that disc in Windows VM, I need to create PVC.

The problem is that when I try to create PVC, Longhorn asks me to specify Filesystem and the only choice is `ext4` or `xfs`, which are incorrect for Windows:

![Screenshot 2024-09-12 at 11 08 20](https://github.com/user-attachments/assets/d64710aa-e831-466b-a66a-37a66f187767)

How can I create correct PVC for Windows disk?

Volume:
```
Ready for workload:Ready
Conditions: Restore Scheduled
Frontend:Block Device
Data Engine:v1
Offline Replica Rebuilding:disabled
Attached Node & Endpoint:
Size: 160 Gi
Actual Size:86.9 Gi
Data Locality:disabled
Access Mode:ReadWriteMany
Backing Image:default-image-xx6n7
Backing Image Size:146 Gi
Engine Image:longhornio/longhorn-engine:v1.6.2
Created:26 minutes ago
Encrypted:False
Node Tags:
Disk Tags:SSD
Last Backup:backup-2f20f210622f4cbe
Last Backup At:16 hours ago
Replicas Auto Balance:ignored
Snapshot Data Integrity:ignored
Snapshot Max Count:250
Snapshot Max Size:0 Bi
Instance Manager:
Allow snapshots removal during trim:ignored
Replica Soft Anti Affinity:ignored
Replica Zone Soft Anti Affinity:ignored
Replica Disk Soft Anti Affinity:ignored
Last time bound with PVC:16 hours ago
Last time used by Pod:16 hours ago
Last Namespace:default
Last Bounded PVC Name:qb-win-disk-0-sjzjc
PV Name:
PV Status:
Revision Counter Disabled:False
Last Pod Name:virt-launcher-qb-win-jcjm2
Last Workload Name:qb-win
Last Workload Type:VirtualMachineInstance
```
@Vicente-Cheng can you look at this issue, please?

**Comment by SlavikCA** [comment]
I tried to create PV and PVC manually with `kubectl`:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qb20-disc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 160Gi
  storageClassName: longhorn-image-4mwl7   # that's original VM image
  volumeMode: Block
  volumeName: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6  # that's  disk restored from backup
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 160Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: qb20-disc
    namespace: default
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      backingImage: vmi-093a66e7-7f99-4388-b3a2-f7dd6167a89d
      diskSelector: SSD
      migratable: "true"
      numberOfReplicas: "2"
      share: "true"
      staleReplicaTimeout: "30"
    volumeHandle: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6   # that's  disk restored from backup
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-image-4mwl7
  volumeMode: Block
```

And it succesfully created.
I can see it VOLUMES:
![Screenshot 2024-09-12 at 20 53 01](https://github.com/user-attachments/assets/93a0920d-2b5b-46e0-955e-ea94868e9085)

**Comment by SlavikCA** [comment]
I tried to create PV and PVC manually with `kubectl`:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qb20-disc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 160Gi
  storageClassName: longhorn-image-4mwl7   # that's original VM image
  volumeMode: Block
  volumeName: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6  # that's  disk restored from backup
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 160Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: qb20-disc
    namespace: default
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      backingImage: vmi-093a66e7-7f99-4388-b3a2-f7dd6167a89d
      diskSelector: SSD
      migratable: "true"
      numberOfReplicas: "2"
      share: "true"
      staleReplicaTimeout: "30"
    volumeHandle: pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6   # that's  disk restored from backup
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-image-4mwl7
  volumeMode: Block
```

And it succesfully created.
I can see it VOLUMES:
![Screenshot 2024-09-12 at 20 53 01](https://github.com/user-attachments/assets/93a0920d-2b5b-46e0-955e-ea94868e9085)

But I can't add it to the VM: it's not shown in UI:
![Screenshot 2024-09-12 at 20 54 37](https://github.com/user-attachments/assets/a7c2f537-af05-4008-a1d4-a674e219057c)

**Comment by SlavikCA** [comment]
And when I try to add disc manually in the VM's YAML, - it get's added, but then I see in the pod status:
vvv
>  FailedAttachVolume  47s (x8 over 115s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6" : rpc error: code = Internal desc = volume pvc-a26ed124-c4b7-4bb3-b9ab-7e29ed24fac6 failed to attach to node t5820 with attachmentID csi-8e73c2c1d61b77c868239c3fc0244911ed67463b9106e4c96cae0d9ccdc931a9: Waiting for volume share to be available

But I'm not sure, if I'm adding it correctly.
Do I just need to add PVC? Should backing image be added too?

Here is VM manifest I tried:
```
type: kubevirt.io.virtualmachine
metadata:
  namespace: default
  annotations:
    network.harvesterhci.io/ips: '[]'
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: windows
  name: qb45
__clone: true
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      labels:
        harvesterhci.io/vmName: qb45
    spec:
      domain:
        machine:
          type: ''
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
          disks:
            - name: disk-0
              disk:
                bus: virtio
              bootOrder: 1
          hostDevices: []
        resources:
          limits:
            memory: 12Gi
            cpu: '4'
        features:
          acpi:
            enabled: true
      evictionStrategy: LiveMigrateIfPossible
      hostname: qb45
      networks:
        - name: default
          multus:
            networkName: default/un2
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: qb20-disc
      affinity: {}
      terminationGracePeriodSeconds: 120
```
