### ISSUE TITLE
[BUG] Rancher2 Terraform Seems To Have Issues Provisioning RKE2 Clusters w/ v1.3.2

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6562]
### Describe The Bug
- when creating a vCluster addon based Rancher on Harvester, importing Harvester and then setting up Rancher2 Terraform Provider with vCluster Rancher there seems to be issues provisioning RKE2 clusters on Harvester with:
  - [v1.29.8+rke2r1, v1.27.16+rke2r2, v1.28.13, v1.30.4] , any of those versions to "start"
  - tested with callico, cilium, and canal -> all similar outcomes

### Workaround
- it's interesting, pretty much, when the cluster starts provisioning the VM (kubelet, etcd, etc.) start to be displayed in the "provisioning log" from Rancher v2.9.1 , the way around it, is to just "upgrade" the cluster from the UI, like bumping "v1.29.8" -> "v1.30.4", and that seems to fix everything
- otherwise, the cluster just seems to hang at "waiting for node to register"

### vCluster Loadout:
- https://github.com/irishgordo/rancher-harvester-demo/blob/main/harvester-k8-crds/harvester-vcluster-enablement.yaml

### Terraform Loadout:
- this terraform, with exceptions of the few bugs in the README.md within the folder accomplishes the following:
  - builds 2 VirtualMachineImages ( one for rke2 cluster & one for minio )
  - sets up a 2 VM Networks on MGMT ( one for rke2 cluster & one for minio )
  - creates a VM for MinIO, that stands up MinIO with a bucket/key/secretkey/etc. all the configuration via Ansible
  - creates two cloud credentials, one for the imported harvester cluster, one for S3 bucket information 
  - builds out the machine config & rke2 cluster ( setting up etcd snapshots to point to the MinIO Harvester VM instance )
 - https://github.com/irishgordo/rancher-harvester-demo/blob/main/harvester-terraform-and-rke2/main.tf
 
 ### To Reproduce:
 1. git clone: https://github.com/irishgordo/rancher-harvester-demo/tree/main
 1. ensure ansible is installed (and in $PATH) + ansible dependencies ( highlighted in readme, for brevity: `ansible-galaxy collection install ansible.posix` , `ansible-galaxy collection install community.general` ) + also ensure `sshpass` is present
 1. in `harvester-k8s-crds` dir, modify: https://github.com/irishgordo/rancher-harvester-demo/blob/main/harvester-k8-crds/harvester-vcluster-enablement.yaml , to change "hostname" additionally password if desired , then run: https://github.com/irishgordo/rancher-harvester-demo/blob/main/harvester-k8-crds/setup-vcluster.sh
 1. once vCluster is up and running validate that you can log in
 1. in vCluster Rancher v2.9.1, build an API key copy the info down, modify https://github.com/irishgordo/rancher-harvester-demo/blob/c1389fec9a6498d3d2d960fda2925118b8886c3c/harvester-terraform-and-rke2/variables.tf#L241-L260 to update to your new api key
 1. in vCluster Rancher v2.9.1, import the Harvester v1.3.2 cluster as name: `harvester132`
 1. in vCluster Rancher v2.9.1, download your Harvester (`harvester132`) Kubeconfig YAML from vCluster Rancher, replacing: https://github.com/irishgordo/rancher-harvester-demo/blob/main/harvester132.yaml
 1. in Harvester v1.3.2 download the Kubeconfig, and replace it in: https://github.com/irishgordo/rancher-harvester-demo/blob/main/integration-cluster-kubeconfig.yaml
 1. inside the folder of https://github.com/irishgordo/rancher-harvester-demo/tree/main/harvester-terraform-and-rke2 run `TF_LOG=TRACE terraform init -reconfigure -upgrade` 
 1. in same folder as last step run `TF_LOG=TRACE TF_LOG_PROVIDER=DEBUG terraform apply -auto-approve`
 1. the apply will fail the first time with `Error: Provider produced inconsistent final plan` , don't worry, this is a bug, just run: `TF_LOG=TRACE TF_LOG_PROVIDER=DEBUG terraform apply -auto-approve` it again
 1. keep an eye in Rancher -> Clusters and when you see the cluster reach the "calico" stage -> then "waiting to register" you'll notice it's entirely hung
 1. navigate to Harvester -> VMs -> find the RKE2 VM -> `ssh ubuntu@the-vm-ipv-address` w/ password: `ubuntupw` -> then `sudo cat /etc/rancher/rke2/rke2.yaml` -> toss in clipboard -> then build a kubeconfig file and just `k9s` to view the VM's IPV4 RKE2 v1.29 and you'll notice "calico" pod is just stuck... **NOTE** (this is also noticed similarly w/ Cilium & Canal -> the main networking pod(s) of those CNIs also just seem to be "hung") 
 1. upgrade the RKE2 cluster to a new version from Rancher while keeping an eye on K9s, you'll see pods roll, and then all of a sudden things seem to spring back to life, the calico pod somehow becomes fixed, other helm operations and cattle-cluster things seem to look good and all of a sudden once upgrade to v1.30, the cluster seems to be fine
 
 ### Expected Behavior:
 - the ability to with Terraform from Harvester & Rancher2 , be able to provision a cluster "as is" at it's "desired version", with any CNI, without needing to "upgrade" the cluster to have it be "fixed" (so that the terraform doesn't time out and continues/finishes)
 
 ### Additional Context:
 - Rancher v2.9.1
 - vCluster Addon Used
 - Harvester v1.3.2
 - Rancher2 Terraform Provider: 5.0.0 **ALSO** noticable on `4.2.0` 
 - Harvester Terraform Provider:  0.6.4
 - Ansible Terraform Provider: 1.3.0
 - Setup: "bare-metal" HP DL160s
 
 **NOTE:** do not change:
 ```hcl
 {
    "disks": [{
        "imageName": "${harvester_image.rke2-jammy-img.id}",
        "size": ${var.rke2_pool_node_disk_size},
        "bootOrder": 1
    }]
}
 ``` 
 To:
 ```hcl
 {
    "disks": [{
        "imageName": "default/${harvester_image.rke2-jammy-img.id}",
        "size": ${var.rke2_pool_node_disk_size},
        "bootOrder": 1
    }]
}
 ```
 This seems to be another bug or perhaps a doc issue, as if you prepend the image id with a `default/` you'll be greeted by the error of:
 ```
     Error with pre-create check: "unexpected namespacedName format
    (\"default/default/rke2-jammy-img\"), expected \"namespace/name\" or
    \"name\". "
 ```
 From the bigger message in:
 ```
   failureMessage: >-
    Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=HarvesterMachine with name "rke2-terraform-pool1-ndtxd-fjxvd":
    Downloading driver from
    https://rancher.192.168.104.180.sslip.io/assets/docker-machine-driver-harvester

    Doing /etc/rancher/ssl

    docker-machine-driver-harvester

    docker-machine-driver-harvester: ELF 64-bit LSB executable, x86-64, version
    1 (SYSV), statically linked, stripped

    Trying to access option  which does not exist

    THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR

    Type assertion did not go smoothly to string for key 

    Running pre-create checks...

    Error with pre-create check: "unexpected namespacedName format
    (\"default/default/rke2-jammy-img\"), expected \"namespace/name\" or
    \"name\". "
  failureReason: CreateError
  lastUpdated: '2024-09-13T23:02:02Z'
  observedGeneration: 3
 ```
 - As it seems that it for some reason is already prepending the image-id with `default/` currently...

**Comment by irishgordo** [comment]
**Note this isn't only applicable to vCluster instances:**

A separate loadout was:
- a VM (jammy cloud image) 4C 8Gi RAM
- RKE2 (latest), v1.30.4+rke2r1
- Rancher v2.9.1
- Harvester v1.3.2, imported

It still is causing the same effect.

Sample flow:
On VM:
```bash
ubuntu@rke2vmnew:~$ curl -sfL https://get.rke2.io | sudo sh -
[INFO]  finding release for channel stable
[INFO]  using v1.30.4+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.30.4+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.30.4+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
ubuntu@rke2vmnew:~$ sudo systemctl enable rke2-server.service
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/local/lib/systemd/system/rke2-server.service.
ubuntu@rke2vmnew:~$ sudo systemctl start rke2-server.service
ubuntu@rke2vmnew:~$ sudo cat /etc/rancher/rke2/rke2.yaml
```
On Host:
```bash
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set installCRDs=true --version=v1.15.2
```
```bash
kubectl create namespace cattle-system
```
```bash
helm install rancher rancher-stable/rancher \
  --version 2.9.1 \
  --namespace cattle-system \
  --set hostname=rancher.192.168.104.249.sslip.io \
  --set global.cattle.psp.enabled=false \
  --set bootstrapPassword=testtesttest \
  --set replicas=1 \
  --debug
```


Calico Node (again common with cilium, others) in the pods seems to be having all sorts of issues:
```go
le.crt"                                                                                                                                                  
calico-node 2024-09-17 18:50:28.423 [INFO][392] tunnel-ip-allocator/config_params.go 671: Parsed value for TyphaCAFile: /etc/pki/tls/certs/tigera-ca-bund
le.crt (from environment variable)                                                                                                                       
calico-node 2024-09-17 18:50:28.423 [INFO][392] tunnel-ip-allocator/config_params.go 635: Parsing value for TyphaK8sNamespace: calico-system (from enviro
nment variable)                                                                                                                                          
calico-node 2024-09-17 18:50:28.423 [INFO][392] tunnel-ip-allocator/config_params.go 671: Parsed value for TyphaK8sNamespace: calico-system (from environ
ment variable)                                                                                                                                           
calico-node 2024-09-17 18:50:28.425 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHAK8SSERVICENAME=calico-typha                           
calico-node 2024-09-17 18:50:28.425 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHAK8SNAMESPACE=calico-system                            
calico-node 2024-09-17 18:50:28.426 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHAKEYFILE=/node-certs/tls.key                           
calico-node 2024-09-17 18:50:28.426 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHACERTFILE=/node-certs/tls.crt                          
calico-node 2024-09-17 18:50:28.426 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHACAFILE=/etc/pki/tls/certs/tigera-ca-bundle.crt        
calico-node 2024-09-17 18:50:28.426 [INFO][392] tunnel-ip-allocator/config.go 62: Found FELIX_TYPHACN=typha-server                                       
calico-node 2024-09-17 18:50:28.426 [INFO][392] tunnel-ip-allocator/discovery.go 172: Creating Kubernetes client for Typha discovery...                  
calico-node 2024-09-17 18:50:28.426 [WARNING][392] tunnel-ip-allocator/winutils.go 150: Neither --kubeconfig nor --master was specified.  Using the inClu
sterConfig.  This might not work.                                                                                                                        
calico-node 2024-09-17 18:50:28.427 [INFO][392] tunnel-ip-allocator/discovery.go 188: (Re)discovering Typha endpoints using the Kubernetes API...        
calico-node 2024-09-17 18:50:28.432 [ERROR][392] tunnel-ip-allocator/discovery.go 228: Didn't find any ready Typha instances.                            
calico-node 2024-09-17 18:50:28.432 [FATAL][392] tunnel-ip-allocator/startsyncerclient.go 49: Typha discovery enabled but discovery failed. error=Kuberne
tes service missing IP or port                                                                                                                           
calico-node 2024-09-17 18:50:28.627 [ERROR][53] felix/discovery.go 228: Didn't find any ready Typha instances.                                           
calico-node 2024-09-17 18:50:28.627 [ERROR][53] felix/daemon.go 351: Typha discovery enabled but discovery failed. error=Kubernetes service missing IP or
 port     
```

And again, *these all disappear with the workaround implemented*

![Screenshot from 2024-09-17 11-49-35](https://github.com/user-attachments/assets/312e5c11-e34e-45cc-93a8-9dda52fc6651)

**Comment by irishgordo** [comment]
Adding `regression` label to this, but willing to remove if this is a configuration issue :smile:

**Comment by albinsun** [comment]
FYI, have a quick test run on `test_z_terraform_rancher.py` and looks OK.
But I only change Rancher and K3s version compared to official [rancher-vcluster.yaml]( https://raw.githubusercontent.com/harvester/experimental-addons/main/rancher-vcluster/rancher-vcluster.yaml)
Do you have other changes like terraform script content compare to auot test case?
```
harvester-node-0:~ # diff rancher-vcluster-r291-k129.yaml rancher-vcluster.yaml 
20c20
<     rancherVersion: "v2.9.1"
---
>     rancherVersion: "v2.8.2"
23c23
<       image: rancher/k3s:v1.29.8-k3s1
---
>       image: rancher/k3s:v1.27.10-k3s2

```


### Environment
* `harvester-v1.3.2`
  * Profile: Single node QEMU/KVM (16C/32G/500G)
* `rancher-v2.9.1`
  * Profile: rancher-vcluster (`rancher/k3s:v1.29.8-k3s1`)
  * Guest Cluster
    * Image: `ubuntu-22.04-jammy-server-cloudimg-amd64.img`
    * Profile: Single node `v1.30.4+rke2r1`

### Result
![image](https://github.com/user-attachments/assets/4c392692-2f3f-4e3c-a233-c5ff5fe2fff0)
* `rancher-vcluster-r291-k129.yaml`
  ```
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rancher-vcluster
  ---
  apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    name: rancher-vcluster
    namespace: rancher-vcluster
    labels:
      addon.harvesterhci.io/experimental: "true"
  spec:
    enabled: false
    repo: https://charts.loft.sh
    version: "v0.19.0"
    chart: vcluster
    valuesContent: |-
      hostname: ""
      rancherVersion: "v2.9.1"
      bootstrapPassword: ""
      vcluster:
        image: rancher/k3s:v1.29.8-k3s1
      sync:
        ingresses:
          enabled: "true"
      syncer:
        resources:
          limits:
            memory: 8Gi    
      init:
        manifestsTemplate: |-
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cattle-system
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cert-manager
            labels:
              certmanager.k8s.io/disable-validation: "true"
          ---
          apiVersion: helm.cattle.io/v1
          kind: HelmChart
          metadata:
            name: cert-manager
            namespace: kube-system
          spec:
            targetNamespace: cert-manager
            repo: https://charts.jetstack.io
            chart: cert-manager
            version: v1.5.1
            helmVersion: v3
            set:
              installCRDs: "true"
          ---
          apiVersion: helm.cattle.io/v1
          kind: HelmChart
          metadata:
            name: rancher
            namespace: kube-system
          spec:
            targetNamespace: cattle-system
            repo: https://releases.rancher.com/server-charts/stable/
            chart: rancher
            version: {{ .Values.rancherVersion }}
            set:
              ingress.tls.source: rancher
              hostname: {{ .Values.hostname }}
              replicas: 1
              global.cattle.psp.enabled: "false"
              bootstrapPassword: {{ .Values.bootstrapPassword | quote }}
            helmVersion: v3
  ```
