### ISSUE TITLE
[DOC] Mention the importance of excluding IP addresses when configuring the storage network setting

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#6600]
**Is your doc request related to a problem? Please describe or add the related issue ID.**

Sometimes, IP addresses are used by other entities, e.g., the gateway, and we want to retain their usage while assigning the network as the storage network at the same time. This is when we use the `exclude` field in the storage network setting.

For instance, suppose 192.168.100.1 is the gateway IP address; with the following storage network setting, I can instruct the controller to avoid issuing that specific IP address to the Longhorn pods, thus preventing the IP address conflict.

```yaml
{
  "vlan": 100,
  "clusterNetwork": "provider",
  "range": "192.168.100.0/24",
  "exclude": [
    "192.168.100.1/32"
  ]
}
```

Despite having such functionality implemented, we don't seem to have a description explaining how to prevent Longhorn pods from using any specific IP address when configuring the storage network.

**Describe the solution you'd like**

Adding documentation about how to exclude specific IP addresses when configuring the storage network.

## Additional context

N/A
