### ISSUE TITLE
[BUG] BIOS based VMs imported from VMWare and OpenStack has no IP address

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6644]
**Describe the bug**
During verify harvester/harvester/issues/5758, we found BIOS based VMs imported from VMWare or OpenStack will has no IP address.
(EFI based VMs works fine)
![image](https://github.com/user-attachments/assets/d69c13af-5fa3-4372-a83b-8f9d63f6f0cc)

Note that if manually check **Install guest agent** and restart, IP address will shown.
* Manual **Install guest agent** and restart VM
  ![image](https://github.com/user-attachments/assets/3984e89f-9811-4e32-9d03-31d950a5eb94)
* And IP will shown
  ![image](https://github.com/user-attachments/assets/f957155b-5049-49ec-a1e9-8c367df06ae0)

**Prerequisite**
1. Having VMWare endpoint
3. <details>
   <summary> Create VM network <i>mgmt-vlan1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/fbe8707c-9772-4cff-9455-9a375dae7732)
   </details>
4. <details>
   <summary> Enable <b>vm-import-controller</b> addon 
   </summary>
   
   * Deploy Successful
     ![image](https://github.com/user-attachments/assets/11e9708a-7d50-4612-819b-7258ab05b193)
   * Config
     ![image](https://github.com/user-attachments/assets/5317714b-9d79-4de3-a653-cf07841411bf)
   </details>

**To Reproduce**
For example, import from VMWare
1. <details>
   <summary> :green_circle: <i>Given</i> a running BIOS based VM <i>dl-ubuntu-bios</i>
   </summary>
 
   * BIOS based
     ![image](https://github.com/user-attachments/assets/ad239002-2eb5-4d1d-910c-405092fcc46a)
   * Running
     ![image](https://github.com/user-attachments/assets/e69fa935-b9d3-4fcd-99b5-abf391d7ec51)
   </details>

2. <details>
   <summary> :green_circle: <i>When</i> import VM by creating <i>VirtualMachineImport</i>
   </summary>

    ```
    # cat vmware-VirtualMachineImport.yaml 
    apiVersion: migration.harvesterhci.io/v1beta1
    kind: VirtualMachineImport
    metadata:
      name: vmware-bios
      namespace: default
    spec: 
      virtualMachineName: "dl-ubuntu-bios"
      networkMapping:
      - sourceNetwork: "VM Network"
        destinationNetwork: "default/mgmt-vlan1"
      sourceCluster: 
        name: vcsim
        namespace: default
        kind: VmwareSource
        apiVersion: migration.harvesterhci.io/v1beta1
    
    # kubectl apply -f vmware-VirtualMachineImport.yaml 
    virtualmachineimport.migration.harvesterhci.io/vmware-bios created
    # 
    ```
   </details>

3. <details open>
   <summary> :yellow_circle: <i>Then</i> VM should be import and boot correctly
   </summary>
   
    > :warning: Running but IP does NOT shown
    ![image](https://github.com/user-attachments/assets/c0b790f9-ddc4-4bf9-a768-432cfac65a66)
    ![image](https://github.com/user-attachments/assets/5a05beb9-e226-4dad-8b3a-3a638d11a0a8)
    ![image](https://github.com/user-attachments/assets/d69c13af-5fa3-4372-a83b-8f9d63f6f0cc)
   </details>
  
4. <details>
   <summary> :green_circle: <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is not checked
   </summary>
 
   ![image](https://github.com/user-attachments/assets/cac48aa0-a8f8-4c74-beb2-7f28baaae95c)
   </details>

**Expected behavior**
Should have IP address once successfully imported.

**Support bundle**
[supportbundle_ImportedVmsHasNoIp_2024-09-25T10-00-44Z.zip](https://github.com/user-attachments/files/17129335/supportbundle_ImportedVmsHasNoIp_2024-09-25T10-00-44Z.zip)

**Environment**
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: Single node QEMU/KVM (48C/128G/1.6T)
  * ui-source: Auto

**Additional context**
n/a

**Reference**
1. https://docs.harvesterhci.io/v1.3/advanced/addons/vmimport#sources
2. https://docs.harvesterhci.io/v1.3/advanced/addons/vmimport#virtualmachineimport
3. https://harvester.github.io/tests/manual/advanced/addons/5846-vm-import-enhancement/

**Comment by bk201** [comment]
@votdev Please help check this issue, thanks!

**Comment by irishgordo** [comment]
Perhaps also somewhat related to:
https://github.com/harvester/harvester/issues/6451

**Comment by votdev** [comment]
I think the issue is related to https://github.com/harvester/harvester/issues/6406

**Comment by votdev** [comment]
I can confirm that after the import no IP is displayed.

After the import of a BIOS and UEFI VM i found the following.

# UEFI
```
kind: VirtualMachineInstance
metadata:
  name: dl-opensue-uefi
spec:
  domain:
    devices:
      disks:
      - bootOrder: 1
        disk:
          bus: sata
        name: disk-0
      interfaces:
      - bridge: {}
        macAddress: 00:50:56:96:46:94
        model: virtio
        name: migrated-0
  networks:
  - multus:
      networkName: default/vlan1
    name: migrated-0
status:
  interfaces:
  - infoSource: domain, guest-agent, multus-status
    interfaceName: eth0
    ipAddress: 192.168.0.50
    ipAddresses:
    - 192.168.0.50
    - fe80::250:56ff:fe96:4694
    mac: 00:50:56:96:46:94
    name: migrated-0
    queueCount: 1
```

# BIOS
```
kind: VirtualMachineInstance
metadata:
  name: dl-ubuntu-bios
spec:
  domain:
    devices:
      disks:
      - bootOrder: 1
        disk:
          bus: sata
        name: disk-0
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        macAddress: 00:50:56:96:65:62
        model: virtio
        name: migrated-0
  networks:
  - multus:
      networkName: default/vlan1
    name: migrated-0
status:
  interfaces:
  - infoSource: domain, multus-status
    mac: 00:50:56:96:65:62
    name: migrated-0
    queueCount: 1
```

**Comment by votdev** [comment]
Some more information.

# UEFI
```
qemu@dl-opensue-uefi:/> virsh qemu-agent-command 1 '{"execute":"guest-network-get-interfaces"}'
{
    "return":[
       {
          "name":"lo",
          "ip-addresses":[
             {
                "ip-address-type":"ipv4",
                "ip-address":"127.0.0.1",
                "prefix":8
             },
             {
                "ip-address-type":"ipv6",
                "ip-address":"::1",
                "prefix":128
             }
          ],
          "statistics":{
             "tx-packets":14,
             "tx-errs":0,
             "rx-bytes":2072,
             "rx-dropped":0,
             "rx-packets":14,
             "rx-errs":0,
             "tx-bytes":2072,
             "tx-dropped":0
          },
          "hardware-address":"00:00:00:00:00:00"
       },
       {
          "name":"eth0",
          "ip-addresses":[
             {
                "ip-address-type":"ipv4",
                "ip-address":"192.168.0.xx",
                "prefix":24
             },
             {
                "ip-address-type":"ipv6",
                "ip-address":"fe80::250:56ff:fe96:4694",
                "prefix":64
             }
          ],
          "statistics":{
             "tx-packets":51,
             "tx-errs":0,
             "rx-bytes":162100,
             "rx-dropped":1652,
             "rx-packets":2830,
             "rx-errs":0,
             "tx-bytes":6547,
             "tx-dropped":0
          },
          "hardware-address":"00:50:56:96:46:94"
       }
    ]
}
```

# BIOS
```
qemu@dl-ubuntu-bios:/> virsh qemu-agent-command 1 '{"execute":"guest-network-get-interfaces"}'
error: Guest agent is not responding: QEMU guest agent is not connected
```

Wanted to check if qemu-guest-agent is installed in the Ubuntu VM, bad need to get the credentials first.

**Comment by votdev** [comment]
Based on the `status.conditions` and `status.guestOSInfo` there is no qemu-guest-agent in the Ubuntu VM, thus no IP address can be reported.

# UEFI
```
status:
  conditions:
  - lastProbeTime: "2024-10-14T07:49:20Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
...
  guestOSInfo:
    id: opensuse-leap
    kernelRelease: 5.14.21-150500.55.65-default
    kernelVersion: '#1 SMP PREEMPT_DYNAMIC Thu May 23 04:57:11 UTC 2024 (a46829d)'
    machine: x86_64
    name: openSUSE Leap
    prettyName: openSUSE Leap 15.5
    version: "15.5"
    versionId: "15.5"
  interfaces:
  - infoSource: domain, guest-agent, multus-status
...
```

# BIOS
The Ubuntu machine is missing that `AgentConnected` condition entry. The `status.guestOSInfo` is empty and finally `status.interfaces.infoSource` does not contain `guest-agent` which indicates that the interface information does not contain data from the guest agent.
```
status:
  guestOSInfo: {}
  interfaces:
  - infoSource: domain, multus-status
```

Unfortunately, the other VMs listed in the issue description no longer exist to validate these as well.

For this reason I think we can close the issue because of expected behavior.
