### ISSUE TITLE
[BUG] Those after-upgrade actions may conflict with a new upgrade

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6670]
**Describe the bug**

Upgrade controller will try to:
(1) Remove unused images (https://github.com/harvester/harvester/issues/5749)
(2) Start VMs which were running before the upgrade if it is in a single-node cluster (https://github.com/harvester/harvester/issues/4005)

It is based on the condition that the current upgrade is completed, either successful or failed.

https://github.com/harvester/harvester/blob/606f485579d087def560e2a8a255a2b0f4bad019/pkg/controller/master/upgrade/upgrade_controller.go#L217

```
h.cleanup(upgrade, harvesterv1.UpgradeCompleted.IsTrue(upgrade))
h.restoreVMState(upgrade)
repo.startVM()
cleanupImages(upgrade, repo)
```

The webhookk will deny new upgrade:

https://github.com/harvester/harvester/blob/606f485579d087def560e2a8a255a2b0f4bad019/pkg/webhook/resources/upgrade/validator.go#L122

if an existing upgrade is not completed.

https://github.com/harvester/harvester/blob/606f485579d087def560e2a8a255a2b0f4bad019/pkg/webhook/resources/upgrade/validator.go#L132

You will notice that, when the controller is running to do those last actions, another upgrade can be started now 
(https://github.com/harvester/harvester/issues/6144,  PR: https://github.com/harvester/dashboard/pull/1081), 

the webhook does not block it.

**To Reproduce**

**Expected behavior**

The new upgrade should be blocked until the privious upgrade has finished all of those last actions.

It may affect those continuous upgrades.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

This is checked via validating issues:
https://github.com/harvester/harvester/issues/4005

https://github.com/harvester/harvester/issues/6144
PR: https://github.com/harvester/dashboard/pull/1081

https://github.com/harvester/harvester/issues/5749

**Comment by w13915984028** [comment]
cc @bk201 @starbops @tserong

**Comment by bk201** [comment]
@w13915984028 I'd suggest fixing this in the next milestone, given it's not a very common case to start the upgrade again. Does this sound good to you?

@brandboat the secret name to keep VMs is re-used and can cause conflict in this situation.

**Comment by brandboat** [comment]
> @brandboat the secret name to keep VMs is re-used and can cause conflict in this situation.

I see, I'm going to reimplement https://github.com/harvester/harvester/issues/4005, and store the info of running vm before upgrade in Upgrade CRD instead of secret to avoid this kind of awkward scenario.

**Comment by w13915984028** [comment]
@bk201 It is okay to move to next release, and better to mention this on document, suggest user to do some tests and monitoring after each upgrade. Some users may prefer to upgrade a series of versions in a row.

**Comment by ihcsim** [comment]
@w13915984028 @starbops @brandboat It seems to me the easiest way to ensure a new upgrade gets blocked by the validator as early as possible, while the post-upgrade cleanup is happening, is to add another label to the upgrade object [here](https://github.com/harvester/harvester/blob/b2169056102dee6867b3d86b3f82586a69818f9a/pkg/controller/master/upgrade/common.go#L146-L150) to indicate that cleanup is in-progress. Obviously, once clean-up is done, we will need to remove the label. This ensures we don't have to change any of the existing code around the upgrade's object conditions and `harvesterhci.io/upgradeState` labeling.

Alternately, we can also consider updating the validator to [check for resources](https://github.com/harvester/harvester/blob/b2169056102dee6867b3d86b3f82586a69818f9a/pkg/webhook/resources/upgrade/validator.go#L155) like the `repo` VM, purge-able images, any `cleanup` plans, or even the `harvesterhci.io/image-cleanup-plan-completed` annotation. All of these leave a window of time where a new upgrade could still be started.

Lastly, my least preferred option is to consider adding a new condition to indicate that post-upgrade cleanup is in-progress. It means the code needs to be updated to defer setting the success condition to after the clean up, if it completed successfully. I don't like this because technically, the upgrade already completed successfully. If the cleanup failed, user can't re-run the upgrade, and what state should we set the upgrade's condition to? 

LMKWYT.

**Comment by brandboat** [comment]
@ihcsim I think adding a new label should be sufficient. I also agree that introducing a new condition/status for the upgrade would only complicate the flow. Since the upgrade v2 work is still in progress, I’d like to hear @starbops’ opinion - do you see any potential issues with the label approach?

**Comment by starbops** [comment]
All of these are because introducing new phases to the upgrade flow is not an easy task, so we tend to add additional logic to the flow before or after specific phases. Ideally, there should be no more tasks being executed after the upgrade has ended, i.e., the `Completed` condition being either `True` or `False`. We aim to improve this by making it a more structured phase runner in the upgrade v2 enhancement, so that people can add new phases and handlers more easily. Upgrade v2 aside, to fix the issue mentioned in the ticket, I believe it's reasonable, given the scope of the work and the time being devoted, to go with the labeling route for the fix.

**Comment by asc5543** [comment]
Test fail, the upgrade stuck even in `Upgrading system service`.
<img width="2558" height="1318" alt="Image" src="https://github.com/user-attachments/assets/64a4d299-cdc0-4209-b532-08c2cb3534ff" />

SB: [supportbundle_e8393fea-d9c5-412d-94d7-d85d38485c99_2025-10-30T05-48-54Z.zip](https://github.com/user-attachments/files/23226184/supportbundle_e8393fea-d9c5-412d-94d7-d85d38485c99_2025-10-30T05-48-54Z.zip)

It seems like block by https://github.com/harvester/harvester/issues/9349

**Comment by asc5543** [comment]
# Test Case 1 - Regression Test
## Test result
Test PASS

## Environment
* Harvester ISO version: `v1.6.0` -> `v1.7.0-rc1`
* Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `1 node Baremetel`


## Test Scenario
### Preparation
Prepare the v1.7.0-rc1 or upgrade

1. Prepare the v1.7.0-rc1 ISO file
1. <details> <summary> Prepare the version.yaml file </summary>

    ```
    apiVersion: harvesterhci.io/v1beta1
    kind: Version
    metadata:
      name: v1.7.0-rc1
      namespace: harvester-system
    spec:
      isoChecksum: 'a7b3e4d38d81035af535390df079a6db1adc4bd34a7e6266f7e8ff709b5a26a1c612fb1fe9a7fe35ca598abe46f83323bb92cd9607c4fc70cfb2e37ba368126c'
      isoURL: http://<lab-server>/iso/v1.7.0-rc1/harvester-v1.7.0-rc1-amd64.iso
      releaseDate: '20251105'
    ```

   </details>

1. <details> <summary> Create a version object. </summary>

    ```
    # kubectl create -f version.yaml
    version.harvesterhci.io/v1.7.0-rc1 created
    ```

   </details>

1. <details>
   <summary> Confirm the version is ready
   </summary>

    ```
    # kubectl -n harvester-system get versions
    NAME         ISO-URL                                                                    RELEASEDATE            MINUPGRADABLEVERSION
    v1.7.0-rc1   http://<lab-server>/iso/v1.7.0-rc1/harvester-v1.7.0-rc1-amd64.iso            20251105               
    ```

   </details>

### Test Steps
1. <details>
   <summary> ✔ Trigger upgrade from the Harvester UI
   </summary>
  
    <img width="2494" height="1306" alt="Image" src="https://github.com/user-attachments/assets/641e3af2-d78f-432e-b90b-985ef05419d0" />
    <img width="2494" height="1306" alt="Image" src="https://github.com/user-attachments/assets/15448e7e-34f8-4b85-b8e1-48c41695a08b" />

   </details>

1. <details>
   <summary> ✔ Identify the Upgrade resource name, and set as variable
   </summary>

    ```
    # kubectl -n harvester-system get upgrades -lharvesterhci.io/latestUpgrade=true -oname
    upgrade.harvesterhci.io/hvst-upgrade-9lr7s
    # upgrade_name=`kubectl -n harvester-system get upgrades -lharvesterhci.io/latestUpgrade=true -oname`
    ```

   </details>

1. <details>
   <summary> ✔ Once the upgrade starts, issue a wait command (for 60 mins) to wait for the cleanup to complete(the wait command will need to be restarted after the node is upgraded and rebooted)
   </summary>

    ```
    kubectl -n harvester-system wait --for=jsonpath='{.metadata.labels.harvesterhci\.io/upgradeCleanup}=Succeeded' "${upgrade_name}" --timeout=60m
    ```

    <img width="2494" height="1306" alt="Image" src="https://github.com/user-attachments/assets/faae7cd1-2888-4ea6-9581-ab2239a80ac5" />

    After reboot
    <img width="1230" height="1174" alt="Image" src="https://github.com/user-attachments/assets/79ff9e7a-483e-4090-836b-43c583948fcf" />

    ```
    # kubectl -n harvester-system wait --for=jsonpath='{.metadata.labels.harvesterhci\.io/upgradeCleanup}=Succeeded' "${upgrade_name}" --timeout=60m
    upgrade.harvesterhci.io/hvst-upgrade-9lr7s condition met
    ```
    
   </details>

1. <details>
   <summary> ✔ Once the wait is over, confirm that the Upgrade resource is labeled
   </summary>

    ```
    # kubectl -n harvester-system get "${upgrade_name}" -ojsonpath='{.metadata.labels.harvesterhci\.io/upgradeCleanup}'
    Succeeded
    ```

   </details>

1. <details>
   <summary> ✔ Check for post-upgrade clean up start and complete logs
   </summary>

    ```
    # kubectl -n harvester-system logs deployment/harvester --all-pods=true | grep -i "post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:27:04Z" level=info msg="starting post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="starting post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="successfully completed post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="starting post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="post-upgrade cleanup already completed"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="starting post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="successfully completed post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="starting post-upgrade cleanup"
    [pod/harvester-7fbf7cd698-t5kfg/apiserver] time="2025-11-06T02:29:36Z" level=info msg="post-upgrade cleanup already completed"

    ```

   </details>

**Comment by asc5543** [comment]
# Test Case 2 - Assert Validating Webhook New Admission Rule
## Test result
Test PASS, the conflict will show

## Environment
* Harvester ISO version: `v1.6.0` -> `v1.7.0-rc1`
* Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `1 node via iPXE`


## Test Scenario
### Preparation
Prepare the v1.7.0-rc1 or upgrade

1. Prepare the v1.7.0-rc1 ISO file
1. <details> <summary> Prepare the version.yaml file </summary>

    ```
    apiVersion: harvesterhci.io/v1beta1
    kind: Version
    metadata:
      name: v1.7.0-rc1
      namespace: harvester-system
    spec:
      isoChecksum: 'a7b3e4d38d81035af535390df079a6db1adc4bd34a7e6266f7e8ff709b5a26a1c612fb1fe9a7fe35ca598abe46f83323bb92cd9607c4fc70cfb2e37ba368126c'
      isoURL: http://<lab-server>/v1.7.0-rc1/harvester-v1.7.0-rc1-amd64.iso
      releaseDate: '20251105'
    ```

   </details>

1. <details> <summary> Create a version object. </summary>

    ```
    # kubectl create -f version.yaml
    version.harvesterhci.io/v1.7.0-rc1 created
    ```

   </details>

1. <details>
   <summary> Confirm the version is ready
   </summary>

    ```
    # kubectl -n harvester-system get versions
    NAME         ISO-URL                                                                    RELEASEDATE            MINUPGRADABLEVERSION
    v1.7.0-rc1   http://<lab-server>/iso/v1.7.0-rc1/harvester-v1.7.0-rc1-amd64.iso            20251105               
    ```

### Test Steps
1. <details>
   <summary> ✔ Trigger upgrade from the Harvester UI
   </summary>  

    <img width="1276" height="1328" alt="Image" src="https://github.com/user-attachments/assets/2fb143d4-41f1-421b-ad1c-54d565b0e02c" />
    <img width="1276" height="1328" alt="Image" src="https://github.com/user-attachments/assets/4020c430-abce-4f99-b167-4511567ff136" />

   </details>

1. <details>
   <summary> ✔ Identify the Upgrade resource name, and set as variable
   </summary>

    ```
    # kubectl -n harvester-system get upgrades -lharvesterhci.io/latestUpgrade=true -oname
    upgrade.harvesterhci.io/hvst-upgrade-klmcl
    # upgrade_name=`kubectl -n harvester-system get upgrades -lharvesterhci.io/latestUpgrade=true -oname`
    ```

   </details>

1. <details>
   <summary> ✔ Once the upgrade starts, issue a wait command (for 60 mins) to wait for the cleanup to start and then attempt to start another concurrent upgrade
   </summary>

    ```
    kubectl -n harvester-system wait --for=jsonpath='{.metadata.labels.harvesterhci\.io/upgradeCleanup}=Pending' "${upgrade_name}" --timeout=60m && cat <<EOF | kubectl create -f -
    apiVersion: harvesterhci.io/v1beta1
    kind: Version
    metadata:
      name: v1.7.0-rc5
      namespace: harvester-system
    spec:
      isoChecksum: 'a7b3e4d38d81035af535390df079a6db1adc4bd34a7e6266f7e8ff709b5a26a1c612fb1fe9a7fe35ca598abe46f83323bb92cd9607c4fc70cfb2e37ba368126c'
      isoURL: http://192.168.123.1:8080/v1.7.0-rc1/harvester-v1.7.0-rc1-amd64.iso
      releaseDate: '20251105'
    ---
    apiVersion: harvesterhci.io/v1beta1
    kind: Upgrade
    metadata:
      generateName: v1.7.0-rc5
      namespace: harvester-system
    spec:
      image: ""
      logEnabled: true
      version: v1.7.0-rc5
    EOF
    ```

    <img width="2549" height="1328" alt="Image" src="https://github.com/user-attachments/assets/9ac9076d-efb4-4daa-a56f-9851dbf1c285" />

   </details>

1. <details>
   <summary> ✔ Expect the webhook to reject the upgrade
   </summary>

    ```
    upgrade.harvesterhci.io/hvst-upgrade-klmcl condition met
    version.harvesterhci.io/v1.7.0-rc5 created
    Error from server (Conflict): error when creating "STDIN": admission webhook "validator.harvesterhci.io" denied the request: cannot proceed until the following upgrades completed their cleanup process: hvst-upgrade-klmcl
    ```

   </details>
