### ISSUE TITLE
[BUG] failure if VM name is not RFC 1123 compliant in OpenStack

### ISSUE THREAD

**Issue by belgaied2** [harvester/harvester#6673]
If the VM name is OpenStack is not compliant with RFC 1123, we have the following behaviour: 
- if the `virtualMachineName` in the `virtualmachineimport` resource uses the above name, the VM Import Controller fails explicitly and early. This failure is not necessary, because OpenStack supports non-compliant names. VM Import Controller should handle these names by modifying them. This is also because the user, when he sees that will probably try to work it around by using the uuid of the instance instead.
- If the `virtualMachineName` uses a UUID, the VM Import Controller will first not detect the problem, but would fail long afterwards, when trying to create the VM (because it does not change the VM or the VM volume name).

VM Import Controller should have proper handling of name conversion from non-RFC 1123 compliant to compliant. This should also be documented.

**Comment by votdev** [comment]
Will be fixed by https://github.com/harvester/vm-import-controller/pull/42.

**Comment by votdev** [comment]
The issue will be solved by https://github.com/harvester/vm-import-controller/pull/42.

**Comment by votdev** [comment]
Issues that are also involved:
- https://github.com/harvester/harvester/issues/6500
- https://github.com/harvester/harvester/issues/6505

**Comment by irishgordo** [comment]
@votdev for:

```bash

╭─mike at suse-workstation-team-harvester in ~/Projects/v150-vm-import-stuff
╰─○ openstack server list --os-cloud openstack 
Password: 
+--------------------------------------+-------------+---------+-----------------------+--------------------------+----------+
| ID                                   | Name        | Status  | Networks              | Image                    | Flavor   |
+--------------------------------------+-------------+---------+-----------------------+--------------------------+----------+
| 7b60cf85-bc59-4e8a-aad7-8fa48937ae19 | foo-Bar     | ACTIVE  | shared=192.168.233.93 | N/A (booted from volume) | m1.nano  |
| b3693d06-8135-4c7c-b3ea-d37b2cc6fb8f | cirros-tiny | SHUTOFF | shared=192.168.233.13 | N/A (booted from volume) | m1.tiny  |
| 13ad0b6d-d7b9-4bcc-a9c9-e0a5c78ecd8e | testjammy   | SHUTOFF | shared=192.168.233.90 | N/A (booted from volume) | m1.small |

```

I'm noticing trying to bring across the VM by UUID is causing to trigger `virtualMachineImportInvalid`:

w/ the manifest of:
```
Name:         cirros-tiny-uuid                                                                                                                                                                                     
Namespace:    default                                                                                                                                                                                              
Labels:       <none>                                                                                                                                                                                               
Annotations:  <none>                                                                                                                                                                                               
API Version:  migration.harvesterhci.io/v1beta1                                                                                                                                                                    
Kind:         VirtualMachineImport                                                                                                                                                                                 
Metadata:                                                                                                                                                                                                          
  Creation Timestamp:  2025-03-16T22:08:19Z                                                                                                                                                                        
  Generation:          1                                                                                                                                                                                           
  Resource Version:    6338410                                                                                                                                                                                     
  UID:                 4e13f988-70cd-4cff-b953-bfe327312793                                                                                                                                                        
Spec:                                                                                                                                                                                                              
  Network Mapping:                                                                                                                                                                                                 
    Destination Network:  default/vlan2011                                                                                                                                                                         
    Source Network:       shared                                                                                                                                                                                   
  Source Cluster:                                                                                                                                                                                                  
    API Version:         migration.harvesterhci.io/v1beta1                                                                                                                                                         
    Kind:                OpenstackSource                                                                                                                                                                           
    Name:                mike-demo-2023-stable                                                                                                                                                                     
    Namespace:           default                                                                                                                                                                                   
  Virtual Machine Name:  b3693d06-8135-4c7c-b3ea-d37b2cc6fb8f                                                                                                                                                      
Status:                                                                                                                                                                                                            
  Import Status:  virtualMachineImportInvalid                                                                                                                                                                      
Events:           <none>  
``` 

Any ideas?
I'm still believing that the spec.virtualMachineName, will be the UUID from the VM running in OpenStack

**Comment by irishgordo** [comment]
@votdev this all looks good on v1.5.0-rc1

Testing manifest was:
```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: cirros-tiny
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan2011"
  sourceCluster: 
    name: mike-demo-2024-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
#---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: cirros-tiny-uuidnew
  namespace: default
spec: 
  virtualMachineName: "a944a663-293c-49ad-a4d7-9c8a448ebe59"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan2011"
  sourceCluster: 
    name: mike-demo-2024-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
#a---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: foo-bar
  namespace: default
spec: 
  virtualMachineName: "foo-Bar"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/vlan2011"
  sourceCluster: 
    name: mike-demo-2024-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-test2
  namespace: default
spec: 
  virtualMachineName: "mr-test2"
  folder: "gmehta"
  networkMapping:
  - sourceNetwork: "vCenter-HA-VM-Network"
    destinationNetwork: "default/vlan2011"
  sourceCluster: 
    name: mike-vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```
Attaching also the tarball of logs from the controller.

[logcontent.tar.gz](https://github.com/user-attachments/files/19276410/logcontent.tar.gz)

Some initial issues were present due to RKE2 CoreDNS ConfigMap & RKE2 CoreDNS deployment modifications needed, due to our env.  As well as, switching to 2024 ver of OpenStack.

After those hiccups were fixed this works 😄 

Tracking in:
- https://github.com/rancherlabs/harvester-access-lab/issues/16

![Image](https://github.com/user-attachments/assets/24db9d2a-2975-4451-a8ff-a71c4d320056)
