### ISSUE TITLE
[OpenStack] Make timeout during waiting for `uploadImage` configurable

### ISSUE THREAD

**Issue by belgaied2** [harvester/harvester#6675]
In VM Import Controller, the timeout after which the VM Import Controller fails (when waiting for `uploadImage` on OpenStack) is hard-coded to 300s or 5min (30 iterations of a 10s wait loop). Code [here](https://github.com/harvester/vm-import-controller/blob/main/pkg/source/openstack/client.go#L39-L40).

This should be configurable because the `uploadImage` OpenStack API Call can take several dozens of minutes if not hours sometimes.

**Comment by irishgordo** [comment]
@votdev on v1.5.0-dev-20250203 I'm noticing an issue:
```yaml
Error from server (BadRequest): error when creating "openstack-main-creds-and-sources.yaml": OpenstackSource in version "v1beta1" cannot be handled as a OpenstackSource: strict decoding error: unknown field "spec.uploadImageRetryCount", unknown field "spec.uploadImageRetryDelay"
Error from server (BadRequest): error when creating "openstack-main-creds-and-sources.yaml": OpenstackSource in version "v1beta1" cannot be handled as a OpenstackSource: strict decoding error: unknown field "spec.uploadImageRetryCount", unknown field "spec.uploadImageRetryDelay"
Error from server (BadRequest): error when creating "openstack-main-creds-and-sources.yaml": OpenstackSource in version "v1beta1" cannot be handled as a OpenstackSource: strict decoding error: unknown field "spec.uploadImageRetryCount", unknown field "spec.uploadImageRetryDelay"
Error from server (BadRequest): error when creating "openstack-main-creds-and-sources.yaml": OpenstackSource in version "v1beta1" cannot be handled as a OpenstackSource: strict decoding error: unknown field "spec.uploadImageRetryCount", unknown field "spec.uploadImageRetryDelay"
```
with the deployment on the single node cluster of:
```yaml
Pod Template:                                                                                                                                                                              
  Labels:           app.kubernetes.io/instance=vm-import-controller                                                                                                                        
                    app.kubernetes.io/name=harvester-vm-import-controller                                                                                                                  
  Service Account:  harvester-vm-import-controller                                                                                                                                         
  Containers:                                                                                                                                                                              
   harvester-vm-import-controller:                                                                                                                                                         
    Image:      rancher/harvester-vm-import-controller:v0.4.1                                                                                                                              
    Port:       <none>                                                                                                                                                                     
    Host Port:  <none>                                                                                                                                                                     
    Limits:                                                                                                                                                                                
      cpu:     2                                                                                                                                                                           
      memory:  4Gi                                                                                                                                                                         
    Requests:                                                                                                                                                                              
      cpu:        500m                                                                                                                                                                     
      memory:     2Gi                                                                                                                                                                      
    Environment:  <none>                                                                                                                                                                   
    Mounts:                                                                                                                                                                                
      /tmp from storage (rw)                                                                                                                                                               
  Volumes:                                                                                                                                                                                 
   storage:                                                                                                                                                                                
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)                                                                                                              
    Medium:                                                                                                                                                                                
    SizeLimit:  <unset>                                                                                                                                                                    
Conditions:                                                                                                                                                                                
  Type           Status  Reason                                                                                                                                                            
  ----           ------  ------                                                                                                                                                            
  Available      True    MinimumReplicasAvailable                                                                                                                                          
  Progressing    True    NewReplicaSetAvailable                                                                                                                                            
OldReplicaSets:  <none>                                                                                                                                                                    
NewReplicaSet:   harvester-vm-import-controller-fdc8ccdc6 (1/1 replicas created)                                                                                                           
Events:          <none>                                                                                                                                                                    
                                                     
```
