### ISSUE TITLE
add ISO image unmount action when CD-ROM disks is attached

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#67]
**Description:**
When the user chooses to boot MV from the `.iso` image by default the CD-ROM will be set as the 1st bootable disk in its VM config if the root disk is empty, and after the OS is installed successfully we should allow unmounting the CR-ROM disk easily through the action handler.

manual process:
1. confirm the OS is installed successfully to the VM.
1. kubectl edit vm and remove the `cdrom` disk and volume.
1. delete the VMI to reboot it.
1. check the VM is running and only the `root-disk` is enabled.

example of YAML:
1. before remove
```YAML
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: gc-ubuntu-server
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
      name: gc-simple-iso
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        http:
          url: http://172.16.0.254:8080/ubuntu-18.04.4-live-server-amd64.iso
  - metadata:
      name: gc-simple-root
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        blank: {}
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - cdrom:
              bus: sata
              readonly: true
            name: cdrom-disk
            bootOrder: 2
          - disk:
              bus: virtio
            name: datavolumedisk1
            bootOrder: 1
        resources:
          requests:
            memory: 2048M
      volumes:
      - dataVolume:
          name: gc-simple-iso
        name: cdrom-disk
      - dataVolume:
          name: gc-simple-root
        name: datavolumedisk1
```

2. removed iso disk
```YAML
apiVersio: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: gc-ubuntu-server
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
      name: gc-simple-root
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        blank: {}
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      volumes:
      - dataVolume:
          name: gc-simple-root
        name: datavolumedisk1
```
