### ISSUE TITLE
[ENHANCEMENT] Cancel previous in progress build when there is new commit in a same PR

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#6711]
**Is your enhancement related to a problem? Please describe.**
If there is a new commit and previous in progress build has not finished yet, there will be multiple running workflows. We can cancel previous in progress build to save CI resources.

**Describe the solution you'd like**
Add this to `build.yml`:

```yml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(fromJson('["master", "v1.2", "v1.3", "v1.4", "v1.5"]'), github.ref) }}
```
