### ISSUE TITLE
[ENHANCEMENT] Harvester-cloud-provider allows user to mark more IPs as none-external IPs

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6751]
**Is your enhancement related to a problem? Please describe.**

HCP marks the node IPs as internal or external.

https://github.com/harvester/cloud-provider-harvester/blob/dc00bdbb4b2bc41e33054a439c65de4126bb4d0b/pkg/cloud-controller-manager/instance.go#L83

```
	providedNodeIP, ok := node.Annotations[api.AnnotationAlphaProvidedIPAddr]
...
					if networkInterface.IP == providedNodeIP {
						nodeAddr.Type = v1.NodeInternalIP
					} else {
						nodeAddr.Type = v1.NodeExternalIP
					}
```

In case the nodes (harveser VMs) have mor NICs and IPs, certain IPs may be used only for internal like for third storage provider, user does not want those IPs are marked as `external`.

**Describe the solution you'd like**

Allow user to add a Harvester specific annotation to the node and mark some IPs are also belongs to none-external IPs.

note: the marked IPs will not show on `INTERNAL-IP` or `EXTERNAL-IP`

**Describe alternatives you've considered**

**Additional context**

guest k8s nodes:
```
NAME                       STATUS   ROLES                       AGE     VERSION          INTERNAL-IP       EXTERNAL-IP     OS-IMAGE                      KERNEL-VERSION                 CONTAINER-RUNTIME
...
test3-worker-hmg25-nlhcc   Ready    worker                      3d18h   v1.30.4+rke2r1   192.168.254.149   192.168.48.89   Rocky Linux 9.4 (Blue Onyx)   5.14.0-427.18.1.el9_4.x86_64   containerd://1.7.20-k3s1
```

guest cluster node:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 192.168.254.149
    cluster.x-k8s.io/cluster-name: test3
    cluster.x-k8s.io/cluster-namespace: fleet-default
...
  name: test3-worker-hmg25-nlhcc
  resourceVersion: "246580"
  uid: 93566c37-240b-49b9-bced-877bdfd27bb6
spec:
  podCIDR: 10.42.5.0/24
  podCIDRs:
  - 10.42.5.0/24
  providerID: harvester://a380c72c-0b3a-4f8f-ad08-de68c6de28fa
status:
  addresses:
  - address: 192.168.254.149
    type: InternalIP
  - address: test3-worker-hmg25-nlhcc
    type: Hostname
  allocatable:
```

related backed Harvester VM:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"test3-worker-hmg25-nlhcc-disk-0-nzft7","creationTimestamp":null,"annotations":{"harvesterhci.io/imageId":"default/image-hcgkn"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"40Gi"}},"storageClassName":"longhorn-image-hcgkn","volumeMode":"Block"},"status":{}}]
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
...
          interfaces:
            - bridge: {}
              macAddress: 12:5f:45:0c:e5:c8
              model: virtio
              name: nic-0
            - bridge: {}
              macAddress: 1e:97:45:86:4e:f5
              model: virtio
              name: nic-1
...
      networks:
        - multus:
            networkName: default/vm-254
          name: nic-0
        - multus:
            networkName: default/net-48
          name: nic-1
...
```

The second IP `192.168.48.89` on node/VM is marked as `external`, but it is only used for internal storage.

**Comment by w13915984028** [comment]
Test plan:

(1) Import harvester to Rancher
(2) Prepare a couple of VM networks on Harvester
(3) Create a guest cluster with control + worker nodes/machines, let nodes have multi networks/interfaces;  observe below on guest k8s cluster
```
NAME                       STATUS   ROLES                       AGE     VERSION          INTERNAL-IP       EXTERNAL-IP     OS-IMAGE                      KERNEL-VERSION                 CONTAINER-RUNTIME
...
test3-worker-hmg25-nlhcc   Ready    worker                      3d18h   v1.30.4+rke2r1   192.168.254.149   192.168.48.89   Rocky Linux 9.4 (Blue Onyx)   5.14.0-427.18.1.el9_4.x86_64   containerd://1.7.20-k3s1
```
<del>
(4) Add annotations to the backend VM's, like
cloudprovider.harvesterhci.io/additional-internal-ips: "[\"192.168.48.89\", \"192.168.120.11\"]"
(5) Observe the guest cluster, the previously marked as `EXTERNAL-IP` will switch to `INTERNAL-IP` when it is in the annotations.
</del>

(4) Add annotations to the guest k8s cluster's NODE (not the HOST side VM), like
like
```
cloudprovider.harvesterhci.io/additional-internal-ips: '["192.168.48.89", "192.168.120.11]"'
```
(5) Re-place the `harvester-cloud-provider` POD on guest cluster
(6) Observe the guest cluster, the previously marked as `EXTERNAL-IP` will disappear from `EXTERNAL-IP` when it is in the annotations.

**Comment by TachunLin** [comment]
Verified on `v1.5.0-rc1` with Rancher `v2.11.0-alpha13`.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ After add new external IP to internal IPs list, the external IP would disappeared $~~$</summary>

  1. When RKE2 cluster already have an internal and external IP

  ```
  root@rke2-v1322-pool1-6j5bw-l9q8g:/var/lib/rancher/rke2/bin# ./kubectl get nodes -o wide
  NAME                           STATUS   ROLES                              AGE     VERSION          INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
  rke2-v1322-pool1-6j5bw-l9q8g   Ready    control-plane,etcd,master,worker   2d20h   v1.32.2+rke2r1   10.115.9.120   10.115.54.127   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  rke2-v1322-pool2-wb6kv-qh97m   Ready    worker                             2d20h   v1.32.2+rke2r1   10.115.9.119   10.115.54.128   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  ```

2. We add the external IP as an additional internal IP to the node by setting the annotation

  ```
  apiVersion: v1
  items:
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        alpha.kubernetes.io/provided-node-ip: 10.115.9.120
        cloudprovider.harvesterhci.io/additional-internal-ips: '["10.115.54.127"]'
        cluster.x-k8s.io/cluster-name: rke2-v1322
  ```

3. After we config the node and restart the harvester-cloud-provider pod
4. The external IP disappear and did not added to the internal IP list

  ```
  root@rke2-v1322-pool1-6j5bw-l9q8g:/var/lib/rancher/rke2/bin# ./kubectl get nodes -o wide
  NAME                           STATUS   ROLES                              AGE     VERSION          INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
  rke2-v1322-pool1-6j5bw-l9q8g   Ready    control-plane,etcd,master,worker   2d20h   v1.32.2+rke2r1   10.115.9.120   <none>          Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  rke2-v1322-pool2-wb6kv-qh97m   Ready    worker                             2d20h   v1.32.2+rke2r1   10.115.9.119   10.115.54.128   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  ```


 </details>


### Test Information
* Test Environment: Single node harvester on baremetal machine
* Harvester version: v1.5.0-rc1
* Rancher version: v2.11.0-alpha13

### Verify Steps
<details><summary> Set additional internal IP to RKE2 guest cluster </summary>

1. Import harvester to Rancher
2. Prepare a couple of VM networks on Harvester (vlan2012 and vlan2017)

  ![Image](https://github.com/user-attachments/assets/248d4ea9-b7c3-4793-8026-b1078c1409cc)
  
3. Create a guest cluster with control + worker nodes/machines, let nodes have multi networks/interfaces 


4. After RKE2 cluster running, access to each node machines 

5. Bring up the second NIC and request dhcp IP 
 
  ```
  $ ip link set enp2s0 up
  $ dhclient enp2s0
  ```

6. Ensure node machine can get two IP address 

  ![Image](https://github.com/user-attachments/assets/987ea610-a7da-4670-bd8d-d2509bf390da)
  
7. Check the guest cluster can get EXTERNAL and INTERNAL IPs

  ```
  root@rke2-v1322-pool1-6j5bw-l9q8g:/var/lib/rancher/rke2/bin# ./kubectl get nodes -o wide
  NAME                           STATUS   ROLES                              AGE     VERSION          INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
  rke2-v1322-pool1-6j5bw-l9q8g   Ready    control-plane,etcd,master,worker   2d20h   v1.32.2+rke2r1   10.115.9.120   10.115.54.127   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  rke2-v1322-pool2-wb6kv-qh97m   Ready    worker                             2d20h   v1.32.2+rke2r1   10.115.9.119   10.115.54.128   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  ```

8. Use kubectl edit node to add the external IP to the `additional-internal-ips` annotation 

  ```
  $ ./kubectl edit node
  
  cloudprovider.harvesterhci.io/additional-internal-ips: '"[\"10.115.54.127\"]"'
  
  ```

9. Check if the node can get additional internal ip

  ```
  ./kubectl get nodes -o wide
  ```

</details>

**Comment by TachunLin** [comment]
During the issue verification process, 

* We found when RKE2 cluster already have an internal and external IP

  ```
  root@rke2-v1322-pool1-6j5bw-l9q8g:/var/lib/rancher/rke2/bin# ./kubectl get nodes -o wide
  NAME                           STATUS   ROLES                              AGE     VERSION          INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
  rke2-v1322-pool1-6j5bw-l9q8g   Ready    control-plane,etcd,master,worker   2d20h   v1.32.2+rke2r1   10.115.9.120   10.115.54.127   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  rke2-v1322-pool2-wb6kv-qh97m   Ready    worker                             2d20h   v1.32.2+rke2r1   10.115.9.119   10.115.54.128   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  ```

* And add the external IP as an additional internal IP to the node by setting the annotation

  ```
  apiVersion: v1
  items:
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        alpha.kubernetes.io/provided-node-ip: 10.115.9.120
        cloudprovider.harvesterhci.io/additional-internal-ips: '["10.115.54.127"]'
        cluster.x-k8s.io/cluster-name: rke2-v1322
  ```

* After we config the node and restart the harvester-cloud-provider pod

* The external IP disappear and did not added to the internal IP list

  ```
  root@rke2-v1322-pool1-6j5bw-l9q8g:/var/lib/rancher/rke2/bin# ./kubectl get nodes -o wide
  NAME                           STATUS   ROLES                              AGE     VERSION          INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
  rke2-v1322-pool1-6j5bw-l9q8g   Ready    control-plane,etcd,master,worker   2d20h   v1.32.2+rke2r1   10.115.9.120   <none>          Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  rke2-v1322-pool2-wb6kv-qh97m   Ready    worker                             2d20h   v1.32.2+rke2r1   10.115.9.119   10.115.54.128   Ubuntu 20.04.6 LTS   5.4.0-193-generic   containerd://2.0.2-k3s2
  ```

* nodes yaml 

  [node3.txt](https://github.com/user-attachments/files/19286821/node3.txt)
  
* harvester-cloud-provider.log

  [harvester-cloud-provider4.log](https://github.com/user-attachments/files/19286844/harvester-cloud-provider4.log)

**Comment by w13915984028** [comment]
Thanks @TachunLin for the comprehensive test. After pair-testing, we found that the `INTERNAL-IP` is managed by k8s, even when we mark additional IP from `EXTERNAL-IP` to `INTERNAL-IP`, the IP just disappears from `EXTERNAL-IP`, but does not show on `INTERNAL-IP`.

The `status` of `nodes` from guest cluster are attached. I will discuss with the reporter about this limitation.

```
node1:
  status:
    addresses:
    - address: 10.115.9.120
      type: InternalIP
    - address: rke2-v1322-pool1-6j5bw-l9q8g
      type: Hostname
node2:
  status:
    addresses:
    - address: 10.115.9.119
      type: InternalIP
    - address: 10.115.54.128  // when we mark this a `internal`, it will not be shown on `node status InternalIP` but disappear from `ExternalIP`
      type: ExternalIP
    - address: rke2-v1322-pool2-wb6kv-qh97m
      type: Hostname
```
