### ISSUE TITLE
[ENHANCEMENT] Prevent Upgrade if there is VM Backup (VM Backup Schedule) Under Processing

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6754]
**Is your enhancement related to a problem? Please describe.**
While the VM Backup is under processing, it may occupy one LH VA ticket. This can cause the following VM operation (e.q. VM Live migration) to be blocked by LH VA webhook  https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/webhook/resources/volumeattachment/validator.go#L121-L124

**Describe the solution you'd like**
Prevent upgrade if there is VM Backup (VM Backup Schedule) under Processing

**Comment by w13915984028** [comment]
@WebberHuang1118 Another question:

When an upgrade is ongoing, it may take hours, will scheduled backup still process if the timer arrives?

**Comment by WebberHuang1118** [comment]
Hi @w13915984028 

PR https://github.com/harvester/harvester/pull/6755 will make sure all schedules are suspended before starting an upgrade.

**Comment by innobead** [comment]
> **Is your enhancement related to a problem? Please describe.** While the VM Backup is under processing, it may occupy one LH VA ticket. This can cause the following VM operation (e.q. VM Live migration) to be blocked by LH VA webhook [longhorn/longhorn-manager@`5ff1f83`/webhook/resources/volumeattachment/validator.go#L121-L124](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/webhook/resources/volumeattachment/validator.go#L121-L124)

Will the upgrade eventually happen after the backup is finished? What is the current result when encountering this issue?

**Comment by WebberHuang1118** [comment]
> > **Is your enhancement related to a problem? Please describe.** While the VM Backup is under processing, it may occupy one LH VA ticket. This can cause the following VM operation (e.q. VM Live migration) to be blocked by LH VA webhook [longhorn/longhorn-manager@`5ff1f83`/webhook/resources/volumeattachment/validator.go#L121-L124](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/webhook/resources/volumeattachment/validator.go#L121-L124)
> 
> Will the upgrade eventually happen after the backup is finished? What is the current result when encountering this issue?

According to my discussion with @starbops, the upgrade may have a timeout for VM live migration if the backup spends too much time. cc @starbops

**Comment by w13915984028** [comment]
Test report: **PASS**

(1) Set up a 2-node cluster with v1.4.0-rc3 ISO
(2) Create a VM
(3) Setup backup target to NFS server
(4) Backup the VM
(5) Click upgrade

The webhook denied the upgrade request:
![image](https://github.com/user-attachments/assets/557ce853-dea5-4d7d-9361-668160dfe041)

(6) Create vmbackup schedule, which happens per plan
```
kubectl get schedulevmbackup
NAME                   CRON          RETAIN   MAXFAILURE   SPECSUSPEND   SOURCE       SUSPENDED   FAILURE
svmbackup-vm1-ubuntu   14 15 * * *   8        4            false         vm1-ubuntu       
```
![image](https://github.com/user-attachments/assets/a275cca4-cb12-4e21-b085-1993ec78b9de)

(7) When a schedulevmbackup is running, click `upgrade`, the `upgrade` is blocked as well.

![image](https://github.com/user-attachments/assets/fc9f8701-97b6-43b5-b9b6-813d0fabe059)

(8) When schedule is active, but no running instances (timer is not reached), the upgrade is also blocked.

![image](https://github.com/user-attachments/assets/ed36dbba-0713-413e-931c-0a008a57f109)

The schedule will run the next cron job after ~24 hours, but the webhook still denied the upgrade.

```
apiVersion: v1
items:
- apiVersion: harvesterhci.io/v1beta1
  kind: ScheduleVMBackup
..
  spec:
    cron: 19 15 * * *
    maxFailure: 4
    retain: 8
    suspend: false
    vmbackup:
      source:
        apiGroup: kubevirt.io
        kind: VirtualMachine
        name: vm1-ubuntu
      type: backup
  status:
    conditions:
    - lastUpdateTime: "2024-10-22T15:36:27Z"
      status: "False"
      type: BackupSuspend
```

This topic is tracked via https://github.com/harvester/harvester/issues/6848
