### ISSUE TITLE
[ENHANCEMENT] Refactor the `canMigrate` condition check on vmi

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6843]
**Is your enhancement related to a problem? Please describe.**

Harvester assumes a VM is migratable based on the condition of `NodeSelector`, and then render the `migration` action button on the UI.

https://github.com/harvester/harvester/blob/d0d234b5d8f434301111acef85370cc41972e202/pkg/api/vm/formatter.go#L246

```
	// The VM is set to run on a specific node
	if vmi.Spec.NodeSelector != nil && vmi.Spec.NodeSelector[corev1.LabelHostname] != "" {
		return false
	}
```

This is broken (not migratable VM has the menu `migrate`):
(1) If the nodeSelector is forgotten not set, like https://github.com/harvester/harvester/issues/6648; or the possible situation observed in PR https://github.com/harvester/harvester/pull/6836
(2) If the nodeSelector is not `LabelHostname` but other labels
(3) the `nodedrain_controller` checks more conditions on `FindNonMigratableVMS`

https://github.com/harvester/harvester/blob/d0d234b5d8f434301111acef85370cc41972e202/pkg/controller/master/nodedrain/nodedrain_controller.go#L321
...

**Describe the solution you'd like**

Unify the VMI migratable condition check

**Describe alternatives you've considered**

Update the v1.4.0 documents about the known limitations.

**Additional context**

PR: https://github.com/harvester/harvester/pull/6839
Issue: https://github.com/harvester/harvester/issues/6509

**Comment by w13915984028** [comment]
example:

A VM has `migrate` button,

![image](https://github.com/user-attachments/assets/294135eb-097f-4425-a392-724f289f97e6)

It is pinned to some kind of nodes:

![image](https://github.com/user-attachments/assets/8d60dbc8-c363-41fb-9f13-c09e53a848e5)


```
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: vm3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - harv2
```

But after clicking `migrate` button, it shows:
![image](https://github.com/user-attachments/assets/6f4c7153-ffd6-4bf4-9325-31bb55f9922f)

**Comment by w13915984028** [comment]
a customized `nodeSelector` will break `migrate` condition check easily:


vm with a customized `nodeSelector` (via `kubectl` edit vm object)

```
    spec:
      affinity: {}
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-0
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 06:b8:d8:04:9e:8b
            masquerade: {}
            model: virtio
            name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 62m
            memory: 1365Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: vm2
      networks:
      - name: default
        pod: {}
      nodeSelector:
        test.io: test  /// customized label
```

Harvester shows `migrate` menu, and can select a node as target:

![image](https://github.com/user-attachments/assets/d2be3644-7702-42be-8d2d-95e8bb3db8e4)


But kubevirt vmi checks this VM as `migrationMethod: BlockMigration`.

```
status:
  activePods:
    f636e0a4-d08d-41ec-8457-fa25d6a93057: harv2
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-22T10:35:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable  // this condition is true
  currentCPUTopology:
    cores: 1
    sockets: 1
    threads: 1
  guestOSInfo: {}
  interfaces:
  - infoSource: domain
    ipAddress: 10.52.1.23
    ipAddresses:
    - 10.52.1.23
    mac: 06:b8:d8:04:9e:8b
    name: default
    queueCount: 1
  launcherContainerImageVersion: registry.suse.com/suse/sles/15.5/virt-launcher:1.2.2-150500.8.21.1
  machine:
    type: pc-q35-7.1
  memory:
    guestAtBoot: 2Gi
    guestCurrent: 2Gi
    guestRequested: 2Gi
  migrationMethod: BlockMigration // but method is BlockMigration
```

The `migration` will fail finally, if another node has no label `test.io:test`.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceMigration
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  creationTimestamp: "2024-10-22T11:03:04Z"
  generateName: vm3-
  generation: 1
  labels:
    kubevirt.io/vmi-name: vm3
  name: vm3-6r9hr
  namespace: default
  resourceVersion: "89306"
  uid: 68153015-a1f6-4ab9-85dd-29bce8024e97
spec:
  vmiName: vm3
status:
  migrationState:
    completed: true
    endTimestamp: "2024-10-22T11:01:38Z"
    migrationConfiguration:
      allowAutoConverge: false
      allowPostCopy: false
      bandwidthPerMigration: "0"
      completionTimeoutPerGiB: 800
      nodeDrainTaintKey: kubevirt.io/drain
      parallelMigrationsPerCluster: 5
      parallelOutboundMigrationsPerNode: 2
      progressTimeout: 150
      unsafeMigrationOverride: false
    migrationUid: 26f696a7-de09-462a-98d3-8cd239e81c12
    mode: PreCopy
    sourceNode: harv2
    sourcePod: virt-launcher-vm3-t59rq
    startTimestamp: "2024-10-22T11:01:34Z"
    targetDirectMigrationNodePorts:
      "37631": 49153
      "43845": 0
      "45905": 49152
    targetNode: harv41
    targetNodeAddress: 10.52.0.61
    targetNodeDomainDetected: true
    targetNodeDomainReadyTimestamp: "2024-10-22T11:01:38Z"
    targetPod: virt-launcher-vm3-sxwlq
  phase: Failed
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2024-10-22T11:03:04Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2024-10-22T11:03:04Z"
  - phase: Failed
    phaseTransitionTimestamp: "2024-10-22T11:08:04Z"
```
