### ISSUE TITLE
[BUG] Upgrade stuck on waiting harvester bundle (v1.3.2 -> v1.4 master build)

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6851]
**Describe the bug**

I see the upgrade is stuck on apply-manifest job when upgrading from v1.3.2 to master build:

```
enabled: true
managedchart.management.cattle.io/harvester configured
managedchart.management.cattle.io/harvester patched
managedchart.management.cattle.io/harvester-crd patched
Waiting for ManagedChart fleet-local/harvester from generation 2
Target version: 0.0.0-test-pr-6826-e086070e, Target state: ready
Current version: 0.0.0-test-pr-6826-e086070e, Current state: null, Current generation: 2
Sleep for 5 seconds to retry
Current version: 0.0.0-test-pr-6826-e086070e, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 0.0.0-test-pr-6826-e086070e, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
...

Sleep for 5 seconds to retry
Current version: 0.0.0-test-pr-6826-e086070e, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 0.0.0-test-pr-6826-e086070e, Current state: ErrApplied, Current generation: 4

```

The bundle status is:
```
  summary:
    desiredReady: 1
    errApplied: 1
    nonReadyResources:
    - bundleState: ErrApplied
      message: 'encountered 2 deletion errors. First is: admission webhook "validator.harvesterhci.io"
        denied the request: Internal error occurred: no route match found for DELETE
        /v1, Kind=Secret harvester-system/sh.helm.release.v1.harvester.v1'
      name: fleet-local/local
    ready: 0
  unavailable: 1
```

**To Reproduce**
1. Create a v1.3.2 cluster.
2. Upgrade to a maser build (I believe v1.4.0-rc3 is similar).
3. There is a chance to hit this issue.

**Expected behavior**

The upgrade should be smooth.

**Support bundle**

[supportbundle_19aaa896-fd99-4bec-8fe3-1b6ec00b690c_2024-10-22T15-49-19Z.zip](https://github.com/user-attachments/files/17484024/supportbundle_19aaa896-fd99-4bec-8fe3-1b6ec00b690c_2024-10-22T15-49-19Z.zip)

**Environment**
 - Harvester ISO version: d0d234b5d8f434301111acef85370cc41972e202
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

The workaround is to remove these part in the `harvester-validator` Validatingwebhookconfigurations

```
 - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - secrets
    scope: Namespaced
```
