### ISSUE TITLE
[FEATURE] write_files equivalent in harvester config

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#690]
**Is your feature request related to a problem? Please describe.**
I'd like to automatically configure a linux bonding for my harvester node.
I'm using the automatic installation for deploying harvester on my lab (https://github.com/rancher/harvester/blob/master/docs/automatic-installation.md) and looks like that's not possible to create the bonding automatically. 

I tried something like this: `kernel assets/harvester-vmlinuz-amd64 initrd=harvester-initrd-amd64 k3os.mode=install k3os.install.config_url=http://x.x.x.x/config.yaml harvester.install.automatic=true harvester.install.config_url=http://x.x.x.x/config-create.yaml console=tty1 console=ttyS0` but it doesn't work.

**Describe the solution you'd like**
It could be perfect to be able to create custom files through the harvester config. Mainly to update the `/var/lib/rancher/k3os/config.yaml` in my case.

**Comment by guangbochen** [comment]
Harvester has introduced a custom [configuration file](https://github.com/rancher/harvester/blob/master/docs/harvester-configuration.md) which is similar to the k3os config, let us know if the existing configuration file does not meet your expectation, an example can be found on https://github.com/harvester/ipxe-examples/tree/main/general.

**Comment by juadk** [comment]
> Harvester has introduced a custom [configuration file](https://github.com/rancher/harvester/blob/master/docs/harvester-configuration.md) which is similar to the k3os config, let us know if the existing configuration file does not meet your expectation, an example can be found on https://github.com/harvester/ipxe-examples/tree/main/general.

Hello, yes I'm aware of the harvester configuration file but I don't see how to create a custom file with it.
And yes I got inspired by the IPXE examples on Github.

I asked the question on slack and @gitlawr told me to open this issue because it is not possible to create a custom file with the harvester config.

**Comment by gitlawr** [comment]
So the initial request is to be able to configure network bonding. In k3os this is feasible using [custom config file](https://github.com/rancher/k3os/issues/457). Comparing with that, `write_files` and `run_cmd` are the missing parts in harvester configuration as far as I can tell.

**Comment by juadk** [comment]
> So the initial request is to be able to configure network bonding. In k3os this is feasible using [custom config file](https://github.com/rancher/k3os/issues/457). Comparing with that, `write_files` and `run_cmd` are the missing parts in harvester configuration as far as I can tell.

Exactly, our k3os custom file looks like this:
```
hostname: xxxxxx
k3os:
  k3sArgs:
  - agent
  - --flannel-iface
  - bond0
  labels:
    harvester.cattle.io/managed: "true"
  modules:
  - kvm
  - bonding
  - vhost_net
  ntpServers:
  - 0.suse.pool.ntp.org
  password: xxxxxx
  serverUrl: https://xxxxxx
  token: xxxxxx
boot_cmd:
- ip link add dev bond0 type bond
- ip link set dev eth0 down
- ip link set dev eth1 down
- ip link set dev bond0 down
- ip link set dev eth0 master bond0
- ip link set dev eth1 master bond0
- ip link set dev eth0 up
- ip link set dev eth1 up
- ip link set dev bond0 up
write_files:
- encoding: ""
  content: |-
    [General]
      NetworkInterfaceBlacklist=veth,eth1
      PreferredTechnologies=ethernet,wifi
      FallbackNameservers=9.9.9.9
      FallbackTimeservers=0.suse.pool.ntp.org
  owner: root:root
  path: /etc/connman/main.conf
  permissions: "0644"
```

**Comment by guangbochen** [comment]
depends on https://github.com/harvester/harvester/issues/581, let's review this when we have the new OS ready.

**Comment by guangbochen** [comment]
addressed via https://github.com/harvester/harvester-installer/pull/86,and you can test using the [master-head ISO image](https://releases.rancher.com/harvester/master/harvester-amd64.iso).

**Comment by juadk** [comment]
Tested successfully in build `master-6d5c7df2-head` ​with ISO mode.
I was able to create a file with the following configuration:

```
token: token
os:
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbeUa9A7Kee+hcCleIXYxuaPksn2m4PZTd4T7wPcse8KbsQfttGRax6vxQXoPO6ehddqOb2nV7tkW2mEhR50OE7W7ngDHbzK2OneAyONYF44bmMsapNAGvnsBKe9rNrev1iVBwOjtmyVLhnLrJIX+2+3T3yauxdu+pmBsnD5OIKUrBrN1sdwW0rA2rHDiSnzXHNQM3m02aY6mlagdQ/Ovh96h05QFCHYxBc6oE/mIeFRaNifa4GU/oELn3a6HfbETeBQz+XOEN+IrLpnZO9riGyzsZroB/Y3Ju+cJxH06U0B7xwJCRmWZjuvfFQUP7RIJD1gRGZzmf3h8+F+oidkO2i5rbT57NaYSqkdVvR6RidVLWEzURZIGbtHjSPCi4kqD05ua8r/7CC0PvxQb1O5ILEdyJr2ZmzhF6VjjgmyrmSmt/yRq8MQtGQxyKXZhJqlPYho4d5SrHi5iGT2PvgDQaWch0I3ndEicaaPDZJHWBxVsCVAe44Wtj9g3LzXkyu3k= root@admin
  password: rancher
  write_files:
  - encoding: ""
    content: test content
    owner: root
    path: /etc/test.txt
    permissions: '0755'
install:
  mode: create
  mgmt_interface: eth0
```
I will try to configure the bonding even if we are about to change the OS.
