### ISSUE TITLE
[ENHANCEMENT] StorageNetwork should associated with Longhorn RWX Storage Network Support

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6910]
**Is your enhancement related to a problem? Please describe.**
After Longhorn v1.7, Longhorn RWX volume supports the Storage Network.
We cannot configure it on the Harvester Setting. It would be better to add a new option when we enable the storage network on the Harvester side. (e.g. enable RWX storage network)

**Describe the solution you'd like**
Add the new option for RWX volume storage network with the storage network setting on the harvester side.

**Describe alternatives you've considered**
None

**Additional context**
https://longhorn.io/docs/1.7.0/advanced-resources/deploy/storage-network/#setting-storage-network-for-rwx-volumes

**Comment by innobead** [comment]
The storage network is currently required for RWX. We must remove this dependency before allowing users to enable or disable the storage network.

- https://github.com/longhorn/longhorn/issues/10269
- https://github.com/harvester/harvester/issues/7218

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/10269 is ready in Longhorn 1.11.

**Comment by TachunLin** [comment]
Related document:
* Test plan:  https://github.com/harvester/harvester/pull/10256#issue-4105234023
* HEP: https://github.com/harvester/docs/pull/990

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.8.0-rc2` and `v1.8.0-rc4` with Rancher v2.14.0. Close this issue.

### Result:  Harvester side

#### Test Group 1: Default state & deletion protection
<details><summary>$\color{green}{\textsf{PASS}}$ Check rwx-network default Settings  $~~$</summary>


1. `rwx-network` default value is {"share-storage-network":false}

  ```
  {
    "share-storage-network": false
  }
  ```
  
  <img width="525" height="202" alt="Image" src="https://github.com/user-attachments/assets/7c770062-79bc-4069-bec1-73bd0850e834" />



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Check rwx-network delete protection  $~~$</summary>


1. Delete `rwx-network` with kubectl will prompt MethodNotAllowed error

  ```
  harvester-node-0:~ # kubectl delete setting rwx-network
  Error from server (MethodNotAllowed): admission webhook "validator.harvesterhci.io" denied the request: Disallow delete setting name rwx-network
  ```



 </details>

#### Test Group 3: Dedicated mode with overlap validation

<details><summary>$\color{green}{\textsf{PASS}}$ Configure rwx-network in dedicated mode to test functionality  $~~$</summary>

1. Enable rwx-network setting
2. And set to `Dedicated Storage Network`
3. Provide the following settings

  ```
  {
    "share-storage-network": false,
    "network": {
      "vlan": 2011,
      "clusterNetwork": "mgmt",
      "range": "172.16.0.0/24"
    }
  }
  ```

4. Create a new storage class `longhorn-rwx` 

  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-rwx
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "3"
    staleReplicaTimeout: "2880"
    fromBackup: ""
    fsType: "ext4"
    nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  ```
  
  <img width="1347" height="518" alt="Image" src="https://github.com/user-attachments/assets/17bbfd17-89a0-4e20-8459-d34698a08a5e" />

5. Apply the following manifest to create a temporary PVC and pod

  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rwx-test-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn-rwx
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: rwx-test-pod
  spec:
    containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "echo RWX OK > /data/test.txt && cat /data/test.txt && sleep 3600"]
        volumeMounts:
          - name: data
            mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rwx-test-pvc
  ```

6. Ensure the pod reaches Running state and the volume is mounted successfully

```
hp-41-multindclstr-node-a:~ # kubectl get pod rwx-test-pod
NAME           READY   STATUS    RESTARTS   AGE
rwx-test-pod   1/1     Running   0          68s
```

7. Access the pod and test the read/write function 

  ```
  <<K9s-Shell>> Pod: default/rwx-test-pod | Container: test 
  / # cd /data/
  /data # ls
  lost+found  test.txt
  /data # cat test.txt
  RWX OK
  /data # vi test.txt
  /data # cat test.txt
  RWX OK
  Write RWX1
  ```


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Change rwx-storage IP Range to non-overlapping while having rwx volume attached  $~~$</summary>

  1. It will be rejected with a message listing the attached volume(s).
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: there are RWX volumes not in detached state: pvc-c2600ea7-ecc4-4e6f-b982-c5c497901a24
  ```
  
  <img width="1354" height="787" alt="Image" src="https://github.com/user-attachments/assets/090219f2-b69a-4ffa-9337-3e42bcaf1b77" />


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Change rwx-storage IP Range to overlapping while having rwx volume detached $~~$</summary>

  1. It will be rejected with an overlap error naming the conflicting setting.
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: rwx-network: the network configuration is overlapped with storage-network
  ```
  
  <img width="1349" height="730" alt="Image" src="https://github.com/user-attachments/assets/02030b36-8ef5-4115-a66c-5606b746629b" />

 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Change storage-network IP Range to overlapping while having rwx volume detached $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true.
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: exclude range 10.115.16.1/32 do not overlap include range 172.16.0.0/24
  ```

  <img width="1348" height="732" alt="Image" src="https://github.com/user-attachments/assets/8c4de590-dcf0-420e-8e2a-337835fe9d9b" />


 </details>


#### Test Group 4: Mode transitions & cleanup

<details><summary>$\color{green}{\textsf{PASS}}$ Switch rwx-network from dedicated to shared mode  $~~$</summary>

1. Can correctly switch rwx-network from dedicated to shared mode
2. Check the dedicated NAD is deleted


  https://github.com/user-attachments/assets/0518c92f-a4d2-46f3-b31e-1bfd7d49fbf7
  


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Switch rwx-network from shared to dedicated mode  $~~$</summary>

1. Can correctly switch rwx-network from shared to dedicated mode
2. Check a new dedicated NAD is created
  

  https://github.com/user-attachments/assets/349412a6-8172-4ce7-8a44-edf86dc3be35


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Reset rwx-network to {"share-storage-network": false} (no network) $~~$</summary>

  1. Check the dedicated NAD is removed and Longhorn's RWX network setting is cleared.
  

  https://github.com/user-attachments/assets/14bce1ea-223b-41b4-8c7e-e46efeedca89
  

 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Attempt to manually delete the NAD referenced by rwx-network $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true.
  
  ```
  hp-41-multindclstr-node-a:~ # kubectl delete network-attachment-definitions rwx-network-j7fr6 -n harvester-system
  Error from server (BadRequest): admission webhook "validator.harvesterhci.io" denied the request: cannot delete NetworkAttachmentDefinition harvester-system/rwx-network-j7fr6 which is used by Harvester setting 'rwx-network'
  ```

  https://github.com/user-attachments/assets/cb63ac5e-e937-4bcb-ba88-df5aa0ec0f13


 </details>



#### Test Group 2: Share mode with blocking conditions

<details><summary>$\color{green}{\textsf{PASS}}$ Configure rwx-network in shared mode to test functionality  $~~$</summary>

1. Enable rwx-network setting
2. And set to `Shared Storage Network`
  ```
  {
    "share-storage-network": true
  }
  ```

  <img width="1347" height="728" alt="Image" src="https://github.com/user-attachments/assets/dac2774d-17c2-45b1-9f29-219a66275231" />

3. Check Longhorn's endpoint-network-for-rwx-volume points to the same NAD as storage-network.

  <img width="1574" height="282" alt="Image" src="https://github.com/user-attachments/assets/7e023f20-a20d-4a4d-a560-692ffcf62413" />

4. Create a new storage class `longhorn-rwx` 

  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-rwx
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "3"
    staleReplicaTimeout: "2880"
    fromBackup: ""
    fsType: "ext4"
    nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  ```
  
  <img width="1347" height="518" alt="Image" src="https://github.com/user-attachments/assets/17bbfd17-89a0-4e20-8459-d34698a08a5e" />

5. Apply the following manifest to create a temporary PVC and pod

  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rwx-test-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn-rwx
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: rwx-test-pod
  spec:
    containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "echo RWX OK > /data/test.txt && cat /data/test.txt && sleep 3600"]
        volumeMounts:
          - name: data
            mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rwx-test-pvc
  ```

6. Ensure the pod reaches Running state and the volume is mounted successfully

  ```
  hp-41-multindclstr-node-a:~ # kubectl get pod rwx-test-pod
  NAME           READY   STATUS    RESTARTS   AGE
  rwx-test-pod   1/1     Running   0          81s
  hp-41-multindclstr-node-a:~ # kubectl get pvc rwx-test-pvc
  NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
  rwx-test-pvc   Bound    pvc-5f979803-0963-4bc0-9e18-45b59554bb64   1Gi        RWX            longhorn-rwx   <unset>                 89s
  ```

7. Access the pod and test the read/write function 

```
<<K9s-Shell>> Pod: default/rwx-test-pod | Container: test 
/ # cd /data
/data # ls
lost+found  test.txt
/data # cat test.txt
RWX OK
/data # vi test.txt
/data # cat test.txt
RWX OK
shared mode
```


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Clear storage-network, then attempt to enable share mode $~~$</summary>

  1. It will be rejected with storage-network is not set
  

    ```
    admission webhook "validator.harvesterhci.io" denied the request: storage-network is not set
    ```

    <img width="1594" height="783" alt="Image" src="https://github.com/user-attachments/assets/8a75e26a-5fd2-49b9-addf-80bdea697330" />



 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ With share mode active, attempt to clear storage-network $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true
  

    <img width="1348" height="733" alt="Image" src="https://github.com/user-attachments/assets/b440faf2-35e3-4352-8f0e-244ec4c55069" />
    
    https://github.com/user-attachments/assets/20855f05-4e97-4176-a0ba-8e1f511c6a7e


 </details>


#### Test Group 5: share-storgae-network is set to true after Upgrade
<details><summary>$\color{green}{\textsf{PASS}}$ After upgrade to v1.8.0-rc5, check the default share-storgae-network is true   $~~$</summary>


1. With storage network setup and enable the Storage Network for RWX Volume Enabled


<img width="1917" height="1093" alt="Image" src="https://github.com/user-attachments/assets/61e0bf9e-d8d6-4ba1-81de-e9dfa73af590" />

https://github.com/user-attachments/assets/75e70507-db93-4577-8982-9d01285339a6


https://github.com/user-attachments/assets/3fac252d-36b7-4641-a785-3276abd2e9db


2. After upgrade from v1.7.1 to v1.8.0-rc5

  <img width="1593" height="785" alt="Image" src="https://github.com/user-attachments/assets/03f1cc51-df05-4deb-a79a-92c22b2a2138" />
  
  <img width="1599" height="794" alt="Image" src="https://github.com/user-attachments/assets/9772fc88-0a3c-414f-9fca-ea3087596e27" />

3. check `rwx-network` setting, the default value now is {"share-storage-network": `true`}

  <img width="1599" height="783" alt="Image" src="https://github.com/user-attachments/assets/354a1249-b3cd-4468-8928-24cd1ba2d609" />
  


 </details>


### Test Information
* Test Environment: Two nodes bare-metal machines
* Harvester version: v1.8.0-rc2 and v1.8.0-rc5
* Rancher version: v2.14

### Verify Steps
<details><summary>Test steps </summary>

  Refer to: https://github.com/harvester/harvester/pull/10256#issue-4105234023

</details>
