### ISSUE TITLE
[BUG] Files that should be unique per node (e.g. /etc/machine-id) are idential across all harvester nodes for a given release

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6911]
**Describe the bug**
Certain files in `/etc/` that should be unique per node, for example `/etc/machine-id`, `/etc/iscsi/initiatorname.iscsi` and `/etc/nvme/hostnqn` are included in the rootfs in the Harvester ISO. This means that they are identical on every single Harvester node installed from a given ISO image.

**To Reproduce**
1. Install Harvester v1.3.2 on as many nodes as you like.
2. Check the contents of  `/etc/machine-id`, `/etc/iscsi/initiatorname.iscsi` and `/etc/nvme/hostnqn`. Verify that these files contain `f93c751c5aa9e98da8a607da66d82d3c`, `InitiatorName=iqn.1996-04.de.suse:01:68c3e7cbc1a3` and `nqn.2014-08.org.nvmexpress:uuid:3b9c3277-1d37-4aef-a7eb-28c6aa232ffe` respectively.
3. Repeat for any other Harvester version.
4. Observe that for a given ISO image, these files are identical on all nodes installed from that image.

**Expected behavior**
These files have different contents on each individual Harvester node.

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: all of them
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): anything

**Additional context**
`/etc/machine-id` is meant to be unique per node because there's some externally visible things that might be generated based on it, and it not being unique could cause problems for this reason.

`/etc/iscsi/initiatorname.iscsi` and `/etc/nvme/hostnqn` need to be unique when accessing external storage via iSCSI or NVMe over fabrics.
- This shouldn't be an issue for Harvester v1.3.x and earlier which don't support this sort of thing anyway.
- I'm not sure if it's a problem for https://github.com/harvester/harvester/issues/5150 in Harvester v1.4.x, as iSCSI config in that case is handled in the system BIOS and picked up by ibft, and I don't know where the initiator name comes from in that scenario (need to verify).
- I don't know if it's a problem for VM access to external iSCSI based CSI storage.
- It will likely be a problem if future versions of Harvester support connecting the _host_ to arbitrary external iSCSI or NVMe-oF devices.

There are some strategies for handling `/etc/machine-id` described in https://manpages.opensuse.org/Tumbleweed/systemd/machine-id.5.en.html and https://systemd.io/BUILDING_IMAGES/

`/etc/iscsi/initiatorname.iscsi` and `/etc/nvme/hostnqn` are generated by the RPM postinstall scriptlets in the open-iscsi and nvme-cli packages respectively. `/etc/iscsi` _is_ in the persistent state paths, so theoretically editing this file at runtime would work, except that because it exists in the underlying persistent root partition, the original will be re-written on every boot (see https://github.com/rancher/elemental-toolkit/blob/v1.1.x/pkg/features/embedded/immutable-rootfs/usr/lib/dracut/modules.d/30elemental-immutable-rootfs/elemental-mount-layout.sh#L198)

Probably best to `rm /etc/machine-id /etc/iscsi/initiatorname.iscsi /etc/nvme/host*` from the rootfs during ISO build, make sure all those paths are in the list of persistent state paths, let systemd take care of `/etc/machine-id`, and duplicate the RPM postinstall scriptlets from open-iscsi and nvme-cli somewhere early in the boot to take care of the rest.

Workarounds include manually doing things like this on each node:

```
# cat /oem/99_iscsi_nvme.yaml
name: iSCSI and NVMe Configuration
stages:
  initramfs:
    - files:
      - path: /etc/iscsi/initiatorname.iscsi
        permissions: 384
        owner: 0
        group: 0
        content: |
          InitiatorName=iqn.1996-04.de.suse:harvester-node-0
      - path: /etc/nvme/hostnqn
        permissions: 420
        owner: 0
        group: 0
        content: |
          nqn.2014-08.org.nvmexpress:harvester-node-0
```
