### ISSUE TITLE
[BUG] vm-import-controller error

### ISSUE THREAD

**Issue by b-milescu** [harvester/harvester#6929]
Describe the bug
I have followed the steps in https://docs.harvesterhci.io/v1.4/advanced/addons/vmimport/. But the VM import fails.

1. Enabled the `vm-import-controller` plugin from add-ons in Harvester UI
2. Apply the VMware source CRD by specifying the VMware endpoint
  In our case, both Harvester and VMware environments are in the same subnet - 192.168.0.0/24
  Harvester UI: 192.168.0.69, Nodes: 192.168.0.113
  VMware: 192.168.0.250(vSphere) and 192.168.0.150 (esxi)

```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VmwareSource
metadata:
  name: vcsim
  namespace: default
spec:
  endpoint: "https://192.168.0.250/sdk"
  dc: "homelab"
  credentials:
    name: vsphere-credentials
    namespace: default
```

vCenter credentials are kept in vsphere-credentials

3. Apply the VM import CRD
```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: work
  namespace: default
spec:
  virtualMachineName: "work"
  folder: "/"
  networkMapping:
  sourceCluster:
    name: vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

4. Status
```
# kubectl get VmwareSource
NAME    STATUS
vcsim   clusterReady
```
```
# kubectl get virtualmachineimport.migration
NAME   STATUS
work   sourceReady
```
5. Logs
```
# kubectl logs -f -n harvester-system harvester-vm-import-controller-56cc769df4-nrtkf
time="2024-11-02T19:27:36Z" level=info msg="Importing client disk images ..." name=work namespace=default spec.virtualMachineName=work
time="2024-11-02T19:27:36Z" level=info msg="Powering off client VM ..." name=work namespace=default spec.virtualMachineName=work
time="2024-11-02T19:27:36Z" level=error msg="error syncing 'default/work': handler virtualmachine-import-job-change: error in poweroff call: error finding vm in PowerOffVirtualMachine: vm '/homelab/vm/work' not found, requeuing"
6. vSphere showing the VM to be imported 
```
![image](https://github.com/user-attachments/assets/6b3e7b72-937f-4dd6-8a4d-68dfceb307e1)

Environment

Harvester ISO version: [v1.4.0-rc4](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc4)
Underlying Infrastructure: Minisforum MS-01, 96GB RAM, 2TB nvme SSD

**Comment by ibrokethecloud** [comment]
are you able to please download https://github.com/vmware/govmomi/blob/main/govc/README.md
 and provide the output of 

```
govc find / -type m
```

**Comment by b-milescu** [comment]
Hey @ibrokethecloud  thanks for  chipping in!
Here is the output:
```
govc find / -type m
/homelab/vm/sensorz
/homelab/vm/Checkmk
/homelab/vm/Discovered virtual machine/work
/homelab/vm/VMware vCenter Server
```

I guess that if I change the folder in the VirtualMachineImport definition it will work :D.

LE:

Not working:
```
time="2024-11-03T12:32:15Z" level=info msg="Importing client disk images ..." name=work namespace=default spec.virtualMachineName=work
time="2024-11-03T12:32:15Z" level=info msg="Powering off client VM ..." name=work namespace=default spec.virtualMachineName=work
time="2024-11-03T12:32:15Z" level=error msg="error syncing 'default/work': handler virtualmachine-import-job-change: error in poweroff call: error finding vm in PowerOffVirtualMachine: cannot traverse type VirtualMachine, requeuing"
```

**Comment by ibrokethecloud** [comment]
the folder name needs to be `Discovered virtual machine` and i expect it would then work.

**Comment by b-milescu** [comment]
Worked! Thanks! That was an unusual case. That VM was migrated to ESXi maybe this is why it appeared this way.
```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: work
  namespace: default
spec:
  virtualMachineName: "work"
  folder: "/Discovered virtual machine/"
  networkMapping:
  sourceCluster:
    name: vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```
