### ISSUE TITLE
[ENHANCEMENT] Ability to have static Mac-addresses assigned to VF (SR-IOV) and trust enable on VFs

### ISSUE THREAD

**Issue by samueldewever** [harvester/harvester#6954]
**Is your enhancement related to a problem? Please describe.**

We are trying to see if we can run all our VNFs on Harvester
One of our VNF (SBC) is requiring SR-IOV for Media. Once we added the Sr-IOV interface, the system crashed. 
After troubleshooting with the VNF vendor, we concluded the following:

if "ens1" indicates the Physical Media port NIC on which VF "10" was assigned with NULL MAC address and such VF:10 assigned to guest VM. Then, for every reboot, a new MAC is assigned automatically and cause such mac mismatch issues which in turn causes the dpdk port mapping (mactab) and port init failures on the VNF.

The VF also need trust on instead of off

As per the standard of SR-IOV configuration provided by Intel documentation, we should configure the SR-IOV VFs with proper MAC address on the Host server using "ip" command.
For ex: ip link set ens1 vf 10 mac ee:07:94:7a:a7:81.

Referring to https://cdrdv2-public.intel.com/630211/630211-E810%20SR-IOV%20RHEL8%20ConfigGuide_Rev1.2.pdf

We manually assigned the MACs to the VF and put trust on ON to resolve the crashing of the VNF. This indeed resolves the issue for this VNF 

**Describe the solution you'd like**
Currently the VF get created. Mac addresses get assigned at boot (by libvirt)
The VF are standard spoof checking on, trust off. 

We should be able to to configure this settings per VF. Not only mac address but also spoof checking on/off and trust mode on/off

**Describe alternatives you've considered**
Making a script which manually change this at reboot. The issue is that the VF is recreated after reboot and I have nothing to trigger when this is completed. At the same time I don't know if this will be overwritten again at any other moment in time ? The VNF will always boot before I have made the changed and than crash. 

**Additional context**

**Comment by samueldewever** [comment]
@ibrokethecloud @bk201 Can you have a look in this. I will also request the enhancement officially via our Presales at Suse.

This is a blocker in our testings to be able to start using harvester as a production system.

If you could advase on a temporary workaround were we, via a script on the host, could change the settings via ip link statement and give us the confort that it will not be overwritten again as long the node is not rebooted, we would already have a temporary workaround which is acceptable.

**Comment by w13915984028** [comment]
@samueldewever 

You may try following solution:

https://rancher.github.io/elemental-toolkit/docs/customizing/stages/

1. Add a file to Harvester node /oem path manually, test until it works (change the file format/parameter and reboot the node), this is the place to run certain commands after the system is rebooted/...

```
network
This stage is executed when network is available

Example:

name: "Run something on boot"
stages:
   network:
     - name: "Setting"
       if: '[ ! -f "/run/cos/recovery_mode" ]'
       commands:
       - |

          # Network is available, do something..          

or:

name: "Run something on boot"
stages:
   reconcile:
     - name: "Setting"
       if: '[ ! -f "/run/sentinel" ]'
       commands:
       - |
          touch /run/sentinel          

```

2. (Optional) Consolidate and simplify it with a CloudInit CRD object.

Following examples shows how to configure an indepedent NIC for other usage. Sorry I have no SR-IOV environment to test a workaround for you. Thanks.

https://github.com/w13915984028/harvester-develop-summary/blob/main/config-indepedent-nic-with-l2network-on-harvester.md
