### ISSUE TITLE
[BUG] Harvester doesn't appear to be able to find userdata/metadata mounted device

### ISSUE THREAD

**Issue by aleiner** [harvester/harvester#7017]
**Describe the bug**
Potential race condition as this works fine in a virtual machine. Harvester is installed via Install Harvester Binaries Only option. On first boot, userdata/metadata are not found. userdata/metadata are available and that exact flash drive will be read when OS is switch to Elemental Teal.

`journalctl` shows `Processing stage step 'Pull data from provider'...` followed by `no metadata/userdata found`.

**To Reproduce**
1. Build Harvester on Bare Metal (tested with Dell Server and Intel NUC) choose Install Binaries only.
2. Before first boot, mount a CDROM or USB that contains user-data and meta-data

**Expected behavior**
user-data get's read and configures host, which happens on a vmware virtual machine

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Working - Virtual Machine | Not Working: Dell R630 and Intel NUC.

**Comment by aleiner** [comment]
For added context, we modified the initial Harvester ISO to include the following grub options:
```
harvester.scheme_version=1 harvester.install.skipchecks=true harvester.install.mode=install harvester.install.device=/dev/sda harvester.install.automatic=true
```

This enables automatic installation of Harvester.

Due to a separate bug with regarding default routes, I'm also using a custom build of Harvester from this PR: https://github.com/harvester/harvester-installer/pull/876

**Comment by asettle** [comment]
Could you please upload a support bundle? https://docs.harvesterhci.io/v0.3/troubleshooting/harvester/ CC @innobead @bk201

**Comment by bk201** [comment]
@aleiner In general the parameter `harvester.install.automatic=true` was designed to work with a config file url (`harvester.install.config_url=http://10.100.0.10/harvester/config-create.yaml`).  We have not tested the automatic installation in other scenarios.
(example in create mode https://docs.harvesterhci.io/v1.3/install/pxe-boot-install#create-mode)

**Comment by aleiner** [comment]
@asettle - Is there a way to create a support bundle from the CLI? Since Harvester never get's configured, it never get's an IP assigned. 

@bk201 - Anything we can do on the RGS side to assist in testing or making this a a support scenario?

**Comment by aleiner** [comment]
[scc_bundle.txz.log](https://github.com/user-attachments/files/17846638/scc_bundle.txz.log)
Including a support bundle. I added the .log to the filename to get GitHub to accept the attachment.

**Comment by ibrokethecloud** [comment]
in my local tests issue seems to be caused by the scsi device scanning not yet being completed before the datasource directive is run to try and mount the cloud-init

A confirmed work around has been to move the datasource lookup to `initramfs` stage

https://github.com/harvester/os2/blob/sle-micro/files/system/oem/00_rootfs.yaml

A fix would be to change this to a more suitable stage and ensure this is executed before the installer service is booted.

**Comment by zackbradys** [comment]
hey @ibrokethecloud @rebeccazzzz... I see a few different PRs for this in `os2`... is there an ETA on when this will be fixed/available in a release of `harvester`?

**Comment by rebeccazzzz** [comment]
Hi @zackbradys. This issue is currently scheduled to be fixed in v1.5.0 (release date at the end of March 2025).

**Comment by ibrokethecloud** [comment]
this is already available in v1.4.1

**Comment by TachunLin** [comment]
@ibrokethecloud 
May I know the reproduce steps/test steps for this issue verification. 
And also could I verify it using kvm machine or need to verify on the bare-metal machine. Many thanks.

**Comment by ibrokethecloud** [comment]
To test this change:
* Install harvester to a physical machine or vm using install mode option
* create a cloud-init iso using the following script genenerate-iso.sh. Please change the interface to match interface of your machine
```
#/bin/bash

cat > /tmp/user-data <<EOF
#cloud-config
scheme_version: 1
token: token # replace with a desired token
os:
  password: p@ssword # replace with a your password
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
install:
  automatic: true
  mode: create
  vip_mode: dhcp
  management_interface:
    interfaces:
      - name: enp4s0f0
    default_route: true
    method: dhcp
    vlan_id: 2017
    bond_options:
      mode: balance-tlb
      miimon: 100
EOF
touch /tmp/meta-data
genisoimage  -output /tmp/create.iso  -volid cidata -joliet -rock /tmp/user-data /tmp/meta-data
rm /tmp/user-data
rm /tmp/meta-data
```
* attach the generated `create.iso` to the node
* boot the node with harvester pre-installed in install mode
* on first boot the harvester node should auto configure from the contents of the iso

**Comment by zackbradys** [comment]
I can verify that this works in `v1.4.1` and `v1.4.2`! Hoping to test and be sure for `v1.5.0`, but I don't expect it to not work since it's already working in `v1.4.x`. Thank you for getting this fixed for everyone and feel free to close whenever you're ready... @ibrokethecloud

**Comment by TachunLin** [comment]
Verified **fixed** on v1.5-head (25/03/20). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ User binary installation can load user data on the mounted device $~~$</summary>

  1. When we set the user data in the iso and attached to the node machine

  1. After first boot from binary installation, it can find the userdata on the mounted cd-rom device

  ![Image](https://github.com/user-attachments/assets/9aec0deb-3ab9-44ae-b75b-88a0cab07a64)
  
  https://github.com/user-attachments/assets/b621924c-1c7b-41e3-ac3a-955a44001f95
  
 </details>



### Test Information
* Test Environment: Single node harvester on kvm machine
* Harvester version: v1.5-head (25/03/20) 

### Verify Steps
<details><summary> User binary installation can load user data on the mounted device </summary>

1. Create a cloud-init iso using the following script `genenerate-iso.sh`. Please change the interface to match interface of your machine

    ```
    #/bin/bash
    
    cat > /tmp/user-data <<EOF
    #cloud-config
    scheme_version: 1
    token: token # replace with a desired token
    os:
      password: p@ssword # replace with a your password
      ntp_servers:
        - 0.suse.pool.ntp.org
        - 1.suse.pool.ntp.org
    install:
      automatic: true
      mode: create
      vip_mode: dhcp
      management_interface:
        interfaces:
          - name: enp4s0f0
        default_route: true
        method: dhcp
        vlan_id: 2017
        bond_options:
          mode: balance-tlb
          miimon: 100
    EOF
    touch /tmp/meta-data
    xorriso -as mkisofs -o /tmp/create.iso -V cidata -J -R /tmp/user-data /tmp/meta-data
    rm /tmp/user-data
    rm /tmp/meta-data
    ```

2. Generate the iso
3. Prepare a kvm node machine
4. Add the second CD ROM device (SCSI) and attach the generated `create.iso` to the machine
5. Boot the node with harvester pre-installed in install mode
6. Check on first boot the harvester node should auto configure from the contents of the iso

</details>
