### ISSUE TITLE
[ENHANCEMENT] Upgrade CI To Use Trivy v0.57.1 To Handle GHCR Rate Limiting Errors

### ISSUE THREAD

**Issue by ihcsim** [harvester/harvester#7023]
**Is your enhancement related to a problem? Please describe.**

Trivy v0.57.1 includes multiple image registry fallbacks, to account for the recent increase in GHCR rate limiting errors. Since Trivy action v0.28.0 is still using Trivy v0.56.1, we can override Trivy's version in GHA with:

```yaml
- uses: aquasecurity/trivy-action@0.28.0
  with:
    version: 'v0.57.1'
```

**Describe the solution you'd like**

Update the `trivy-scanning` GHA workflow to use Trivy v0.57.1.

**Describe alternatives you've considered**

**Additional context**
