### ISSUE TITLE
[ENHANCEMENT] Improve Managed DHCP to sync VM MAC address changes and allow network config updates

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#7046]
**Is your enhancement related to a problem? Please describe.**

In the current design and implementation of the Managed DHCP feature, there are two limitations regarding the virtual machine's MAC addresses being recorded in the VirtualMachineNetworkConfig custom resource:

- Existing elements under the `.spec.networkConfig` field cannot be altered. Users can only append new elements to the `.spec.networkConfig` field.
- The controller will not sync with the MAC addresses in the VirtuamMachine resource. They are what they were when the VirtualMachineNetworkConfig resource was first populated from the VirtualMachine resource. That means even when the user updates the MAC address in the VirtualMachine resource, the corresponding VirtualMachineNetworkConfig resource still holds the old MAC addresses.

We plan to support the capability of reflecting the MAC addresses in the virtual machine by tracking the VirtualMachine resource and updating the corresponding field in the VirtualMachineNetworkConfig resource (of course, this will involve allocating new IP addresses if no designated IP addresses are specified).

For example, given a VirtualMachine resource:

```yaml
          interfaces:
          - bootOrder: 1
            bridge: {}
            macAddress: 52:54:00:0f:2e:67
            model: virtio
            name: default
```

The controller will populate a VirtualMachineNetworkConfig resource out of the VirtualMachine resource:

```yaml
spec:
  networkConfigs:
  - macAddress: 52:54:00:0f:2e:67
    networkName: default/vm-net
  vmName: machine-1
```

But when the user tries to update the MAC address in the VirtualMachine resource and reboot the virtual machine:

```yaml
          interfaces:
          - bootOrder: 1
            bridge: {}
            macAddress: f6:54:7e:b2:9d:10 # Note: the mac address has changed
            model: virtio
            name: default
```

The VirtualMachineNetworkConfig resource remains the same and no new leases are generated, causing the virtual machine unable to get the IP address from the DHCP agent.

**Describe the solution you'd like**

1. Make the VirtualMachineNetworkConfig resource's `.spec.networkConfig` field updatable (Need to adjust CRD validation rule). Currently, the field is protected by a CEL (Common Expression Language) validation rule
   ```go
           // +optional
           // +kubebuilder:validation:Optional
           // +kubebuilder:validation:XValidation:rule="oldSelf.all(x, x in self)",message="NetworkConfig may only be added"
           // +kubebuilder:validation:MaxItems=4
           NetworkConfigs []NetworkConfig `json:"networkConfigs,omitempty"`
   ```
2. The vm-controller should sync the MAC address changes to the VirtualMachineNetworkConfig resource
3. The vmnetcfg-controller should allocate a new IP address for the MAC address if necessary (the old one should also be taken care of)

**Describe alternatives you've considered**

A simple workaround is to remove the corresponding VirtualMachineNetworkConfig resource. After the virtual machine is rebooted, the vm-controller will generate a new one from the latest VirtualMachine resource; therefore, the new MAC addresses will be reflected. To retain the allocated IP addresses, jot down the IP addresses and then manually create a VirtualMachineNetworkConfig resource with the designated IP address before rebooting the virtual machine.

**Additional context**

Some users see plenty of `LEASE NOT FOUND` warning messages popping up in the DHCP agent's log. One of the reasons is that they changed the MAC addresses of the virtual machine, as described in this issue. Another reason is that the virtual machine could create more network interfaces during its runtime. For instance, users log into the virtual machine and create a new network interface. A common situation we notice is that the virtual machine, one of the nodes forming a downstream RKE2 cluster, has some macvlan interface created because kube-vip needs them to get IP addresses from the DHCP server. As this kind of network interface will be reported by the QEMU guest agent and be reflected on the VirtualMachineInstance custom resource, we may have a chance to support this specific use case. But I think it's off-topic. If such a use case is demanded, I will create a new ticket to track it.
