### ISSUE TITLE
[BUG] Crash when `VirtualMachineTemplateVersion` contains bogus JSON data

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester#7051]
**Describe the bug**
Harvester container crashes when a `VirtualMachineTemplateVersion` with bogus JSON data in `.spec.vm.metadata.annotations.harvesterhci.io/volumeClaimTemplates` is created
As a result of the Harvester container crashing, Harvester web UI becomes unavailable:

![Screenshot at 2024-11-27 17-05-53](https://github.com/user-attachments/assets/de2b2533-09bb-456f-93d6-a35a8fa35e5b)

**To Reproduce**
1. Install Harvester
2. Create new `VirtualMachineTemplateVersion` object with bogus JSON data in `.spec.vm.metadata.annotations.harvesterhci.io/volumeClaimTemplates`, e.g.
   (note the extra `}` at the end of the JSON data):

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineTemplateVersion
metadata:
  labels:
    template.harvesterhci.io/templateID: windows-raw-image-base-template
  name: windows-raw-image-base-version-2
  namespace: harvester-public
  ownerReferences:
    - apiVersion: harvesterhci.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: VirtualMachineTemplate
      name: windows-raw-image-base-template
      uid: b92d77a2-0313-451f-92b6-364f566a5fd3
spec:
  templateId: harvester-public/windows-raw-image-base-template
  vm:
    metadata:
      annotations:
        harvesterhci.io/reservedMemory: 256Mi
        harvesterhci.io/volumeClaimTemplates: |-
          [{
            "metadata": {
              "name": "pvc-rootdisk",
              "annotations": {
                "harvesterhci.io/imageId": ""
              }
            },
            "spec":{
              "accessModes": ["ReadWriteMany"],
              "resources":{
                "requests":{
                  "storage": "32Gi"
                }
              },
              "volumeMode": "Block"
            }
          }]}
      creationTimestamp: null
      labels:
        harvesterhci.io/os: windows
    spec:
      runStrategy: RerunOnFailure
      template:
        metadata:
          creationTimestamp: null
        spec:
          domain:
            cpu:
              cores: 1
            devices:
              disks:
                - bootOrder: 1
                  disk:
                    bus: virtio
                  name: rootdisk
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
            features:
              acpi:
                enabled: true
            resources:
              limits:
                cpu: '1'
                memory: 2Gi
          evictionStrategy: LiveMigrateIfPossible
          networks:
            - name: default
              pod: {}
          volumes:
            - name: rootdisk
              persistentVolumeClaim:
                claimName: pvc-rootdisk
```

3. Make new VirtualMachineTemplateVersion the current version of the VirtualMachineTemplate

**Expected behavior**
Bogus user input should never cause a crash

**Environment**
 - Harvester ISO version: v1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe-examples based test environment

**Additional context**
Log with error message: [log.txt](https://github.com/user-attachments/files/17937061/log.txt)

There are two errors here:
1) `unable to calculate an index entry for key \"harvester-public/windows-raw-image-base-version-2\" on index \"harvesterhci.io/vmtemplateversion-by-image-id\"`
The first error is emitted from the `k8s.io/client-go` package.
This error happens when a Harvester controller tries to index the objects in its local cache and fails to process one of the objects.

2) `can't unmarshal harvesterhci.io/volumeClaimTemplates, err: invalid character '}' after top-level value`
The error is emitted from the `mailru/easyjson` package, which is a dependency of Harvester. This is a Golang library used for parsing JSON data.
This error seems to be emitted when the JSON data in the annotation of the VirtualMachineTemplateVersion is bogus.
