### ISSUE TITLE
[BUG] Pod `guest-consloe-log` Terminated during Migrating VM on Upgrading harvester

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#7068]
**Describe the bug**

I have noticed that the VM status shows `Containers with unready status:[guest-consloe-log]` during a long time VM migration on upgrading harvester.
But infact the VM is running normally.
This phenomenon has been observed in v1.3.1 to v1.3.2 and v1.3.2 to v1.4.0.
![微信截图_20241128205246](https://github.com/user-attachments/assets/5bb51f03-b7cd-45d0-93f4-fe8c481e4d98)
![微信截图_20241128205203](https://github.com/user-attachments/assets/b19b46d6-f7f1-4eb9-8803-7a48a3a811c7)

**To Reproduce**
1. Upgrading harvester on multi-node cluster and trigged VM migration.

**Expected behavior**

It faithfully reflects the running state of the VM.

**Support bundle**

same with https://github.com/harvester/harvester/issues/7067
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.5.zip](https://github.com/user-attachments/files/17954903/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.5.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.4.zip](https://github.com/user-attachments/files/17954905/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.4.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.3.zip](https://github.com/user-attachments/files/17954907/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.3.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.2.zip](https://github.com/user-attachments/files/17954908/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.2.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.1.zip](https://github.com/user-attachments/files/17954909/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T05-33-04Z.1.zip)

**Environment**
 - Harvester ISO version: v1.3.2 v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes Dell PowerEdge R740

**Additional context**

same with https://github.com/harvester/harvester/issues/7067
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.6.zip](https://github.com/user-attachments/files/17954191/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.6.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.5.zip](https://github.com/user-attachments/files/17954193/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.5.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.4.zip](https://github.com/user-attachments/files/17954194/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.4.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.3.zip](https://github.com/user-attachments/files/17954196/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.3.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.2.zip](https://github.com/user-attachments/files/17954197/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.2.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.1.zip](https://github.com/user-attachments/files/17954198/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T03-40-09Z.1.zip)

**Comment by bk201** [comment]
We can reproduce this by (not 100%)
- hot plug some volumes (8+ volumes)
- run workload in the vm: `stress-ng --cpu 4 --vm 2 --hdd 1 --fork 8 --timeout 2m --metrics`
- do a live migration

the `guest-console-log` container expects a log file from the `compute` container, but the file doesn't show up in 20 seconds. VM is running well, but it will be in the not ready status.

**Comment by Yu-Jack** [comment]
Upstream issue https://github.com/kubevirt/kubevirt/issues/13466 has been merged. We'll wait for a new patch and test it.

**Comment by innobead** [comment]
Added to 1.5.0 as @Yu-Jack is working on this.

**Comment by Yu-Jack** [comment]
Wait for the Harvester to be patched.

**Comment by megabreit** [comment]
Any backport to 1.4.2 planned?

**Comment by innobead** [comment]
@Yu-Jack IIRC, the virt team already backported the upstream fix to KubeVirt 1.3 and 1.2 images. Please move this issue forward. 

> The PR ([#13588](https://github.com/kubevirt/kubevirt/pull/13588)) has been backported to SP5, SP6, and Factory.

cc @harvester/tpm

**Comment by Yu-Jack** [comment]
For master and v1.5 branch, the KubeVirt image has been updated in this PR https://github.com/harvester/harvester/pull/7531. Test results are below.

```
- command:
  - /usr/bin/virt-launcher-monitor
  - --qemu-timeout
  - 327s
  - --name
  - test
  - --uid
  - a229ec41-1c07-4d6e-b8f2-3794a43f79a2
  - --namespace
  - default
  - --kubevirt-share-dir
  - /var/run/kubevirt
  - --ephemeral-disk-dir
  - /var/run/kubevirt-ephemeral-disks
  - --container-disk-dir
  - /var/run/kubevirt/container-disks
  - --grace-period-seconds
  - "135"
  image: registry.suse.com/suse/sles/15.6/virt-launcher:1.4.0-150600.5.12.1
- args:
    - --logfile
    - /var/run/kubevirt-private/a229ec41-1c07-4d6e-b8f2-3794a43f79a2/virt-serial0-log
    - --socket-timeout
    - 327s
    command:
    - /usr/bin/virt-tail
    env:
    - name: VIRT_LAUNCHER_LOG_VERBOSITY
      value: "2"
    image: registry.suse.com/suse/sles/15.6/virt-launcher:1.4.0-150600.5.12.1
```
