### ISSUE TITLE
[BUG] v1.4.0 Harvester w/ Rancher v2.10.1-alpha1 Harvester Cloud-Config User Data Fail to Render At RKE2 Cluster Creation

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7176]
**Describe the bug**
In Rancher when building RKE2 Clusters Cloud-Config User Data fails to come across correctly.
What's noticed is that it seems to only be rendering / bringing in a "small" portion of the cloud-config for User Data for instance.
In the attached screen grabs you can audit the behavior a bit more.
But the gist might be that it's just not doing a "merge" on the YAML content appropriately.

**To Reproduce**
1. In Harvester v1.4.0, create a cloud-config template for User Data that holds the following code block of yaml
```yaml
#cloud-config
password: password
chpasswd:
  expire: false
ssh_pwauth: true
package_update: true
packages:
  - qemu-guest-agent
  - apt-transport-https
  - neovim
  - wget
  - ca-certificates
  - python3
  - python3-pip
  - jq
  - curl
  - gnupg-agent
  - gnupg
  - lsb-release
  - htop
  - parted
  - fdisk
  - gnupg2
  - neovim
  - software-properties-common
  - coreutils
  - sshpass
  - tmux
  - net-tools
  - unzip
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
```
2.  In Rancher v2.10.1-alph1 / v2.10-head (possibly) , add the repo for the harvester-ui-extension, to your manage repos, then add the branch of `gh-pages` then select v1.0.2 , install and reload
3. Import your Harvester v1.4.0 cluster of N nodes into Rancher, wait for import to be successful
4. Build a cloud credential for your Harvester imported v1.4.0 cluster
5. Click create on a RKE2 Cluster (the k8s version of RKE2 does not matter) , go down to the "Advanced" Section, and then select your `User Data Template` you built in Harvester. 
6. Notice that the User Data Template rendered does not show the correct cloud-config, you instead will see that it will show "other" items properly like `password, chpasswd, package_update, ssh_pwauth, runcmd` , yet the text merging of the data on `packages` seems to be entirely off -> Note that if you do "create" a RKE2 cluster with your cloud config, as referenced from the screengrabs below, they also will not have the correct cloud-config that you have desired from your template.

**Expected behavior**
User Data in an RKE2 Cluster to be accurate to the Template built in Harvester and not have issues merging properties like "packages" in the YAML

**Environment**
 - Harvester ISO version: v1.4.0
 - Rancher Version: v2.10.1-alpha1 
 - Underlying Infrastructure: Bare Metal, HP-DL160, Single Node + VM For Rancher w/ K3S

**Additional context**
![Screenshot from 2024-12-16 11-33-17](https://github.com/user-attachments/assets/174e5332-679b-47c4-b557-dc5cec947dd7)
![Screenshot from 2024-12-16 11-34-03](https://github.com/user-attachments/assets/4db686c5-1dfb-4cf9-8dde-64575126fc5f)
