### ISSUE TITLE
[BUG] The upgrade pre-check script does not catch all non-ready pods

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#7181]
**Describe the bug**

If the pod contains multiple containers and some are not ready, the pod's `.status.phase` field will still be `Running`. The upgrade pre-check script currently relies on the `.status.phase` field to determine whether pods are ready, which misses that kind of pod.

**To Reproduce**
1. Prepare a Harvester cluster (single node is enough)
2. Get the kubeconfig file
3. Create a testing pod
   ```
   cat <<EOF | kubectl apply -f -
   apiVersion: v1
   kind: Pod
   metadata:
     labels:
       run: test
     name: test
   spec:
     containers:
     - image: busybox
       name: worker
       command: ["/bin/sh", "-c"]
       args:
       - |
         #!/usr/bin/env sh
         set -ex
         echo Start doing something...
         sleep 10
         echo Done.
     - image: nginx
       name: server
     dnsPolicy: ClusterFirst
     restartPolicy: Never
   EOF
   ```
4. Run the pre-check script (https://raw.githubusercontent.com/harvester/upgrade-helpers/refs/heads/main/pre-check/v1.x/check.sh) on the node
   ```
   ./check.sh
   ```
5. The pre-check script reports that everything looks fine (while it should've detected the problematic testing pod we just created)

**Expected behavior**

The pre-check script should detect any non-ready pods.

**Support bundle**

N/A

**Environment**
 - Harvester ISO version: v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

N/A
