### ISSUE TITLE
[ENHANCEMENT] Harvester CSI Driver Controller should only deploy on the control plane nodes.

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#7189]
**Is your enhancement related to a problem? Please describe.**
Currently, the Harvester CSI Driver Controller does not have the affinity to ensure the deployment target.
That means we will encounter the following two cases:
- The Harvester CSi Driver Controller will deploy to the worker node. The worker nodes should not run the Harvester CSI Driver Controller.
- The replica number of Harvester CSI driver Controller did not adapt the control plane nodes. It is fixed to 3, so we will deploy 3 Harvester CSI driver Controller on the one control plane node if we have only one control plane.

**Describe the solution you'd like**
Prevent the above two cases:
- Harvester CSI driver Controller should not be deployed to the worker nodes
- Harvester CSI driver Controller should adapt the control plane nodes but limited with 3.

**Describe alternatives you've considered**

**Additional context**

**Comment by megabreit** [comment]
Please also make sure that the CSI driver controller pods are not running on the same node (regardless of worker or control plane)!

**Comment by ihcsim** [comment]
@Vicente-Cheng Can the controller pods be scheduled to run on management nodes too? From what I see, a control plane node (with `node-role.kubernetes.io/control-plane: "true"`) is not necessary a management node (with `node-role.harvesterhci.io/management: "true"` label).

Also, I notice that the controller tolerates the [witness node's taint](https://github.com/harvester/charts/blob/e68cc57d3818a00aa33f86aeb95f8ee3dab59168/charts/harvester-csi-driver/values.yaml#L45-L47). Do we want the controller to run on a witness node?

And AFAICT, we don't need to worry about the LVM CSI controller since it's a STS with a `hostpath` volume?

**Comment by ihcsim** [comment]
@megabreit Yes, it will be a soft constraint.

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng Can the controller pods be scheduled to run on management nodes too? From what I see, a control plane node (with `node-role.kubernetes.io/control-plane: "true"`) is not necessary a management node (with `node-role.harvesterhci.io/management: "true"` label).
> 
> Also, I notice that the controller tolerates the [witness node's taint](https://github.com/harvester/charts/blob/e68cc57d3818a00aa33f86aeb95f8ee3dab59168/charts/harvester-csi-driver/values.yaml#L45-L47). Do we want the controller to run on a witness node?
> 

The harvester csi driver runs on the guest cluster. We should treat it with the formal label (like you mentioned `node-role.kubernetes.io/control-plane: "true"`).  Also, we should not run this controller on the witness node, so please help to update the toleration on Chart.

> And AFAICT, we don't need to worry about the LVM CSI controller since it's a STS with a `hostpath` volume?

Yeah, we don't need to worry about the LVM CSI controller. It did not have any replicas.  (I thought we have toleration to temporarily handle the LVM CSI controller down).

**Comment by ihcsim** [comment]
Right - I forgot that the CSI driver runs on the guest cluster. So by "worker nodes", you meant any node that doesn't have the `node-role.kubernetes.io/control-plane` label? Unlike Harvester, there isn't an official K8s label for worker nodes.

**Comment by Vicente-Cheng** [comment]
> Right - I forgot that the CSI driver runs on the guest cluster. So by "worker nodes", you meant any node that doesn't have the `node-role.kubernetes.io/control-plane` label? Unlike Harvester, there isn't an official K8s label for worker nodes.

Yes, we need to ensure the Controller is deployed to the nodes with the `node-role.kubernetes.io/control-plane: "true"` label. If nodes did not have this label, they should be worker or etcd. We would not want to deploy the controller into worker/etcd nodes.

**Comment by ihcsim** [comment]
> Harvester CSI driver Controller should adapt the control plane nodes but limited with 3.

@Vicente-Cheng Any thoughts on how to go about doing this? Feels like this should be some form of auto-scaling (up/down) feature based on volume-related metrics, not a chart install-time decision.

**Comment by Vicente-Cheng** [comment]
> > Harvester CSI driver Controller should adapt the control plane nodes but limited with 3.
> 
> @Vicente-Cheng Any thoughts on how to go about doing this? Feels like this should be some form of auto-scaling (up/down) feature based on volume-related metrics, not a chart install-time decision.

Hi @ihcsim, 
I did some surveys, and it looks like we need an extra controller for it (if we want to adjust the replica number dynamically).
I thought we could skip this part at this moment. And open another enhancement ticket.
It is nice to have but not a must for Harvester CSI driver.
WDYT?

**Comment by ihcsim** [comment]
@Vicente-Cheng Keeping it in another enhancement ticket makes sense to me. I'd like to better understand the requirements you have in mind. Normally, handling of dynamic replicas is done with the k8s horizontal pod auto-scaler, versus writing our own controller. Also worth considering is whether the controller is a bottleneck? In other CSI providers I've seen, the busier pods tend to be the driver's csi-plugin, not the controller. If you start an enhancement story, we can discuss further there. Thanks.

**Comment by albinsun** [comment]
Hi @ihcsim ,
I'm going to test this and have 2 questions:
1. Which version of `harvester-csi-driver` I can test with? `v0.1.23` or ?
1. Per discussed, seems auto-scaling is not support yet (e.g. scale up/down RKE2 cluster), is it correct?

cc. @Vicente-Cheng

**Comment by Vicente-Cheng** [comment]
Hi @albinsun,

We need to wait for Harvester CSI driver v0.1.23 to be available on the rancher/rke2 side. It should be in the Feb Release cycle.
And, yes, auto-scaling is not within this scope.

**Comment by Vicente-Cheng** [comment]
> [@Vicente-Cheng](https://github.com/Vicente-Cheng) Keeping it in another enhancement ticket makes sense to me. I'd like to better understand the requirements you have in mind. Normally, handling of dynamic replicas is done with the k8s horizontal pod auto-scaler, versus writing our own controller. Also worth considering is whether the controller is a bottleneck? In other CSI providers I've seen, the busier pods tend to be the driver's csi-plugin, not the controller. If you start an enhancement story, we can discuss further there. Thanks.

Hi @ihcsim,
Currently, I do not have a strong opinion of this feature. Two replicas would be enough to handle the rolling upgrade.
And, yes, the controller should not be the bottleneck. We could create an issue and keep the backlog to collect more feedback. WDYT?

**Comment by albinsun** [comment]
Let's wait for version bumping on RKE2 side before testing.
* https://github.com/harvester/harvester/issues/7501

**Comment by TachunLin** [comment]
@ihcsim,
May I know the detailed reproduce and test steps for this issue verification. Thank you.

**Comment by ihcsim** [comment]
@TachunLin Take a look at the test step at https://github.com/harvester/charts/pull/323. Let me know if you have any questions. Make sure you are using v0.1.23 of the Harvester CSI driver. Thanks.

**Comment by TachunLin** [comment]
As per discussed with Ivan, list the following test plan steps  

1. Prepare Harvester and import to Rancher 
2. Provision a RKE2 cluster 
3. Ensure the Harvester-csi-driver is `0.1.23`
4. Specify five pools for different role: three control-planes, one etcd and one worker node 
5. Check the roles status when RKE2 cluster ready   
    ```
    kubectl --kubeconfig rke2-v1308.yaml get nodes -o wide
    ```
6. Check the csi-controllers replicas 

    ```
      kubectl --kubeconfig rke2-v1308.yaml -n kube-system get po -lcomponent=csi-controllers -owide
    ```
  
7. **(optional)** If the csi-driver version lower than `0.1.23`, can add the node affinity and pod anti-affinity rules in the deployment

      ```
      affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  # For RKE1
                  - matchExpressions:
                    - key: [node-role.kubernetes.io/controlplane](http://node-role.kubernetes.io/controlplane)
                      operator: Exists
                  # For RKE2
                  - matchExpressions:
                    - key: [node-role.kubernetes.io/control-plane](http://node-role.kubernetes.io/control-plane)
                      operator: Exists
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: [app.kubernetes.io/name](http://app.kubernetes.io/name)
                        operator: In
                        values: [harvester-csi-driver]
                      - key: component
                        operator: In
                        values: [csi-controllers]
                    topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
      ```
  
8. Scale the CSI controller to 10 replicas
    ```
    kubectl --kubeconfig rke2-v1308.yaml -n kube-system scale deploy/harvester-csi-driver-controllers --replicas=10
    ```

9. Confirm that all the replicas:
    - are scheduled to run only on control plane nodes, not worker nor etcd nodes
    - are distributed across the control plane nodes, instead of just one node
    - are healthy
