### ISSUE TITLE
add default template that do not require pre-existing images

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#72]
**Description:**
add embedded/system templates that do not require pre-existing images
- [x] iso-img-template
- [x] windows-template
- [x] qcow2/img/raw-template

**Comment by aiwantaozi** [comment]
- [ ] qcow2/img/raw-template

**Comment by aiwantaozi** [comment]
Plan to add a parameters to templateVersion.

Parameters allow a inject values:
1. value to be generated when the template is instantiated. This is useful for generating unique datavolume name, random passwords etc.
2. reference value from VM object when the template is instantiated.

```
type Parameter struct {
	Name               string `json:"name,omitempty"`
	Path               string `json:"path,omitempty"`
	Description        string `json:"description,omitempty"`
	From               string `json:"from,omitempty"` //options: generate/object
	GenerateExpression string `json:"generateExpression,omitempty"`
	ObjectKey          string `json:"objectKey,omitempty"`
}
```

```
type VirtualMachineTemplateVersionSpec struct {
	Description string                          `json:"description,omitempty"`
	TemplateID  string                          `json:"templateId,omitempty"`
	ImageID     string                          `json:"imageId,omitempty"`
	KeyPairIDs  []string                        `json:"keyPairIds,omitempty"`
	VM          virtv1alpha3.VirtualMachineSpec `json:"vm,omitempty"`
	Parameters  []Parameter                     `json:"parameters,omitempty"`
}
```
example 1: use parameter name to set value, value from GenerateExpression
```
parameters:
  - name: DATAVOLUME_NAME_SUFFIX 
    description:  generate random suffix datavolume name to avoid duplicate
    from: generate
    generateExpression: [\w]{6}
    required: true 
```

example 2: use parameter name to set value, value from VM object, will get data from VM metadata.name
```
parameters:
  - name:  DATAVOLUME_NAME_PREFIX
    description:  
    from: object
    objectKey: metadata.name
```

final templateVersion

```
vm:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: ${DATAVOLUME_NAME_PREFIX}-${DATAVOLUME_NAME_SUFFIX}
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: ${DATAVOLUME_NAME_PREFIX}-${DATAVOLUME_NAME_SUFFIX}
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      source:
        http:
          url: http://cdi-http-import-server.kubevirt/images/alpine.iso
parameters:
  - name:  DATAVOLUME_NAME_PREFIX
    description:  
    from: object
    objectKey: metadata.name
  - name: DATAVOLUME_NAME_SUFFIX 
    description:  generate random suffix datavolume name to avoid duplicate
    from: generate
    generateExpression: [\w]{6}
    required: true 
```

example 3: use json path to set value, the specified path will be set with the value from vm metadata.name 
```
parameters:
  - path: vm.dataVolumeTemplates[0].metadata.name
    description:  
    from: object
    objectKey: metadata.name
```

**Comment by gitlawr** [comment]
A few questions:
1. How do users create a template like example 2 in the UI?

2. When creating a VM via a template(example 2), Can users customize the fields that are using parameters in the template?

**Comment by guangbochen** [comment]
+1 of the above questions and can u please help to clarify how those parameters will imply the UI design and management, additionally,  will parameters be used for both VM and template page or VM page only, let's arrange an offline meeting to discuss it when u those designs ready, thanks.

**Comment by aiwantaozi** [comment]
We would like to support our UI to generate unique dataVolume name, can allow the user to configure parameter in the UI later.

***Re 1***: when a user creates a template, and add a disk, could check the ***New example 1***. If we could support parameters in the UI,  when the user adds a disk or other resource, could also use the parameter already added. 

![image](https://user-images.githubusercontent.com/5936271/91278653-1674b480-e7b7-11ea-8e48-61a7d54150fb.png)

***Re 2***: when a user creates a VM from the template, after the user clicks the launch from the template, UI will render the VM configure base on the template, then the user could edit it.

***Re parameters scope***: this parameter only configure in vmTemplateVersion, and use for render VM configure when user launch from template

Update parameter struct to:
```
type Parameter struct {
	Path               string `json:"path,omitempty"`
	Description        string `json:"description,omitempty"`
	From               string `json:"from,omitempty"` //options: regex/object/param
        Regex             string `json:"regex,omitempty"`
	ObjectKey          string `json:"objectKey,omitempty"`
        Param            string `json:"param,omitempty"`
}
```

***New example 1***: UI will add parameters ${DATAVOLUME_NAME_PREFIX}, ${DATAVOLUME_NAME_SUFFIX}, ${DATAVOLUME_NAME_1} to the templateVersion when user add a disk, will add ${DATAVOLUME_NAME_2} parameter when user add second disk.
```
vm:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: ${DATAVOLUME_NAME_1}
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: ${DATAVOLUME_NAME_1}
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      source:
        http:
          url: http://cdi-http-import-server.kubevirt/images/alpine.iso
parameters:
  - name:  DATAVOLUME_NAME_PREFIX
    description:  
    from: object
    objectKey: metadata.name
  - name: DATAVOLUME_NAME_SUFFIX 
    description:  generate random suffix datavolume name to avoid duplicate
    from: regex
    regex: [\w]{6}
  - name: DATAVOLUME_NAME_1
    description:  generate datavolume name
    from: param
    param: ${DATAVOLUME_NAME_PREFIX}-${DATAVOLUME_NAME_SUFFIX}
  ```
