### ISSUE TITLE
[ENHANCEMENT] Support various vlan for RWX volume on the guest cluster

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#7218]
**Is your enhancement related to a problem? Please describe.**
Currently, we need Harvester storage network for the RWX volume on the guest cluster. The Longhorn share manager will _**create NFS endpoint on the storage network, so users need to create guest clusters with at least two nic cards.**_ One is for general purposes, and the other is for RWX volume.

**Describe the solution you'd like**
We should able to create RWX with the vlan id of the running guest VM. That means only the guest cluster VM can access this RWX volume. Also, that might split the use case from the storage network.

**Describe alternatives you've considered**
None

**Additional context**
TBU

**Comment by innobead** [comment]
After discussing this with @Vicente-Cheng, the current design does not support VLAN (VM network) awareness. As a result, we need to rely on the Longhorn storage network to ensure that the NFS endpoints exported by the Longhorn Share Manager can be accessed by the Harvester CSI drivers running on guest/downstream clusters. For 1.4, the storage network can generally be considered the secondary interface for all VMs provisioned on Harvester, regardless of the VM networks they use. It still works but unfortunately, the storage network becomes a condition for this feature. 

How to improve this? Enabling VLAN awareness for Longhorn RWX volumes requires enhancements in Longhorn to support multiple storage networks instead of relying solely on a built-in network when exporting NFS endpoints.

To make this feature for general third-party storage solutions, it needs to depend on upstream KubeVirt FS volume support instead of the current design. 

cc @Vicente-Cheng @derekbit @bk201

**Comment by innobead** [comment]
ref: https://github.com/kubevirt/kubevirt/issues/11699

**Comment by innobead** [comment]
Added `area/upstream`, since this requires upstream longhorn efforts first.

**Comment by hoo29** [comment]
We have the storage network enabled on harvester but don't currently have a NIC for it attached to any VM, only our compute networks. Are there any security implications if we start giving each VM direct access to the storage network?

**Comment by Vicente-Cheng** [comment]
Hi @hoo29, 

I know your concern. 
I will do some tests to ensure the user cannot do anything weird through the storage network on the guest VM.

I will update here later.

**Comment by BringerOD** [comment]
+1

**Comment by innobead** [comment]
@Vicente-Cheng I just noticed there is a [Longhorn setting](https://longhorn.io/docs/1.8.1/references/settings/#storage-network-for-rwx-volume-enabled) allowing to disable the storage network for RWX. It's disabled by default. Having it disabled and just relying on the VLAN network for guest cluster nodes to decouple the dependency on the storage network for RWX volumes for workloads on guest clusters. Have we considered this first before the upstream Longhorn issue gets improved?

[/controller/share_manager_controller.go#L460-L469](https://github.com/longhorn/longhorn-manager/blob/84262a085e4fab2dd34a2ec32b8a2d2795da529d/controller/share_manager_controller.go#L460-L469)
```go
	if storageNetworkForRWXVolume {
		serviceFqdn := fmt.Sprintf("%v.%v.svc.cluster.local", sm.Name, sm.Namespace)
		sm.Status.Endpoint = fmt.Sprintf("nfs://%v/%v", serviceFqdn, sm.Name)
	} else {
		endpoint := service.Spec.ClusterIP
		if service.Spec.IPFamilies[0] == corev1.IPv6Protocol {
			endpoint = fmt.Sprintf("[%v]", endpoint)
		}
		sm.Status.Endpoint = fmt.Sprintf("nfs://%v/%v", endpoint, sm.Name)
	}
```

cc @harvester/storage

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/10269 is ready in Longhorn 1.11.

**Comment by brandboat** [comment]
Just a heads-up: Currently we need to shutdown all VMs for the `endpoint-network-for-rwx-volume` setting to take effect.
more info please check: https://github.com/longhorn/longhorn/issues/12644.

Update: https://github.com/longhorn/longhorn/issues/12644 was resolved and backported to v1.11.x branch (see https://github.com/longhorn/longhorn-manager/commit/0ecbb25292b8b50f4eea4288ed41e45eeb1bd0f8).

**Comment by TachunLin** [comment]
Related document:
* Test plan:  https://github.com/harvester/harvester/pull/10256#issue-4105234023
* HEP: https://github.com/harvester/docs/pull/990

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.8.0-rc2` and `v1.8.0-rc4` with Rancher v2.14.0. Close this issue.

### Result:  Harvester side

#### Test Group 1: Default state & deletion protection
<details><summary>$\color{green}{\textsf{PASS}}$ Check rwx-network default Settings  $~~$</summary>


1. `rwx-network` default value is {"share-storage-network":false}

  ```
  {
    "share-storage-network": false
  }
  ```
  
  <img width="525" height="202" alt="Image" src="https://github.com/user-attachments/assets/7c770062-79bc-4069-bec1-73bd0850e834" />



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Check rwx-network delete protection  $~~$</summary>


1. Delete `rwx-network` with kubectl will prompt MethodNotAllowed error

  ```
  harvester-node-0:~ # kubectl delete setting rwx-network
  Error from server (MethodNotAllowed): admission webhook "validator.harvesterhci.io" denied the request: Disallow delete setting name rwx-network
  ```



 </details>

#### Test Group 3: Dedicated mode with overlap validation

<details><summary>$\color{green}{\textsf{PASS}}$ Configure rwx-network in dedicated mode to test functionality  $~~$</summary>

1. Enable rwx-network setting
2. And set to `Dedicated Storage Network`
3. Provide the following settings

  ```
  {
    "share-storage-network": false,
    "network": {
      "vlan": 2011,
      "clusterNetwork": "mgmt",
      "range": "172.16.0.0/24"
    }
  }
  ```

4. Create a new storage class `longhorn-rwx` 

  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-rwx
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "3"
    staleReplicaTimeout: "2880"
    fromBackup: ""
    fsType: "ext4"
    nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  ```
  
  <img width="1347" height="518" alt="Image" src="https://github.com/user-attachments/assets/17bbfd17-89a0-4e20-8459-d34698a08a5e" />

5. Apply the following manifest to create a temporary PVC and pod

  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rwx-test-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn-rwx
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: rwx-test-pod
  spec:
    containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "echo RWX OK > /data/test.txt && cat /data/test.txt && sleep 3600"]
        volumeMounts:
          - name: data
            mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rwx-test-pvc
  ```

6. Ensure the pod reaches Running state and the volume is mounted successfully

```
hp-41-multindclstr-node-a:~ # kubectl get pod rwx-test-pod
NAME           READY   STATUS    RESTARTS   AGE
rwx-test-pod   1/1     Running   0          68s
```

7. Access the pod and test the read/write function 

  ```
  <<K9s-Shell>> Pod: default/rwx-test-pod | Container: test 
  / # cd /data/
  /data # ls
  lost+found  test.txt
  /data # cat test.txt
  RWX OK
  /data # vi test.txt
  /data # cat test.txt
  RWX OK
  Write RWX1
  ```


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Change rwx-storage IP Range to non-overlapping while having rwx volume attached  $~~$</summary>

  1. It will be rejected with a message listing the attached volume(s).
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: there are RWX volumes not in detached state: pvc-c2600ea7-ecc4-4e6f-b982-c5c497901a24
  ```
  
  <img width="1354" height="787" alt="Image" src="https://github.com/user-attachments/assets/090219f2-b69a-4ffa-9337-3e42bcaf1b77" />


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Change rwx-storage IP Range to overlapping while having rwx volume detached $~~$</summary>

  1. It will be rejected with an overlap error naming the conflicting setting.
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: rwx-network: the network configuration is overlapped with storage-network
  ```
  
  <img width="1349" height="730" alt="Image" src="https://github.com/user-attachments/assets/02030b36-8ef5-4115-a66c-5606b746629b" />

 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Change storage-network IP Range to overlapping while having rwx volume detached $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true.
  
  ```
  admission webhook "validator.harvesterhci.io" denied the request: exclude range 10.115.16.1/32 do not overlap include range 172.16.0.0/24
  ```

  <img width="1348" height="732" alt="Image" src="https://github.com/user-attachments/assets/8c4de590-dcf0-420e-8e2a-337835fe9d9b" />


 </details>


#### Test Group 4: Mode transitions & cleanup

<details><summary>$\color{green}{\textsf{PASS}}$ Switch rwx-network from dedicated to shared mode  $~~$</summary>

1. Can correctly switch rwx-network from dedicated to shared mode
2. Check the dedicated NAD is deleted


  https://github.com/user-attachments/assets/0518c92f-a4d2-46f3-b31e-1bfd7d49fbf7
  


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Switch rwx-network from shared to dedicated mode  $~~$</summary>

1. Can correctly switch rwx-network from shared to dedicated mode
2. Check a new dedicated NAD is created
  

  https://github.com/user-attachments/assets/349412a6-8172-4ce7-8a44-edf86dc3be35


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Reset rwx-network to {"share-storage-network": false} (no network) $~~$</summary>

  1. Check the dedicated NAD is removed and Longhorn's RWX network setting is cleared.
  

  https://github.com/user-attachments/assets/14bce1ea-223b-41b4-8c7e-e46efeedca89
  

 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Attempt to manually delete the NAD referenced by rwx-network $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true.
  
  ```
  hp-41-multindclstr-node-a:~ # kubectl delete network-attachment-definitions rwx-network-j7fr6 -n harvester-system
  Error from server (BadRequest): admission webhook "validator.harvesterhci.io" denied the request: cannot delete NetworkAttachmentDefinition harvester-system/rwx-network-j7fr6 which is used by Harvester setting 'rwx-network'
  ```

  https://github.com/user-attachments/assets/cb63ac5e-e937-4bcb-ba88-df5aa0ec0f13


 </details>



#### Test Group 2: Share mode with blocking conditions

<details><summary>$\color{green}{\textsf{PASS}}$ Configure rwx-network in shared mode to test functionality  $~~$</summary>

1. Enable rwx-network setting
2. And set to `Shared Storage Network`
  ```
  {
    "share-storage-network": true
  }
  ```

  <img width="1347" height="728" alt="Image" src="https://github.com/user-attachments/assets/dac2774d-17c2-45b1-9f29-219a66275231" />

3. Check Longhorn's endpoint-network-for-rwx-volume points to the same NAD as storage-network.

  <img width="1574" height="282" alt="Image" src="https://github.com/user-attachments/assets/7e023f20-a20d-4a4d-a560-692ffcf62413" />

4. Create a new storage class `longhorn-rwx` 

  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-rwx
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "3"
    staleReplicaTimeout: "2880"
    fromBackup: ""
    fsType: "ext4"
    nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  ```
  
  <img width="1347" height="518" alt="Image" src="https://github.com/user-attachments/assets/17bbfd17-89a0-4e20-8459-d34698a08a5e" />

5. Apply the following manifest to create a temporary PVC and pod

  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rwx-test-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn-rwx
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: rwx-test-pod
  spec:
    containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "echo RWX OK > /data/test.txt && cat /data/test.txt && sleep 3600"]
        volumeMounts:
          - name: data
            mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rwx-test-pvc
  ```

6. Ensure the pod reaches Running state and the volume is mounted successfully

  ```
  hp-41-multindclstr-node-a:~ # kubectl get pod rwx-test-pod
  NAME           READY   STATUS    RESTARTS   AGE
  rwx-test-pod   1/1     Running   0          81s
  hp-41-multindclstr-node-a:~ # kubectl get pvc rwx-test-pvc
  NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
  rwx-test-pvc   Bound    pvc-5f979803-0963-4bc0-9e18-45b59554bb64   1Gi        RWX            longhorn-rwx   <unset>                 89s
  ```

7. Access the pod and test the read/write function 

```
<<K9s-Shell>> Pod: default/rwx-test-pod | Container: test 
/ # cd /data
/data # ls
lost+found  test.txt
/data # cat test.txt
RWX OK
/data # vi test.txt
/data # cat test.txt
RWX OK
shared mode
```


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Clear storage-network, then attempt to enable share mode $~~$</summary>

  1. It will be rejected with storage-network is not set
  

    ```
    admission webhook "validator.harvesterhci.io" denied the request: storage-network is not set
    ```

    <img width="1594" height="783" alt="Image" src="https://github.com/user-attachments/assets/8a75e26a-5fd2-49b9-addf-80bdea697330" />



 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ With share mode active, attempt to clear storage-network $~~$</summary>

  1. It will be rejected with storage-network cannot be disabled while rwx-network has share-storage-network=true
  

    <img width="1348" height="733" alt="Image" src="https://github.com/user-attachments/assets/b440faf2-35e3-4352-8f0e-244ec4c55069" />
    
    https://github.com/user-attachments/assets/20855f05-4e97-4176-a0ba-8e1f511c6a7e


 </details>


#### Test Group 5: share-storgae-network is set to true after Upgrade
<details><summary>$\color{green}{\textsf{PASS}}$ After upgrade to v1.8.0-rc5, check the default share-storgae-network is true   $~~$</summary>


1. With storage network setup and enable the Storage Network for RWX Volume Enabled


<img width="1917" height="1093" alt="Image" src="https://github.com/user-attachments/assets/61e0bf9e-d8d6-4ba1-81de-e9dfa73af590" />

https://github.com/user-attachments/assets/75e70507-db93-4577-8982-9d01285339a6


https://github.com/user-attachments/assets/3fac252d-36b7-4641-a785-3276abd2e9db


2. After upgrade from v1.7.1 to v1.8.0-rc5

  <img width="1593" height="785" alt="Image" src="https://github.com/user-attachments/assets/03f1cc51-df05-4deb-a79a-92c22b2a2138" />
  
  <img width="1599" height="794" alt="Image" src="https://github.com/user-attachments/assets/9772fc88-0a3c-414f-9fca-ea3087596e27" />

3. check `rwx-network` setting, the default value now is {"share-storage-network": `true`}

  <img width="1599" height="783" alt="Image" src="https://github.com/user-attachments/assets/354a1249-b3cd-4468-8928-24cd1ba2d609" />
  


 </details>



### Result:  Rancher side

<details><summary>$\color{green}{\textsf{PASS}}$ (Shared Mode) Create and use RWX volume on RKE2 guest cluster with the same VLAN id of the running guest VM $~~$</summary>


1. With Harvester set rwx-network set to the Shared Storage Network

  <img width="1347" height="573" alt="Image" src="https://github.com/user-attachments/assets/60385f7e-6cdd-4d2b-9834-f145c1288534" />
  
  <img width="1591" height="783" alt="Image" src="https://github.com/user-attachments/assets/44e279fc-bf6d-466d-8143-929bb012bb58" />
  
2. And configure the RKE2 guest cluster and the storage network both on the same VLAN ID `2011`

  <img width="1596" height="782" alt="Image" src="https://github.com/user-attachments/assets/46f5615d-171a-4633-a23c-538c2f1780ee" />
  
  <img width="1596" height="784" alt="Image" src="https://github.com/user-attachments/assets/4f617c30-8f98-40f5-a957-4a27eaa69e2b" />

3. We can create the RWX volume on RKE2 guest cluster

  <img width="1597" height="782" alt="Image" src="https://github.com/user-attachments/assets/3f828023-70b0-4a6d-93f6-19693dcba160" />

4. And attached to the nginx pod
  
  <img width="1279" height="308" alt="Image" src="https://github.com/user-attachments/assets/9470a429-dda4-4022-87cf-4b52775af318" />

5. Can write file to the mount volume

  <img width="328" height="141" alt="Image" src="https://github.com/user-attachments/assets/45f8d90b-fa15-4ba4-9d32-1597ef238286" />


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ (Dedicated Mode) Create and use RWX volume on RKE2 guest cluster with the RWX network VLAN ID $~~$</summary>


1. With Harvester set rwx-network set to the Dedicated Storage Network

<img width="1598" height="788" alt="Image" src="https://github.com/user-attachments/assets/3b63b0da-e7ff-4986-9c94-4aa338723915" />

  <img width="1593" height="786" alt="Image" src="https://github.com/user-attachments/assets/f74ce749-3fcd-46cb-8d4a-470350d1715b" />

  
2. And configure the RKE2 guest cluster and the storage network both on the rwx-network VLAN ID `2017`

  <img width="1597" height="785" alt="Image" src="https://github.com/user-attachments/assets/75fd673d-16e1-40ad-9b77-7fe33ff05f35" />

3. We can create the RWX volume on RKE2 guest cluster

  <img width="1600" height="790" alt="Image" src="https://github.com/user-attachments/assets/2cd8dea3-329b-400b-883f-ab30b4295174" />

4. And attached to the nginx pod
  

  <img width="1600" height="782" alt="Image" src="https://github.com/user-attachments/assets/0bc5ff28-8fa6-4bac-ab97-16bce3f4d5e9" />
  
  <img width="1585" height="317" alt="Image" src="https://github.com/user-attachments/assets/a8f01ee2-8a65-4bdd-af17-5bc9772a0198" />


5. Can write file to the mount volume

  <img width="296" height="144" alt="Image" src="https://github.com/user-attachments/assets/91167b1d-fa14-418d-910e-649414387a1c" />


 </details>



### Test Information
* Test Environment: Two nodes bare-metal machines
* Harvester version: v1.8.0-rc2 and v1.8.0-rc5
* Rancher version: v2.14

### Verify Steps
<details><summary>Test steps </summary>

  Refer to: https://github.com/harvester/harvester/pull/10256#issue-4105234023

</details>
