### ISSUE TITLE
[BUG] DHCP Check for Default Route breaks when using Static IP Addresses in Automated Mode

### ISSUE THREAD

**Issue by tayterz2** [harvester/harvester#7280]
**Describe the bug**
When using the automated installer (either PXE or ISO) to install Harvester with *static* IP addresses, the installer fails with the error "No default route found. Please check the router setting on the DHCP server" regardless of the gateway setting.  Example cloud-init userdata file:

~~~~
#cloud-config
scheme_version: 1
token: token
os:
  password: password1234
  hostname: harvester1
  ntp_servers:
    - 192.168.4.1
    - 1.2.3.4
  dns_nameserver:
    - 192.168.4.200
    - 192.168.4.1
    - 1.2.3.4
install:
  automatic: true
  mode: create
  vip_mode: static
  vip: 192.168.4.200
  management_interface:
    interfaces:
      - name: enp1s0
    default_route: true
    method: static
    ip: 192.168.4.201
    subnet_mask: 255.255.255.0
    gateway: 192.168.4.1
    bond_options:
      mode: balance-tlb
      miimon: 100
~~~~~

**To Reproduce**
1.  Start Harvester installer in binary-only mode.
![Screenshot 2025-01-06 at 6 01 06 PM](https://github.com/user-attachments/assets/d2f7c3a5-7380-4b31-a177-190c76b8337a)
2.  Finish the installation with appropriate disk/password/etc values and eject the installation ISO after it completes/reboots.
3.  Create a configuration ISO with the above (or similar - static IP addresses) cloud-init file as user-data:
~~~~~
xorriso -outdev config.iso -map user-data /user-data -map meta-data /meta-data  -volid CIDATA
~~~~~
4.   Attach this ISO (as CDROM or USB) to the newly created binary-only install machine.
5.  Observe the "No default route found..." error when the automated installer starts.
![Screenshot 2025-01-06 at 6 10 48 PM](https://github.com/user-attachments/assets/54010296-0e05-442d-8f40-a8f74ea984b8)

**Expected behavior**
The automated installer should complete successfully.

**Environment**
 - Harvester ISO version: 1.4.0
 - Underlying Infrastructure: Several Dell, Intel, and VM-based environments (VMware and KVM)

**Comment by tayterz2** [comment]
See PR https://github.com/harvester/harvester-installer/pull/876

**Comment by bk201** [comment]
@starbops please help manage the issue status, thanks!

**Comment by brandboat** [comment]
Test OK, will close the issue.
Environment: build harvester iso based on https://github.com/harvester/harvester/commit/dd910aae134a1178a0a3a10904dc0d74bbcb9ba6, and follow the test step mentioned in issue description https://github.com/harvester/harvester/issues/7280#issue-2763501959.

```
➜ brandboat@suse  ~/SUSE/harvester/harvester-installer git:(v1.5) ✗ cat meta-data
instance-id: i-1234567890
local-hostname: my-cloud-vm
```

```
➜ brandboat@suse  ~/SUSE/harvester/harvester-installer git:(v1.5) ✗ cat user-data
#cloud-config
scheme_version: 1
token: token
os:
  password: password1234
  hostname: harvester1
  ntp_servers:
    - time1.google.com
    - time2.google.com
  dns_nameserver:
    - 8.8.8.8
    - 8.8.4.4
install:
  automatic: true
  mode: create
  vip_mode: static
  vip: 192.168.50.243
  management_interface:
    interfaces:
      - name: enp1s0
    default_route: true
    method: static
    ip: 192.168.50.201
    subnet_mask: 255.255.255.0
    gateway: 192.168.50.1
    bond_options:
      mode: balance-tlb
      miimon: 100
```

```
➜ brandboat@suse  ~/SUSE/harvester/harvester-installer git:(v1.5) ✗ xorriso -outdev config.iso -map user-data /user-data -map meta-data /meta-data  -volid CIDATA
xorriso 1.5.6 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'config.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  465g free
xorriso : UPDATE :       1 files added in 1 seconds
Added to ISO image: file '/user-data'='/home/brandboat/SUSE/harvester/harvester-installer/user-data'
xorriso : UPDATE :       1 files added in 1 seconds
Added to ISO image: file '/meta-data'='/home/brandboat/SUSE/harvester/harvester-installer/meta-data'
ISO image produced: 25 sectors
Written to medium : 192 sectors at LBA 32
Writing to 'config.iso' completed successfully.
```

![Image](https://github.com/user-attachments/assets/3900971d-be42-43ae-8bb6-32280482bd8a)
![Image](https://github.com/user-attachments/assets/6d753511-29b0-475d-a8ed-903c64823ff7)
![Image](https://github.com/user-attachments/assets/6c20b0b8-a891-46cb-8782-11b18f229714)
ssh login success.
```
➜ brandboat@suse  ~/SUSE/harvester/harvester-installer git:(v1.5) ✗ ssh rancher@192.168.50.201
(rancher@192.168.50.201) Password:
Last login: Mon Mar 10 04:27:09 2025 from 192.168.50.1
rancher@harvester1:~>
```
