### ISSUE TITLE
[QUESTION] Upgrading rancher-vcluster addon?

### ISSUE THREAD

**Issue by devclef** [harvester/harvester#7284]
Hi,

Is there any harvester specific instructions for upgrading the rancher that is part of the vcluster addon?

Or does one follow rancher's instructions here - https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades 

This is for a Harvester 1.4.0 cluster (recently upgraded from 1.3.2). The vcluster rancher version is 2.8.2 .

**Comment by innobead** [comment]
refer to https://github.com/harvester/experimental-addons/blob/main/rancher-vcluster/README.md. 

> Updates to rancherVersion in the contentValues can be used to trigger rancher upgrades in the cluster.

We might want to make the update mechanism of experimental add-ons clearer and easier to find in the Harvester doc. cc @harvester/maintainer @harvester/tpm

**Comment by devclef** [comment]
Thanks for reply @innobead 

The value field is 'grayed out' when navigating to 'edit' on the addon.

Ofcourse one can (probably) modify it by using Edit Yaml. 

here is what valueContents has at the moment. Perhaps it is as simple as incrementing rancherVersion? But then why would it be grayed out on the ui?

```
 hostname: rancher.my.domain
    rancherVersion: v2.8.2
    bootstrapPassword: woops
    vcluster:
      image: rancher/k3s:v1.27.10-k3s2
    sync:
      ingresses:
        enabled: 'true'
    init:
      manifestsTemplate: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cattle-system
        ---
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager
          labels:
            certmanager.k8s.io/disable-validation: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cert-manager
          namespace: kube-system
        spec:
          targetNamespace: cert-manager
          repo: https://charts.jetstack.io
          chart: cert-manager
          version: v1.5.1
          helmVersion: v3
          set:
            installCRDs: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/stable/
          chart: rancher
          version: {{ .Values.rancherVersion }}
          set:
            ingress.tls.source: rancher
            hostname: {{ .Values.hostname }}
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: {{ .Values.bootstrapPassword | quote }}
          helmVersion: v3
```
