### ISSUE TITLE
[FEATURE] Add build catalog job to harvester-ui-extension CI

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#7353]
**Is your feature request related to a problem? Please describe.**

It would be useful for users how want to use air-gapped environment to build the registry in the CI https://github.com/rancher/dashboard/blob/master/.github/workflows/build-extension-catalog.yml when we publish new verisons.
This way the users could just download the docker image and push the images to their own registry

**Comment by a110605** [comment]
Not necessary to include this CI flow in v1.5.0. Update milestone to v1.6.0.

**Comment by a110605** [comment]
Need re-prioritize to include this CI flow in v1.5.0 or not.

**Comment by bk201** [comment]
@a110605 We need every item that can ease the extension deployment for our users.
What's the drawback if this issue is not implemented?

**Comment by Yu-Jack** [comment]
Done. 

- Tag: [rancher/harvester-ui-catalog:1.5.0-rc1](https://hub.docker.com/layers/rancher/harvester-ui-catalog/1.5.0-rc1/images/sha256-76706a2741ff2fd6b0496f352944d4e0c7c6c23caf45c69cc6ea0ba8af16bbea)
- Action: https://github.com/harvester/harvester-ui-extension/actions/runs/13851741955/job/38760127079


Demo

![Image](https://github.com/user-attachments/assets/878de5bf-4668-4ae0-b603-29c617be87ca)

![Image](https://github.com/user-attachments/assets/89ec0ad6-88b8-4703-bc6a-d0ab84826d56)

cc @a110605 @bk201

**Comment by brandboat** [comment]
Hi @Yu-Jack, I followed the test steps in https://github.com/harvester/harvester/issues/7353#issuecomment-2705643425, but after clicking the install button in Extensions, an error showed up. Am I do something wrong?
Here is the cmd I run rancher `docker run -d --restart=unless-stopped --name=rancher-head -p 80:80 -p 443:443 --privileged rancher/rancher:v2.11-head`

![Image](https://github.com/user-attachments/assets/69545c50-4d41-4e27-92c5-7104d4346389)

**Comment by Yu-Jack** [comment]
@brandboat This one https://docs.harvesterhci.io/v1.5/airgap/#installation-failed can help you. I think v-cluster might not have this kind of questions. Let me do some experiment with v-cluster.

**Comment by brandboat** [comment]
Thank you @Yu-Jack, the doc really helps!
> Ensure that svc.namespace is accessible from Rancher. If that endpoint is not accessible, you can directly use a cluster IP such as 10.43.33.58:8080/plugin/harvester-1.0.3.
---
The harvester UIPlugin object in my environment
```yaml
apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
...
  name: harvester
  namespace: cattle-ui-plugin-system
...
spec:
  plugin:
    endpoint: http://ui-extension-harvester-ui-extension-svc.cattle-ui-plugin-system:8080/plugin/harvester-1.5.0-rc1
...
```
But I can't find the `ui-extension-harvester-ui-extension-svc` endpoint in `cattle-ui-plugin-system` namespace, only `harvester-ui-catalog-svc` shows up.
```
bash-4.4# k get endpoints -n cattle-ui-plugin-system
NAME                       ENDPOINTS         AGE
harvester-ui-catalog-svc   10.42.0.35:8080   61m
```
After changing the endpoint to `http://10.42.0.35:8080/plugin/harvester-1.5.0-rc1`, I can access the harvester ui.

**Comment by brandboat** [comment]
Now I'm using vagrant to setup rancher, and follow the steps in https://github.com/harvester/harvester/issues/7353#issuecomment-2705643425 to install harvester-ui-extenstion, but I'm still encountering the same installation failed issue, though I can use the workaround mentioned in https://github.com/harvester/harvester/issues/7353#issuecomment-2739061368 to mitigate the installation failed issue. I'm wondering is this expected? Or should we consider it as a bug? c.c @khushboo-rancher, @noahgildersleeve.

Note: the endpoint in harvester UIPlugin seems wrong, and should be `http://harvester-ui-catalog-svc.cattle-ui-plugin-system:8080/plugin/harvester-1.5.0-rc1` instead.

**Comment by Yu-Jack** [comment]
~~@brandboat The endpoint is not quite wrong. It's from the image name. If your image name is `harvester-ui-catalog`, it'll be `harvester-ui-catalog-svc`. If image name is `ui-plugin-catalog`, it'll be `ui-plugin-catalog-svc`. I'll revise the endpoint part and use template to describe that.~~ Sorry, I'm wrong. I misunderstood it. The endpoint isn't correct.

For the installation failed, currently I can't use v-cluster to install it. I'll keep trying that.

**Comment by Yu-Jack** [comment]
After discussion with @brandboat.

> For the installation failed, currently I can't use v-cluster to install it. I'll keep trying that.

This one has been verified by @brandboat. Please paste screenshot of the endpoint of UIPlugin here. Thanks!

The endpoint in the Harvester documentation is correct because customers uses `rancher/ui-plugin-catalog` to install Harvester UI Extension in air gapped environment.

However, `rancher/harvester-ui-catalog` should be only used by QAs. So, you shouldn't see any `harvester-ui-plugin` word in Harvester document.

So, if you try to verify this issue using Harvester document, you need to treat all `ui-plugin-catalog` word as `harvester-ui-plugin`. Otherwise, it might be weird for you.

Generally, we can close this issue. Thanks!

**Comment by brandboat** [comment]
Thank for the explanation @Yu-Jack.

Test OK, will close the issue.

### Test environment
- ipxe environment
- harvester v1.5-head (https://github.com/harvester/harvester/commit/c2e6602e90590aea5e6d80d08cbc0c697f6186d1), single node
- rancher: v2.11.0-rc5, below is my rancher config in [settings.yml](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/settings.yml)
  ```
  rancher_config:
    enabled: true
    version: v2.11-head
  
    # IP should be out of harvester_network_config.dhcp_server.range and does not
    # conflict with other static IPs (e.g. Harvester).
    ip: 192.168.100.141
    password: rancher
  
    # Refer resource requirements to
    # https://ranchermanager.docs.rancher.com/pages-for-subheaders/installation-requirements
    cpu: 2
    memory: 4096
  ```

### Test steps
- Go to extension, and click Manage Extension Catalogs  on right top corner.
- Import this image rancher/harvester-ui-catalog:1.5.0-rc1
- Wait until harvester ui extension pop up in available tab 
- Click install in harvester ui extenstion
- Search `UIPlugins`, and switch to `All Namespaces`, click harvester UIPlugin.
- Click `Edit YAML`, modify the endpoint to `http://harvester-ui-catalog-svc.cattle-ui-plugin-system:8080/plugin/harvester-1.5.0-rc1`
![Image](https://github.com/user-attachments/assets/547fb989-2b83-444e-af15-7fe0cf09cc6c)
- Verify the error message is gone in harvester ui extension
![Image](https://github.com/user-attachments/assets/2aa3b09d-fb5e-4d14-b76f-d0042fedce02)
- Import harvester to rancher, and verify the harvester dashboard shows up.
![Image](https://github.com/user-attachments/assets/564325fe-0c81-4ae6-a003-b6c93a0f0cd8)

**Comment by Yu-Jack** [comment]
> But I can't find the ui-extension-harvester-ui-extension-svc endpoint in cattle-ui-plugin-system namespace, only harvester-ui-catalog-svc shows up.

Sorry. I thought endpoint was correct by using `rancher/harvester-ui-catalog`. I was wrong and misunderstood before.

Due to this reason, I'll reopen issue. It seems that it would be better to use `rancher/ui-extension-harvester-ui-extension` as image repo name. Otherwise, QA needs to modify endpoint **each time** when testing this. I don't think it's a good idea. 

Thanks @a110605 @brandboat

**Comment by Yu-Jack** [comment]
Please use this tag [`rancher/ui-extension-harvester-ui-extension:1.5.0-rc3`](https://hub.docker.com/layers/rancher/ui-extension-harvester-ui-extension/1.5.0-rc3/images/sha256-43790ca2d298d2c8127afea4a368cd972fdc9f2cf8a291265f954064fcf7edad). 

The result is:

```
bash-4.4# k get svc -A | grep extension
cattle-system                     api-extension                             ClusterIP   10.43.103.53    <none>        5555/TCP,6666/TCP        64s
cattle-system                     imperative-api-extension                  ClusterIP   10.43.222.83    <none>        6666/TCP                 7m55s
cattle-ui-plugin-system           ui-extension-harvester-ui-extension-svc   ClusterIP   10.43.228.45    <none>        8080/TCP                 6m19s
bash-4.4# k get uiplugins harvester -n cattle-ui-plugin-system -o yaml | grep endpoint
    endpoint: http://ui-extension-harvester-ui-extension-svc.cattle-ui-plugin-system:8080/plugin/harvester-1.5.0-rc3
bash-4.4#
```

**Comment by brandboat** [comment]
Test successful!

### Test environment
- ipxe environment
- harvester v1.5.0-rc3, single node
- rancher: v2.11-head, below is my rancher config in [settings.yml](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/settings.yml)
  ```
  rancher_config:
    enabled: true
  
    version: v2.11-head
    k3s_channel: v1.30
    repo: https://releases.rancher.com/server-charts/latest
  
    # Reserved IP for Rancher. Do not conflict with DHCP range and other reserved IPs.
    ip: 192.168.100.141
    hostname: rancher.192.168.100.141.sslip.io
    password: rancher
    cpu: 2
    memory: 4096
  ```

### Test steps
- Go to extension, click `Manage Extension Catalogs` on right top corner.
- Import image `rancher/ui-extension-harvester-ui-extension:1.5.0-rc3`
- Wait until harvester ui extension pop up in the `available` tab 
- Click `install` in harvester ui extension
- Import harvester to rancher, and verify the harvester dashboard shows up.

![Image](https://github.com/user-attachments/assets/f4059b12-7a1e-454a-b004-6c25df22c8e5)
![Image](https://github.com/user-attachments/assets/3265013a-b168-4e91-b33a-422bbd418dc0)
