### ISSUE TITLE
[FEATURE] Support Network policies for micro segmentation of VMs using KubeOVN

### ISSUE THREAD

**Issue by rrajendran17** [harvester/harvester#7381]
We could achieve VM isolation using virtual switch concept in KubeOVN.
But implementing network policies facilitate further micro segmentation of VMs by isolating VMs within the same L2/Virtual Switch.

**Describe the solution you'd like**
a.KubeOVN makes use of Kubernetes Network Policy CRD to implement ACL rules allowing/restricting traffic between VMs.

(Or)
b.KubeOVN subnet acl can be used to isolate traffic between VMs within the same subnet.

**Describe alternatives you've considered**
OVN kubernetes.Ovn kubernetes uses MultiNetworkPolicy CRD to implement network policies per vswitch.

**Additional context**
Network policy yaml example:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ip-block
spec:
  podSelector:
    matchLabels:
      name: access-control
  ingress:
    - from:
        - ipBlock:
            cidr: 10.10.0.0/16
  egress:
    - to:
        - ipBlock:
            cidr: 20.20.0.0/16

VMs could be labeled and used in network policy, so that the ACL rule is applied specific to those VMs.
ingress and egress rules allow traffic to and from particular ip block and rest of the traffic is dropped.
Using above VMs can be isolated within the same L2, by specifying the VMs and IPs which has to communicate.

subnet acl example:

apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: acl
spec:
  allowEWTraffic: false
  acls:
    - action: drop
      direction: to-lport
      match: ip4.dst == 10.10.0.2 && ip
      priority: 1002
    - action: allow-related
      direction: from-lport
      match: ip4.src == 10.10.0.3 && ip
      priority: 1002
  cidrBlock: 10.10.0.0/24

The above allows traffic from 10.10.0.3, but blocks traffic from 10.10.0.2

**Comment by rrajendran17** [comment]
The following could be used to filter traffic per vswitch using acls added to subnet.
https://kubeovn.github.io/docs/stable/en/guide/subnet/#subnet-acl

**Comment by rrajendran17** [comment]
Need for micro segmentation between VMs:

```
VM isolation could be achieved using VLANs traditionally or using virtual switches in KubeOVN.
Implementing network policies allow micro segmentation of VMs by isolating VMs within 
the same L2 network/Virtual Switch.
```

Proposal:
```
- Use KubeOVN's subnet ACL to apply ACL rules per subnet
- Use K8s Network Policy to allow/deny traffic to a particular VM 
```

Goals:
```
Users will be able to restrict access between VMs within same logical network

option 1 : Using kubeOVN subnet ACL
https://kubeovn.github.io/docs/stable/en/guide/subnet/#subnet-acl

- match [source mac ,destination mac,source ip,destination ip,ip protocol,application port numbers]
- action [ drop,allow]
- direction[ingress,egress]
- priority[int value]

Example:

apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: acl
spec:
  acls:
    - action: drop
      direction: to-lport
      match: ip4.dst == 10.10.0.2 && ip
      priority: 1002
    - action: allow-related
      direction: from-lport
      match: ip4.src == 10.10.0.2 && ip
      priority: 1002
  cidrBlock: 10.10.0.0/24
  gateway: 10.10.0.1
  provider: vswitch1.default.ovn


option 2: Using k8s Network policy crd
https://kubernetes.io/docs/concepts/services-networking/network-policies/
These rules are by default deny, so rules must be added for allowing traffic.

- direction[ingress,egress]
- ipBlock [cidr]
- ports [protocol,port]
- podSelector[pod label] - policy applied only to those pods matching the label

Example:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ip-block
spec:
  ingress:
    - from:
        - ipBlock:
            cidr: 172.20.10.0/30
        - ipBlock:
            cidr: 10.52.0.0/16
  egress:
    - to:
        - ipBlock:
            cidr: 172.20.10.0/30
        - ipBlock:
            cidr: 10.52.0.0/16

```

User stories:

```
a.Isolate traffic between VMs within same subnet/vswitch using subnet ACLs
- Deny traffic between VMs using srcip,dstip
- Deny traffic between VMs using direction to-lport,from-lport
- Deny traffic between VMs using higher priority rule
- Deny traffic between VMs using srcport,dstport
- Deny traffic between VMs using ip protocol type

b. Isolate traffic between subnets used by VMs
- Deny traffic to a subnet by toggle private to true in that subnet
- Allow specific subnet to communicate by adding subnet ranges to allowSubnets

c.Allow traffic between only certain VMs within the same subnet
- Create K8s Network Policy matching cidr using ip-block and using labels as pod selectors (vm.kubevirt.io/name)
- The policy is applied to VMs only matching the selectors

d. Isolate traffic between VMs by vxlan network
- Deny/Allow traffic from specific subnets
- Deny/Allow traffic from specific tunnel endpoints
- Deny/Allow traffic matching vxlan headers
- Deny/Allow traffic matching vxlan udp port number
```

**Comment by rrajendran17** [comment]
Example using a k8s network policy with pod selector:

```
a.Create NAD vswitch1
b.Create subnet vswitch1 using provider vswitch1
c.Create 8 VMs (vm1-vswitch1 .... vm8-vswitch1) 172.20.10.3/24 to 172.20.10.10/24

d.Validate ping between VMs - ping will be successful between all VMs.

e.Create the following network policy and apply it.

kubectl get networkpolicy ip-block -o yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"ip-block","namespace":"default"},"spec":{"egress":[{"to":[{"ipBlock":{"cidr":"172.20.10.0/30"}},{"ipBlock":{"cidr":"10.52.0.0/16"}}]}],"ingress":[{"from":[{"ipBlock":{"cidr":"172.20.10.0/30"}},{"ipBlock":{"cidr":"10.52.0.0/16"}}]}]}}
  creationTimestamp: "2025-06-19T20:58:59Z"
  generation: 5
  name: ip-block
  namespace: default
  resourceVersion: "108030691"
  uid: 45be43b4-79c7-49db-a1f1-7273534a5642
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 172.20.10.0/29
    - ipBlock:
        cidr: 10.52.0.0/16
  ingress:
  - from:
    - ipBlock:
        cidr: 172.20.10.0/29
    - ipBlock:
        cidr: 10.52.0.0/16
  podSelector:
    matchLabels:
      vm.kubevirt.io/name: vm8-vswitch1
  policyTypes:
  - Ingress
  - Egress

f.Based on the pod selector value the above policy is only attached to vm8-vswitch1
g.The above policy means vm8-vswitch1 vm will be able to communicate only with vm1-vswitch1,vm2-vswitch1,vm3-vswitch1,vm4-vswitch1,vm5-vswitch1 as 172.20.10.0/29 network is allowed and remaining traffic is restricted.
h.Ping works between all the VMs except vm6-vswitch1 and vm7-vswitch1 will not be able to communicate with vm8-vswitch1.

```

**Comment by rrajendran17** [comment]
Only UI changes are required for this task.

For subnet ACL from the UI dashboard: example format

```
subnets -> 
               acls ->
                        name: acl-1 
                        direction [from-lport,to-lport] 
                        protocol version [v4,v6]
                        ip protocol [udp,tcp]
                        port number
                        .
                        .
                        .
                        protocol version [v4,v6]
                        ip protocol [udp,tcp]
                        port number
                        combine rules [AND,OR]
                        action[drop,allow-related]
                        .
                        .
                        .
                        priority[value]
                        name: acl-N
```
                        
 The match condition in subnet acl is derived using the following logic
 ```
 The  most  important  components of match expression are comparisons  between  symbols   and   constants,   e.g.   ip4.dst   ==
 192.168.0.1,  ip.proto == 6, arp.op == 1, eth.type == 0x800. The logical AND operator && and logical OR operator ||  can  combine
 comparisons into a larger expression.          
```
Reference:   https://www.ovn.org/support/dist-docs/ovn-sb.5.html   
 
For k8s network policy from the UI dashboard, a new tab has to be created for network policy.

```
Network Policies ->
                          name: policy-1
                          direction [ingress,egress] 
                          ipBlock[cidr]
                          ip protocol [udp,tcp]
                          port number
                          podSelector[key:value]
        
                          .
                          .
                          .
                          name: policy-N
```

**Comment by rrajendran17** [comment]
Network Policy on Subnets: (drop/allow-related based on ip address)

Create:

```
curl -k --location --request POST 'https://10.115.54.251/apis/kubeovn.io/v1/subnets' \
--header 'Authorization: Bearer token-6q5s8:rcl8qjbbcgs54lb2k8k44557j587xdtnvdhsmf9bqxv6tmksdjwpqr' \
--header 'Content-Type: application/json' \
--data-raw '{"apiVersion":"kubeovn.io/v1","kind":"Subnet","metadata":{"annotations":{},"name":"acl"},"spec":{"acls":[{"action":"drop","direction":"to-lport","match":"ip4.dst == 10.10.0.2","priority":1002},{"action":"allow-related","direction":"from-lport","match":"ip4.src == 10.10.0.2","priority":1002}],"cidrBlock":"10.10.0.0/24","gateway":"10.10.0.1","provider":"vswitch1.default.ovn"}}'
```

Update on existing subnet with acls:

Add acl for dropping all traffic from and to 172.20.10.6 within subnet vswitch1:
```
curl -k --location --request PATCH 'https://10.115.54.251/apis/kubeovn.io/v1/subnets/vswitch1' \
--header 'Authorization: Bearer token-6q5s8:rcl8qjbbcgs54lb2k8k44557j587xdtnvdhsmf9bqxv6tmksdjwpqr' \
--header 'Content-Type: application/merge-patch+json' \
--data-raw '{"apiVersion":"kubeovn.io/v1","kind":"Subnet","metadata":{"annotations":{},"name":"vswitch1"},"spec":{"acls":[{"action":"drop","direction":"to-lport","match":"ip4.dst == 172.20.10.6","priority":1002},{"action":"drop","direction":"from-lport","match":"ip4.src == 172.20.10.6","priority":1002}],"cidrBlock":"172.20.10.0/24","gateway":"172.20.10.1","provider":"vswitch1.default.ovn"}}'
```
Delete:

`Removing the acl field from subnet spec will remove the acl rules applied and traffic will resume.`

Note: Network policy can be updated on running VMs

**Comment by rrajendran17** [comment]
No back end changes required.UI issue tracked via https://github.com/harvester/harvester/issues/8683.
Refer this https://github.com/harvester/harvester/issues/7381#issuecomment-2989335247 for UI changes required.Hence resolving this issue.

**Comment by Vicente-Cheng** [comment]
Although the UI is not yet ready and has been rescheduled for 1.7.0, we need the documentation to inform users on how to configure it in a headless way.

**Comment by Vicente-Cheng** [comment]
Hi @rrajendran17, 
Just a reminder, we still need a document for this issue.

Thanks!

**Comment by Vicente-Cheng** [comment]
Hi @rrajendran17, 
Just another reminder. We need the document for this feature before v1.6.0, as it is related to the highlight feature.
Please work on it with high priority.
Thanks!

**Comment by rrajendran17** [comment]
> Hi [@rrajendran17](https://github.com/rrajendran17), Just another reminder. We need the document for this feature before v1.6.0, as it is related to the highlight feature. Please work on it with high priority. Thanks!

@Vicente-Cheng sure will send it for review asap.Thanks

**Comment by innobead** [comment]
https://github.com/harvester/docs/pull/843 doc is ready for testing. @rrajendran17 remember to move the issue to ready for testing next time. 

Pleaes also update https://github.com/harvester/harvester/issues/7381#issuecomment-3161819743 first. 

cc @harvester/release

**Comment by rrajendran17** [comment]
@innobead https://github.com/harvester/docs/pull/843 is not merged yet, still in review.I thought we would move after its merged.

**Comment by albinsun** [comment]
Test FAIL, create VM using subnet with ACL stuck at `Starting`.

Please help to check, thx.



## Environment
* `harvester-v1.6.0-rc6`
  * Profile: 2 nodes AMD64 Bare-metal HPE ProLiant DL360 
  * ui-source: `Auto`


## Test Cases
Refer example 1 in https://docs.harvesterhci.io/v1.6/networking/kubeovn-subnet-acls/#examples
1. <details>
   <summary> ✔️ Create subnet with YAML contians ACL
   </summary>

   * Enable **kubeovn-operator**
     <img width="1563" height="1035" alt="Image" src="https://github.com/user-attachments/assets/b6f0cfa1-e2ce-494e-b49c-8d7a458781aa" />

   * VM Network
     <img width="1563" height="513" alt="Image" src="https://github.com/user-attachments/assets/c2be0ace-0fc7-4fa9-9629-f069f90cc619" />

   * VPC
     <img width="1563" height="513" alt="Image" src="https://github.com/user-attachments/assets/ec08a6fa-d10b-4b43-9442-b20cae88ae0b" />

   * Subnet YAML
      ```
      apiVersion: kubeovn.io/v1
      kind: Subnet
      metadata:
        name: vswitch1
      spec:
        acls:
        - action: drop
          direction: to-lport
          match: ip4.dst == 172.20.10.0/30
          priority: 1005
        - action: drop
          direction: from-lport
          match: ip4.src == 172.20.10.0/30
          priority: 1005
        cidrBlock: 172.20.10.0/24
        excludeIps:
        - 172.20.10.1
        gateway: 172.20.10.1
        gatewayNode: ""
        natOutgoing: false
        private: false
        protocol: IPv4
        provider: vswitch1.default.ovn
        vpc: vpc1
      ```

   * Subnet
     <img width="1563" height="513" alt="Image" src="https://github.com/user-attachments/assets/09390f4a-10a7-492c-aca9-9fb57b696d23" />
     <img width="1563" height="684" alt="Image" src="https://github.com/user-attachments/assets/9245457d-4cb6-4231-988c-c6d9fc2a87dd" />
   </details>

1. <details open>
   <summary> ❌ Create a VM using VM network <i>vswitch1</i>
   </summary>

   > failed to setup network for sandbox ... error adding container to network "vswitch1": RPC failed; request ip return 500 configure nic pod37a8eec1ce1 for pod vm-vswitch1/default failed: gateway check of 172.20.10.1
   <img width="1563" height="867" alt="Image" src="https://github.com/user-attachments/assets/1117a0ee-478f-427a-b440-1d46967fc943" />

   > Add eth0 [10.52.1.x/32] from k8s-pod-network
   <img width="1563" height="867" alt="Image" src="https://github.com/user-attachments/assets/9889a9df-ea23-4f73-b97d-6181df1c670b" />

   </details>




## Logs
* Support bundle: [supportbundle_179299d5-98a2-4520-b43c-3eb65783d5d2_2025-08-18T05-53-45Z.zip](https://github.com/user-attachments/files/21828300/supportbundle_179299d5-98a2-4520-b43c-3eb65783d5d2_2025-08-18T05-53-45Z.zip)

**Comment by rrajendran17** [comment]
@albinsun since the following rule blocks the communication with gw 172.20.10.1, the VMs creation in the subnet "vswitch1" will be affected.

```
  - action: drop
    direction: to-lport
    match: ip4.dst == 172.20.10.0/30
    priority: 1005
  - action: drop
    direction: from-lport
    match: ip4.src == 172.20.10.0/30
```

you could either add an explicit allow rule to allow "172.20.10.1" with higher priority as follows or add acls to subnet "vswitch1" after all the VM creation.

```
 - action: allow
    direction: to-lport
    match: ip4.dst == 172.20.10.1
    priority: 1006
  - action: allow
    direction: from-lport
    match: ip4.src == 172.20.10.1
    priority: 1006
  - action: drop
    direction: to-lport
    match: ip4.dst == 172.20.10.0/30
    priority: 1005
  - action: drop
    direction: from-lport
    match: ip4.src == 172.20.10.0/30
    priority: 1005
```

**Comment by albinsun** [comment]
> [@albinsun](https://github.com/albinsun) since the following rule blocks the communication with gw 172.20.10.1, the VMs creation in the subnet "vswitch1" will be affected.
> ...

Hi @rrajendran17, the behavior seems not quite stable.
I tried to create a new VM on vswitch1, it seems works and get IP, but when I repeat same steps for a new subnet vswitch2, the problem happen again. vm-vswitch2 seems keep scanning 10.52.1.x/32 over an hour but will eventually get IP.

https://github.com/user-attachments/assets/d0ca2fd6-6bfd-4a44-92dc-28f056fdd6fd

<img width="1563" height="882" alt="Image" src="https://github.com/user-attachments/assets/7ed897c3-5105-4914-9009-fffca33e6942" />

over an hour

<img width="1563" height="432" alt="Image" src="https://github.com/user-attachments/assets/7b036d97-6f18-447a-aed5-3c7dbf1c10e6" />

Note that VM will eventually get the IP

<img width="1563" height="460" alt="Image" src="https://github.com/user-attachments/assets/a7a4c687-5c3f-4671-94b4-380e092b6175" />

**Comment by rrajendran17** [comment]
@albinsun I checked the issue and looks to be a undesired/unstable behaviour with kubeovn.
The ip must be allocated for VM secondary interfaces when a higher priority rule is added and must be stuck in container creating state when gw ip is blocked completely.But currently with GW IP blocked, there is a failure for sometime and later ip is successfully allocated.

Workaround: Create all VMs and then add the subnet ACLs for range 172.20.x.x/30 or you could entirely use different ip sets to test the behaviour.This should not block your testing https://github.com/harvester/harvester/issues/7381 and you can continue to test this feature.

Meanwhile I will debug this further with kubeovn team and update.
FYR created a GH issue https://github.com/harvester/harvester/issues/8935

**Comment by albinsun** [comment]
Test PASS, close as done.


## Environment
* `harvester-v1.6.0-rc6`
  * Profile: 2 nodes AMD64 Bare-metal HPE ProLiant DL360 
  * ui-source: `Auto`


## Test Scenarios
Ref. https://docs.harvesterhci.io/v1.6/networking/kubeovn-subnet-acls/#examples
### 🟢 example 1: All virtual machines within the 172.20.10.0/24 subnet, except those with the addresses 172.20.10.2 and 172.20.10.3 in the subnet range 172.20.10.0/30, are allowed to communicate with each other.
1. <details>
   <summary> ✔️ Create a subnet
   </summary>

   * Enable **kubeovn-operator**
     <img width="1563" height="1035" alt="Image" src="https://github.com/user-attachments/assets/b6f0cfa1-e2ce-494e-b49c-8d7a458781aa" />

   * Subnet YAML
      ```
      apiVersion: kubeovn.io/v1
      kind: Subnet
      metadata:
        name: vswitch10
      spec:
        acls:
        cidrBlock: 172.20.10.0/24
        excludeIps:
        - 172.20.10.1
        gateway: 172.20.10.1
        gatewayNode: ""
        natOutgoing: false
        private: false
        protocol: IPv4
        provider: onet-c10.default.ovn
        vpc: c10
      ```

   * NAD, Subnet
     <img width="1563" height="517" alt="Image" src="https://github.com/user-attachments/assets/af784fb1-bf5e-4792-aa27-3418d3bec990" />
     <img width="1563" height="517" alt="Image" src="https://github.com/user-attachments/assets/310b104e-d9dd-4ae4-8b2a-4e7e625ab66a" />

   </details>

1. <details>
   <summary> ✔️ Create VMs using VM network, they can communicate to each other.
   </summary>

   * VMs
     <img width="1563" height="550" alt="Image" src="https://github.com/user-attachments/assets/102cd2c0-2911-4b24-9fb2-e34e454d6c22" />

   * Communicate
     <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/8b896940-cc3e-40a9-8f34-b8d38ead496d" />
   </details>

1. <details>
   <summary> ✔️ Adding ACL to subnet via YAML, target /30 VMs are blocked. 
   </summary>

   * Adding ACL
     <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/5463f52f-8f7e-4956-8ada-1357afbc0729" />

   * Communication
     <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/32c52f84-ed62-478f-b1c1-b4de253306e7" />
   </details>



### 🟢 example 2: All virtual machines within the 172.20.10.0/24 subnet, except those with the address 172.20.10.3, are allowed to communicate with each other. 
1. <details>
   <summary> Edit subnet's ACL via YAML
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/efe84507-3a2f-4946-a80c-23ea6a7faaad" />
   </details>

1. <details>
   <summary> In /30, only 2 is allowed
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/9075d0b8-2d9d-4e47-8760-053a9dabf13b" />
   </details>



### 🟢 example 3: Virtual machines with the address 172.20.10.2 are allowed to communicate with other virtual machines. However, traffic in the opposite direction is blocked.
1. <details>
   <summary> Edit subnet's ACL via YAML
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/a418ce4a-d75d-4cc4-bdf9-0c49e45f377c" />
   </details>

1. <details>
   <summary> In /30, 2 can ping others but others can not ping 2.
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/02087047-43f1-4c68-a8c1-e60c238a0a71" />
   </details>



### 🟢 example 4: TCP traffic originating from port 9501 and ip address 172.20.10.4 is blocked on the vswitch1 subnet.
1. <details>
   <summary> Edit subnet's ACL via YAML
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/ccba414b-1987-483b-847e-014f9132e12e" />
   </details>

1. <details>
   <summary> 4:9501 can not access 2 and 3, but 2 and 3 can access 4.
   </summary>

   <img width="1563" height="879" alt="Image" src="https://github.com/user-attachments/assets/c9f2e542-6718-4712-8d14-f4541e1c2cf8" />
   </details>
