### ISSUE TITLE
[ENHANCEMENT] SB Enhancements (NS selection and timeout)

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#7385]
**Is your enhancement related to a problem? Please describe.**

A support bundle only collects selected namespaces unless the user configures additional namespaces in the settings. It's not intuitive in the UX. Also the customer wants to be able to customize the timeout value.

**Describe the solution you'd like**

Enhancement support bundle collection with:
- Add the harvester cluster name and version to the support bundle name
- Make it possible to select the namespaces when a support bundle is created. Even add "all namespaces" button. This will reduce the the load on both sides, because it will reduce the repeated creation of "wrong" support bundles.
- The dynamic choice should not change the default namespaces configured in settings.
- Increase the default support bundle timeout to something bigger, e.g. 30 min

**Describe alternatives you've considered**

**Additional context**

SURE-9519

**Comment by Yu-Jack** [comment]
Current flow is that GUI creates a `supportbundle` resource with description and URL in spec field. 

Note environments used in SB for future usage:

```yaml
# request from frontend
{
    "apiVersion": "harvesterhci.io/v1beta1",
    "type": "harvesterhci.io.supportbundle",
    "kind": "SupportBundle",
    "metadata": {
        "name": "bundle-1kzct",
        "namespace": "harvester-system"
    },
    "spec": {
        "issueURL": "",
        "description": "test"
    }
}
```

```yaml
# deployment 
image: rancher/support-bundle-kit:v0.0.46
env: 
- name: SUPPORT_BUNDLE_TARGET_NAMESPACES
  value: cattle-dashboards,cattle-fleet-local-system,cattle-fleet-system,cattle-fleet-clusters-system,cattle-monitoring-system,fleet-local,harvester-system,local,longhorn-system,cattle-logging-system,cattle-provisionin    g-capi-system
- name: SUPPORT_BUNDLE_NAME
  value: bundle-0hl85
- name: SUPPORT_BUNDLE_DESCRIPTION
  value: {input from UI}
- name: SUPPORT_BUNDLE_ISSUE_URL
  value: {input from UI}
- name: SUPPORT_BUNDLE_DEBUG
  value: "true"
- name: SUPPORT_BUNDLE_MANAGER_POD_IP
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.podIP
- name: SUPPORT_BUNDLE_IMAGE
  value: rancher/support-bundle-kit:v0.0.46
- name: SUPPORT_BUNDLE_IMAGE_PULL_POLICY
  value: IfNotPresent
- name: SUPPORT_BUNDLE_NODE_SELECTOR
  value: harvesterhci.io/managed=true
- name: SUPPORT_BUNDLE_EXCLUDE_RESOURCES
  value: settings.harvesterhci.io,authconfigs.management.cattle.io,authtokens.management.cattle.io,samltokens.management.cattle.io,tokens.management.cattle.io,users.management.cattle.io
- name: SUPPORT_BUNDLE_EXTRA_COLLECTORS
  value: harvester
- name: SUPPORT_BUNDLE_TAINT_TOLERATION
  value: ':'
- name: SUPPORT_BUNDLE_NODE_TIMEOUT
  value: 30m0s
```


```yaml
# node agent
  - name: SUPPORT_BUNDLE_HOST_PATH
    value: /host
  - name: SUPPORT_BUNDLE_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName
  - name: SUPPORT_BUNDLE_MANAGER_URL
    value: http://10.52.1.215:8080
  - name: SUPPORT_BUNDLE_COLLECTOR # yes, there is no value for this field
```
