### ISSUE TITLE
[ENHANCEMENT] Burn In Testing Of Harvester Node's Underlying Hardware Prior To Install

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7423]
**Is your enhancement related to a problem? Please describe.**
A user may not know that their underlying hardware does not meet requirements.

**Describe the solution you'd like**
At Harvester node installation inception, a flow that might take the following shape.
1. Harvester Nodes that are purposefully doing something like `harvester_checks_install_skip_hardware_testing` **are permanently forever "tainted" with an unmovable/immutable kind of tag, that would manifest itself as a present entity inside a generated support-bundle & through the UI of Harvester Dashboard (only allowing removal via Upgrade to "new" or same version of Harvester [xref- 4.])**... perhaps the `harvester_checks_install_skip_hardware_testing` element could be split into different categories like:
```yaml
os:
  install:
    hardware_checks_install:
      - name: disks-random-iops
        skip: false
      - name: smartctl-ssd-disk-test
        skip: false
      - name: cpu-stress-test
        skip: false
      - name: network-load-test
        skip: false
      - name: memory-test
        skip: false
      - name: pci-gpu-test
        skip: false
### etc... 
```
2. If the user opts to "not" skip the hardware checks install, the node then undergoes the hardware checks, if it fails any of the hardware checks it will allow the user to continue the install -> **but again will "taint" with an immutable/unmovable kind of tag on the node that it did indeed fail 1 or more of the checks,** but also giving the option of the user to cancel install maybe additionally a configuration of something like `harvester_checks_install_always_fail: false` would allow the checks to pass (install to continue) but if the bool was flipped to `true` (maybe by default it's true) we do not continue installing harvester
3. Upgrades from prior versions of Harvester, would run the checks on the underlying infrastructure, always allowing the Harvester install to continue but tainting the nodes that fail given tests.  
4. Failed node taints can **ONLY** be removed if they're taken offline from the cluster, have hardware change (eg memory replaced, disks replaced, etc.) and then upgraded to "new" or "same" versions of Harvester 

**Describe alternatives you've considered**
Users validating their hardware prior to install.

**Additional context**
This can help speedup the pipeline & re-enforce validation of bare-metal infrastructure that is absolutely needed to support Harvester prior to even installing Harvester.  Additionally it helps identify immediate areas when support-bundles are generated - if taints in any area are present.
