### ISSUE TITLE
[BUG] The VM importer fails to check the OpenStack source network exists

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#7432]
**Describe the bug**
During the preflight check the VM importer tries to make sure the specified `spec.networkMapping[x].sourceNetwork` in `VirtualMachineImport` exists for OpenStack imports.
The existing implementation seems not to work anymore with the latest OpenStack versions.

The solution is to make use of the NewNetworkV2 ServiceClient to query for the specified source network.

**To Reproduce**
Try to import a VM from a up-to-date OpenStack installation.

**Expected behavior**
The import should not fail.

**Support bundle**
n/a

**Environment**
 - Harvester ISO version: 1.4.x
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe-examples 1-node cluster

**Additional context**
n/a

**Comment by innobead** [comment]
Moving to 1.5.0 instead. 

cc @bk201 @tserong

**Comment by irishgordo** [comment]
@votdev When running something like:
```
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2024-stable
  namespace: default
spec: 
  virtualMachineName: "testjammy"
  sourceCluster: 
    name: mike-demo-2024-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable
  namespace: default
spec: 
  virtualMachineName: "jammytest"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable-new
  namespace: default
spec: 
  virtualMachineName: "newtestjammy"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```
I'm not getting denied at a webhook level like validatingwebhookconfiguration - as I would guess since there is no network-mapping it would reject the request.
Where [networkMapping, seems to be required](https://docs.harvesterhci.io/v1.5/advanced/addons/vmimport#virtualmachineimport).

Running off of `main-head` for the vm-import-controller, on the deployment.

Is that to be expected?

**Comment by irishgordo** [comment]
Or actually, I guess it is fine, as they imported the vms and they just got mapped to the `pod-network` / management Network / masquerade

**Comment by irishgordo** [comment]
Off of `main-head` for the deployment/vm-import-controller & with the modifications to the ClusterRole for harvester-vm-import-controller-cluster-role to house what's off of main + the storage.k8s.io content.

I can see in the logs of the deployment that it did it's preflight check and is not allowing the VM due to the destination network not existing:

```
kSource                                                                                                                                               
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:41:38Z" level=error msg="error syncing 'default/mr-jammy-2023-stable': handler vir
tualmachine-import-job-change: network-attachment-definitions.k8s.cni.cncf.io \"doesntexist\" not found, requeuing"                                   
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:41:38Z" level=info msg="Running preflight checks ..." name=mr-jammy-2023-stable-ne
w namespace=default spec.virtualMachineName=newtestjammy                                                                                              
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:41:38Z" level=error msg="Failed to get destination network 'default/doesntexist': 
network-attachment-definitions.k8s.cni.cncf.io \"doesntexist\" not found" name=mr-jammy-2023-stable-new namespace=default spec.sourcecluster.kind=Open
stackSource   
```

As `doesntexist` doesn't exist 😄

**Comment by irishgordo** [comment]
I can also validate that if the `sourceNetwork` doesn't exist that the logs are mentioning that as well:
```go
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:18Z" level=info msg="Checking the source network as part of the preflight check
s" name=mr-jammy-2023-stable-new namespace=default sourceNetwork=source-network-doesnt-exist                                                          
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:19Z" level=error msg="Failed to perform source cluster specific preflight check
s: source network 'source-network-doesnt-exist' not found" name=mr-jammy-2023-stable-new namespace=default spec.sourcecluster.kind=OpenstackSource    
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:19Z" level=error msg="error syncing 'default/mr-jammy-2023-stable-new': handler
 virtualmachine-import-job-change: source network 'source-network-doesnt-exist' not found, requeuing"                                                 
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:22Z" level=info msg="Running preflight checks ..." name=mr-jammy-2024-stable na
mespace=default spec.virtualMachineName=testjammy                                                                                                     
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=info msg="Checking the source network as part of the preflight check
s" name=mr-jammy-2024-stable namespace=default sourceNetwork=source-network-doesnt-exist                                                              
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=error msg="Failed to perform source cluster specific preflight check
s: source network 'source-network-doesnt-exist' not found" name=mr-jammy-2024-stable namespace=default spec.sourcecluster.kind=OpenstackSource        
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=error msg="error syncing 'default/mr-jammy-2024-stable': handler vir
tualmachine-import-job-change: source network 'source-network-doesnt-exist' not found, requeuing"                                                     
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=info msg="Running preflight checks ..." name=mr-jammy-2023-stable na
mespace=default spec.virtualMachineName=jammytest                                                                                                     
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=info msg="Checking the source network as part of the preflight check
s" name=mr-jammy-2023-stable namespace=default sourceNetwork=source-network-doesnt-exist                                                              
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=error msg="Failed to perform source cluster specific preflight check
s: source network 'source-network-doesnt-exist' not found" name=mr-jammy-2023-stable namespace=default spec.sourcecluster.kind=OpenstackSource        
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:23Z" level=error msg="error syncing 'default/mr-jammy-2023-stable': handler vir
tualmachine-import-job-change: source network 'source-network-doesnt-exist' not found, requeuing"                                                     
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:24Z" level=info msg="Running preflight checks ..." name=mr-jammy-2023-stable-ne
w namespace=default spec.virtualMachineName=newtestjammy                                                                                              
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:24Z" level=info msg="Checking the source network as part of the preflight check
s" name=mr-jammy-2023-stable-new namespace=default sourceNetwork=source-network-doesnt-exist                                                          
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:24Z" level=error msg="Failed to perform source cluster specific preflight check
s: source network 'source-network-doesnt-exist' not found" name=mr-jammy-2023-stable-new namespace=default spec.sourcecluster.kind=OpenstackSource    
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:24Z" level=error msg="error syncing 'default/mr-jammy-2023-stable-new': handler
 virtualmachine-import-job-change: source network 'source-network-doesnt-exist' not found, requeuing"     
```

**Comment by irishgordo** [comment]
**Validation Issue**
@votdev I am however noticing an issue with something like this:

```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable
  namespace: default
spec: 
  virtualMachineName: "jammytest"
  networkMapping:
  - sourceNetwork: "source-network-doesnt-exist"
    destinationNetwork: "default/vmnet"
  - sourceNetwork: "shared"
    destinationNetwork: "default/nonet"
  - sourceNetwork: "shared"
    destinationNetwork: "default/vmnet"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
```

I'm seeing various errors of:
```go
2025-02-08T00:45:54.595028546Z harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:54Z" level=error msg="error syncing 'default/mr-
jammy-2023-stable': handler virtualmachine-import-job-change: source network 'source-network-doesnt-exist' not found, requeuing"                      
2025-02-08T00:45:55.069903964Z harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:55Z" level=info msg="Running preflight checks ..
." name=mr-jammy-2023-stable-new namespace=default spec.virtualMachineName=newtestjammy                                                               
2025-02-08T00:45:55.190809009Z harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:55Z" level=info msg="Checking the source network
 as part of the preflight checks" name=mr-jammy-2023-stable-new namespace=default sourceNetwork=source-network-doesnt-exist                           
2025-02-08T00:45:55.251042225Z harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:45:55Z" level=error msg="Failed to perform source c
luster specific preflight checks: source network 'source-network-doesnt-exist' not found" name=mr-jammy-2023-stable-new namespace=default spec.sourcec
luster.kind=OpenstackSource       
```
And:
```go
2025-02-08T00:50:50.351888065Z harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:50:50Z" level=error msg="error syncing 'default/mr-
jammy-2023-stable': handler virtualmachine-import-job-change: source network shared appears multiple times in vm spec, requeuing"      
```

But let's say I have in OpenStack, `jammytest` that has two IP addresses (two `shared` network interfaces, eg: 192.168.233.204 & 192.168.233.209).

So:
```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable-new
  namespace: default
spec: 
  virtualMachineName: "jammytest"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/mgmtnet"
  - sourceNetwork: "shared"
    destinationNetwork: "default/vmnet"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
```

And `mgmtnet` & `vmnet` both exist.

I'm seeing in the logs:
```go
harvester-vm-import-controller-8675bb474c-tts7k time="2025-02-08T00:58:08Z" level=error msg="error syncing 'default/mr-jammy-2023-stable-new': handler
 virtualmachine-import-job-change: source network shared appears multiple times in vm spec, requeuing" 
```

Where the VM on OpenStack's side is valid, and attempting to import it with it's two nics that map to "different" destinationNetworks is a problem.

Potentially the same could be trying to map two "shared" nics to the "same" destination network.

![Image](https://github.com/user-attachments/assets/5608270e-9dc3-4369-a20d-d21b4d4ce265)
![Image](https://github.com/user-attachments/assets/1de4e655-a707-47b7-ad46-5b1dc4654a7d)

**Comment by irishgordo** [comment]
What will happen then if we morph the previous YAML to:

```yaml

---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mr-jammy-2023-stable-new
  namespace: default
spec: 
  virtualMachineName: "jammytest"
  networkMapping:
  - sourceNetwork: "shared"
    destinationNetwork: "default/mgmtnet"
  sourceCluster: 
    name: mike-demo-2023-stable
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
```

So even though at the OpenStack level there are "two" nics both at the  "Shared" network.
We won't see the "error" anymore about "multiple shared" - Since we only listed one.
However, the VM Import Controller becomes opinionated, it will import the VM, then take both of it's Shared Network NICs, and map them to `mgmtnet`

![Image](https://github.com/user-attachments/assets/37774039-41f5-4f6a-a04c-7b7e44ec0d43)
