### ISSUE TITLE
[BUG]  Time Zone always show `Guest agent required`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#745]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/115690094-4a789780-a38f-11eb-8de4-3fa847b6774a.png)

**To Reproduce**
1.  Create a vm (install qemu-guest-agent)

**Expected behavior**

if no timezone field in guestOsinfo, use `kernelRelease` instead
![image](https://user-images.githubusercontent.com/15064560/115690123-52383c00-a38f-11eb-8be1-eadfc7976946.png)
```yaml
    guestOSInfo:
      id: ubuntu
      kernelRelease: 5.4.0-72-generic
      kernelVersion: '#80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021'
      name: Ubuntu
      prettyName: Ubuntu 20.04.2 LTS
      version: "20.04"
      versionId: "20.04"
```
**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
