### ISSUE TITLE
[FEATURE] Terraform Provider: Addons

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7491]
**Is your feature request related to a problem? Please describe.**
Allow for standard & experimental addons to be controlled as a Terraform resource(s).

**Describe the solution you'd like**
Something to avoid having to rely entirely on the Kubernetes API.
In the scenario a user wants to have a Harvester cluster respond to Addons, like vCluster for instance.
To accomplish this now it's kinda cultivated with something like the following.

Generalized script to apply via `kubectl` the expiremental addon & then run the customized yaml as a config:
```bash
#! /usr/bin/bash
kubectl apply -f https://raw.githubusercontent.com/harvester/experimental-addons/main/rancher-vcluster/rancher-vcluster.yaml
sleep 5
kubectl apply -f harvester-vcluster-enablement.yaml
```
Whereas, `harvester-vcluster-enablement.yaml` would look something like this:
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: true
  repo: https://charts.loft.sh
  version: "v0.19.0"
  chart: vcluster
  valuesContent: |-
    hostname: "rancher.192.168.104.126.sslip.io"
    rancherVersion: "v2.9.3"
    bootstrapPassword: "testtesttest"
    vcluster:
      image: rancher/k3s:v1.29.8-k3s1
    sync:
      ingresses:
        enabled: "true"
    init:
      manifestsTemplate: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cattle-system
        ---
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager
          labels:
            certmanager.k8s.io/disable-validation: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cert-manager
          namespace: kube-system
        spec:
          targetNamespace: cert-manager
          repo: https://charts.jetstack.io
          chart: cert-manager
          version: v1.15.3
          helmVersion: v3
          set:
            installCRDs: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/stable/
          chart: rancher
          version: {{ .Values.rancherVersion }}
          set:
            ingress.tls.source: rancher
            hostname: {{ .Values.hostname }}
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: {{ .Values.bootstrapPassword | quote }}
          helmVersion: v3
```

But maybe instead the resource is just kind of set up something like:

```terraform
resource "harvester_addon" "vcluster" {
  name = "rancher-vcluster"
  namespace = "rancher-vcluster"
  experimental = true
  spec =  <<EOF
enabled: true
repo: https://charts.loft.sh
version: "v0.19.0"
chart: vcluster
valuesContent: |-
  hostname: "rancher.192.168.104.126.sslip.io"
  rancherVersion: "v2.9.3"
  bootstrapPassword: "testtesttest"
  vcluster:
    image: rancher/k3s:v1.29.8-k3s1
  sync:
    ingresses:
      enabled: "true"
EOF
} 
```

**Describe alternatives you've considered**
Using the Kubernetes API.
