### ISSUE TITLE
[BUG] harvester 1.4.1: Ubuntu 24.04/Centos cannot display IP

### ISSUE THREAD

**Issue by mustang2247** [harvester/harvester#7520]
**Describe the bug**

harvester 1.4.1: Ubuntu 24.04/Centos cannot display IP

![Image](https://github.com/user-attachments/assets/14c56cd8-7c57-4818-8ee0-68186f505fb8)

![Image](https://github.com/user-attachments/assets/056d068b-9d04-4552-ade6-c60ba0501b4a)

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: harvester 1.4.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ProLiant DL380e Gen8

**Additional context**

**Comment by shkatara** [comment]
@mustang2247 I also have the same issue. 

The VMI.Status.Conditions say that my agent is connected, I have the qemu-guest-agent installed and running, and I only get IPv6 and not IPv4 in VMI.Status.Interfaces. 

Following is the VMI.Status.conditions and VMI.Status.Interfaces. 

```
conditions:
  - lastProbeTime: "2025-03-04T15:21:03Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
interfaces:
  - infoSource: domain, guest-agent, multus-status
    interfaceName: enp1s0
    ipAddress: 2a00:6480:8748:fa4:c81f:d8ff:fe62:d7f3
    ipAddresses:
      - 2a00:6480:8748:fa4:c81f:d8ff:fe62:d7f3
    mac: ca:1f:d8:62:d7:f3
    name: default
    queueCount: 1
```

**Comment by mlhynfield** [comment]
Hi! I'm also running into this issue but I have one addition. It seems that disabling ipv6 in cloud-init does not resolve the issue:

```yaml
runcmd:
- - sysctl
    - -w
    - net.ipv6.conf.all.disable_ipv6=1
```

VMI.Status.Interfaces:

```yaml
interfaces:
  - infoSource: domain, guest-agent, multus-status
    interfaceName: enp1s0
    ipAddress: fdd7:f41c:9c42:574d:5c95:d3ff:fe18:b4eb
    ipAddresses:
    - fdd7:f41c:9c42:574d:5c95:d3ff:fe18:b4eb
    mac: 5e:95:d3:18:b4:eb
    name: nic-0
    queueCount: 1
  - infoSource: guest-agent
    interfaceName: calif43c83fe774
    mac: ee:ee:ee:ee:ee:ee
```

On the example node:

```bash
~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 5e:95:d3:18:b4:eb brd ff:ff:ff:ff:ff:ff
    inet **redacted ipv4** metric 100 brd **redacted** scope global dynamic enp1s0
       valid_lft 86171sec preferred_lft 86171sec
5: calif43c83fe774@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-e28604e5-ea9b-64b1-3eba-630f5c891a1b
```

During RKE2 cluster provisioning via the Harvester node driver sporadically nodes will experience this issue causing a provisioning timeout on the node, and notably upon provisioning failure and VM deletion the affected node is not removed from the target RKE2 cluster, requiring manual deletion via `kubectl delete node`
