### ISSUE TITLE
[BUG] Restoring VM Backup to another Namespace or another Cluster is Broken

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#7539]
**Describe the bug**
Restoring VM Bacup to another Namespace or another Cluster is Broken

Please check the LH issue https://github.com/longhorn/longhorn/issues/10366 for details

**Related LH issue**
https://github.com/longhorn/longhorn/issues/10366

**Comment by WebberHuang1118** [comment]
Per discussion with @bk201 and @FrankYang0529 

We will update the VolumeSnapshotConten's `snapshotHandle` to the correct format `bak://<backupvolume name>/<backup name>` with the following scenarios:
- For the newly created `VolumeSnapshotContent`, the Harvester controller will deploy it with the right `snapshotHandle` content
- For the existing `VolumeSnapshotContent`, the Harvester will update it on-demand
  - Once the VM Backup Restore is requested, the Harvester will check if the `VolumeSnapshotContent`'s `snapshotHandle` is in the wrong format `bs://<pvc name>/<backup name>`, then apply the following operations:
    - Getting the `backupvolume` name from LH `backup` CR 
    - Creating a new `VolumeSnapshot` and `VolumeSnapshotContent`
    - Connecting the original `VMBackup` CR with the new `VolumeSnapshot` and `VolumeSnapshotContent`

**Comment by WebberHuang1118** [comment]
I had the verification to confirm whether [our proposed method](https://github.com/harvester/harvester/issues/7539#issuecomment-2642316452) works

**Prerequisite**
- Building a Harvester cluster with the master branch
- Updating Harvester deployment with the image `webberhuang/harvester:issue-7539-head`
  - This contains the modification to the Harvester controller to match https://github.com/mantissahz/longhorn/blob/5972d80c833cc7fc7d7df3757f0b0d0558f14f7c/enhancements/20240926-multiple-backup-targets-support.md
  - This contains PR to have[ the correct VolumeSnapshotContent's snapshotHandle](https://github.com/WebberHuang1118/harvester/commit/487de8c15e7845b8c1881d6c1b8f9d1191d60aaf) for the case `restoring VMBackup to another namespace` 
-  Updating LH manager daemonset with the image `phanle1010/longhorn-manager:v1.8.0-10303`
   - This contains the fix for https://github.com/longhorn/longhorn/issues/10303
- Configuring backup target with an NFS server
- Starting a VM `vm1`
  - Creating a PVC `os-vol` from a VM image
  - Using PVC `os-vol` to  create VM `vm1`
- Creating a VMBackup `vm1-b`
- Disconnecting the backup target and deleting VMBackup `vm1-b`
- Reconnecting backup target and confirming VMBackup `vm1-b` is recovered
- There should be a VolumeSnapshotContent with incorrect snapshotHandle format `bs://<PVC name>/<backup name>`

**Simulating Harvester Controller Update SnapshotHandle at Runtime**
- Deleting VolumeSnapshotContent `vm1-b-volume-os-vol-vsc`
- Deleting VolumeSnapshot `vm1-b-volume-os-vol`
- Applying a new VolumeSnapshotContent `vm1-b-volume-os-vol-vsc`
  ```
  apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshotContent
  metadata:
    name: vm1-b-volume-os-vol-vsc
    ownerReferences:
    - apiVersion: harvesterhci.io/v1beta1
      controller: true
      kind: VirtualMachineBackup
      name: vm1-b
      uid: <VMBackup UID>
  spec:
    deletionPolicy: Delete
    driver: driver.longhorn.io
    source:
      snapshotHandle: bak://<volume name>/<backup name>
    volumeSnapshotClassName: longhorn
    volumeSnapshotRef:
      name: vm1-b-volume-os-vol
      namespace: default
  ```
- Applying a new VolumeSnapshot `vm1-b-volume-os-vol`
  ```
  apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    name: vm1-b-volume-os-vol
    namespace: default
    ownerReferences:
    - apiVersion: harvesterhci.io/v1beta1
      controller: true
      kind: VirtualMachineBackup
      name: vm1-b
      uid: <VMBackup UID>
  spec:
    source:
      volumeSnapshotContentName: vm1-b-volume-os-vol-vsc
    volumeSnapshotClassName: longhorn
  ```
- Restoring a new VM from VMBackup `vm1-b`, the resorting should success

**Simulatring Restoring VMBackup to another Namespace**
- Following above steps
- Restoring VMBackup `vm-b1` to another namespace, the restoring should success
  - Since we already apply the [PR](https://github.com/WebberHuang1118/harvester/commit/487de8c15e7845b8c1881d6c1b8f9d1191d60aaf)

**Summary**
Based on the above verification, [our proposed method](https://github.com/harvester/harvester/issues/7539#issuecomment-2642316452) should work.

Hi @FrankYang0529,

When you're available, can you help to check the above verification methods in case I missed anything? 
This will affect the schedule for LH v1.8.1. Many thanks. cc @bk201
