### ISSUE TITLE
[BUG] vm-import-controller off of main-head complains rbac issues w/ clusterrole for storageclasses

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7543]
**Describe the bug**
When using `main-head` as the image for vm-import-controller deployment, the pre-existing rbac in ClusterRole has an issue.
Even after updating it to `main` there are the errors of:

```go
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:12:37.301855       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:12:37.301947       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope               
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:12:38.887006       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:12:38.887042       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope               
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:12:40.558411       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:12:40.558452       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope               
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:12:46.293712       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:12:46.293763       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope               
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:12:55.649095       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:12:55.649166       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope               
harvester-vm-import-controller-867bd7f9cf-b5g44 W0208 00:13:12.220624       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:harvester-system:harvester-vm-import
-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope                                                 
harvester-vm-import-controller-867bd7f9cf-b5g44 E0208 00:13:12.220670       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:ha
rvester-system:harvester-vm-import-controller" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope 
```

And:

```go
harvester-vm-import-controller-7b9cdc96c6-bv7sz E0208 00:15:17.311468       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: unknown (get storageclasses.meta.k8s.io)                                                                   
harvester-vm-import-controller-7b9cdc96c6-bv7sz E0208 00:15:20.506710       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: unknown (get storageclasses.meta.k8s.io)                                                                   
harvester-vm-import-controller-7b9cdc96c6-bv7sz E0208 00:15:24.407654       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.4/tools/cache/reflector
.go:169: Failed to watch *v1.StorageClass: unknown (get storageclasses.meta.k8s.io)                                                                   
                                                                                      
```

**Workaround**
Errors can be resolved by modifying the RBAC for the ClusterRole/harvester-vm-import-controller-role to have the content from `main` branch.  And also to hold the content of:

```yaml
- apiGroups:                                                                                                                                          
  - storage.k8s.io                                                                                                                                    
  resources:                                                                                                                                          
  - '*'                                                                                                                                               
  verbs:                                                                                                                                              
  - list                                                                                                                                              
  - watch                                                                                                                                             
```

**To Reproduce**
1. Have deployment utilize main-head image for vm-import-controller
2. Notice the logs
3. Modify the RBAC in the cluster role to give it more permissions 
4. Error disappears at the controller level

**Expected behavior**
No errors at the controller level

**Environment**
 - Harvester ISO version: v1.5.0-dev-20250203
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal
