### ISSUE TITLE
[BUG] Parsing error in the Managed DHCP agent image name

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#7549]
**Describe the bug**

If the Managed DHCP agent image name contains an explicitly specified port number for the image registry, the parsing cannot be done correctly. For instance, if the image name is `myregistry.local:5000/rancher/harvester-vm-dhcp-agent:v0.3.3`, the controller manager will error out with the following error:

![Image](https://github.com/user-attachments/assets/3caaa93f-16ce-4564-85f9-a78a56a9c32a)

This results in the controller manager pod in a crashing loop.

**To Reproduce**
1. Prepare a v1.4.1 Harvester cluster
2. Create the Managed DHCP Addon CR with the following content
   ```
   apiVersion: harvesterhci.io/v1beta1
   kind: Addon
   metadata:
     name: harvester-vm-dhcp-controller
     namespace: harvester-system
     labels:
       addon.harvesterhci.io/experimental: "true"
   spec:
     enabled: false
     repo: https://charts.harvesterhci.io
     version: 0.3.3
     chart: harvester-vm-dhcp-controller
     valuesContent: |
       agent:
         image:
           repo: myregistry.local:5000/rancher/harvester-vm-dhcp-agent
   ```
3. Enable the add-on
4. The controller manager pod will be in crashing loop

Note that we don't check if the agent pod can be created or not because we don't set up a proper private registry.

**Expected behavior**

The controller manager pod should be running fine.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.1 (with Managed DHCP v0.3.3)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

This is originally found in https://github.com/harvester/harvester/issues/6942#issuecomment-2642457834. To work around it, please use port 80/443 for the container registry (so you don't have to specify the port number explicitly).
