### ISSUE TITLE
[BUG] VM controller calculates ResourceQuota with wrong assumption

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#7585]
**Describe the bug**

When testing https://github.com/harvester/harvester/pull/7504, an interesting bug is observed:

>time="2025-02-11T10:33:58Z" level=debug msg="stop the VM vm-test2-1 in namespace test2 due to insufficient resource quota: cpu insufficient resources due to resource quota"

The webhooks does not complain about resourcequota, but the vm_controller does.

```
pkg/webhook/resources/virtualmachinerestore/validator.go:	if err := v.vmrCalculator.CheckIfVMCanStartByResourceQuota(vm); err != nil {
pkg/webhook/resources/virtualmachinerestore/validator.go:	if err := v.vmrCalculator.CheckIfVMCanStartByResourceQuota(vm); err != nil {
pkg/webhook/resources/virtualmachine/validator.go:	return v.rqCalculator.CheckIfVMCanStartByResourceQuota(vm)

pkg/controller/master/virtualmachine/vm_controller.go:	err := h.vmrCalculator.CheckIfVMCanStartByResourceQuota(vm)
```

https://github.com/harvester/harvester/blob/d50fd7ea563b467e7b1e7258256c7e8e439dd7ec/pkg/controller/master/virtualmachine/vm_controller.go#L278

The root cause is:

When webhook check the new VM RQ, there is no running PODs yet, but when vm_controller does same, there maybe a POD of this VM, the `CheckIfVMCanStartByResourceQuota` does not exlclude current VM's POD from the used quota, and finally get a wrong decision.

**To Reproduce**
1. Create a namespace with RQ `CPU 2500m, memory 3Gi`
2. Create a VM on this namespace with request: `cpu 2, memory 2Gi`; the webhook does not complain RQ, but the VM is put to failure status and has error `cpu insufficient resources due to resource quota`

vm:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/insufficient-resource-quota: cpu insufficient resources due to
      resource quota
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"test3-vm1-disk-0-br8du","annotations":{"harvesterhci.io/imageId":"default/image-v7rlb"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-v7rlb"}}]'

  creationTimestamp: "2025-02-11T17:28:31Z"

  generation: 2
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: linux
  name: test3-vm1
  namespace: test3-ns

  uid: 7b299f18-bdd6-4c04-9588-331f03bb1199
spec:
  runStrategy: Halted
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: test3-vm1
    spec:
  ...
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 125m
            memory: 1365Mi
```

namespace RQ used is empty
![Image](https://github.com/user-attachments/assets/82fe4283-5df3-4bf8-a49a-105132ea5a0b)

VM can't start
![Image](https://github.com/user-attachments/assets/57203e34-a0ab-4609-b3eb-20fc37cd5814)

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.5.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

It is easy to reproduce when the whole cluster is powered off and powered on again:

![Image](https://github.com/user-attachments/assets/94f04d7c-7c39-4bb0-b239-2267b6c11fcc)
