### ISSUE TITLE
[DOC] Mention To Users About charts.harvesterhci.io For AirGapping

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7588]
**Is your doc request related to a problem? Please describe or add the related issue ID.**
So currently it looks like there's no mention of:
- https://charts.harvesterhci.io/
Which is a good charts repo that holds the charts.harvesterhci.io/index.yaml for helm. 

**Describe the solution you'd like**
It could be good to mention this if users are intending to maybe airgap experimental addons with [Hauler](https://docs.hauler.dev/docs/airgap-workflow)

## Additional context
```yaml
---
apiVersion: content.hauler.cattle.io/v1 
kind: Charts
metadata:
  name: "vmdhcp-controller-charts"
spec:
  charts:
    - name: harvester-vm-dhcp-controller
      repoURL: https://charts.harvesterhci.io/
      version: 0.3.3
--- 
```
With something like that ^ from above, Hauler, and the user knowing about charts.harvesterhci.io -> the user then would be able to airgap the chart of the experimental addons.
Like something like:
- `tar xvf harvester-vm-dhcp-controller-0.3.3.tgz`
- `cd /home/ubuntu/fileserver/harvester-vm-dhcp-controller && helm package . -d serv && helm repo index serv`

Given that the user has the images that the HelmChart relies on already airgapped ^
