### ISSUE TITLE
[BUG] Harvester v1.4-head & Rancher v2.9-head || v2.8-head || v2.10-head Downstream RKE1 Node Template Not Seeing Proper Cloud-Config

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7592]
**Describe the bug**

https://github.com/user-attachments/assets/6078b1f5-e5af-44fd-8219-09d291a8f5a3

Pretty much in an RKE1 Cloud Config section of the node-template, it does not bring in the Harvester cloud-config user-data properly.
It ends up ignoring all the `packages`.

**To Reproduce**
1. Build an RKE1 Node Template that references a user-data cloud-config on Harvester and that cloud-config data should have at least 3 or more packages.
2. It won't display all of them, the cloud-config userdata is being rendered incorrectly

**Workaround**
- just paste in the cloud-config from Harvester into Rancher

**Expected behavior**
It to be rendered correctly.

**Environment**
 - Harvester ISO version: v1.4-head
- Rancher (docker install) version: v2.9-head || v2.8-head
 - Underlying Infrastructure: HP DL360 Gen9

**Additional context**

```
diff what-i-would-expect-that-rke1-node-template-would-see-when-rendering-cloud-configuration-template-userdata.txt what-rke1-sees-for-node-template-when-rendering-the-user-data.txt 
8,13d7
<   - apt-transport-https
<   - ca-certificates
<   - curl
<   - cowsay
<   - gnupg-agent
<   - software-properties-common
15,17d8
<   - neovim
<   - htop
<   - net-tools
25c16
<     - --now
---
>     - '--now'
```

**desired cloud-config**

```yaml
#cloud-config
password: password
chpasswd:
  expire: false
ssh_pwauth: true
package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - cowsay
  - gnupg-agent
  - software-properties-common
  - qemu-guest-agent
  - neovim
  - htop
  - net-tools
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service

```

**whats rendered cloud-config via selection drop down**

```yaml
#cloud-config
password: password
chpasswd:
  expire: false
ssh_pwauth: true
package_update: true
packages:
  - qemu-guest-agent
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
```
