### ISSUE TITLE
[BUG] cloud config byte limit

### ISSUE THREAD

**Issue by emctl** [harvester/harvester#760]
**Describe the bug**
Anytime I try to use non base64 encoded strings  in my cloud config section for VM creation I get: `admission webhook "virtualmachine-validator.kubevirt.io" denied the request: spec.template.spec.volumes[1].cloudInitNoCloud userdata exceeds 2048 byte limit. Should use UserDataSecretRef for larger data.`

I have tried to base64 encode this as kubvirt does but still no luck.

**To Reproduce**
Steps to reproduce the behaviour:
1. attempt to create a vm with multiline cloud config

**Expected behaviour**

The VM creation to take my k3os values from [this](https://github.com/rancher/k3os#sample-configyaml) and provision (even fail at provision if cloud init is wrong.
 
**Log**
N/A

**Environment:**
 - Harvester ISO version: v0.1.0
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal

**Additional context**
![image](https://user-images.githubusercontent.com/8000237/116001305-b820ff80-a5eb-11eb-8508-d88aeb38bf75.png)

I am trying to spin up some K3OS agents/server using [this](https://github.com/rancher/k3os#sample-configyaml) and was trying to play with what kubevirt had [here](https://github.com/kubevirt/kubevirt/blob/master/docs/cloud-init.md)

**Comment by futuretea** [comment]
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init-userdata-as-k8s-secret
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init-network-config-as-k8s-secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-userdata-secret
  namespace: default
data:
  userdata: IyEvYmluL2Jhc2gKZWNobyAiSGkgZnJvbSBzdGFydHVwIHNjcmlwdCEiCg==
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-networkdata-secret
  namespace: default
data:
  networkdata: bmV0d29yazoKICB2ZXJzaW9uOiAxCiAgY29uZmlnOgogIC0gdHlwZTogcGh5c2ljYWwKICBuYW1lOiBldGgwCiAgc3VibmV0czoKICAgIC0gdHlwZTogZGhjcAo=
```

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
  name: demo
  namespace: default
spec:
  template:
    spec:
      domain:
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
      volumes:
      - name: rootdisk
         dataVolume:
          name: rootdisk
      - name: cloudinitdisk
         cloudInitNoCloud:
           secretRef:
             name: my-userdata-secret
           networkDataSecretRef:
             name: my-networkdata-secret
```
