### ISSUE TITLE
[BUG] Upgrade from v1.4.1 to v1.4.2-rc1 stuck in first node `pre-drained`

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#7647]
**Describe the bug**

When upgrade the three nodes Harvester from `v1.4.1` to `v1.4.2-rc1`. 
The upgrade process of the upgrading node stuck in the first node `Pre-drained` state 

![Image](https://github.com/user-attachments/assets/ea6f8bb1-ac69-48d6-87e1-2ec1bef5aa26)
  
* Each node was installed with os disk and data disk separate on different disks

* Some pods keep in `Pending` state 
  -  cattle-system/rancher-b57c5b74f-x8jjp
  -  harvester-system/harvester-6f767fc779-8rgrv
  -  harvester-system/harvester-webhook-d4668cdd8-lk2nn
  -  harvester-system/virt-api-549fb47477-n2bb7
  -  harvester-system/virt-controller-666fcffd7b-c26mz

  ![Image](https://github.com/user-attachments/assets/ded8b8cd-3159-40cb-8828-6ac47d7d2d68)
  
  ![Image](https://github.com/user-attachments/assets/939065bb-1e1c-4131-bd4b-ed53babd6353)

**To Reproduce**
1. Use ISO install to provision three nodes v1.4.1 Harvester cluster 
2. During installation, select the os disk and data disk to different disks
3. During installation, select the first node to be management role
4. Select the second node to be worker role
5. Select the third node to be worker role
6. Access to the management node, check the partition state and size     
    ```
    lsblk -o NAME,LABEL,SIZE
    ```
7. Check the disk usage of `active.img` and `passive.img`
    ```
    du -sh /run/initramfs/cos-state/cOS/*
    ```
8. Check if `active.img` is corrupted by running the command
    ```
    fsck.ext2 -nf /run/initramfs/cos-state/cOS/active.img
    ```
    
9. Upgrade to v1.4.2-rc1  

**Expected behavior**

Should be able to correctly upgrade from v1.4.1 to 1.4.2-rc1 without any node stuck in `Pre-drained` state

**Support bundle**

  - [supportbundle_88247adb-d21d-4d98-96b2-80f053d96ab1_2025-02-18T07-43-13Z.zip](https://github.com/user-attachments/files/18841026/supportbundle_88247adb-d21d-4d98-96b2-80f053d96ab1_2025-02-18T07-43-13Z.zip)

**Upgrade log**

  - [hvst-upgrade-pn6q2-upgradelog-archive-2025-02-18T07-28-50Z.zip](https://github.com/user-attachments/files/18841030/hvst-upgrade-pn6q2-upgradelog-archive-2025-02-18T07-28-50Z.zip)

**Environment**
 - Harvester ISO version: v1.4.1 to v1.4.2-rc1
 - Underlying Infrastructure: Three nodes bare-metal machines

**Additional context**

Found this issue when verify issue #7574

**Comment by bk201** [comment]
From Rancher log:

```evicting pod harvester-system/virt-api-549fb47477-nb896
evicting pod harvester-system/virt-controller-666fcffd7b-dkxv6
error when evicting pods/"virt-api-549fb47477-nb896" -n "harvester-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
error when evicting pods/"virt-controller-666fcffd7b-dkxv6" -n "harvester-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

It seems the cluster didn't promote nodes to control nodes thus virt-api/controller has only one instance:
```
$ kubectl get nodes
NAME       STATUS                     ROLES                       AGE   VERSION
n1-hp128   Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.30.7+rke2r1
n2-hp6     Ready                      <none>                      18h   v1.30.7+rke2r1
n3-hp10    Ready                      <none>                      13h   v1.30.7+rke2r1
```

Nodes `n2-hp6` and `n3-hp10` are configured as `worker` roles, and they can't be promoted. Currently, the upgrade path for mutli-nodes env needs to tune for this kind of cluster. Actually, it works more like a single node cluster.

The workaround is to delete `virt-api-pdb` and `virt-controller-pdb` PDBs in the `harvester-system` namespace, and the upgrade will move forward.

**Comment by bk201** [comment]
We can also reproduce the issue with a two-node cluster. The `virt-api` and `virt-controller` deployments have the node affinity in KubeVirt 1.3.1. The rules only allow control-plane nodes to run the deployments' pods:
```
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: DoesNotExist
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
```

After we upgrade KubeVirt to 1.3.1, the `virt-api` and `virt-controller` pods on the worker node are immediately killed. Thus, when we drain the first control-plane node, the two pods can't be evicted because doing this will violate their PDBs.

In Kubevirt v1.2.2, there is no node affinity for these two services.
