### ISSUE TITLE
virt-handler frequently restarts due to memory limits - unable to increase them

### ISSUE THREAD

**Issue by MaksimRudakov** [harvester/harvester#7659]
Environment
- Harvester Version: v1.4.0

Problem Description
virt-handler DaemonSet is constantly hitting memory limits and restarting (see attached graph). Current memory limit is 1.6GB but usage regularly hits this ceiling causing OOM kills.

![Image](https://github.com/user-attachments/assets/4a1498c8-25fd-4e30-a411-8f44410c99f1)

I've tried to increase the resources but Harvester keeps reverting my changes:
1. Attempted direct edits using kubectl edit ds virt-handler -n kubevirt
2. Tried applying HelmChartConfig in both fleet-local and harvester-system namespaces with appropriate patches

Current configuration from App resource shows:
```yaml
- patch: >-
    {"spec":{"template":{"spec":{"containers":[{"name":"virt-handler",
    "resources":{"limits":{"cpu":"700m","memory":"1600Mi"}}}]}}}}
```

Question
What is the correct way to increase virt-handler resource limits that won't be reverted by Harvester?

**Comment by MaksimRudakov** [comment]
@w13915984028 please help

**Comment by w13915984028** [comment]
@MaksimRudakov 

You need to `kubectl edit managedchart -n fleet-local harvester`, put the patch to `values.kubevirt.spec.customizeComponents.patches`

Then it will not be reverted.

https://github.com/harvester/harvester-installer/blob/8214c4680e1a62ae870840b01064f3494ee607ab/pkg/config/templates/rancherd-10-harvester.yaml#L169


https://github.com/harvester/harvester/blob/9b46493d505dfc4e9d0402ad57de43752dfcc9f8/deploy/charts/harvester/dependency_charts/kubevirt/values.yaml#L72

**Comment by ihcsim** [comment]
I don't if there is a better way for it, but what I normally do is to `patch` the `harvester` managed chart with my custom kubevirt configuration. E.g.,

```sh
$ cat patch.yaml
spec:
  values:
    kubevirt:
      spec:
        customizeComponents:
          patches:
          - patch: '{"webhooks":[{"name":"kubevirt-validator.kubevirt.io","failurePolicy":"Ignore"},{"name":"kubevirt-update-validator.kubevirt.io","failurePolicy":"Ignore"}]}'
            resourceName: virt-operator-validator
            resourceType: ValidatingWebhookConfiguration
            type: strategic
          - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-api",
              "resources":{"limits":{"cpu":"400m","memory":"1100Mi"}}}]}}}}'
            resourceName: virt-api
            resourceType: Deployment
            type: strategic
          - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-controller",
              "resources":{"limits":{"cpu":"800m","memory":"1300Mi"}}}]}}}}'
            resourceName: virt-controller
            resourceType: Deployment
            type: strategic
          - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-handler",
              "resources":{"limits":{"cpu":"700m","memory":"2400Mi"}}}]}}}}'
            resourceName: virt-handler
            resourceType: DaemonSet
            type: strategic

$ k -n fleet-local patch managedchart harvester --type merge --patch-file patch.yaml
```

Make sure to include all the `patch` entries in order to preserve the existing ones in the `kubevirt/kubevirt` resource. Then you should see be able to see the changes via `k -n harvester-system get kubevirt kubevirt`, and then eventually in your daemonset.

cc @w13915984028

**Comment by MaksimRudakov** [comment]
Thank you @w13915984028 and @ihcsim for your help! I successfully applied the patch to virt-handler using the managedchart approach. Here's what I did:

I applied the following patch to increase the memory limits:
```yaml
spec:
  values:
    kubevirt:
      spec:
        customizeComponents:
          patches:
          - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-handler",
              "resources":{"limits":{"cpu":"1000m","memory":"8000Mi"}}}]}}}}'
            resourceName: virt-handler
            resourceType: DaemonSet
            type: strategic
```

However, I'm still experiencing issues. Even with 8Gi memory limit, virt-handler continues to consume all available memory and crashes with OOM. In the logs, I see many errors about failing to update VMI statuses:

```json
{"component":"virt-handler","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"rdns2-choco-kz","namespace":"default","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"rdns2-choco-kz\": the object has been modified; please apply your changes to the latest version and try again"}
```

These errors appear frequently for multiple VMs. Could this indicate some underlying issue with status updates that's causing memory consumption to spiral? Any suggestions on how to investigate this further would be appreciated.

Current node metrics show high load on hv03 where most of these errors occur:
```
NAME   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
hv01   10940m      15%    131040Mi        25%
hv02   2493m       3%     15406Mi         2%
hv03   16464m      23%    139377Mi        27%
```

Is there another approach to resolve these status update conflicts?

**Comment by MaksimRudakov** [comment]
After detailed investigation, we identified the root cause of virt-handler's high memory consumption.

In the virt-launcher logs for affected virtual machines, we noticed a pattern of constant Freeze/Unfreeze cycles with very high frequency (every 1-2 seconds):

```
{"component":"virt-launcher","level":"warning","msg":"Unfreeze was not called for vmi freeipa-chocodew-kz for more than 1s, initiating unfreeze","pos":"manager.go:1567"}
{"component":"virt-launcher","level":"info","msg":"Freezed vmi","name":"freeipa-chocodew-kz","namespace":"default"}
{"component":"virt-launcher","level":"info","msg":"Synced vmi","name":"freeipa-chocodew-kz","namespace":"default"}
```
and the cycle repeats...

The cause was VM backups in Error state for these virtual machines. Once we deleted the problematic backups, the Freeze/Unfreeze cycle stopped, and the excessive memory consumption and OOM crashes of virt-handler were resolved.

For other users experiencing similar issues, we recommend checking and removing backups in Error state:

```
kubectl get vmbackups -A | grep Error
kubectl delete vmbackup <vmbackup-name>
```

Increasing memory limits may temporarily solve the problem, but it doesn't address the root cause of the status update cycle that leads to memory leaks.

**Comment by w13915984028** [comment]
@MaksimRudakov Thanks for reporting this.


cc @WebberHuang1118 @FrankYang0529 any insights? thanks.

**Comment by MaksimRudakov** [comment]
I won't close the issue yet. We'll try to reproduce the problem with a broken backup again and monitor both virt-handler memory consumption and virt-launcher logs.

**Comment by MaksimRudakov** [comment]
@w13915984028 
Let me share the background of the problem. Recently, we set up another Harvester cluster for our dev environment and for testing updates and new Harvester features without impacting production. We needed to migrate some virtual machines from our production Harvester to the new one. Currently, Harvester doesn't have capabilities to migrate VMs between clusters, but this can be done by specifying the same S3 backup-target for both clusters, and by creating a backup and restoring it in the new cluster to transfer the VM.

We also have a backup schedule configured, implemented by our custom script that calls the Harvester API to create backups. The script was working without errors, and we weren't receiving any alerts about backup errors. However, after some time, all created backups failed with the error:
```
conditions:
  - lastTransitionTime: "2025-02-25T09:25:00Z"
    message: backups.longhorn.io "backup-9cebaad6bf8544cc" not found
    reason: Error
    status: "False"
    type: InProgress
  - lastTransitionTime:
```

This was related to the fact that two Harvester clusters were using the same backup-target. All virtual machines with broken backups started experiencing issues with cyclical freeze calls:
```
{"component":"virt-launcher","level":"warning","msg":"Unfreeze was not called for vmi freeipa-chocodew-kz for more than 1s, initiating unfreeze","pos":"manager.go:1567"}
{"component":"virt-launcher","level":"info","msg":"Freezed vmi","name":"freeipa-chocodew-kz","namespace":"default"}
{"component":"virt-launcher","level":"info","msg":"Synced vmi","name":"freeipa-chocodew-kz","namespace":"default"}
```

This led to excessive memory consumption by virt-handler with subsequent OOM restarts. If the problem is left for several days, it leads to chaotic restarts of all virtual machines in the cluster because qemu-guest-agent cannot query VM status. The problem with flashing IP addresses that I described here also reappears: [BUG] Intermittent VM IP Address Disappearance in Harvester v1.3.2 · Issue #7031 · harvester/harvester

Conclusion: We understand that we "shot ourselves in the foot" by using the same backup-target for different Harvester clusters. However, I believe it's necessary to add some handler for Harvester VM backups that would prevent calling fsfreeze on VMs indefinitely.

**Comment by w13915984028** [comment]
@MaksimRudakov Thanks for your so detailed bunch of information, they are really helpful.

@bk201 @ihcsim @WebberHuang1118 @FrankYang0529 

This looks to be an interesting scenario for us to enhance the robustness of backup and restore, do we have planned features/issues to cover? thanks.

**Comment by WebberHuang1118** [comment]
Hi @MaksimRudakov 
Can you provide the SB? Thanks.

**Comment by MaksimRudakov** [comment]
Hi @WebberHuang1118 . At the moment, we got rid of shared s3 storage for two Harvester clusters and planned an upgrade to Harvester 1.4.1. I can describe the steps to reproduce the problem. I can also try to reproduce the problem already on 1.4.1, but I can only do this in 1-2 weeks. Unfortunately, my work schedule does not allow me to do this earlier.

**Comment by WebberHuang1118** [comment]
> Hi [@WebberHuang1118](https://github.com/WebberHuang1118) . At the moment, we got rid of shared s3 storage for two Harvester clusters and planned an upgrade to Harvester 1.4.1. I can describe the steps to reproduce the problem. I can also try to reproduce the problem already on 1.4.1, but I can only do this in 1-2 weeks. Unfortunately, my work schedule does not allow me to do this earlier.

Hi @MaksimRudakov 

Please describe the steps, I will try to reproduce it on my side, thanks.

**Comment by MaksimRudakov** [comment]
@WebberHuang1118 
Here are steps to reproduce the issue:

1) Set up two Harvester clusters with 3 nodes each, using Harvester 1.4.0

2) Create several virtual machines in both clusters. We used Ubuntu 24.04 (configuration below)

3) Configure identical backup-target for both clusters - this should be the same S3 bucket with the same access keys

4) On the first cluster, create backups of all virtual machines (either manually or via schedule). These backups should complete successfully, and in the Harvester web UI, you should see them with a "Ready" status

5) Either wait several hours or go to the second Harvester cluster and save the backup-target configuration again

6) After some time, you'll notice all backups fail with "Error" status:
```
conditions:
  - lastTransitionTime: "2025-02-25T09:25:00Z"
    message: backups.longhorn.io "backup-9cebaad6bf8544cc" not found
    reason: Error
    status: "False"
    type: InProgress
```

7) On virtual machines with broken backups, you'll see the following in virt-launcher logs repeating every 1-2 seconds:
```
{"component":"virt-launcher","level":"warning","msg":"Unfreeze was not called for vmi freeipa-chocodew-kz for more than 1s, initiating unfreeze","pos":"manager.go:1567"}
{"component":"virt-launcher","level":"info","msg":"Freezed vmi","name":"freeipa-chocodew-kz","namespace":"default"}
{"component":"virt-launcher","level":"info","msg":"Synced vmi","name":"freeipa-chocodew-kz","namespace":"default"}
```

8) You'll also observe increasing memory consumption on one of the virt-handler pods, eventually leading to OOM restarts

VM Configuration used for testing:
```yaml
apiVersion: v1
data:
  networkdata: >-
    bmV0d29yazoKICB2ZXJzaW9uOiAyCiAgZXRoZXJuZXRzOgogICAgZW5wMXMwOgogICAgICBkaGNwNDogZmFsc2UKICAgICAgZGhjcDY6IGZhbHNlCiAgICAgIGxpbmstbG9jYWw6IFtdCiAgICAgIGFkZHJlc3NlczoKICAgICAgICAtIDEwLjMxLjAuMTIzLzI0CiAgICAgIHJvdXRlczoKICAgICAgICAtIHRvOiAwLjAuMC4wLzAKICAgICAgICAgIHZpYTogMTAuMzEuMC4xCiAgICAgIG5hbWVzZXJ2ZXJzOgogICAgICAgICAgYWRkcmVzc2VzOgogICAgICAgICAgLSAxMC4xMy4wLjEyCiAgICAgICAgICAtIDE4NS4xMDIuNzQuMTcxCiAgICAgICAgICBzZWFyY2g6CiAgICAgICAgICAtIGNob2NvZGV2Lmt6Cg==
kind: Secret
metadata:
  name: fleet-rnd-vm01
  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    harvesterhci.io/imageId: default/ubuntu24-sdlc-app-storageclass-2repl
  finalizers:
    - kubernetes.io/pvc-protection
  name: fleet-rnd-vm01
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-ubuntu24-sdlc-app-storageclass-2repl
  volumeMode: Block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    harvesterhci.io/imageId: default/ubuntu24-sdlc-app-storageclass-2repl
  finalizers:
    - kubernetes.io/pvc-protection
  name: fleet-rnd-vm01-additional
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-ubuntu24-sdlc-app-storageclass-2repl
  volumeMode: Block
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fleet-rnd-vm01
  namespace: default
  annotations:
    field.cattle.io/description: fleet rnd vms
    harvesterhci.io/reservedMemory: 512Mi
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  finalizers:
    - wrangler.cattle.io/VMController.CleanupPVCAndSnapshot
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: linux
    tag.harvesterhci.io/environment: sdlc-db
    tag.harvesterhci.io/role: master
    tag.harvesterhci.io/service_type: rnd
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: 'null'
        harvesterhci.io/waitForLeaseInterfaceNames: '["enp1s0"]'
      labels:
        harvesterhci.io/creator: harvester
        harvesterhci.io/vmName: fleet-rnd-vm01
        tag.harvesterhci.io/environment: sdlc-db
        tag.harvesterhci.io/role: master
        tag.harvesterhci.io/service_type: rnd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network.harvesterhci.io/mgmt
                    operator: In
                    values:
                      - 'true'
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: harvesterhci.io/creator
                      operator: Exists
                    - key: tag.harvesterhci.io/service_type
                      operator: In
                      values:
                        - rnd
                topologyKey: kubernetes.io/hostname
              weight: 100
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: scsi
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: enp1s0
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        machine:
          type: q35
        memory:
          guest: 3584Mi
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      evictionStrategy: LiveMigrate
      hostname: fleet-rnd-vm01
      networks:
        - multus:
            networkName: default/sdlc-db
          name: enp1s0
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: fleet-rnd-vm01
        - cloudInitNoCloud:
            networkDataSecretRef:
              name: fleet-rnd-vm01
            secretRef:
              name: default-cloudinit-ubuntu24-04
          name: cloudinitdisk
```
