### ISSUE TITLE
[BUG] Image name 63 characters max

### ISSUE THREAD

**Issue by xelab04** [harvester/harvester#7697]
Apologies if the Title doesn't explain very well.

I launched a migration using the following manifest file:
```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: mantis-bug-tracker
  namespace: default
spec: 
  virtualMachineName: "mantis-bug-tracker-server"
  folder: "/Discovered virtual machine"
  sourceCluster: 
    name: vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

After transferring the data to Harvester, I get the following error as the controller attempts to create the image:

```
level=error msg="error syncing 'default/mantis-bug-tracker': handler virtualmachine-import-job-change: error creating vmi: VirtualMachineImage.harvesterhci.io \"image-ddn6m\" is invalid:

metadata.labels: Invalid value: \"vm-import-mantis-bug-tracker-mantis-bug-tracker-default-disk-1.img\": must be no more than 63 characters, requeuing"

level=info msg="Creating VM images ..." name=mantis-bug-tracker namespace=default spec.virtualMachineName=mantis-bug-tracker-server
```

First of all, I find it bizarre that the name of the VM appears twice.

Second, I try changing the VM name for when it comes to Harvester, to simply "mantis", and this restarts the whole transfer process, which I guess makes sense. But if this happens, it's better to do the character length check at the start so I don't spend 45 minutes of transfer just to have to change the name and restart.
