### ISSUE TITLE
[ENHANCEMENT] Deny the change of network on nad

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#7701]
**Is your feature request related to a problem? Please describe.**

**A. Temporary information mis-match**

1. create a NAD on mgmt network, and create a VM
NAD:
```
  spec:
    config: '{"cniVersion":"0.3.1","name":"nad1","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":100,"ipam":{}}'
```

VM: the nad's belonging clusternetwork (mgmt) is converted to vm's `affinity`
```
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: network.harvesterhci.io/mgmt               //  mgmt network
                  operator: In
...
...
        networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/nad1
          name: nic-1                  - 
```
2. stop vm

3. change nad, the nad labels shows it is changed from `mgmt` to `data`
```
...
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
...
    creationTimestamp: "2025-02-27T10:32:31Z"
...
    labels:
      network.harvesterhci.io/clusternetwork: data
      network.harvesterhci.io/last-clusternetwork: mgmt       //  mgmt network
      network.harvesterhci.io/ready: "true"
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "100"
    name: nad1
    namespace: default
..
  spec:
    config: '{"cniVersion":"0.3.1","name":"nad1","type":"bridge","bridge":"data-br","promiscMode":true,"vlan":100,"ipam":{}}'
...

// nad points  data   network
```

4. check VM, the `affinity` is not updated yet

```
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: network.harvesterhci.io/mgmt        //  still mgmt network
                  operator: In
                  values:
                  - "true"
                  - 
...
        networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/nad1
```

5. When VM is started again, the `affinity` is updated.

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network.harvesterhci.io/data     //  updated to  data  network
                    operator: In
                    values:
                      - 'true'
```

It is done from:

https://github.com/harvester/harvester/blob/ff96b3c351ddb00ae54e2f072882178a3df144c6/pkg/webhook/resources/virtualmachine/mutator.go#L458

https://github.com/harvester/harvester/blob/ff96b3c351ddb00ae54e2f072882178a3df144c6/pkg/webhook/resources/virtualmachine/mutator.go#L427

Before a VM is rebooted, the VM's spec affinity may be staled.

**B. The network agent may leak some VLANs**

When NADs are dangling NAD (no VM/storgenetwork attached), the back & forth moving a/a group of NAD(s) from/to other clusternetworks frequently, may cause the agent in abnormal status.

e.g., One NAD is changed from cn1, to cn2, to cn3, to cn4 continuously, the client onChange may not get all the change in sequences, it may get cn1->cn3->cn4, or cn1->cn2->cn4 .., but I did not test to get the full log yet.

Refer PR: https://github.com/harvester/network-controller-harvester/pull/155

**Describe the solution you'd like**

Deny the change on NAD's network, if a change is needed, delete & create it.

This is a bit like that k8s' object's namespace & name are immutable, technically, it should be fine to change, but it will cost too much efforts to cover all cases.

**Describe alternatives you've considered**

**Additional context**

PR & commit: https://github.com/harvester/network-controller-harvester/pull/149/commits/9f06c5475073e2b82e67298efcbee9dea32b8f80#diff-900397cb9002ed992e8565ae266dc4ec231a187b1d3cf016f5fa0cd6ebf82d04

issue: https://github.com/harvester/harvester/issues/4355

https://github.com/harvester/network-controller-harvester/pull/155
https://github.com/harvester/network-controller-harvester/pull/131
