### ISSUE TITLE
[BUG] Broken UI when removing a volume from a VM

### ISSUE THREAD

**Issue by aylen384** [harvester/harvester#7720]
![Image](https://github.com/user-attachments/assets/8f1decd7-66f8-49ce-97cb-84857c6cf38c)
![Image](https://github.com/user-attachments/assets/0967b2a9-c14e-445a-8a10-99d92b0ccab8)

**Environment**
happend on op-prg2.openplatform.suse.com on 2025-02-26 on harvester v2.9.2
with browser Vivaldi 7.1.3570.54 stable

**Comment by aylen384** [comment]
[some activity to prevent stale]

**Comment by w13915984028** [comment]
@asdil12 Could you explain a bit more the steps, the abnormal result, the expected result? thanks.

cc @a110605 @houhoucoop

**Comment by aylen384** [comment]
When trying to remove a volume from a VM, the confirmation dialog is broken be having a larger content than the box is in size resulting in a horizontal scrollbar that must be used in order to see the buttons.

**Comment by w13915984028** [comment]
Which Harvester version are you using @asdil12 ?

On Harvester v1.5.0 cluster, the UI looks good.  From the source code, there is no var on `unmount` part.

@a110605 @houhoucoop any insights on this issue? 


https://github.com/harvester/dashboard/blob/9807b623f9053044af4c3233a4b8862b945e18a7/pkg/harvester/l10n/en-us.yaml#L619
```
      unmount:
        title: Are you sure?
        message: Are you sure you want to unmount this volume?

    unplug:
      title: 'Are you sure that you want to detach volume {name} ?'
      actionLabel: Detach
      detachVolume:
        Detach Volume
```

v1.3 UI

https://github.com/harvester/dashboard/blob/5280151dd94f49abe92dac30376481619d37838f/pkg/harvester/l10n/en-us.yaml#L537


![Image](https://github.com/user-attachments/assets/a379f960-9b2a-4bcb-9c18-4df62396dc4f)


![Image](https://github.com/user-attachments/assets/907ed496-2227-4c3a-94cd-74f60d6daf29)
