### ISSUE TITLE
[BUG] Upgrade from v1.4.2-rc2 to v1.5.0-rc1 stuck

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#7819]
**Describe the bug**

I‘m encountering an issue while upgrading from v1.4.2-rc2 to v1.5.0-rc1. The upgrade appears to be stuck, and from the k9s I noticed job hvst-upgrade-gntmj-apply-manifests is continuously logging:
```
hvst-upgrade-gntmj-apply-manifests-9r5dk Sleep for 5 seconds to retry                                                                                                                    
hvst-upgrade-gntmj-apply-manifests-9r5dk Current version: 1.5.0-rc1, Current state: ErrApplied, Current generation: 4
```

and in `mcc-harvester` bundle CR I found the error message: `resource mapping not found for name: "cdi" namespace: "" from "": no matches for kind "CDI" in version "[cdi.kubevirt.io/v1beta1]`(http://cdi.kubevirt.io/v1beta1)" ensure CRDs are installed first .

**To Reproduce**
- Upgrade from v1.4.2-rc2 to v1.5.0-rc1, then upgrade stuck.

**Expected behavior**
Upgrade should work successfully.

**Support bundle**
N/A

**Environment**
v1.4.2-rc2, 3 node cluster

**Additional context**

**Comment by khushboo-rancher** [comment]
cc: @harvester/qa

**Comment by brandboat** [comment]
Verified this issue has been fixed, will close the issue

### Test Steps
#### Single node upgrade
- Prepare a single node with v1.4.2
- Upgrade to v1.5-head (e86c6208e9366112b5889204dfa67449e54db633)
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: Version
  metadata:
    name: master
    namespace: harvester-system
  spec:
    isoURL: http://192.168.100.1:8000/harvester-master-amd64.iso
  ```
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/skip-version-check: "true"
      harvesterhci.io/skipWebhook: "true"
    generateName: hvst-upgrade-
    namespace: harvester-system
  spec:
    version: "master"
  ```
- Upgrade success.

#### Multi-node upgrade
- Prepare a 3 node cluster with v1.4.2.
- Upgrade to v1.5-head (e86c6208e9366112b5889204dfa67449e54db633)
- Upgrade success
