### ISSUE TITLE
[FEATURE] option to disable kubevirt VM scheduling on 'management' role

### ISSUE THREAD

**Issue by notsrch** [harvester/harvester#7849]
**Is your feature request related to a problem? Please describe.**
The current Management role nodes are preferred but not dedicated.  If creating a cluster with dedicated Management role nodes the nodes are smaller and not sized to host VM workloads.   It would be beneficial to have a feature to set a management node as a dedicated Management role node that disables VM scheduling on that node.

**Describe the solution you'd like**
An option to disable VM scheduling on a Management role node that will persist through a Harvester upgrade.

**Describe alternatives you've considered**
Setting kubevirt.io/schedulable: 'false' manually will work to disable scheduling on Management role nodes but it does not persist through a Harvester upgrade.   After upgrade it resets to kubevirt.io/schedulable: 'true'

**Additional context**
None

**Comment by w13915984028** [comment]
@notsrch You may try with following steps:

(1) Edit host, add customized group of labels to nodes
![Image](https://github.com/user-attachments/assets/c5b5ef79-62a9-431f-b949-345a7a02fa9d)

(2) Set VM's `node scheduling` when `create vm`
![Image](https://github.com/user-attachments/assets/53288c2b-93b1-402b-aa85-7e21a9573f32)

Thus, the VM can be set to schdule on a specific label, it looks to meet your requirement.

the created-vm
```
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: vm2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nonemgmt
                    operator: Exists
```
