### ISSUE TITLE
[BUG] Upgrade 1.4.0 -> 1.4.1 stuck for days

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#7851]
**Environment**
- Harvester ISO version: 1.4.0
- Underlying Infrastructure:
  - 2 Dell Precision servers with dual Xeon Gold CPU and 192GB+ RAM
  - 1 witness VM

**Describe the bug**
- started upgrade from UI
- Upgrade runs for about 2 days. 2 nodes (witness + node) got rebooted and looks good.
- Last node (t7920) has not been upgraded.
- Looking at pods, I see `longhorn-system   backing-image-manager` pod constantly starting and starting...

I see this issues:
```
kubectl get managedcharts -n fleet-local harvester -o yaml 
...
  summary:
    desiredReady: 1
    nonReadyResources:
    - bundleState: NotReady
      name: fleet-local/local
      nonReadyStatus:
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester-network-controller-manager
        namespace: harvester-system
        summary:
          message:
          - Deployment does not have minimum availability.
          - 'Available: 1/2'
          state: updating
          transitioning: true
        uid: 2e7bee6a-55ee-4266-999c-ff5270dbf492
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester-webhook
        namespace: harvester-system
        summary:
          message:
          - 'Available: 1/2'
          state: in-progress
          transitioning: true
        uid: 373614a9-2b68-40f4-b85e-359f774fd49b
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester
        namespace: harvester-system
        summary:
          message:
          - 'Available: 1/2'
          state: in-progress
          transitioning: true
        uid: 7468a48f-caaa-4cf7-a84c-9545cb909d0d
      - apiVersion: kubevirt.io/v1
        kind: KubeVirt
        name: kubevirt
        namespace: harvester-system
        summary:
          message:
          - KubeVirt generation is 4577, but latest observed generation is 4576
          state: deployed
          transitioning: true
        uid: b8236712-610f-461c-8a17-ccfc3d26a8c9
    notReady: 1
    ready: 0
  unavailable: 1
  unavailablePartitions: 0
```

How can I continue the upgrade?

How can I see the status of the upgrade?
