### ISSUE TITLE
[BUG] VMNetwork Manifests Fail to have Route Connectivity "Active" v1.4.1/v1.5.0-rc1

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7917]
**Describe the bug**
Somehow applying multiple network configurations to better try to at the start of the Harvester cluster have some automation via manifests to reduce the manual efforts need fail to ever show as Rout Connectivity Active in UI

**Example Manifest**
```yaml
apiVersion: network.harvesterhci.io/v1beta1
kind: ClusterNetwork
metadata:
  name: extra
---
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  name: extranc
spec:
  clusterNetwork: extra
  uplink:
    bondOptions:
      mode: active-backup
    nics:
      - eno50
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2011
  namespace: harvester-public
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2011","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2011,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2017
  namespace: harvester-public
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2017","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2017,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2013
  namespace: harvester-public
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2013","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2013,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2014
  namespace: harvester-public
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2014","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2014,"ipam":{}}

```

**To Reproduce**
1. Get Harvester Cluster KubeConfig
2. apply manifest to "fresh" Harvester cluster
3. VM Networks will be present but the UI the Route Connectivity "Active" is never shown 

**Workaround**
1. Manually edit each VM network to modify the Description in the UI, then save, then the VM Network's route connectivity will show as "Active"

**Expected behavior**
Automation to succeed with YAML manifests

**Environment**
 - Harvester ISO version: v1.4.1/v1.5.0-rc1
 - Underlying Infrastructure: bare-metal

**Comment by rrajendran17** [comment]
@irishgordo The Route connectivity status is updated in UI, when network controller tries to ping the Gateway IP of the vlan from the host.So this expects a valid CIDR and GW ip to be filled in the annotations of the NAD.

In the above example given, since there is no route info filled, the connectivity status is empty, when you edited the config and saved, the mode becomes "auto" which is DHCP and a helper job is created in network controller which requests a CIDR/GW ip for that vlan from the DHCP server and details are updated to the NAD and later ping towards this GW IP is checked and connectivity becomes "Active".

network.harvesterhci.io/route: >-
      {"mode":"auto","cidr":"10.115.24.0/21","gateway":"10.115.31.254","connectivity":"true"}

"cidr" and "gateway" info (configured statically or acquired from DHCP) is necessary for the network controller to update the "connectivity" status.

**Comment by irishgordo** [comment]
Maybe this is an enhancement then? @rrajendran17 

As currently in the UI if "auto" is used (dhcp) it would just automatically figure out the CIDR & GW IP

Trying to do something like:
```yaml
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan2014
  namespace: harvester-public
spec:
  config: >-
    {"mode":"auto","cniVersion":"0.3.1","name":"vlan2014","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2014,"ipam":{}}
```

just specifying `mode: auto` in the config doesn't seem to bring that accross

**Comment by irishgordo** [comment]
@rrajendran17 thank you for the help -based on your suggestion, to avoid having to specify the GW IP & CIDR/
We just need to specify
```yaml
apiVersion: network.harvesterhci.io/v1beta1
kind: ClusterNetwork
metadata:
  name: extra
---
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  name: extranc
spec:
  clusterNetwork: extra
  uplink:
    bondOptions:
      mode: active-backup
    nics:
      - eno50
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    field.cattle.io/description: this is an regular non-airgap vlan
    network.harvesterhci.io/route: >-
      {"mode":"auto"}
  name: vlan2011
  namespace: harvester-public
  labels:
    network.harvesterhci.io/clusternetwork: extra
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "2011"
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2011","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2011,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    field.cattle.io/description: this is an regular non-airgap vlan
    network.harvesterhci.io/route: >-
      {"mode":"auto"}
  name: vlan2017
  namespace: harvester-public
  labels:
    network.harvesterhci.io/clusternetwork: extra
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "2017"
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2017","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2017,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    field.cattle.io/description: this is an airgap vlan
    network.harvesterhci.io/route: >-
      {"mode":"auto"}
  name: vlan2013
  namespace: harvester-public
  labels:
    network.harvesterhci.io/clusternetwork: extra
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "2013"
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2013","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2013,"ipam":{}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    field.cattle.io/description: this is an airgap vlan
    network.harvesterhci.io/route: >-
      {"mode":"auto"}
  name: vlan2014
  namespace: harvester-public
  labels:
    network.harvesterhci.io/clusternetwork: extra
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "2014"
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan2014","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2014,"ipam":{}}
```

So that:
```yaml
annotations:
    network.harvesterhci.io/route: >-
      {"mode":"auto"}
```

the annotation is set for it to fetch down the address ty!
👍 😄 
I'll go ahead and close this out
