### ISSUE TITLE
[BUG] Harvester os.write_files not working with /var/lib/rancher/rke2/server/manifests v1.5 & v1.4

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#7921]
**Describe the bug**
os.write_files is not writing the files

**Sample:**
```yaml
os:
  write_files:
  - content: |
      apiVersion: v1
      data:
        cloudInit: |-
          #cloud-config
          password: password
          chpasswd:
            expire: false
          ssh_pwauth: true
          package_update: true
          packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - cowsay
            - gnupg-agent
            - software-properties-common
            - qemu-guest-agent
          write_files:
            - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
              content: |
                net.ipv4.conf.all.forwarding=1
          groups:
            - docker
          runcmd:
            - - systemctl
              - enable
              - --now
              - qemu-guest-agent.service
            - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            - apt-get update -y
            - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            - systemctl start docker
            - systemctl enable docker
          system_info:
            default_user:
              groups: [docker]
      kind: ConfigMap
      metadata:
        name: docker-buntu
        namespace: harvester-public
        labels:
          harvesterhci.io/cloud-init-template: user
        annotations:
          field.cattle.io/description: docker cloud-config
      ---
      apiVersion: v1
      data:
        cloudInit: |-
          #cloud-config
          password: password
          chpasswd:
            expire: false
          ssh_pwauth: true
          package_update: true
          packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - cowsay
            - gnupg-agent
            - software-properties-common
            - qemu-guest-agent
          runcmd:
            - - systemctl
              - enable
              - --now
              - qemu-guest-agent.service
      kind: ConfigMap
      metadata:
        name: ubuntu-base
        namespace: harvester-public
        labels:
          harvesterhci.io/cloud-init-template: user
        annotations:
          field.cattle.io/description: ubuntu base user is ubuntu cloud-config
      ---
      apiVersion: v1
      data:
        cloudInit: |-
          #cloud-config
          password: password
          chpasswd:
            expire: false
          ssh_pwauth: true
          package_update: true
          packages:
            - qemu-guest-agent
          runcmd:
            - - systemctl
              - enable
              - --now
              - qemu-guest-agent.service
      kind: ConfigMap
      metadata:
        name: sles-base
        namespace: harvester-public
        labels:
          harvesterhci.io/cloud-init-template: user
        annotations:
          field.cattle.io/description: sles user is sles base cloud-config
      ---
      apiVersion: v1
      data:
        cloudInit: |-
          #cloud-config
          password: password
          chpasswd:
            expire: false
          ssh_pwauth: true
          package_update: true
          packages:
            - qemu-guest-agent
          runcmd:
            - - systemctl
              - enable
              - --now
              - qemu-guest-agent.service
      kind: ConfigMap
      metadata:
        name: rhel-base
        namespace: harvester-public
        labels:
          harvesterhci.io/cloud-init-template: user
        annotations:
          field.cattle.io/description: rhel user is cloud-user base cloud-config
      ---
      apiVersion: v1
      data:
        cloudInit: |-
          #cloud-config
          password: password
          chpasswd:
            expire: false
          ssh_pwauth: true
          package_update: true
          packages:
            - qemu-guest-agent
          runcmd:
            - - systemctl
              - enable
              - --now
              - qemu-guest-agent.service
      kind: ConfigMap
      metadata:
        name: sle-micro-base
        namespace: harvester-public
        labels:
          harvesterhci.io/cloud-init-template: user
        annotations:
          field.cattle.io/description: sle micro 6 user is sles base cloud-config
    path: /var/lib/rancher/rke2/server/manifests/cloud-configs.yaml
    owner: root
  - content: |
      apiVersion: network.harvesterhci.io/v1beta1
      kind: ClusterNetwork
      metadata:
        name: extra
      ---
      apiVersion: network.harvesterhci.io/v1beta1
      kind: VlanConfig
      metadata:
        name: extranc
      spec:
        clusterNetwork: extra
        uplink:
          bondOptions:
            mode: active-backup
          nics:
            - eno50
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an regular non-airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2011
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2011"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2011","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2011,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an regular non-airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2012
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2012"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2012","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2012,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an regular non-airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2017
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2017"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2017","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2017,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2013
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2013"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2013","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2013,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2014
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2014"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2014","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2014,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an regular non-airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2015
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2015"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2015","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2015,"ipam":{}}
      ---
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          field.cattle.io/description: this is an regular non-airgap vlan
          network.harvesterhci.io/route: >-
            {"mode":"auto"}
        name: vlan2016
        namespace: harvester-public
        labels:
          network.harvesterhci.io/clusternetwork: extra
          network.harvesterhci.io/ready: "true"
          network.harvesterhci.io/type: L2VlanNetwork
          network.harvesterhci.io/vlan-id: "2016"
      spec:
        config: >-
          {"cniVersion":"0.3.1","name":"vlan2015","type":"bridge","bridge":"extra-br","promiscMode":true,"vlan":2016,"ipam":{}}
    path: /var/lib/rancher/rke2/server/manifests/basic-networking-eno50.yaml
    owner: root
  - content: |
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: jammy-cloudimg-amd64
        namespace: harvester-public
        labels:
          harvesterhci.io/imageDisplayName: jammy-cloudimg-amd64
          harvesterhci.io/os-type: ubuntu
      spec:
        displayName: jammy-cloudimg-amd64
        sourceType: download
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: focal-cloudimg-amd64
        namespace: harvester-public
        labels:
          harvesterhci.io/imageDisplayName: focal-cloudimg-amd64
          harvesterhci.io/os-type: ubuntu
      spec:
        displayName: focal-cloudimg-amd64
        sourceType: download
        url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: noble-cloudimg-amd64
        namespace: harvester-public
        labels:
          harvesterhci.io/imageDisplayName: noble-cloudimg-amd64
          harvesterhci.io/os-type: ubuntu
      spec:
        displayName: noble-cloudimg-amd64
        sourceType: download
        url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: sles15-sp6-minimal
        labels:
          harvesterhci.io/imageDisplayName: sles15-sp6-minimal
        namespace: harvester-public
      spec:
        displayName: sles15-sp6-minimal
        sourceType: download
        url: http://10.115.1.6/iso/sles/SLES15-SP6-Minimal-VM.x86_64-Cloud-GM.qcow2
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: sles15-sp5-minimal
        labels:
          harvesterhci.io/imageDisplayName: sles15-sp5-minimal
        namespace: harvester-public
      spec:
        displayName: sles15-sp5-minimal
        sourceType: download
        url: http://10.115.1.6/iso/sles/SLES15-SP5-Minimal-VM.x86_64-Cloud-GM.qcow2
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: sl-micro-6
        labels:
          harvesterhci.io/imageDisplayName: sl-micro-6
        namespace: harvester-public
      spec:
        displayName: sl-micro-6
        sourceType: download
        url: http://10.115.1.6/iso/sles/SL-Micro.x86_64-6.0-Default-qcow-GM2.qcow2
      ---
      apiVersion: harvesterhci.io/v1beta1
      kind: VirtualMachineImage
      metadata:
        name: rhel-9-4
        labels:
          harvesterhci.io/imageDisplayName: rhel-9-4
        namespace: harvester-public
      spec:
        displayName: rhel-9-4
        sourceType: download
        url: http://10.115.1.6/iso/rhel/rhel-9.4-x86_64-kvm.qcow2
    path: /var/lib/rancher/rke2/server/manifests/basic-images.yaml
    owner: root
  ntpServers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
install:
  wipeAllDisks: true
  harvester:
    enableGoCoverDir: true
```

**To Reproduce**
1. have your harvester config url point to somewhere that has that configuration
2. install harvester with seeder
3. check your /var/lib/rancher/rke2/server/manifests

**Expected behavior**
manifests should be there

**Workaround**
- manually write out the manifests in /var/lib/rancher/rke2/server/manifests

**Environment**
 - Harvester ISO version: v1.5.0-rc4, v1.4.3-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare-metal
