### ISSUE TITLE
[BUG] Via Rancher, config Selector on an existing ranged IPPool causes it "Not Ready"

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#7942]
**Describe the bug**
As title, we found that the IPPool becomes `Not Ready` if we update it's Selector later rather than config them in one time.
⚠ Note that it only happen in **rancher integration** but not in Harvester standalone mode.

https://github.com/user-attachments/assets/b32ba218-76ca-4cd5-a393-a84b0ddecc68

**To Reproduce**
As record in description

**Expected behavior**
IPPool should be `Active`

**Support bundle**

[supportbundle_47c469f0-237f-4786-a3ae-dbc8a505b8be_2025-03-26T02-58-11Z.zip](https://github.com/user-attachments/files/19459802/supportbundle_47c469f0-237f-4786-a3ae-dbc8a505b8be_2025-03-26T02-58-11Z.zip)

**Environment**
 - Harvester ISO version: `v1.5.0-rc2`
 - Rancher version: `v2.11.0-rc7`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): QEMU/KVM

**Additional context**
![Image](https://github.com/user-attachments/assets/6a5a2cf0-6210-48bc-921b-c38310c8f376)

**Comment by bk201** [comment]
@w13915984028 can you help check if this is a UI issue? Thanks!

**Comment by starbops** [comment]
I found no IPPool CRs left in the cluster from the support bundle. Below are some messages found in the load balancer controller

```
time="2025-03-26T02:23:23Z" level=info msg="IP Pool pool1 is deleted"
time="2025-03-26T02:44:40Z" level=info msg="IP Pool mypool is deleted"
time="2025-03-26T02:46:06Z" level=info msg="IP Pool pool1 is deleted"
time="2025-03-26T02:48:17Z" level=info msg="IP Pool pool1 is deleted"
```

But @albinsun said no IPPool CRs were deleted. Is it possible that the IPPool CRs got removed by something accidentally?

**Comment by starbops** [comment]
Looks like the same in #7791 happens to IPPools too.

Rancher integrated:
<img width="647" alt="Image" src="https://github.com/user-attachments/assets/e04f90ce-37ee-4f7f-bdcf-a2696578012e" />

Standalone:
<img width="745" alt="Image" src="https://github.com/user-attachments/assets/9accebc0-479e-4d9b-808c-102d021dc0d7" />

cc @a110605

**Comment by w13915984028** [comment]
Got a similar observation, the IPPool object status `Ready` was wiped out ...


```
 name: pool-2stages

  status:
    available: 0
    lastAllocated: "null"
    total: 0
```

```

 name: pool-onetime

  status:
    available: 10
    conditions:
    - lastUpdateTime: "2025-03-26T02:49:10Z"
      status: "True"
      type: Ready
    lastAllocated: "null"
    total: 10
```
