### ISSUE TITLE
[BUG] Backing images' on-disk data might be removed during upgrade

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#7958]
### Describe the Bug

When upgrading from Harvester v1.3.2 to v1.4.0 (Longhorn v1.6.2 to v1.7.2), there is a chance the backing image's data will be deleted.

### To Reproduce

1. Upgrading from v1.3.2 to v1.40 and noticing some VMs can't start due to PVC can't be ready.

### Expected Behavior

Backing images should be available and ready.

### Environment

- Harvester version: v1.3.2 to v1.4.0
- Impacted VM: 
- Impacted volume (PV): 
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630):
- Rancher version:

### Additional context

Longhorn upstream issue: https://github.com/longhorn/longhorn/issues/10644

### Workaround and Mitigation

Applying Longhorn v1.7.2 backing image CRD before the upgrade can avoid the issue.

**Comment by bk201** [comment]
We'll need to verify the workaround and publish a known issue on the doc site (plus updating release note.)

**Comment by WebberHuang1118** [comment]
I've tried the workaround to upgrade Harvester `v1.3.2` -> `v1.4.0` (LH `v1.6.2` -> `v1.7.2`)
- Patching harvester managechart to avoid complaints
  ```
  $ kubectl patch managedchart harvester \
  -n fleet-local \
  --type='json' \
  -p='[
    {
      "op":"add",
      "path":"/spec/diff/comparePatches/-",
      "value": {
        "apiVersion":"apiextensions.k8s.io/v1",
        "jsonPointers":["/spec","/metadata/annotations", "/metadata/labels", "/status"],
        "kind":"CustomResourceDefinition",
        "name":"backingimages.longhorn.io"
      }
    }
  ]'
  ```
- Applying [BI CRD from LH v1.7.2](https://github.com/longhorn/longhorn/blob/bd3b19984d8dcaa41e84edd207a385ef6befa907/deploy/longhorn.yaml#L486-L690) ahead of the upgrade
  ```
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    annotations:
      controller-gen.kubebuilder.io/version: v0.15.0
    labels:
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/version: v1.7.2
      longhorn-manager: ""
    name: backingimages.longhorn.io
  spec:
    conversion:
      strategy: Webhook
      webhook:
        clientConfig:
          service:
            name: longhorn-conversion-webhook
            namespace: longhorn-system
            path: /v1/webhook/conversion
            port: 9501
        conversionReviewVersions:
        - v1beta2
        - v1beta1
    group: longhorn.io
    names:
      kind: BackingImage
      listKind: BackingImageList
      plural: backingimages
      shortNames:
      - lhbi
      singular: backingimage
    scope: Namespaced
    versions:
    - additionalPrinterColumns:
      - description: The backing image name
        jsonPath: .spec.image
        name: Image
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          description: BackingImage is where Longhorn stores backing image object.
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
      - description: The system generated UUID
        jsonPath: .status.uuid
        name: UUID
        type: string
      - description: The source of the backing image file data
        jsonPath: .spec.sourceType
        name: SourceType
        type: string
      - description: The backing image file size in each disk
        jsonPath: .status.size
        name: Size
        type: string
      - description: The virtual size of the image (may be larger than file size)
        jsonPath: .status.virtualSize
        name: VirtualSize
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1beta2
      schema:
        openAPIV3Schema:
          description: BackingImage is where Longhorn stores backing image object.
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: BackingImageSpec defines the desired state of the Longhorn
                backing image
              properties:
                checksum:
                  type: string
                diskFileSpecMap:
                  additionalProperties:
                    properties:
                      evictionRequested:
                        type: boolean
                    type: object
                  type: object
                diskSelector:
                  items:
                    type: string
                  type: array
                disks:
                  additionalProperties:
                    type: string
                  description: Deprecated. We are now using DiskFileSpecMap to assign
                    different spec to the file on different disks.
                  type: object
                minNumberOfCopies:
                  type: integer
                nodeSelector:
                  items:
                    type: string
                  type: array
                secret:
                  type: string
                secretNamespace:
                  type: string
                sourceParameters:
                  additionalProperties:
                    type: string
                  type: object
                sourceType:
                  enum:
                  - download
                  - upload
                  - export-from-volume
                  - restore
                  - clone
                  type: string
              type: object
            status:
              description: BackingImageStatus defines the observed state of the Longhorn
                backing image status
              properties:
                checksum:
                  type: string
                diskFileStatusMap:
                  additionalProperties:
                    properties:
                      lastStateTransitionTime:
                        type: string
                      message:
                        type: string
                      progress:
                        type: integer
                      state:
                        type: string
                    type: object
                  nullable: true
                  type: object
                diskLastRefAtMap:
                  additionalProperties:
                    type: string
                  nullable: true
                  type: object
                ownerID:
                  type: string
                size:
                  format: int64
                  type: integer
                uuid:
                  type: string
                virtualSize:
                  description: Virtual size of image, which may be larger than physical
                    size. Will be zero until known (e.g. while a backing image is uploading)
                  format: int64
                  type: integer
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
  ```
  - Upgrading Harvester `v1.3.2` -> `v1.4.0`
- After the upgrade is completed, the existing BIs are in good shape
  - No waring message like [`warnings.go:70] unknown field "spec.diskFileSpecMap"`](https://github.com/longhorn/longhorn/issues/10644#issue-2951867207)
  - All the BIs have valid copies
  - All the BIs' replicas can provide new/existing volume
      
cc @innobead @bk201 @ChanYiLin @starbops @Vicente-Cheng
