### ISSUE TITLE
[BUG] Failed to migrate vm when the current node enter maintenance mode in two nodes Harvester cluster

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#7965]
### Describe the Bug

* On two nodes Harvester cluster, a virtual machine `vm` created on node `n2-v15`
* When we enter the current host `n2-v15` into maintenance mode
* The VM can't migrate to the first node `n1-v15`, it would keep looping the migrating process
  
  https://github.com/user-attachments/assets/fa203725-e168-43fc-a0ad-65e3e59d5da7
  
  ![Image](https://github.com/user-attachments/assets/6aba6ea5-2a49-4388-91ed-3b58614469c7)

* vm event display the migration failure message
  ```
  VirtualMachineInstance migration uid a4fc06fb-209b-4bd2-8b29-cdd91c707b8e failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=9, Domain=31, Message='operation failed: guest CPU doesn't match specification: missing features: vmx-exit-load-perf-global-ctrl,vmx-entry-load-perf-global-ctrl')
  ```

### To Reproduce

1. Use iso install to create the first node Harvester
2. Use iso install to join the second node 
3. Create a virtual machine `vm` 
4. Set the host where the `vm` located into maintenance mode
5. On the pop up dialog, don't select to force shutdown vm.
6. Check the vm migration state

### Expected Behavior

On two nodes Harvester cluster.
When we set the current host into maintenance mode, all vms on the current node can be migrated to another node

### Support Bundle for Troubleshooting

[supportbundle_fcb1058b-a7f6-43e4-9984-4d047d87789f_2025-03-28T13-14-55Z.zip](https://github.com/user-attachments/files/19506316/supportbundle_fcb1058b-a7f6-43e4-9984-4d047d87789f_2025-03-28T13-14-55Z.zip)

### Environment

- Harvester version: v1.5-1b62d4d1-head (25/03/28)
- Underlying Infrastructure: Two nodes local kvm machines

### Additional context

This issue did not exists on three nodes Harvester cluster.

https://github.com/user-attachments/assets/af7d8815-5900-43bb-b948-912172329078

**Comment by w13915984028** [comment]
@TachunLin The error message says, when `n2-v15` CPU has some features that does not exist in `n1-v15`, vms on `n2` can't migrate to n1.

From the SB, the VM does not set CPU model
```
  spec:
    runStrategy: RerunOnFailure
    template:
      metadata:
        annotations:
          harvesterhci.io/sshNames: '[]'
        creationTimestamp: "null"
        labels:
          harvesterhci.io/vmName: vm1
      spec:
        affinity: {}
        architecture: amd64
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
```

You may try to set below, and try again, thanks.
```
spec:
  domain:
    cpu:
      # this passthrough the node CPU to the VM
      model: host-passthrough
```

```
Default CPU model is set when vmi doesn't have any cpu model. When vmi has cpu model set, then vmi's cpu model is preferred. When default cpu model is not set and vmi's cpu model is not set too, host-model will be set. Default cpu model can be changed when kubevirt is running. When CPUNodeDiscovery feature gate is enabled Kubevirt creates node selector with default cpu model.

CPU model special cases[¶](https://kubevirt.io/user-guide/compute/virtual_hardware/#cpu-model-special-cases)
As special cases you can set spec.domain.cpu.model equals to: - host-passthrough to passthrough CPU from the node to the VM

metadata:
  name: myvmi
spec:
  domain:
    cpu:
      # this passthrough the node CPU to the VM
      model: host-passthrough
...
```
