### ISSUE TITLE
[FEATURE] Add option to select network interface model while importing VM to Harvester using the vm-import-controller

### ISSUE THREAD

**Issue by ghost** [harvester/harvester#7999]
### Describe the Bug

The network interface model of an imported VM is set to "VirtIO" bydefault. Can we have an option to select/configure the network interface model within the VM Import CR?

If not directly configurable in the YAML, can we have a recommended approach (e.g., templates, post-import patching, cloud-init scripting) to achieve these changes automatically during or after import? 

### To Reproduce

- Import a VM from VMware or OpenStack and see the imported VM on Harvester runs with virtIO as network interface model by default.

### Expected Behavior

- Have a option in the VM import CR to configure the network interface model.
OR
- A way such as template/cloudinit script to modify network interface model during import process or after import automatically

### Support Bundle for Troubleshooting

N/A

### Environment

- Harvester version: 1.4.1

### Additional context
- https://suse.slack.com/archives/C02NGQZ8M0F/p1743705680575159

**Comment by votdev** [comment]
In case of VMware, we can "auto-detect" the model type. This can be done [here](https://github.com/harvester/vm-import-controller/blob/29629c75f81f1dfbb0b317d145066acbcc4af899/pkg/source/vmware/client.go#L444).

To be able to override this we can enhance [NetworkMapping](https://github.com/harvester/vm-import-controller/blob/29629c75f81f1dfbb0b317d145066acbcc4af899/pkg/apis/migration.harvesterhci.io/v1beta1/virtualmachines.go#L70).

```
type NetworkMapping struct {
	SourceNetwork      string `json:"sourceNetwork"`
	DestinationNetwork string `json:"destinationNetwork"`
	// Interface model.
	// One of: e1000, e1000e, ne2k_pci, pcnet, rtl8139, virtio.
	// Defaults to virtio.
	InterfaceModel string
}
```

Model will be set then here:
- [VMware source](https://github.com/harvester/vm-import-controller/blob/29629c75f81f1dfbb0b317d145066acbcc4af899/pkg/source/vmware/client.go#L373)
- [OpenStack source](https://github.com/harvester/vm-import-controller/blob/5288366b5627f5c750e50ab4b161410cc95230b7/pkg/source/openstack/client.go#L500)

The default interface model can be specified in the `VirtualMachineImportSpec`. This is used when no
`Mapping` is configured. See [here](https://github.com/harvester/vm-import-controller/blob/29629c75f81f1dfbb0b317d145066acbcc4af899/pkg/source/vmware/client.go#L380) for the VMware source.

```
type VirtualMachineImportSpec struct {
	SourceCluster corev1.ObjectReference `json:"sourceCluster"`

	// VirtualMachineName is the name of the virtual machine that will be
	// imported. It contains the name or ID of the source virtual machine.
	// Note that these names may not be DNS1123 compliant and will therefore
	// be sanitized later.
	// Examples: "vm-1234", "my-VM" or "5649cac7-3871-4bb5-aab6-c72b8c18d0a2"
	VirtualMachineName string `json:"virtualMachineName"`

	Folder string `json:"folder,omitempty"`

	// If empty new VirtualMachineImport will be mapped to Management Network.
	Mapping []NetworkMapping `json:"networkMapping,omitempty"`
	// The Management Network interface model.
	// One of: e1000, e1000e, ne2k_pci, pcnet, rtl8139, virtio.
	// Defaults to virtio.
	ManagementNetworkInterfaceModel string `json:"managementNetworkInterfaceModel,omitempty"`

	StorageClass string `json:"storageClass,omitempty"`
}
```

**Comment by irishgordo** [comment]
@votdev I'm having an issue validating this on:
- Version: v1.6-9d264654-head
With seeing:
```
Error from server (BadRequest): error when creating "vm-import-stuff-manifest.yaml": VirtualMachineImport in version "v1beta1" cannot be handled as a VirtualMachineImport: strict decoding error: unknown field "spec.networkMapping[0].networkInterfaceModel"
Error from server (BadRequest): error when creating "vm-import-stuff-manifest.yaml": VirtualMachineImport in version "v1beta1" cannot be handled as a VirtualMachineImport: strict decoding error: unknown field "spec.defaultNetworkInterfaceModel"
```
With the manifest looking like:
```yaml
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: test-efi-secure-buntu
  namespace: default
spec: 
  virtualMachineName: "test-efi-secure-buntu"
  networkMapping:
  - sourceNetwork: "vCenter-HA-Management"
    destinationNetwork: "harvester-public/vlan2011" 
    networkInterfaceModel: "e1000"
  folder: "gmehta"
  sourceCluster: 
    name: mike-vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: gm-ubuntu-test
  namespace: default
spec: 
  virtualMachineName: "gm-ubuntu-test"
  networkMapping:
  - sourceNetwork: "vCenter-HA-Management"
    destinationNetwork: "harvester-public/vlan2011" 
  defaultNetworkInterfaceModel: "e1000e"
  folder: "gmehta"
  sourceCluster: 
    name: mike-vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
---

```
