### ISSUE TITLE
X-Forwarded-For Header for downstream Cluster

### ISSUE THREAD

**Issue by kfehrenbach** [harvester/harvester#8021]
**Describe the issue**
In my Harvester Setup i need the originating client-ip to be present in the X-Forwarded-For header of the request that is coming from my Browser and is sent to my workload on the downstream cluster.

**Expected behavior**
There should be any configuration to set the header.

**Environment**
 - Harvester ISO version: 1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R630

**Additional context**
I already set the use-forwarded-headers: "true" in the configmap of the nginx-ingress-controller of the downstream cluster, but that doesn't help... 
I extended logging of the nginx-ingress-controller of the downstream cluster:
10.42.1.152 - - [08/Apr/2025:13:18:37 +0000] "GET /api/systemstatus/ HTTP/2.0" 200 164 "https://abc.com/api" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" Host="abc.com" X-Real-IP="-" X-Forwarded-For="-" X-Forwarded-Proto="-" X-Request-ID="-" Authorization="-" Content-Type="-" Accept="application/json, text/plain, */*" Accept-Encoding="gzip, deflate, br, zstd" Cache-Control="-" User-Agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" Cookie="fe-version=3.8.2; fe-version-date=03.06.2024 17:39; SESSION=abc" Custom-Header="-"

As you can see, there is X-Forwarded-For="-"

**Comment by kfehrenbach** [comment]
The remoteaddress 10.42.1.152 (see logs above) is the kube-apiserver of my downstream cluster... can anybody explain me this?

**Comment by bpedersen2** [comment]
Well, at the ingress you would not have any x-forwarded* headers set ( unless you have another  reverse-proxy in front). 

As you don't specify what type of cluster you have and how you deployed nginx-ingress, it is hard to guess what is wrong.

The  ingress should use an LoadBalancer service, if not,then check the externalTrafficPolicy.

**Comment by ihcsim** [comment]
I am guessing the 10.42.1.152 is the IP of the guest node where your ingress controller pod runs. You should see it in the pod's `.status.hostIP`. It looks like the k8s api server IP because the api server runs on the (guest) host network.

**Comment by kfehrenbach** [comment]
No, it's not the IP of the host, it's a cluster internal IP address... i cannot find that IP, when i select all pods and get their ip adresses using kubectl over all namespaces... very strange!

My Setup is very easy and consists of a standard installation of a harvester cluster with 3 servers. Then i used Rancher to setup an k8s Cluster within harvester using the harvester node driver for setup. It then spawns dynamically a k8s-cluster using rke2. Afterwards i deploy my application within this newly created cluster and added a service and ingress for the application. 
Using a windows client with chrome browser from outside connecting to the ingress of typ LoadBalancer works fine, but my application cannot detect the ip adress of my windows client, because the 10.42.1.152 is sent to my application as the source of the request instead of my windows clients ip. And the X-Forwarded-For header just has a dash...

**Comment by Yu-Jack** [comment]
I followed similar steps:

- Install Harvester v1.4.0
- Install Rancher 2.10.2
- Provision a RKE2 downstream cluster
  - Use vlan ID 1 `L2VlanNetwork` `mgmt` network in `Virtual Machine Network`
- Deploy `ClusterIP` service and Nginx ingress
- Access one VM IP.

The log is from my Nginx. I haven't deployed any application, only Nginx. The `192.168.122.1` is my computer internal IP.

`10.42.72.8 - - [11/Apr/2025:07:47:10 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" Host="192.168.122.236" X-Real-IP="192.168.122.1" X-Forwarded-For="192.168.122.1" X-Forwarded-Proto="http" X-Request-ID="514b3bf9efd3517c16fc3d133b73df17" Authorization="-" Content-Type="-" Accept="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" Accept-Encoding="gzip, deflate" Cache-Control="max-age=0" User-Agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" Cookie="-" Custom-Header="-"`

Have you set up any special configurations? Could you provide your configuration? I'm not sure if you're using cloud service as load balancer. If so, I'm guessing that  load balancer of your cloud might have limited the headers.

<details>
<summary>
BTW, here is my deploy configurations. Most are default.
</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" '
                        'Host="$host" '
                        'X-Real-IP="$http_x_real_ip" '
                        'X-Forwarded-For="$http_x_forwarded_for" '
                        'X-Forwarded-Proto="$http_x_forwarded_proto" '
                        'X-Request-ID="$http_x_request_id" '
                        'Authorization="$http_authorization" '
                        'Content-Type="$http_content_type" '
                        'Accept="$http_accept" '
                        'Accept-Encoding="$http_accept_encoding" '
                        'Cache-Control="$http_cache_control" '
                        'User-Agent="$http_user_agent" '
                        'Cookie="$http_cookie" '
                        'Custom-Header="$http_custom_header"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    } 
```

</details>
