### ISSUE TITLE
[BUG] unexpected volume shows when adding to VM

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#8023]
### Describe the Bug

After enable **Longhorn V2 data engine**, the CDI volume will available in the list of adding volume to VM.

![Image](https://github.com/user-attachments/assets/3ac479ba-85b2-4bda-b621-7b28a38fde35)
![Image](https://github.com/user-attachments/assets/7d4f3eea-5382-425c-9006-026f9a6f9143)

### To Reproduce

1. Enable Longhorn V2 data engine [^1]
2. Create image with the storage class using longhorn v2
3. Create an VM `vm1`
4. add volume to VM `vm1`

[^1]: https://docs.harvesterhci.io/v1.5/advanced/longhorn-v2/#using-the-longhorn-v2-data-engine

### Expected Behavior

CDI volume should not shows as the volume to add to VM.

### Support Bundle for Troubleshooting

N/A

### Environment

- Harvester version: **v1.5.0-rc3**, **v1.5-38d3cccf-head**
- Impacted VM: 
- Impacted volume (PV): 
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630):
- Rancher version:

**Comment by Vicente-Cheng** [comment]
It might be an UI issue. We already have a webhook to block this operation.
If we try to hotplug the VM image to the VM we will see the following error.
```
admission webhook "validator.harvesterhci.io" denied the request: PVC default/image-lxpfp is a golden image, it can't be used as a hotplug volume in VM
```

cc @a110605, could we filter out the VM Image PVC in this operation?

**Comment by a110605** [comment]
> It might be an UI issue. We already have a webhook to block this operation. If we try to hotplug the VM image to the VM we will see the following error.
> 
> ```
> admission webhook "validator.harvesterhci.io" denied the request: PVC default/image-lxpfp is a golden image, it can't be used as a hotplug volume in VM
> ```
> 
> cc [@a110605](https://github.com/a110605), could we filter out the VM Image PVC in this operation?

Fixed in https://github.com/harvester/harvester-ui-extension/pull/239

**Comment by w13915984028** [comment]
@a110605 As usual, please add a `test plan` to the ticket, thanks.

**Comment by w13915984028** [comment]
Test Result: **PASS**

Test Setup: v1.5.0-rc4 single-node cluster

Test Steps:

1. One v150-rc4 cluster,
2. Enable LH v2
3. Create a LH v2 SC, single-replica
4. Download image with the new v2 SC;

The new image related PVC `image-g8r5s` has annotation `harvesterhci.io/goldenImage: "true"`
```
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/createdForDataVolume: fbfde512-6366-4d26-886b-821794c29287
    cdi.kubevirt.io/storage.condition.running: "false"
    cdi.kubevirt.io/storage.condition.running.message: ""
    cdi.kubevirt.io/storage.condition.running.reason: ContainerCreating
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.pod.phase: Pending
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.preallocation.requested: "false"
    cdi.kubevirt.io/storage.usePopulator: "true"
    harvesterhci.io/goldenImage: "true"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2025-04-10T14:44:25Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - wrangler.cattle.io/persistentvolumeclaim-controller
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
  name: image-g8r5s
  namespace: default
```

And another PVC `prime-bc600ebf-8c9f-41da-9bf8-0ce05366303d` has no annotation `harvesterhci.io/goldenImage: "true"`

```
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: ""
    cdi.kubevirt.io/storage.condition.running: "false"
    cdi.kubevirt.io/storage.condition.running.message: ""
    cdi.kubevirt.io/storage.condition.running.reason: ContainerCreating
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.import.endpoint: https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
    cdi.kubevirt.io/storage.import.importPodName: importer-prime-bc600ebf-8c9f-41da-9bf8-0ce05366303d
    cdi.kubevirt.io/storage.import.source: http
    cdi.kubevirt.io/storage.pod.phase: Pending
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.populator.kind: VolumeImportSource
    cdi.kubevirt.io/storage.preallocation.requested: "false"
    linkerd.io/inject: disabled
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    sidecar.istio.io/inject: "false"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2025-04-10T14:44:25Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - wrangler.cattle.io/persistentvolumeclaim-controller
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    velero.io/exclude-from-backup: "true"
  name: prime-bc600ebf-8c9f-41da-9bf8-0ce05366303d
  namespace: default
```

The volume/pvc  `image-g8r5s` is not viewable on the `volumes` page

![Image](https://github.com/user-attachments/assets/432d596b-9c42-4691-948d-12e486d95a19)

6. When adding volume to VM, the image volume  `image-g8r5s`  is filter out.

![Image](https://github.com/user-attachments/assets/e8be61ed-5d91-4687-848d-6558219b5e97)

According to original issue description, the `image-g8r5s` is not shown.
