### ISSUE TITLE
[BUG] Set default bond mode to Active-Backup for mgmt during harvester installation

### ISSUE THREAD

**Issue by rrajendran17** [harvester/harvester#8042]
### Describe the Bug

Problem:
The default bond mode set during harvester installation using seeder or ipxe is balance-tlb

Expected Behavior:
The recommended or default bond mode is Active backup

Solution:
Set the default mode to Active backup in harvester-installer when no bond options are specified by user.

Note:This is not applicable to harvester installed in manual mode as install panel defaults to "Active-Backup" and the value cannot be empty

### To Reproduce

Create a harvester cluster using ipxe without specifying  bond options and check the following file.
cat /proc/net/bonding/mgmt-bo

Ethernet Channel Bonding Driver: v5.14.21-150500.55.97-default

Bonding Mode: transmit load balancing
Primary Slave: None
Currently Active Slave: ens6
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0
Peer Notification Delay (ms): 0

Slave Interface: ens6
MII Status: up
Speed: 1000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 02:00:00:0d:62:e2
Slave queue ID: 0

### Expected Behavior

The bonding mode should be Active Backup in /proc/net/bonding/mgmt-bo

Bonding Mode: Active Backup
Primary Slave: None
Currently Active Slave: ens6
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0
Peer Notification Delay (ms): 0

Slave Interface: ens6
MII Status: up
Speed: 1000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 02:00:00:0d:62:e2
Slave queue ID: 0

### Support Bundle for Troubleshooting

.

### Environment

- Harvester version:
- v1.5.0
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630):
- Rancher version:

**Comment by irishgordo** [comment]
@rrajendran17 
As a workaround currently we can with:
- https://github.com/harvester/seeder/blob/9cb5a89fd80ed2f231e49a515a81b1afb8bc0a9f/pkg/api/v1alpha1/cluster_types.go#L47-L59

In a seeder yaml of rrajendran17-test-cluster.yaml in:
```yaml
apiVersion: metal.harvesterhci.io/v1alpha1
kind: Cluster
metadata:
  name: rrajendran17-test
  namespace: tink-system
spec:
  clusterConfig:
    bondOptions:
      mode: "active-backup"
      miimon: 100
    nameservers:
    - 8.8.8.8
    vlanID: 2021
    wipeDisks: true
    streamImageMode: false
  imageURL: http://A.B.C.D/iso/
  nodes:
  - addressPoolReference:
      name: vlan2021-static-pool
      namespace: tink-system
    inventoryReference:
      name: hp-NN
      namespace: tink-system
  version: v1.5.0-rc4
  vipConfig:
    addressPoolReference:
      name: vlan2021-static-pool
      namespace: tink-system
```

Set it to `active-backup` - but yes, currently, by default it's set to `balance-tlb` when bondOptions aren't specified in the yaml:
- https://github.com/harvester/seeder/blob/9cb5a89fd80ed2f231e49a515a81b1afb8bc0a9f/pkg/tink/tink.go#L42-L45

**Comment by rrajendran17** [comment]
Thanks @irishgordo for pointing this out.Then I think the similar changes are needed in the file you pointed out.
Currently I have changes only in harvester-installer code which is only applicable for ipxe installation.

**Comment by albinsun** [comment]
Hi @votdev ,
Please help to verify this issue, thank you.

**Comment by votdev** [comment]
Verified this bug has been fixed.

### Setup
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.6.0-rc5**
* PXE boot via [pixiecore](https://github.com/danderson/netboot/tree/main/pixiecore)

1. Prepare preseed config
```
scheme_version: 1
token: token
os:
  hostname: node0
  dns_nameservers:
  - 192.168.121.1
  - 8.8.8.8
  password: harvester
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
  ssh_authorized_keys:
  - ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxx
  sshd:
    sftp: true
install:
  mode: create
  management_interface:
    interfaces:
      - name: ens6
    default_route: true
    method: dhcp
#   bond_options:
#     mode: balance-tlb
#     miimon: 100
  device: /dev/vda
  data_disk: /dev/vda
  vip: 192.168.121.102
  vip_mode: dhcp
  vip_hw_addr: 52:54:00:8d:1d:21
```
2. Run pixiecore
```
$ docker run --network vagrant-libvirt -v ~/Data/images:/image pixiecore/pixiecore:master boot /image/harvester-v1.6.0-rc5-vmlinuz-amd64 /image/harvester-v1.6.0-rc5-initrd-amd64 --cmdline='ip=dhcp net.ifnames=1 rd.cos.disable rd.live.debug=1 rd.noverifyssl cos.install.power_off=true root=live:{{ ID "./image/harvester-v1.6.0-rc5-rootfs-amd64.squashfs" }} console=tty1 harvester.install.automatic=true harvester.install.skipchecks=true harvester.install.config_url={{ ID "./image/harvester-config-create.yaml" }} harvester.install.iso_url={{ ID "./image/harvester-v1.6.0-rc5-amd64.iso" }}'
```
3. After installation, check the iface bonding configuration:
<img width="551" height="373" alt="Image" src="https://github.com/user-attachments/assets/a42852b0-ef5c-40e1-ba01-6b195db1ddc5" />
