### ISSUE TITLE
[ENHANCEMENT] Reduce the downtime for VMs with PCI devices during Harvester upgrade

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#8049]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

During the Harvester 1.3.2 -> 1.4.0 upgrade, VMs with PCI Passthrough (GPU) must be powered off and remain off during the entire process, causing significant downtime for critical workloads.

### Describe the solution you'd like

VMs with PCI passthrough should only be powered off while the specific node is updated, allowing us to balance workloads between two nodes.

**Comment by ihcsim** [comment]
To recap, it seems like the current implementation at 83b89e820f739a9333182cf22ca0c4ab41301226 triggers a reconciliation loop every time an annotation update is made per VM. This happens as the original upgrade reconciliation tries to complete. We explore putting the annotations either at the VM or node level, each has its pros and cons, and require us to retain and coordinate restart states throughout the whole upgrade process.

To simplify the logic and have a more reliable persistence mechanism, we decided to store the list of non-migratable VMs in a configmap, with an owner reference to the upgrade object.

@brandboat let me know if i missed anything from our discussion.

In pre-drain job, store the non-migratable VM information to a configmap.
* The configmap includes label to record the upgrade uuid to help the job in step 2 determine which upgrade it is associated with
* Set configmap owner reference to the upgrade object, once upgrade is deleted, the configmap is gone.
 
Here is the configmap example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-non-migratable-vms-xdkj #generated name
  namespace: harvester-system
  labels:
    upgrade-uuid: 123e4567-e89b-12d3-a456-426614174000
  ownerReferences: #the upgrade object
    ...
data:
  node-1: default/vm1,default/vm2
  node-2: default/vm3
  node-3: default/vm4,default/vm5,default/vm6
```

After the node reboots, we submit the VM restart job. We can do this in [here](https://github.com/harvester/harvester/blob/ccabfab00f0c97b898a27408fe730d5b55bd5702/pkg/controller/master/upgrade/node_controller.go#L84-L109).

This job is fire-and-forget, and won't block the upgrade process even if it failed.

We do not want to wait for vm status and delay the upgrade even more.

The restart is done on a best-effort basis. E.g., if vm failed to be restarted, we won't retry forever. If configmap is lost, no restart will happen. We can emit some `event`s to record these key events (so that they will be captured in SB):
* configmap is created
* configmap failed to be created (e.g., due to size limit)
* vm stopped (maybe just total number stopped)
* vm restarted (total number restarted)
* vm failed to restart (vm name and failed reason)

Although a configmap's data is limited to 1MiB, that's still a lot of space to store non-migratable VMs.

cc @brandboat @ibrokethecloud @w13915984028
