### ISSUE TITLE
[FEATURE] Extend vm-import-controller to support 3rd party CSI

### ISSUE THREAD

**Issue by innobead** [harvester/harvester#8074]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

3rd party storage support for VM importer.

**Comment by Vicente-Cheng** [comment]
Hi @votdev, 
Could we move this to Ready for testing?

**Comment by irishgordo** [comment]
I've opened, https://github.com/harvester/harvester/issues/8848 as we could maybe expand on the docs related to vm import controller when it's using a Volume that's been enabled that's of a different storage-class than the vms are specified on in their spec.

**Comment by irishgordo** [comment]
I've also opened, https://github.com/harvester/harvester/issues/8849 to track the silent failure when storage class with 3rd party csi is used and there's no space available

**Comment by irishgordo** [comment]
@votdev I'm seeing several issues with this on v1.6.0-rc3.

When building a storage class that targets 1 node, that one node having LVM set up on a single disk with a new volume group.
Then using that storage class for the VM that is to be imported from OpenStack, it's failing.
It hangs at 0% download

When building a storage class of `nfs-csi` that is using nfs it is also failing.
It winds up in a "downloading" loop, where it's complaining that `/scratch` doesn't have enough space.
With nfs-csi, I'm noticing from the pvc side on vm import of cirros-tiny for instance:
- first (both on nfs-csi):
    - PVC, image-mzhxc
    - PVC, prime, non-scratch
- second (on harvester longhorn):
    - PVC, prime, scratch
So for some reason, scratch pvc is also built on `harvester-longhorn` and not using the `nfs-csi`.



Either taking the shape of:
```yaml
#---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: cirros-tiny
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  storageClass: vg-lvm-dm-thin
  sourceCluster: 
    name: mike-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
  forcePowerOff: true
```

Or:
```yaml
#---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: cirros-tiny
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  storageClass: nfs-csi
  sourceCluster: 
    name: mike-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
  forcePowerOff: true

```


Some artifacts:

<img width="2056" height="756" alt="Image" src="https://github.com/user-attachments/assets/9e42e00d-24c7-48ce-846a-4f6504d81b36" />
<img width="2029" height="708" alt="Image" src="https://github.com/user-attachments/assets/4a583543-8901-426e-aa0f-5be0a451bb0c" />
<img width="3820" height="1905" alt="Image" src="https://github.com/user-attachments/assets/1ab0f0ec-4d43-4185-a04f-822fd1f47e5c" />
<img width="3838" height="1967" alt="Image" src="https://github.com/user-attachments/assets/a251c837-db9f-4ea6-a53b-0e1f3733e314" />
<img width="2094" height="969" alt="Image" src="https://github.com/user-attachments/assets/c1912735-49e7-431b-9fd4-ee0599b950bd" />
<img width="2154" height="976" alt="Image" src="https://github.com/user-attachments/assets/d96a56f7-95d9-4379-bae0-8ea219de92f9" />
<img width="2136" height="1036" alt="Image" src="https://github.com/user-attachments/assets/f383d9ec-cd5c-44eb-8cab-164df2f79a30" />
<img width="2120" height="378" alt="Image" src="https://github.com/user-attachments/assets/eee18f06-1c1e-4922-9632-915a40858f47" />
<img width="2121" height="982" alt="Image" src="https://github.com/user-attachments/assets/0e4009b2-5219-48b8-b214-cc090a912afb" />
<img width="1671" height="1915" alt="Image" src="https://github.com/user-attachments/assets/e2e90fbf-38bf-4073-a3bc-c4991e5578c9" />
