### ISSUE TITLE
[FEATURE] Upgrade via ISO Upload

### ISSUE THREAD

**Issue by innobead** [harvester/harvester#8078]
Allow users to upgrade by uploading an ISO, in addition to the existing options of automatic version sync from the Harvester endpoint, or a user-created Version CR with a remote ISO endpoint. Provide a clear UX procedure for this upload-based upgrade.

**Comment by starbops** [comment]
Is this similar to what #7690 described (though it did not work in v1.5.0)?

**Comment by innobead** [comment]
> Is this similar to what [#7690](https://github.com/harvester/harvester/issues/7690) described (though it did not work in v1.5.0)?

Exactly, we might need to improve the current experience to make this feature an official path for users. 

cc @harvester/pm

**Comment by a110605** [comment]
ui issues :
- https://github.com/harvester/harvester/issues/7690
- https://github.com/harvester/harvester/issues/8079

**Comment by a110605** [comment]
Hi @brandboat, there is unknown webhook to block system upgrade via uploading an image method.
The issue is observed in harvester master and v1.5.0. 
But it's good on v1.4.3-rc4.

<img width="1489" alt="Image" src="https://github.com/user-attachments/assets/c9cb6955-288e-4155-8c29-5ab67cbfc2ed" />

**Comment by a110605** [comment]
Test in ipxe environment, it's quite fast to upload a harvester image locally (within 1min).

But test against to a ECM machine, there is 408 request timeout (around 5 min) to abort the upload API (`/v1/harvester/harvesterhci.io.virtualmachineimages/harvester-system/image-zq6k5?action=upload&size=6184173568`) . Not sure it's caused Suse VPN.

@brandboat , @ibrokethecloud , do you think is it possible to fine tune the timeout from backend ? 
 
<img width="1489" alt="Image" src="https://github.com/user-attachments/assets/d1795b6e-06d7-45f9-b252-6927878f089e" />
<img width="1490" alt="Image" src="https://github.com/user-attachments/assets/ed288003-4561-4ee4-9985-0f2b0c013e04" />

**Comment by brandboat** [comment]
> Hi @brandboat, there is unknown webhook to block system upgrade via uploading an image method.
The issue is observed in harvester master and v1.5.0.
But it's good on v1.4.3-rc4.

The root cause is we didn't check if the version object exists in ugprade/validator.go#checkCerts https://github.com/harvester/harvester/blob/master/pkg/webhook/resources/upgrade/validator.go#L647, if we directly create upgrade object without first creating a version object, a NPE occurred, causing the upgrade creation process to fail.

Now there are two validations in upgrade/validator.go rely on the version object:
- skipGarbageCollectionThresholdCheck https://docs.harvesterhci.io/v1.5/upgrade/index/#skipgarbagecollectionthresholdcheck-annotation
- minCertsExpirationInDay https://docs.harvesterhci.io/v1.5/upgrade/index/#mincertsexpirationinday-annotation

After discussing with @FrankYang0529 offline, we can move these 2 checks(annotations) to the Upgrade object. This change would prevent the NPE while keeping the validation logic.

**Comment by brandboat** [comment]
see https://github.com/harvester/harvester/pull/8333#issuecomment-2897506069

@w13915984028 , let's discuss here

> ATM, the upgrade has some inconsistencies in user exprience, and when ISO based upgrade is added, we need to keep/improve user experience as well. This PR might not be the best places to dicsuss, forgive me.
> 
> Traditional Upgrade:
> (1) UI, user can set settings, click upgrade menu and click enable upgradeog and start upgrade; the missing part is above two > annotations;
> (2) CLI, user can create version, upgrade to start upgrade
> 
> ISO based upgrade:
> (1) UI, similar to above
> (2) CLI, create image by upload ISO/URL, create upgrade ? any additional steps are needed/not feasible? suppose user needs to customize it this way to outcome some issue, a detailed step description is needed on the doc.

For the CLI part of ISO based upgrade,  user have to create a VirtualMachineImage first, something like this:
```
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/image-name: harvester-v1.5.0-amd64.iso
    harvesterhci.io/os-upgrade-image: "True"
  generateName: image-
  namespace: harvester-system
spec:
  backend: backingimage
  displayName: harvester-v1.5.0-amd64.iso
  sourceType: download
  url: http://192.168.100.1/iso/v1.5.0/harvester-v1.5.0-amd64.iso
```
then create the upgrade CR
```
apiVersion: harvesterhci.io/v1beta1
kind: Upgrade
metadata:
  generateName: hvst-upgrade-
  namespace: harvester-system
spec:
  image: "harvester-system/image-gs8kl"
  logEnabled: true
```
