### ISSUE TITLE
[BUG] ipxe installation, unable to set dns server and environment variable

### ISSUE THREAD

**Issue by kingsd041** [harvester/harvester#810]
**Describe the bug**

ipxe installation, unable to set dns server and environment

**To Reproduce**
1. Follow the [harvester-configuration](https://github.com/harvester/harvester/blob/master/docs/harvester-configuration.md) to set the harvester configuration, for example:
```
#cloud-config
token: ksd-token
os:
  ssh_authorized_keys:
  - github:kingsd041
  dns_nameservers:
  - 114.114.114.114
  environment:
    nnn: kkk
install:
  mode: create
  mgmt_interface: eth0
  device: /dev/sda
  iso_url: http://x.x.x.x/harvester/harvester-amd64.iso
```
2. Install harvester via pxe
3. After waiting for the harvester to start, check the dns server and environment variables of the host
```
hailong-hvst-2 [~]$ cat /etc/resolv.conf
# Generated by Connection Manager
nameserver 147.75.207.207
nameserver 147.75.207.208
hailong-hvst-2 [~]$ export| grep -i nnn
hailong-hvst-2 [~]$
```
**Expected behavior**

1. dns server should be `114.114.114.114`
2. There should be an environment variable `nnn=kkk`

**Log**

Note: `dnsNameservers` in the k3os configuration is the wrong name
```
# cat /k3os/system/config.yaml
hostname: kkk-node1
k3os:
  dnsNameservers:
  - 114.114.114.114
  - 8.8.8.8
  environment:
    ddd: sss
    nnn: kkk
```

**Environment:**
 - Harvester ISO version:  0.2.0-rc5
 - Installation Mode: IPXE 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): equinix

**Additional context**
