### ISSUE TITLE
[ENHANCEMENT] Upgrade pre-flight checks the matching between node and machine objects

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#8179]
### Is your enhancement request of an existing feature related to a problem? Please describe (👍 if you like this request)

Very rarely, the node is installed, but the related machine object is not created, the mis-matching may cause a couple of upgrade issues.

e.g., upgrade blocks `"Plan $plan_name completes."`
 https://github.com/harvester/harvester/blob/44b1d5b33173c142d18050bc517374b5f8121570/package/upgrade/upgrade_manifests.sh#L1112

### Describe the solution you'd like

The upgrade pre-flight check works upon this case.

### Describe alternatives you've considered

Review the waiting upon `plan` object.

### Additional context

Refer https://github.com/w13915984028/harvester-develop-summary/blob/main/one-v132-v140-upgrade-issue-analysis.md#why-upgrade-is-stucking-on-waiting-for-plan

**Comment by albinsun** [comment]
Test PASS, close as fixed.


## Environment
* `harvester-v1.6.0-rc2`
  * Profile: 2 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`


## Test Scenario
1. <details>
   <summary> Create a 2 nodes cluster
   </summary>

   <img width="1598" height="807" alt="Image" src="https://github.com/user-attachments/assets/23a7cdf6-93de-449d-812b-f7ed50bec270" />
   </details>

1. <details>
   <summary> Create a fake machine for testing
   </summary>

   machine.yaml
    ```
    apiVersion: cluster.x-k8s.io/v1beta1
    kind: Machine
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: local
        cluster.x-k8s.io/control-plane: "false"
        rke.cattle.io/cluster-name: local
        rke.cattle.io/control-plane-role: "false"
        rke.cattle.io/etcd-role: "false"
        rke.cattle.io/worker-role: "true"
      name: custom-4d279419a084
      namespace: fleet-local
    spec:
      bootstrap:
        configRef:
          apiVersion: rke.cattle.io/v1
          kind: RKEBootstrap
          name: custom-4d279419a084
          namespace: fleet-local
        dataSecretName: custom-4d279419a084-machine-bootstrap
      clusterName: local
      infrastructureRef:
        apiVersion: rke.cattle.io/v1
        kind: CustomMachine
        name: custom-4d279419a084
        namespace: fleet-local
      nodeDeletionTimeout: 10s
      providerID: rke2://harv44
    ```

   <img width="1598" height="401" alt="Image" src="https://github.com/user-attachments/assets/b6797efb-531f-456d-b8b7-68d11430ab5a" />
   </details>

1. <details open>
   <summary> ✔️ Trigger a same-version upgrade, should be denied with <code>machine xxx is not running</code>
   </summary>

   <img width="1598" height="880" alt="Image" src="https://github.com/user-attachments/assets/4e7c3a4e-119e-44fe-8961-94a2ac3f6ef0" />
   </details>
