### ISSUE TITLE
[BUG] Release of duplicate loadbalancer IP fails with error "fail to get allocator"

### ISSUE THREAD

**Issue by ghost** [harvester/harvester#8221]
### Describe the Bug

This is a followup issue to #7449.

When the duplicate allocation state occurs, the load balancer controller fails to execute the release logic added with 1.5, with the following log entries:

  ```
2025-05-07T07:26:08.267801060Z time="2025-05-07T07:26:08Z" level=debug msg="lb harvester-public/cluster-name-namespace-lb-name-hash is changed, spec: {Description: WorkloadType:cluster IPAM:pool IPPool: Listeners:[] BackendServerSelector:map[] HealthCheck:<nil>}, apiVersion: loadbalancer.harvesterhci.io/v1beta1"
2025-05-07T07:26:08.267838824Z time="2025-05-07T07:26:08Z" level=debug msg="lb harvester-public/cluster-name-namespace-lb-name-hash fail to allocate from pool 10.251.105.62 has been allocated to harvester-public/cluster-name-namespace-lb-name-hash, duplicate allocation is not allowed"
2025-05-07T07:26:08.267841918Z time="2025-05-07T07:26:08Z" level=info msg="lb harvester-public/cluster-name-namespace-lb-name-hash error: 10.251.105.62 has been allocated to harvester-public/cluster-name-namespace-lb-name-hash, duplicate allocation is not allowed, try to release ip to pool , error: fail to get allocator "
2025-05-07T07:26:08.267880356Z time="2025-05-07T07:26:08Z" level=error msg="error syncing 'harvester-public/cluster-name-namespace-lb-name-hash': handler harvester-lb-controller: 10.251.105.62 has been allocated to harvester-public/cluster-name-namespace-lb-name-hash, duplicate allocation is not allowed, requeuing"
  ```

The problem seems to be caused by the fact that the IP pool used cannot be correctly identified. The Loadbalancers in our environment are created by the harvester cloud provider, without explicitly specifying an IP Pool, and rely on the autoamtic selection logic selecting one "global" pool.

### To Reproduce

- Create a lot of loadbalancers without explicitly specifying an IP pool at the same time.
- Observe the loadbalancers becoming "stuck" with the error message from above in the log of the load balancer controller

### Expected Behavior

The allocated duplicate IP should be released back into the pool

### Support Bundle for Troubleshooting

Can be provided privately upon request.

### Environment

- Harvester version: 1.4.2, with the Loadbalancer Controller manually updated to 1.5.0, as described [here](https://docs.harvesterhci.io/v1.4/rancher/cloud-provider#guest-cluster-load-balancer-ip-permanently-stuck-in-ipam-mode)
- Impacted VM: n/a
- Impacted volume (PV): n/a
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630): Baremetal Dell Servers
- Rancher version: 2.10.3

### Additional context

Tagging @w13915984028, as he implemented the fix for the original issue.

### Workaround and Mitigation

It is possible to manually modify the IPPool.loadbalancer.harvesterhci.io/v1beta1 CRD and remove the failed allocations.

**Comment by w13915984028** [comment]
@kisv-SOPTIM Thanks for reporting, I will investigate it.

**Comment by w13915984028** [comment]
@kisv-SOPTIM Please also help generate a SB and upload here https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle

If you can't do it, then please get the `ippool` and `lb` object's yaml output from Harvester cluster and post here. thanks.

**Comment by ghost** [comment]
> [@kisv-SOPTIM](https://github.com/kisv-SOPTIM) Please also help generate a SB and upload here https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle
> 
> If you can't do it, then please get the `ippool` and `lb` object's yaml output from Harvester cluster and post here. thanks.

Thanks for taking a look at the issue! I have provided you with a support bundle of our cluster via Slack.

**Comment by w13915984028** [comment]
With the PR https://github.com/harvester/load-balancer-harvester/pull/53, I made an image for @kisv-SOPTIM , and Sven kindly helped validated on his cluster, the issue was solved now.

Thanks @kisv-SOPTIM again.

**Comment by w13915984028** [comment]
FYI: If you encounter this issue too, please run `kuectl edit managedchart -n fleet-local harvester`, and set the `image.repository` and `image.tag`,  suppose the image will be pull from [docker hub harvester-load-balancer master-head](https://hub.docker.com/layers/rancher/harvester-load-balancer/master-head/images/sha256-7afb56d5bd0130bd8d54f757fd4d39c2e597027ecedb268eef930421c8b2cc6d)

```
spec:
  chart: harvester
  defaultNamespace: harvester-system
  values:
    harvester-load-balancer:
      enabled: true
      image:
        imagePullPolicy: IfNotPresent
        repository: rancher/harvester-load-balancer  // add to your cluster 
        tag: master-head // add to your cluster ; master-head or v1.5.1-dev.0
```

Another image tag [v1.5.1-dev.0](https://github.com/harvester/load-balancer-harvester/releases/tag/v1.5.1-dev.0) solves the issue as well.

cc @kisv-SOPTIM Please also set above on your cluster.

**Comment by albinsun** [comment]
Hi @starbops,
Please help to verify this issue, thank you.

**Comment by Vicente-Cheng** [comment]
Hi @martindekov, 
Since @starbops is working on the upgrade issue, could you help verify this issue? Thanks!

**Comment by Vicente-Cheng** [comment]
Verify PASS, closed as complete.


## Environment
* `harvester-v1.6.0-rc5`
* Profile: 2 nodes AMD64 QEMU/KVM
* External-Rancher: v2.12.0 + v1.6.0-rc5 ui-ext
* ui-source: `Auto`


## Test Scenario
1. <details>
   <summary> Create cluster, imported with external rancher and create guest cluster
   </summary>

   </details>

1. <details>
   <summary> Create IP Pool based on the mgmt network
   </summary>

     <img width="1182" height="698" alt="Image" src="https://github.com/user-attachments/assets/fac32dbc-b3de-4ccf-9c82-550157ecfd68" />

     <img width="1171" height="693" alt="Image" src="https://github.com/user-attachments/assets/cf278e38-6fba-4340-82e8-589eef0dc95e" />

   </details>

1. <details>
   <summary> Create a lot of loadbalancers without explicitly specifying an IP pool at the same time.
   </summary>

     Create 10 loadbalancers with the below yaml files.
     ```
     apiVersion: loadbalancer.harvesterhci.io/v1beta1
     kind: LoadBalancer
     metadata:
       annotations:
         loadbalancer.harvesterhci.io/namespace: default
         loadbalancer.harvesterhci.io/network: ""
         loadbalancer.harvesterhci.io/project: c-s5gg4/p-bgh4n
       name: lb01
       namespace: default
     spec:
       backendServerSelector:
         app:
         - nginx
       healthCheck: {}
       ipam: pool
       listeners:
       - backendPort: 80
         name: http
         port: 8080
         protocol: TCP
       workloadType: vm
     `````

     We can see all IP were allocated (and no duplicated), just no corresponding service backend
     
     <img width="1169" height="712" alt="Image" src="https://github.com/user-attachments/assets/265b94ac-8727-437f-bcc5-2b8db81add08" />

   </details>
