### ISSUE TITLE
[BUG] The NAD could be deleted when it still used by VMs

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#8293]
### Describe the Bug

When testing
https://github.com/harvester/harvester/issues/6961
https://github.com/harvester/harvester/pull/7743

https://github.com/harvester/harvester/pull/8110

one issue is observed:

When one VM is `Off`, and the realted `nad` is deleted (not protected by PR yet), then edit VM to remove the dangling interface does not work, the only workaround is to delete the VM (https://github.com/harvester/harvester/pull/8110 is merged)

### To Reproduce

1. Create an VM, refer to a second network with a custom nad
2. Stop the VM
3. Delete the nad
4. Edit VM to remove the second network

Such error is reported:

![Image](https://github.com/user-attachments/assets/0eb8af5b-a0a9-402a-a785-f50eab0029be)

### Expected Behavior

Should not report error when user removes the dangling interface

### Support Bundle for Troubleshooting

not needed

### Environment

- Harvester version: master-head; v1.5, v1.4
- Impacted VM: 
- Impacted volume (PV): 
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630):
- Rancher version:

### Additional context

This is a side-effect of VM duplicated MAC check:

In most cases, the validator works on newVM, but rarely, it works on oldVM

https://github.com/harvester/harvester/blob/db6f22f419fda9d012768b94a9a0aa9cba73da16/pkg/webhook/resources/virtualmachine/validator.go#L192

When oldvm has dangling resources, the above function reports error.

**Comment by w13915984028** [comment]
cc @rrajendran17

**Comment by w13915984028** [comment]
A VM can have 2 interfaces from same network, the current check looks missing this part.

![Image](https://github.com/user-attachments/assets/318d46f9-188b-4e00-aa09-9462c339b48f)

```
      hostname: vm1
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/v200
          name: nic-1
        - multus:
            networkName: default/v200
          name: nic-2
```
