### ISSUE TITLE
add image metadata info to the DV annotations

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#83]
add image metadata `ns:name` to the dataVolume template annotations when creating the VirtualMachine, therefore user/UI will be able to know which image the URL is related.
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
spec:
  dataVolumeTemplates:
  - metadata:
      annotations:
        harvester.cattle.io/imageId: default:myimage ## add image metadata annotation with `ns:name`
      name: lawr-ubuntu
    spec:
      pvc: {...}
      source:
        http:
          url: http://minio.default:9000/vm-images/xxxxx
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: lawr-ubuntu
    spec: {...}
```
