### ISSUE TITLE
[BUG] `upgrade-checker-url` not displaying as proper value in UI

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#8310]
### Describe the Bug

If user has something like:
```yaml
scheme_version: 1
system_settings:
  upgrade-checker-enabled: false
  upgrade-checker-url: ""
```
And installs w/ config.yaml for the cluster.
The upgrade-checker-url remains the `https://harvester-upgrade-responder.rancher.io/v1/checkupgrade` in the UI and does not update.

If you describe the upgrade-checker-url:
```yaml
Name:         upgrade-checker-url
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  harvesterhci.io/v1beta1
Default:      https://harvester-upgrade-responder.rancher.io/v1/checkupgrade
Kind:         Setting
Metadata:
  Creation Timestamp:  2025-05-16T19:54:11Z
  Generation:          3
  Managed Fields:
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2025-05-16T19:54:11Z
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:default:
      f:status:
      f:value:
    Manager:         harvester
    Operation:       Update
    Time:            2025-05-16T20:04:50Z
  Resource Version:  13863
  UID:               e28c1ca8-8467-4864-a35b-f77cd3cb2e44
Status:
Value:   
Events:  <none>
```

### To Reproduce

1. install a cluster with a config.yaml, specifying the system_setting to set the upgrade-checker-enabled to false and the upgrade-checker-url to an empty string
2. wait for the cluster to be online, see that the value does not display in the UI

other method:
1. have a cluster ready
2. modify the value in the UI to set it to an empty string
3. see that it does not bubble up that value to the UI but it does persist it on the backend

### Expected Behavior

The UI to reflect the value.

### Support Bundle for Troubleshooting

N/A

### Environment

- Harvester version: v1.4.3-rc3
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630): qemu/kvm

### Additional context

![Image](https://github.com/user-attachments/assets/2e1b5ed0-9466-4c22-bb55-9ab7f3805059)

You can set it as the default value and also an empty string and see on the backend it changes but the UI isn't reflecting this.

```
╭─mike at suse-workstation-team-harvester in ~/Downloads/temptemp
╰─○ kubectl describe settings/upgrade-checker-url 
Name:         upgrade-checker-url
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  harvesterhci.io/v1beta1
Default:      https://harvester-upgrade-responder.rancher.io/v1/checkupgrade
Kind:         Setting
Metadata:
  Creation Timestamp:  2025-05-16T19:54:11Z
  Generation:          4
  Managed Fields:
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2025-05-16T19:54:11Z
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:default:
      f:status:
      f:value:
    Manager:         harvester
    Operation:       Update
    Time:            2025-05-16T20:16:36Z
  Resource Version:  21326
  UID:               e28c1ca8-8467-4864-a35b-f77cd3cb2e44
Status:
Value:   https://harvester-upgrade-responder.rancher.io/v1/checkupgrade
Events:  <none>
╭─mike at suse-workstation-team-harvester in ~/Downloads/temptemp
╰─○ kubectl describe settings/upgrade-checker-url 
Name:         upgrade-checker-url
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  harvesterhci.io/v1beta1
Default:      https://harvester-upgrade-responder.rancher.io/v1/checkupgrade
Kind:         Setting
Metadata:
  Creation Timestamp:  2025-05-16T19:54:11Z
  Generation:          5
  Managed Fields:
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2025-05-16T19:54:11Z
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:default:
      f:status:
      f:value:
    Manager:         harvester
    Operation:       Update
    Time:            2025-05-16T20:16:50Z
  Resource Version:  21482
  UID:               e28c1ca8-8467-4864-a35b-f77cd3cb2e44
Status:
Value:   
Events:  <none>
```

### Workaround and Mitigation

N/A
