### ISSUE TITLE
[BUG] pcidevice enablement fails with rancher v2.10.1 and harvester v1.4.1

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#8346]
### Describe the Bug

Enabling a pcidevice when accessing via rancher 2.10.1 and Harvester v1.4.1 fails.

The device is stuck in enabling stage.

### To Reproduce

* setup a rancher v2.10.1 cluster
* import harvester v1.4.1 cluster
* enable the pcidevices controller addon in harvester
* enable a pcidevice via rancher

device will stay stuck in enabling phase.

### Expected Behavior

pcidevice should be enabled successfully

### Support Bundle for Troubleshooting

Not applicable

### Environment

- Harvester version: v1.4.1
- Impacted VM: 
- Impacted volume (PV): 
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630):
- Rancher version: v2.10.1

### Additional context

The pcidevice claim is missing ownership reference for the pcidevices.

This causes the pcideviceclaim to be requeued by the pcidevice controller and UI reflects the same by showing the device is being enabled.

### Workaround and Mitigation

Manually adding the owner reference to the pcideviceclaim allows the claim to be processed successful

```
  ownerReferences:
  - apiVersion: devices.harvesterhci.io/v1beta1
    kind: PCIDevice
    name: tekton28a-0000c1000
    uid: cb439de7-3145-4b0f-a64e-f34a4dec2059
```
