### ISSUE TITLE
[BUG] host-model-cpu not in cpu-model.node

### ISSUE THREAD

**Issue by zelitomas** [harvester/harvester#8361]
### Describe the Bug

It is impossible to schedule a VM with template 
```yaml
spec:
  template:
    spec:
      domain:
        cpu:
          model: EPYC-Rome
``` 
on a node with host-model-cpu.node.kubevirt.io/EPYC-Rome, because this definition creates a pod that has following nodeSelector
```yaml
  nodeSelector:
    cpu-model.node.kubevirt.io/EPYC-Rome: "true"
    kubernetes.io/arch: amd64
    kubevirt.io/schedulable: "true"
```
and `cpu-model.node.kubevirt.io/EPYC-Rome` is not present for a node with `host-model-cpu.node.kubevirt.io/EPYC-Rome`

### To Reproduce

 * Install harvester 1.5.0 on node with `host-model-cpu.node.kubevirt.io/EPYC-Rome`
 * Create a VM and set `spec.template.spec.domain.cpu.model` to `EPYC-Rome`
 * Try to run the VM. The VM can only be scheduled to nodes with higher CPU models (for example `EPYC-Genoa`), but not on `EPYC-Rome` itself.

### Expected Behavior

 * Nodes that have host-model-cpu.node.kubevirt.io/EPYC-Rome should be able to schedule VM with `spec.template.spec.domain.cpu.model` set to `EPYC-Rome` 

### Support Bundle for Troubleshooting

[supportbundle_14480d9c-2288-4d5f-aa7e-e5422cce7bd3_2025-05-26T16-13-31Z.zip](https://github.com/user-attachments/files/20443892/supportbundle_14480d9c-2288-4d5f-aa7e-e5422cce7bd3_2025-05-26T16-13-31Z.zip)

### Environment

- Harvester version: 1.5.0
- Underlying Infrastructure: Baremetal with EPYC-Rome microarchitecture

### Workaround and Mitigation

Manually labeling the node with `kubectl label node node-rome-01 cpu-model.node.kubevirt.io/EPYC-Rome=true` does not seem to resolve the issue
