### ISSUE TITLE
[DOC] Document steps to specify service CIDR during creation of harvester-vm-dhcp-controller add-on

### ISSUE THREAD

**Issue by rrajendran17** [harvester/harvester#8448]
### Document request

Problem:
Currently the vm-dhcp-controller webhook returns the following error when trying to create an IPPool using the service cidr 10.53.0.0/16 though the service cidr used in the cluster is different.

Error from server (InternalError): error when creating "STDIN": admission webhook "validator.harvester-system.harvester-vm-dhcp-controller-webhook" denied the request: Internal error occurred: cannot create IPPool infrastructure/vlan83 because cidr 10.53.83.0/24 overlaps cluster service cidr 10.53.0.0/16

The current implementation of the default-to-10.53.0.0/16 was the final decision of the [GH ticket #5153](https://github.com/harvester/harvester/issues/5153), which left a configurable way for users to manually specify the service CIDR flexibly. There was no reliable ways to dynamically determine the service CIDR that the cluster is using. So the workaround is to specify the correct service CIDR in the Addon CR. For example:

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: harvester-vm-dhcp-controller
  namespace: harvester-system
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: true
  repo: https://charts.harvesterhci.io
  version: 1.5.0
  chart: harvester-vm-dhcp-controller
  valuesContent: |
    serviceCIDR: 10.62.0.0/16
```

That way, the vm-dhcp-webhook will be run with the provided service CIDR.

Solution:
Document the limitation and provide steps to specify service CIDR during creation of harvester-vm-dhcp-controller add-on in case the service cidr used is different from default 10.53.0.0/16.
