### ISSUE TITLE
[Help wanted] host changes to cordoned after 5 minutes

### ISSUE THREAD

**Issue by laralar** [harvester/harvester#8454]
**Describe the issue**
I have a 4 host harvester cluster and originally I had the #8182 issue, however, I can't wait for the fix.  So I decided to remove the host, reinstall it and add it again as worker node (it was a control plane node)

![Image](https://github.com/user-attachments/assets/73f29456-1144-4091-a512-b84b5662d98a)

However the host gets to Ready state in the console, but it nevers gets **Active** in the dashboard. It remains **Cordoned**

![Image](https://github.com/user-attachments/assets/c9529173-726b-4450-b244-bafb468b5896)

If I manually Uncordon the host, or if I enable the maintenance mode and then disable it.  it goes to the desired **Active** state.

I can run VMs there.. with Issue #8182 I couldn't.  However, after approximately 5 minutes. it switches automatically to **Cordoned** state and all VMs are migrated to other nodes (es expected if the node was going to Maintenance mode) and Ceph RDB Pods are removed 

If I Manually **Uncordon** it,, Ceph RBD Pods are run again and VMs can run.. for 5 minutes,, when the Host goes again to Cordoned state.

Now I can run VMs there. and Ceph RBD pods are running fine.  However after 5 

**To Reproduce**
1. Remove the node dmz02 (I had sometimes to remove it using kubectl delete node dmz02)
2. Reinstall and add it again
3. dmz02 stays in **Cordoned** state

**Expected behavior**
DMZ02 should stay in Active state

**Support bundle**
[dmz02.zip](https://github.com/user-attachments/files/20670570/dmz02.zip)

[dmz01.zip](https://github.com/user-attachments/files/20670575/dmz01.zip)

[dmz03.zip](https://github.com/user-attachments/files/20670576/dmz03.zip)

[dmz04.zip](https://github.com/user-attachments/files/20670577/dmz04.zip)

[logs.zip](https://github.com/user-attachments/files/20670581/logs.zip)

[metadata.zip](https://github.com/user-attachments/files/20670584/metadata.zip)

[yamls.zip](https://github.com/user-attachments/files/20670586/yamls.zip)

**Environment**
 - Harvester ISO version: 1.5.0
 - Underlying Infrastructure:
4 x  Dell PowerEdge R730xd w/128 GB of RAM, 2xM.2 SATA SSD (for OS and Longhorn) + 12x3.5" HDD, 2x2.5" SSD (for Ceph-Rook)

**Additional context**

**Comment by w13915984028** [comment]
Like guessed, the cluster provisioning is in abnormal status, the repeated `Cordoned` is caused by the OnDeleting old machine.

```
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster

    - lastTransitionTime: "2025-06-10T09:49:16Z"
      message: configuring worker node(s) custom-8019c31ceff0,custom-91357ad65ba6
      reason: Waiting
      status: Unknown
      type: ControlPlaneReady

      - lastTransitionTime: "2025-06-09T10:59:18Z"
        message: |-
          * Machine custom-a3b368e81759:
            * Deleting: Machine deletion in progress since more than 15m, stage: WaitingForPreTerminateHook
        observedGeneration: 2848
        reason: NotReady
        status: "False"
        type: ControlPlaneMachinesReady
      - lastTransitionTime: "2025-06-10T09:49:58Z"
        message: |-
          * Machines custom-8019c31ceff0, custom-91357ad65ba6:
            * NodeHealthy: Waiting for CustomMachine to report spec.providerID
        observedGeneration: 2848
        reason: ReadyUnknown
        status: Unknown
        type: WorkerMachinesReady
      - lastTransitionTime: "2025-05-02T13:54:02Z"
        message: '* Machines custom-2cd24e0bf324, custom-a3b368e81759, custom-a9c82ff3ef40,
          ... (1 more): Condition UpToDate not yet reported'
        observedGeneration: 2848
        reason: UpToDateUnknown
        status: Unknown
        type: ControlPlaneMachinesUpToDate
      - lastTransitionTime: "2025-05-02T13:52:49Z"
        message: '* Machines custom-538feb0c7a6a, custom-8019c31ceff0, custom-91357ad65ba6,
          ... (1 more): Condition UpToDate not yet reported'
        observedGeneration: 2848
        reason: UpToDateUnknown
        status: Unknown
        type: WorkerMachinesUpToDate  
```

**Comment by w13915984028** [comment]
There are 4 nodes, but 8 machines; normally, they should be matched 1:1

old `dmz02` machine was not successfully deleted, and the re-joined `dmz02` was cordoned by old machine.

```
// dmz01: running


- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-2cd24e0bf324
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz01
  status:
    addresses:
    - address: 192.168.186.201
      type: InternalIP
    - address: dmz01
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-05-02T17:03:42Z"
      status: "True"
      type: Ready
...
    infrastructureReady: true
    lastUpdated: "2025-05-02T17:04:37Z"
    nodeInfo:
      architecture: amd64
      bootID: b957b32f-2679-4bb0-b124-a7f2a436d3f9
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: 9ea98c5df849ed819e835b166814fac3
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 00000000-0000-0000-0000-d05099c04014
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz01
      uid: 621d4d69-5ad1-4f1f-b9b0-785b7647182e
    observedGeneration: 3
    phase: Running            


// dmz02: running

  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-538feb0c7a6a
        namespace: fleet-local
      dataSecretName: custom-538feb0c7a6a-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-538feb0c7a6a
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz02
  status:
    addresses:
    - address: 192.168.186.202
      type: InternalIP
    - address: dmz02
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-06-10T05:29:52Z"
      status: "True"
      type: Ready
...
    infrastructureReady: true
    lastUpdated: "2025-06-10T05:30:22Z"
    nodeInfo:
      architecture: amd64
      bootID: 35d6dcf9-c16b-47be-87c6-aa07e0136d4d
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: b7b9566427b80f341c95c13d6847ff33
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 4c4c4544-0043-5810-8047-b1c04f483632
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz02
      uid: 480c8771-0bfb-40ff-a57b-075a9acebb9f
    observedGeneration: 3
    phase: Running    


// dmz04: running

  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-ee3e3ba5fea7
        namespace: fleet-local
      dataSecretName: custom-ee3e3ba5fea7-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-ee3e3ba5fea7
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz04
  status:
    addresses:
    - address: 192.168.186.204
      type: InternalIP
    - address: dmz04
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-05-02T15:58:54Z"
      status: "True"
      type: Ready
...
    infrastructureReady: true
    lastUpdated: "2025-05-02T15:59:24Z"
    nodeInfo:
      architecture: amd64
      bootID: cc35b2d1-18fe-4d4e-85ab-fe558b461446
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: 5214d3006f6bce2943dfa9766814eb96
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 4c4c4544-0044-4d10-804b-b4c04f483632
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz04
      uid: 113dac30-7474-4ca8-a3c0-551935e59c97
    observedGeneration: 3
    phase: Running
...     



// dmz03: running

  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-a9c82ff3ef40
        namespace: fleet-local
      dataSecretName: custom-a9c82ff3ef40-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-a9c82ff3ef40
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz03
  status:
    addresses:
    - address: 192.168.186.203
      type: InternalIP
    - address: dmz03
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-05-02T14:38:46Z"
      status: "True"
      type: Ready
...
    infrastructureReady: true
    lastUpdated: "2025-05-02T14:39:15Z"
    nodeInfo:
      architecture: amd64
      bootID: 991ef5d4-853f-43b3-995e-8255129fa8b4
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: 2e6982b408b0dc2e40182f6c6814d611
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 4c4c4544-004c-3910-8038-b8c04f4e4b32
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz03
      uid: 66d0ae28-c63c-4ad3-9e4e-9d1e5be92ec7
    observedGeneration: 3
    phase: Running




// custom-c61dc74310e6 dmz02, running


  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-c61dc74310e6
        namespace: fleet-local
      dataSecretName: custom-c61dc74310e6-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-c61dc74310e6
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz02
  status:
    addresses:
    - address: 192.168.186.202
      type: InternalIP
    - address: dmz02
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-06-10T09:48:12Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-06-10T09:48:12Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2025-06-10T09:48:12Z"
      status: "True"
      type: InfrastructureReady
    - lastTransitionTime: "2025-06-10T09:48:43Z"
      status: "True"
      type: NodeHealthy
    - lastTransitionTime: "2025-06-10T09:48:12Z"
      status: "True"
      type: PlanApplied
    - lastTransitionTime: "2025-06-10T09:49:16Z"
      status: "True"
      type: Reconciled
    infrastructureReady: true
    lastUpdated: "2025-06-10T09:48:43Z"
    nodeInfo:
      architecture: amd64
      bootID: 35d6dcf9-c16b-47be-87c6-aa07e0136d4d
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: b7b9566427b80f341c95c13d6847ff33
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 4c4c4544-0043-5810-8047-b1c04f483632
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz02
      uid: 967c1c28-36b2-4f4c-bc65-d37a59a8d211
    observedGeneration: 3
    phase: Running



// custom-8019c31ceff0  Provisioning

  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-8019c31ceff0
        namespace: fleet-local
      dataSecretName: custom-8019c31ceff0-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-8019c31ceff0
      namespace: fleet-local
    nodeDeletionTimeout: 10s
  status:
    bootstrapReady: true
...
    infrastructureReady: false
    lastUpdated: "2025-05-02T13:52:38Z"
    observedGeneration: 2
    phase: Provisioning
    v1beta2:
      conditions:
...


// custom-91357ad65ba6 Provisioning
 
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-91357ad65ba6
        namespace: fleet-local
      dataSecretName: custom-91357ad65ba6-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-91357ad65ba6
      namespace: fleet-local
    nodeDeletionTimeout: 10s
  status:
    bootstrapReady: true
    conditions:
...
    - lastTransitionTime: "2025-06-09T11:00:02Z"
      message: waiting for agent to check in and apply initial plan
      reason: Waiting
      status: Unknown
      type: Reconciled
    infrastructureReady: false
    lastUpdated: "2025-05-02T16:11:34Z"
    observedGeneration: 2
    phase: Provisioning
...



// custom-a3b368e81759, dmz02,  Deleting

  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-a3b368e81759
        namespace: fleet-local
      dataSecretName: custom-a3b368e81759-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-a3b368e81759
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://dmz02
  status:
    addresses:
    - address: 192.168.186.202
      type: InternalIP
    - address: dmz02
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-06-10T09:50:40Z"
      status: "True"
      type: Ready
...
    deletion:
      nodeDrainStartTime: "2025-06-09T10:59:17Z"
      waitForNodeVolumeDetachStartTime: "2025-06-09T10:59:56Z"
    infrastructureReady: true
    lastUpdated: "2025-06-09T10:59:18Z"
    nodeInfo:
      architecture: amd64
      bootID: 35d6dcf9-c16b-47be-87c6-aa07e0136d4d
      containerRuntimeVersion: containerd://2.0.4-k3s2
      kernelVersion: 5.14.21-150500.55.100-default
      kubeProxyVersion: v1.32.3+rke2r1
      kubeletVersion: v1.32.3+rke2r1
      machineID: b7b9566427b80f341c95c13d6847ff33
      operatingSystem: linux
      osImage: Harvester v1.5.0
      systemUUID: 4c4c4544-0043-5810-8047-b1c04f483632
    nodeRef:
      apiVersion: v1
      kind: Node
      name: dmz02
      uid: 1a16d77c-1fa6-4442-8ff0-11ce03e7761a
    observedGeneration: 4
    phase: Deleting
    v1beta2:
      conditions:
      - lastTransitionTime: "2025-06-09T10:27:36Z"
        message: "null"
        observedGeneration: 4
        reason: NotReady
        status: "False"
        type: Available
      - lastTransitionTime: "2025-06-09T10:59:18Z"
        message: '* Deleting: Machine deletion in progress since more than 15m, stage:
          WaitingForPreTerminateHook'
        observedGeneration: 4
        reason: NotReady
        status: "False"
        type: Ready
      - lastTransitionTime: "2025-05-02T13:53:42Z"
        message: "null"
        observedGeneration: 4
        reason: Ready
        status: "True"
        type: BootstrapConfigReady
      - lastTransitionTime: "2025-05-02T13:53:42Z"
        message: "null"
        observedGeneration: 4
        reason: Ready
        status: "True"
        type: InfrastructureReady
      - lastTransitionTime: "2025-06-10T09:50:00Z"
        message: "null"
        observedGeneration: 4
        reason: NodeHealthy
        status: "True"
        type: NodeHealthy
      - lastTransitionTime: "2025-06-10T09:48:32Z"
        message: "null"
        observedGeneration: 4
        reason: NodeReady
        status: "True"
        type: NodeReady
      - lastTransitionTime: "2025-05-02T13:53:42Z"
        message: "null"
        observedGeneration: 4
        reason: NotPaused
        status: "False"
        type: Paused
      - lastTransitionTime: "2025-06-09T10:59:18Z"
        message: 'Waiting for pre-terminate hooks to succeed (hooks: pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup)'
        observedGeneration: 4
        reason: WaitingForPreTerminateHook
        status: "True"
        type: Deleting
```
