### ISSUE TITLE
[BUG] Race Condition When Applying VM Import Manifests

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#8463]
### Describe the Bug

We currently whether that is Openstack Source or VMWare based can't just give Harvester a big manifest that contains all the credentials/locations and vms to import.

It will fail to process and reconcile everything all at once.

### To Reproduce

Provide a giant manifest for openstack like:
```
---
apiVersion: v1
kind: Secret
metadata: 
  name: mike-test-admin
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "admin"
  "domain_name": "default"
---
apiVersion: v1
kind: Secret
metadata: 
  name: mike-test-demo
  namespace: default
stringData:
  "username": "admin"
  "password": "testtesttest"
  "project_name": "demo"
  "domain_name": "default"
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: mike-admin
  namespace: default
spec:
  endpoint: "http://10.115.0.182/identity"
  region: "RegionOne"
  credentials:
    name: mike-test-admin
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: OpenstackSource
metadata:
  name: mike-demo
  namespace: default
spec:
  endpoint: "http://10.115.0.182/identity"
  region: "RegionOne"
  credentials:
    name: mike-test-demo
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: cirros-tiny
  namespace: default
spec: 
  virtualMachineName: "cirros-tiny"
  sourceCluster: 
    name: mike-demo
    namespace: default
    kind: OpenstackSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

Or provide a giant manifest for vmware like:
```
apiVersion: v1
kind: Secret
metadata: 
  name: mike-vsphere-credentials
  namespace: default
stringData:
  "username": "a"
  "password": "b"
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VmwareSource
metadata:
  name: mike-vcsim
  namespace: default
spec:
  endpoint: "https://some-place/sdk"
  dc: "PG Devlab"
  credentials:
    name: mike-vsphere-credentials
    namespace: default
---
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: test-efi-secure-buntu
  namespace: default
spec: 
  virtualMachineName: "test-efi-secure-buntu"
  networkMapping:
  - sourceNetwork: "vCenter-HA-Management"
    destinationNetwork: "harvester-public/vlan2011" 
  folder: "gmehta"
  sourceCluster: 
    name: mike-vcsim
    namespace: default
    kind: VmwareSource
    apiVersion: migration.harvesterhci.io/v1beta1
```

1. have enabled vm import controller addon
2. run either manifest
3. you'll be greeted with `The VM import spec is invalid`, in the pod for the vm-import-controller

### Expected Behavior

A single big manifest for all sources all credentials all vms to not be an issue.
We'd expect it to behave like auto-deploying RKE2 manifests, that it should be agnostic of the manifest items and work to reconcile all of them if all of them are applied/created at once.

### Support Bundle for Troubleshooting

N/A

### Environment

- Harvester version: v1.5.1-rc2
- Underlying Infrastructure (e.g., Baremetal with Dell PowerEdge R630): bare-metal & qemu/kvm

### Additional context

The workaround is really easy, but it's a strange behavior.

What I believe is happening is this:
1. the vmwaresource or openstacksource is hitting a race condition
2. it is not "ready" quick enough and fails briefly before succeding
3. when it's failing it's causing some sort of downstream issue, so the VirtualMachineImport items are tanking and throwing an unhelpful error of `The VM import spec is invalid`

### Workaround and Mitigation

# Important
The work-around is straight forward.
In your big manifest, comment out the chunks of the VirtualMachineImport items.
Apply your manifest.
Wait a little bit for both `OpenStackSource` and `VMWareSource` to be ready.
Un-comment the VirtualMachineImport items.
You'll be able to have it succeed, if you the "re-apply" or "re-create" `kubectl create -f manifest.yaml`.

**Comment by ibrokethecloud** [comment]
we can make a minor change to requeue/retry until source is ready rather than marking the import as failed

**Comment by irishgordo** [comment]
@ibrokethecloud perhaps there'd try to be a limit to the requeue/retry? - marking imports as failed is good for the ones that truly did fail (and not trying to indefinitely retry with failed imports) ... so that it still upholds:

> change behaviour of vm-import-controller to disable retry for failed vm-import-controller requests if export VM fails. This is to avoid triggering multiple exports on source environment

From: https://github.com/harvester/vm-import-controller/pull/31#issue-2314287826

I'm not sure if there is conflicting interests between those elements...

**Comment by albinsun** [comment]
Test PASS, close as fixed.


## Environment
* `harvester-v1.7.0-dev-20250914`
  * Profile: Single node AMD64 Bare-metal HPE ProLiant DL360 
  * ui-source: `Auto`


## Test Steps
1. <details>
   <summary> Enable the <b>vm-import-controller</b> add-on
   </summary>

   <img width="1569" height="770" alt="Image" src="https://github.com/user-attachments/assets/3def1458-a60f-4876-a0a8-6919532e0872" />
   </details>

1. <details>
   <summary> Prepare <i>giant_manifest_openstack.yaml</i> 
   </summary>

    ```
    # cat giant_manifest_openstack.yaml 
    ---
    apiVersion: v1
    kind: Secret
    metadata: 
      name: mike-test-admin
      namespace: default
    stringData:
      "username": "admin"
      "password": "testtesttest"
      "project_name": "admin"
      "domain_name": "default"
    ---
    apiVersion: v1
    kind: Secret
    metadata: 
      name: mike-test-demo
      namespace: default
    stringData:
      "username": "admin"
      "password": "testtesttest"
      "project_name": "demo"
      "domain_name": "default"
    ---
    apiVersion: migration.harvesterhci.io/v1beta1
    kind: OpenstackSource
    metadata:
      name: mike-admin
      namespace: default
    spec:
      endpoint: "http://10.115.0.182/identity"
      region: "RegionOne"
      credentials:
        name: mike-test-admin
        namespace: default
    ---
    apiVersion: migration.harvesterhci.io/v1beta1
    kind: OpenstackSource
    metadata:
      name: mike-demo
      namespace: default
    spec:
      endpoint: "http://10.115.0.182/identity"
      region: "RegionOne"
      credentials:
        name: mike-test-demo
        namespace: default
    ---
    apiVersion: migration.harvesterhci.io/v1beta1
    kind: VirtualMachineImport
    metadata:
      name: cirros-tiny
      namespace: default
    spec: 
      virtualMachineName: "cirros-tiny"
      sourceCluster: 
        name: mike-demo
        namespace: default
        kind: OpenstackSource
        apiVersion: migration.harvesterhci.io/v1beta1
    ```
   </details>

1. <details>
   <summary> Should be able to import bulk related resources (1 image, volume and VM)
   </summary>

   * Before
     <img width="1569" height="770" alt="Image" src="https://github.com/user-attachments/assets/f05ba15a-07cd-4a87-9033-1b1441ac4353" />
     <img width="1569" height="356" alt="Image" src="https://github.com/user-attachments/assets/9752e848-8142-469d-bccb-4ea230cecdce" />
     <img width="1569" height="356" alt="Image" src="https://github.com/user-attachments/assets/fcb7af64-bb54-40f7-9f09-ceff32909e3e" />

   * `kubectl create -f giant_manifest_openstack.yaml`
     <img width="1569" height="162" alt="Image" src="https://github.com/user-attachments/assets/081fb21e-3332-443c-84f3-368b4ccc77fd" />
     <img width="1569" height="75" alt="Image" src="https://github.com/user-attachments/assets/e6d9c2f1-0cf2-4401-8386-586ec50c699c" />


   * `kubectl -n harvester-system logs deployment/harvester-vm-import-controller | grep -i creating`
     <img width="1569" height="318" alt="Image" src="https://github.com/user-attachments/assets/c69f1b0a-ce14-4081-80c9-da3f4b5b4da0" />


   * 1 images named cirros-tiny
     <img width="1569" height="361" alt="Image" src="https://github.com/user-attachments/assets/0adeca47-1a2f-4a17-a983-42571717d261" />

   * 1 volume
     <img width="1569" height="380" alt="Image" src="https://github.com/user-attachments/assets/7ca26b78-f35e-496f-8dec-3526c618baa7" />

   * 1 VM be imported and running on Masquerade Network (embedded non VLAN network)
     <img width="1569" height="554" alt="Image" src="https://github.com/user-attachments/assets/f34ceace-9f30-4fcb-9675-3d70c87b9f67" />
     <img width="1569" height="554" alt="Image" src="https://github.com/user-attachments/assets/c2d1cc96-bd57-4a4f-ac52-487d4cc9dcd1" />
   </details>
