### ISSUE TITLE
[BUG] Harvester UI Accessible Without Login When Using Ingress with FQDN

### ISSUE THREAD

**Issue by kingnarmer** [harvester/harvester#8511]
### Describe the Bug

I'm attempting to expose the Harvester management UI using an Ingress and DNS setup. After configuring a hostname (FQDN) and successfully provisioning a TLS certificate using cert-manager and externalDNS, I can access the UI at https://harvester.k8s.domain.tld , but it logs me in automatically without prompting for a username or password.

**Environment**

    Harvester version: 1.5.0
	
    Kubernetes distro/version: 1.32.3+rke2r1

    Rancher version: 2.11.2

**What I Did**

   * Installed and configured:

        cert-manager (using the letsencrypt-prod cluster issuer)

        externalDNS (auto-creating records for Ingress resources)

   * Created an Ingress to expose the Harvester UI via FQDN, modeled after rancher-expose.

**Ingress YAML (simplified)**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-ui
  namespace: harvester-system
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: harvester.k8s.domain.tld
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: harvester.k8s.domain.tld
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: harvester
                port:
                  number: 8443
  tls:
    - hosts:
        - harvester.k8s.domain.tld
      secretName: harvester-ui-tls
```

### Expected Behavior

I expect to be prompted for credentials when accessing the Harvester UI via the FQDN, just like when accessing it directly by IP or hostname. 

### Support Bundle for Troubleshooting

Will send it using other means. 

### Environment

    Harvester version: 1.5.0
	
    Kubernetes distro/version: 1.32.3+rke2r1

    Rancher version: 2.11.2

### Additional context

Tried another variation of the ingress without success

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-ui
  namespace: harvester-system
  annotations:
    kubernetes.io/ingress.class: nginx
    externalDNS: "true"
    external-dns.alpha.kubernetes.io/hostname: harvester.k8s.domain.tld
    external-dns.alpha.kubernetes.io/ttl: "300"
    external-dns.alpha.kubernetes.io/target: "10.96.118.17"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: harvester.k8s.domain.tld
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: harvester
                port:
                  number: 8443
  tls:
    - hosts:
        - harvester.k8s.domain.tld
      secretName: harvester-ui-tls
```
