### ISSUE TITLE
[FEATURE] Show `Kernel` and `Container Runtime` on host deatil page

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#856]
**Is your feature request related to a problem? Please describe.**

If this information is displayed, it can help identify problems

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/15064560/117951071-62b45480-b346-11eb-9fb3-05a92900056e.png)

**Describe alternatives you've considered**

**Additional context**

These info can be found on node's `status.nodeInfo`

```yaml
status:
  nodeInfo:
    architecture: amd64
    bootID: ff2a66ed-023d-4953-8128-2fde4a94ab13
    containerRuntimeVersion: docker://20.10.6
    kernelVersion: 5.4.118-1.el7.elrepo.x86_64
    kubeProxyVersion: v1.20.6
    kubeletVersion: v1.20.6
    machineID: 408d57e201554fdf867323caba0fecf7
    operatingSystem: linux
    osImage: CentOS Linux 7 (Core)
    systemUUID: 7fed4d56-6103-2d44-72b1-17bfc42e20f5
```
