### ISSUE TITLE
After the move to block vol. mode as the default in v0.2.0 volume snapshots are not working with CDI

### ISSUE THREAD

**Issue by larssb** [harvester/harvester#877]
**Describe the bug**
I'm using [KCLI](https://github.com/karmab/kcli) to deploy VM's and K3s clusters on-top of Harvester. KCLI integrates with KubeVirt by way of the kubeconfig one can pull out from an installed Harvester cluster.
In 0.1.0 of Harvester CDI cloning worked without issues. In 0.2.0 it doesn't.

**To Reproduce**
1. Setup Harvester v0.2.0
1. [Install KCLI](https://kcli.readthedocs.io/en/latest/#installation)
1. Configure KCLI to use the Harvester platform:
  1. [Here's how](https://kcli.readthedocs.io/en/latest/#kubevirt)
1. Execute `kcli download image ubuntu2004` to download the Ubuntu 20.04 OS img
1. Execute `kcli create vm -i ubuntu2004`

> The above should request for a VM named something randomly generated to be created on the Harvester platform. Part of that process entails requesting CDI to create a clone of the OS img PVC ....
A datavolume is created and a volume snapshot as well. However, executing `kubectl describe ...` on the volumesnapshot the newest event is  `Normal  CreatingSnapshot  41m   snapshot-controller  Waiting for a snapshot default/RANDOM_NAME to be created by the CSI driver.` and nothing more happens.

It can potentially be reproduced by just executing:

```yaml
kubectl create -f - <<EOF
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
 name: "test-clone"
spec:
 pvc:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 25Gi
   volumeMode: Block
 source:
   pvc:
     name:      ubuntu2004
     namespace: default
EOF
```

After one have downloaded the ubuntu2004 image with *KCLI*. The above DataVolume will create a volumesnapshot request that will also just hang and do nothing.

---

The initial symptom that I exeperienced/saw was the following err. in the CDI deployment pod, the kubernetes events and elsewhere: `the object has been modified; please apply your changes to the latest version and try again` ... but that's just a symptom as I've later found out.

**Expected behavior**
That volume snapshots are working with Longhorn now that Longhorn seems to advertise that it does so. Because, the KubeVirt CDI component wouldn't try to use smart cloning and volume snapshots if the CSI driver wasn't advertising it.

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
   - Two Dell PowerEdge R710's
   - One HP ProLiant G9

**Additional context**
Slack RancherLabs Harvester channel debugging thread > https://rancher-users.slack.com/archives/C01GKHKAG0K/p1621182290393100

Slack Kubernetes virtualization channel debugging thread > https://kubernetes.slack.com/archives/C8ED7RKFE/p1621161501370600

----

Looking forward to hearing from the project. And let me know if I need to elaborate further on xyz 👍
