### ISSUE TITLE
failed to upload the vm image when size is over 5G or plus

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#88]
failed to upload a large image file to the Minio server
```
 conditions:
  - lastUpdateTime: "2020-08-28T10:36:12Z"
    message: started image importing
    reason: Your proposed upload size ‘6600930864’ exceeds the maximum allowed object
      size ‘5368709120’ for single PUT operation.
    status: "False"
    type: imported
  downloadUrl: ""
  downloadedBytes: 1211191827
  progress: 18
```
