### ISSUE TITLE
[BUG] Kubevirt patch version 0.40.0-hp-0 fails to create VM

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#894]
**Describe the bug**

When trying to create a image template VM with Kubevirt version 0.40.0-hp-0 it fails
**To Reproduce**
1. Setup Kubevirt patch version on Rancher
2. Create new VM in harvester with image template
3. Define default password and SSH key in cloud config
3. Click create
**Expected behavior**

It should create
**Support bundle**

[harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-21T17-42-59Z.zip](https://github.com/harvester/harvester/files/6524436/harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-21T17-42-59Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head

 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL360G9

**Additional context**
![Greenshot 2021-05-21 10 44 13](https://user-images.githubusercontent.com/83787952/119182602-f9100680-ba27-11eb-8fff-0c711182e566.png)

**Comment by yasker** [comment]
@guangbochen can someone take a look at this?

**Comment by guangbochen** [comment]
@ngildersleeveSUSE which image and template are u using for the validation, can u please check if it works without replacing the kubevrit img first.

The image and hot-plugin feature works on my custom v0.2.0 environment, the validation steps are:
1. replace kubevirt with patched `0.40.0-hp-0` image
1. enable the hotVolumePlugin feature of kubevirt, refer to https://github.com/harvester/harvester/issues/283#issuecomment-800843117
1. create a VM image e.g with ubuntu image
1. Create a volume on the Volumes page
1. Attach the volume via API call or my WIP change to virtctl.
1. The new-created volume should be available in the instance.
1. Detaching volume works too.

```
status:
  volumeStatus:
  - name: cloudinitdisk
    target: vdb
  - name: disk-0
    target: vda
  - hotplugVolume:
      attachPodName: hp-volume-qxw8g
      attachPodUID: 98681def-a8f9-4168-8f45-d5f0477a6531
    message: Successfully attach hotplugged volume foo to VM
    name: foo
    phase: Ready
    reason: VolumeReady
    target: sda
```

However, the live-migration is still not supported yet with this custom image.
```
admission webhook "migration-create-validator.kubevirt.io" denied the request: Cannot migrate VMI, Reason: HotplugNotLiveMigratable, Message: VMI has hotplugged disks
```
