### ISSUE TITLE
[BUG] harvester pod error with helm install

### ISSUE THREAD

**Issue by brunnels** [harvester/harvester#899]
I get the following error from the harvester pods after installing in existing k3os cluster v1.20.6+k3s1 with longhorn already installed:

```level=fatal msg="failed to create harvester server: Failed to create virtualMachineTemplate harvester-system/iso-image-base-template: VirtualMachineTemplate.harvesterhci.io \"iso-image-base-template\" is invalid: spec.defaultVersionId: Invalid value: \"null\": spec.defaultVersionId in body must be of type string: \"null\""```

helm install command:
```
deploy/charts/harvester❯ helm install harvester . --namespace harvester-system \
--set longhorn.enabled=false,multus.enabled=true --create-namespace
```

**Comment by gitlawr** [comment]
What's the Harvester/Chart version?
Will harvester pods recover or they always crash?

**Comment by brunnels** [comment]
Using current master branch commit dfeedb83daf8b3cebe6a5c66696b55918b0ec2ca

I set replicas for harvester to 0 before I created the issue and just set back to 3.  Same errors in the logs and they're all in CrashLoopBackOff again now.

**Comment by gitlawr** [comment]
hmm, I'm not able to reproduce by:
1. install k3os v0.20.6-k3s1r0
2. install longhorn
3. install harvester

Did it happen before you scale harvester to 0?
Do you have other workloads in your Kubernetes cluster?
Can you show the output of
```
kubectl get vmtemplate -n harvester-system && kubectl get crd virtualmachineimages.harvester.cattle.io -o yaml
```

**Comment by brunnels** [comment]
I have lots of other workloads.  I got the error right after installing.  

The only thing weird I did was install once, realize it was starting pods on my masters, did helm uninstall, removed the master tolerations from the harvester-network-controller and multus chart values, did helm install again.

I don't have that crd for some reason.

**Comment by brunnels** [comment]
I'm spinning up another cluster to try fresh

**Comment by brunnels** [comment]
- New k3s cluster, 1 master, 1 worker.  
- kube-vip daemonset for the k8s api (because I normally do HA) and to be service load balancer
- longhorn installed via chart and configured as default storageclass
- traefik 2 installed via chart with dynamic pvc config to ensure longhorn is working
- IngressRoutes added for traefik and longhorn dashboards and I can access both.

harvester installed with values:
```
longhorn:
  enabled: false
multus:
  enabled: true
  tolerations: []
harvester-network-controller:
  tolerations: []
```
using these commands:
```
git clone https://github.com/harvester/harvester
cd harvester/deploy/charts/harvester
helm install harvester . --namespace harvester-system -f cv.yml --create-namespace
```

Same error after letting it run for a half hour to ensure everything is up.
```time="2021-05-26T20:28:40Z" level=fatal msg="failed to create harvester server: Failed to create virtualMachineTemplate harvester-system/iso-image-base-template: VirtualMachineTemplate.harvesterhci.io \"iso-image-base-template\" is invalid: spec.defaultVersionId: Invalid value: \"null\": spec.defaultVersionId in body must be of type string: \"null\""```

```
❯ kubectl get vmtemplate -n harvester-system && kubectl get crd virtualmachineimages.harvester.cattle.io -o yaml

No resources found in harvester-system namespace.
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "virtualmachineimages.harvester.cattle.io" not found
```

k3os master config is:
```
k3os:
  install:
    device: /dev/sda
  k3s_args:
  - server
  - "--tls-san=10.0.0.3"
  - "--disable=servicelb,traefik,local-storage,metrics-server"
  - "--kube-proxy-arg=ipvs-strict-arp"
  - "--disable-cloud-controller"
  - "--cluster-init"
  taints:
  - node-role.kubernetes.io/master:NoSchedule
```
