### ISSUE TITLE
[BUG] Can't restore from backup

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#912]
**Describe the bug**

You can't restore from backup with replace as an option
**To Reproduce**
1. Create a backup target with S3
2. Create a new VM from live image
3. Make some modifications to the filesystem, like create a file
4. Make a backup of the VM
5. Wait for the backup to complete
6. Turn off the VM
7. Restore the backup with replace as the option

**Expected behavior**

1. The restore should complete and the VM should work

**Support bundle**

[harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-28T23-20-14Z.zip](https://github.com/harvester/harvester/files/6563668/harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-28T23-20-14Z.zip)

**Environment:**
 - Harvester ISO version: master-4997d634-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL160G9

**Additional context**
It looks like the volume fails to attach. This happens both with create new, and with replace. This was working on `v0.2.0`.
![Greenshot 2021-05-28 16 19 50](https://user-images.githubusercontent.com/83787952/120050102-06e9fc80-bfd1-11eb-97cc-172366b99c68.png)
![Greenshot 2021-05-28 16 20 00](https://user-images.githubusercontent.com/83787952/120050106-081b2980-bfd1-11eb-8ce7-acf7a96952c5.png)

**Comment by guangbochen** [comment]
according to the log the restoring is still in progress and the time will be dependens on the volume size and network performance, can u test using a smaller volume size images first, and if u like to validate larger images which is over 10G, then u maybe check on the lognhorn UI as it will inlcues the progress status of volume restoring(this is something we would like to add in the harvester side in the future).
```
  spec:
    size: 10737418240
    frontend: blockdev
    frombackup: s3://ngildersleeve-harvester@us-west-2/?backup=backup-6eee31ad90bf4d5d&volume=pvc-d5d5a0a8-3bc6-4d9f-a93b-8730b69f4292
    numberofreplicas: 3
    datalocality: disabled
    stalereplicatimeout: 30
    nodeid: ""
    migrationnodeid: ""
    engineimage: longhornio/longhorn-engine:v1.1.1
    recurringjobs: []
    backingimage: image-czjfv
    standby: false
    diskselector: []
    nodeselector: []
    disablefrontend: false
    revisioncounterdisabled: false
    lastattachedby: ""
    accessmode: rwx
    migratable: true
    baseimage: ""
  status:
    ownerid: hpd11s19
    state: attached
    robustness: degraded
    currentnodeid: hpd11s19
    currentimage: longhornio/longhorn-engine:v1.1.1
    kubernetesstatus:
      pvname: pvc-8d5dcb14-7757-43fe-8c85-15e721c0ae9f
      pvstatus: Bound
      namespace: default
      pvcname: restore-test-backup2-1-be13afd6-07f1-43fa-a630-adaff02bef66-rootdisk
      lastpvcrefat: ""
      workloadsstatus:
      - podname: virt-launcher-test-backup2-82d4k
        podstatus: Pending
        workloadname: test-backup2
        workloadtype: VirtualMachineInstance
      lastpodrefat: ""
    conditions:
      restore:
        type: restore
        status: "True"
        lastprobetime: ""
        lasttransitiontime: "2021-05-28T23:14:39Z"
        reason: RestoreInProgress
        message: ""
```
