### ISSUE TITLE
vm lauched in rancher cluster with default canal/calico cni can't be access 

### ISSUE THREAD

**Issue by aiwantaozi** [harvester/harvester#94]
vm use masquerade and pod network deployed in cluster created by rke, with default cni configure, find the VM can't be access from host, and can't ping host inside the vm.

vm configure:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu5-pod-masquerade
  label:
    test: ubuntu5-pod-masquerade
spec:
  dataVolumeTemplates:
    - metadata:
        name: ubuntu5-masq-disk
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        source:
          http:
            url: http://172.16.0.254:8080/ubuntu-18.04-server-cloudimg-amd64.img
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
              bootOrder: 1
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2048M
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: ubuntu5-masq-disk
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
          name: cloudinitdisk
```
cni configure 
```
root@gc-harvester-1:/home/root# cat /etc/cni/net.d/10-canal.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "WARNING",
      "datastore_type": "kubernetes",
      "nodename": "xx.xx.221.77",
      "mtu": 1450,
      "ipam": {
          "type": "host-local",
          "subnet": "usePodCidr"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}
```

check IP forward in pod:
cat `/proc/sys/net/ipv4/ip_forward` is 0 , find that IP forwarding isn't enable

base on this kubevirt [issue](https://github.com/kubevirt/kubevirt/issues/2942), need to enable IP forwarding for cni, after enable cni IP forwarding, create a new vm with same configure, can access the new vm from host, and can ping host inside the vm.

cni configure after enabling IP forwarding
``` 
root@gc-harvester-1:/home/root# cat /etc/cni/net.d/10-canal.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "WARNING",
      "datastore_type": "kubernetes",
      "nodename": "xx.xx.221.77",
      "mtu": 1450,
      "ipam": {
          "type": "host-local",
          "subnet": "usePodCidr"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
      },
      "container_settings": {
	  "allow_ip_forwarding": true
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}
```
