### ISSUE TITLE
[FEATURE] Kubevirt Annotations in the UI

### ISSUE THREAD

**Issue by dgiebert** [harvester/harvester#942]
**Is your feature request related to a problem?**
We are testing Harvester to spawn CoreOS nodes with Ignition.
This can be done using a ConfigMap to enable the support: 
```yaml
apiVersion: v1
data:
  feature-gates: ExperimentalIgnitionSupport,LiveMigration
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: harvester-system

```
And an annotation that has to be patched into either into the node or the template using kubectl.
Added the following annotation, skipping the content here:
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineTemplateVersion
spec:
    template:
      metadata:
        annotations:
          kubevirt.io/ignitiondata: |
            {}
```

**Describe the solution you'd like**
- **Harvester:** In Advanced Options provide a section to a add annotations
- **Rancher:** Extend the Labels section to also contain annotations
