### ISSUE TITLE
[FEATURE] Allow configuration of custom certificate and LetsEncrypt via Addon

### ISSUE THREAD

**Issue by cjohn001** [harvester/harvester#9824]
Hello @guangbochen 
I have seen that the yaml installs cert-manager. In the README you are writing that the cluster uses a self signed cert. Is it also possible to configure cert-manager to use lets-encrypt with this chart? And in case, are you aware of a description how to do it?

Thanks for your help!

Best regards 
  Christoph

**Comment by cjohn001** [comment]
@guangbochen 
addon works by pressing a single button, great!. It would be perfect if you could add an additional explanation on how to replace the initial certificate with a self signed one. I see 3 different certificates in the local cluster and are not sure if I can change them without breaking things, and which one is responsible for what kind of feature. Looks like the certs are CA certs, hence they hold both, private and a public signature and need to be generated as ca certificate? Which format is required for it and how could I create a self signed one?

I have also seen that the chart already installs certmanager. Is their an easy way to use letsencrypt together with the plugin? Would be great if you could provide a description on how this could be done. Thanks for the great addon!

<img width="427" alt="Bildschirmfoto 2023-10-10 um 17 22 52" src="https://github.com/harvester/harvester/assets/43253483/4e368f68-6ef0-4210-b0ea-b1e71d2555d6">

**Comment by ER-EPR** [comment]
@cjohn001 
According to the rancher documentation. 
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options
You can change the following three settings to obtain a letsencrypt SSL.
<html>
<body>


Option | Default Value | Description
-- | -- | --
ingress.tls.source | "rancher" | string - Where to get the cert for the ingress. - "rancher, letsEncrypt, secret"
letsEncrypt.email | " " | string - Your email address
letsEncrypt.environment | "production" | string - Valid options: "staging, production"


</body>
</html>
To apply those settings you need to edit the addon config yaml, by click the three dot to the right of the rancher-vcluster addon, and click the edit yaml.
Scroll to the bottom you will see configurations for rancher, which you can change them to something like the following:
(for "letsEncrypt.environment: production" you may test "letsEncrypt.environment: staging" first)

```
       ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/stable/
          chart: rancher
          version: {{ .Values.rancherVersion }}
          set:
            ingress.tls.source: letsencrypt
            letsEncrypt.email: "youremail@yourdomain.com"
            letsEncrypt.environment: production
            hostname: {{ .Values.hostname }}
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: {{ .Values.bootstrapPassword }}
          helmVersion: v3
```
